### ISSUE TITLE
No converter available for genOta - implement an ignore converter?

### ISSUE THREAD

**Issue by Kryzek** [Koenkk/zigbee-herdsman-converters#1015]
Should we have fz.ignore_basic_report (https://github.com/Koenkk/zigbee-herdsman-converters/blob/ebbeec638c92498694de50bdb248153769991612/converters/fromZigbee.js#L4055)-style ignore converter i.e. `fz.ignore_ota_report` for devices that support OTA updates?

Currently these devices cause
`No converter available for '4713407' with cluster 'genOta' and type 'commandQueryNextImageRequest' and data '{"fieldControl":0,"manufacturerCode":4456,"imageType":12545,"fileVersion":285802498}'
`-messages in the debug log.

**Comment by Koenkk** [comment]
There are much more devices which will send these `commandQueryNextImageRequest` messages, not only the ones which supports ota, e.g. hue bulbs. 

In the end it's only a cosmetic things (functional wise it doesn't change anything), therefore it's also logged as debug. Let's not add it for now.

**Comment by sjorge** [comment]
@Koenkk didn't this get resolved by not printing the message anymore on current dev?

**Comment by Koenkk** [comment]
Yes, closing this thanks!
