### ISSUE TITLE
RTCGQ11LM has same value for illuminance and illuminance_lux

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee-herdsman-converters#1017]
https://github.com/Koenkk/zigbee-herdsman-converters/blob/12c37f740c223aab6b3df5badfa8b24a4415617f/converters/fromZigbee.js#L613

Since RTCGQ11LM is returning lux not illuminance in the msIlluminanceMeasurement reporting, we just copy it to illuminance_lux (great)...

However illuminance is not converted to the other format, now if you have other sensors too _lux will be lux everywhere but illuminance will not be illuminance for the RTCGQ11LM, perhaps we should do the reverse conversion... even if we lose some accuracy.

**Comment by Koenkk** [comment]
Doing the reverse calculation is not possible as its a breaking change

**Comment by sjorge** [comment]
Then that should atleast be documented somewhere for this device.

As for all others _lux is the lux value and the other is not. It breaks POLA that the normal one is different for only one device.
