### ISSUE TITLE
Please add temperature for Xiaomi QBKG12LM

### ISSUE THREAD

**Issue by Jiri72** [Koenkk/zigbee-herdsman-converters#1020]
Hi, I realized that mqtt message for Xiaomi QBKG12LM contains data for temperature, but this values is not advertised to homeassistant:
{"power":0,"consumption":0.32,"temperature":16,"linkquality":34,"last_seen":"2020-02-26T20:44:09+01:00","state_left":"OFF","state_right":"OFF"}

**Comment by Koenkk** [comment]
added in latest zigbee2qmtt dev branch, thanks!
