### ISSUE TITLE
Xiaomi sensor, wrong battery percentage

### ISSUE THREAD

**Issue by dzungpv** [Koenkk/zigbee-herdsman-converters#1036]
I test some Xiaomi temp sensor:WSDCQ01LM and WSDCQ11LM , battery report wrong value. always show 100%, but Siaomi original with  report 7% and 47% show i guest it wrong for all xiaomi device.

**Comment by Koenkk** [comment]
The sensors only report it's voltage, based on this voltage a calculation is done: https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/converters/fromZigbee.js#L612 .  Maybe this can be improved somehow.

**Comment by dzungpv** [comment]
@Koenkk it wrong for voltage too, i take out the battery and check with multimeter, one 2.8V but log from z2m is 3.0v

**Comment by Koenkk** [comment]
@dzungpv what voltage does the sensor report? (via sniffing)

**Comment by dzungpv** [comment]
> 
> 
> @dzungpv what voltage does the sensor report? (via sniffing)

Sniffing tool could not decode that data, i measure directly

**Comment by Koenkk** [comment]
So the question is what the sensor actually reports, if the sensors reports the wrong voltage we cannot correct it.

**Comment by dzungpv** [comment]
@Koenkk No, original Xiaomi hub correct and i verify it physically, it is report correct voltage and percentage.
Like 2.8V they will report 7%, but z2m report 3.0v and 100%

**Comment by dzungpv** [comment]
I check the same sensor, first connect to xiaomi app and hub and then the same sensor connect to z2m

**Comment by dzungpv** [comment]
![ba1](https://user-images.githubusercontent.com/10563561/75887584-994a3180-5e5c-11ea-8644-8ff81e5b21f0.png)
![ba2](https://user-images.githubusercontent.com/10563561/75887591-9b13f500-5e5c-11ea-9a08-c987232733c8.png)
@Koenkk they calculate like this. Those device i use HA integrated with original xiaomi API

**Comment by dzungpv** [comment]
@Koenkk i measure new batterry, it about 3.2V

**Comment by Koenkk** [comment]
I wonder if the battery percentage is actually included in the `genBasic` struct of the devices. Currently we parse the voltage from it and based on that calculate the percentage (here stuff seems to be inaccurate). @dzungpv can you figure this out if any of the values in this struct match the battery level? (https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/converters/fromZigbee.js#L605)

**Comment by dzungpv** [comment]
@Koenkk i will try

**Comment by dzungpv** [comment]
@Koenkk After check some xiaomi sensor. I found that it only report battery each in **about 10 minute** (even press button it not update immediately after change battery).
So our decode still work fine.
But the problem with percentage calculator. I see that you fix it. So i close this issue

**Comment by dzungpv** [comment]
@Koenkk I reopen this issue, because problem not solve.
With my statics, original xiaomi hub report those value (home assistant component read value directly from local xiaomi hub):

Voltage Percent
3.0  41
3.04  47
3.02  45
3.02  43
3.04  49
3.0  39
3.02  45
2.82  3
3.1 61
3.12 65

So seem that xiaomi may  wrong about battery percent, because 3.12 is a new Panasonic CR2032 i replace and check after 12 hours, so it could be 99 percent

**Comment by Koenkk** [comment]
So the Xiaomi gateway itself is wrong about it?

**Comment by dzungpv** [comment]
@Koenkk Both us and Original xiaomi wrong about battery percent.
You can check your sensor, about 1 year and it still 100%, it wrong. I read in the project may use min 2.4 and max 3.2v for lithium percentage calculate like code here: https://github.com/Koenkk/zigbee-herdsman-converters/blob/bbb73a183eeb47de99d10399c6b514a0c4d6e152/converters/fromZigbee.js#L740

**Comment by dzungpv** [comment]
![bat_sens](https://user-images.githubusercontent.com/10563561/77883287-018a0880-728d-11ea-8bf5-0d2f2bac8856.png)
@Koenkk i have install new smoke sensor, they report 97% so for Xiaomi they may count 100% at 3.3v

**Comment by Koenkk** [comment]
@dzungpv what does the Xiaomi hub show now?

**Comment by Koenkk** [comment]
So current data (also added measurement from @flouck)

- 3.29 = 99%
- 3.005 = +- 60%

I we can add a few more measurement we can determine the correct function.

**Comment by flouck** [comment]
Thank you! I think it's a good approach. Maybe we can ask more people in the Home Assistant community on the zigbee2mqtt main thread?

**Comment by exetico** [comment]
Almost all my sensors/buttons/whatever are reporting unknown or 100. Only a single on, is reporting 37.

Here's my dump:
sensor.0x00158d0001d66cdf_battery 	100
sensor.0x00158d0001d672e5_battery 	100
sensor.0x00158d0001f3ac20_battery 	unknown
sensor.0xccccccfffe37baad_battery 	unknown
sensor.aqara1_battery 				unknown
sensor.aqara2_battery 				37
sensor.aqara_sensor1_battery 		unknown
sensor.aqara_sensor2_battery 		unknown
sensor.mijia1_battery 				unknown
sensor.mijia2_battery 				unknown
sensor.mijia_sensor1_battery 			unknown
sensor.switch3_mijia_battery 			unknown
sensor.switch4_mijia_battery 			unknown
sensor.switch5_mijia_battery 			unknown
sensor.switch6_mijia_battery 			unknown
sensor.switch8_mijia_battery 			unknown
sensor.switch9_mijia_battery 			100

What can i do, to help? Normally it's reporting values, that actually looks (at least) somewhat correct :-)

**Comment by Kosygor** [comment]
I also have similar issue. My MCCGQ01LM Aquara for sensors are reporting always 100% battery and voltage between 3015 and 3025. Today i have drained one of the batteries to 2.8 V and there was no update. Can I at least provide some data to help with solving this issue ?

**Comment by Smiggel** [comment]
Had The same issue here too with the door sensor. Suddenly stopped working, while battery was at 100%. Never noticed that it was almost empty and stopped working.

Will there be an update about this?

**Comment by larod241** [comment]
Issue is still relevant

**Comment by verstrepeng** [comment]
I just migrated from ZHA to Z2M. Have a bunch of WSDCGQ11LM Aquara sensor, which were on different levels between 60% and 95%. Now in Z2M they are all at 100% or N/A so this isn't correct. I don't have a xiaomi bridge to compare...

**Comment by verstrepeng** [comment]
Reading a bit of technical lecture, it's not so easy with these batteries:
[https://uncannier.com/cr2032-lithium-battery-charge-level-measurement/](https://uncannier.com/cr2032-lithium-battery-charge-level-measurement/)
But to make it simple: 3.1V or anything above can be reported as 100% and 2.7V or anything below can be reported as 0% ; values in-between can be simplified as linear interpolation. 
E.g.: 3.0V -> 75% [(https://www.johndcook.com/interpolator.html)](https://www.johndcook.com/interpolator.html)

**Comment by Koenkk** [comment]
Lets continue this in https://github.com/Koenkk/zigbee2mqtt/issues/8499
