### ISSUE TITLE
Bticino K4027C shutter switch support

### ISSUE THREAD

**Issue by blackwiz4rd** [Koenkk/zigbee-herdsman-converters#1057]
Hi, I'd like to add support for the K4027C. The [K4003C](https://github.com/Koenkk/zigbee2mqtt/issues/2626) was already added to zigbee2mqtt. It seems like there is a Legrand product which could be similar to the K4027C.
The manual is [here](https://catalogo.bticino.it/app/webroot/low_res/496319_496357_F02730IT_00.pdf). The switch has 3 positions: pause, up, down.

Zigbee2mqtt has recognized the switch:
`2020-03-11 16:28:33: Device 'shutter_xxx' with Zigbee model ' Shutter SW with level control' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html`

I was thinking of replicating this similar product's configuration for testing:
```
{
        zigbeeModel: [' Shutter switch with neutral\u0000\u0000\u0000'],
        model: '067776',
        vendor: 'Legrand',
        description: 'Netatmo wired shutter switch',
        // the physical LED will be green when permit join is true, off otherwise and red when not linked
        supports: 'open, close, stop, position, tilt',
        fromZigbee: [
            // Devices can send an identify message when the configuration button is pressed
            // (behind the physical buttons)
            // Used on the official gateway to send to every devices an identify command (green)
            fz.identify, fz.ignore_basic_report,
            // support binary report on moving state (supposed)
            fz.legrand_binary_input_moving, fz.cover_position_tilt_inverted,
        ],
        toZigbee: [
            tz.cover_state, tz.cover_position_tilt_inverted, tz.legrand_identify, tz.legrand_settingAlwaysEnableLed,
        ],
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            await bind(endpoint, coordinatorEndpoint, ['genBinaryInput', 'closuresWindowCovering', 'genIdentify']);
        },
    }
```
As this:
```
{
        zigbeeModel: [' Shutter SW with level control\u0000'],
        model: 'K4027C',
        vendor: 'BTicino',
        description: 'Shutter switch with neutral and level control',
        supports: 'open, close, stop, position, tilt, led color',
        fromZigbee: [
            fz.identify, fz.ignore_basic_report,
            fz.legrand_binary_input_moving, fz.cover_position_tilt,
        ],
        toZigbee: [
            tz.cover_state, tz.cover_position_tilt, tz.legrand_settingAlwaysEnableLed,
            tz.legrand_settingEnableLedIfOn, tz.legrand_identify,
        ],
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            await bind(endpoint, coordinatorEndpoint, ['genBinaryInput', 'closuresWindowCovering', 'genIdentify']);
        },
    },
```
I have a few questions (edited):

~~1. Why doesn't the shutter show in the devices from home-assistant but it does on zigbee2mqtt?~~ (had to implement a cover, see below)
2. The position doesn't look to be the correct one, see the logs in the third reply, how can I fix that?

**Comment by blackwiz4rd** [comment]
This is the database.db entry:
```
{
   "id": 3,
   "type": "Router",
   "ieeeAddr": "0x00047400007d550c",
   "nwkAddr": 30633,
   "manufId": 4129,
   "manufName": " Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000",
   "powerSource": "Mains (single phase)",
   "modelId": " Shutter SW with level control\u0000",
   "epList": [
      1
   ],
   "endpoints": {
      "1": {
         "profId": 260,
         "epId": 1,
         "devId": 514,
         "inClusterList": [
            0,
            3,
            258,
            4,
            5,
            15,
            64513
         ],
         "outClusterList": [
            0,
            64513,
            25
         ],
         "clusters": {
            "genBasic": {
               "attributes": {
                  "modelId": " Shutter SW with level control\u0000",
                  "manufacturerName": " Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000",
                  "powerSource": 1,
                  "zclVersion": 2,
                  "appVersion": 0,
                  "stackVersion": 65,
                  "hwVersion": 1,
                  "dateCode": " \u000020191030\u0000\u0000\u0000\u0000\u0000",
                  "swBuildId": "00b\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 \u0002\u0000\u0001\u0000 \u0002\u0000\u0002\u0000!\u0012\u0000\u0000\u0000\u0000��\u0003\u0000\u0010\u0002\u0001\u0004\u0000\u0018\u0002\u0000��!"
               }
            }
         },
         "binds": []
      }
   },
   "appVersion": 0,
   "stackVersion": 65,
   "hwVersion": 1,
   "dateCode": " \u000020191030\u0000\u0000\u0000\u0000\u0000",
   "swBuildId": "00b\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 \u0002\u0000\u0001\u0000 \u0002\u0000\u0002\u0000!\u0012\u0000\u0000\u0000\u0000��\u0003\u0000\u0010\u0002\u0001\u0004\u0000\u0018\u0002\u0000��!",
   "zclVersion": 2,
   "interviewCompleted": true,
   "meta": {},
   "lastSeen": 1584089191350
}
```

**Comment by blackwiz4rd** [comment]
```
info  2020-03-13 11:15:42: Successfully configured '0x00047400007d550c'
info  2020-03-13 11:25:41: MQTT publish: topic 'zigbee2mqtt/0x00047400007d550c', payload '{"position":50,"linkquality":97}'
info  2020-03-13 11:35:41: MQTT publish: topic 'zigbee2mqtt/0x00047400007d550c', payload '{"position":50,"linkquality":94}'
info  2020-03-13 11:39:13: MQTT publish: topic 'zigbee2mqtt/0x00047400007d550c', payload '{"position":50,"linkquality":92,"action":"moving"}'
info  2020-03-13 11:39:13: MQTT publish: topic 'zigbee2mqtt/0x00047400007d550c', payload '{"position":50,"linkquality":92,"action":""}'
info  2020-03-13 11:39:14: MQTT publish: topic 'zigbee2mqtt/0x00047400007d550c', payload '{"position":100,"linkquality":92}'
info  2020-03-13 11:39:18: MQTT publish: topic 'zigbee2mqtt/0x00047400007d550c', payload '{"position":100,"linkquality":92,"action":"moving"}'
info  2020-03-13 11:39:18: MQTT publish: topic 'zigbee2mqtt/0x00047400007d550c', payload '{"position":100,"linkquality":92,"action":""}'
info  2020-03-13 11:39:18: MQTT publish: topic 'zigbee2mqtt/0x00047400007d550c', payload '{"position":100,"linkquality":92,"action":"identify"}'
info  2020-03-13 11:39:18: MQTT publish: topic 'zigbee2mqtt/0x00047400007d550c', payload '{"position":100,"linkquality":92,"action":""}'
info  2020-03-13 11:39:47: MQTT publish: topic 'zigbee2mqtt/0x00047400007d550c', payload '{"position":100,"linkquality":92,"action":"stopped"}'
info  2020-03-13 11:39:47: MQTT publish: topic 'zigbee2mqtt/0x00047400007d550c', payload '{"position":100,"linkquality":92,"action":""}'
info  2020-03-13 11:39:47: MQTT publish: topic 'zigbee2mqtt/0x00047400007d550c', payload '{"position":0,"linkquality":92}'
info  2020-03-13 11:39:47: MQTT publish: topic 'zigbee2mqtt/0x00047400007d550c', payload '{"position":0,"linkquality":92,"action":"identify"}'
info  2020-03-13 11:39:47: MQTT publish: topic 'zigbee2mqtt/0x00047400007d550c', payload '{"position":0,"linkquality":92,"action":""}'
info  2020-03-13 11:39:54: MQTT publish: topic 'zigbee2mqtt/0x00047400007d550c', payload '{"position":0,"linkquality":92,"action":"moving"}'
info  2020-03-13 11:39:54: MQTT publish: topic 'zigbee2mqtt/0x00047400007d550c', payload '{"position":0,"linkquality":92,"action":""}'
info  2020-03-13 11:39:54: MQTT publish: topic 'zigbee2mqtt/0x00047400007d550c', payload '{"position":100,"linkquality":92}'
info  2020-03-13 11:39:55: MQTT publish: topic 'zigbee2mqtt/0x00047400007d550c', payload '{"position":100,"linkquality":92,"action":"stopped"}'
info  2020-03-13 11:39:55: MQTT publish: topic 'zigbee2mqtt/0x00047400007d550c', payload '{"position":100,"linkquality":92,"action":""}'
info  2020-03-13 11:39:55: MQTT publish: topic 'zigbee2mqtt/0x00047400007d550c', payload '{"position":100,"linkquality":92,"action":"identify"}'
info  2020-03-13 11:39:55: MQTT publish: topic 'zigbee2mqtt/0x00047400007d550c', payload '{"position":100,"linkquality":92,"action":""}'
info  2020-03-13 11:40:05: MQTT publish: topic 'zigbee2mqtt/0x00047400007d550c', payload '{"position":100,"linkquality":92,"action":"moving"}'
info  2020-03-13 11:40:05: MQTT publish: topic 'zigbee2mqtt/0x00047400007d550c', payload '{"position":100,"linkquality":92,"action":""}'
info  2020-03-13 11:40:05: MQTT publish: topic 'zigbee2mqtt/0x00047400007d550c', payload '{"position":50,"linkquality":92}'
info  2020-03-13 11:40:05: MQTT publish: topic 'zigbee2mqtt/0x00047400007d550c', payload '{"position":50,"linkquality":92,"action":"identify"}'
info  2020-03-13 11:40:05: MQTT publish: topic 'zigbee2mqtt/0x00047400007d550c', payload '{"position":50,"linkquality":92,"action":""}'
```

It does recognize the moving/stop but the position is not correct (shouldn't that be the percentage of opening of the shutter?).

**Comment by Koenkk** [comment]
@cemonneau would you mind helping with this?

**Comment by blackwiz4rd** [comment]
> @cemonneau would you mind helping with this?

Can you give me any hints on how to debug the problem so I can manage to fix it? I don't understand how the message "parsing" works in zigbee2mqtt. I would like to understand where that message comes from and why it is interpreted in that way. Thanks a lot!

**Comment by blackwiz4rd** [comment]
> @cemonneau would you mind helping with this?

I have some very good news.
I can close, open and stop the shutter with mosquitto_pub:
For closing:
```
mosquitto_pub -h 127.0.0.1 -t zigbee2mqtt/0x00047400007d550c/set -m "{\"position\": \"100\"}"
```
For opening:
```
mosquitto_pub -h 127.0.0.1 -t zigbee2mqtt/0x00047400007d550c/set -m "{\"position\": \"50\"}"
```
For stopping:
```
mosquitto_pub -h 127.0.0.1 -t zigbee2mqtt/0x00047400007d550c/set -m "{\"position\": \"stop\"}"
```

However, I still have the same problems pointed out above:
1. The shutter doesn't show in the devices from home-assistant
2. The position is not available in percentage, why? (50 means opening, 100 means closing)

**Comment by blackwiz4rd** [comment]
> > @cemonneau would you mind helping with this?
> 
> I have some very good news.
> I can close, open and stop the shutter with mosquitto_pub:
> For closing:
> 
> ```
> mosquitto_pub -h 127.0.0.1 -t zigbee2mqtt/0x00047400007d550c/set -m "{\"position\": \"100\"}"
> ```
> 
> For opening:
> 
> ```
> mosquitto_pub -h 127.0.0.1 -t zigbee2mqtt/0x00047400007d550c/set -m "{\"position\": \"50\"}"
> ```
> 
> For stopping:
> 
> ```
> mosquitto_pub -h 127.0.0.1 -t zigbee2mqtt/0x00047400007d550c/set -m "{\"state\": \"stop\"}"
> ```
> 
> However, I still have the same problems pointed out above:
> 
> 1. The shutter doesn't show in the devices from home-assistant
> 2. The position is not available in percentage, why? (50 means opening, 100 means closing)

I can now answer for question 1.
I didn't know you need to setup a cover in `configuration.yaml`:
cover:
  - platform: mqtt
    name: "Tapparella Cucina"
    command_topic: "zigbee2mqtt/shutter_xxx/set"
    position_topic: "zigbee2mqtt/shutter_xxx/set/position"
    position_open: 50
    position_closed: 100

**Comment by blackwiz4rd** [comment]
Hi, some additional information that can be useful for understanding why the percentage isn't reported.
With the original gateway the device doesn't need calibration and:
- the percentage can be set with Apple Home
- the percentage may be set with Google Home (not 100% sure)
- the shutter is not supported by Alexa.

**Comment by blackwiz4rd** [comment]
After manual calibration of the motor, nothing has changed. So there are two options:

- the traffic from the K4027C is not interpreted correctly
- there is no way to control the percentage of the shutter from the K4027C (unlikely because Apple Home can do it) and it is made by software (could Apple Home do this by software only?).

**Comment by blackwiz4rd** [comment]
@cemonneau @Koenkk please, can you provide any help? I am clueless on how to solve or debug the problem (I don't have a CC debugger to flash the sniffing firmware).
Thanks,
Luca.

**Comment by jd1900** [comment]
I have a similar (but worse) issue described in the similar shutter (Legrand 067776 https://www.zigbee2mqtt.io/devices/067776.html), described in here:
https://github.com/Koenkk/zigbee2mqtt/issues/2399#issuecomment-622569450

The positions is always 50. 

Here is the official documentation: https://www.grupolegrand.es/e-catalogo/docs/NP-FT-GT/Valena-Next/741807-37-67_LE11246_ES.pdf But there is very little information other than installing. No config, nothing. 

Maybe the configuration is in the official app with the official gateway. I guess that there must be some config commands available. Sniffing the traffic between the official gateway and the shutter could help.

**Comment by blackwiz4rd** [comment]
> I have a similar (but worse) issue described in the similar shutter (Legrand 067776 https://www.zigbee2mqtt.io/devices/067776.html), described in here:
> [Koenkk/zigbee2mqtt#2399 (comment)](https://github.com/Koenkk/zigbee2mqtt/issues/2399#issuecomment-622569450)
> 
> The positions is always 50.
> 
> Here is the official documentation: https://www.grupolegrand.es/e-catalogo/docs/NP-FT-GT/Valena-Next/741807-37-67_LE11246_ES.pdf But there is very little information other than installing. No config, nothing.
> 
> Maybe the configuration is in the official app with the official gateway. I guess that there must be some config commands available. Sniffing the traffic between the official gateway and the shutter could help.

Hi, thank you very much for answering. I suppose that to understand the issue and clarify why the position is interpreted in a wrong way, we must flash the sniffing firmware. Unfortunately, I can't do that because I don't have a CC debugger. In case you have it we could try and understand why this is happening by looking at the traffic at a lower level. If you need instructions on how to flash the firmware they can be found here: [sniffing](https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html). Maybe we can work together on this in case you need help in understanding the traffic.

**Comment by agsola** [comment]
@blackwiz4rd unfortunately not only I don't have a CC debugger, but neither the official gateway to snif from :(

**Comment by jd1900** [comment]
@blackwiz4rd unfortunately not only I don't have a CC debugger, but neither the official gateway to snif from :(

**Comment by jd1900** [comment]
I've been doing a little bit more of research.

I though I couldn't get 0 or 100 position values. But I was wrong, I can get them, but I have to wait quite a bit not pressing the "stop" button. Maybe after 5 minutes or so the Legrand device reports 100 or 0 depending of being opened or closed.

**Comment by blackwiz4rd** [comment]
> I've been doing a little bit more of research.
> 
> I though I couldn't get 0 or 100 position values. But I was wrong, I can get them, but I have to wait quite a bit not pressing the "stop" button. Maybe after 5 minutes or so the Legrand device reports 100 or 0 depending of being opened or closed.

I don't understand this, can you explain more clearly? Are you opening/closing manually or with zigbee2mqtt?
Thanks.

**Comment by jd1900** [comment]
> > I've been doing a little bit more of research.
> > I though I couldn't get 0 or 100 position values. But I was wrong, I can get them, but I have to wait quite a bit not pressing the "stop" button. Maybe after 5 minutes or so the Legrand device reports 100 or 0 depending of being opened or closed.
> 
> I don't understand this, can you explain more clearly? Are you opening/closing manually or with zigbee2mqtt?
> Thanks.

Both. It doesn't matter.
The point is that when it reaches the end, it doesn't change the position until maybe 4-5 minutes after being stopped. 
And the only values used are 0, 50 and 100. 
0 and 100 are used only if the end or beginning is reached, no stop button is pressed and after a few minutes with no movement.

I hope this clarifies a bit my other message.

Otherwise I can give examples.
