### ISSUE TITLE
light.toggle(on) (after light.toggle(off) with a transition) don't set brightness to previous level

### ISSUE THREAD

**Issue by htvekov** [Koenkk/zigbee-herdsman-converters#1073]
Hi' Koenkk.

I've an issue with Ikea White Spectrum/color bulbs on zigbee2mqtt integrations.

Environment:
Hass.io - Home Assistant 0.106.6
zigbee2mqtt-dev v1.11.0

- light.turn_off/light.toggle(off) with a transition via HA service calls
- light.turn_on/light.toggle(on) again via HA service call with transition attribute omitted completely
- Previous brightness wont be restored to bulb, even though HA states correct attribute value.
  Brightness is actually at 1.

Expected behaviour: light.toggle(on)/light.turn_on without any attributes at all should restore bulb to previous state - color/color_temp and brightness.

Below zigbee logs with HA service call 'off event' including transition attribute and afterwards 'on event' with no attributes at all.

> zigbee2mqtt:debug 2020-03-18 22:08:36: Received MQTT message on 'zigbee2mqtt/Office desk lamp/set' with data '{"state": "OFF", "transition": 1.0}'
> zigbee2mqtt:debug 2020-03-18 22:08:36: Publishing 'set' 'state' to 'Office desk lamp'
> zigbee2mqtt:info  2020-03-18 22:08:36: MQTT publish: topic 'zigbee2mqtt/Office desk lamp', payload '{"state":"OFF","color_temp":250,"brightness":255,"update_available":false}'
> zigbee2mqtt:debug 2020-03-18 22:08:36: Publishing 'set' 'transition' to 'Office desk lamp'
> zigbee2mqtt:debug 2020-03-18 22:08:40: Received MQTT message on 'zigbee2mqtt/Office desk lamp/set' with data '{"state": "ON"}'
> zigbee2mqtt:debug 2020-03-18 22:08:40: Publishing 'set' 'state' to 'Office desk lamp'
> zigbee2mqtt:info  2020-03-18 22:08:40: MQTT publish: topic 'zigbee2mqtt/Office desk lamp', payload '{"state":"ON","color_temp":250,"brightness":255,"update_available":false}'

I actually experience somewhat the opposite problem with same type of Ikea bulbs via HA Hue integration.
Here light.toggle(on) is needed with NO attributes at all for brightness/color to be restored to original state. If a transition attribute is applied, then brightness at bulb will be set to 1. 
(Hue brightness issue: https://github.com/home-assistant/core/issues/32894)

I'm using Xavi's ControllerX appdeamon app for easy Ikea/Xiomi remote integration. And this 'toggle(off) with transition brightness issue' is quite struggling, as I use both z2m and Hue light integrations. (ControllerX issue: https://github.com/xaviml/controllerx/issues/58)

I could imagine that this issue could be somewhat connected to previous issue regarding transition with both color/color_temp and brightness simultaneously ? (https://github.com/Koenkk/zigbee2mqtt/issues/1810#issuecomment-534511680)

Any help on fixing this issue would really be appreciated 🙏😆😎🙋‍♂️

Ciao !

**Comment by Koenkk** [comment]
Fixed in the latest zigbee2mqtt dev branch, thanks for reporting!

**Comment by htvekov** [comment]
Hi' Koenkk.

Wow, that was quick ! 😃
Just shifted from v1.12.0 to v1.12.0-dev and tested behaviour.
Sorry, but can't see any change. zigbee logs also seems identical to prior logs.

Anything I can help with, logs, tests etc. - just let me know.

Ciao !

> zigbee2mqtt:debug 2020-03-20 00:00:18: Received MQTT message on 'zigbee2mqtt/Office desk lamp/set' with data '{"state": "OFF", "transition": 2.0}'
zigbee2mqtt:debug 2020-03-20 00:00:18: Publishing 'set' 'state' to 'Office desk lamp'
zigbee2mqtt:info  2020-03-20 00:00:18: MQTT publish: topic 'zigbee2mqtt/Office desk lamp', payload '{"state":"OFF","color_temp":500,"brightness":255,"update_available":false}'
zigbee2mqtt:debug 2020-03-20 00:00:18: Publishing 'set' 'transition' to 'Office desk lamp'
zigbee2mqtt:debug 2020-03-20 00:00:24: Received MQTT message on 'zigbee2mqtt/Office desk lamp/set' with data '{"state": "ON"}'
zigbee2mqtt:debug 2020-03-20 00:00:24: Publishing 'set' 'state' to 'Office desk lamp'
zigbee2mqtt:info  2020-03-20 00:00:24: MQTT publish: topic 'zigbee2mqtt/Office desk lamp', payload '{"state":"ON","color_temp":500,"brightness":255,"update_available":false}'

**Comment by Koenkk** [comment]
I forgot to push the changes, can you try again with the latest dev branch?

Also make sure that you first at least set the brightness of the bulb once.

**Comment by htvekov** [comment]
Hi' Koenkk.

Sorry about the late reply.
I'm on Hass.io with z2m-edge installed as Add-ons.
No new update yet. Still on v1.12.0-dev
Can I pull latest manually or have to wait for hassio z2m-dev branch to be updated ?

**Comment by Koenkk** [comment]
To update the edge addon, remove it and install it agian.

**Comment by htvekov** [comment]
Simple solution - How hard can it be ! 😉

Tested new edge version now.
It works completely as expected 😃🙏😁😎🎉🎉

I'm SO pleased, Koenkk 🤗

When can I expect this change applied to stable version ?
As I have to report some needed changes to be made in Xavi's controllerX code regarding this general z2m brightness change.

Ciao !

**Comment by Koenkk** [comment]
Cool, it will be included in the next zigbee2mqtt release which will be released in 2.5 weeks from now.
