### ISSUE TITLE
meta.mapped is always null for groups, breaking applyRedFix and enhancedHue

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee-herdsman-converters#1086]
After some debugging as to why my Innr bulb was not responding to hue/sat color changes, I figure it out.

`meta.mapped` is always `null` for a group! (makes sense in hindsight), however this means that `enhancedHue` and `applyRedFix` don't work via groups.

e.g. group_1 has 4 bulbs, sending `{"color": {"hue": 0, "saturation": 100}}` to the group has no effect (nothing happens), sending that to the individual bulbs works fine.

Currently not sure how this can be fixed.

**Comment by sjorge** [comment]
Some debugging with console.log() in toZigbee.js seems to show 'meta' is always null, doesn't matter what I set in devices.js!

I think applyRedFix is probably also broken then, it's late now and still not sure how to fix it. I'm off to bed.

**Comment by sjorge** [comment]
I can only think of a half-workaround.

I guess it is more likely that all bulbs in a group will be of the same type: 4x Hue Type X || 4x Innr Type Y vs 2x Hue Type X + 2x Innr Type Y

The workaround could be if we notice all device in the group are the same manufacturer/model is to take the meta parameter from that manufacturer/model vs having it be `null`.

All the code would then work as is, this has a few down sides though:
- won't cover cases of mixed manufacturer/model
- seems a PITA to implement (ideas?)

**Comment by sjorge** [comment]
So i came up with 2 possible solutions

- option 1
  - !group of same devices => print warning
  - group of same devices => meta.mapper = group.devices[0].meta.mapper

- option 2
  - group of same devices => meta.mapper = group.devices[0].meta.mapper
  - !group of same devices => send multiple messages to group for each device time

I don't like option 2 personally, as some device will get 2 message it can handle and others potentially only one, this does probably give the best overal results but at the cost of increased traffic and maybe double actions?

I think option 1 is a good middle group, a mixed group of bulbs will get a warning printed so it is easy for the users to identify the source of potential odd behavior. If all devices in the group are the same there is no issue as we can send the correct command by just taking the meta.mapped from the first device.

I have a rought idea of how to implement option 1, so I am willing to give that a shot.

Any other ideas @Koenkk ?

**Comment by Koenkk** [comment]
Option 1 looks good to me, lets print the error only when an applyRedFix or enhanceHue device is in it and other device and when setting the color (to no bother too many people with it).

**Comment by sjorge** [comment]
Sounds good, maybe to future proof it instead of checking only applyRedFix and enhanceHue we should simply  check if any of the meta.mapper values differ.

For most device it should be the same and unset right? I'll try to look at it next friday after work... well after I am done WFH.

**Comment by Koenkk** [comment]
There can be multiple values in this, also configureKey.

Currently these values are hard checked in https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/test/index.test.js#L128 so a comment there is good enough.

**Comment by sjorge** [comment]
Since we're in toZigbee... that is also not available...
I suppose I could also add ```const zigbeeHerdsmanConverters = require('zigbee-herdsman-converters')``` but won't that be a circular issue then?

**Comment by sjorge** [comment]
That doesnt work either as zigbeeHerdsmanConverters is `{}` in that case.
I also tried loading devices.js but adding
```const devices = require('../devices');``` has it also as `{}`.

**Comment by sjorge** [comment]
Alright, I got it working... it's 2 PRs one for z2m and one for converters, I will prop them now.

**Comment by sjorge** [comment]
Both PR's are up

**Comment by sjorge** [comment]
both PR's got merged.
