### ISSUE TITLE
light.toggle(on) with a transition attribute set (after light.turn_off) don't set brightness to correct previous level 

### ISSUE THREAD

**Issue by htvekov** [Koenkk/zigbee-herdsman-converters#1097]
Hi' Koenkk.

I'm quite sure this issue is related to the other, newly fixed, brightness issue #1073 
It's somewhat the 'opposite' error of what was previously fixed.

Actually Xavi, the developer of ControllerX app, found this bug after new tests with the updated z2m-edge:

Environment:
Hass.io - Home Assistant 0.107.7
zigbee2mqtt-edge (but also on latest z2m-stable version)
Ikea White Spectrum bulb on z2m integration

Case:
- Turn on the light from HA (service calls)
- Change the brightness to 50%
- Turn off the light from HA (service calls)
- Call light.toggle service with transition = 0.3 (e.g.)

Then the brightness is NOT set back to 50%, but to a 'different' brightness.
This can be repeated over and over again with same result.

There's actually a pattern to the 'brightness set error'. The brightness set is ALWAYS the PREVIOUS brightness, until an lights off or toggle off is called with a transition attribute set. Then this brightness becomes new 'previous brightness' (Hope this somewhat difficult sentence makes any sense ?)

However, if I remove the "transition" attribute, I do not experience this. Then light always turns on at correct previous brightness.

ControllerX Github issue reference: https://github.com/xaviml/controllerx/issues/58

Hope you can fix this as well, Koenkk 🙏😃🙋‍♂️

Ciao !

**Comment by Koenkk** [comment]
I cannot reproduce this but probably I'm using slightly different commands. Could you provide the log when reproducing this bug and running with `DEBUG=zigbee:herdsman:controller*`?

Some background on why you get these bugs when using transition: Zigbee does not have commands to turn on/off lights with a transition (besides one with a fixed 0.8 transition). Therefore we turning a bulb off with a transition, we set the brightness to 0. When the bulb is turned on again we need to restore this transition.

**Comment by htvekov** [comment]
Hi' Koenkk.

OK. Wasn't aware of that.

Thought that transition was so low level, that it was handled completely by bulbs firmware.
As I understand your answer, Ikea bulbs firmware defaults to transition: 0.8,  if no attribute is specified ? And remaining transitions are 'emulated' by zigbee converter, by transitioning to/from brightness: 0 and then turn on/off lights ? Clever ! 👍😎

Anyway I'm on hassio and tried googling how to enable herdsman logging ?
Actually couldn't find much, so I used  `zigbee_herdsman_debug: true` directly in zigbee config and made cut/paste directly from screen output.

Hopefully this log contains all the info you need ?

Here goes:


> # HA service call: light.turn.on <entity_id>
> 
> 
> zigbee2mqtt:debug 2020-03-28 20:22:38: Received MQTT message on 'zigbee2mqtt/Office desk lamp/set' with data '{"state": "ON"}'
> zigbee2mqtt:debug 2020-03-28 20:22:38: Publishing 'set' 'state' to 'Office desk lamp'
> 2020-03-28T19:22:38.025Z zigbee-herdsman:controller:endpoint Command 0x680ae2fffe924460/1 genLevelCtrl.moveToLevelWithOnOff({"level":255,"transtime":0}, {"timeout":6000,"manufacturerCode":null,"disableDefaultResponse":false})
> 2020-03-28T19:22:38.027Z zigbee-herdsman:adapter:zStack:znp:SREQ --> AF - dataRequest - {"dstaddr":8393,"destendpoint":1,"srcendpoint":1,"clusterid":8,"transid":32,"options":0,"radius":30,"len":6,"data":{"type":"Buffer","data":[1,18,4,255,0,0]}}
> 2020-03-28T19:22:38.028Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,16,36,1,201,32,1,1,8,0,32,0,30,6,1,18,4,255,0,0,4]
> 2020-03-28T19:22:38.041Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,100,1,0,100]
> 2020-03-28T19:22:38.042Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,100,1,0,100]
> 2020-03-28T19:22:38.043Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 4 - 1 - [0] - 100
> 2020-03-28T19:22:38.043Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- AF - dataRequest - {"status":0}
> 2020-03-28T19:22:38.043Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
> 2020-03-28T19:22:38.048Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,68,128,0,1,32,230]
> 2020-03-28T19:22:38.048Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,68,128,0,1,32,230]
> 2020-03-28T19:22:38.049Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 4 - 128 - [0,1,32] - 230
> 2020-03-28T19:22:38.049Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - dataConfirm - {"status":0,"endpoint":1,"transid":32}
> 2020-03-28T19:22:38.049Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
> 2020-03-28T19:22:38.081Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,69,196,201,32,0,107]
> 2020-03-28T19:22:38.082Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,69,196,201,32,0,107]
> 2020-03-28T19:22:38.082Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 5 - 196 - [201,32,0] - 107
> 2020-03-28T19:22:38.082Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - srcRtgInd - {"dstaddr":8393,"relaycount":0,"relaylist":[]}
> 2020-03-28T19:22:38.083Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
> 2020-03-28T19:22:38.128Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,25,68,129,0,0,8,0,201,32,1,1,0,107,0,98,231,42,0,0,5,8,18,11,4,0,201,32,29,29]
> 2020-03-28T19:22:38.128Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,25,68,129,0,0,8,0,201,32,1,1,0,107,0,98,231,42,0,0,5,8,18,11,4,0,201,32,29,29]
> 2020-03-28T19:22:38.129Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 25 - 2 - 4 - 129 - [0,0,8,0,201,32,1,1,0,107,0,98,231,42,0,0,5,8,18,11,4,0,201,32,29] - 29
> 2020-03-28T19:22:38.129Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - incomingMsg - {"groupid":0,"clusterid":8,"srcaddr":8393,"srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"linkquality":107,"securityuse":0,"timestamp":2811746,"transseqnumber":0,"len":5,"data":{"type":"Buffer","data":[8,18,11,4,0]}}
> 2020-03-28T19:22:38.131Z zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":false},"transactionSequenceNumber":18,"manufacturerCode":null,"commandIdentifier":11},"Payload":{"cmdId":4,"statusCode":0}},"address":8393,"endpoint":1,"linkquality":107,"groupID":0}'
> 2020-03-28T19:22:38.132Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
> zigbee2mqtt:info  2020-03-28 20:22:38: MQTT publish: topic 'zigbee2mqtt/Office desk lamp', payload '{"state":"ON","color_temp":500,"brightness":255,"update_available":false}'
> 
> 
> # Change brightness to 123 (via brightness slider on entity in HA)
> 
> 
> zigbee2mqtt:debug 2020-03-28 20:22:46: Received MQTT message on 'zigbee2mqtt/Office desk lamp/set' with data '{"state": "ON", "brightness": 123}'
> zigbee2mqtt:debug 2020-03-28 20:22:46: Publishing 'set' 'brightness' to 'Office desk lamp'
> 2020-03-28T19:22:46.664Z zigbee-herdsman:controller:endpoint Command 0x680ae2fffe924460/1 genLevelCtrl.moveToLevelWithOnOff({"level":123,"transtime":0}, {"timeout":6000,"manufacturerCode":null,"disableDefaultResponse":false})
> 2020-03-28T19:22:46.666Z zigbee-herdsman:adapter:zStack:znp:SREQ --> AF - dataRequest - {"dstaddr":8393,"destendpoint":1,"srcendpoint":1,"clusterid":8,"transid":33,"options":0,"radius":30,"len":6,"data":{"type":"Buffer","data":[1,19,4,123,0,0]}}
> 2020-03-28T19:22:46.666Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,16,36,1,201,32,1,1,8,0,33,0,30,6,1,19,4,123,0,0,128]
> 2020-03-28T19:22:46.678Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,100,1,0,100]
> 2020-03-28T19:22:46.679Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,100,1,0,100]
> 2020-03-28T19:22:46.679Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 4 - 1 - [0] - 100
> 2020-03-28T19:22:46.679Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- AF - dataRequest - {"status":0}
> 2020-03-28T19:22:46.679Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
> 2020-03-28T19:22:46.687Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,68,128,0,1,33,231]
> 2020-03-28T19:22:46.688Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,68,128,0,1,33,231]
> 2020-03-28T19:22:46.688Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 4 - 128 - [0,1,33] - 231
> 2020-03-28T19:22:46.689Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - dataConfirm - {"status":0,"endpoint":1,"transid":33}
> 2020-03-28T19:22:46.689Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
> 2020-03-28T19:22:46.711Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,69,196,201,32,0,107]
> 2020-03-28T19:22:46.712Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,69,196,201,32,0,107]
> 2020-03-28T19:22:46.712Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 5 - 196 - [201,32,0] - 107
> 2020-03-28T19:22:46.713Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - srcRtgInd - {"dstaddr":8393,"relaycount":0,"relaylist":[]}
> 2020-03-28T19:22:46.713Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
> 2020-03-28T19:22:46.759Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,25,68,129,0,0,8,0,201,32,1,1,0,107,0,191,80,43,0,0,5,8,19,11,4,0,201,32,29,119]
> 2020-03-28T19:22:46.760Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,25,68,129,0,0,8,0,201,32,1,1,0,107,0,191,80,43,0,0,5,8,19,11,4,0,201,32,29,119]
> 2020-03-28T19:22:46.760Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 25 - 2 - 4 - 129 - [0,0,8,0,201,32,1,1,0,107,0,191,80,43,0,0,5,8,19,11,4,0,201,32,29] - 119
> 2020-03-28T19:22:46.761Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - incomingMsg - {"groupid":0,"clusterid":8,"srcaddr":8393,"srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"linkquality":107,"securityuse":0,"timestamp":2838719,"transseqnumber":0,"len":5,"data":{"type":"Buffer","data":[8,19,11,4,0]}}
> 2020-03-28T19:22:46.765Z zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":false},"transactionSequenceNumber":19,"manufacturerCode":null,"commandIdentifier":11},"Payload":{"cmdId":4,"statusCode":0}},"address":8393,"endpoint":1,"linkquality":107,"groupID":0}'
> 2020-03-28T19:22:46.766Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
> zigbee2mqtt:info  2020-03-28 20:22:46: MQTT publish: topic 'zigbee2mqtt/Office desk lamp', payload '{"state":"ON","color_temp":500,"brightness":123,"update_available":false}'
> 
> 
> # HA service call: light.turn.off <entity_id>
> 
> 
> zigbee2mqtt:debug 2020-03-28 20:27:14: Received MQTT message on 'zigbee2mqtt/Office desk lamp/set' with data '{"state": "OFF"}'
> zigbee2mqtt:debug 2020-03-28 20:27:14: Publishing 'set' 'state' to 'Office desk lamp'
> 2020-03-28T19:27:14.674Z zigbee-herdsman:controller:endpoint Command 0x680ae2fffe924460/1 genOnOff.off({}, {"timeout":6000,"manufacturerCode":null,"disableDefaultResponse":false})
> 2020-03-28T19:27:14.675Z zigbee-herdsman:adapter:zStack:znp:SREQ --> AF - dataRequest - {"dstaddr":8393,"destendpoint":1,"srcendpoint":1,"clusterid":6,"transid":63,"options":0,"radius":30,"len":3,"data":{"type":"Buffer","data":[1,21,0]}}
> 2020-03-28T19:27:14.676Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,13,36,1,201,32,1,1,6,0,63,0,30,3,1,21,0,241]
> 2020-03-28T19:27:14.689Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,100,1,0,100]
> 2020-03-28T19:27:14.689Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,100,1,0,100]
> 2020-03-28T19:27:14.689Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 4 - 1 - [0] - 100
> 2020-03-28T19:27:14.689Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- AF - dataRequest - {"status":0}
> 2020-03-28T19:27:14.690Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
> 2020-03-28T19:27:14.695Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,68,128,0,1,63,249]
> 2020-03-28T19:27:14.696Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,68,128,0,1,63,249]
> 2020-03-28T19:27:14.696Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 4 - 128 - [0,1,63] - 249
> 2020-03-28T19:27:14.696Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - dataConfirm - {"status":0,"endpoint":1,"transid":63}
> 2020-03-28T19:27:14.696Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
> 2020-03-28T19:27:14.716Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,69,196,201,32,0,107]
> 2020-03-28T19:27:14.717Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,69,196,201,32,0,107]
> 2020-03-28T19:27:14.717Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 5 - 196 - [201,32,0] - 107
> 2020-03-28T19:27:14.717Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - srcRtgInd - {"dstaddr":8393,"relaycount":0,"relaylist":[]}
> 2020-03-28T19:27:14.717Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
> 2020-03-28T19:27:14.766Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,25,68,129,0,0,6,0,201,32,1,1,0,107,0,115,24,56,0,0,5,8,21,11,0,0,201,32,29,236]
> 2020-03-28T19:27:14.766Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,25,68,129,0,0,6,0,201,32,1,1,0,107,0,115,24,56,0,0,5,8,21,11,0,0,201,32,29,236]
> 2020-03-28T19:27:14.767Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 25 - 2 - 4 - 129 - [0,0,6,0,201,32,1,1,0,107,0,115,24,56,0,0,5,8,21,11,0,0,201,32,29] - 236
> 2020-03-28T19:27:14.767Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - incomingMsg - {"groupid":0,"clusterid":6,"srcaddr":8393,"srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"linkquality":107,"securityuse":0,"timestamp":3676275,"transseqnumber":0,"len":5,"data":{"type":"Buffer","data":[8,21,11,0,0]}}
> 2020-03-28T19:27:14.771Z zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":false},"transactionSequenceNumber":21,"manufacturerCode":null,"commandIdentifier":11},"Payload":{"cmdId":0,"statusCode":0}},"address":8393,"endpoint":1,"linkquality":107,"groupID":0}'
> 2020-03-28T19:27:14.772Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
> zigbee2mqtt:info  2020-03-28 20:27:14: MQTT publish: topic 'zigbee2mqtt/Office desk lamp', payload '{"state":"OFF","color_temp":500,"brightness":123,"update_available":false}'
> 
> 
> # HA service call: light.toggle <entity_id>, [transition=1]
> 
> 
> zigbee2mqtt:debug 2020-03-28 20:27:19: Received MQTT message on 'zigbee2mqtt/Office desk lamp/set' with data '{"state": "ON", "transition": 1.0}'
> zigbee2mqtt:debug 2020-03-28 20:27:19: Publishing 'set' 'state' to 'Office desk lamp'
> 2020-03-28T19:27:19.225Z zigbee-herdsman:controller:endpoint Command 0x680ae2fffe924460/1 genLevelCtrl.moveToLevelWithOnOff({"level":255,"transtime":10}, {"timeout":6000,"manufacturerCode":null,"disableDefaultResponse":false})
> 2020-03-28T19:27:19.227Z zigbee-herdsman:adapter:zStack:znp:SREQ --> AF - dataRequest - {"dstaddr":8393,"destendpoint":1,"srcendpoint":1,"clusterid":8,"transid":64,"options":0,"radius":30,"len":6,"data":{"type":"Buffer","data":[1,22,4,255,10,0]}}
> 2020-03-28T19:27:19.228Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,16,36,1,201,32,1,1,8,0,64,0,30,6,1,22,4,255,10,0,106]
> 2020-03-28T19:27:19.241Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,100,1,0,100]
> 2020-03-28T19:27:19.241Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,100,1,0,100]
> 2020-03-28T19:27:19.241Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 4 - 1 - [0] - 100
> 2020-03-28T19:27:19.242Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- AF - dataRequest - {"status":0}
> 2020-03-28T19:27:19.242Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
> 2020-03-28T19:27:19.248Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,68,128,0,1,64,134]
> 2020-03-28T19:27:19.250Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,68,128,0,1,64,134]
> 2020-03-28T19:27:19.250Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 4 - 128 - [0,1,64] - 134
> 2020-03-28T19:27:19.250Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - dataConfirm - {"status":0,"endpoint":1,"transid":64}
> 2020-03-28T19:27:19.251Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
> 2020-03-28T19:27:19.272Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,69,196,201,32,0,107]
> 2020-03-28T19:27:19.273Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,69,196,201,32,0,107]
> 2020-03-28T19:27:19.273Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 5 - 196 - [201,32,0] - 107
> 2020-03-28T19:27:19.273Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - srcRtgInd - {"dstaddr":8393,"relaycount":0,"relaylist":[]}
> 2020-03-28T19:27:19.273Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
> 2020-03-28T19:27:19.322Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,25,68,129,0,0,8,0,201,32,1,1,0,107,0,19,80,56,0,0,5,8,22,11,4,0,201,32,29,205]
> 2020-03-28T19:27:19.323Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,25,68,129,0,0,8,0,201,32,1,1,0,107,0,19,80,56,0,0,5,8,22,11,4,0,201,32,29,205]
> 2020-03-28T19:27:19.323Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 25 - 2 - 4 - 129 - [0,0,8,0,201,32,1,1,0,107,0,19,80,56,0,0,5,8,22,11,4,0,201,32,29] - 205
> 2020-03-28T19:27:19.324Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - incomingMsg - {"groupid":0,"clusterid":8,"srcaddr":8393,"srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"linkquality":107,"securityuse":0,"timestamp":3690515,"transseqnumber":0,"len":5,"data":{"type":"Buffer","data":[8,22,11,4,0]}}
> 2020-03-28T19:27:19.326Z zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":false},"transactionSequenceNumber":22,"manufacturerCode":null,"commandIdentifier":11},"Payload":{"cmdId":4,"statusCode":0}},"address":8393,"endpoint":1,"linkquality":107,"groupID":0}'
> 2020-03-28T19:27:19.327Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
> zigbee2mqtt:info  2020-03-28 20:27:19: MQTT publish: topic 'zigbee2mqtt/Office desk lamp', payload '{"state":"ON","color_temp":500,"brightness":255,"update_available":false}'
> zigbee2mqtt:debug 2020-03-28 20:27:19: Publishing 'set' 'transition' to 'Office desk lamp'
> 
> # Light turns on with transition: 1 to previous brightness: 255 instead of expected brightness: 123

**Comment by Koenkk** [comment]
Thanks, fixed it, will be available in the latest dev branch in a few hours.

**Comment by xaviml** [comment]
I confirm this fixed the bug👍

Thanks for fixing this @Koenkk and thank you for all the effort you put into this project :)

**Comment by htvekov** [comment]
Hi' Koenkk.

Xavi has already tested and confirmed fix.
Thank you once again, Koenkk 👍🍻😃

**Comment by Koenkk** [comment]
@xaviml @htvekov also thanks to you for finding, cheers 😄
