### ISSUE TITLE
Yale YRD210 wrong battery reading

### ISSUE THREAD

**Issue by presslab-us** [Koenkk/zigbee-herdsman-converters#1102]
My Yale YRD210 locks (I have four) are correctly detected and the functionality is fine.  But the battery reading is incorrect, it reads half what it should.  I tested with new batteries and it reports exactly 50%.
https://github.com/Koenkk/zigbee-herdsman-converters/blob/fa037d57038450c29e78ea93d0b8dffdd42630b2/devices.js#L6285
Changing that line to the same as YRD220 like so:
https://github.com/Koenkk/zigbee-herdsman-converters/blob/fa037d57038450c29e78ea93d0b8dffdd42630b2/devices.js#L6317
works and fixes the battery problem.

I'm not sure who wrote that original code, and GitHub blame isn't working (I get a Unicorn).  Is it safe to assume that my four locks are correct and the original implementation is not?  I'm not sure...

**Comment by Koenkk** [comment]
The implementation is correct, but the locks are not complying to the Zigbee specification (e.g. report of 200 = 100%, report of 100 = 50%). 

![image](https://user-images.githubusercontent.com/2892853/77832391-fb354880-7135-11ea-9475-cf93f9377887.png)

Anyway, pushed the fix to the repo, thanks!

**Comment by presslab-us** [comment]
Yep!  I agree the devices are not meeting Zigbee spec.  When I said implementation I meant the specific definition in `devices.js`  to match the YRD210.  Thanks!
