### ISSUE TITLE
Centralite 4257050-RZHAC power report wrong

### ISSUE THREAD

**Issue by presslab-us** [Koenkk/zigbee-herdsman-converters#1103]
I have a dozen of the Centralite 4257050-RZHAC outlet switches.  Currently the device configuration is shared with the 4256251-RZHAC.

There is a problem with the power reporting, the values are wrong.  I have tested changing the handler to be like 4257050-ZHAC (note no 'R', and I removed the level control stuff) and it's working as it should.  BTW, the 'R' means it is a relay module.

I'd be happy to do a PR if you think this change is okay.

**Comment by Koenkk** [comment]
Please submit the PR, I can check there.
