### ISSUE TITLE
Legrand 067723

### ISSUE THREAD

**Issue by Adorem** [Koenkk/zigbee-herdsman-converters#1104]
Hi,

I'm trying to pair a device Legrand 067723
This device is probably closed to that one: [Legrand 067773](https://www.zigbee2mqtt.io/devices/067773.html)

But then I get this error:
```
zigbee2mqtt:info  2020-03-28 23:36:56: Starting interview of '0x00047400007991eb'
zigbee2mqtt:info  2020-03-28 23:36:56: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"0x00047400007991eb"}}'
zigbee2mqtt:error 2020-03-28 23:37:56: Failed to interview '0x00047400007991eb', device has not successfully been paired
```
And then I can't go further with the steps describes in "How to support new devices".

Any idea why I can't pair it?

Thanks.

**Comment by Kryzek** [comment]
Not sure if related, but there is this issue with joining devices after some uutinen: https://github.com/Koenkk/zigbee2mqtt/issues/3177

I would start by stopping Z2M and replugging the coordinator stick and restarting Z2M.

**Comment by Adorem** [comment]
I tried to pair other devices and for them it's working.

I also try to reboot my full system and this do not solve the problem.

**Comment by blackwiz4rd** [comment]
I suggest you to keep trying to reset the device when the power is on until you get a successful interview (I had the same problem with BTcino switches, Legrand brand)

**Comment by Adorem** [comment]
Thank you both for your answers. After several retry, reinstall
of zigbee2mqtt it seems the main raison was batterie too low on this device
and/or distance to the coordinator.
