### ISSUE TITLE
patch for Gledopto GL-S-004ZS

### ISSUE THREAD

**Issue by Wuppi68** [Koenkk/zigbee-herdsman-converters#1111]
--- a/devices.js
+++ b/devices.js
@@ -3996,6 +3996,14 @@ const devices = [
         extend: gledopto.light,
         supports: 'on/off, brightness, color temperature',
     },
+    {
+        zigbeeModel: ['GL-S-004ZS'],
+        model: 'GL-S-004ZS',
+        vendor: 'Gledopto',
+        description: 'Zigbee Smart RGB+CCT 4W MR16',
+        extend: gledopto.light,
+        supports: 'on/off, brightness, color temperature, color',
+    },
     {
         zigbeeModel: ['GL-S-007Z'],
         model: 'GL-S-007Z',

**Comment by Wuppi68** [comment]
Just a new block inside devices.js
tested and full working except some pings failed
bulb get on with last setting after getting power

**Comment by Koenkk** [comment]
added, thanks!
