### ISSUE TITLE
Osram Plug 01 - converter problem

### ISSUE THREAD

**Issue by Jogobo** [Koenkk/zigbee-herdsman-converters#1132]
I think this does not have an impact on functionality but I have the following messages from all Osram Lightify Plugs in my log every 2 to 30 seconds:

`Apr  6 08:23:07  npm[13171]: 2020-04-06 08:23:07: Received Zigbee message from 'mqtt_Switch_XYZ', type 'readResponse', cluster 'genBasic', data '{"zclVersion":1}' from endpoint 3 with groupID 0
Apr  6 08:23:07  npm[13171]: 2020-04-06 08:23:07: No converter available for 'AB3257001NJ' with cluster 'genBasic' and type 'readResponse' and data '{"zclVersion":1}'`

What converter is missing?

**Comment by Koenkk** [comment]
Do you have the availability feature enabled? If so this is expected and can be ignored.

**Comment by Jogobo** [comment]
Yes, 'availability' is enabled. 
As I did not realize any "misbehaving" of the plugs I already assumed that the messages don't have any impact.

Issue closed.
