### ISSUE TITLE
adding some proprietary extension - proprietary commands

### ISSUE THREAD

**Issue by Chrischi-** [Koenkk/zigbee-herdsman-converters#1134]
Hello, 

i wanted to add some proprietary extensions. For `proprietary attributes` this works fine. 
But `proprietary commands` do not work. 

@Koenkk Is it possible that zigbee-herdsman needs an update to know these extension?

![proprietary commands](https://user-images.githubusercontent.com/6323217/78539034-36004600-77f2-11ea-9ee3-ed21ff24c39f.jpg)

Change Transmission Power (value in the low byte, from -30 to 8) is very interesting.

**Comment by Koenkk** [comment]
The cluster + command needs to be added to https://github.com/Koenkk/zigbee-herdsman/blob/master/src/zcl/definition/cluster.ts . Proprietary commands is just a random name they put there I think.
