### ISSUE TITLE
Sylvania SMART+ 73693

### ISSUE THREAD

**Issue by dlashua** [Koenkk/zigbee-herdsman-converters#1144]
I have several Sylvania SMART+ 73693 bulbs.

When a color_temp is sent to these bulbs, they use the white LEDs. When an xy color is sent to them, they use RGB LEDs. When both are sent, they use RGB LEDs.

Home Assistant, with the current dev of Zigbee2MQTT and MQTT Discovery turned on, defaults to sending the xy color ONLY when a scene is created. So, this means that activating the scene causes the bulb to produce white light using the RGB LEDs, which is not desired (it's dimmer, and not quite the same color). 

If I manually configure TWO MQTT lights in Home Assistant for this single bulb, one with xy: true, and the other with color_temp: true, then the scenes are created and sent correctly by Home Assistant.

I tried adding "separate_control" to my Zigbee2MQTT config (a config option the Gledopto controller can take) but it had no effect.

Can this converter for this bulb type be modified to allow for separate control of white and RGB LEDs?

**Comment by Jogobo** [comment]
I use a couple of Osram Lightify Bulbs and Osram Lightify RGB strips. The latter should work very similar to the Sylvania SMART+ 73693 Bulbs.
What I found out is that, when you send a color_temp value the RGB strips make use of the white LEDs. When you send a color_xy value the RGB LEDs are used.
