### ISSUE TITLE
How to integrate new equipment

### ISSUE THREAD

**Issue by songzh96** [Koenkk/zigbee-herdsman-converters#1158]
Hi

I now have some new Zigbee products (Yishang series) from Schneider, how can I add these devices to the z2m gateway.

Best Regards
songzh

![image](https://user-images.githubusercontent.com/26770241/79242847-68bbd580-7ea7-11ea-8ebd-9047f4a8a1db.png)

**Comment by Koenkk** [comment]
https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
