### ISSUE TITLE
Add support for Müller Licht Tint Armaro

### ISSUE THREAD

**Issue by rnorden** [Koenkk/zigbee-herdsman-converters#1162]
Greetings,
seeing several tint devices by Müller Licht supported already, I want to share my issue pairing the 'Armaro' lamp.

**Setup:**
- CC2531
- Coordinator firmware version: 
```json
{
  "type":"zStack12",
  "meta":{
    "transportrev":2,
    "product":0,
    "majorrel":2,
    "minorrel":6,
    "maintrel":3,
    "revision":20190608
    }
}
```

Log: https://blog.nrdn.eu/zigbee2mqtt-debug-log.txt

I tried to follow the 'supporting new devices' howto but failed when zigbee2mqtt didn't show any interviewing process.

Can you point me to resources on interpreting the output of zigbee-herdsman or what to look for in the log?

**Comment by rnorden** [comment]
Before digging deeper into code figuring out whether there's any join/announce event received: Does zigbee2mqtt/herdsman support Zigbee 3.0?
As far as I searched the internet I know 3.0 coordinators support older devices but I dont know about the other way.

**Comment by Koenkk** [comment]
Zigbee 3.0 is not a problem, they can join fine no matter what coordinator you use (1.2 or 3.0). Make sure to check: https://www.zigbee2mqtt.io/information/FAQ.html#why-does-my-device-not-or-fail-to-pair first.

**Comment by rnorden** [comment]
Hey, I'm currently out of time. I'll dig deeper into this in a couple of days/weeks and come back at it.

**Comment by rnorden** [comment]
Pulled new commits into my setup this weekend, and my device was recognized as
```
{
  "ieeeAddr" : "0xec1bbdfffe7f358b",
  "type" : "Router",
  "networkAddress" : 8215,
  "model" : "ZG192910-4",
  "vendor" : "Sunricher",
  "description" : "Zigbee LED-controller",
  "friendly_name" : "Armaro",
  "manufacturerID" : 4635,
  "manufacturerName" : "MLI",
  "powerSource" : "Mains (single phase)",
  "modelID" : "CCT Lighting",
  "hardwareVersion" : 0,
  "softwareBuildID" : "2.5.3_r47",
  "dateCode" : "NULL",
  "lastSeen" : 1594373588445
}
```

So far it's working fine. How should I add that device to the documentation? Ideally I'd point out that this is bought from Müller Licht but it's a Sunricher, right?

**Comment by Koenkk** [comment]
Can you share the `data/database.db` entry of your device?

**Comment by rnorden** [comment]
```
{
  "id":4,
  "type":"Router",
  "ieeeAddr":"0xec1bbdfffe7f358b",
  "nwkAddr":8215,
  "manufId":4635,
  "manufName":"MLI",
  "powerSource":"Mains (single phase)",
  "modelId":"CCT Lighting",
  "epList":[
    1,
    242
  ],
  "endpoints":{
    "1":{
      "profId":49246,
      "epId":1,
      "devId":544,
      "inClusterList":[
        0,
        3,
        4,
        5,
        6,
        8,
        768,
        2821,
        4096
      ],
      "outClusterList":[
        25
      ],
      "clusters":{
        "genBasic":{
          "attributes":{
            "modelId":"CCT Lighting",
            "manufacturerName":"MLI",
            "powerSource":1,
            "zclVersion":3,
            "appVersion":40,
            "stackVersion":0,
            "hwVersion":0,
            "dateCode":"NULL",
            "swBuildId":"2.5.3_r47"
          }
        },
        "genOnOff":{
          "attributes":{
            "onOff":0
          }
        }
      },
      "binds":[

      ]
    },
    "242":{
      "profId":41440,
      "epId":242,
      "devId":102,
      "inClusterList":[
        33
      ],
      "outClusterList":[
        33
      ],
      "clusters":{

      },
      "binds":[

      ]
    }
  },
  "appVersion":40,
  "stackVersion":0,
  "hwVersion":0,
  "dateCode":"NULL",
  "swBuildId":"2.5.3_r47",
  "zclVersion":3,
  "interviewCompleted":true,
  "meta":{

  },
  "lastSeen":1594035921023
}
```

**Comment by Koenkk** [comment]
Thanks, should be identified as Muller Licht now.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by rnorden** [comment]
That's looking great, I'll pull the dev branch tonight and check again.
