### ISSUE TITLE
add support for ROB_200-008-0 

### ISSUE THREAD

**Issue by Steefph** [Koenkk/zigbee-herdsman-converters#1169]
I've added the following to my custom devices.js to get the different end-points to function on the ROB_200-008-0. Can this be added to the default file?

{
        zigbeeModel: ['ZG2833K4_EU06'],
        model: 'ROB_200-008-0',
        vendor: 'ROBB',
        description: 'Zigbee 4 button wall switch',
        supports: 'action',
        fromZigbee: [
            fz.command_on, fz.command_off, fz.command_move_with_on_off, fz.command_stop_with_on_off,
            fz.battery,
        ],
        toZigbee: [],
		meta: {multiEndpoint: true},
    },

**Comment by Koenkk** [comment]
added, thanks!

**Comment by Koenkk** [comment]
It seems that a device with this zigbeeModel is already supported (https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L71930) . Does it already work in the latest zigbee2mqtt?

**Comment by Steefph** [comment]
Well, it was working but not completely, the discription of this Sunrich device only shows 2 buttons while it actually has 4. 

adding this line "meta: {multiEndpoint: true}," could make it work correctly with the Sunricher ZG2833K4_EU06 work for the one from Robb.

**Comment by Koenkk** [comment]
@thumbnail since you added support for the sunricher device, does yours only have 2 buttons? (I expect its the same device but just a whitelabel as you mentioned in: https://github.com/Koenkk/zigbee-herdsman-converters/pull/613)

**Comment by thumbnail** [comment]
It has 4 (on+off for 2 groups):
![image](https://user-images.githubusercontent.com/4689114/79785790-bbccd700-8344-11ea-853f-dad0333172d3.png)


I'm not using the device with the firmware right now, and am not 100% confident that it works for both groups tbh.

**Comment by Steefph** [comment]
For both button groups the reply from Zigbee2mqtt was "on" or "off" while for example the 8 button version it shows "on_1", "off_1","on_2", "off_2",etc.
Adding the "meta: {multiEndpoint: true}," works if I also copy the lines "fromZigbee: []" from the 8 button device. Don't know if what I'm doing is correct in this case :)

**Comment by Koenkk** [comment]
Thanks @thumbnail, in that case I assume that the current definition is not complete. @Steefph I added your code and marked the Sunricher as a whitelabel. Assuming this can be closed now.
