### ISSUE TITLE
Error creating new Device implementation, can't finish pairing.

### ISSUE THREAD

**Issue by patricker** [Koenkk/zigbee-herdsman-converters#1175]
I'm working on adding support for a new device, "URC4450BC0-X-R".  Here is what I've built so far following the instructions:

{
    zigbeeModel: ['URC4450BC0-X-R'],
    model: 'XHK1-UE',
    vendor: 'XFINITY',
    description: 'Comcast Xfinity Home Classic Keypad',
    supports: '15 key security keypad',
    fromZigbee: [],
    toZigbee: [],
},

While adding this block does remove the, "unsupported device" error messages, I never get to the, "No converter available" messages because the device will not fully pair, and I get the dreaded, "Failed to interview 'xxxxx', device has not successfully been paired"

I removed my entry from devices.js to get more log messages, and have herdsmen debugging enabled through my Docker ENV, here is the pastebin for what I'm seeing (herdsmen debugging still goes to log.txt right?)
https://pastebin.com/fYxrSJzn

Later, I noticed some additional log messages for this device, maybe this will help:

debug 2020-04-22 10:04:57: Received Zigbee message from '0x000d6f000f678161', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":1,"manufacturerCode":4335,"imageType":0,"fileVersion":538315028}' from endpoint 1 with groupID 0
debug 2020-04-22 10:04:59: Received Zigbee message from '0x000d6f000f678161', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":1,"manufacturerCode":4335,"imageType":0,"fileVersion":538315028}' from endpoint 1 with groupID 0
debug 2020-04-22 10:05:02: Received Zigbee message from '0x000d6f000f678161', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":1,"manufacturerCode":4335,"imageType":0,"fileVersion":538315028}' from endpoint 1 with groupID 0
debug 2020-04-22 10:05:05: Received Zigbee message from '0x000d6f000f678161', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":1,"manufacturerCode":4335,"imageType":0,"fileVersion":538315028}' from endpoint 1 with groupID 0
debug 2020-04-22 10:05:08: Received Zigbee message from '0x000d6f000f678161', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":1,"manufacturerCode":4335,"imageType":0,"fileVersion":538315028}' from endpoint 1 with groupID 0

**Comment by Koenkk** [comment]
Can you share the herdsman debug logging when pairing this device?

To enable herdsman debug logging, see https://www.zigbee2mqtt.io/information/debug.html#zigbee-herdsman-debug-logging

**Comment by patricker** [comment]
info  2020-04-22 11:52:48: Device '0x000d6f000f678161' joined
info  2020-04-22 11:52:48: Starting interview of '0x000d6f000f678161'
info  2020-04-22 11:52:48: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":{"friendly_name":"0x000d6f000f678161"}}'
info  2020-04-22 11:52:48: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"0x000d6f000f678161"}}'
debug 2020-04-22 11:52:59: Device '0x000d6f000f678161' announced itself
info  2020-04-22 11:52:59: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_announced","message":"announce","meta":{"friendly_name":"0x000d6f000f678161"}}'
debug 2020-04-22 11:53:05: Received Zigbee message from '0x000d6f000f678161', type 'readResponse', cluster 'genBasic', data '{"modelId":"URC4450BC0-X-R"}' from endpoint 1 with groupID 0
warn  2020-04-22 11:53:05: Received message from unsupported device with Zigbee model 'URC4450BC0-X-R'
warn  2020-04-22 11:53:05: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
debug 2020-04-22 11:53:07: Received Zigbee message from '0x000d6f000f678161', type 'readResponse', cluster 'genBasic', data '{"manufacturerName":"Universal Electronics Inc"}' from endpoint 1 with groupID 0
warn  2020-04-22 11:53:07: Received message from unsupported device with Zigbee model 'URC4450BC0-X-R'
warn  2020-04-22 11:53:07: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
debug 2020-04-22 11:53:09: Received Zigbee message from '0x000d6f000f678161', type 'readResponse', cluster 'genBasic', data '{"powerSource":3}' from endpoint 1 with groupID 0
warn  2020-04-22 11:53:09: Received message from unsupported device with Zigbee model 'URC4450BC0-X-R'
warn  2020-04-22 11:53:09: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
debug 2020-04-22 11:53:11: Received Zigbee message from '0x000d6f000f678161', type 'readResponse', cluster 'genBasic', data '{"zclVersion":1}' from endpoint 1 with groupID 0
warn  2020-04-22 11:53:11: Received message from unsupported device with Zigbee model 'URC4450BC0-X-R'
warn  2020-04-22 11:53:11: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
debug 2020-04-22 11:53:13: Received Zigbee message from '0x000d6f000f678161', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 1 with groupID 0
warn  2020-04-22 11:53:13: Received message from unsupported device with Zigbee model 'URC4450BC0-X-R'
warn  2020-04-22 11:53:13: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
debug 2020-04-22 11:53:15: Received Zigbee message from '0x000d6f000f678161', type 'readResponse', cluster 'genBasic', data '{"stackVersion":0}' from endpoint 1 with groupID 0
warn  2020-04-22 11:53:15: Received message from unsupported device with Zigbee model 'URC4450BC0-X-R'
warn  2020-04-22 11:53:15: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
debug 2020-04-22 11:53:17: Received Zigbee message from '0x000d6f000f678161', type 'readResponse', cluster 'genBasic', data '{"hwVersion":1}' from endpoint 1 with groupID 0
warn  2020-04-22 11:53:17: Received message from unsupported device with Zigbee model 'URC4450BC0-X-R'
warn  2020-04-22 11:53:17: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
debug 2020-04-22 11:53:19: Received Zigbee message from '0x000d6f000f678161', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 1 with groupID 0
warn  2020-04-22 11:53:19: Received message from unsupported device with Zigbee model 'URC4450BC0-X-R'
warn  2020-04-22 11:53:19: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
debug 2020-04-22 11:53:21: Received Zigbee message from '0x000d6f000f678161', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 1 with groupID 0
warn  2020-04-22 11:53:21: Received message from unsupported device with Zigbee model 'URC4450BC0-X-R'
warn  2020-04-22 11:53:21: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
debug 2020-04-22 11:53:23: Received Zigbee message from '0x000d6f000f678161', type 'readResponse', cluster 'ssIasZone', data '{"iasCieAddr":"0x0000000000000000","zoneState":0}' from endpoint 1 with groupID 0
warn  2020-04-22 11:53:23: Received message from unsupported device with Zigbee model 'URC4450BC0-X-R'
warn  2020-04-22 11:53:23: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
debug 2020-04-22 11:53:26: Saving state to file /app/data/state.json
debug 2020-04-22 11:53:27: Received Zigbee message from '0x000d6f000f678161', type 'readResponse', cluster 'ssIasZone', data '{"iasCieAddr":"0x00124b000be8af6c","zoneState":0}' from endpoint 1 with groupID 0
warn  2020-04-22 11:53:27: Received message from unsupported device with Zigbee model 'URC4450BC0-X-R'
warn  2020-04-22 11:53:27: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
debug 2020-04-22 11:53:29: Received Zigbee message from '0x000d6f000f678161', type 'readResponse', cluster 'ssIasZone', data '{"iasCieAddr":"0x00124b000be8af6c","zoneState":0}' from endpoint 1 with groupID 0
warn  2020-04-22 11:53:29: Received message from unsupported device with Zigbee model 'URC4450BC0-X-R'
warn  2020-04-22 11:53:29: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
debug 2020-04-22 11:53:31: Received Zigbee message from '0x000d6f000f678161', type 'readResponse', cluster 'ssIasZone', data '{"iasCieAddr":"0x00124b000be8af6c","zoneState":0}' from endpoint 1 with groupID 0
warn  2020-04-22 11:53:31: Received message from unsupported device with Zigbee model 'URC4450BC0-X-R'
warn  2020-04-22 11:53:31: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
debug 2020-04-22 11:53:33: Received Zigbee message from '0x000d6f000f678161', type 'readResponse', cluster 'ssIasZone', data '{"iasCieAddr":"0x00124b000be8af6c","zoneState":0}' from endpoint 1 with groupID 0
warn  2020-04-22 11:53:33: Received message from unsupported device with Zigbee model 'URC4450BC0-X-R'
warn  2020-04-22 11:53:33: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
debug 2020-04-22 11:53:36: Received Zigbee message from '0x000d6f000f678161', type 'readResponse', cluster 'ssIasZone', data '{"iasCieAddr":"0x00124b000be8af6c","zoneState":0}' from endpoint 1 with groupID 0
warn  2020-04-22 11:53:36: Received message from unsupported device with Zigbee model 'URC4450BC0-X-R'
warn  2020-04-22 11:53:36: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
error 2020-04-22 11:53:36: Failed to interview '0x000d6f000f678161', device has not successfully been paired

**Comment by Koenkk** [comment]
This is not the herdsman debug logging, please check https://www.zigbee2mqtt.io/information/debug.html#zigbee-herdsman-debug-logging carefully.

**Comment by patricker** [comment]
Sorry about that, I found it. 
https://pastebin.com/H78p2z3W

**Comment by Koenkk** [comment]
The ias enrollment fails, I'm not sure if this is problematic for this device.

In order to continue we would need to sniff the traffic with the original gateway to figure out how to correctly configure this device and get button events. (https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html)

**Comment by patricker** [comment]
I don't have it hooked up to a pre-existing bridge. Does this linked code help?  It's code for working with a number of different keypads, including the model I have: https://github.com/arnbme/nyckelharpa/blob/master/Centralite-Keypad.groovy#L136

**Comment by Koenkk** [comment]
Maybe, can you provide the zigbee herdsman debug loggin when pressing buttons on the device?

To enable herdsman debug logging, see https://www.zigbee2mqtt.io/information/debug.html#zigbee-herdsman-debug-logging

**Comment by patricker** [comment]
I can't get it to send any additional messages, no matter what buttons I press, besides the ones already in the log.  Maybe it's expecting to be configured first by having codes or the like written to it, not sure...  Sorry, proving a lot harder than I expected :)

**Comment by Koenkk** [comment]
Do you see anything in the herdsman debug log when running with:

```js
{
    zigbeeModel: ['URC4450BC0-X-R'],
    model: 'XHK1-UE',
    vendor: 'XFINITY',
    description: 'Comcast Xfinity Home Classic Keypad',
    supports: '15 key security keypad',
    fromZigbee: [],
    toZigbee: [],
    meta: {configureKey: 1},
    configure: async (device, coordinatorEndpoint) => {
        const endpoint = device.getEndpoint(1);
        await bind(endpoint, coordinatorEndpoint, ['ssIasZone', 'ssIasAce']);
    },
},
```

**Comment by patricker** [comment]
Yay, I got something!  I had tried something similar to what you had, but I was focused on 'genBasic' and not 'ssIasAce'.

May 04 16:19:16 iotcontroller npm[9353]: zigbee2mqtt:debug 2020-05-04 16:19:16: Received Zigbee message from '0x000d6f000f678161', type 'commandArm', cluster 'ssIasAc
May 04 16:19:16 iotcontroller npm[9353]: zigbee2mqtt:debug 2020-05-04 16:19:16: No converter available for 'XHK1-UE' with cluster 'ssIasAce' and type 'commandArm' and
May 04 16:19:16 iotcontroller npm[9353]: 2020-05-04T15:19:16.749Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
May 04 16:18:51 iotcontroller npm[9353]: 2020-05-04T15:18:51.958Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,100,1,0,100]
May 04 16:18:51 iotcontroller npm[9353]: 2020-05-04T15:18:51.958Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 4 - 1 - [0] - 100
May 04 16:18:51 iotcontroller npm[9353]: 2020-05-04T15:18:51.958Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- AF - dataRequest - {"status":0}
May 04 16:18:51 iotcontroller npm[9353]: 2020-05-04T15:18:51.958Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
May 04 16:18:53 iotcontroller npm[9353]: 2020-05-04T15:18:53.938Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,68,128,0,1,60,250]
May 04 16:18:53 iotcontroller npm[9353]: 2020-05-04T15:18:53.939Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,68,128,0,1,60,250]
May 04 16:18:53 iotcontroller npm[9353]: 2020-05-04T15:18:53.939Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 4 - 128 - [0,1,60] - 250
May 04 16:18:53 iotcontroller npm[9353]: 2020-05-04T15:18:53.939Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - dataConfirm - {"status":0,"endpoint":1,"transid":60}
May 04 16:18:53 iotcontroller npm[9353]: 2020-05-04T15:18:53.939Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
May 04 16:18:54 iotcontroller npm[9353]: 2020-05-04T15:18:54.254Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,32,68,129,0,0,25,0,159,245,1,13,0,128,0,50,158,150,0,0,12,1,89,1,0,91,17,0,0,33,81,35,16,159,245,29,11]
May 04 16:18:54 iotcontroller npm[9353]: 2020-05-04T15:18:54.254Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,32,68,129,0,0,25,0,159,245,1,13,0,128,0,50,158,150,0,0,12,1,89,1,0,91,17,0,0,33,81,35,16,159,245,29,11]
May 04 16:18:54 iotcontroller npm[9353]: 2020-05-04T15:18:54.254Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 32 - 2 - 4 - 129 - [0,0,25,0,159,245,1,13,0,128,0,50,158,150,0,0,12,1,89,1,0,91,17,0,0,33,81,35,16,159,245,29] - 11
May 04 16:18:54 iotcontroller npm[9353]: 2020-05-04T15:18:54.255Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - incomingMsg - {"groupid":0,"clusterid":25,"srcaddr":62879,"srcendpoint":1,"dstendpoint":13,"wasbroadcast":0,"linkquality":128,"securityuse":0,"timestamp":9870898,"transseqnumber":0,"len":12,"data":{"type":"Buffer","data":[1,89,1,0,91,17,0,0,33,81,35,16]}}
May 04 16:18:54 iotcontroller npm[9353]: 2020-05-04T15:18:54.256Z zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":false},"transactionSequenceNumber":89,"manufacturerCode":null,"commandIdentifier":1},"Payload":{"fieldControl":0,"manufacturerCode":4443,"imageTyp
May 04 16:18:54 iotcontroller npm[9353]: zigbee2mqtt:debug 2020-05-04 16:18:54: Received Zigbee message from '0x0022a3000014e087', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"manufacturerCode":4443,"imageType":0,"fileVersion":270749985}' from endpoint 1 with groupID 0

**Comment by patricker** [comment]
I got it to send a second one by triggering the tamper sensor on the back:

May 04 16:33:52 iotcontroller npm[9353]: 2020-05-04T15:33:52.896Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
May 04 16:33:53 iotcontroller npm[9353]: 2020-05-04T15:33:53.199Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,23,68,129,0,0,1,5,32,67,1,1,0,107,0,22,124,193,0,0,3,17,24,7,32,67,29,6]
May 04 16:33:53 iotcontroller npm[9353]: 2020-05-04T15:33:53.199Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,23,68,129,0,0,1,5,32,67,1,1,0,107,0,22,124,193,0,0,3,17,24,7,32,67,29,6]
May 04 16:33:53 iotcontroller npm[9353]: 2020-05-04T15:33:53.199Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 23 - 2 - 4 - 129 - [0,0,1,5,32,67,1,1,0,107,0,22,124,193,0,0,3,17,24,7,32,67,29] - 6
May 04 16:33:53 iotcontroller npm[9353]: 2020-05-04T15:33:53.200Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - incomingMsg - {"groupid":0,"clusterid":1281,"srcaddr":17184,"srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"linkquality":107,"securityuse":0,"timestamp":12680214,"transseqnumber":0,"len":3,"data":{"type":"Buffer","data":[17,24,7]}}
May 04 16:33:53 iotcontroller npm[9353]: 2020-05-04T15:33:53.201Z zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":true},"transactionSequenceNumber":24,"manufacturerCode":null,"commandIdentifier":7},"Payload":{}},"address":17184,"endpoint":1,"linkquality":107,"
May 04 16:33:53 iotcontroller npm[9353]: 2020-05-04T15:33:53.204Z zigbee-herdsman:controller:log Skipping command 'getPanelStatus' because it is missing from the lookup
May 04 16:33:53 iotcontroller npm[9353]: 2020-05-04T15:33:53.204Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
May 04 16:33:53 iotcontroller npm[9353]: 2020-05-04T15:33:53.960Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,68,128,0,1,86,144]
May 04 16:33:53 iotcontroller npm[9353]: 2020-05-04T15:33:53.961Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,68,128,0,1,86,144]
May 04 16:33:53 iotcontroller npm[9353]: 2020-05-04T15:33:53.961Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 4 - 128 - [0,1,86] - 144
May 04 16:33:53 iotcontroller npm[9353]: 2020-05-04T15:33:53.961Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - dataConfirm - {"status":0,"endpoint":1,"transid":86}
May 04 16:33:53 iotcontroller npm[9353]: 2020-05-04T15:33:53.961Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
May 04 16:33:54 iotcontroller npm[9353]: 2020-05-04T15:33:54.232Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,68,128,0,1,87,145]
May 04 16:33:54 iotcontroller npm[9353]: 2020-05-04T15:33:54.233Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,68,128,0,1,87,145]
May 04 16:33:54 iotcontroller npm[9353]: 2020-05-04T15:33:54.233Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 4 - 128 - [0,1,87] - 145
May 04 16:33:54 iotcontroller npm[9353]: 2020-05-04T15:33:54.233Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - dataConfirm - {"status":0,"endpoint":1,"transid":87}
May 04 16:33:54 iotcontroller npm[9353]: 2020-05-04T15:33:54.233Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
May 04 16:33:54 iotcontroller npm[9353]: 2020-05-04T15:33:54.250Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,23,68,129,0,0,1,5,32,67,1,1,0,89,0,255,136,193,0,0,3,17,25,7,32,67,29,40]
May 04 16:33:54 iotcontroller npm[9353]: 2020-05-04T15:33:54.250Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,23,68,129,0,0,1,5,32,67,1,1,0,89,0,255,136,193,0,0,3,17,25,7,32,67,29,40]
May 04 16:33:54 iotcontroller npm[9353]: 2020-05-04T15:33:54.250Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 23 - 2 - 4 - 129 - [0,0,1,5,32,67,1,1,0,89,0,255,136,193,0,0,3,17,25,7,32,67,29] - 40
May 04 16:33:54 iotcontroller npm[9353]: 2020-05-04T15:33:54.250Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - incomingMsg - {"groupid":0,"clusterid":1281,"srcaddr":17184,"srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"linkquality":89,"securityuse":0,"timestamp":12683519,"transseqnumber":0,"len":3,"data":{"type":"Buffer","data":[17,25,7]}}
May 04 16:33:54 iotcontroller npm[9353]: 2020-05-04T15:33:54.252Z zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":true},"transactionSequenceNumber":25,"manufacturerCode":null,"commandIdentifier":7},"Payload":{}},"address":17184,"endpoint":1,"linkquality":89,"g
May 04 16:33:54 iotcontroller npm[9353]: 2020-05-04T15:33:54.252Z zigbee-herdsman:controller:log Skipping command 'getPanelStatus' because it is missing from the lookup
May 04 16:33:54 iotcontroller npm[9353]: 2020-05-04T15:33:54.252Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
May 04 16:33:56 iotcontroller npm[9353]: 2020-05-04T15:33:56.251Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,29,68,129,0,0,0,5,32,67,1,1,0,102,0,107,161,193,0,0,9,25,23,0,0,0,0,23,0,0,32,67,29,189]
May 04 16:33:56 iotcontroller npm[9353]: 2020-05-04T15:33:56.251Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,29,68,129,0,0,0,5,32,67,1,1,0,102,0,107,161,193,0,0,9,25,23,0,0,0,0,23,0,0,32,67,29,189]
May 04 16:33:56 iotcontroller npm[9353]: 2020-05-04T15:33:56.251Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 29 - 2 - 4 - 129 - [0,0,0,5,32,67,1,1,0,102,0,107,161,193,0,0,9,25,23,0,0,0,0,23,0,0,32,67,29] - 189
May 04 16:33:56 iotcontroller npm[9353]: 2020-05-04T15:33:56.251Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - incomingMsg - {"groupid":0,"clusterid":1280,"srcaddr":17184,"srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"linkquality":102,"securityuse":0,"timestamp":12689771,"transseqnumber":0,"len":9,"data":{"type":"Buffer","data":[25,23,0,0,0,0,23,0,0]}}
May 04 16:33:56 iotcontroller npm[9353]: 2020-05-04T15:33:56.252Z zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":true},"transactionSequenceNumber":23,"manufacturerCode":null,"commandIdentifier":0},"Payload":{"zonestatus":0,"extendedstatus":0}},"address":17184
May 04 16:33:56 iotcontroller npm[9353]: zigbee2mqtt:debug 2020-05-04 16:33:56: Received Zigbee message from '0x000d6f000f678161', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"zonestatus":0,"extendedstatus":0}' from endpoint 1 with groupID 0
May 04 16:33:56 iotcontroller npm[9353]: zigbee2mqtt:debug 2020-05-04 16:33:56: No converter available for 'XHK1-UE' with cluster 'ssIasZone' and type 'commandStatusChangeNotification' and data '{"zonestatus":0,"extendedstatus":0}'

**Comment by Koenkk** [comment]
The things you have to be looking for is `Skipping command 'getPanelStatus' because it is missing from the lookup` (where `getPanelStatus` can also be something else).

Next you have to add this to `/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/events.js` `CommandsLookup`, for `getPanelStatus` add `'getPanelStatus': 'commandGetPanelStatus',`.

After restarting zigbee2mqtt you will get `No converter available..` messages in your log when `getPanelStatus` is triggered.

**Comment by patricker** [comment]
That helped a lot.  I'm getting real messages and am able to parse them.  I'll keep working on the config.

**Comment by Rockman18** [comment]
@patricker : 
I just bought  the same keypad but I can't pair it at all. I try to plug the batteries pushing the tamper switch, to plug the batteries without pushing the tamper switch. But In 95% of the case the interview start then failed, else, sometimes device announces itself and fails. Have you try to pair the keypad since May ? Have you gone on your investigation ?

**Comment by patricker** [comment]
@Rockman18 I was able to get a very simple pairing, but I believe I only succeed in getting sensor data back.  I couldn't figure out how to get codes back in a reasonable amount of time, and ended up dropping the effort.

**Comment by dettrick** [comment]
Hi, I've got the arm and disarm working, as well as the temperature and battery. Just got the status' working as well. I will share my devices.js file that i've used. To skip to the relavent code the zigbee model is URC4450BC0-X-R on line 8333 
[devices.zip](https://github.com/Koenkk/zigbee-herdsman-converters/files/5597524/devices.zip)

Only thing i'm still trying to figure out is how to set delay.

**Comment by lancelon** [comment]
> Just got the status' working as well.

Does this mean you're able to query the status of the keypad from HA?

**Comment by Matssa56** [comment]
> @patricker
> 
> Hi, I've got the arm and disarm working, as well as the temperature and battery. Just got the status' working as well. I will share my devices.js file that i've used. To skip to the relavent code the zigbee model is URC4450BC0-X-R on line 8333
> [devices.zip](https://github.com/Koenkk/zigbee-herdsman-converters/files/5597524/devices.zip)
> 
> Only thing i'm still trying to figure out is how to set delay.

Tried to use your devices.js by adding the new code (lines 43 to 64, 76 to 126 and 8333). However I'm using the Xfinity XHK1-TC TKA105 which is very similar to yours. 

I manged to get some info back but I can't seem to make the bottom LED work, getting the top one to be fixed or getting a good feedback. 
Indeed I don't see any MQTT messsage if there is a fail, only see arm or disarm with the code attached Here is what I get regularly:
`{
    "battery_low": false,
    "contact": true,
    "last_seen": "2021-01-13T10:28:45.862Z",
    "linkquality": 81,
    "occupancy": false,
    "tamper": false
}`

Here is what I get when arming:
`{
    "action": "arm_day_zones",
    "action_code": "1234",
    "action_transaction": 59,
    "action_zone": 23,
    "battery_low": false,
    "contact": true,
    "last_seen": "2021-01-13T10:31:34.155Z",
    "linkquality": 81,
    "occupancy": false,
    "tamper": false
}`

If  I use any other digit, it still disarms :-S
`{
    "action": "disarm",
    "action_code": "6788",
    "action_transaction": 72,
    "action_zone": 23,
    "battery_low": false,
    "contact": true,
    "last_seen": "2021-01-13T10:33:39.427Z",
    "linkquality": 81,
    "occupancy": false,
    "tamper": false
}`
So yeah not sure how I can get a better feedback, how can I help?

**Comment by Multipage** [comment]
@Matssa56 :
It always sends the action:disarm if it's armed.
It's up to you to check the alarmcode and send the response back to the keypad.
The keypad itself is a 'dumb'-device.

Currently the code for the XHK1-UE is merged in the dev branch of Zigbee2MQTT and all the leds are working , or least for the XHK1-UE. I think the XHK1-TC should work to because the only difference afaik is that it's manufactured by Technicolor.
