### ISSUE TITLE
Add support to NEO Motion Sensor

### ISSUE THREAD

**Issue by losdolobus** [Koenkk/zigbee-herdsman-converters#1179]
I need some help because I´m not able to figure out the message from the sensor. It is a motion, temperature and humidity sensor with anti-dismantle alert from Neo Coolcam.
https://szneo.com/en/products/show.php?id=239

**devices.js**
```
{
    zigbeeModel: ['hfcudw5'], 
    model: 'PD0780', //  (NAS-PD0780 V3)
    vendor: 'Neo Coolcam',
    description: 'Motion/Temperature/Humidity Sensor with anti-dismantle ', 
    supports: 'motion, temperature and humidity', 
    fromZigbee: [], 
    toZigbee: [], 
},
```

The message from the logs is:

```
zigbee2mqtt:debug 2020-04-22 22:00:53: Received Zigbee message from '0xec1bbdfffe6c1d1d', type 'commandSetDataResponse', cluster 'manuSpecificTuyaDimmer', data '{"status":0,"transid":2,"dp":619,"fn":0,"data":{"type":"Buffer","data":[0,0,0,18]}}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-04-22 22:00:53: Received Zigbee message from '0xec1bbdfffe6c1d1d', type 'commandSetDataResponse', cluster 'manuSpecificTuyaDimmer', data '{"status":0,"transid":2,"dp":620,"fn":0,"data":{"type":"Buffer","data":[0,0,0,27]}}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-04-22 22:00:53: Received Zigbee message from '0xec1bbdfffe6c1d1d', type 'commandSetDataResponse', cluster 'manuSpecificTuyaDimmer', data '{"status":0,"transid":2,"dp":621,"fn":0,"data":{"type":"Buffer","data":[0,0,0,45]}}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-04-22 22:00:53: Received Zigbee message from '0xec1bbdfffe6c1d1d', type 'commandSetDataResponse', cluster 'manuSpecificTuyaDimmer', data '{"status":0,"transid":2,"dp":622,"fn":0,"data":{"type":"Buffer","data":[0,0,0,80]}}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-04-22 22:00:53: Received Zigbee message from '0xec1bbdfffe6c1d1d', type 'commandSetDataResponse', cluster 'manuSpecificTuyaDimmer', data '{"status":0,"transid":2,"dp":1126,"fn":0,"data":{"type":"Buffer","data":[0]}}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-04-22 22:00:53: Received Zigbee message from '0xec1bbdfffe6c1d1d', type 'commandSetDataResponse', cluster 'manuSpecificTuyaDimmer', data '{"status":0,"transid":4,"dp":359,"fn":0,"data":{"type":"Buffer","data":[0]}}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-04-22 22:00:53: Received Zigbee message from '0xec1bbdfffe6c1d1d', type 'commandSetDataResponse', cluster 'manuSpecificTuyaDimmer', data '{"status":0,"transid":2,"dp":616,"fn":0,"data":{"type":"Buffer","data":[0,0,0,215]}}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-04-22 22:00:53: Received Zigbee message from '0xec1bbdfffe6c1d1d', type 'commandSetDataResponse', cluster 'manuSpecificTuyaDimmer', data '{"status":0,"transid":2,"dp":617,"fn":0,"data":{"type":"Buffer","data":[0,0,0,63]}}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-04-22 22:00:53: Received Zigbee message from '0xec1bbdfffe6c1d1d', type 'commandSetDataResponse', cluster 'manuSpecificTuyaDimmer', data '{"status":0,"transid":2,"dp":1137,"fn":0,"data":{"type":"Buffer","data":[4]}}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-04-22 22:00:56: Received Zigbee message from '0xec1bbdfffe6c1d1d', type 'commandSetDataResponse', cluster 'manuSpecificTuyaDimmer', data '{"status":0,"transid":2,"dp":622,"fn":0,"data":{"type":"Buffer","data":[0,0,0,80]}}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-04-22 22:00:56: Received Zigbee message from '0xec1bbdfffe6c1d1d', type 'commandSetDataResponse', cluster 'manuSpecificTuyaDimmer', data '{"status":0,"transid":4,"dp":359,"fn":0,"data":{"type":"Buffer","data":[0]}}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-04-22 22:00:57: Received Zigbee message from '0xec1bbdfffe6c1d1d', type 'commandSetDataResponse', cluster 'manuSpecificTuyaDimmer', data '{"status":0,"transid":2,"dp":616,"fn":0,"data":{"type":"Buffer","data":[0,0,0,215]}}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-04-22 22:00:58: Received Zigbee message from '0xec1bbdfffe6c1d1d', type 'commandSetDataResponse', cluster 'manuSpecificTuyaDimmer', data '{"status":0,"transid":2,"dp":617,"fn":0,"data":{"type":"Buffer","data":[0,0,0,63]}}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-04-22 22:00:59: Received Zigbee message from '0xec1bbdfffe6c1d1d', type 'commandSetDataResponse', cluster 'manuSpecificTuyaDimmer', data '{"status":0,"transid":2,"dp":1137,"fn":0,"data":{"type":"Buffer","data":[4]}}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-04-22 22:01:00: Received Zigbee message from '0xec1bbdfffe6c1d1d', type 'commandSetDataResponse', cluster 'manuSpecificTuyaDimmer', data '{"status":0,"transid":4,"dp":357,"fn":0,"data":{"type":"Buffer","data":[0]}}' from endpoint 1 with groupID 0
```

It throws this message too but seems unimportant:
`zigbee2mqtt:debug 2020-04-22 21:29:48: Received Zigbee message from '0xec1bbdfffe6c1d1d', type 'attributeReport', cluster 'genBasic', data '{"appVersion":73}' from endpoint 1 with groupID 0`

Any help is appreciated.

Thank you.

**Comment by Koenkk** [comment]
Seems to be a TuYa device. @kirovilya could you maybe help?

**Comment by kirovilya** [comment]
You need to understand what the data in the messages means. This can be done by sniffing traffic between the device and the original gateway.
You need to find out what the code in dp means and the values ​​in data.
Here is an example of processing this data for a thermostat: https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/converters/fromZigbee.js#L242

**Comment by maciii** [comment]
Hi. I have same device and I discovered some data. I tried to add some code, but I'm not good at this at all, can anyone help me with this?

`neo_motion_temp_hum: {
        cluster: 'manuSpecificTuyaDimmer',
        type: ['commandSetDataResponse', 'commandGetData'],
        convert: (model, msg, publish, options, meta) => {
            const dp = msg.data.dp;

            switch (dp) {
            
            //transid:4 - unknown function
            case 357: {// 0x01 0x65: Motion detected data [0] [1] - 
                const pohyb = msg.data.data[0];
                if (pohyb > 0) {
                    return {occupancy: true};
                } else {
                    return {occupancy: false};
                }
            }
            case 359: // 0x01 0x67:  Tamper switch???? data [0] [1] 
            case 362: // 0x01 0x6A:  unknown data [0]
            
            //transid:2 - unknown function
            case 616: // 0x02 0x68:  temperature [0,0,0,XX]  XX known values 215,218,219, 221-228
                const temperature = parseFloat(msg.data.data[3]) / 10.0;    
                return {temperature: calibrateAndPrecisionRoundOptions(temperature, options, 'temperature')};
           
            case 617: // 0x02 0x69:  humidity [0,0,0,XX]  XX known values 54-59,63 so it will be humidity
                return {humidity: calibrateAndPrecisionRoundOptions(msg.data.data[3], options, 'humidity')};
            
            case 619: // 0x02 0x6B:  unknown [0,0,0,XX]  XX known values 18
            case 620: // 0x02 0x6C:  unknown [0,0,0,XX]  XX known values 27
            case 621: // 0x02 0x6D:  unknown [0,0,0,XX]  XX known values 45
            case 622: // 0x02 0x6E:  unknown [0,0,0,XX]  XX known values 80

            case 1126: // 0x04 0x66:  unknown data [0] [4] 
            case 1137: // 0x04 0x71:  unknown data [4]
            
            default: // Unknown code
                console.log(`hfcudw5: Unhandled DP #${dp}: ${JSON.stringify(msg.data)}`);
            }
        },`

**Comment by maciii** [comment]
Now I can see some results. But I do not know how to add this data into HomeAssistant :-(

`zigbee2mqtt:info  2020-06-21 21:33:27: MQTT publish: topic 'zigbee2mqtt/0xec1bbdfffe6c1e20', payload '{"occupancy":false,"linkquality":36,"running":true,"humidity":57}'
zigbee2mqtt:debug 2020-06-21 21:34:14: Received Zigbee message from '0xec1bbdfffe6c1e20', type 'commandSetDataResponse', cluster 'manuSpecificTuyaDimmer', data '{"status":0,"transid":4,"dp":357,"fn":0,"data":{"type":"Buffer","data":[1]}}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-06-21 21:34:14: MQTT publish: topic 'zigbee2mqtt/0xec1bbdfffe6c1e20', payload '{"occupancy":true,"linkquality":65,"running":true,"humidity":57}'
zigbee2mqtt:debug 2020-06-21 21:34:23: Received Zigbee message from '0xec1bbdfffe6c1e20', type 'commandSetDataResponse', cluster 'manuSpecificTuyaDimmer', data '{"status":0,"transid":2,"dp":616,"fn":0,"data":{"type":"Buffer","data":[0,0,0,217]}}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-06-21 21:34:23: MQTT publish: topic 'zigbee2mqtt/0xec1bbdfffe6c1e20', payload '{"occupancy":true,"linkquality":70,"running":true,"humidity":57,"temperature":21.7}'`

**Comment by maciii** [comment]
Hi all, can ANYONE help with "polishing" source code and add this device into official repository for Home Assistant usage? Look for ZIP file attached. Look for last device in devices.js and for "coolcam_motion_temp_hum" in fromZigbee.js.

[Neo NAS-PD07B.zip](https://github.com/Koenkk/zigbee-herdsman-converters/files/4814562/Neo.NAS-PD07B.zip)

**Comment by hossface** [comment]
I have the same sensor did you get it working in the end?

**Comment by seoulop** [comment]
> Hi all, can ANYONE help with "polishing" source code and add this device into official repository for Home Assistant usage? Look for ZIP file attached. Look for last device in devices.js and for "coolcam_motion_temp_hum" in fromZigbee.js.
> 
> [Neo NAS-PD07B.zip](https://github.com/Koenkk/zigbee-herdsman-converters/files/4814562/Neo.NAS-PD07B.zip)

I added the device to HA with your devices.js and fromZigbee.js by add following line in the homeassistant.js
	'NAS-PD07B': [cfg.sensor_temperature, cfg.binary_sensor_occupancy, cfg.sensor_humidity, cfg.binary_sensor_tamper],

But my results are little bit diffrent from yours. 
'{"unknown_1137":4,"linkquality":123,"humidity":45,"temperature":1.1,"occupancy":false,"unknown_362":0,"unknown_619":18,"unknown_620":27,"unknown_621":45,"unknown_622":80,"unknown_1126":4,"tamper":true}'
zigbee2mqtt:error 2020-08-11 22:00:36: Failed to call 'Receive' 'onZigbeeEvent' (ReferenceError: temperature is not defined
    at Object.convert (/zigbee2mqtt-1.14.2/node_modules/zigbee-herdsman-converters/converters/fromZigbee.js:4979:72)
    at /zigbee2mqtt-1.14.2/lib/extension/receive.js:168:41
    at Array.forEach (<anonymous>)
    at Receive.onZigbeeEvent (/zigbee2mqtt-1.14.2/lib/extension/receive.js:166:20)
    at Controller.callExtensionMethod (/zigbee2mqtt-1.14.2/lib/controller.js:360:44)
    at Controller.onZigbeeEvent (/zigbee2mqtt-1.14.2/lib/controller.js:246:14)
    at Zigbee.emit (events.js:315:20)
    at Controller.<anonymous> (/zigbee2mqtt-1.14.2/lib/zigbee.js:67:52)
    at Controller.emit (events.js:315:20)
    at Controller.<anonymous> (/zigbee2mqtt-1.14.2/node_modules/zigbee-herdsman/dist/controller/controller.js:503:22))

I don't want to know about unknows :) but temperature is not correct and tamper is always true.
I completely have no idea what should I have to do, because I don't know about these codes at all and I just copied your files :D
Would you please let me know last devices.js and fromZigbee.js you used?

**Comment by Dcashe** [comment]
I have the same sensor. Did someone find a solution to this issue? ?

**Comment by jvrrr** [comment]
> I have the same sensor. Did someone find a solution to this issue? ?

Maybe create a new topic and refer to this topic.
It seems it is almost figure out.
