### ISSUE TITLE
battery_low is inconssitant

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee-herdsman-converters#1214]
I noticed battery_low is inconsistent, sometimes it is a boolean value other times it is 0 or 1.

Not sure which one is correct, but I think it would be better to align all of them to be either true/false or 1/0 ?

**Comment by Koenkk** [comment]
It should be true/false, which devices show 1/0?

**Comment by sjorge** [comment]
The eurotronic trv is one example I found.

**Comment by Koenkk** [comment]
Should be fixed in latest dev branch (in a few hours from now). Thanks! Assuming this can be closed now.
