### ISSUE TITLE
Tuya TRV should report piHeatingDemand

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee-herdsman-converters#1215]
Most TRV's report piHeatingDemand which is the valve open %... looks like the Tuya convert also gets this value form the special format it uses but returns it as `position`.

This should be renamed to match the others.

https://github.com/Koenkk/zigbee-herdsman-converters/blob/300d373e4b282fbfbcce0362c4d25949bb4fdfce/converters/fromZigbee.js#L301

@Koenkk is it still Ok to change this? Or we report it as both and remove the 'position' after a deprecation periode? Has this made it into a release yet? It only got recently added.

**Comment by Koenkk** [comment]
I assume you mean the Siterwell GS361A-H04, this device is supported in 1.13.0 so it should return both `position` and `piHeatingDemand` (to prevent a breaking change). In the PR please add `// DEPRECATED` with a link to this issue.

**Comment by sjorge** [comment]
I did some more testing with this device, it actually never returns the value as far as I can tell... which sucks as I need it for something :(

So I do think we can rename it, would be nice to be able to actually get it to return/report it though.

**Comment by Koenkk** [comment]
@kirovilya do you have any experience with this device?

**Comment by kirovilya** [comment]
I added support for a similar thermostat compatible with Tuya Gateway
https://www.moeshouse.com/products/zigbee-smart-thermostatic-radiator-valve-controller-trv-thermostat-tuya-temperature-voice-control-works-with-alexa-google-home

My position values ​​were either 0 or 100. If you think it is necessary, let's rename it.

Now I no longer have this thermostat - I left the customer :)

**Comment by sjorge** [comment]
I currently switched back to the eurotronic trv, although the tuya one works OK. It only seems to report changes once every hour.

Also mine was missing battery and pi_heating_demand/position as it was never reported. The hardware itself was also very loud.

I have not decided if I want to return it or not yet, as it might be good to have as a testing device.
