### ISSUE TITLE
Zemismart Model: LXT56-LS27LX1.6

### ISSUE THREAD

**Issue by krasevych** [Koenkk/zigbee-herdsman-converters#1219]
Please add the new light Zemismart Model: LXT56-LS27LX1.6.
link: https://www.aliexpress.com/item/4000012905509.html?spm=a2g0s.9042311.0.0.72dd4c4d2RUthw
I try myself but I cant add ssh access because dont have "import from USB" option event if advance mode is enabled.

**Comment by lukyjay** [comment]
Hi @krasevych you haven't provided any information other than a link to buy the product. It's impossible for anyone to assist you without owning the product.

I would recommend following the hass.io guide assuming that is where you installation sits: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html#hassio-addon

If enabling SSH causes issues with the way you use hass.io, you can enable it temporarily to access and edit the required files, then disable it after. Ongoing SSH access is not required.

Alternatively you can access the shell interface on your hass.io installation if you have direct console access. If you're running in a VM (e.g. Proxmox) this is easy to do, or if running headless you may need to connect via IPMI or use a monitor + keyboard and mouse temporarily.
