### ISSUE TITLE
Ikea On/Off Switch E1766 Hold click

### ISSUE THREAD

**Issue by comdata** [Koenkk/zigbee-herdsman-converters#1239]
Hello,

I want to figure out if a button is being hold on the Ikea E1766.

Unfortunately I get the following in the log:

Single short click:
zigbee2mqtt:info  2020-05-16 20:09:27: MQTT publish: topic 'zigbee2mqtt/Dimmer Treppenhaus', payload '{"update_available":false,"linkquality":97,"click":"open"}'
zigbee2mqtt:info  2020-05-16 20:09:27: MQTT publish: topic 'zigbee2mqtt/Dimmer Treppenhaus', payload '{"update_available":false,"linkquality":97,"click":""}'
zigbee2mqtt:info  2020-05-16 20:09:27: MQTT publish: topic 'zigbee2mqtt/Dimmer Treppenhaus/click', payload 'open'

Hold:

zigbee2mqtt:info  2020-05-16 20:09:55: MQTT publish: topic 'zigbee2mqtt/Dimmer Treppenhaus', payload '{"update_available":false,"linkquality":97,"click":"open"}'
zigbee2mqtt:info  2020-05-16 20:09:55: MQTT publish: topic 'zigbee2mqtt/Dimmer Treppenhaus', payload '{"update_available":false,"linkquality":97,"click":""}'
zigbee2mqtt:info  2020-05-16 20:09:55: MQTT publish: topic 'zigbee2mqtt/Dimmer Treppenhaus/click', payload 'open'
zigbee2mqtt:info  2020-05-16 20:09:57: MQTT publish: topic 'zigbee2mqtt/Dimmer Treppenhaus', payload '{"update_available":false,"linkquality":97,"click":"release"}'
zigbee2mqtt:info  2020-05-16 20:09:57: MQTT publish: topic 'zigbee2mqtt/Dimmer Treppenhaus', payload '{"update_available":false,"linkquality":97,"click":""}'
zigbee2mqtt:info  2020-05-16 20:09:57: MQTT publish: topic 'zigbee2mqtt/Dimmer Treppenhaus/click', payload 'release'

So for some reason the second link with the click is empty ("").

For IKEA E1743 I get a hold event instead of a click.

How can this be fixed?

Are they any other logs required?

**Comment by Koenkk** [comment]
With the commands that this button sends, we cannot detect that the button is being hold. 

Btw are you sure the E1743 provides a `hold`? (I cannot find it in the code)

**Comment by comdata** [comment]
Ok, I checked it is not a hold but a brightness_<up>/<down> for a hold scenario:

zigbee2mqtt:info  2020-05-18 11:10:40: MQTT publish: topic 'zigbee2mqtt/FB Arbeitszimmer', payload '{"linkquality":99,"update_available":false,"battery":16,"click":"brightness_down"}'
zigbee2mqtt:info  2020-05-18 11:10:40: MQTT publish: topic 'zigbee2mqtt/FB Arbeitszimmer', payload '{"linkquality":99,"update_available":false,"battery":16,"click":""}'
zigbee2mqtt:info  2020-05-18 11:10:40: MQTT publish: topic 'zigbee2mqtt/FB Arbeitszimmer/click', payload 'brightness_down'

zigbee2mqtt:info  2020-05-18 11:10:41: MQTT publish: topic 'zigbee2mqtt/FB Arbeitszimmer', payload '{"linkquality":63,"update_available":false,"battery":16,"click":"brightness_stop"}'
zigbee2mqtt:info  2020-05-18 11:10:41: MQTT publish: topic 'zigbee2mqtt/FB Arbeitszimmer', payload '{"linkquality":63,"update_available":false,"battery":16,"click":""}'

And an off for a single click:

zigbee2mqtt:info  2020-05-18 11:12:42: MQTT publish: topic 'zigbee2mqtt/FB Arbeitszimmer', payload '{"linkquality":23,"update_available":false,"battery":16,"click":"off"}'
zigbee2mqtt:info  2020-05-18 11:12:42: MQTT publish: topic 'zigbee2mqtt/FB Arbeitszimmer', payload '{"linkquality":23,"update_available":false,"battery":16,"click":""}'
zigbee2mqtt:info  2020-05-18 11:12:42: MQTT publish: topic 'zigbee2mqtt/FB Arbeitszimmer/click', payload 'off'

**Comment by MattWestb** [comment]
E1743  its a command dimmer swish (old LL) so its sending command for lights like On/Off dimm up/dow.
If you like using it for clicking things you must triggering this command sended from the device and translate them to clicks commands in your ha system.
If you using one HA switch (old HA or Z30) you getting clicks but its cant steering lights direct and must going thru your HA system for translating the clicks to command and its not working if the HA system its not online (corrupted sd card, software update, wifi down and so on) and the command (LL) its working autonomous with or without your HA system (as long the devices have power).
For simple HA you can use all switches but the click one its easier 2 use and for lights the HA (click ones) its more or less not useful (all Xiaomi not zigbee certified switches = 90%) then one light dont understand "right double click"and need a real zigbee command like "Dimm down" in the zigbee standard (old LL or new Z30, the Ikea switches is Z30 if updated or LL with old FW).
