### ISSUE TITLE
No converter available for 'HS2WD-E' with cluster 'genBasic' and type 'readResponse' and data '{"zclVersion":1}'

### ISSUE THREAD

**Issue by wojciechczyz** [Koenkk/zigbee-herdsman-converters#1243]
Heiman Siren seems to be working good, yet is reporting this problem from time to time. 
Is something missing in the converter?

zigbee2mqtt:debug 2020-05-18 15:15:02: Received Zigbee message from '0x000d6f00143c0899', type 'readResponse', cluster 'genBasic', data '{"zclVersion":1}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-05-18 15:15:02: No converter available for 'HS2WD-E' with cluster 'genBasic' and type 'readResponse' and data '{"zclVersion":1}'
zigbee2mqtt:debug 2020-05-18 15:15:02: Successfully pinged '0x000d6f00143c0899'

zigbee2mqtt
Current version: 1.13.0 
Home Assistant 0.109.6

**Comment by Koenkk** [comment]
There is indeed no converter specified for this message as it makes no sense to convert it to MQTT. Can be ignored.
