### ISSUE TITLE
Can I add this?

### ISSUE THREAD

**Issue by qjiang888** [Koenkk/zigbee-herdsman-converters#1245]
zigbee2mqtt:info  2020-05-18 14:25:53: Successfully interviewed '0x00124b0015fc99b5', device has successfully been paired
zigbee2mqtt:warn  2020-05-18 14:25:53: Device '0x00124b0015fc99b5' with Zigbee model 'HORN-PIR--A3.9-E' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
zigbee2mqtt:info  2020-05-18 14:25:53: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0x00124b0015fc99b5","supported":false}}'
zigbee2mqtt:debug 2020-05-18 14:25:58: Received Zigbee message from '0x00124b0015fc99b5', type 'raw', cluster '65024', data '{"type":"Buffer","data":[28,3,18,0,10,0,0,35,72,9,26,0,3,0,33,250,0]}' from endpoint 1 with groupID 0
zigbee2mqtt:warn  2020-05-18 14:25:58: Received message from unsupported device with Zigbee model 'HORN-PIR--A3.9-E
![QQ截图20200518225748](https://user-images.githubusercontent.com/39437973/82227931-05680c00-995b-11ea-922f-249dee0aba8d.png)
'
zigbee2mqtt:warn  2020-05-18 14:25:58: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.

**Comment by qjiang888** [comment]
//这段是人体的
    {
        zigbeeModel: ['TI0001          '],
        model: 'LH-990ZB',
        vendor: 'iHORN',
        description: 'PIR motion sensor',
        supports: 'occupancy',
        fromZigbee: [fz.iaszone_occupancy_1],
        toZigbee: [],
    },

//这段是门磁的
    {
        zigbeeModel: ['HORN-MECI-A3.9-E'],
        model: 'HO-09ZB',
        vendor: 'iHORN',
        description: 'Door or window contact switch',
        supports: 'contact',
        fromZigbee: [fz.ias_contact_alarm_1, fz.battery],
        toZigbee: [],
    },

**Comment by Koenkk** [comment]
Added both, thanks!

**Comment by qjiang888** [comment]
I still can't parse it. Do you want to modify fromzigbee.js?

![QQ图片20200519003523](https://user-images.githubusercontent.com/39437973/82237958-11f36100-9969-11ea-85a3-c48d36f04c7e.png)
![QQ截图20200519003903](https://user-images.githubusercontent.com/39437973/82237998-28012180-9969-11ea-8e19-075a3560e973.png)
Thank you very much.

**Comment by Koenkk** [comment]
Its available in the latest dev branch now: https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html
