### ISSUE TITLE
I have modified this one and it can be used

### ISSUE THREAD

**Issue by qjiang888** [Koenkk/zigbee-herdsman-converters#1248]
{
        zigbeeModel: ['HORN-PIR--A3.9-E'],
        model: 'LH-990F',
        vendor: 'iHORN',
        description: 'PIR motion sensor',
        supports: 'occupancy',
        fromZigbee: [fz.ias_occupancy_alarm_1],
        toZigbee: [],
    },

#1024 
I have modified this one and it can be used

**Comment by qjiang888** [comment]
#1245

**Comment by Koenkk** [comment]
added, thanks!
