### ISSUE TITLE
help

### ISSUE THREAD

**Issue by unpack8866** [Koenkk/zigbee-herdsman-converters#1261]
I want to add a human body movement sensor. How to modify it fromzigbee.js file？

{"ieeeAddr":"0x00124b000959e9db","type":"EndDevice","networkAddress":16043,"model":"AD-IR602-HB","vendor":"ADDYMAN","description":"PIR motion sensor","friendly_name":"0x00124b000959e9db","manufacturerID":0,"manufacturerName":"链融","powerSource":"Battery","modelID":"131c854783bc45c9b2ac58088d09571c","hardwareVersion":1,"dateCode":"20151128        ","lastSeen":1590342311241}]}'

zigbee2mqtt:debug 2020-05-25 09:29:17: Received Zigbee message from '0x00124b000959e9db', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"zonestatus":257,"extendedstatus":0}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-05-25 09:29:17: No converter available for 'AD-IR602-HB' with cluster 'ssIasZone' and type 'commandStatusChangeNotification' and data '{"zonestatus":257,"extendedstatus":0}'

zigbee2mqtt:debug 2020-05-25 09:24:01: Received Zigbee message from '0x00124b000959e9db', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":200}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-05-25 09:24:01: No converter available for 'AD-IR602-HB' with cluster 'genPowerCfg' and type 'attributeReport' and data '{"batteryPercentageRemaining":200}'

**Comment by Koenkk** [comment]
Please try with below in `devices.js` (https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html)

```js
{
    zigbeeModel: ['131c854783bc45c9b2ac58088d09571c'],
    model: 'TODO',
    vendor: 'ADDYMAN',
    description: 'Smart motion sensor',
    supports: 'occupancy',
    fromZigbee: [fz.ias_occupancy_alarm_1, fz.battery],
    toZigbee: [],
},
```

If that works, please share an URL (link) to the device.

**Comment by unpack8866** [comment]
> Please try with below in `devices.js` (https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html)
> 
> ```js
> {
>     zigbeeModel: ['131c854783bc45c9b2ac58088d09571c'],
>     model: 'TODO',
>     vendor: 'ADDYMAN',
>     description: 'Smart motion sensor',
>     supports: 'occupancy',
>     fromZigbee: [fz.ias_occupancy_alarm_1, fz.battery],
>     toZigbee: [],
> },
> ```
> 
> If that works, please share an URL (link) to the device.


Thank you, this setting is feasible!
https://www.orvibo.com/cn/product/bodysensor.html

     // ADDYMAN
    {
        zigbeeModel: ['131c854783bc45c9b2ac58088d09571c'],
        model: 'AD-IR602-HB',
        vendor: 'ADDYMAN',
        description: 'Occupancy sensor',
        supports: 'occupancy',
        fromZigbee: [fz.ias_occupancy_alarm_1_with_timeout, fz.battery],
        toZigbee: [],
    },

**Comment by unpack8866** [comment]
There's another message，What should I do？

zigbee2mqtt:debug 2020-05-27 21:50:47: Received Zigbee message from '0x00124b000959e9db', type 'attributeReport', cluster 'genIdentify', data '{"1989":"0x00124b000959e9db"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-05-27 21:50:47: No converter available for 'AD-IR602-HB' with cluster 'genIdentify' and type 'attributeReport' and data '{"1989":"0x00124b000959e9db"}'

**Comment by Koenkk** [comment]
That message can be ignored (not interesting to convert to MQTT).

I've added support for this device, will be supported in zigbee2mqtt tomorrow
