### ISSUE TITLE
Request to add device！

### ISSUE THREAD

**Issue by unpack8866** [Koenkk/zigbee-herdsman-converters#1274]
Request to add device！

[link：](https://www.xiaomiyoupin.com/detail?gid=118897&spmref=YouPinPC.$SearchFilter$1.search_list.3.99223308)

Model ：QBKG24LM
Vendor： Xiaomi
Description：Aqara double key wired wall switch D1
Supports：on/off, power measurement, temperature

    {
        zigbeeModel: ['lumi.switch.b2nacn02'],
        model: 'QBKG24LM',
        vendor: 'Xiaomi',
        description: 'Aqara double key wired wall switch D1',
        supports: 'on/off, power measurement, temperature',
        fromZigbee: [
            fz.QBKG03LM_QBKG12LM_LLKZMK11LM_state, fz.QBKG12LM_LLKZMK11LM_power, fz.QBKG03LM_QBKG12LM_operation_mode,
            fz.QBKG12LM_click, fz.ignore_multistate_report, fz.xiaomi_power,
        ],
        toZigbee: [tz.on_off, tz.xiaomi_switch_operation_mode],
        endpoint: (device) => {
            return {'left': 1, 'right': 2, 'system': 1};
        },
        onEvent: xiaomi.prevent_reset,
    },

**Comment by Koenkk** [comment]
- Does changing the operation mode work? (https://www.zigbee2mqtt.io/devices/QBKG03LM.html#decoupled-mode)
- Does it also work ok with the config below? :

```js
{
    zigbeeModel: ['lumi.switch.b2nacn02'],
    model: 'QBKG24LM',
    vendor: 'Xiaomi',
    description: 'Aqara double key wired wall switch D1',
    supports: 'on/off, power measurement, temperature',
    fromZigbee: [fz.on_off, fz.xiaomi_power, fz.QBKG03LM_QBKG12LM_operation_mode],
    toZigbee: [tz.on_off, tz.xiaomi_switch_operation_mode],
    meta: {multiEndpoint: true},
    endpoint: (device) => {
        return {'left': 1, 'right': 2, 'system': 1};
    },
    onEvent: xiaomi.prevent_reset,
},
```

**Comment by unpack8866** [comment]
I try to add three key switch D1;

How to modify device.js

**Comment by Koenkk** [comment]
Is this the QBKG25LM? Should already be supported: https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L730

**Comment by unpack8866** [comment]
> Is this the QBKG25LM? Should already be supported: https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L730

This is QBKG26LM,With L&N line。
QBKG25LM only has L line。

zigbeeModel: ['lumi.switch.n3acn3'],
model: 'QBKG26LM',
vendor: 'Xiaomi',

**Comment by unpack8866** [comment]
> 这是QBKG25LM吗？应该已经受到支持：[https](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L730) : [//github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L730](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L730)

D1 wall switch:

1) L line only：
    QBKG21LM     single key
    QBKG22LM     double key
    QBKG25LM     three key

2) L&N line：
    QBKG23LM     single key
    QBKG24LM     double key
    QBKG26LM     three key

**Comment by Koenkk** [comment]
For the QBKG26LM try with:

```js
{
    zigbeeModel: ['lumi.switch.n3acn3'],
    model: 'QBKG26LM',
    vendor: 'Xiaomi',
    description: 'Aqara D1 3 gang smart wall switch (with neutral wire)',
    supports: 'on/off, power measurement',
    fromZigbee: [fz.on_off, fz.xiaomi_power],
    toZigbee: [tz.on_off],
    meta: {multiEndpoint: true},
    endpoint: (device) => {
        return {'left': 1, 'center': 2, 'right': 3, 'system': 1};
    },
    onEvent: xiaomi.prevent_reset,
},
```

See https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html on how to add to `devices.js`

**Comment by unpack8866** [comment]
> * Does changing the operation mode work? (https://www.zigbee2mqtt.io/devices/QBKG03LM.html#decoupled-mode)
> * Does it also work ok with the config below? :
> 
> ```js
> {
>     zigbeeModel: ['lumi.switch.b2nacn02'],
>     model: 'QBKG24LM',
>     vendor: 'Xiaomi',
>     description: 'Aqara double key wired wall switch D1',
>     supports: 'on/off, power measurement, temperature',
>     fromZigbee: [fz.on_off, fz.xiaomi_power, fz.QBKG03LM_QBKG12LM_operation_mode],
>     toZigbee: [tz.on_off, tz.xiaomi_switch_operation_mode],
>     meta: {multiEndpoint: true},
>     endpoint: (device) => {
>         return {'left': 1, 'right': 2, 'system': 1};
>     },
>     onEvent: xiaomi.prevent_reset,
> },
> ```

It's working now！

    {
        zigbeeModel: ['lumi.switch.b2nacn02'],
        model: 'QBKG24LM',
        vendor: 'Xiaomi',
        description: 'Aqara D1 1 gang smart wall switch (with neutral wire)',
        supports: 'on/off, power measurement, temperature',
        fromZigbee: [
            fz.on_off_xiaomi_ignore_endpoint_4_5_6, fz.QBKG03LM_QBKG12LM_click, fz.xiaomi_power,
            fz.QBKG03LM_QBKG12LM_operation_mode, fz.generic_device_temperature, fz.xiaomi_power_from_basic,
        ],
        toZigbee: [tz.on_off, tz.xiaomi_switch_operation_mode],
        meta: {multiEndpoint: true},
        endpoint: (device) => {
            return {'left': 1, 'right': 2, 'system': 1};
        },
        onEvent: xiaomi.prevent_reset,
    },

**Comment by unpack8866** [comment]
> * Does changing the operation mode work? (https://www.zigbee2mqtt.io/devices/QBKG03LM.html#decoupled-mode)
> * Does it also work ok with the config below? :
> 
> ```js
> {
>     zigbeeModel: ['lumi.switch.b2nacn02'],
>     model: 'QBKG24LM',
>     vendor: 'Xiaomi',
>     description: 'Aqara double key wired wall switch D1',
>     supports: 'on/off, power measurement, temperature',
>     fromZigbee: [fz.on_off, fz.xiaomi_power, fz.QBKG03LM_QBKG12LM_operation_mode],
>     toZigbee: [tz.on_off, tz.xiaomi_switch_operation_mode],
>     meta: {multiEndpoint: true},
>     endpoint: (device) => {
>         return {'left': 1, 'right': 2, 'system': 1};
>     },
>     onEvent: xiaomi.prevent_reset,
> },
> ```

It's working now！

    {
        zigbeeModel: ['lumi.switch.b2nacn02'],
        model: 'QBKG24LM',
        vendor: 'Xiaomi',
        description: 'Aqara D1 1 gang smart wall switch (with neutral wire)',
        supports: 'on/off, power measurement, temperature',
        fromZigbee: [
            fz.on_off_xiaomi_ignore_endpoint_4_5_6, fz.QBKG03LM_QBKG12LM_click, fz.xiaomi_power,
            fz.QBKG03LM_QBKG12LM_operation_mode, fz.generic_device_temperature, fz.xiaomi_power_from_basic,
        ],
        toZigbee: [tz.on_off, tz.xiaomi_switch_operation_mode],
        meta: {multiEndpoint: true},
        endpoint: (device) => {
            return {'left': 1, 'right': 2, 'system': 1};
        },
        onEvent: xiaomi.prevent_reset,
    },

**Comment by unpack8866** [comment]
> For the QBKG26LM try with:
> 
> ```js
> {
>     zigbeeModel: ['lumi.switch.n3acn3'],
>     model: 'QBKG26LM',
>     vendor: 'Xiaomi',
>     description: 'Aqara D1 3 gang smart wall switch (with neutral wire)',
>     supports: 'on/off, power measurement',
>     fromZigbee: [fz.on_off, fz.xiaomi_power],
>     toZigbee: [tz.on_off],
>     meta: {multiEndpoint: true},
>     endpoint: (device) => {
>         return {'left': 1, 'center': 2, 'right': 3, 'system': 1};
>     },
>     onEvent: xiaomi.prevent_reset,
> },
> ```
> 
> See https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html on how to add to `devices.js`

It's working now！But there is no temperature, signal, status, power

**Comment by Koenkk** [comment]
Can you try adding `fz.generic_device_temperature` and `fz.QBKG12LM_LLKZMK11LM_power` to `formZigbee?

**Comment by unpack8866** [comment]
> Can you try adding `fz.generic_device_temperature` and `fz.QBKG12LM_LLKZMK11LM_power` to `formZigbee?

I modified the following. But there is no temperature, signal, status, power。
And I was formZigbee Not found in` fz.QBKG12LM_ LLKZMK11LM_ power`

        zigbeeModel: ['lumi.switch.n3acn3'],
        model: 'QBKG26LM',
        vendor: 'Xiaomi',
        description: 'Aqara D1 3 gang smart wall switch (with neutral wire)',
        supports: 'on/off, power measurement, temperature',
        fromZigbee: [
            fz.on_off_xiaomi_ignore_endpoint_4_5_6, fz.QBKG25LM_click, fz.xiaomi_power,
            fz.generic_device_temperature, fz.xiaomi_power_from_basic,
        ],
        toZigbee: [tz.on_off, tz.xiaomi_switch_operation_mode],
        meta: {multiEndpoint: true},
        endpoint: (device) => {
            return {'left': 1, 'center': 2, 'right': 3, 'system': 1};
        },
        onEvent: xiaomi.prevent_reset,
    },

**Comment by Koenkk** [comment]
Does the above config work?

**Comment by unpack8866** [comment]
> Does the above config work?

Switch active；Temperature, power, signal and state feedback are not available

**Comment by dongvanthinh** [comment]
the same issue

**Comment by espkami** [comment]
the same issue nosignal how can i fix it

**Comment by espkami** [comment]
i think the problem is fromzigbee.js file . 
why is it write this
                const mapping = {41: 'left', 42: 'center', 43: 'right'};
                const times = {1: 'single', 2: 'double', 3: 'triple', 0: 'hold', 255: 'release'};
                const button = mapping[msg.endpoint.ID];
is the mapping right in QBKG26LM

**Comment by zhongfu** [comment]
> * Does changing the operation mode work? (https://www.zigbee2mqtt.io/devices/QBKG03LM.html#decoupled-mode)

I just got a QBKG22LM (2-gang no-neutral), and can confirm that decoupled mode works great.

Doesn't seem to be working with my QBKG25LM (3-gang no-neutral) though -- is there anything I can do to help figure this out? I tried copying the config over from that of the QBKG22LM, but unsurprisingly it didn't work.

**Comment by zhongfu** [comment]
I've also had a look at the Aqara app, and unfortunately it seems that there's no support (at least in their app) for click-and-hold detection. Perhaps that's why the 3-gang switches can be re-paired despite being connected to a coordinator, while the 1- and 2-gang switches can't be.

**Comment by korikutkin** [comment]
Good day! Are there working settings for the QBKG26LM?

**Comment by zhongfu** [comment]
@korikutkin You can try out the [`qbkg26lm` branch of my repo](https://github.com/zhongfu/zigbee-herdsman-converters/tree/qbkg26lm) (just clone it and replace the `node_modules/zigbee-herdsman-converters` folder in your zigbee2mqtt folder), but it'll be missing power measurements (and temperature, if it reports that too). You should be able to enable `power_outage_memory`, `do_not_disturb`, and also set the `operation_mode`, although the interface for the latter will be slightly different from the older Aqara switches.

You could also enable debug logging and see if it reports power measurements -- if it does, you should be able to see the raw messages in the logs, I think. With that, it might be possible to add support for power measurements (and so on) for the QBKG26LM

**Comment by korikutkin** [comment]
> You could also enable debug logging and see if it reports power measurements -- if it does, you should be able to see the raw messages in the logs, I think. With that, it might be possible to add support for power measurements (and so on) for the QBKG26LM

Thank you, I will check soon and will answer you.

**Comment by voky45** [comment]
I have the same problem for theQBKG26LM, how are the test results?

**Comment by desmondgohsw-private** [comment]
> @korikutkin You can try out the [`qbkg26lm` branch of my repo](https://github.com/zhongfu/zigbee-herdsman-converters/tree/qbkg26lm) -- just clone it and replace the `node_modules/zigbee-herdsman-converters` folder in your zigbee2mqtt folder -- but it'll be missing power and temperature measurements. You should then be able to enable `power_outage_memory`, `do_not_disturb`, and also set the `operation_mode`, although the interface for the latter will be slightly different from the older Aqara switches.
> 
> You could also enable debug logging and see if it reports power measurements -- if it does, you should be able to see the raw messages in the logs, I think. With that, it might be possible to add support for power measurements (and so on) for the QBKG26LM

Can these be included to the official release to get the basic switch operations supported?

**Comment by korikutkin** [comment]
The device is detected, but no control occurs...

**Comment by zhongfu** [comment]
@korikutkin Sorry, my bad... I made a branch, but it seems like I forgot to actually push the relevant commit. Could you try again?

**Comment by korikutkin** [comment]
https://github.com/zhongfu/zigbee-herdsman-converters/blob/qbkg26lm/converters/fromZigbee.js
Why is there no description for QBKG26M in the file, similar to QBKG25LM_click?

**Comment by zhongfu** [comment]
https://github.com/zhongfu/zigbee-herdsman-converters/blob/qbkg26lm/devices.js#L687

**Comment by lovelylain** [comment]
> @korikutkin You can try out the [`qbkg26lm` branch of my repo](https://github.com/zhongfu/zigbee-herdsman-converters/tree/qbkg26lm) -- just clone it and replace the `node_modules/zigbee-herdsman-converters` folder in your zigbee2mqtt folder -- but it'll be missing power and temperature measurements. You should then be able to enable `power_outage_memory`, `do_not_disturb`, and also set the `operation_mode`, although the interface for the latter will be slightly different from the older Aqara switches.
> 
> You could also enable debug logging and see if it reports power measurements -- if it does, you should be able to see the raw messages in the logs, I think. With that, it might be possible to add support for power measurements (and so on) for the QBKG26LM

尝试了，除了tz.on_off可以控制开关通断外，没收到任何反馈。
```
zigbee2mqtt:info  2020-08-09 16:39:26: Device '0xXXXXXXXXXXXXXXXX' joined
zigbee2mqtt:info  2020-08-09 16:39:26: Starting interview of '0xXXXXXXXXXXXXXXXX'
zigbee2mqtt:info  2020-08-09 16:39:26: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":{"friendly_name":"0xXXXXXXXXXXXXXXXX"}}'
zigbee2mqtt:info  2020-08-09 16:39:26: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"0xXXXXXXXXXXXXXXXX"}}'
zigbee2mqtt:debug 2020-08-09 16:39:26: Device '0xXXXXXXXXXXXXXXXX' announced itself
zigbee2mqtt:info  2020-08-09 16:39:26: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_announced","message":"announce","meta":{"friendly_name":"0xXXXXXXXXXXXXXXXX"}}'
zigbee2mqtt:debug 2020-08-09 16:39:27: Received Zigbee message from '0xXXXXXXXXXXXXXXXX', type 'readResponse', cluster 'genBasic', data '{"modelId":"lumi.switch.n3acn3"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-08-09 16:39:27: Received Zigbee message from '0xXXXXXXXXXXXXXXXX', type 'readResponse', cluster 'genBasic', data '{"manufacturerName":"LUMI"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-08-09 16:39:27: Received Zigbee message from '0xXXXXXXXXXXXXXXXX', type 'readResponse', cluster 'genBasic', data '{"powerSource":1}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-08-09 16:39:27: Received Zigbee message from '0xXXXXXXXXXXXXXXXX', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-08-09 16:39:27: Received Zigbee message from '0xXXXXXXXXXXXXXXXX', type 'readResponse', cluster 'genBasic', data '{"appVersion":31}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-08-09 16:39:27: Received Zigbee message from '0xXXXXXXXXXXXXXXXX', type 'readResponse', cluster 'genBasic', data '{"stackVersion":2}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-08-09 16:39:27: Received Zigbee message from '0xXXXXXXXXXXXXXXXX', type 'readResponse', cluster 'genBasic', data '{"hwVersion":1}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-08-09 16:39:27: Received Zigbee message from '0xXXXXXXXXXXXXXXXX', type 'readResponse', cluster 'genBasic', data '{"dateCode":"02-24-2020"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-08-09 16:39:27: Received Zigbee message from '0xXXXXXXXXXXXXXXXX', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-08-09 16:39:27: Received Zigbee message from '0xXXXXXXXXXXXXXXXX', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 2 with groupID 0
zigbee2mqtt:debug 2020-08-09 16:39:28: Received Zigbee message from '0xXXXXXXXXXXXXXXXX', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 3 with groupID 0
zigbee2mqtt:info  2020-08-09 16:39:28: Successfully interviewed '0xXXXXXXXXXXXXXXXX', device has successfully been paired
zigbee2mqtt:info  2020-08-09 16:39:28: Device '0xXXXXXXXXXXXXXXXX' is supported, identified as: Xiaomi Aqara D1 3 gang smart wall switch (with neutral wire) (QBKG26LM)
zigbee2mqtt:info  2020-08-09 16:39:28: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0xXXXXXXXXXXXXXXXX","model":"QBKG26LM","vendor":"Xiaomi","description":"Aqara D1 3 gang smart wall switch (with neutral wire)","supported":true}}'
zigbee2mqtt:debug 2020-08-09 16:39:38: Received Zigbee message from '0xXXXXXXXXXXXXXXXX', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"manufacturerCode":4447,"imageType":1164,"fileVersion":31}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-08-09 16:41:23: Received MQTT message on 'zigbee2mqtt/0xXXXXXXXXXXXXXXXX/right/set' with data 'ON'
zigbee2mqtt:debug 2020-08-09 16:41:23: Publishing 'set' 'state' to '0xXXXXXXXXXXXXXXXX'
zigbee2mqtt:info  2020-08-09 16:41:23: MQTT publish: topic 'zigbee2mqtt/0xXXXXXXXXXXXXXXXX', payload '{"state_center":"OFF","state_right":"ON","state_left":"OFF"}'
zigbee2mqtt:debug 2020-08-09 16:41:27: Received MQTT message on 'zigbee2mqtt/0xXXXXXXXXXXXXXXXX/right/set' with data 'OFF'
zigbee2mqtt:debug 2020-08-09 16:41:27: Publishing 'set' 'state' to '0xXXXXXXXXXXXXXXXX'
zigbee2mqtt:info  2020-08-09 16:41:27: MQTT publish: topic 'zigbee2mqtt/0xXXXXXXXXXXXXXXXX', payload '{"state_center":"OFF","state_right":"OFF","state_left":"OFF"}'
```
这是重新配对到开关一次的相关log，只收到配对时的设备信息和一条genOta信息。

BTW, does QBKG24LM (D1 2 gang wall switch with neutral wire) support operation_mode? I have three QBKG24LM switches only use one gang, I want change the other to a wireless switch.

**Comment by zhongfu** [comment]
> 尝试了，除了tz.on_off可以控制开关通断外，没收到任何反馈。  
>\<snip\>
> 这是重新配对到开关一次的相关log，只收到配对时的设备信息和一条genOta信息。  

If you don't see any other messages from the switch even after an extended period of time (or change in power consumption, maybe?) then it could be that you have to poll it for measurements or maybe enable power consumption reports. If that's the case, then we'd need to [sniff the communications between it and an Aqara/Xiaomi hub](https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html) to figure it out

> BTW, does QBKG24LM (D1 2 gang wall switch with neutral wire) support operation_mode? I have three QBKG24LM switches only use one gang, I want change the other to a wireless switch.

I have no reason to believe that it wouldn't -- as far as I can tell, the D1 1- and 2-gang switches are functionally identical to the previous-gen switches. I've updated the qbkg26lm branch on my repo with the necessary changes, so perhaps you could test it out as well

**Comment by lovelylain** [comment]
@zhongfu thanks, I have only one z2m gateway, no offical, so I cannot sniff. My house is being decorated, I can only get there on weekends, I will test it next weekend.

**Comment by korikutkin** [comment]
> @korikutkin You can try out the [`qbkg26lm` branch of my repo](https://github.com/zhongfu/zigbee-herdsman-converters/tree/qbkg26lm) -- just clone it and replace the `node_modules/zigbee-herdsman-converters` folder in your zigbee2mqtt folder -- but it'll be missing power and temperature measurements. You should then be able to enable `power_outage_memory`, `do_not_disturb`, and also set the `operation_mode`, although the interface for the latter will be slightly different from the older Aqara switches.
> 
> You could also enable debug logging and see if it reports power measurements -- if it does, you should be able to see the raw messages in the logs, I think. With that, it might be possible to add support for power measurements (and so on) for the QBKG26LM

Very strange, after cloning the repository in the files toZigbee.js and devices.js the file browser does not find the name "QBKG26" and therefore the device does not work ... What should I do?

**Comment by zhongfu** [comment]
@korikutkin try `git checkout qbkg26lm`

**Comment by korikutkin** [comment]
> @korikutkin try `git checkout qbkg26lm`

I just copied the ZIP file and replaced the files. The device was identified as QBKG26ЛМ. But there was no control. After I selected SELECTVENDOR: Xiaomi and SELECTTYPE: QBKG03LM, two keys became controlled, but the third was not controlled. In general, it seems to me that the settings are working, only you need to add the device to the Koenkk directory. Thank!

**Comment by lovelylain** [comment]
@korikutkin Do you receive zigbee message from your QBKG26LM switch?
Set the Zigbee2mqtt log_level to debug and then view Zigbee2mqtt's log. You can visit https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html for how to config the log_level.

**Comment by lovelylain** [comment]
@zhongfu 我把QBKG24LM完全当做QBKG12LM尝试了，确实基本一样，温度等参数都能获取了，转换无线开关似乎也有反应，你知道这个功能具体该怎么用吗？https://www.zigbee2mqtt.io/devices/QBKG12LM.html#decoupled-mode 我参考这里发送了decoupled，但是开关并没有像米家APP里提示的那样变为常通。

**Comment by desmondgohsw-private** [comment]
> > 尝试了，除了tz.on_off可以控制开关通断外，没收到任何反馈。
> > <snip>
> > 这是重新配对到开关一次的相关log，只收到配对时的设备信息和一条genOta信息。
> 
> If you don't see any other messages from the switch even after an extended period of time (or change in power consumption, maybe?) then it could be that you have to poll it for measurements or maybe enable power consumption reports. If that's the case, then we'd need to [sniff the communications between it and an Aqara/Xiaomi hub](https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html) to figure it out
> 
> > BTW, does QBKG24LM (D1 2 gang wall switch with neutral wire) support operation_mode? I have three QBKG24LM switches only use one gang, I want change the other to a wireless switch.
> 
> I have no reason to believe that it wouldn't -- as far as I can tell, the D1 1- and 2-gang switches are functionally identical to the previous-gen switches. I've updated the qbkg26lm branch on my repo with the necessary changes, so perhaps you could test it out as well

Tried your repo, and I'm still not seeing the metrics. While in the debug log, nothing seems to show up for QBKG26LM. 
One more thing which I've noticed is that if you toggle the physical wall switches, the on/off state doesn't get reflected to the z2m.

**Comment by sshaikh** [comment]
Does this quirk require zstack 3 or is that a nonsensical question? (asking before I flash unnecessarily)

**Comment by lovelylain** [comment]
@sshaikh have you tried flash zstack 3 firmware? If you did, does it solve the feedback problem?

**Comment by sshaikh** [comment]
Unfortunately I can't confirm for sure. Here's my timeline:

0. I was using ha with native zha/ZigBee and z2m cc stick on 1.2, everything working well.
1. New D1 Aqara light switch didn't work.
2. Upgraded to zstack 3. This allowed the D1 to work with zha
3. Switched over to z2m anyway as it was more stable and had more features (like decoupling).

In short, I didn't test the aqara d1 with z2m and zstack 1.2. I think it'll probably work since the config seems to be independent of the firmware running on the cc stick.

**Comment by lovelylain** [comment]
The D1 two-gang version is almost the same as the previous generation, it worked well with zstack 1.2.
But the D1 three-gang version (QBKG26LM) is completely different, it can pair with z2m, and control on/off from z2m, but after pressing the physical button, no zigbee messages is received, so the switch status in z2m will be wrong.
I want to know if flashing zstack 3 will solve the problem.

**Comment by sshaikh** [comment]
That behaviour sounds similar to what I was experiencing with native HA integration before I upgraded, but there was also no quirk being loaded so there was probably multiple problems.

What I can confirm is that it fully works with ZHA and Z2M with ZStack 3.
