### ISSUE TITLE
Default precision wrong in Xiami GZCGQ01LM (and maybe others)

### ISSUE THREAD

**Issue by McGiverGim** [Koenkk/zigbee-herdsman-converters#1275]
I'm not too sure if I don't understand the documentation what precision means in https://www.zigbee2mqtt.io/devices/GZCGQ01LM.html :
> illuminance_lux_precision: Controls the precision of illuminance_lux values, e.g. 0 or 1; default 1. To control the precision based on the illuminance_lux value set it to e.g. {1000: 0, 100: 1}, when illuminance_lux >= 1000 precision will be 0, when illuminance_lux >= 100 precision will be 1.

If I'm not wrong, the default value is to have precision 1, that I assume is to use 1 decimal for the value. If that's true, I'm receiving the lux values with zero decimals. Sample:
```log
zigbee2mqtt:info  2020-06-03 11:35:30: MQTT publish: topic 'zigbee2mqtt/luminosidad_comedor', payload '{"battery":100,"voltage":3200,"linkquality":107,"illuminance":15315,"illuminance_lux":33}'
```

Thanks for the hard work!!

**Comment by Koenkk** [comment]
The `illuminance` value is always provided as a whole number (devices will never report precision). Based on the `illuminance`, the `illuminance_lux` is calculated, for the above example:

![image](https://user-images.githubusercontent.com/2892853/83670618-bfa27900-a5d3-11ea-968e-78827597ee01.png)

The `illuminance_lux` value is `33.00165058040711` in your case, rounded `33.0`, as Javascript does not preserve `0` decimals the value published to MQTT is `33`.

**Comment by McGiverGim** [comment]
Maybe my sample was not good enough... This happens to me with ALL the values. Maybe internally the illuminance only uses values that correspond with entire lux? Some more samples:
```txt
'zigbee2mqtt/luminosidad_comedor', payload '{"battery":100,"voltage":3200,"linkquality":94,"illuminance":15564,"illuminance_lux":35}'
info  2020-06-03 16:28:58: MQTT publish: topic 'zigbee2mqtt/luminosidad_comedor', payload '{"battery":100,"voltage":3200,"linkquality":94,"illuminance":15441,"illuminance_lux":34}'
info  2020-06-03 16:29:22: MQTT publish: topic 'zigbee2mqtt/luminosidad_comedor', payload '{"battery":100,"voltage":3200,"linkquality":99,"illuminance":15315,"illuminance_lux":33}'
info  2020-06-03 16:29:27: MQTT publish: topic 'zigbee2mqtt/luminosidad_comedor', payload '{"battery":100,"voltage":3200,"linkquality":97,"illuminance":15441,"illuminance_lux":34}'
info  2020-06-03 16:29:47: MQTT publish: topic 'zigbee2mqtt/luminosidad_comedor', payload '{"battery":100,"voltage":3200,"linkquality":99,"illuminance":14914,"illuminance_lux":30}'
info  2020-06-03 16:29:52: MQTT publish: topic 'zigbee2mqtt/luminosidad_comedor', payload '{"battery":100,"voltage":3200,"linkquality":99,"illuminance":12042,"illuminance_lux":15}'
info  2020-06-03 16:29:57: MQTT publish: topic 'zigbee2mqtt/luminosidad_comedor', payload '{"battery":100,"voltage":3200,"linkquality":99,"illuminance":11462,"illuminance_lux":13}'
```

**Comment by Koenkk** [comment]
Interesting! It indeed seems that the sensor only sends values which correspond to a whole lux

**Comment by McGiverGim** [comment]
Then I think I can close this issue, but maybe is better to remove the precision text from the help page, because it will do nothing :)

**Comment by Koenkk** [comment]
You are right, done. Assuming this can be closed now.
