### ISSUE TITLE
Hive Motion (MOT003) hardware rev 0 does not support illuminance

### ISSUE THREAD

**Issue by sprockers** [Koenkk/zigbee-herdsman-converters#1288]
I was excited to see support for MOT003 being added a few weeks ago, and moved some of my sensors across to zigbee2mqtt straight away, but with mixed results. I ended up with a bunch of entities for each MOT003 sensor in homeassistant as I'd expect, but most had no data and stayed that way.
Occupancy was working fine (which is a good start!), but battery, battery low, illuminance, illuminance_lux and temperature all had no data.

I had a bit of time today so I dug a bit into the code and learned what was going on.

In short, all my MOT003 devices (hardware rev 0) do not support cluster 1024 - illuminance, and this was causing an error when the devices were configured, leaving them mostly unconfigured. 

I manually removed the illuminance from the device config in devices.js in my setup and reconfigured the devices via the zigbee2mqtt-assistant. That has worked - the battery and temperature entities now have data.

What I don't know right now is whether there are multiple hardware revisions of this device, with later revisions supporting illuminance. Maybe @matchett808-gh who put in the original patch to add support can confirm the hardware version of his sensors so we can find a good way forward. Or is it best to simply remove illuminance from this device type as not all hardware versions support it? @Koenkk is there a preferred way to handle this?

Here's a sample of my database.db data for one of the sensors:
`{"id":88,"type":"EndDevice","ieeeAddr":"0x00124b000d7c5264","nwkAddr":10826,"manufId":4153,"manufName":"HiveHome.com","powerSource":"Battery","modelId":"MOT003","epList":[6],"endpoints":{"6":{"profId":260,"epId":6,"devId":1026,"inClusterList":[0,1,3,32,1026,1030,1280],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"hwVersion":0}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b001ca16672","zoneState":0}}},"binds":[]}},"appVersion":5,"stackVersion":38,"hwVersion":0,"dateCode":"20181205","zclVersion":1,"interviewCompleted":false,"meta":{},"lastSeen":1591455599315}`

**Comment by matchett808-gh** [comment]
Hey - can you take a picture of the board above the battery? Will easily rule out if there is a real difference - after adding this I'm still to upgrade (will do so tomorrow and get my sensors in to confirm)

~I don't see anything obvious~

looks like I'm running the same but older firmware at least I assume that's the difference - Hive must've removed lux :(

> "appVersion":4,"stackVersion":38,"hwVersion":0,"dateCode":"20180226","zclVersion":1

I'm not sure if you can update to the latest firmware to confirm (or if there is anything later than yours)? I don't know if it's been added back in later... Also not sure what's best to do - might be best for lux to be removed (it's better for it to work in all cases rather than the % with the right firmware)

**Comment by matchett808-gh** [comment]
yeah - thinking a little further, are you comfortable putting in a PR to remove lux? I'll not be able to get to it until late tomorrow

**Comment by sprockers** [comment]
Hive don't talk much about OTA firmware updates. They definitely do them for some devices - their FAQs talk about firmware updates on their cameras, but I'm not sure if those are even zigbee devices.
Zigbee2mqtt doesn't offer OTA firmware for any hive devices.

What I can say is that until very recently my MOT003s were all connected to my hive hub, so I would expect that if OTA was available via that route they would all be running the latest firmware. In addition they were added over the period of a couple of years, and now they are in zigbee2mqtt I can see they all have the same version info. So again, if OTA is available, they've all been updated to this one version. Either they use OTA and all mine are at the latest version, or they don't use OTA and I've been very lucky to receive 7 sensors over the years all with the same version! 

I'll get a PR raised to remove illuminance.

**Comment by sprockers** [comment]
There we go - PRs to remove the illuminance in the converters and also in the homeassistant integration.

Incidentally, it's interesting that Hive's sensors have a temperature sensor in them. They don't expose this to consumers via their own hub/app, but ultimately as a business they are centred around their central heating and TRV sensors, so I wonder if they quietly collect this data to give them a bigger picture of your house temperature. After all you are encouraged to name your contact/occupancy sensors with the name they are located in...
