### ISSUE TITLE
unreportable attribute for the RS-23ZBS

### ISSUE THREAD

**Issue by estebanz01** [Koenkk/zigbee-herdsman-converters#1312]
Hello again! After pulling dev to the lastest SHA with a green build I'm having this error which I'm not quite sure how to solve it:

```javascript
Jun 13 21:09:53 raspberrypi npm[10066]: zigbee2mqtt:error 2020-06-13 21:09:53: Failed to configure '0x00124b00061c23ce', attempt 2 (Error: ConfigureReporting 0x00124b00061c23ce/1 msRelativeHumidity([{"attribute":"measuredValue","minimumReportInterval":10,"maximumReportInterval":3600,"reportableChange":10}], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Error: Status 'UNREPORTABLE_ATTRIBUTE')
```

According to https://community.smartthings.com/t/help-with-sending-zigbee-configure-reporting-command/4121/11 it seems that my device cannot report al the time the relative humidity measure, which is weird.

Any idea on where should I look to fix this ?

**Comment by estebanz01** [comment]
I removed ` await configureReporting.humidity(endpoint)` from here https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L6387-6391 and it works now. Not sure if that's the correct approach:

**Comment by Koenkk** [comment]
@estebanz01 do you still get humidity reports after removing that?

**Comment by estebanz01** [comment]
@Koenkk yep and it keeps reporting as usual after a bunch of restarts (I was configuring a couple of zigbee devices). Here's what I see in the logs:

```javascript
Jun 14 18:53:08 raspberrypi npm[6727]: zigbee2mqtt:info  2020-06-14 18:53:08: MQTT publish: topic 'zigbee2mqtt/0x00124b00061c23ce', payload '{"temperature":30.1,"linkquality":55,"humidity":48}'
```

and this is what I see on HA:
![Temperature](https://user-images.githubusercontent.com/2417465/84600405-9a690280-ae3e-11ea-8512-93e2a9dbf077.png)
![Relative Humidity](https://user-images.githubusercontent.com/2417465/84600417-aeacff80-ae3e-11ea-8144-c875162f86d8.png)

**Comment by Koenkk** [comment]
Added the fix, thanks!
