### ISSUE TITLE
GLEDOPTO GL-C-007 unsupported although it is

### ISSUE THREAD

**Issue by docbobo** [Koenkk/zigbee-herdsman-converters#1315]
According  to the compatibility list, GLEDOPTO GL-C-007 devices are supported. However, when joining, the following is being logged.

`zigbee2mqtt             | zigbee2mqtt:info  2020-06-15 08:42:05: Device '0x00124b001ada7031' joined
zigbee2mqtt             | zigbee2mqtt:info  2020-06-15 08:42:05: Starting interview of '0x00124b001ada7031'
zigbee2mqtt             | zigbee2mqtt:info  2020-06-15 08:42:05: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":{"friendly_name":"0x00124b001ada7031"}}'
zigbee2mqtt             | zigbee2mqtt:info  2020-06-15 08:42:05: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"0x00124b001ada7031"}}'
zigbee2mqtt             | zigbee2mqtt:debug 2020-06-15 08:42:05: Device '0x00124b001ada7031' announced itself
zigbee2mqtt             | zigbee2mqtt:info  2020-06-15 08:42:05: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_announced","message":"announce","meta":{"friendly_name":"0x00124b001ada7031"}}'
zigbee2mqtt             | zigbee2mqtt:debug 2020-06-15 08:42:05: Device '0x00124b001ada7031' announced itself
zigbee2mqtt             | zigbee2mqtt:info  2020-06-15 08:42:05: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_announced","message":"announce","meta":{"friendly_name":"0x00124b001ada7031"}}'
zigbee2mqtt             | zigbee2mqtt:debug 2020-06-15 08:45:46: Received Zigbee message from '0x00124b001ada7031', type 'readResponse', cluster 'genBasic', data '{"modelId":"GL-C-007"}' from endpoint 12 with groupID 0
zigbee2mqtt             | zigbee2mqtt:debug 2020-06-15 08:45:46: Received Zigbee message from '0x00124b001ada7031', type 'readResponse', cluster 'genBasic', data '{"manufacturerName":"GLEDOPTO"}' from endpoint 12 with groupID 0
zigbee2mqtt             | zigbee2mqtt:debug 2020-06-15 08:45:46: Received Zigbee message from '0x00124b001ada7031', type 'readResponse', cluster 'genBasic', data '{"powerSource":1}' from endpoint 12 with groupID 0
zigbee2mqtt             | zigbee2mqtt:debug 2020-06-15 08:45:46: Received Zigbee message from '0x00124b001ada7031', type 'readResponse', cluster 'genBasic', data '{"zclVersion":1}' from endpoint 12 with groupID 0
zigbee2mqtt             | zigbee2mqtt:debug 2020-06-15 08:45:46: Received Zigbee message from '0x00124b001ada7031', type 'readResponse', cluster 'genBasic', data '{"appVersion":1}' from endpoint 12 with groupID 0
zigbee2mqtt             | zigbee2mqtt:debug 2020-06-15 08:45:47: Received Zigbee message from '0x00124b001ada7031', type 'readResponse', cluster 'genBasic', data '{"stackVersion":2}' from endpoint 12 with groupID 0
zigbee2mqtt             | zigbee2mqtt:debug 2020-06-15 08:45:47: Received Zigbee message from '0x00124b001ada7031', type 'readResponse', cluster 'genBasic', data '{"hwVersion":1}' from endpoint 12 with groupID 0
zigbee2mqtt             | zigbee2mqtt:debug 2020-06-15 08:45:47: Received Zigbee message from '0x00124b001ada7031', type 'readResponse', cluster 'genBasic', data '{"dateCode":"20180920"}' from endpoint 12 with groupID 0
zigbee2mqtt             | zigbee2mqtt:debug 2020-06-15 08:45:47: Received Zigbee message from '0x00124b001ada7031', type 'readResponse', cluster 'genBasic', data '{"swBuildId":"1.0.2"}' from endpoint 12 with groupID 0
zigbee2mqtt             | zigbee2mqtt:info  2020-06-15 08:45:47: Successfully interviewed '0x00124b001ada7031', device has successfully been paired
zigbee2mqtt             | zigbee2mqtt:warn  2020-06-15 08:45:47: Device '0x00124b001ada7031' with Zigbee model 'GL-C-007' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
zigbee2mqtt             | zigbee2mqtt:info  2020-06-15 08:45:47: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0x00124b001ada7031","supported":false}}'`

**Comment by Koenkk** [comment]
Can you share the `database.db` entry of this device?

**Comment by docbobo** [comment]
```
{
  "id": 48,
  "type": "Router",
  "ieeeAddr": "0x00124b001ada7031",
  "nwkAddr": 9418,
  "manufId": 0,
  "manufName": "GLEDOPTO",
  "powerSource": "Mains (single phase)",
  "modelId": "GL-C-007",
  "epList": [
    11,
    12,
    13,
    15
  ],
  "endpoints": {
    "11": {
      "profId": 49246,
      "epId": 11,
      "devId": 528,
      "inClusterList": [
        0,
        3,
        4,
        5,
        6,
        8,
        768
      ],
      "outClusterList": [],
      "clusters": {},
      "binds": []
    },
    "12": {
      "profId": 260,
      "epId": 12,
      "devId": 258,
      "inClusterList": [
        0,
        3,
        4,
        5,
        6,
        8,
        768
      ],
      "outClusterList": [],
      "clusters": {
        "genBasic": {
          "attributes": {
            "modelId": "GL-C-007",
            "manufacturerName": "GLEDOPTO",
            "powerSource": 1,
            "zclVersion": 1,
            "appVersion": 1,
            "stackVersion": 2,
            "hwVersion": 1,
            "dateCode": "20180920",
            "swBuildId": "1.0.2"
          }
        }
      },
      "binds": []
    },
    "13": {
      "profId": 49246,
      "epId": 13,
      "devId": 57694,
      "inClusterList": [
        4096
      ],
      "outClusterList": [
        4096
      ],
      "clusters": {},
      "binds": []
    },
    "15": {
      "profId": 49246,
      "epId": 15,
      "devId": 256,
      "inClusterList": [
        0,
        3,
        4,
        5,
        6,
        8,
        768
      ],
      "outClusterList": [],
      "clusters": {},
      "binds": []
    }
  },
```

**Comment by docbobo** [comment]
Found  the  problem myself... Let me prepare a PR..

**Comment by Koenkk** [comment]
Is it a color + white (RGBW) OR color + color temperature controller (RGB + CCT)?

**Comment by docbobo** [comment]
It is RGB+CCT and it roughly works when I use the  same setting as the  GLEDOPTO zigbeeModelId... But  there are some  issues

**Comment by docbobo** [comment]
Actually,  I  do  need some help here.  There is a fingerprint for  the  GL-C-007 in devices.js that seems to  match the database entry above. Why isn't it working? Because there is also EP 12? Or am  I just not noticing the  obvious  there?

**Comment by Koenkk** [comment]
Yes because EP 12 is missing. Actually this is a Gl-C-008-2ID (separate control of cct/rgb leds).

Does it work correctly with

```js
{
    fingerprint: [
        // Although the device announces modelID GL-C-007, this is clearly a GL-C-008
        // https://github.com/Koenkk/zigbee2mqtt/issues/3525
        {type: 'Router', manufacturerName: 'GLEDOPTO', modelID: 'GL-C-007', endpoints: [
            {ID: 11, profileID: 49246, deviceID: 528, inputClusters: [0, 3, 4, 5, 6, 8, 768], outputClusters: []},
            {ID: 13, profileID: 49246, deviceID: 57694, inputClusters: [4096], outputClusters: [4096]},
            {ID: 15, profileID: 49246, deviceID: 544, inputClusters: [0, 3, 4, 5, 6, 8, 768], outputClusters: []},
        ]},
        {type: 'Router', manufacturerName: 'GLEDOPTO', modelID: 'GL-C-007', endpoints: [
            {ID: 11, profileID: 49246, deviceID: 528, inputClusters: [0, 3, 4, 5, 6, 8, 768], outputClusters: []},
            {ID: 12, profileID: 260, deviceID: 258, inputClusters: [0, 3, 4, 5, 6, 8, 768], outputClusters: []},
            {ID: 13, profileID: 49246, deviceID: 57694, inputClusters: [4096], outputClusters: [4096]},
            {ID: 15, profileID: 49246, deviceID: 256, inputClusters: [0, 3, 4, 5, 6, 8, 768], outputClusters: []},
        ]},
    ],
    model: 'GL-C-008-2ID', // 2 ID controls color temperature and color separate
    vendor: 'Gledopto',
    description: 'Zigbee LED controller RGB + CCT (2 ID)',
    extend: gledopto.light,
    supports: 'on/off, brightness, color temperature, color',
    endpoint: (device) => {
        return {rgb: 11, cct: 15};
    },
},
```

**Comment by docbobo** [comment]
I only got it to work when also adding `meta: {disableDefaultResponse: true, configureKey: 1},` - is it okay if I add yet another device?

**Comment by Koenkk** [comment]
`configureKey` doesn't make a difference here (as there is no `configure`), regarding `disableDefaultResponse`, what errors do you get?

**Comment by docbobo** [comment]
Oh, yes I  know. That was just copy & paste.

Without disableDefaultResponse, the device is always show as "state = off" in Home Assistant. When I toggle them, they immediately turn off again. Logs are  showing all kinds of timeouts, e.g.

```
zigbee2mqtt             | zigbee2mqtt:error 2020-06-17 13:30:55: Publish 'set' 'state' to '0x00124b001ada7031' failed: 'Error: Command 0x00124b001ada7031/11 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Error: Timeout - 9015 - 11 - 88 - 6 - 11 after 10000ms)'
```

**Comment by Koenkk** [comment]
Preferable not, can you try if it works after applying these changes: https://github.com/Koenkk/zigbee-herdsman-converters/pull/1326/files ?

**Comment by docbobo** [comment]
Unless I screwed up my testing, I'd say that PR works

**Comment by docbobo** [comment]
BTW, is there some documentation on what disableDefaultResponse does?

**Comment by Koenkk** [comment]
I've added the entry. Will be available in the dev branch in a few hours.

By default when a command is send to a device the device send a response (acknowledging that the command has been received). This is called the `defaultResponse`. `disableDefaultResponse: true` will skip this.

Assuming this can be closed now.
