### ISSUE TITLE
Pull request build failed for new Zigbee Environment Sensor support 

### ISSUE THREAD

**Issue by iharyadi** [Koenkk/zigbee-herdsman-converters#1323]
Hello Koen,

I submitted a couple pull request to get my Environment Sensor support for Zigbee2Mqtt.   I notice that it failed during build check.

I am not familiar with node js in general.  I did follow the instruction to bring new device.  I also test the changes in my deployment.  It works just fine.

I am sure that I could have been making some mistake.  If you can let me know so that I can fix them,  I will be happy to do so.

Thank you for your work on Zigbee2mqtt.   It work very well during my testing.  I am sure that a lot of people has benefit from it.

I hope to hear from you.

Regards
Iman

**Comment by Koenkk** [comment]
Let's discuss further in the pr.
