### ISSUE TITLE
Is there a way to zigbee2mqtt/xxx/get on WSDCGQ01LM?

### ISSUE THREAD

**Issue by yangit** [Koenkk/zigbee-herdsman-converters#1327]
I'm trying to get data from `WSDCGQ01LM` humidity and temperature sensor by Xiaomi.
Pairing went fine.
Data reports by sensor are fine, but they only happen once every hour. 
Xiaomi hub can show temp data with much greater time resolution. 
I thought solution would be to 
`zigbee2mqtt/0x00158d0003a035e5/get'` `{ temperature: '', humidity: '' }` but I get
 `No converter available for 'temperature' ()` and `No converter available for 'humidity' ()`

I can request an update from sensor if it is a `ZNCZ02LM ` power socket by sending `{ state: '' }`. But I think that is because it is always on and has mains power supply.
Same `{ state: '' }` request does not work for `WSDCGQ01LM`
Anything can be done?
Am I missing the docs somwhere?

**Comment by Koenkk** [comment]
No this is not possible, the WSDCGQ01LM  is sleeping most of the time, and when it wakes up it will send a message.
