### ISSUE TITLE
GET converter is failing for IKEA Tådfri LED1624G9 color bulb

### ISSUE THREAD

**Issue by madchicken** [Koenkk/zigbee-herdsman-converters#1340]
Hi, while using this library for a custom project, I discovered that calling the GET converter for any color attribute on the Ikea LED1624G9 outputs an UNSUPPORTED_ATTRIBUTE error.
The problem is very similar to the one reported here https://github.com/Koenkk/zigbee2mqtt/issues/3260 except I am not using reporting ATM.
Maybe I didn't get how to use the converter, but I did the same test on zigbee2mqtt, and when calling GET with a payload like `{ color: { rgb: '' } }` I get the same error printed in the console.

**Comment by Koenkk** [comment]
In `toZigbee.js` can you change `await entity.read('lightingColorCtrl', ['currentX', 'currentY', 'currentHue', 'currentSaturation']);` to `await entity.read('lightingColorCtrl', ['currentX', 'currentY']);`, does this fix the issue?

See https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html on how to modify toZigbee.js

**Comment by madchicken** [comment]
Yes, it does. I was about filing a PR with the same fix, but I wasn't sure I was doing the right thing. I opened the issue to have a confirmation.

**Comment by Koenkk** [comment]
Merged the PR so I assume this can be closed now.
