### ISSUE TITLE
External converters

### ISSUE THREAD

**Issue by nurikk** [Koenkk/zigbee-herdsman-converters#1343]
Hi, @Koenkk 

I've noticed a little pain in diy community. Each and every DIY developer needs to write/modify converters, some times this devices are in very limited quantity or not even meant to be published. So many guys are modifying `fromZigbee.js` straight from `node_modules` folder, which eventually causes all changes are lost during update. What if we implement mechanism to support external converters?
We can create base package with some interfaces, like this
```
interface FromZigbeeConverter {
    cluster: string;
    type: string[];
    convert(model, msg, publish, options, meta): unknown;
}

interface ToZigbeeConverter {
    key: string[];
    convertSet(entity, key, value, meta): Promise<void>;
    convertGet(entity, key, meta): Promise<unknown>;
}
interface DeviceDescriptor {
    zigbeeModel: string[];
    model: string;
    vendor: string;
    description: string;
    supports: string;
    fromZigbee: FromZigbeeConverter[];
    toZigbee: ToZigbeeConverter[];
    meta?: { configureKey: number },
    configure?(device, coordinatorEndpoint): Promise<void>
}
``` 
+ package.json declaration 
```
{
 "name": "my-awesome-converter"
  "main": "custom-converter.js"
}
```

users could install their packages like this, or even from their github repositories
`npm install ~/my-super-converter`

And implement loading js modules who are implementing this interfaces. This configuration can be placed in z2m configuration files, where we can just list of packages ex:
```yaml
external_converters:
    - my-awesome-converter
```

If this idea is good enough, I'm ready to invest my time into implementation.

**Comment by Koenkk** [comment]
Good idea and I also like your approach.

To make it more concrete, from your example zigbee2mqtt will include `my-awesome-converter` which should expose a list of device definitions (same as `devices.js`). Zigbee2mqtt will add all these definitions to zigbee-hersman-converters (via a `addDefinition` method in `zigbee-hersman-converters/index.js`. 

Note that besides a package, it should also be possible to specify a path to a `.js` file (so users can e.g. create `data/my_device.js` and use this instead of installing a package).

**Comment by nurikk** [comment]
I've done initial development, kindly take a look. Haven't yet tested, but will do it tomorrow

**Comment by nurikk** [comment]
@Koenkk

**Comment by Koenkk** [comment]
Merged, assuming this can be closed. Big thanks!

**Comment by artem-dudarev** [comment]
Guys, could you add a similar mechanism for `mapping` in homeassistant.js?

**Comment by Koenkk** [comment]
Done, documentation: https://github.com/Koenkk/zigbee2mqtt.io/blob/develop/docs/externalConvertersExample/dummy-converter.js#L66

**Comment by ciotlosm** [comment]
Sorry for digging an old thread, but using the included example, I can't start z2m in the add-on, and I can't figure out if the path needs some changes or there is really a problem with the example:

@nurikk any help appreciated.

```
> zigbee2mqtt@1.15.0-dev start /app
> node index.js
internal/modules/cjs/loader.js:968
  throw err;
  ^
Error: Cannot find module 'zigbee-herdsman-converters'
Require stack:
- /share/zigbee2mqtt/freepad_ext.js
- /app/lib/util/utils.js
- /app/lib/util/settings.js
- /app/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/share/zigbee2mqtt/freepad_ext.js:1:34)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/share/zigbee2mqtt/freepad_ext.js',
    '/app/lib/util/utils.js',
    '/app/lib/util/settings.js',
    '/app/index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.15.0-dev start: `node index.js`
npm ERR! Exit status 1
```

**Comment by nurikk** [comment]
Hi, @ciotlosm! Yes, I see there is issue. I was able to reproduce this locally on my vanilla z2m instance using pm2

```bash
ZIGBEE2MQTT_DATA=/home/nur/data pm2-runtime start npm -- start
```

but if i'm using `pm2` instead of `pm2-runtime` everything is hunky-dory

```bash
ZIGBEE2MQTT_DATA=/home/nur/data pm2 start npm -- start
```

**Comment by nurikk** [comment]
Hi, @ciotlosm! Can you try to prepend `NODE_PATH=/app/node_modules` env variable before `ZIGBEE2MQTT_DATA` in Dockerfile?

**Comment by ciotlosm** [comment]
Thanks @nurikk it works with that set.
