### ISSUE TITLE
Illuminize 511.010

### ISSUE THREAD

**Issue by jhm47** [Koenkk/zigbee-herdsman-converters#1345]
Hi

just got a illuminize 511.010 LED dimmer (230V).

Is not in the database yet, I manually edited the devices.js and copied the config from 511.012 and renamed it to 511.010. works flawlessly :) 

Since I don't know how to upload this change (sorry, new to github) -- can somebody do that? Then this device would work for others as well, right from the start...

**Comment by Koenkk** [comment]
Added, thanks!
