### ISSUE TITLE
Add TUYA lock TY0A01 as an alias of Vima Lock A6121

### ISSUE THREAD

**Issue by DarkPark** [Koenkk/zigbee-herdsman-converters#1365]
TY0A01 is the same as A6121 but with different vendor. It would be nice not to add a new manual integration but to use the existing one.

**Comment by Koenkk** [comment]
Can you first check if this works? (https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html)

**Comment by DarkPark** [comment]
Unfortunately just addition TY0A01 to the Xiaomi lock didn't work. Pairing was successful but I can't see any parsed events from the lock (debug mode does show some). Need to investigate more.

**Comment by Koenkk** [comment]
Closing this in favour of https://github.com/Koenkk/zigbee-herdsman-converters/issues/1433
