### ISSUE TITLE
Better customization support

### ISSUE THREAD

**Issue by DarkPark** [Koenkk/zigbee-herdsman-converters#1366]
There is a huge `device.js` file with all the devices. In order to add a new device it's necessary to modify this one very important file.
It would be nice to have a new file (e.g. `device.override.js`) which by default exports an empty list but can contain any new custom devices. This file should be imported (probably even with try/catch because there can be some typos from some inexperienced users) to `device.js` and merged with general device list.
This approach also can simplify new devices creation when zigbee2mqtt is used as a docker container. Now it's not a trivial task but in future it's possible to export only `device.override.js` as a volume and modify it independent from all existing devices.

**Comment by Koenkk** [comment]
This can be done with external converters (https://www.zigbee2mqtt.io/information/configuration.html#external-converters-configuration) (new feature added in zigbee2mqtt 1.14.1).

**Comment by DarkPark** [comment]
Thank you. Will try this approach.
