### ISSUE TITLE
Yale YMF 40 unsupported although in the supported list

### ISSUE THREAD

**Issue by jrespir** [Koenkk/zigbee-herdsman-converters#1373]
First I'm sorry if this is not the place to post but, I already did everything and I can't solve my problem. I have the latest home assistant installed on the docker. Updated zigbee2mqtt addon. My lock in the pairing appears as unsupported despite a while ago working perfectly. I am a beginner and would like to know how to make the home assistant look at the converter file. thanks in advance

**Comment by Koenkk** [comment]
Can you share your logging?

**Comment by jrespir** [comment]
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
./run.sh: line 17: [Info] Configuration backup found in /share/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory
[Info] Socat is DISABLED and not started
2020-07-04T10:16:09: PM2 log: Launching in no daemon mode
2020-07-04T10:16:09: PM2 log: App [npm:0] starting in -fork mode-
2020-07-04T10:16:10: PM2 log: App [npm:0] online
> zigbee2mqtt@1.14.1 start /zigbee2mqtt-1.14.1
> node index.js
zigbee2mqtt:info  2020-07-04 10:16:15: Logging to console and directory: '/share/zigbee2mqtt/log/2020-07-04.10-16-15' filename: log.txt
zigbee2mqtt:info  2020-07-04 10:16:16: Starting zigbee2mqtt version 1.14.1 (commit #unknown)
zigbee2mqtt:info  2020-07-04 10:16:16: Starting zigbee-herdsman...
zigbee2mqtt:info  2020-07-04 10:16:17: zigbee-herdsman started
zigbee2mqtt:info  2020-07-04 10:16:17: Coordinator firmware version: '{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}}'
zigbee2mqtt:info  2020-07-04 10:16:17: Currently 1 devices are joined:
zigbee2mqtt:info  2020-07-04 10:16:17: 0x000d6f00118c149b (0x000d6f00118c149b): Not supported (EndDevice)
zigbee2mqtt:warn  2020-07-04 10:16:17: `permit_join` set to  `true` in configuration.yaml.
zigbee2mqtt:warn  2020-07-04 10:16:17: Allowing new devices to join.
zigbee2mqtt:warn  2020-07-04 10:16:17: Set `permit_join` to `false` once you joined all devices.
zigbee2mqtt:info  2020-07-04 10:16:17: Zigbee: allowing new devices to join.
zigbee2mqtt:info  2020-07-04 10:16:18: Connecting to MQTT server at mqtt://192.168.68.135:1883
zigbee2mqtt:info  2020-07-04 10:16:19: Connected to MQTT server
zigbee2mqtt:info  2020-07-04 10:16:19: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
zigbee2mqtt:info  2020-07-04 10:16:19: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.14.1","commit":"unknown","coordinator":{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}},"log_level":"info","permit_join":true}'
zigbee2mqtt:warn  2020-07-04 10:19:06: Device '0x000d6f00118c149b' left the network
zigbee2mqtt:info  2020-07-04 10:19:06: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_removed","message":"left_network","meta":{"friendly_name":"0x000d6f00118c149b"}}'
zigbee2mqtt:info  2020-07-04 10:19:10: Device '0x000d6f00118c149b' joined
zigbee2mqtt:info  2020-07-04 10:19:10: Starting interview of '0x000d6f00118c149b'
zigbee2mqtt:info  2020-07-04 10:19:10: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":{"friendly_name":"0x000d6f00118c149b"}}'
zigbee2mqtt:info  2020-07-04 10:19:10: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"0x000d6f00118c149b"}}'
zigbee2mqtt:info  2020-07-04 10:19:11: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_announced","message":"announce","meta":{"friendly_name":"0x000d6f00118c149b"}}'
zigbee2mqtt:warn  2020-07-04 10:19:31: Received message from unsupported device with Zigbee model '0700000001'
zigbee2mqtt:warn  2020-07-04 10:19:31: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.

**Comment by Koenkk** [comment]
Can you check if it works now?

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html) (edge version for hassio)

**Comment by jrespir** [comment]
It worked. I have no words to thank. I was stuck in this for several days. Thank you very much for your attention.
