### ISSUE TITLE
eCozy 1TST-EU - No converter available for 'thermostat_occupancy' 

### ISSUE THREAD

**Issue by MarcSN311** [Koenkk/zigbee-herdsman-converters#1380]
Hi! 
I am trying to read the occupancy from a eCozy 1TST-EU thermostat. But I am getting the following error message:

```
Jul 08 20:27:40 hass npm[11835]: zigbee2mqtt:debug 2020-07-08 20:27:40: Received MQTT message on 'zigbee2mqtt/0x70b3d5de0000116e/get/thermostat_occupancy' with data ''
Jul 08 20:27:40 hass npm[11835]: zigbee2mqtt:error 2020-07-08 20:27:40: No converter available for 'thermostat_occupancy' ()
```
I updated to the latest version before testing.

Am I doing it wrong or is there a problem with my installation? The device page is not very clear about reading data from the device.

EDIT: `pi_heating_demand` and `running_state` give the same message

**Comment by Koenkk** [comment]
`thermostat_occupancy` should be `occupancy`. 

I've added `pi_heating_demand` and `running_state`

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by MarcSN311** [comment]
Awesome thanks! I will try it tomorrow.
