### ISSUE TITLE
Add Philips LWA009

### ISSUE THREAD

**Issue by NeV3rKilL** [Koenkk/zigbee-herdsman-converters#1382]
LWA009 only has brightness parameter and it's pretty similar to LWA007.

I tried to branch the project to create a pull request but it's closed.

Here is the code:

`{
        zigbeeModel: ['LWA009'],
        model: '9290023349',
        vendor: 'Philips',
        description: 'Hue white A67 bulb E26 with Bluetooth. 1600 Lumenns',
        extend: hue.light_onoff_brightness,
        ota: ota.zigbeeOTA,
    },`

**Comment by Koenkk** [comment]
added, thanks!
