### ISSUE TITLE
After 1.14.1 update my gledopto controller began to write that it is not supported

### ISSUE THREAD

**Issue by daddvok** [Koenkk/zigbee-herdsman-converters#1392]
{
        zigbeeModel: ['GL-C-009'],
        **fingerprint: [
            {type: 'Router', manufacturerName: 'GLEDOPTO', modelID: 'GLEDOPTO', endpoints: [
                {ID: 11, profileID: 49246, deviceID: 256, inputClusters: [0, 3, 4, 5, 6, 8], outputClusters: []},
                {ID: 13, profileID: 49246, deviceID: 57694, inputClusters: [4096], outputClusters: [4096]},
            ]},
        ],**
        model: 'GL-C-009',
        vendor: 'Gledopto',
        description: 'Zigbee LED controller dimmer',
        extend: gledopto.light_onoff_brightness,
},
added this line to devices.js and the problem was solved

**Comment by Koenkk** [comment]
Added, thanks!

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
