### ISSUE TITLE
Applying a unified description for message topics

### ISSUE THREAD

**Issue by MarcSchmidt** [Koenkk/zigbee-herdsman-converters#1393]
Hello,

Currently, I need to consider different topics (like "action" and "click") when I am switching between remotes/switches, while these remotes do similar things. It would be preferable when all remotes/switches would use a unified topic e.g. all use "action" or all use "click". 
Example:
[Xiaomi WXKG02LM](https://www.zigbee2mqtt.io/devices/WXKG01LM.html)
Payload: {"battery":100,"voltage":3012,"linkquality":65,**"click":"single"**}
[Philips 324131092621](https://www.zigbee2mqtt.io/devices/324131092621.html)
Payload: {"battery":100,"linkquality":68,"counter":1,"brightness":255,"update_available":false,**"action":"on-press"**,"duration":0}
[IKEA E1524/E1810](https://www.zigbee2mqtt.io/devices/E1524_E1810.html)
{"battery":34,"linkquality":55,"update_available":false,**"action":"toggle"**}

Personally I would suggest the usage of the term "action" as it is more versatile.

From my understanding the required change would be to replace all "click" with "action" in the converter [fromZigbee.js](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/converters/fromZigbee.js).
Example
Xiaomi WXKG02LM
WXKG02LM_click: {
        cluster: 'genOnOff',
        type: ['attributeReport', 'readResponse'],
        convert: (model, msg, publish, options, meta) => {
            return {**click**: getKey(model.endpoint(msg.device), msg.endpoint.ID)};
        },
    },
IKEA E1524/E1810
E1524_E1810_toggle: {
        cluster: 'genOnOff',
        type: 'commandToggle',
        convert: (model, msg, publish, options, meta) => {
            const payload = **{action:** getProperty('toggle', msg, model)};
            return payload;
        },
    },

So my question would be:
1. Can we unify the structure for all devices?
2. Is my understanding of the code correct, that it would only require an update of one file?

Greetings
Marc

**Comment by dchwilk** [comment]
that would be really helpful

**Comment by Koenkk** [comment]
`click` is deprecated and should be replaced by `action`, all new integrations are forced to use `action`, as changing `click` to `action` would result in a breaking change this is currently not done (until Zigbee2mqtt 2.0.0). 

Something we can consider is adding both for the time being, however I'm not sure if this will create confusion for users.

**Comment by MarcSchmidt** [comment]
Thx for the fast reply. 
I think for a smooth transition from the deprecated solution to the newer `action` a duplication should be considered. Then the users could switch over time from one solution to the newer one and are not forced to make a hard migration to 2.0.

To prevent the confusion of users the documentation could be updated with an deprecation information. (This would also prevent creating more technical debt until the new version is out)

**Comment by Koenkk** [comment]
Good, in case you are interested feel free to make some PRs already (simply add `action` e.g. here: https://github.com/Koenkk/zigbee-herdsman-converters/blob/6a2faed478e88a7af536de76d7ee8f5559f3f642/converters/fromZigbee.js#L1581). If not I will pick this up later.

**Comment by MarcSchmidt** [comment]
I have started with the first device and will create more PRs later on.

**Comment by MarcSchmidt** [comment]
@Koenkk Is there any device, for which `click` is not deprecated in favor of `action`? Or can I update all devices in the list

**Comment by Koenkk** [comment]
Closing this as https://github.com/Koenkk/zigbee-herdsman-converters/pull/1399 is merged

**Comment by uncle-fed** [comment]
> Something we can consider is adding both for the time being, however I'm not sure if this will create confusion for users.

Speaking of user's confusion...

Was this intentional that the legacy value for a left/right switch looks like `"click":"right_double"` but the new one looks like `"action":"double_right"`  (i.e., the value has the order of `right` and `double` reversed).

Confused my existing automation for sure :-)

**Comment by uncle-fed** [comment]
@Koenkk , what about consistency when the 'legacy: false' is set?
I am getting this now for 2 different devices...
Don't you think that the `double` part should go the end of the value, rather?

```
WXCJKG12LM - Xiaomi Aqara Opple switch 2 bands:           payload '{"action":"button_3_single"}'
WXKG02LM - Xiaomi Aqara double key wireless wall switch:  payload '{"action":"double_right"}'
```

**Comment by Koenkk** [comment]
`double_right` is the correct one, only the devices that used `click` have been refactored, devices that already used `action` have not been refactored yet (therefore `legacy: false` won't make a difference).

**Comment by uncle-fed** [comment]
Not to question it largely, just curious, what sort of logic led to decision to have `<typeOfAction>_<subDeviceId>` order?
Is there more to it or was it a random decision?

**Comment by Koenkk** [comment]
For device with only a single endpoint (e.g. `WXKG01LM`) the payload will be `double`, in my opinion it is logic that for the devices with multiple endpoints the endpoint was added as a postfix.

**Comment by AlexeyHimki** [comment]
zigbee2mqtt 1.14.3
Xiaomi QBKG11LM in Decoupled mode
When I press the button physicaly:
`
{"state":"OFF","linkquality":63,"power":0,"consumption":0.98,"temperature":28,"action":"single"}
`
And when I toggle from HA:
`
{"state":"ON","linkquality":63,"power":0,"consumption":0.98,"temperature":28,"action":"single"}
`
There is the same action SINGLE. But I need a trigger that must be work only on a physical press.

How can I do this?

**Comment by Koenkk** [comment]
@AlexeyHimki can you provide the debug logging of this?

To enable debug logging set in `configuration.yaml`:
```yaml
advanced:
  log_level: debug
```

**Comment by AlexeyHimki** [comment]
Physical press:
`
Zigbee2MQTT:info  2020-08-19 00:32:38: MQTT publish: topic 'zigbee2mqtt/garderob.wired_switch', payload '{"state":"OFF","linkquality":55,"power":0,"consumption":0.98,"temperature":28,"action":"single"}'
Zigbee2MQTT:info  2020-08-19 00:32:38: MQTT publish: topic 'zigbee2mqtt/garderob.wired_switch', payload '{"state":"OFF","linkquality":55,"power":0,"consumption":0.98,"temperature":28,"action":""}'
Zigbee2MQTT:info  2020-08-19 00:32:38: MQTT publish: topic 'homeassistant/device_automation/0x00158d00041e7383/action_single/config', payload '{"automation_type":"trigger","type":"action","subtype":"single","payload":"single","topic":"zigbee2mqtt/garderob.wired_switch/action","device":{"identifiers":["zigbee2mqtt_0x00158d00041e7383"],"name":"garderob.wired_switch","sw_version":"Zigbee2MQTT 1.14.3","model":"Aqara single key wired wall switch (QBKG11LM)","manufacturer":"Xiaomi"}}'
Zigbee2MQTT:info  2020-08-19 00:32:38: MQTT publish: topic 'zigbee2mqtt/garderob.wired_switch/action', payload 'single'
`

Remote toggle:
`
Zigbee2MQTT:info  2020-08-19 00:34:40: MQTT publish: topic 'zigbee2mqtt/garderob.wired_switch', payload '{"state":"ON","linkquality":55,"power":0,"consumption":0.98,"temperature":28}'
Zigbee2MQTT:info  2020-08-19 00:34:40: MQTT publish: topic 'zigbee2mqtt/garderob.wired_switch', payload '{"state":"ON","linkquality":49,"power":0,"consumption":0.98,"temperature":28,"action":"single"}'
Zigbee2MQTT:info  2020-08-19 00:34:40: MQTT publish: topic 'zigbee2mqtt/garderob.wired_switch', payload '{"state":"ON","linkquality":49,"power":0,"consumption":0.98,"temperature":28,"action":""}'
Zigbee2MQTT:info  2020-08-19 00:34:40: MQTT publish: topic 'zigbee2mqtt/garderob.wired_switch/action', payload 'single'
`

**Comment by Koenkk** [comment]
@AlexeyHimki should be fixed

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
