### ISSUE TITLE
Exception in PromiseRejectCallback

### ISSUE THREAD

**Issue by Wuppi68** [Koenkk/zigbee-herdsman-converters#1412]
i got the following error and i have no clue how to fix it :-(

```
Exception in PromiseRejectCallback:
/Users/ralf/zigbee2mqtt/node_modules/zigbee-herdsman-converters/converters/toZigbee.js:1520
            return await converters.gledopto_light_color_colortemp.convertGet(entity, key, meta);
```

if u need more information i can get it
the bulbs seems to be runing well

**Comment by Koenkk** [comment]
Please provide more logging (debug logging) and context (what did you do, expected behaviour) of this issue.

To enable debug logging set in `configuration.yaml`:
```yaml
advanced:
  log_level: debug
```

**Comment by Wuppi68** [comment]
sorry, there is no more log :-(

The bulb reports some status and this error apears ...

at wednesday i am able to check more

**Comment by Wuppi68** [comment]
After updating yesterday, those annoying had gone :-)

Thx

**Comment by Wuppi68** [comment]
just noticed ... it's back :-(
`2020-07-29 21:46:20: Successfully pinged 'Gledo_GL_S_004ZS_12'
zigbee2mqtt:debug 2020-07-29 21:46:20: Received Zigbee message from 'Gledo_GL_S_004ZS_12', type 'readResponse', cluster 'genOnOff', data '{"onOff":0}' from endpoint 11 with groupID 0
zigbee2mqtt:info  2020-07-29 21:46:20: MQTT publish: topic 'zigbee2mqtt-dev/Gledo_GL_S_004ZS_12', payload '{"state":"OFF","linkquality":39,"brightness":254,"color_temp":314,"color":{"x":0.1904,"y":0.7201},"last_seen":"2020-07-29T21:46:20+02:00"}'
zigbee2mqtt:debug 2020-07-29 21:46:21: Received Zigbee message from 'Gledo_GL_S_004ZS_12', type 'readResponse', cluster 'genLevelCtrl', data '{"currentLevel":254}' from endpoint 11 with groupID 0
zigbee2mqtt:info  2020-07-29 21:46:21: MQTT publish: topic 'zigbee2mqtt-dev/Gledo_GL_S_004ZS_12', payload '{"state":"OFF","linkquality":42,"brightness":254,"color_temp":314,"color":{"x":0.1904,"y":0.7201},"last_seen":"2020-07-29T21:46:21+02:00"}'
Exception in PromiseRejectCallback:
/Users/ralf/zigbee2mqtt/node_modules/zigbee-herdsman-converters/converters/toZigbee.js:1527
            return await converters.gledopto_light_color_colortemp.convertGet(entity, key, meta);
                                                                                                 

RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
/Users/ralf/zigbee2mqtt/node_modules/zigbee-herdsman-converters/converters/toZigbee.js:1527
            return await converters.gledopto_light_color_colortemp.convertGet(entity, key, meta);
                                                                   ^

RangeError: Maximum call stack size exceeded
zigbee2mqtt:error 2020-07-29 21:46:21: Failed to read state of 'Gledo_GL_S_004ZS_12' after reconnect
`

**Comment by Wuppi68** [comment]
or is it possible cause of 14 bulbs switched on at the same time (power on ...)?

**Comment by Koenkk** [comment]
Are you still on the latest dev? Because line 1527 doesn't match with the current dev
