### ISSUE TITLE
Issue with supported device GZCGQ01LM: unsupported device error

### ISSUE THREAD

**Issue by eriksnijder** [Koenkk/zigbee-herdsman-converters#1425]
I have 2  GZCGQ01LM light sensor devices. The devices are in the supported devices list. Both are able to pair but then present an unsupported device warning. I have upgaded my 2531 coördinator from 1.2 to the 3.0 firmware but to no avail.
Debug log:
zigbee2mqtt:warn  2020-07-23T09:52:19: Device '0x04cf8cdf3c7880d0' left the network
zigbee2mqtt:info  2020-07-23T09:52:19: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_removed","message":"left_network","meta":{"friendly_name":"0x04cf8cdf3c7880d0"}}'
zigbee2mqtt:info  2020-07-23T09:52:22: Device '0x04cf8cdf3c7880d0' joined
zigbee2mqtt:info  2020-07-23T09:52:22: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":{"friendly_name":"0x04cf8cdf3c7880d0"}}'
zigbee2mqtt:info  2020-07-23T09:52:22: Starting interview of '0x04cf8cdf3c7880d0'
zigbee2mqtt:info  2020-07-23T09:52:22: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"0x04cf8cdf3c7880d0"}}'
zigbee2mqtt:debug 2020-07-23T09:52:23: Device '0x04cf8cdf3c7880d0' announced itself
zigbee2mqtt:debug 2020-07-23T09:52:25: Received Zigbee message from '0x04cf8cdf3c7880d0', type 'readResponse', cluster 'genBasic', data '{"modelId":"lumi.sen_ill.mgl01","manufacturerName":"LUMI","powerSource":3}' from endpoint 1 with groupID 0
zigbee2mqtt:warn  2020-07-23T09:52:25: Received message from unsupported device with Zigbee model 'lumi.sen_ill.mgl01'
zigbee2mqtt:warn  2020-07-23T09:52:25: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
zigbee2mqtt:debug 2020-07-23T09:52:26: Received Zigbee message from '0x04cf8cdf3c7880d0', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3,"appVersion":21,"stackVersion":2}' from endpoint 1 with groupID 0
zigbee2mqtt:warn  2020-07-23T09:52:26: Received message from unsupported device with Zigbee model 'lumi.sen_ill.mgl01'
zigbee2mqtt:warn  2020-07-23T09:52:26: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
zigbee2mqtt:debug 2020-07-23T09:52:29: Received Zigbee message from '0x04cf8cdf3c7880d0', type 'readResponse', cluster 'genBasic', data '{"hwVersion":1,"dateCode":"20191118","swBuildId":"2019\u0000www."}' from endpoint 1 with groupID 0
zigbee2mqtt:warn  2020-07-23T09:52:29: Received message from unsupported device with Zigbee model 'lumi.sen_ill.mgl01'
zigbee2mqtt:warn  2020-07-23T09:52:29: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
zigbee2mqtt:info  2020-07-23T09:52:29: Successfully interviewed '0x04cf8cdf3c7880d0', device has successfully been paired
zigbee2mqtt:warn  2020-07-23T09:52:29: Device '0x04cf8cdf3c7880d0' with Zigbee model 'lumi.sen_ill.mgl01' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
zigbee2mqtt:info  2020-07-23T09:52:29: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0x04cf8cdf3c7880d0","supported":false}}'

Could you please assist?

Regards, Erik

**Comment by Koenkk** [comment]
What zigbee2mqtt version are you running?

**Comment by eriksnijder** [comment]
I'm running version 1.7.1 of zigbee2mqtt.

**Comment by Koenkk** [comment]
The device was not supported in that version yet, upgrade to the latest zigbee2mqtt version (1.14.1).

**Comment by eriksnijder** [comment]
Ok, the addon was on auto-update so wasn't aware of a new version. Thanks for your reaction.
