### ISSUE TITLE
WEIMA A6121 - Tuya - How to get messages for new converter?

### ISSUE THREAD

**Issue by marv-in-r** [Koenkk/zigbee-herdsman-converters#1433]
Hello, I have a Tuya-based A6121

[http://www.r-wima.com/en/ShowPro.asp?ID=1](url)

What I did:
1 Changed decices.js with copy from your
Xiaomi A6121 [https://www.zigbee2mqtt.io/devices/A6121.html](url)
and added some configureKeys I found (Where can I find a doc/Wiki about devices.js-Settings?)
=> device joined, but without any useable message fromZigbee
2 set Debug-Mode as you described [https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html](url)
3 put key into the cylinder, left it, did a pick,... and got this

> zigbee2mqtt:info  2020-07-25 12:53:07: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.14.1","commit":"f8463d9","coordinator":{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}},"log_level":"debug","permit_join":false}'
zigbee2mqtt:error 2020-07-25 12:53:44: Failed to configure '0xec1bbdfffe7816f8', attempt 1 (Error: ConfigureReporting 0xec1bbdfffe7816f8/1 genPowerCfg([{"attribute":"batteryPercentageRemaining","minimumReportInterval":3600,"maximumReportInterval":62000,"reportableChange":0}], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Error: Timeout - 64366 - 1 - 3 - 1 - 7 after 10000ms)
    at Endpoint.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:341:23)
    at Generator.throw (<anonymous>)
    at rejected (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65))
zigbee2mqtt:debug 2020-07-25 12:54:05: Received Zigbee message from '0xec1bbdfffe7816f8', type 'attributeReport', cluster 'genBasic', data '{"65506":22,"appVersion":85}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-07-25 12:54:05: No converter available for 'A6121' with cluster 'genBasic' and type 'attributeReport' and data '{"65506":22,"appVersion":85}'
zigbee2mqtt:info  2020-07-25 12:54:05: Configuring '0xec1bbdfffe7816f8'
zigbee2mqtt:error 2020-07-25 12:54:30: Failed to configure '0xec1bbdfffe7816f8', attempt 2 (Error: ConfigureReporting 0xec1bbdfffe7816f8/1 genPowerCfg([{"attribute":"batteryPercentageRemaining","minimumReportInterval":3600,"maximumReportInterval":62000,"reportableChange":0}], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Error: Timeout - 64366 - 1 - 4 - 1 - 7 after 10000ms)
    at Endpoint.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:341:23)
    at Generator.throw (<anonymous>)
    at rejected (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65))
zigbee2mqtt:debug 2020-07-25 12:55:04: Received Zigbee message from '0xec1bbdfffe7816f8', type 'read', cluster 'genTime', data '["localTime"]' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-07-25 12:55:04: Configuring '0xec1bbdfffe7816f8'
zigbee2mqtt:error 2020-07-25 12:55:40: Failed to configure '0xec1bbdfffe7816f8', attempt 3 (Error: ConfigureReporting 0xec1bbdfffe7816f8/1 genPowerCfg([{"attribute":"batteryPercentageRemaining","minimumReportInterval":3600,"maximumReportInterval":62000,"reportableChange":0}], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Error: Timeout - 64366 - 1 - 5 - 1 - 7 after 10000ms)
    at Endpoint.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:341:23)
    at Generator.throw (<anonymous>)
    at rejected (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65))
zigbee2mqtt:debug 2020-07-25 12:57:23: Received Zigbee message from '0xec1bbdfffe7816f8', type 'attributeReport', cluster 'genBasic', data '{"65506":22,"appVersion":85}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-07-25 12:57:23: No converter available for 'A6121' with cluster 'genBasic' and type 'attributeReport' and data '{"65506":22,"appVersion":85}'

4 Now I don‘t know how to do the next step. Could anyone help me please? I want to do the work, but I need a tip.

**Comment by marv-in-r** [comment]
@Koenkk Sorry, saw [https://github.com/Koenkk/zigbee-herdsman-converters/issues/1365](url) yet

**Comment by marv-in-r** [comment]
my device setting 

> {
        zigbeeModel: ['TY0A01'],
        model: 'A6121',
        vendor: 'VIMA',
        description: 'VIMA LOCK',
        supports: 'inserted, forgotten and key error',
        fromZigbee: [],
        toZigbee: [tz.generic_lock],
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            await bind(endpoint, coordinatorEndpoint, ['genPowerCfg']);
            await configureReporting.batteryPercentageRemaining(endpoint);
            await configureReporting.batteryVoltage(endpoint);
        },
    },

**Comment by Koenkk** [comment]
Can you lock/unlock with this config by sending to `zigbee2mqtt/0xec1bbdfffe7816f8/set` payload `{"state": "LOCK"}`?

**Comment by marv-in-r** [comment]
I gives me

> zigbee2mqtt:debug 2020-07-26 12:40:44: Received MQTT message on 'zigbee2mqtt/0xec1bbdfffe7816f8/set' with data 'payload {"state": "LOCK"}'
zigbee2mqtt:debug 2020-07-26 12:40:44: Publishing 'set' 'state' to '0xec1bbdfffe7816f8'
zigbee2mqtt:error 2020-07-26 12:40:44: Publish 'set' 'state' to '0xec1bbdfffe7816f8' failed: 'Error: Cluster 'closuresDoorLock' has no command 'payload {"state": "lock"}Door''
zigbee2mqtt:debug 2020-07-26 12:40:44: Error: Cluster 'closuresDoorLock' has no command 'payload {"state": "lock"}Door'
    at Object.getCommand (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/zcl/utils.js:106:19)
    at Endpoint.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:349:37)
    at Generator.next (<anonymous>)
    at /opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:4:12)
    at Endpoint.command (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:347:16)
    at Object.convertSet (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/converters/toZigbee.js:1422:26)
    at EntityPublish.onMQTTMessage (/opt/zigbee2mqtt/lib/extension/publish.js:197:52)
    at Controller.callExtensionMethod (/opt/zigbee2mqtt/lib/controller.js:360:44)
zigbee2mqtt:info  2020-07-26 12:40:44: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'state' to '0xec1bbdfffe7816f8' failed: 'Error: Cluster 'closuresDoorLock' has no command 'payload {\"state\": \"lock\"}Door''","meta":{"friendly_name":"0xec1bbdfffe7816f8"}}'

**Comment by marv-in-r** [comment]
Your device-info page shows a Xiaomi A6121 with support for _inserted, forgotten, key error_. Do I have to use another command?

**Comment by Koenkk** [comment]
payload should be `{"state": "LOCK"}` instead of ` payload {"state": "LOCK"}`

**Comment by marv-in-r** [comment]
:see_no_evil: Uups.... Thank you for your help and patience!

Now I get:

> zigbee2mqtt:debug 2020-07-26 13:49:34: Received MQTT message on 'zigbee2mqtt/0xec1bbdfffe7816f8/set' with data '{"state": "LOCK"}'
zigbee2mqtt:debug 2020-07-26 13:49:34: Publishing 'set' 'state' to '0xec1bbdfffe7816f8'
zigbee2mqtt:error 2020-07-26 13:50:00: Publish 'set' 'state' to '0xec1bbdfffe7816f8' failed: 'Error: Command 0xec1bbdfffe7816f8/1 closuresDoorLock.lockDoor({"pincodevalue":""}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Error: Timeout - 64366 - 1 - 6 - 257 - 0 after 10000ms)'
zigbee2mqtt:debug 2020-07-26 13:50:00: Error: Command 0xec1bbdfffe7816f8/1 closuresDoorLock.lockDoor({"pincodevalue":""}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Error: Timeout - 64366 - 1 - 6 - 257 - 0 after 10000ms)
    at Endpoint.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:365:23)
    at Generator.throw (<anonymous>)
    at rejected (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65)
zigbee2mqtt:info  2020-07-26 13:50:00: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'state' to '0xec1bbdfffe7816f8' failed: 'Error: Command 0xec1bbdfffe7816f8/1 closuresDoorLock.lockDoor({\"pincodevalue\":\"\"}, {\"timeout\":10000,\"disableResponse\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null}) failed (Error: Timeout - 64366 - 1 - 6 - 257 - 0 after 10000ms)'","meta":{"friendly_name":"0xec1bbdfffe7816f8"}}'
zigbee2mqtt:debug 2020-07-26 13:50:10: Received Zigbee message from '0xec1bbdfffe7816f8', type 'read', cluster 'genTime', data '["localTime"]' from endpoint 1 with groupID 0

**Comment by Koenkk** [comment]
It seems that the device uses non-standard commands (unfortunately normal for TuYa devices). This makes adding support much harder. You can try following: https://medium.com/@dzegarra/zigbee2mqtt-how-to-add-support-for-a-new-tuya-based-device-part-2-5492707e882d
