### ISSUE TITLE
GLEDOPTO 008 RGBW (2ID) not working anymore

### ISSUE THREAD

**Issue by andreasbrett** [Koenkk/zigbee-herdsman-converters#1444]
My GLEDOPTO 008 in RGBW (2 ID) is not working anymore after I updated z2m to the latest dev. Can't pinpoint exactly when there were changes that broke something. The 008 is not responding to any command. I can't change state nor color. I switched from an older z2m dev version to the current dev (maybe 2-3 months between versions).

What I already did:
re-paired the 008

What the logs show:
no errors but the 008 responds to pings

I do not quite understand the "new" way the gledopto converters work (although it looks nicely organised and clean). The fingerprinting identifies the 008 as GL-C-007-2ID (checked by requesting device list via zigbee2mqtt/bridge/config/devices/get). The database entry looks like this:

It matches the fingerprint in https://github.com/Koenkk/zigbee-herdsman-converters/blob/99ed14740fb67d75be2c7f0ee0b32dfdc46a33e7/devices.js#L5064. Not sure though why the 008 is not responding to any command I send. "state": "ON"/"OFF" does not work as well as "color": "{"rgb": "0, 200, 0"}" does not work. Could you help me out debugging this? I see that there were no changes regarding endpoint usage (11 for rgb, 13 for white).

**Comment by Koenkk** [comment]
- Is yours a RGB + CCT or RGBW controller?
- Can you share the `data/database.db` entry?

**Comment by andreasbrett** [comment]
> * Is yours a RGB + CCT or RGBW controller?

It's a RGBW controller. The attached LED strip is RGB only, so the W-port is not connected though.

> * Can you share the `data/database.db` entry?

Yes, of course. I masked the mac address for security reasons. The fingerprint linked in my previous post matches that entry.

`
{"id":2,"type":"Router","ieeeAddr":"0x6666666666666666","nwkAddr":12565,"manufId":0,"manufName":"GLEDOPTO","powerSource":"Mains (single phase)","modelId":"GLEDOPTO","epList":[10,11,13],"endpoints":{"10":{"profId":49246,"epId":10,"devId":256,"inClusterList":[0,3,4,5,6,8],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"modelId":"GLEDOPTO","manufacturerName":"GLEDOPTO","powerSource":1,"zclVersion":1,"appVersion":1,"stackVersion":2,"hwVersion":1,"dateCode":"20131206","swBuildId":"1.0.2"}},"genOnOff":{"attributes":{"onOff":1}},"genLevelCtrl":{"attributes":{"currentLevel":76}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0018df4533","endpointID":1}]},"11":{"profId":49246,"epId":11,"devId":528,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{},"binds":[]},"13":{"profId":49246,"epId":13,"devId":57694,"inClusterList":[4096],"outClusterList":[4096],"clusters":{},"binds":[]}},"appVersion":1,"stackVersion":2,"hwVersion":1,"dateCode":"20131206","swBuildId":"1.0.2","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1596145674268}`

**Comment by Koenkk** [comment]
Looks good, can you provide me the herdsman debug log when trying to turn on the RGB?

To enable herdsman debug logging, see https://www.zigbee2mqtt.io/information/debug.html#zigbee-herdsman-debug-logging

**Comment by andreasbrett** [comment]
`
> zigbee-herdsman:controller:endpoint Command 0x6666666666666666/10 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) +14s
  zigbee-herdsman:adapter:zStack:znp:SREQ --> AF - dataRequest - {"dstaddr":12565,"destendpoint":10,"srcendpoint":1,"clusterid":6,"transid":3,"options":0,"radius":30,"len":3,"data":{"type":"Buffer","data":[1,3,1]}} +14s
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,13,36,1,21,49,10,1,6,0,3,0,30,3,1,3,1,28] +14s
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,100,1,0,100] +14s
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,100,1,0,100] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 4 - 1 - [0] - 100 +0ms
  zigbee-herdsman:adapter:zStack:znp:SRSP <-- AF - dataRequest - {"status":0} +14s
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,68,128,0,1,3,197] +6ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,68,128,0,1,3,197] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 4 - 128 - [0,1,3] - 197 +0ms
  zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - dataConfirm - {"status":0,"endpoint":1,"transid":3} +14s
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,7,69,196,21,49,2,72,253,2,21,2] +45ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,7,69,196,21,49,2,72,253,2,21,2] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 7 - 2 - 5 - 196 - [21,49,2,72,253,2,21] - 2 +0ms
  zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - srcRtgInd - {"dstaddr":12565,"relaycount":2,"relaylist":[64840,5378]} +47ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,25,68,129,0,0,6,0,21,49,10,1,0,63,0,100,144,62,0,0,5,24,3,11,1,0,2,21,27,24] +12ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,25,68,129,0,0,6,0,21,49,10,1,0,63,0,100,144,62,0,0,5,24,3,11,1,0,2,21,27,24] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 25 - 2 - 4 - 129 - [0,0,6,0,21,49,10,1,0,63,0,100,144,62,0,0,5,24,3,11,1,0,2,21,27] - 24 +0ms
  zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - incomingMsg - {"groupid":0,"clusterid":6,"srcaddr":12565,"srcendpoint":10,"dstendpoint":1,"wasbroadcast":0,"linkquality":63,"securityuse":0,"timestamp":4100196,"transseqnumber":0,"len":5,"data":{"type":"Buffer","data":[24,3,11,1,0]}} +14ms
  zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":true,"reservedBits":0},"transactionSequenceNumber":3,"manufacturerCode":null,"commandIdentifier":11},"Payload":{"cmdId":1,"statusCode":0}},"address":12565,"endpoint":10,"linkquality":63,"groupID":0}' +14s
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +4ms
  zigbee-herdsman:controller:endpoint Command 0x6666666666666666/10 genLevelCtrl.moveToLevelWithOnOff({"level":132.47878,"transtime":4}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) +107ms
  zigbee-herdsman:adapter:zStack:znp:SREQ --> AF - dataRequest - {"dstaddr":12565,"destendpoint":10,"srcendpoint":1,"clusterid":8,"transid":4,"options":0,"radius":30,"len":6,"data":{"type":"Buffer","data":[1,4,4,132,4,0]}} +107ms
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,16,36,1,21,49,10,1,8,0,4,0,30,6,1,4,4,132,4,0,143] +107ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,100,1,0,100,254,3,68,128,0,1,4,194] +41ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,100,1,0,100,254,3,68,128,0,1,4,194] +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 4 - 1 - [0] - 100 +10ms
  zigbee-herdsman:adapter:zStack:znp:SRSP <-- AF - dataRequest - {"status":0} +124ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,68,128,0,1,4,194] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 4 - 128 - [0,1,4] - 194 +1ms
  zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - dataConfirm - {"status":0,"endpoint":1,"transid":4} +57ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,25,68,129,0,0,8,0,21,49,10,1,0,65,0,144,145,62,0,0,5,24,4,11,4,0,2,21,27,159] +37ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,25,68,129,0,0,8,0,21,49,10,1,0,65,0,144,145,62,0,0,5,24,4,11,4,0,2,21,27,159] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 25 - 2 - 4 - 129 - [0,0,8,0,21,49,10,1,0,65,0,144,145,62,0,0,5,24,4,11,4,0,2,21,27] - 159 +1ms
  zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - incomingMsg - {"groupid":0,"clusterid":8,"srcaddr":12565,"srcendpoint":10,"dstendpoint":1,"wasbroadcast":0,"linkquality":65,"securityuse":0,"timestamp":4100496,"transseqnumber":0,"len":5,"data":{"type":"Buffer","data":[24,4,11,4,0]}} +40ms
  zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":true,"reservedBits":0},"transactionSequenceNumber":4,"manufacturerCode":null,"commandIdentifier":11},"Payload":{"cmdId":4,"statusCode":0}},"address":12565,"endpoint":10,"linkquality":65,"groupID":0}' +98ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +5ms
  zigbee-herdsman:controller:endpoint Command 0x6666666666666666/10 lightingColorCtrl.enhancedMoveToHueAndSaturation({"transtime":4,"enhancehue":0,"saturation":252.08992,"direction":0}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) +90ms
  zigbee-herdsman:adapter:zStack:znp:SREQ --> AF - dataRequest - {"dstaddr":12565,"destendpoint":10,"srcendpoint":1,"clusterid":768,"transid":5,"options":0,"radius":30,"len":8,"data":{"type":"Buffer","data":[1,5,67,0,0,252,4,0]}} +90ms
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,18,36,1,21,49,10,1,0,3,5,0,30,8,1,5,67,0,0,252,4,0,183] +91ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,100,1,0,100] +25ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,100,1,0,100] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 4 - 1 - [0] - 100 +1ms
  zigbee-herdsman:adapter:zStack:znp:SRSP <-- AF - dataRequest - {"status":0} +73ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,68,128,0,1,5,195] +6ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,68,128,0,1,5,195] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 4 - 128 - [0,1,5] - 195 +1ms
  zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - dataConfirm - {"status":0,"endpoint":1,"transid":5} +40ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,25,68,129,0,0,0,3,21,49,10,1,0,63,0,177,146,62,0,0,5,24,5,11,67,129,2,21,27,15] +50ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,25,68,129,0,0,0,3,21,49,10,1,0,63,0,177,146,62,0,0,5,24,5,11,67,129,2,21,27,15] +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 25 - 2 - 4 - 129 - [0,0,0,3,21,49,10,1,0,63,0,177,146,62,0,0,5,24,5,11,67,129,2,21,27] - 15 +1ms
  zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - incomingMsg - {"groupid":0,"clusterid":768,"srcaddr":12565,"srcendpoint":10,"dstendpoint":1,"wasbroadcast":0,"linkquality":63,"securityuse":0,"timestamp":4100785,"transseqnumber":0,"len":5,"data":{"type":"Buffer","data":[24,5,11,67,129]}} +53ms
  zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":true,"reservedBits":0},"transactionSequenceNumber":5,"manufacturerCode":null,"commandIdentifier":11},"Payload":{"cmdId":67,"statusCode":129}},"address":12565,"endpoint":10,"linkquality":63,"groupID":0}' +96ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +8ms
`

**Comment by Koenkk** [comment]
You are controlling endpoint 10 (white), what MQTT command do you use? It should be e.g. `zigbee2mqtt/0x6666666666666666/rgb/set` `{"state": "ON"}`.

**Comment by andreasbrett** [comment]
Ah I see, I will have to send to the specific endpoint as a sub-topic in MQTT? That must have changed "recently". Previously I sent like this:

`zigbee2mqtt/0x66../set` with message `{"state": "ON", "color": {"hsb": "220,80,90"}}

I just tried by providing the rgb endpoint as sub-topic and it worked. Thanks @Koenkk, feeling a bit stupid right now... All my other colored lights use a single endpoint and although I knew my GLEDOPTO had 2 endpoints it did not click...
