### ISSUE TITLE
Ikea Fyrtur blinds position inverted

### ISSUE THREAD

**Issue by dietah** [Koenkk/zigbee-herdsman-converters#1447]
Hi,

I've been using the Fyrtur blinds for a while an initially I noticed that the position was reversed and didn't think much of it, so I just programmed my own logic in openHAB without defining it as a "Rollershutter".

Then I noticed a similar issue here [#1021](https://github.com/Koenkk/zigbee-herdsman-converters/issues/1021)

The Fyrtur blinds are closed (down) at 0 and open (up) at 100, while openHAB and Google Assistant expects open at 0 and closed at 100.

I also noticed that the device actually reports the correct values but zigbee2mqtt is inverting the position.
```
zigbee2mqtt:debug 2020-08-01 12:04:17: Received Zigbee message from 'tradfri_fyrtur_bedroom', type 'attributeReport', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":2}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-08-01 12:04:17: MQTT publish: topic 'zigbee2mqtt/tradfri_fyrtur_bedroom/update_available', payload 'false'
zigbee2mqtt:info  2020-08-01 12:04:17: MQTT publish: topic 'zigbee2mqtt/tradfri_fyrtur_bedroom/position', payload '98'
zigbee2mqtt:info  2020-08-01 12:04:17: MQTT publish: topic 'zigbee2mqtt/tradfri_fyrtur_bedroom/linkquality', payload '34'
zigbee2mqtt:info  2020-08-01 12:04:17: MQTT publish: topic 'zigbee2mqtt/tradfri_fyrtur_bedroom/battery', payload '89'
```

I was wondering if anybody else is working around the same issue and if this was deliberately inverted to begin with. 
Depending on the answer, can we invert the position in the converters? Or should I set an external converter in my configuration.yaml so it works for me? (I'm running everything inside docker, so custom code changes are a bit harder)

It would also help me getting rid of the icon in openHAB that is working in reverse 😇

Thanks!

**Comment by Koenkk** [comment]
I've added an `invert_cover` option, docs: https://github.com/Koenkk/zigbee2mqtt.io/blob/develop/docs/devices/E1757.md#device-type-specific-configuration

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by dietah** [comment]
Hi Koen,

I have tested this and can happily report it working 😄

Thanks for the quick action!

ps: I assumed wrong about Google Assistant, found in the documentation that openHAB converts this automatically to their standard when receiving the command
