### ISSUE TITLE
 Add another variant of Namron K8 switch

### ISSUE THREAD

**Issue by thomasja27** [Koenkk/zigbee-herdsman-converters#1452]
Hi, 
Have a Namron K8 switch that I see is supported allready, but the one I have has a different model id. When i add the model ID in devices.js it works perfect.

Model: 4512721, same switch as model: 4512703. Can you add it so it will be supported in next release?

    {
        zigbeeModel: ['4512721'],
        model: '4512721',
        vendor: 'Namron',
        description: 'Zigbee 4 channel switch K8',
        supports: 'action',
        fromZigbee: [
            fz.command_on, fz.command_off, fz.battery,
            fz.command_move, fz.command_stop,
        ],
        toZigbee: [],
        meta: {multiEndpoint: true},
        endpoint: (device) => {
            return {l1: 1, l2: 2, l3: 3, l4: 4};
        }
    },

**Comment by Koenkk** [comment]
Added, thanks!

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
