### ISSUE TITLE
Remote disarm of Xiaomi smoke detector

### ISSUE THREAD

**Issue by elfhack** [Koenkk/zigbee-herdsman-converters#1457]
I got myself one of these https://www.zigbee2mqtt.io/devices/JTYJ-GD-01LM_BW.html, and can't figure out the remote disarm command, if there is one. I looked around toZigbee.js and found nothing of the sort, then looked at other supported smoke detectors and found no commands as well. Is this not possible?

**Comment by Koenkk** [comment]
The easiest way to check if it's supported with the Xiaomi gateway.
