### ISSUE TITLE
Small syntax error

### ISSUE THREAD

**Issue by SymbolCsaba** [Koenkk/zigbee-herdsman-converters#1477]
Hello Koenkk!

I don't want to fork and pull request for a small mistakes. FromZigbee.js#line 453 the "&& model.meta.batery &&" should be "&& model.meta.bat**t**ery &&". (Find once in file, not a big problem)

**Comment by Koenkk** [comment]
Fixed by https://github.com/Koenkk/zigbee-herdsman-converters/pull/1478
