### ISSUE TITLE
Both Lonhonso and Lonsonho are used, but seem to be the same manufacturer?

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee-herdsman-converters#1485]
I was checking out the supported devices page and I noticed both:
- Lonsonho
- Lonhonso

Are listed, they look to be the same so I think one of them Lonhonso is probably a typo.
Also they all seem to be TuYa white label devices?

**Comment by Koenkk** [comment]
Fixed the typo, Lonsonho indeed use TuYa modules a lot, so most of them are marked as whitelabel.
