### ISSUE TITLE
Philips Hue Aurelle 3216131P6 not supported

### ISSUE THREAD

**Issue by cody82** [Koenkk/zigbee-herdsman-converters#1490]
I am getting the message that the 3216131P6 is not supported but the 3216131P5 is listed under supported devices.
Both models look the same, maybe the only difference is bluetooth support?
Maybe it is just missing in devices.js? I dont know how to add it on my local zigbee2mqtt installation.

**Comment by cody82** [comment]
I added this to devices.js and it works:

> {
        zigbeeModel: ['3216131P6'],
        model: '3216131P6',
        vendor: 'Philips',
        description: 'Hue white ambiance Aurelle square panel light',
        extend: hue.light_onoff_brightness_colortemp,
        ota: ota.zigbeeOTA,
    },

**Comment by Koenkk** [comment]
Added!
