### ISSUE TITLE
Converting zigbee illuminance value to lux

### ISSUE THREAD

**Issue by tcwj2008** [Koenkk/zigbee-herdsman-converters#1506]
According to[ Zigbee doc](https://zigbeealliance.org/wp-content/uploads/zip/zigbee-cluster-library.zip) (4.2.2.2.1) 
 > MeasuredValue = 10000 * LOG10( lx )+1

so  converting zigbee illuminance value to lux should be
> lx = 10^((MeasuredValue-1)/10000)

not 
lx = 10^(MeasuredValue/10000)-1

**Comment by Koenkk** [comment]
Fixed, thanks!

**Comment by Koenkk** [comment]
I'm wondering wether this calculation is correct, in case of `MeasuredValue` `0`, `1` is returned now (https://github.com/Koenkk/zigbee2mqtt/issues/4211)

Shouldn't it be `(Math.pow(10, illuminance) - 1) / 10000` ?

**Comment by sjorge** [comment]
Any consensus on this?

**Comment by Koenkk** [comment]
@tcwj2008 could you please check https://github.com/Koenkk/zigbee-herdsman-converters/issues/1506#issuecomment-683387479 , if I don't hear anything I assume `(Math.pow(10, illuminance) - 1) / 10000` is OK.

**Comment by Koenkk** [comment]
Reverted it back to the old calculation.

**Comment by presslab-us** [comment]
I believe the new calculation is correct, but there also needs to be a special case for 0.  The documentation states: ”0x0000 indicates a value of Illuminance that is too low to be measured." So if MeasuredValue == 0, then lx = 0. Otherwise use the new calculation.

**Comment by Koenkk** [comment]
@presslab-us good to know, I've added it know with a check on 0 value.
