### ISSUE TITLE
Please add Philips A21 B22 1600 lumen bulb

### ISSUE THREAD

**Issue by hughb8on** [Koenkk/zigbee-herdsman-converters#1521]
This bulb is the bayonet version of the already-supported LWA009

I've successfully tested this addition to devices.js : -

{
        zigbeeModel: ['LWA010'],
        model: '929002335001',
        vendor: 'Philips',
        description: 'Hue white A21 bulb B22 with Bluetooth (1600 Lumen)',
        extend: hue.light_onoff_brightness,
        ota: ota.zigbeeOTA,
    }

**Comment by Koenkk** [comment]
Added!
