### ISSUE TITLE
Add support for the "night mode" of the IKEA PIR sensor

### ISSUE THREAD

**Issue by oxivanisher** [Koenkk/zigbee-herdsman-converters#1528]
Since the original issue was stale and got closed, I am opening this one, as the problem is not yet fixed. Can I help with something here?
To paraphrase the original issue (#519) to my unserstanding:
The night mode is sent with an additional field called "ctrlbits" (see https://github.com/Koenkk/zigbee-herdsman-converters/issues/519#issuecomment-640246496). This is not being forwarded to MQTT as of now, so this feature is not working.

**Comment by Koenkk** [comment]
In `fromZigbee.js` change the following converter: 

```js
    tradfri_occupancy: {
        cluster: 'genOnOff',
        type: 'commandOnWithTimedOff',
        convert: (model, msg, publish, options, meta) => {
            const ctrlbits = msg.data.ctrlbits;
            const timeout = msg.data.ontime / 10;
            const deviceID = msg.device.ieeeAddr;

            // Stop existing timer because motion is detected and set a new one.
            if (store[deviceID]) {
                clearTimeout(store[deviceID]);
                store[deviceID] = null;
            }

            if (timeout !== 0) {
                store[deviceID] = setTimeout(() => {
                    publish({occupancy: false});
                    store[deviceID] = null;
                }, timeout * 1000);
            }

            return {occupancy: true, ctrlbits};
        },
    },
```

This sould expose the ctrlbits to MQTT, but we ofc want to translate this value to night/day, what values do you get for ctrlbits?

See https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html how to edit `fromZigbee.js`.

**Comment by oxivanisher** [comment]
I just did that, and got the same results as in comment https://github.com/Koenkk/zigbee-herdsman-converters/issues/519#issuecomment-640246496 (I only own the E1745):


Night mode, darkness:
Zigbee2MQTT:info  2020-09-04 19:58:17: MQTT publish: topic 'zigbee2mqtt/TradfriPIR_entrance', payload '{"battery":100,"ctrlbits":0,"linkquality":0,"occupancy":true,"requested_brightness_level":76,"requested_brightness_percent":30,"update_available":false}'

Day mode, darkness:
Zigbee2MQTT:info  2020-09-04 20:01:06: MQTT publish: topic 'zigbee2mqtt/TradfriPIR_entrance', payload '{"battery":100,"ctrlbits":0,"linkquality":0,"occupancy":true,"requested_brightness_level":76,"requested_brightness_percent":30,"update_available":false}'

Night mode, daylight:
Zigbee2MQTT:info  2020-09-04 20:05:21: MQTT publish: topic 'zigbee2mqtt/TradfriPIR_entrance', payload '{"battery":100,"ctrlbits":1,"linkquality":0,"occupancy":true,"requested_brightness_level":76,"requested_brightness_percent":30,"update_available":false}'

Day mode, daylight:
Zigbee2MQTT:info  2020-09-04 20:10:49: MQTT publish: topic 'zigbee2mqtt/TradfriPIR_entrance', payload '{"battery":100,"ctrlbits":0,"linkquality":0,"occupancy":true,"requested_brightness_level":76,"requested_brightness_percent":30,"update_available":false}'

So it seems that the logic would be: If `ctrlbits` is 1, ignore the `"occupancy":true`, since its only sent if night mode is enabled and its daylight.

**Comment by Koenkk** [comment]
> So it seems that the logic would be: If ctrlbits is 1, ignore the "occupancy":true, since its only sent if night mode is enabled and its daylight.

This indeed corresponds with the Zigbee documentation of this property:

![image](https://user-images.githubusercontent.com/2892853/92280008-c43f3c00-eef8-11ea-85b9-bff6a110294a.png)

So if I understand correctly:
- Night mode can be activated/deactivated by clicking a button on the back
- When night mode is enabled it will not turn on bulbs in daylight

> So it seems that the logic would be: If ctrlbits is 1, ignore the "occupancy":true, since its only sent if night mode is enabled and its daylight.

Implemented.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by oxivanisher** [comment]
> So if I understand correctly:
> 
> * Night mode can be activated/deactivated by clicking a button on the back
> * When night mode is enabled it will not turn on bulbs in daylight

Yes and yes. I will as soon as the container is available 👍 thanks!

**Comment by oxivanisher** [comment]
It seems to work 👍 

Sadly now I seem to have this issue https://github.com/Koenkk/zigbee2mqtt/issues/1961 but this has probably nothing to to with this here.
