### ISSUE TITLE
how to contribute converter changes for new devices

### ISSUE THREAD

**Issue by insipiens** [Koenkk/zigbee-herdsman-converters#1533]
Hi, I have a device (a Moes room thermostat) which now works on my own installation having added the changes to toZigbee.js and fromZigbee.js converters and devices,js.

However being new to using git hub I understand how to fork the environment but after that would like some guidance on how best to proceed. 

specifically, do you clone the dev converter fork to my local Z2M environment so I can develop and prove the device works before creating a pull request? 

I'm assuming there's a few different ways to do this so interested in best practice.

Thanks

Ins

**Comment by Koenkk** [comment]
You can either make a pull request yourself (https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) or post the changes here so I can add them.

**Comment by insipiens** [comment]
@Koenkk Much appreciated! 

I've attached my copies of the toZigbee.js/fromZigbee.js/devices.js (.txt extension to allow attachment)

The changes have bracketed comments:  
_//Add Moes Room Thermostat - start_
.......
_//Add Moes Room Thermostat - end_

There is one code insertion in devices.js and one in toZigbee.js, Two separate code insertions in fromZigbee.js

Also the addition to /lib/extension/homeassistant.js

`'BHT-002-GCLZB': [cfg.lock_child_lock, climate(5, 30, 'current_heating_setpoint', 1)],`

Many thanks!

[toZigbee.txt](https://github.com/Koenkk/zigbee-herdsman-converters/files/5180201/toZigbee.txt)
[fromZigbee.txt](https://github.com/Koenkk/zigbee-herdsman-converters/files/5180202/fromZigbee.txt)
[devices.txt](https://github.com/Koenkk/zigbee-herdsman-converters/files/5180203/devices.txt)


Link to related ticket for device: [(https://github.com/Koenkk/zigbee2mqtt/issues/4185#issue-685914463)]

**Comment by Koenkk** [comment]
Done!
