### ISSUE TITLE
New Device Support(TS0601 Zemismart model: 'M515EGB' Curtain motor)

### ISSUE THREAD

**Issue by Krolik1988** [Koenkk/zigbee-herdsman-converters#1536]
Hello, got new [roller curtains motor](https://www.aliexpress.com/item/4001343586623.html?spm=a2g0s.9042311.0.0.1e144c4dDR6xFX), and triying to add it to your plug-in.  Please check if everything is correct(I think not) and please add support. It look likes motor it self are RF, but then it have USB stick Zigbee  Router(I think)

`{"id":6,"type":"Router","ieeeAddr":"0x842e14fffefec07d","nwkAddr":51870,"manufId":4098,"manufName":"_TZE200_xuzcvlku","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0601","manufacturerName":"_TZE200_xuzcvlku","powerSource":1,"zclVersion":3,"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[]}},"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1599402930812}
`

```
"friendly_name":"0x842e14fffefec07d"
"type":"devices"
"modelId":"TS0601"
"manufacturerName":"_TZE200_xuzcvlku"
"powerSource":1
"zclVersion":3
"appVersion":68
"stackVersion":0
"hwVersion":1
"dateCode":""
data '{}'

"manufacturerID":4098
"manufacturerName":"_TZE200_xuzcvlku"
"model":"TS0601"
"modelID":"TS0601"
"powerSource":"Mains (single phase)"
"type":"Router"
"vendor":"-"
"type":"devices"

Cluster 'genTime', data '["localTime"]' 
 type 'raw'
cluster 'manuSpecificTuyaDimmer'
data '{"data":[25,4,36,0,6]
"type":"Buffer"}
```

What I did:

Added 'raw' to fromZigbee.js:
```
tuya_curtain: { 
 type: ['commandSetDataResponse', 'commandGetData', 'raw'],    #<raw

```
changed section devices.js:
```
 {
        zigbeeModel: ['owvfni3\u0000', 'owvfni3', 'aabybja'],  **#<<< Not suere if I need to add here some thing.**
        fingerprint: [{modelID: 'TS0601', manufacturerName: '_TZE200_5zbp6j0u'}
                            {modelID: 'TS0601', manufacturerName: '_TZE200_xuzcvlku'}, **# <<< THIS ONE.**
],
        model: 'TS0601_curtain',
        vendor: 'TuYa',
        description: 'Curtain motor',
        whiteLabel: [
            {vendor: 'Yushun', model: 'YS-MT750'},
            {vendor: 'Zemismart', model: 'ZM79E-DT'},
            {vendor: 'Zemismart', model: 'M515EGB'}, **# <<< THIS ONE.**
            {vendor: 'Binthen', model: 'BCM100D'},
        ],
        supports: 'open, close, stop, position',
        fromZigbee: [fz.tuya_curtain, fz.ignore_basic_report],
        toZigbee: [tz.tuya_curtain_control, tz.tuya_curtain_options],
    },


```
Probably, it's pairs successfully but I have MSG:
`owvfni3: Unhandled DP #undefined: {"type":"Buffer","data":[25,81,36,0,72]}`

Then I think I miss something in fromZigbee.js.

![20200904_165939](https://user-images.githubusercontent.com/52775223/92328669-a68de600-f062-11ea-8c41-06acf3c49bbc.jpg)
Looks like it works. Added to domoticz as well. But would be nice if you will check everything

**Comment by Koenkk** [comment]
Added, please check if it works.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by Krolik1988** [comment]
Hi Koenkk, I'm sorry about I'm messing here, but I commented my closed [case](https://github.com/Koenkk/zigbee-herdsman-converters/issues/1436). Do I need to open new one, or it's ok?

**Comment by Krolik1988** [comment]
> 
> 
> Added, please check if it works.
> 
> Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

Hi, everything works. Thanks you very much.

**Comment by Krolik1988** [comment]
No converter available for 'TS0601_curtain' with cluster 'manuSpecificTuyaDimmer' and type 'raw' and data '{"data":[25,116,36,0,75],"type":"Buffer"}'

**Comment by Krolik1988** [comment]
look likes work.

**Comment by aleksandrdobrynin** [comment]
I got such a motor, added it, but from the states I only get the signal level. How do you get the rest of the parameters? Current position of the shade, battery status?

And how to send a value to the set topic for which the curtain should be opened / closed? Tried it like this:
zigbee2mqtt / bedroom_curtain / set
{
"position": 50
}
The motor starts spinning indefinitely.

**Comment by Krolik1988** [comment]
> I got such a motor, added it, but from the states I only get the signal level. How do you get the rest of the parameters? Current position of the shade, battery status?
> 
> And how to send a value to the set topic for which the curtain should be opened / closed? Tried it like this:
> zigbee2mqtt / bedroom_curtain / set
> {
> "position": 50
> }
> The motor starts spinning indefinitely.

Hi, motor(mine) it self are rf based and are controlled by rf remote or by zigbee2rf bridge  converter what was included, and rf converter are connected to z2m and dz, not motor it self. You will not get bbu level  or actual hight. You can have only linq and dimmer who are provided by rf bridge(let call this dongl). With dimmer in dz you can set necessary high if you are codded motor top and buttom positions but you will not have any respons from motor with actual information. Check mqtt2zigbee msgs from this zb converter and check if everything is ok. If there are some errors, probably must be added 2 z2m plugin, and after this to dz. But unfortunately you do not provide any information.  Goodluck.
Kind regards,
Aleksejs.

**Comment by Stetocasa** [comment]
@robertalexa
