### ISSUE TITLE
TS0207 its not a water leakage sensor

### ISSUE THREAD

**Issue by arteck** [Koenkk/zigbee-herdsman-converters#1540]
the TS0207 is a repeater RP280 but in converter is it under water leakage sensor listed

https://de.aliexpress.com/item/4001276417072.html?spm=a2g0s.9042311.0.0.27424c4ds4GGDH

https://github.com/Koenkk/zigbee-herdsman-converters/blob/a2d3c9e1ffaa2a1a61a988f01e5e9c906e5d1572/devices.js#L11207

**Comment by Koenkk** [comment]
Seems that multiple devices use `TS0207` as the model (I'm sure TS0207 is also a water leakage sensor because I added this device myself). Please support this new device through a fingerprint: https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L11305

**Comment by 9Mad-Max5** [comment]
ok it just haves a manuf id:4098
