### ISSUE TITLE
Transition time leads to incorrect state info 

### ISSUE THREAD

**Issue by d-EScape** [Koenkk/zigbee-herdsman-converters#155]
After publishing a command to change color on a Philips Hue bulb with a transition time the bulb(?) or zigbee2mqtt(?) will quickly respond with the new settings. However the values represent the color at that exact moment during the transition, not the color after the full transition.
I suspect this is the behavior of the hue bulb, but I'm not sure. Is there any way to force/tickle/persuade the bulb or zigbee2mqtt to publish the correct values after the transition?
Otherwise the home automation software will keep thinking the color is somewhere between the old and the desired value.

Not sure if this is an issue for zigbee2mqtt, shepherd or shepherd-converters. Apologies if this is not the right place.

**Comment by Koenkk** [comment]
It's an zigbee2mqtt issue. 

A fix is available in the dev branch, at the end of the transition, zigbee2mqtt will refresh the state.

Can you verify this?

**Comment by d-EScape** [comment]
Good stuff! Seems te work in de dev branch. Not 100% reliable while testing, but I'll keep an eye on it and report back if more failures occur and I can make sense of them.
