### ISSUE TITLE
Request to add new device

### ISSUE THREAD

**Issue by jonasknoergaard** [Koenkk/zigbee-herdsman-converters#1563]
I have a dimmer I would like to add. 
It is an Envilar - ZG102-BOX- UNIDIM. It appears to be a rebranding of a Sunricher - ZG9101SAC-HP. I have it working by adding the the following to devices.js (It is just a copy of the Sunricher entry and I don't quite understand it, but it works).

	{
		zigbeeModel: ['ZG102-BOX-UNIDIM'],
        model: 'ZG102-BOX-UNIDIM',
        vendor: 'Envilar',
        description: 'ZigBee AC phase-cut dimmer',
        extend: generic.light_onoff_brightness,
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            await bind(endpoint, coordinatorEndpoint, ['genOnOff', 'genLevelCtrl']);
            await configureReporting.onOff(endpoint);
        },
	}

I'm not sure how to proceed from here.

Thanks
Jonas

**Comment by Koenkk** [comment]
Added, thanks!

Changes will be available in the latest dev branch tomorrow (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by jonasknoergaard** [comment]
Thanks for the quick action

I 'm sorry to reopen this, and I'm not entirely sure this is the right place, but things are not working 100% yet. Zigbee2mqtt recognizes the devices, but when zigbee2mqtt connects to home assistant it is not announced, it works fine when I add it in the home assistant configuration.yaml
I run hassio so if the issue is related to the addon I am sorry for posting in the wrong place.

Thanks
Jonas

**Comment by Koenkk** [comment]
Are you on the latest edge addon?

**Comment by jonasknoergaard** [comment]
No I am still in stable I have just used the devices.js. I haven't change to edge because I am worried that it might mess up pairings (I have a few rather inaccessible), but if it doesn't I will change and test right away.

**Comment by Koenkk** [comment]
You need to be to have home assistant discovery for that device or you can wait for the next z2m release on 1 october.
