### ISSUE TITLE
Request to add Phillips Hue Centris fixture

### ISSUE THREAD

**Issue by TheGreyDiamond** [Koenkk/zigbee-herdsman-converters#1573]
Please add the Phillips Hue Centris fixture (in the 4-spot variant). I would do it myself, but the docs on adding a light are not very good and I'm a noob in that area. I do not have the light just yet, but it will be delivered to me soon. Any help is appreciated.
(Product link: https://www.philips-hue.com/de-de/p/hue-white---color-ambiance-centris-4er-deckenspot/5060730P7 )

**Comment by Koenkk** [comment]
Once you receive it, pair it to Zigbee2MQTT and provide the logging of this.

Also what does this bulb support: color? color_temperature? both?

**Comment by TheGreyDiamond** [comment]
I will surely do! I think all of the parts are "Hue White Color Ambiance" so, both.

**Comment by TheGreyDiamond** [comment]
They updated the shipping day and moved it to the middle of November. This will take some time.

**Comment by TheGreyDiamond** [comment]
@Koenkk Please remove the stale lable, cause its still a thing. The shipping has been moved (again)

**Comment by Koenkk** [comment]
@TheGreyDiamond stale label is automatically removed once you comment

**Comment by TheGreyDiamond** [comment]
Okay, weird because its still visible for me.

**Comment by Koenkk** [comment]
@TheGreyDiamond it will do it at 12:00

**Comment by TheGreyDiamond** [comment]
Hmm still stale.... Sorry to annoy you. I finally got shipping information, so it should arrive soon.

**Comment by copystring** [comment]
I have got this. Added support in devices.js and works just fine.

Not sure how to create a PR... my fork is not up to date and not sure how to update. Is it OK if I post my changes here?

**Comment by copystring** [comment]
OK. Not sure if the way I did it is OK. Tried to merge upstream branch to mine. Did not work 100% but in the end only devices.js is modified. Hope this is ok like this. Not used to git/github. Let me know.

**Comment by TheGreyDiamond** [comment]
I also got the lamp now and it just joined as a hue bulbish device, so....
