### ISSUE TITLE
Possibly duplicate modelID. Need advice

### ISSUE THREAD

**Issue by blakadder** [Koenkk/zigbee-herdsman-converters#1579]
I have a TS0043 device [LoraTap remote](https://www.loratap.com/products/tuya-smart-life-zigbee-smart-home-wireless-switch-3-gangs-remote-tuya-zigbee-hub-required-no-limit-to-control-home-device) which has same functions as the existing TS0043 wireless switches but the actions are reported as left, middle and right which does not really apply in this case. 

![image](https://user-images.githubusercontent.com/5904370/93797541-a97cff00-fc3c-11ea-9c17-d6626af9a096.png)

I couldn't find the manufacturer for the Smart9 and Lonsonho wireless switch to compare. This device is `_TZ3000_bi6lpsew`

Would this warrant a new device with fingerprint to report different actions or is that stretching it too far?

**Comment by Koenkk** [comment]
I propose to:
- add device as a whitelabel here: https://github.com/Koenkk/zigbee-herdsman-converters/blob/55bd00ee1f162d4125cbe0234a340a0236ccb583/devices.js#L1316
- Change https://github.com/Koenkk/zigbee-herdsman-converters/blob/55bd00ee1f162d4125cbe0234a340a0236ccb583/converters/fromZigbee.js#L3639 to 

```js
            if (model.model === 'TS0042') buttonMapping = {1: 'left', 2: 'right'};
            else if (model.model === 'TS0043' && msg.device.manufacturerName === '_TZ3000_bi6lpsew') buttonMapping = {1: '1', 2: '2', 3: '3'};
            else if (model.model === 'TS0043') buttonMapping = {1: 'right', 2: 'middle', 3: 'left'};
```
