### ISSUE TITLE
Request to add Danfoss icon floor heating system

### ISSUE THREAD

**Issue by mihail4anov** [Koenkk/zigbee-herdsman-converters#1589]
I would like to ask somebody to add the Danfoss icon floor heating system to Z2M please.
I am not a programmer, and I cant do it myself.

This is the link to [API](https://drive.google.com/file/d/1n5MqOSaBiPYZAXqRsyglrGSwGzOSjZUA/view?usp=sharing) which I received from Danfoss.

**Comment by mihail4anov** [comment]
Anyone is interested in this?

**Comment by TLongstride** [comment]
Hey,
Did you had a answer for this problem ? 
Have you find a solution to integrate the controler since you post this requet ? 
I'm intresseted if you have find how to controle it from Hassio.
Thanks

**Comment by mihail4anov** [comment]
> Hey,
> Did you had a answer for this problem ?
> Have you find a solution to integrate the controler since you post this requet ?
> I'm intresseted if you have find how to controle it from Hassio.
> Thanks

Check out [this](https://community.home-assistant.io/t/floor-heating-danfoss-icon-system/96383/12?u=mihail4anov)
