### ISSUE TITLE
EMIZB-132 divisor on current wrong.

### ISSUE THREAD

**Issue by toremick** [Koenkk/zigbee-herdsman-converters#1591]
The divisor on current is now wrong on my device. This worked nice before, not sure when it happend.

The current values should have been divided by 100 as they are shown.

database.db:
`{"id":12,"type":"EndDevice","ieeeAddr":"0x0015bc001b02508c","nwkAddr":48641,"manufId":4117,"manufName":"Develco Products A/S","powerSource":"DC Source","modelId":"EMIZB-132","epList":[1,2],"endpoints":{"1":{"profId":49353,"epId":1,"devId":1,"inClusterList":[3,5,6],"outClusterList":[],"clusters":{},"binds":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":83,"inClusterList":[0,3,32,1794,1796,2820],"outClusterList":[3,10,25],"clusters":{"genBasic":{"attributes":{"modelId":"EMIZB-132","manufacturerName":"Develco Products A/S","powerSource":4,"zclVersion":1,"dateCode":"2019-07-11 14:40"}},"haElectricalMeasurement":{"attributes":{"rmsVoltage":2383,"rmsCurrent":11278,"rmsVoltagePhB":0,"rmsCurrentPhB":11845,"rmsVoltagePhC":2385,"rmsCurrentPhC":2011,"acVoltageMultiplier":1,"acVoltageDivisor":10,"acCurrentMultiplier":1,"acCurrentDivisor":10}},"seMetering":{"attributes":{"currentSummDelivered":[0,38860694],"currentSummReceived":[0,0],"instantaneousDemand":3095,"status":0,"multiplier":1,"divisor":1000}}},"binds":[{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00124b001ca14e07","endpointID":1},{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x00124b001ca14e07","endpointID":1}],"meta":{}}},"dateCode":"2019-07-11 14:40","zclVersion":1,"interviewCompleted":true,"meta":{"configured":9},"lastSeen":1601068589570}
`

log:
`debug 2020-09-25 21:23:59: Received Zigbee message from '0x0015bc001b02508c', type 'attributeReport', cluster 'seMetering', data '{"currentSummDelivered":[0,38860694],"currentSummReceived":[0,0],"instantaneousDemand":3236,"status":0}' from endpoint 2 with groupID 0
info  2020-09-25 21:23:59: MQTT publish: topic 'zigbee2mqtt/0x0015bc001b02508c', payload '{"current":1167.9,"current_phase_b":1234.4,"current_phase_c":217.6,"energy":38860.69,"interface_mode":"kaifa_and_kamstrup","linkquality":90,"power":3236,"voltage":237.8,"voltage_phase_b":0,"voltage_phase_c":238.4}'
debug 2020-09-25 21:24:01: Received Zigbee message from '0x0015bc001b02508c', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"rmsCurrent":11659,"rmsCurrentPhB":12339,"rmsCurrentPhC":2190,"rmsVoltage":2379,"rmsVoltagePhB":0,"rmsVoltagePhC":2384}' from endpoint 2 with groupID 0
info  2020-09-25 21:24:01: MQTT publish: topic 'zigbee2mqtt/0x0015bc001b02508c', payload '{"current":1165.9,"current_phase_b":1233.9,"current_phase_c":219,"energy":38860.69,"interface_mode":"kaifa_and_kamstrup","linkquality":90,"power":3236,"voltage":237.9,"voltage_phase_b":0,"voltage_phase_c":238.4}'
debug 2020-09-25 21:24:05: Received Zigbee message from '0x0015bc001b02508c', type 'attributeReport', cluster 'seMetering', data '{"currentSummDelivered":[0,38860694],"currentSummReceived":[0,0],"instantaneousDemand":3237,"status":0}' from endpoint 2 with groupID 0
`

zigbee2mqtt version:
`Zigbee2MQTT version 1.14.4-dev (commit #49e6211)`

bridge version:
`{"commit":"49e6211","coordinator":{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20200328,"transportrev":2},"type":"zStack3x0"},"log_level":"debug","network":{"channel":20,"extendedPanID":"0xdddddddddddddddd","panID":6741},"permit_join":false,"version":"1.14.4-dev"}`

**Comment by Koenkk** [comment]
Which mode do you use https://github.com/Koenkk/zigbee-herdsman-converters/pull/1091/files#diff-3e0c275bd41af699153bf59d8dda4a2aR1939? If you adjust the vaules in that table and set the `interface_mode` again it should work.

**Comment by toremick** [comment]
> Which mode do you use https://github.com/Koenkk/zigbee-herdsman-converters/pull/1091/files#diff-3e0c275bd41af699153bf59d8dda4a2aR1939? If you adjust the vaules in that table and set the `interface_mode` again it should work.

Setting the inferface_mode again helped, sorry for the trouble!
