### ISSUE TITLE
respond to local time attribute request command

### ISSUE THREAD

**Issue by insipiens** [Koenkk/zigbee-herdsman-converters#1597]
I'm working on improving a device converters for Moes room thermostat

One of the issues is the thermostat doesn't keep good time, an issue when it uses the program setting.

I see it updates using the zigbee cluster library frame command with attribute 0x0007 request local time

Is this possible to use, and how to respond to the device's request?

![image](https://user-images.githubusercontent.com/68975498/94368134-99e93480-00da-11eb-9643-931fcac9b8a5.png)

**Comment by Koenkk** [comment]
This should already be done for all devices here: https://github.com/Koenkk/zigbee-herdsman/blob/master/src/controller/model/device.ts#L174

**Comment by insipiens** [comment]
I see, wonder why that isn't functioning in this case? 

I'll sniff the Z2M traffic and verify.

**Comment by insipiens** [comment]
Wow, seems to be working fine....let me check with someone else testing the same device and had same problem.

If fine I'll close the issue shortly.

Cheers

**Comment by insipiens** [comment]
Closed. Everything works fine
