### ISSUE TITLE
fromZigbee&toZigbee converter

### ISSUE THREAD

**Issue by unpack8866** [Koenkk/zigbee-herdsman-converters#1605]
Zigbee2mqtt version: 1.14.4.2 

![14](https://user-images.githubusercontent.com/40196105/94560719-9a79fa80-0295-11eb-8029-4639e519016b.png)

![13](https://user-images.githubusercontent.com/40196105/94560724-9ea61800-0295-11eb-8f9c-6639d631a7aa.png)

![15](https://user-images.githubusercontent.com/40196105/94560881-d1501080-0295-11eb-9d96-4cff1bf4466e.png)

I want to add  converter files fromZigbee; to facilitate the change, but zigbee2mqtt fails to start

**Comment by lovelylain** [comment]
try below:
```
module.paths.push(require.main.path+ '/node_modules') //sovle Cannot find module 'zigbee-herdsman-converters'

const zc = require('zigbee-herdsman-converters')
const fz = zc.fromZigbeeConverters
const tz = zc.toZigbeeConverters
```
