### ISSUE TITLE
Request to add Xiaomi Aqara US Single Switch Neutral Required

### ISSUE THREAD

**Issue by timothyzalusky** [Koenkk/zigbee-herdsman-converters#1610]
Hi,
This device is just about the same as the others so I think this is everything needed: (model was from package)
![WS-USC03](https://user-images.githubusercontent.com/72116704/94638007-99999680-029e-11eb-8922-2fa58307ed3e.jpg)

    {
        zigbeeModel: ['lumi.switch.b1naus01'],
        model: 'WS-USC03',
        vendor: 'Xiaomi',
        description: 'Aqara smart wall switch (neutral, single rocker)',
        supports: 'on/off',
        fromZigbee: [fz.on_off],
        toZigbee: [tz.on_off],
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            await bind(endpoint, coordinatorEndpoint, ['genOnOff']);
            await configureReporting.onOff(endpoint);
        },
    },

**Comment by Koenkk** [comment]
added, thanks!
