### ISSUE TITLE
Issues adding new device

### ISSUE THREAD

**Issue by atxbyea** [Koenkk/zigbee-herdsman-converters#1615]
## What happened

Tried adding support for a new device, however it complains about converters

## What did you expect to happen
ON \ Off works fine, but can't get 

## How to reproduce it (minimal and precise)
Trying to toggle brightness \ color \ temp, but nothing works, got On \ off to work but unsure how to proceed
Tried using extend with generic and hue light, no go.

homeassistant.js:
`    '3802964': [cfg.light_brightness_colortemp_colorxy],`

devices.js:
`   {
        zigbeeModel: ['3802964'],
        model: '3802964',
        vendor: 'Namron',
        description: 'LED 5,3W CCT E14',
        supports: 'on/off, brightness, color temperature, color',
        fromZigbee: [],
        toZigbee: [tz.on_off],
    },
`

Error produced with nothing more configured gives me :

` No converter available for 'color_temp' (373)` 

If I try adding zome toZigbee for brightness and color temp it just gives me 
`Zigbee2MQTT:error 2020-10-01 11:25:43: Failed to call 'EntityPublish' 'onMQTTMessage' (TypeError: Cannot read property 'key' of undefined
    at /app/lib/extension/publish.js:198:56
    at Array.find (<anonymous>)
    at EntityPublish.onMQTTMessage (/app/lib/extension/publish.js:198:42)
    at Controller.callExtensionMethod (/app/lib/controller.js:371:44)
    at Controller.onMQTTMessage (/app/lib/controller.js:268:14)
    at MQTT.emit (events.js:315:20)
    at MQTT.onMessage (/app/lib/mqtt.js:94:14)
    at MqttClient.emit (events.js:315:20)
    at MqttClient._handlePublish (/app/node_modules/mqtt/lib/client.js:1271:12)
    at MqttClient._handlePacket (/app/node_modules/mqtt/lib/client.js:410:12))`

**Comment by Koenkk** [comment]
Does this bulb only support color temperature or also colors (e.g. green, red..)?

**Comment by atxbyea** [comment]
I'm not 100% sure @Koenkk as I haven't been able to control anything else than on off yet, but I'm pretty sure it is only CT

**Comment by Koenkk** [comment]
Good, added!

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by atxbyea** [comment]
Still same with latest dev branch @Koenkk

**Comment by Koenkk** [comment]
Make sure to discard any manual changes to `devices.js`. (e.g. for hassio remove `zigbee_shepherd_devices`).
