### ISSUE TITLE
aqara QBKG26LM power measurement support

### ISSUE THREAD

**Issue by lovelylain** [Koenkk/zigbee-herdsman-converters#1616]
I tried the latest QBKG26LM configuration, it has support onOff action and report, can someone support the power measurement report?

**Comment by Koenkk** [comment]
@sloopee @lovelylain do you see any `No converter available...` message from this device when debug logging is enabled and attaching a load to the switch?

To enable debug logging set in `configuration.yaml`:
```yaml
advanced:
  log_level: debug
```

**Comment by sloopee** [comment]
debug log level already set up, no "no converter available...." seen. I guess it thinks it has the right "drivers" for it since it found a match but the code written for the switch currently doesn't have power measurement in it. I saw you write the following lines for this exact switch on another thread previously and the feedback was that it worked well. I'm trying to put the exact code into the "devices.js" file to see if it will work however i can't find the devices.js file.

{
    zigbeeModel: ['lumi.switch.n3acn3'],
    model: 'QBKG26LM',
    vendor: 'Xiaomi',
    description: 'Aqara D1 3 gang smart wall switch (with neutral wire)',
    supports: 'on/off, power measurement',
    fromZigbee: [fz.on_off, fz.xiaomi_power],
    toZigbee: [tz.on_off],
    meta: {multiEndpoint: true},
    endpoint: (device) => {
        return {'left': 1, 'center': 2, 'right': 3, 'system': 1};
    },
    onEvent: xiaomi.prevent_reset,
},

**Comment by lovelylain** [comment]
@sloopee you should try the latest z2m version, which has merged PR #1525 , it has support on/off send and receive.
@Koenkk There is no zigbee msg received after pairing succeed. The on/off event of physical buttons are solved with `bind`, i don't know if power measurement can solve with bind too, I tried bind genAnalogInput but not working.

**Comment by sloopee** [comment]
I'm already on the latest z2m version and like you said it only supports on.off without power.

**Comment by Koenkk** [comment]
Does this device supports powers measurements when paired with the original Xiaomi gateway?

**Comment by sloopee** [comment]
yep it does, all the aqara D1 with neutral switches can support power measurement as well.

**Comment by Koenkk** [comment]
@zhongfu could you maybe help with this? (do you have any D1 with neutral switch?)

**Comment by zhongfu** [comment]
> @zhongfu could you maybe help with this? (do you have any D1 with neutral switch?)

I don't have any Aqara neutral switches, unfortunately :/

It sounds like the power measurements might need to be polled for or maybe enabled, so perhaps somebody with one of these switches, a Xiaomi/Aqara gateway, and a CC2531 could try sniffing the traffic between the gateway and switches?

**Comment by lovelylain** [comment]
@hoangphison could you help on this request?
