### ISSUE TITLE
Request to add new model of TuYa thermostat 

### ISSUE THREAD

**Issue by skumka** [Koenkk/zigbee-herdsman-converters#1621]
Dear Community,

I am looking for your help. I am new to Home Assistant. Just about 2 months of experience, but learning fast.
I have an issue with adding new device to zigbee2mqtt. I have bought TuYa TRV 
( https://www.made-in-china.com/showroom/misslinda821/product-detailINumhMclhRVL/China-Saswell-Tuya-Smart-Zigbee-Trv-Amazon-Alexa-and-Google-Assistance-Voice-Control-Available-Room-Thermostat.html ) which is not supported to date.
I am trying to follow documentation about adding new devices, but it seems not to work for me.

What I did?

So I set up debug logs in zigbee2mqtt configuration:
advanced:
  log_level: debug

I have put it also in zigbee2mqtt configuration (~/share/zigbee2mqtt/ folder/configuration.yaml)
zigbee_shepherd_devices: true
 
since I am trying to use sheppard mode :

I have the newest zigbee2mqtt installed so I have copied https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js from master branch into my ~/share/zigbee2mqtt/ folder

Since I think this new TRV is mostlikely the evolution of TuYa TS0601_thermostat I have added following rows to my local devices.js ( in ~/share/zigbee2mqtt/ folder).

This is what I put there (I copied it from other similat model:zigbeeModel: ['kud7u2l'],:

{
zigbeeModel: ['88teujp'],
fingerprint: [{ modelID: 'TS0601', manufacturerName: '_TTYST11_c88teujp' }],
model: 'TS0601_thermostat',
vendor: 'TuYa',
description: 'Radiator valve with thermostat',
supports: 'thermostat, temperature',
whiteLabel: [
{ vendor: 'Moes', model: 'HY369RT' },
{ vendor: 'SHOJZJ', model: '378RT' },
],
meta: { tuyaThermostatSystemMode: common.TuyaThermostatSystemModes, tuyaThermostatPreset: common.TuyaThermostatPresets },
fromZigbee: [fz.tuya_thermostat, fz.tuya_thermostat_on_set_data, fz.ignore_basic_report],
toZigbee: [
tz.tuya_thermostat_child_lock, tz.tuya_thermostat_window_detection, tz.tuya_thermostat_valve_detection,
tz.tuya_thermostat_current_heating_setpoint, tz.tuya_thermostat_system_mode, tz.tuya_thermostat_auto_lock,
tz.tuya_thermostat_calibration, tz.tuya_thermostat_min_temp, tz.tuya_thermostat_max_temp,
tz.tuya_thermostat_boost_time, tz.tuya_thermostat_comfort_temp, tz.tuya_thermostat_eco_temp,
tz.tuya_thermostat_force, tz.tuya_thermostat_preset,
],
toZigbee: [
tz.tuya_thermostat_child_lock, tz.tuya_thermostat_window_detection, tz.tuya_thermostat_valve_detection,
tz.tuya_thermostat_current_heating_setpoint, tz.tuya_thermostat_system_mode, tz.tuya_thermostat_auto_lock,
tz.tuya_thermostat_calibration, tz.tuya_thermostat_min_temp, tz.tuya_thermostat_max_temp,
tz.tuya_thermostat_boost_time, tz.tuya_thermostat_comfort_temp, tz.tuya_thermostat_eco_temp,
tz.tuya_thermostat_force, tz.tuya_thermostat_preset,
],
},

Unfortunately it does not work. I do not see any difference in the zigbee2mqtt logs……

Please help. 

I would like also to ask for a help with adding support for this device officially in add-on.

I am happy to make a pull request if all works for me and create a documentation for it.

Thank you in advance.

Here is my log.
Device ID is 0x60a423fffe8cf958

https://pastebin.pl/view/fa1e35d9

**Comment by insipiens** [comment]
`debug 2020-10-03 10:36:56: Received Zigbee message from '0x60a423fffe8cf958', type 'commandGetData', cluster 'manuSpecificTuyaDimmer', data '{"data":{"data":[0],"type":"Buffer"},"dp":357,"fn":0,"status":0,"transid":1}' from endpoint 1 with groupID 0
debug 2020-10-03 10:36:56: Skipping message, definition is undefined and still interviewing
debug 2020-10-03 10:36:58: Received Zigbee message from '0x60a423fffe8cf958', type 'commandGetData', cluster 'manuSpecificTuyaDimmer', data '{"data":{"data":[1],"type":"Buffer"},"dp":266,"fn":0,"status":0,"transid":23}' from endpoint 1 with groupID 0`

Looks like different DP commands, certainly don't recognise those for the TuYa TRV, but it does seem to be a Tuya device.

You might tail your log with `|grep 0x60a423fffe8cf958` on the end so you just see the messages for this device.

Note the DP number and whether they correlate with what you are changing on the device.

Ideally you'd want to sniff the traffic but you can probably get most of a workable conversion set by noting down action/DP as it might just be a case of copying the existing converter clauses and amending them.

**Comment by insipiens** [comment]
Also can you post the entry for this device from the ./data/database.db file ?

**Comment by skumka** [comment]
I managed to make a basic discovery. Thanks for help @insipiens. Will place feature request for extensions.
