### ISSUE TITLE
IM6001-WLP01 (SmartThings water leak sensor) seems to need another converter

### ISSUE THREAD

**Issue by skandragon** [Koenkk/zigbee-herdsman-converters#1622]
```
Zigbee2MQTT:debug 2020-10-02 18:12:05: Received Zigbee message from '0x286d970001037a4d', type 'attributeReport', cluster 'ssIasZone', data '{"zoneStatus":32}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2020-10-02 18:12:05: No converter available for 'IM6001-WLP01' with cluster 'ssIasZone' and type 'attributeReport' and data '{"zoneStatus":32}'
Zigbee2MQTT:debug 2020-10-02 18:12:16: Device '0x286d970001037a4d' announced itself
```

I suspect this is why it also announces itself constantly, at the rate of about every 20 seconds.  This drains the battery very fast!

**Comment by Koenkk** [comment]
I've added the missing converter, but this won't fix the drain.

**Comment by skandragon** [comment]
I'll find out :). I've found some misbehaving devices before which, unless fully and as they demand properly configured, will result in a retry storm -- just a very small 30 second storm in this case.

**Comment by Duffy987** [comment]
Gibt es inzwischen eine Lösung?
Is there a solution now?
Regards Duffy
