### ISSUE TITLE
Request to add the new models of ceiling lamp philips hue being

### ISSUE THREAD

**Issue by pk68-github** [Koenkk/zigbee-herdsman-converters#1628]
Please add the new models of ceiling lamp [philips hue being](https://www.philips-hue.com/de-de/p/hue-white-ambiance-being-deckenleuchte/3261031P6).

The old model with number 3261030P7 is available at the converter. 
[zigbee2mqtt.io](https://www.zigbee2mqtt.io/devices/3261030P7.html)

Please add the following code in the devices.js:

    {
        zigbeeModel: ['3261030P6'],
        model: '3261030P6',
        vendor: 'Philips',
        description: 'Hue Being Black',
        meta: {turnsOffAtBrightness1: true},
        extend: hue.light_onoff_brightness_colortemp,
        ota: ota.zigbeeOTA,
    },
    {
        zigbeeModel: ['3261031P6'],
        model: '3261031P6',
        vendor: 'Philips',
        description: 'Hue Being White',
        meta: {turnsOffAtBrightness1: true},
        extend: hue.light_onoff_brightness_colortemp,
        ota: ota.zigbeeOTA,
    },
    {
        zigbeeModel: ['3261048P6'],
        model: '3261048P6',
        vendor: 'Philips',
        description: 'Hue Being Aluminium',
        meta: {turnsOffAtBrightness1: true},
        extend: hue.light_onoff_brightness_colortemp,
        ota: ota.zigbeeOTA,
    },

Thanks.

**Comment by Koenkk** [comment]
Added, Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
