### ISSUE TITLE
Heiman Smoke Detector HS1SA incorrectly recognised as HS3SA

### ISSUE THREAD

**Issue by martinschm** [Koenkk/zigbee-herdsman-converters#1632]
Hi,

as per https://github.com/ioBroker/ioBroker.zigbee/issues/802#issuecomment-704050024

the Heiman Smoke Detector HS1SA is incorrectly recognised as HS3SA

`2020-10-01 20:18:15.520 - info: zigbee.0 (1131) Starting interview of '0x00158d0004b487d4'
2020-10-01 20:18:41.818 - info: zigbee.0 (1131) Successfully interviewed '0x00158d0004b487d4', device has succesfully been paired
2020-10-01 20:18:41.819 - info: zigbee.0 (1131) Device '0x00158d0004b487d4' is supported, identified as: HEIMAN Smoke detector (HS3SA)
2020-10-01 20:18:41.821 - info: zigbee.0 (1131) Configuring 0x00158d0004b487d4 SmokeSensor-N-3.0
2020-10-01 20:18:59.874 - info: zigbee.0 (1131) Zigbee: stop joining
2020-10-01 20:19:17.396 - error: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2020-10-01 20:19:17.397 - error: zigbee.0 (1131) unhandled promise rejection: Command 0x00158d0004b487d4/1 ssIasZone.enrollRsp({"enrollrspcode":0,"zoneid":23}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'No network route' (205))
2020-10-01 20:19:17.398 - error: zigbee.0 (1131) Error: Command 0x00158d0004b487d4/1 ssIasZone.enrollRsp({"enrollrspcode":0,"zoneid":23}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'No network route' (205))
at ZStackAdapter. (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:309:27)
at Generator.next ()
at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
2020-10-01 20:19:17.399 - info: zigbee.0 (1131) cleaned everything up...
2020-10-01 20:19:17.401 - info: zigbee.0 (1131) Zigbee: disabling joining new devices.`

**Note**: The log also contains other errors related to network routing. 2 out of 6 Heiman smoke detectors are having trouble getting onto the network.

**Comment by Koenkk** [comment]
Can you provide the `data/database.db` entry of this device?

**Comment by martinschm** [comment]
Hi Koen,
Happy to provide the file/entry however I am completely new to Zigbee via herdsman (coming from Conbee and native Xiaomi), not sure where to find the database and how to provide the entry.

**Comment by Koenkk** [comment]
@kirovilya where can this file be found for iobroker.zigbee?

**Comment by kirovilya** [comment]
usually around here `/opt/iobroker/iobroker-data/zigbee_0/shepherd.db`

**Comment by martinschm** [comment]
Hi,

is this was you are looking for?
`{"id":3,"type":"EndDevice","ieeeAddr":"0x00158d0004b487d4","nwkAddr":62422,"manufId":4619,"manufName":"HEIMAN","powerSource":"Battery","modelId":"SmokeSensor-N-3.0","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,3,1,1280,1282,2821],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"SmokeSensor-N-3.0","manufacturerName":"HEIMAN","powerSource":3,"zclVersion":2,"appVersion":20,"stackVersion":2,"hwVersion":16,"dateCode":"2018.9.27","swBuildId":"2000-0001"}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b001caab658","zoneState":1}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b001caab658","endpointID":1}]}},"appVersion":20,"stackVersion":2,"hwVersion":16,"dateCode":"2018.9.27","swBuildId":"2000-0001","zclVersion":2,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1601969819883}`

**Comment by martinschm** [comment]
I had a look at all the other Heiman Smoke sensors and noticed that especially this one has a sligthly different entry than the others (genPowerCfg is only present with this id:3 sensor):

```
{"id":42,"type":"EndDevice","ieeeAddr":"0x00158d0004fcf923","nwkAddr":37267,"manufId":4619,"manufName":"HEIMAN","powerSource":"Battery","modelId":"SmokeSensor-N-3.0","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,3,1,1280,1282,2821],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"powerSource":3,"zclVersion":2,"appVersion":20,"stackVersion":2,"hwVersion":16,"dateCode":"2018.9.27","swBuildId":"2000-0001"}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b001caab658","zoneState":1}}},"binds":[]}},"appVersion":20,"stackVersion":2,"hwVersion":16,"dateCode":"2018.9.27","swBuildId":"2000-0001","zclVersion":2,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1601940858673}
{"id":3,"type":"EndDevice","ieeeAddr":"0x00158d0004b487d4","nwkAddr":62422,"manufId":4619,"manufName":"HEIMAN","powerSource":"Battery","modelId":"SmokeSensor-N-3.0","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,3,1,1280,1282,2821],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"SmokeSensor-N-3.0","manufacturerName":"HEIMAN","powerSource":3,"zclVersion":2,"appVersion":20,"stackVersion":2,"hwVersion":16,"dateCode":"2018.9.27","swBuildId":"2000-0001"}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b001caab658","zoneState":1}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b001caab658","endpointID":1}]}},"appVersion":20,"stackVersion":2,"hwVersion":16,"dateCode":"2018.9.27","swBuildId":"2000-0001","zclVersion":2,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1601969819883}
{"id":12,"type":"EndDevice","ieeeAddr":"0x00158d0004fcf82a","nwkAddr":11850,"manufId":4619,"manufName":"HEIMAN","powerSource":"Battery","modelId":"SmokeSensor-N-3.0","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,3,1,1280,1282,2821],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"SmokeSensor-N-3.0","manufacturerName":"HEIMAN","powerSource":3,"zclVersion":2,"appVersion":20,"stackVersion":2,"hwVersion":16,"dateCode":"2018.9.27","swBuildId":"2000-0001"}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b001caab658","zoneState":1}}},"binds":[]}},"appVersion":20,"stackVersion":2,"hwVersion":16,"dateCode":"2018.9.27","swBuildId":"2000-0001","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1601896404040}
{"id":13,"type":"EndDevice","ieeeAddr":"0x00158d0004fcf946","nwkAddr":19029,"manufId":4619,"manufName":"HEIMAN","powerSource":"Battery","modelId":"SmokeSensor-N-3.0","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,3,1,1280,1282,2821],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"SmokeSensor-N-3.0","manufacturerName":"HEIMAN","powerSource":3,"zclVersion":2,"appVersion":20,"stackVersion":2,"hwVersion":16,"dateCode":"2018.9.27","swBuildId":"2000-0001"}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b001caab658","zoneState":1}}},"binds":[]}},"appVersion":20,"stackVersion":2,"hwVersion":16,"dateCode":"2018.9.27","swBuildId":"2000-0001","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1601897572219}
{"id":14,"type":"EndDevice","ieeeAddr":"0x00158d0004b487e0","nwkAddr":50272,"manufId":4619,"manufName":"HEIMAN","powerSource":"Battery","modelId":"SmokeSensor-N-3.0","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,3,1,1280,1282,2821],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"SmokeSensor-N-3.0","manufacturerName":"HEIMAN","powerSource":3,"zclVersion":2,"appVersion":20,"stackVersion":2,"hwVersion":16,"dateCode":"2018.9.27","swBuildId":"2000-0001"}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b001caab658","zoneState":1}}},"binds":[]}},"appVersion":20,"stackVersion":2,"hwVersion":16,"dateCode":"2018.9.27","swBuildId":"2000-0001","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1601981367617}
{"id":15,"type":"EndDevice","ieeeAddr":"0x00158d0004fc9476","nwkAddr":14139,"manufId":4619,"manufName":"HEIMAN","powerSource":"Battery","modelId":"SmokeSensor-N-3.0","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,3,1,1280,1282,2821],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"SmokeSensor-N-3.0","manufacturerName":"HEIMAN","powerSource":3,"zclVersion":2,"appVersion":20,"stackVersion":2,"hwVersion":16,"dateCode":"2018.9.27","swBuildId":"2000-0001"}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b001caab658","zoneState":1}}},"binds":[]}},"appVersion":20,"stackVersion":2,"hwVersion":16,"dateCode":"2018.9.27","swBuildId":"2000-0001","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1601982322935}
```

**Comment by Koenkk** [comment]
For you bind error, see https://github.com/Koenkk/zigbee2mqtt/issues/2394#issuecomment-596547337

I've updated the definition, so once iobroker updates it will be marked as HS1SA.
