### ISSUE TITLE
Niviss NIV-ZC-ODF - trying to define in devices

### ISSUE THREAD

**Issue by mkotek** [Koenkk/zigbee-herdsman-converters#1633]
I have a number of NIV-ZC-ODF whcih are named ZIGBEE-SMART-CONTROLER-1CH-DIMMABLE by the company that makes them - Niviss. There is absolutely no tech card available, but I have figured, it should be similar to Paulmann devices, so I have defined it as similar to 50043 and later to 50044/50045 (one is the controller, the other is light). The device itself is similar to Gledopto controllers for LEDs. Yet none of those definitions seem to be working - all the time getting No components in zigbee2mqtt assistant, even though zigbee2mqtt itself shows what I define as supported. No entity is however created in HA after the add-on is restarted.

I have followed https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html, but no error about lacking converters is displayed.

Here is the relevant output from the log file:
{"date_code":"20180701","definition":{"description":"PS-ZIGBEE-SMART-CONTROLER-1CH-DIMMABLE","model":"NIV-ZC-OFD","supports":"on/off","vendor":"Niviss"},"endpoints":{"1":{"bindings":[],"clusters":{"input":["genBasic","genGroups","genIdentify","genOnOff","genLevelCtrl","genScenes","touchlink"],"output":["genOta"]}}},"friendly_name":"0x00158d0001cb057f","ieee_address":"0x00158d0001cb057f","interview_completed":true,"interviewing":false,"network_address":52667,"power_source":"Mains (single phase)","software_build_id":"2000-1005","supported":true,"type":"Router"}]'

{"dateCode":"20180701","description":"PS-ZIGBEE-SMART-CONTROLER-1CH-DIMMABLE","friendly_name":"0x00158d0001cb057f","hardwareVersion":1,"ieeeAddr":"0x00158d0001cb057f","lastSeen":1601992016773,"manufacturerID":4151,"manufacturerName":"NIVISS","model":"NIV-ZC-OFD","modelID":"NIV-ZC-OFD","networkAddress":52667,"powerSource":"Mains (single phase)","softwareBuildID":"2000-1005","type":"Router","vendor":"Niviss"}]'

Zigbee2MQTT:debug 2020-10-06 17:46:14: Received Zigbee message from '0x00158d0001cb057f', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":1,"imageType":4353,"manufacturerCode":4624}' from endpoint 1 with groupID 0

No other information is displayed in the log files and I am unable to do anything with the device.
Can you please direct me, what to do next?

**Comment by Koenkk** [comment]
For Home Assistant discovery you also need to add it to homeassistant.js: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html#5-optional-add-home-assistant-configuration-for-your-device

**Comment by mkotek** [comment]
But I am using Hassio add-on. Is there any way to add this mapping in this scenario?

**Comment by Koenkk** [comment]
@mkotek can you post the config you added to `devices.js` here? Then I can integrate it.

**Comment by mkotek** [comment]
I can of course, but I do not know, if it is correct - cannot test it or just do not know how.

// Niviss
{
     zigbeeModel: ['NIV-ZC-OFD'],
     model: 'NIV-ZC-OFD',
     vendor: 'Niviss',
     description: 'PS-ZIGBEE-SMART-CONTROLER-1CH-DIMMABLE',
     extend: generic.light_onoff_brightness,
},

**Comment by Koenkk** [comment]
Added, Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html) (edge for hassio)

**Comment by mkotek** [comment]
I am happy to say, it works in the current Edge version, albeit only on/off, no brightness control. But it is a step forward and I hope, we will manage to support it fully.

**Comment by Koenkk** [comment]
Can you control brightness via MQTT (https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttfriendly_nameset)?

**Comment by mkotek** [comment]
Will check on Friday as I had to take the device to the install place (no internet yet for remote access). Will come back to you with the update, when only I have it as it is really important to me (already 6 devices like that installed and at least 3 more to come). Thank you for the great support last night.

**Comment by mkotek** [comment]
I am sorry for the lack of earlier answer, but it took longer to have everything in place, including internet connection. Anyway, I seem to be having a strange issue. The lamp that used to work at the beginning has now stopped working. I have removed it and cannot add it again. But I have managed to add another of the same type and it is working absolutely fine on Edge version of the add-on, including brightness control. But for some reason, the rest 4 of the controllers are not detected and added to Zigbee2MQTT. How can I troubleshoot that? I have tried adding them by Allowing join and resetting one after another, tired to turn them all on and leave them as it is for hours, tried to reset them one by one with the rest turned on. Nothing helps.

**Comment by Koenkk** [comment]
Check: https://www.zigbee2mqtt.io/information/FAQ.html#why-does-my-device-not-or-fail-to-pair

**Comment by mkotek** [comment]
I am getting somewhere, as I have managed to pair 3 devices and three others blink 3 times after reset, then one time and do not get detected.
But one last thing that remains. HA does not display the brightness control - on Zigbee2MQTT directly I am seen brightness control and can use it, but those are not exposed to HA. Can you add that as well?

**Comment by Koenkk** [comment]
Can you make a screenshot of what you see in HA? (also make sure to turn on, I believe the brightness slider is only availabel when the device is on).

**Comment by mkotek** [comment]
Sure, see attached.
![Screenshot 2020-10-16 at 20 11 00](https://user-images.githubusercontent.com/9081499/96293957-e47c1380-0feb-11eb-900e-b0f2d61fe350.png)
![Screenshot 2020-10-16 at 20 10 27](https://user-images.githubusercontent.com/9081499/96293960-e514aa00-0feb-11eb-85ce-dd89f2912844.png)
![Screenshot 2020-10-16 at 20 10 06](https://user-images.githubusercontent.com/9081499/96293961-e5ad4080-0feb-11eb-91c5-d7a57d01c430.png)

Do you know, what 3 flashes and then 1 flash mean for Zigbee? This is what I get from the ones I cannot pair. What is interesting, they are located next to the working ones.

**Comment by Koenkk** [comment]
What 3 flashes means differs per device, you can try to reset the bulbs via touclink instead (https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttbridgeconfigtouchlinkfactory_reset) . But this is broken in the current release and requires the dev branch. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
