### ISSUE TITLE
SM311 problem?

### ISSUE THREAD

**Issue by thomaspleasance** [Koenkk/zigbee-herdsman-converters#1653]
I have a SM311 (https://www.zigbee2mqtt.io/devices/ZG2835RAC.html) and it reports itself as model SM311 but when it joins my network it marks itself as unsupported.

I had to change the node_modules/zigbee-herdsman-converters/devices.js for "zigbeeModel: ['Micro Smart Dimmer']," to SM311 to make it work. Is this normal or should it just work? 

From
`    {
        zigbeeModel: ['Micro Smart Dimmer'],
        model: 'ZG2835RAC',
        vendor: 'Sunricher',
        description: 'ZigBee knob smart dimmer',
        supports: generic.light_onoff_brightness.supports + ', power measurements',
        fromZigbee: generic.light_onoff_brightness.fromZigbee.concat(
            [fz.electrical_measurement_power, fz.metering_power, fz.ignore_genOta],
        ),
        toZigbee: generic.light_onoff_brightness.toZigbee,
        meta: {configureKey: 2},
        whiteLabel: [
            {vendor: 'YPHIX', model: '50208695'},
            {vendor: 'Samotech', model: 'SM311'},
        ],`

to

`    {
        zigbeeModel: ['SM311'],
        model: 'ZG2835RAC',
        vendor: 'Samotech',
        description: 'ZigBee knob smart dimmer',
        supports: generic.light_onoff_brightness.supports + ', power measurements',
        fromZigbee: generic.light_onoff_brightness.fromZigbee.concat(
            [fz.electrical_measurement_power, fz.metering_power, fz.ignore_genOta],
        ),
        toZigbee: generic.light_onoff_brightness.toZigbee,
        meta: {configureKey: 2},
        whiteLabel: [
            {vendor: 'YPHIX', model: '50208695'},
            {vendor: 'Sunricher', model: 'Micro Smart Dimmer'},
        ],`

**Comment by Koenkk** [comment]
Added this model.

Changes will be available in the latest dev branch tomorrow (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by thomaspleasance** [comment]
Thank you 🙏
