### ISSUE TITLE
New Device? - Hive SLR1

### ISSUE THREAD

**Issue by BiggsSkeedR** [Koenkk/zigbee-herdsman-converters#1662]
I've finally persuaded my wife to ditch the Hive hub in favour of Home Assistant, however, I've just tried to add our Hive heating and it's reporting itself as "SLR1" rather than "SLR1b" and thus isn't controllable. I can't find any information on whether there is actually any difference or whether they're in fact the same model.

I don't currently have any kit to sniff Zigbee packets, at least, that I know of. If I can sniff using a Zigbee USB dongle in Home Assistant, please advise how I'd go about it.

**Comment by Koenkk** [comment]
In devices.js try to also add `SLR1` to the `zigbeeModel` array of `SLR1b` and check if it works.

See https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html on how to modify devices.js

**Comment by BiggsSkeedR** [comment]
I tried following that page but couldn't get anywhere in the rabbit warren of information. I'm running Home Assistant with the Zigbee2mqtt add-on. Regardless, It's probably best if I wait until the next update when SLT3 support, I assume, will be added into the main branch (There's a PR for it that looks like it's been accepted?). I'll report back if I find any oddities.

**Comment by BiggsSkeedR** [comment]
I've tried to fo,low

**Comment by steveuk23** [comment]
> I've tried to follow the guides to add a custom device but, to be frank, they're horrendous and apparently outdated. There's references to a /data/ folder that apparently no longer apply (It now appears to look at /share/zigbee2mqtt) and I can't get an external_converter to work using the provided guide and examples.
> 
> Currently getting the following, having copied the device declaration from devices.js to a new SLR1.js in /share/zigbee2mqtt;
> evalmachine.:17
> exposes.climate().withSetpoint('occupied_heating_setpoint', 7, 30, 1).withLocalTemperature()
> ^
> ReferenceError: exposes is not defined
> at evalmachine.:17:13
> at Script.runInContext (vm.js:130:18)
> at Script.runInNewContext (vm.js:135:17)
> at Object.runInNewContext (vm.js:302:38)
> at Object.getExternalConvertersDefinitions (/zigbee2mqtt-1.16.2/lib/util/utils.js:159:16)
> at getExternalConvertersDefinitions.next ()
> at HomeAssistant.populateMapping (/zigbee2mqtt-1.16.2/lib/extension/homeassistant.js:452:20)
> at new HomeAssistant (/zigbee2mqtt-1.16.2/lib/extension/homeassistant.js:108:14)
> at new Controller (/zigbee2mqtt-1.16.2/lib/controller.js:80:34)
> at Object. (/zigbee2mqtt-1.16.2/index.js:25:20)#
> 
> What am I doing wrong? Can I help improve the documentation for Home Assistant users?

i know this is really old but i'm looking at adding this device also (SLR1)
Did you get any success with this at all ?
i did edit the hive.js file i found and renamed it but that didnt work as the addon would freeeze on restart 
do you have any ideas @Koenkk 
Thanks
![hive](https://user-images.githubusercontent.com/18037536/127679557-a98ad813-0680-456b-acfd-e28d3bb97c00.png)

**Comment by robertalexa** [comment]
Thread continued here:
https://github.com/Koenkk/zigbee2mqtt/issues/8184

If anyone else is still watching this issue feel free to participate above
