### ISSUE TITLE
Gledopto GL-C-007/GL-C-008-2ID: no LQI, last_seen not updating

### ISSUE THREAD

**Issue by docbobo** [Koenkk/zigbee-herdsman-converters#1688]
After some woes with my Gledopto GL-C-008-2ID, I finally got it working rather consistently. One thing I noticed though: the new Frontend often does not report LQI (something I can probably live with), but also last_seen is not updating. The latter is surprising since I am only controlling the device via Z2M.

**Comment by Koenkk** [comment]
You will only get a LQI/last_seen when a device sends messages to the coordinator (which is often not the case for light kind of devices).

About the last_seen, I'm wondering if we should also update this once we successfully execute a command.

**Comment by docbobo** [comment]
> About the last_seen, I'm wondering if we should also update this once we successfully execute a command.
That's actually what I thought it is doing...

**Comment by Koenkk** [comment]
I've checked again, but this should already be the case, can you share the `data/database.db` of your device?

**Comment by docbobo** [comment]
Here we go:
```
{
    "id": 30,
    "type": "Router",
    "ieeeAddr": "0x00124b001ada7031",
    "nwkAddr": 22819,
    "manufId": 0,
    "manufName": "GLEDOPTO",
    "powerSource": "Mains (single phase)",
    "modelId": "GL-C-007",
    "epList": [
        11,
        12,
        13,
        15
    ],
    "endpoints": {
        "11": {
            "profId": 49246,
            "epId": 11,
            "devId": 528,
            "inClusterList": [
                0,
                3,
                4,
                5,
                6,
                8,
                768
            ],
            "outClusterList": [],
            "clusters": {},
            "binds": [],
            "meta": {}
        },
        "12": {
            "profId": 260,
            "epId": 12,
            "devId": 258,
            "inClusterList": [
                0,
                3,
                4,
                5,
                6,
                8,
                768
            ],
            "outClusterList": [],
            "clusters": {
                "genBasic": {
                    "attributes": {
                        "modelId": "GL-C-007",
                        "manufacturerName": "GLEDOPTO",
                        "powerSource": 1,
                        "zclVersion": 1,
                        "appVersion": 1,
                        "stackVersion": 2,
                        "hwVersion": 1,
                        "dateCode": "20180920",
                        "swBuildId": "1.0.2"
                    }
                }
            },
            "binds": [],
            "meta": {}
        },
        "13": {
            "profId": 49246,
            "epId": 13,
            "devId": 57694,
            "inClusterList": [
                4096
            ],
            "outClusterList": [
                4096
            ],
            "clusters": {},
            "binds": [],
            "meta": {}
        },
        "15": {
            "profId": 49246,
            "epId": 15,
            "devId": 256,
            "inClusterList": [
                0,
                3,
                4,
                5,
                6,
                8,
                768
            ],
            "outClusterList": [],
            "clusters": {},
            "binds": [],
            "meta": {}
        }
    },
    "appVersion": 1,
    "stackVersion": 2,
    "hwVersion": 1,
    "dateCode": "20180920",
    "swBuildId": "1.0.2",
    "zclVersion": 1,
    "interviewCompleted": true,
    "meta": {},
    "lastSeen": 1603111068412
}
```

**Comment by Koenkk** [comment]
I understand why it is happening now. For this specific device the defaultResponse is disabled (https://github.com/Koenkk/zigbee-herdsman-converters/blob/c233df5a7ecb2a8c54edc37e3e7168b2f773769d/devices.js#L6398). When a command is send, normally a device will respond with a defaultResponse, indicating that it received the command. However some gledopto devices don't do this (which is against the spec). If we would not disable the default response here Zigbee2MQTT will timeout after 10 seconds. When default response is disabled we have no clue if the device received the command, normally Zigbee2MQTT updates the last seen when the default response is received.

You can try if this disableDefaultResponse is indeed needed by removing it here: https://github.com/Koenkk/zigbee-herdsman-converters/blob/c233df5a7ecb2a8c54edc37e3e7168b2f773769d/devices.js#L6398 (if you get timeouts when sending commands it is needed).

**Comment by docbobo** [comment]
If  I recall correctly, you added that line because I was complaining that the device is not working properly ;) I guess I'll just replace that piece of crap with something more compliant...
