### ISSUE TITLE
New device definition for meazon meters - error - how to upgrade definitions?

### ISSUE THREAD

**Issue by ccorderod** [Koenkk/zigbee-herdsman-converters#1699]
Hi @Koenkk 

I have to submit new devices.js definitions for the Meazon meters as well as an updated fromZigbee.js code.
My devices were quite old, and running on a very old firmware. Meazon sent me latest firmware and all of them are updated, but there were big changes on the way they report (some fields are now integer32 instead of float).
The way we have to configure them did change too.
Hence I should submit new definition for them. This is the new definition for devices.js:
`    // Meazon
    {
        zigbeeModel: [
            '101.301.001649', '101.301.001838', '101.301.001802', '101.301.001738',
            '101.301.001412', '101.301.001765', '101.301.001814',
        ],
        model: 'MEAZON_BIZY_PLUG',
        vendor: 'Meazon',
        description: 'Bizy plug meter',
        supports: 'on/off, power, energy measurement and temperature',
        fromZigbee: [
            fz.command_on, fz.legacy_genOnOff_cmdOn, fz.command_off, fz.legacy_genOnOff_cmdOff, fz.on_off,
            fz.meazon_meter,
        ],
        toZigbee: [tz.on_off],
        meta: {configureKey: 24},
        ota: ota.meazon,
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(10);
            await bind(endpoint, coordinatorEndpoint, ['genOnOff', 'seMetering']);
            await configureReporting.onOff(endpoint, {min: 1, max: 3600, change: 0});
            const options = {manufacturerCode: 4406, disableDefaultResponse: true};
            await endpoint.write('seMetering', {0x1005: {value: 0x071f, type: 25}}, options);
            await endpoint.configureReporting('seMetering', [{
                attribute: {ID: 0x2007, type: 0x39},
                minimumReportInterval: 1,
                maximumReportInterval: 5,
                reportableChange: 1,
            }], options);
            await endpoint.configureReporting('seMetering', [{
                attribute: {ID: 0x3000, type: 0x23},
                minimumReportInterval: 1,
                maximumReportInterval: 5,
                reportableChange: 1,
            }], options);
        },
    },
    {
        zigbeeModel: [
            '102.106.000235', '102.106.001111', '102.106.000348', '102.106.000256', '102.106.001242',
            '102.106.000540',
        ],
        model: 'MEAZON_DINRAIL',
        vendor: 'Meazon',
        description: 'DinRail 1-phase meter',
        supports: 'on/off, power, energy measurement and temperature',
        fromZigbee: [
            fz.command_on, fz.legacy_genOnOff_cmdOn, fz.command_off, fz.legacy_genOnOff_cmdOff, fz.on_off,
            fz.meazon_meter,
        ],
        toZigbee: [tz.on_off],
        meta: {configureKey: 24},
        ota: ota.meazon,
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(10);
            await bind(endpoint, coordinatorEndpoint, ['genOnOff', 'seMetering']);
            await configureReporting.onOff(endpoint, {min: 1, max: 3600, change: 0});
            const options = {manufacturerCode: 4406, disableDefaultResponse: true};
            await endpoint.write('seMetering', {0x1005: {value: 0x071f, type: 25}}, options);
            await endpoint.configureReporting('seMetering', [{
                attribute: {ID: 0x2007, type: 0x39},
                minimumReportInterval: 1,
                maximumReportInterval: 5,
                reportableChange: 1,
            }], options);
            await endpoint.configureReporting('seMetering', [{
                attribute: {ID: 0x3000, type: 0x23},
                minimumReportInterval: 1,
                maximumReportInterval: 5,
                reportableChange: 1,
            }], options);
        },
    },
`

I didn't PR this because I am getting the following error during z2m startup and honestly I do not know how to fix this:

`error 2020-10-21 15:21:27: Failed to setup reporting for '0x00124b0002cc3cba' - TypeError: Cannot read property 'groupID' of undefined
    at Endpoint.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:281:103)
    at Generator.next (<anonymous>)
    at /opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:23:12)
    at Endpoint.bind (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:275:16)
    at Report.setupReporting (/opt/zigbee2mqtt/lib/extension/report.js:150:38)
    at Report.onZigbeeEvent (/opt/zigbee2mqtt/lib/extension/report.js:225:24)
    at Controller.callExtensionMethod (/opt/zigbee2mqtt/lib/controller.js:372:44)
`
There is one error on the log per meter, just one time. Devices are working perfectly in any case but I would like to get rid of this error before submitting. Any tip?

One more thing; this error may also show up on the log:
`error 2020-10-21 15:21:29: Failed to configure 'Plug5-Salon', attempt 1 (Error: Write 0x00124b0002cc807e/10 seMetering({"4101":{"value":1823,"type":25}}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4406,"transactionSequenceNumber":null}) failed (Status 'FAILURE')
    at Endpoint.checkStatus (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:173:23)
    at Endpoint.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:202:26)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:24:58))
`
It will NOT appear the first time the meter is configured, but will thereafter. The reason is because when you tell the meter to change the reporting (endpoint.write('seMetering', {0x1005: {value: 0x071f, type: 25}}), the firmware has to reallocate memory buffers and reset itself. To avoid this reset, the manufacturer check if the reporting mode request is the same and in this case it throw a "FAILURE" code (instead of just doing nothing). This has to be stated in the zigbee2mqtt documentation.

Let me know how do you want me to proceed with this. Thank you.

**Comment by Koenkk** [comment]
Can you make a pr for this? We can discuss further there (it's easier for me to add comments there).
