### ISSUE TITLE
add SMOK_V15

### ISSUE THREAD

**Issue by kozlik07** [Koenkk/zigbee-herdsman-converters#1723]
please add an entry SMOK_v15 

    {
        zigbeeModel: [
            'SMOK_V16',
	    'SMOK_V15',
            'b5db59bfd81e4f1f95dc57fdbba17931',
            '98293058552c49f38ad0748541ee96ba',
            'SMOK_YDLV10',
            'SmokeSensor-EM',
            'FB56-SMF02HM1.4',
            'SmokeSensor-N-3.0',
        ],
        model: 'HS1SA',
        vendor: 'HEIMAN',
        description: 'Smoke detector',
        supports: 'smoke',
        fromZigbee: [fz.ias_smoke_alarm_1, fz.battery],
        toZigbee: [],
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            await bind(endpoint, coordinatorEndpoint, ['genPowerCfg']);
            await configureReporting.batteryPercentageRemaining(endpoint);
        },
        exposes: [e.smoke(), e.battery_low(), e.tamper(), e.battery()],
    },

**Comment by Koenkk** [comment]
added,thanks!
