### ISSUE TITLE
add new Occupancy Sensor 

### ISSUE THREAD

**Issue by kozlik07** [Koenkk/zigbee-herdsman-converters#1724]
'PIR_TPV12'   Occupancy Sensor 

{
        zigbeeModel: ['SMHM-I1',
                                 'PIR_TPV12'],
        model: 'SMHM-I1',
        vendor: 'HEIMAN',
        description: 'Smart motion sensor',
        supports: 'occupancy',
        fromZigbee: [fz.ias_occupancy_alarm_1],
        toZigbee: [],
        exposes: [exposes.boolean('occupancy'), exposes.boolean('battery_low'), exposes.boolean('tamper')],
    },

**Comment by Koenkk** [comment]
added, thanks!
