### ISSUE TITLE
Support for Heiman Vibration-EF_3.0

### ISSUE THREAD

**Issue by sunde41** [Koenkk/zigbee-herdsman-converters#1726]
Hello!

Heiman Vibration-EF_3.0 is the same to HS1VS-N except battery change (to 2*AAA)
https://heimansmart.en.alibaba.com/product/60339753872-802153532/Zigbee_sensitive_wireless_vibration_sensor_for_IOT_smart_home.html
Thanks!

{
        fingerprint: [{modelID: 'Vibration-EF_3.0', manufacturerName: 'HEIMAN'}],
        model: 'HS1VS-EF',
        vendor: 'HEIMAN',
        description: 'Vibration sensor',
        supports: 'vibration',
        fromZigbee: [fz.ias_vibration_alarm_1, fz.battery],
        toZigbee: [],
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            await bind(endpoint, coordinatorEndpoint, ['genPowerCfg']);
            await configureReporting.batteryPercentageRemaining(endpoint, {min: repInterval.MINUTES_5, max: repInterval.HOUR});
            await endpoint.read('genPowerCfg', ['batteryPercentageRemaining']);
        },
        exposes: [e.vibration(), e.battery_low(), e.tamper(), e.battery()],
    },

**Comment by Koenkk** [comment]
Added, thanks
