### ISSUE TITLE
Setting BHT-002 temperature decimals  

### ISSUE THREAD

**Issue by Courty40** [Koenkk/zigbee-herdsman-converters#1740]
Hi Guys,

having an issue using this device in deg C.
I can set the target temperature to whole numbers like 20 or 21 but if I set it to 21.5, the unit switches to 0.

It is possible to set half degs on the unit and it returns half degs for the current temp but I cant set them.

Any ideas on this ?

Courty

**Comment by insipiens** [comment]
Hi Courty

Alas not, in their [Moes] wisdom they made the app communicate with only integer values. As you have discovered it zeros the thermostat if you send a decimal value as the firmware is expecting only integers.

**Comment by Courty40** [comment]
Thanks for that, odd that they would do that, I assume it was designed for F not C

**Comment by insipiens** [comment]
I asked them if they planned to improve this in a firmware update, could you also enquire?

**Comment by ivan11paths** [comment]
This could be solved. Can you control it from home assistant with 0.5 ºC precision? Is there any other similar thermostat that allows this level of precision?
