### ISSUE TITLE
Feibit switch without feedback from physical button

### ISSUE THREAD

**Issue by Jhonattan-Souza** [Koenkk/zigbee-herdsman-converters#1756]
Hello guys,

Recently i've added the model of my Zemismart Feibit switch at device.js and it worked. But when I press the physical button, there's no feedback of on/off states to zigbee2mqtt, tried to implement different configurations 

Device:
![image](https://user-images.githubusercontent.com/19364782/99026321-7aeb1880-2549-11eb-980b-95d88bcd1072.png)

Configurations:
        zigbeeModel: ['FB56+ZSW1GKJ2.7'],
        model: 'HGZB-42',
        vendor: 'Feibit',
        description: 'Smart one gang wall switch',
        extend: generic.switch,

and

        zigbeeModel: ['FB56+ZSW1GKJ2.7'],
        model: 'HGZB-42',
        vendor: 'Feibit',
        description: 'Smart one gang wall switch',
        extend: generic.switch,
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(16);
            await bind(endpoint, coordinatorEndpoint, ['genOnOff']);
            await configureReporting.onOff(endpoint);
        },

with no success.

In my samsung smartthings, the device send these messages when i press the physical button

[raw:0104 0006 10 0B 0000 00 6559 00 00 0000 0A 01 00002001, profileId:0104, clusterId:0006, sourceEndpoint:10, destinationEndpoint:0B, options:0000, messageType:00, dni:6559, isClusterSpecific:false, isManufacturerSpecific:false, manufacturerId:0000, command:0A, direction:01, attrId:0000, encoding:20, value:01, isValidForDataType:true, data:[00, 00, 20, 01], clusterInt:6, attrInt:0, commandInt:10]

[raw:0104 0006 10 0B 0000 00 6559 00 00 0000 0A 01 00002000, profileId:0104, clusterId:0006, sourceEndpoint:10, destinationEndpoint:0B, options:0000, messageType:00, dni:6559, isClusterSpecific:false, isManufacturerSpecific:false, manufacturerId:0000, command:0A, direction:01, attrId:0000, encoding:20, value:00, isValidForDataType:true, data:[00, 00, 20, 00], clusterInt:6, attrInt:0, commandInt:10]

Tried to expose in the configuration the endpoint10 but it didnt worked as well.

![image](https://user-images.githubusercontent.com/19364782/99026137-1c259f00-2549-11eb-838a-5ea56ca668a5.png)

In the logs, even in the debug log level, nothing different appears to me.

I would appreciate any help. Thanks

**Comment by juslex** [comment]
Dear,

What’s your coordinator? Convee2? I have the some issue. With zzh! I wasn’t problem only with conbee 2.

I have opened a issue: check it: 

https://github.com/Koenkk/zigbee2mqtt/issues/4461

**Comment by Jhonattan-Souza** [comment]
> Dear,
> 
> What’s your coordinator? Conbee2? I have the some issue. With zzh! I wasn’t problem only with conbee 2.
> 
> I have opened a issue: check it:
> 
> [Koenkk/zigbee2mqtt#4461](https://github.com/Koenkk/zigbee2mqtt/issues/4461)

Yes, Conbee II, Im going to follow your discussion

**Comment by Jhonattan-Souza** [comment]
Closing this issue because it's being discussed at https://github.com/Koenkk/zigbee2mqtt/issues/4461
