### ISSUE TITLE
FNB56-SKT1EHG1.2

### ISSUE THREAD

**Issue by arcsyst** [Koenkk/zigbee-herdsman-converters#177]
Trying to get this 'Smart Socket' to work by myself but failing. I can receive the device status if I press the button on the socket but am failing due to mis-configuration or stupidity to send any commands to it. This is what I'm getting:

 zigbee2mqtt:debug 2018-12-29 16:08:40 Received MQTT message on 'zigbee2mqtt/0x00158d0002a85038/set' with data '{"state":"on"}'
  zigbee2mqtt:error 2018-12-29 16:08:40 No converter available for 'state' (on)

Pressing the manual on/off on the device generates:

  zigbee2mqtt:debug 2018-12-29 16:13:42 Received zigbee message of type 'attReport' with data '{"cid":"genOnOff","data":{"onOff":0}}' of device 'FNB56-SKT1EHG1.2' (0x00158d0002a85038)
  zigbee2mqtt:info 2018-12-29 16:13:42 MQTT publish, topic: 'zigbee2mqtt/0x00158d0002a85038', payload: '{"state":"OFF","linkquality":120}'
  zigbee2mqtt:debug 2018-12-29 16:13:42 Received zigbee message of type 'devChange' with data '{"cid":"genOnOff","data":{"onOff":0}}' of device 'FNB56-SKT1EHG1.2' (0x00158d0002a85038)
  zigbee2mqtt:debug 2018-12-29 16:13:44 Received zigbee message of type 'attReport' with data '{"cid":"genOnOff","data":{"onOff":1}}' of device 'FNB56-SKT1EHG1.2' (0x00158d0002a85038)
  zigbee2mqtt:info 2018-12-29 16:13:44 MQTT publish, topic: 'zigbee2mqtt/0x00158d0002a85038', payload: '{"state":"ON","linkquality":128}'
  zigbee2mqtt:debug 2018-12-29 16:13:44 Received zigbee message of type 'devChange' with data '{"cid":"genOnOff","data":{"onOff":1}}' of device 'FNB56-SKT1EHG1.2' (0x00158d0002a85038)

Using current versions of evices.js, fromZigbbe.js and toZigbee.js

**Comment by Koenkk** [comment]
What did you add to `devices.js`?

**Comment by arcsyst** [comment]
Trying to not reinvent the wheel I copied what seemed a similar device and renamed it:

  {
      zigbeeModel: ['FNB56-SKT1EHG1.2'],
      model: 'Z809A',
      vendor: 'Netvox',
      description: 'Power socket',
      supports: 'on/off',
      fromZigbee: [fz.ignore_onoff_change, fz.generic_state],
      toZigbee: [tz.on_off],
      // configure: (ieeeAddr, shepherd, coordinator, callback) => {
      //     const device = shepherd.find(ieeeAddr, 3);
      //     const cfg = {direction: 0, attrId: 0, dataType: 16, minRepIntval: 0, maxRepIntval: 1000, repChange: 0};
      //     const actions = [
      //         (cb) => device.bind('genOnOff', coordinator, cb),
      //         (cb) => device.foundation('genOnOff', 'configReport', [cfg], foundationCfg, cb),
      //     ];
      //
      //     execute(device, actions, callback);
      // },
  },

**Comment by Koenkk** [comment]
That looks good, `tz.on_off` should catch the `{"state":"on"}` message.  Could you provide the complete log? Could you also try just sending `"ON"` instead of `{"state":"on"}`.

**Comment by arcsyst** [comment]
I can’t explain it, it’s like it’s not referencing the correct bit of code.

I can send you anything, not sure what you want so have included the three most recent logs.





  zigbee2mqtt:debug 2018-12-30 20:16:13 Received MQTT message on 'zigbee2mqtt/0x00158d0002a85038/set' with data '"ON"'
  zigbee2mqtt:error 2018-12-30 20:16:13 No converter available for '0' (O)
  zigbee2mqtt:error 2018-12-30 20:16:13 No converter available for '1' (N)

  zigbee2mqtt:debug 2018-12-30 20:16:27 Received MQTT message on 'zigbee2mqtt/0x00158d0002a85038/set' with data 'ON'
  zigbee2mqtt:error 2018-12-30 20:16:27 No converter available for 'state' (ON)

  zigbee2mqtt:debug 2018-12-30 20:17:22 Received MQTT message on 'zigbee2mqtt/0x00158d0002a85038/set' with data 'on'
  zigbee2mqtt:error 2018-12-30 20:17:22 No converter available for 'state' (on)

**Comment by Koenkk** [comment]
On which zigbee2mqtt version are you?

**Comment by arcsyst** [comment]
> zigbee2mqtt@0.2.0 start /opt/zigbee2mqtt
> node index.js

                Zigbee2mqtt requires node version >=8.11 10, you are running v8.14.0!

**Comment by Koenkk** [comment]
Can you update to zigbee2mqtt 1.0.1 and try again?

**Comment by arcsyst** [comment]
Thank you that seems to have fixed it. Simply sending on or off is sufficient.

**Comment by arcsyst** [comment]
Since the update I'm getting lots of:
 zigbee2mqtt:error 2019-1-3 18:21:09 Cannot get the Node Descriptor of the Device: 0x00158d0001cc9439 (Error: Timed out after 10000 ms)
  zigbee2mqtt:error 2019-1-3 18:21:31 Cannot get the Node Descriptor of the Device: 0x00158d0001cc9439 (Error: Timed out after 10000 ms)

errors. I tried deleting the whole shebang and starting again but I'm having difficulties joining some devices that previously worked OK. Any thoughts?

**Comment by arcsyst** [comment]
Hi Koenkk,
Since updating to v1.01 I'm having trouble paring a device that you helped me configure a few weeks ago. It seems to pair ok but throws an error when activated (it's a door contact). I've paired it many times, always with the same result, it worked previously (v1.0.0).

  zigbee2mqtt:debug 2019-1-3 20:36:33 Received zigbee message of type 'devInterview' with data '"0x00158d000202bb30"'
  zigbee2mqtt:warn 2019-1-3 20:36:33 Message without device!
  zigbee2mqtt:debug 2019-1-3 20:36:34 Received zigbee message of type 'devInterview' with data '"0x00158d000202bb30"'
  zigbee2mqtt:warn 2019-1-3 20:36:34 Message without device!
  zigbee2mqtt:debug 2019-1-3 20:36:34 Received zigbee message of type 'devInterview' with data '"0x00158d000202bb30"'
  zigbee2mqtt:warn 2019-1-3 20:36:34 Message without device!
  zigbee2mqtt:debug 2019-1-3 20:36:35 Received zigbee message of type 'devInterview' with data '"0x00158d000202bb30"'
  zigbee2mqtt:warn 2019-1-3 20:36:35 Message without device!
  zigbee2mqtt:debug 2019-1-3 20:36:35 Received zigbee message of type 'devInterview' with data '"0x00158d000202bb30"'
  zigbee2mqtt:warn 2019-1-3 20:36:35 Message without device!
  zigbee2mqtt:debug 2019-1-3 20:36:35 Received zigbee message of type 'devIncoming' with data '"0x00158d000202bb30"' of device 'CSW_ADUROLIGHT' (0x00158d000202bb30)
  zigbee2mqtt:info 2019-1-3 20:36:35 Device incoming...
  zigbee2mqtt:info 2019-1-3 20:36:35 MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"device incoming"}'
  zigbee2mqtt:debug 2019-1-3 20:36:35 Received zigbee message of type 'devStatus' with data '"online"' of device 'CSW_ADUROLIGHT' (0x00158d000202bb30)
  zigbee-shepherd-converters:devices Configured '(cb) => device.write('ssIasZone', 'iasCieAddr', coordinator.device.getIeeeAddr(), cb)' with result 'OK' +7s
  zigbee-shepherd-converters:devices Configured '(cb) => device.functional('ssIasZone', 'enrollRsp', {enrollrspcode: 0, zoneid: 23}, cb)' with result 'OK' +603ms
  zigbee2mqtt:info 2019-1-3 20:36:37 Succesfully configured 0x00158d000202bb30 0x00158d000202bb30
  zigbee2mqtt:debug 2019-1-3 20:36:37 Received zigbee message of type 'devChange' with data '{"cid":"ssIasZone","data":{"zoneState":1,"zoneStatus":32,"zoneId":23}}' of device 'CSW_ADUROLIGHT' (0x00158d000202bb30)
  zigbee2mqtt:debug 2019-1-3 20:36:37 Received zigbee message of type 'devChange' with data '{"cid":"ssIasZone","data":{"zoneState":1,"zoneStatus":32,"zoneId":23}}' of device 'CSW_ADUROLIGHT' (0x00158d000202bb30)

Seems to have paired ok so then activate it:

  zigbee2mqtt:debug 2019-1-3 20:38:28 Received zigbee message of type 'statusChange' with data '{"cid":"ssIasZone","zoneStatus":32}' of device 'undefined' (0x00124b0018ed35a7)
  zigbee2mqtt:info 2019-1-3 20:38:28 New device with address 0x00124b0018ed35a7 connected!
  zigbee2mqtt:info 2019-1-3 20:38:28 MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":"0x00124b0018ed35a7"}'
  zigbee2mqtt:warn 2019-1-3 20:38:28 Device with modelID 'undefined' is not supported.
  zigbee2mqtt:warn 2019-1-3 20:38:28 Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
  zigbee2mqtt:debug 2019-1-3 20:38:28 Received zigbee message of type 'statusChange' with data '{"cid":"ssIasZone","zoneStatus":32}' of device 'CSW_ADUROLIGHT' (0x00158d000202bb30)
/opt/zigbee2mqtt/lib/extension/deviceReceive.js:56
                return c.cid === cid && c.type === message.type;
                         ^

TypeError: Cannot read property 'cid' of undefined
    at mappedDevice.fromZigbee.filter (/opt/zigbee2mqtt/lib/extension/deviceReceive.js:56:26)
    at Array.filter (<anonymous>)
    at DeviceReceive.onZigbeeMessage (/opt/zigbee2mqtt/lib/extension/deviceReceive.js:54:52)
    at extensions.filter.forEach (/opt/zigbee2mqtt/lib/controller.js:112:31)
    at Array.forEach (<anonymous>)
    at Controller.onZigbeeMessage (/opt/zigbee2mqtt/lib/controller.js:112:14)
    at Zigbee.onMessage (/opt/zigbee2mqtt/lib/zigbee.js:173:18)
    at emitOne (events.js:116:13)
    at ZShepherd.emit (events.js:211:7)
    at ZShepherd.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-shepherd/lib/shepherd.js:137:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.0.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@1.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-03T20_38_28_599Z-debug.log


Ii seems to be picking up a different device address somehow.

**Comment by Koenkk** [comment]
Did you do a `rm -rf node_modules && npm install`?

**Comment by arcsyst** [comment]
I deleted the whole zigbee2mqtt folder and started again

**Comment by Koenkk** [comment]
Did you make some manual changes afterwards?

**Comment by arcsyst** [comment]
TBH I was struggling getting anything to pair and flailed around a bit, I now have a smart socket acting as a router could that affect anything? Happy to start over, what's the best way to proceed? Presumably I keep my devices.js?

**Comment by Koenkk** [comment]
Tha shouldnt be a problem, can you start over? (without manual changes)

**Comment by Koenkk** [comment]
The problem probably is your devices.js, how does the section look that you added?

**Comment by arcsyst** [comment]
[devices.zip](https://github.com/Koenkk/zigbee-shepherd-converters/files/2726852/devices.zip)

**Comment by Koenkk** [comment]
Support for this device has been added in https://github.com/Koenkk/zigbee-shepherd-converters/pull/198

**Comment by highground88** [comment]
#https://github.com/Koenkk/zigbee2mqtt/issues/176

Appears to be the same hardware but different model/brand name....  As more of these start appearing it might be easy to use the same handlers once they are finalised.
