### ISSUE TITLE
TuYa switches not working on the latest version

### ISSUE THREAD

**Issue by julioyg** [Koenkk/zigbee-herdsman-converters#1781]
Hi there, 
I've pulled the latest changes from master and none of my switches seem to work, I have pulled this from the logs, I hope it means something 😅 

```
Error: Cluster with key 'manuSpecificTuya' does not exist
zigbee2mqtt      |     at Object.getCluster (/app/node_modules/zigbee-herdsman/dist/zcl/utils.js:60:15)
zigbee2mqtt      |     at Endpoint.<anonymous> (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:397:39)
zigbee2mqtt      |     at Generator.next (<anonymous>)
zigbee2mqtt      |     at /app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:27:71
zigbee2mqtt      |     at new Promise (<anonymous>)
zigbee2mqtt      |     at __awaiter (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:23:12)
zigbee2mqtt      |     at Endpoint.command (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:396:16)
zigbee2mqtt      |     at sendTuyaDataPoint (/app/node_modules/zigbee-herdsman-converters/converters/toZigbee.js:45:18)
zigbee2mqtt      |     at sendTuyaDataPointBool (/app/node_modules/zigbee-herdsman-converters/converters/toZigbee.js:70:11)
zigbee2mqtt      |     at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/converters/toZigbee.js:2811:19)
```

I wish I knew were to start looking... 
also apologies if this is under you radar already, I haven't seen it

**Comment by julioyg** [comment]
nvm, I was using an old version of zigbee2mqtt

**Comment by julioyg** [comment]
so... it's not the case anymore using `zigbee2mqtt:1.16.1` but now I see an awful lot of messages of the type `igbee2MQTT:debug 2020-11-19 14:41:11: Received Zigbee message from ` and when I click a switch it takes a lot more time than before to take effect. 

I'm using a conbee 2 adapter.

is there anything else I'm missing?

**Comment by Koenkk** [comment]
Probably due to https://github.com/Koenkk/zigbee-herdsman-converters/pull/1742, the latest zigbee-herdsman-converters is not compatible with zigbee2mqtt 1.16.1 (specifically the used zigbee-herdsman version in 1.16.1)

To update to the latest zigbee-herdsman-converters switch to the dev branch instead: https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html

**Comment by julioyg** [comment]
that did the trick, thanks, just so I now for the next time, is there anywhere in the readme file I can see the versions that are compatible?

**Comment by Koenkk** [comment]
@julioyg this is not tracked (and would be very time consuming and error prone to do). Just make sure that you are always on the latest dev branch.
