### ISSUE TITLE
Add new manufacturerName for Tuya TS011F

### ISSUE THREAD

**Issue by Nephiel** [Koenkk/zigbee-herdsman-converters#1783]
I just got this one working, Silvercrest 3-gang switch power strip with 4 USB ports. It was already on devices.js:
`        fingerprint: [{modelID: 'TS011F', manufacturerName: '_TZ3000_wzauvbcs'}],`
but manufacturerName didn't match what my device reported, in my case `manufacturerName` was `_TZ3000_1obwwnmq`.

**Comment by Koenkk** [comment]
Added.
