### ISSUE TITLE
Add new device: Gledopto GL-FL-005TZS

### ISSUE THREAD

**Issue by lamosty** [Koenkk/zigbee-herdsman-converters#1787]
Hi.

Could you please add a new device Gledopto GL-FL-005TZS? It's basically the same as GL-FL-005TZ but the "plus" version. I don't think it has any different features from the non-plus one. To make it work, I just add the following to `devices.json`:

```
    {
        zigbeeModel: ['GL-FL-005TZS'],
        model: 'GL-FL-005TZ',
        vendor: 'Gledopto',
        description: 'Zigbee 30W floodlight RGB CCT',
        extend: gledopto.light_onoff_brightness_colortemp_colorxy,
    },
```

However, every time I update zigbeee2mqtt, my custom config gets removed. That's why it would be great if you could add it to the list of devices.

Thanks!

**Comment by Koenkk** [comment]
Added, thanks
