### ISSUE TITLE
integrate "Sonoff ZBMINI" fully

### ISSUE THREAD

**Issue by numberdotone** [Koenkk/zigbee-herdsman-converters#1790]
The Sonoff ZBMINI is already available in the devices.js:

`{
        zigbeeModel: ['01MINIZB'],
        model: 'ZBMINI',
        vendor: 'SONOFF',
        description: 'Zigbee two way smart switch',
        extend: generic.switch,
    },`

If I want to integrate it into iobroker a "not described in statesMapping" appears, as in [https://notenoughtech.com/home-automation/sonoff-zb-mini-and-zigbee2mqtt/] (https://notenoughtech.com/home-automation/sonoff-zb-mini-and-zigbee2mqtt/) mentioned. There is also additional information, which I manually add to the devices.js:
	
`{
        zigbeeModel: ['01MINIZB'],
        model: 'Sonoff ZB Mini',
        vendor: 'Sonoff',
        description: 'Smart switch - 1 gang, 3.3V switch logic',
        supports: 'on/off',
        fromZigbee: [fz.on_off],
        toZigbee: [tz.on_off],
    },`

This doesn't work, maybe while I have to re-pair the device again.

Anything else to consider to make the ZBMINI work?

**Comment by kirovilya** [comment]
@numberdotone This is a iobroker.zigbee problem. Support will be available in the next version

**Comment by numberdotone** [comment]
Thx for clarification. And for all the good work and time you spend on it.
