### ISSUE TITLE
Request for support for Silvercrest HG06467 (Lidl)

### ISSUE THREAD

**Issue by MichielMag** [Koenkk/zigbee-herdsman-converters#1792]
I recently bought the christmas lights and I'm trying to add them to Z2M but I'm a bit stuck.
My first try is the following in devices.js:
```    {
        fingerprint: [
            {modelID: 'TS0601', manufacturerName: '_TZE200_s8gkrkxk'}
        ],
        model: 'HG06467',
        vendor: 'Silvercrest',
        description: 'Smart LED string lights',
        supports: 'on/off, color (hue/saturation), brightness, color_temp',
        toZigbee: [tz.on_off, tz.tuya_led_control],
        fromZigbee: [fz.on_off, fz.tuya_led_controller, fz.brightness, fz.ignore_basic_report],
        exposes: [e.light_brightness_colortemp_colorhs()],
    },
```

That does seem to give me the functionality to turn it off and on, but that's it. I'm also interested in changing the colors and especially using the scenes.

I've sniffed out the messages from the Lidl gateway, but I have no idea how to implement this as converters. 
These are my notes: https://pastebin.com/pcgWVjCp

**Comment by Koenkk** [comment]
Try with:

```js
{
    fingerprint: [{modelID: 'TS0601', manufacturerName: '_TZE200_s8gkrkxk'}],
    model: 'HG06467',
    vendor: 'Silvercrest',
    description: 'Smart LED string lights',
    extend: generic.light_onoff_brightness_colortemp_colorxy,
},
```

**Comment by MichielMag** [comment]
Same effect. I have a feeling that the lights are in an effect mode. Whenever I try to change the color it flashes real quick in random patterns, possibly like the scene that is in effect.

I've seen that the Lidl gateway always first sends a mode change command `00 01	02 04 00 01 01` Where 02 04 is the function and the 01 in the end means color mode.

This is my first time doing anything with zigbee so it could be that I'm bringing old news.

**Comment by Koenkk** [comment]
Seems they use proprietary commands for this device, making it a lot more difficult to add support for. This is a white label TuYa device, I don't have experience myself with this but someone wrote a guide for it: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_tuya_devices.html

**Comment by MichielMag** [comment]
I get it now, thanks. Got it working (colors and scenes/effects) now roughly. I'll make sure to fit it into the code standards of the rest of the software and then make a pull request.

**Comment by Koenkk** [comment]
Off topic: did you buy these at Lidl in the Netherlands?

**Comment by MichielMag** [comment]
I did, yes. For some reason I received them super early a few days back.

**Comment by MichielMag** [comment]
Currently trying to figure out how they do color / brightness. This is what I sniffed from the gateway, but I can't seem to figure it out. My first guess was 4 bytes for Hue, 4 bytes  for Saturation and 4 bytes for Brightness, but the values don't seem to make sense to me for now.

```
Color green 100:
30 30 36 39 30 33 65 38 30 33 65 38

Color red 100:
30 31 35 66 30 33 65 38 30 33 65 38

Color red 1:
30 31 35 66 30 33 65 38 30 30 30 61

Color blue 1:
30 30 64 62 30 33 65 38 30 30 30 61

Color blue 100:
30 30 64 62 30 33 65 38 30 33 65 38
```

**Comment by MichielMag** [comment]
I made a pull request for this issue:
https://github.com/Koenkk/zigbee-herdsman-converters/pull/1799

**Comment by MichielMag** [comment]
Pull request is merged so this issue is resolved.

**Comment by Hedda** [comment]
Does anyone have much better pictures of the Christmas lights themselves and all their control/power-adapters to help a search Chinese online stores in China for a product that use the same internals so people in any country can order directly from China?

https://www.lidl.de/de/melinera-lichterkette-zigbee-smart-home/p360021

https://www.lidl.nl/nl/p/smart-home/200-rgb-led-verlichtingsketting/p43246

It sounds like most if not all of Lidl's Zigbee products are rebranded OEM or while-label version devices that are actually manufactured by Tuya or others in China, so thinking that for people not living in Europe it might be easiest to find the same product sold under a different brand from a Chinese online store and order it to the USA directly from China?

Just a few other companies who are known for rebranding and selling at least a couple OEM or while-label Zigbee devices (and WiFi devices) from example Tuya and HEIMAN are Zemismart, Alecto, Bandi, Binthen, Blitzwolf, Malmbergs, Gosund, Eachen, Moes, Sonoff, Teckin, Earda, LEELKI, Larkkey, Lonsonho, LoraTa, Norklmes, SHOJZJ, Samotech, Smart9, Somgoms, TUYATEC, UseeLink, Vrey, Woox, Yushun, and CR Smart Home,

Many such rebranded OEM or while-label Zigbee devices manufactured by Tuya can be found in zigbee2mqtt and deconz lists:

https://www.zigbee2mqtt.io/information/supported_devices.html

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Supported-Devices

**Comment by Hedda** [comment]
Slightly off-topic, love the Twinkly app concept of using the phone's camera to AR 3D mapping similar Christmas light strings:

https://www.twinkly.com/knowledge/map-your-lights-2/

Twinkly's app uses Augmented-Reality together with your phone's camera to first 3D map each and every lightbulb in the Christmas light string and then let you "paint" each and every one of those lightbulbs individually with their app on your phone.

https://www.youtube.com/watch?v=xMJ3bLBtGaQ&ab_channel=Twinkly-SmartDecoration

**Comment by MichielMag** [comment]
> 
> 
> Slightly off-topic, love the Twinkly app concept of using the phone's camera to AR 3D mapping similar Christmas light strings:

Yea sadly that will never be possible for the Lidl lights. They don't offer any support for manually controlling a single light.

**Comment by Hedda** [comment]
> > Slightly off-topic, love the Twinkly app concept of using the phone's camera to AR 3D mapping similar Christmas light strings:
> 
> Yea sadly that will never be possible for the Lidl lights. They don't offer any support for manually controlling a single light.

Not unless you hack and flash your own Zigbee application firmware on the Zigbee SoC that they use you mean? :P

**Comment by fidel1986** [comment]
@MichielMag did you have problems join led strip to zigbee network? I am not able to pair it.
I tried different systems cubie, rpi4, different cc2531 with different versions, extension cable. Manual confusing me a little bit because reset and pairing of led strip looks not really different.
If i am close to pair i got interview_failed messages. I have already restarted z2m, stickunplug and clean files.

**Comment by MichielMag** [comment]
Hey Fidel,

First of: this is the LED string, which is not a LED strip.
If that is what you mean: are you up-to-date? I'm not sure if it's in the master branch yet, so maybe you'll have to switch to the dev branch.

https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html

**Comment by 26tajeen** [comment]
Also having trouble pairing the Lidl/Tuya LED - keeps just saying interview failed despite the fact I've reset it (by power cycling three times) and it's RIGHT next to the CC2531. Any tips?!

**Comment by smithnick** [comment]
Has this HG06467 Christmas light string been discontinued? I can’t seem to find it in stock

**Comment by MichielMag** [comment]
Like most of their zigbee devices, it seems a one time device with zero support, sadly.
