### ISSUE TITLE
[Device Added] HG06336 Silvercrest (Lidl) Smart Window or Door Sensor

### ISSUE THREAD

**Issue by Electr1fying** [Koenkk/zigbee-herdsman-converters#1814]
Hi Koenkk!

Managed to add the Lidl Door Sensor to Z2M, tried to do a pull request to put up the changes for merge, but i've never done this before. Combined with a few errors when trying to upload the changes to my forked repo, i have no clue how to get them to you.

Any ideas? 

Thanks!

**Comment by Koenkk** [comment]
If you post your addition to devices.js here I can add it.

**Comment by Electr1fying** [comment]
Thanks, here it is!

``{
        fingerprint: [{modelID: 'TY0203', manufacturerName: '_TZ1800_ejwkn2h2'}],
        model: 'HG06336',
        vendor: 'Silvercrest',
        description: 'Door sensor',
        fromZigbee: [fz.ias_contact_alarm_1, fz.battery, fz.ignore_basic_report, fz.ias_contact_alarm_1_report],
        toZigbee: [],
        exposes: [e.contact(), e.battery_low(), e.tamper(), e.battery()],
    },`

**Comment by allofmex** [comment]
Seems we worked in parallel :-)
Here a PR for same device
https://github.com/Koenkk/zigbee-herdsman-converters/pull/1818

**Comment by Electr1fying** [comment]
Haha indeed. Hope your merge doesn't conflict with mine. (As in that i have already configured everything within Z2M and Domoticz). :)

**Comment by Koenkk** [comment]
Supported now.
