### ISSUE TITLE
Support for Silvercrest door sensor TY0203 (Lidl door sensor)

### ISSUE THREAD

**Issue by bokse001** [Koenkk/zigbee-herdsman-converters#1824]
Link whre i bought the device: https://www.lidl-shop.nl/SILVERCREST-Deur-en-raamsensor-Zigbee-Smart-Home/p100306595

This did the trick so it gets paired:
 {
		    fingerprint: [{modelID: 'TY0203', manufacturerName: '_TZ1800_ejwkn2h2'}],
	    	model: 'HG06336',
			vendor: 'Silvercrest',
			description: 'SilverCrest door & window contact sensor',
			fromZigbee: [fz.ias_contact_alarm_1_report, fz.ias_contact_alarm_1],
			toZigbee: [],
    		exposes: [e.battery(), e.battery_low(), e.contact(), e.tamper()],
	},

**Comment by Koenkk** [comment]
Thanks but the device is already supported in the latest dev branch (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by VincentSC** [comment]
I'm not getting any event for opening/closing. Only battery and signal strength. What could be wrong?

**Comment by HelmutD47259** [comment]
@Koenkk 

i'm getting the wrong device in zigbee2mqtt for my LIDL HG0335 from _TZ1800_ejwkn2h2. It is recognices as HG06336.

        "applicationVersion": 65,
        "dateCode": "2019.12.12",
        "friendlyName": "xxxxxxxxxxxxx",
        "hardwareVersion": 1,
        "ieeeAddr": "0xbc33acfffe363488",
        "manufacturerID": 4619,
        "manufacturerName": "_TZ1800_ejwkn2h2",
        "model": "HG06336",
        "networkAddress": 19752,
        "powerSource": "Battery",
        "stackVersion": 2,
        "type": "EndDevice",
        "zclVersion": 1

**Comment by Koenkk** [comment]
Refer to the [documentation](https://www.zigbee2mqtt.io/advanced/support-new-devices/02_support_new_tuya_devices.html#fixing-tuya-device-detection) to fix device detection issues.
