### ISSUE TITLE
Lidl ceiling 3 LEDs light bulbs (TuYa TS0502A)

### ISSUE THREAD

**Issue by SargonofAssyria** [Koenkk/zigbee-herdsman-converters#1830]
Please add: see: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/487
There manufacturerName is_TZ3000_el5kt5im
Productpage: https://www.lidl.nl/nl/p/smart-home/led-plafondlamp/p43250

**Comment by itavero** [comment]
@SargonofAssyria It seems that you own this device?

Have you tried following the steps described in [How to support new devices](https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html)?

**Comment by SargonofAssyria** [comment]
No I do not own the device any more. I did bring it back to Lidl and got my money back.
So I did not pursue those steps. But others might benefit by including the device.
