### ISSUE TITLE
Philips Hue LWA011 is the same as LWW003

### ISSUE THREAD

**Issue by NikolayBorisov** [Koenkk/zigbee-herdsman-converters#1844]
LWA011 not supported.

Philips Hue E27 2700K 9W
929001821618
LWA011

Just add it to zigbeeModel

`{
        zigbeeModel: ['LWW003', 'LWA011'],
        model: '9290018216',
        vendor: 'Philips',
        description: 'Hue white A60 bulb E27 bluetooth',
        meta: { turnsOffAtBrightness1: true },
        extend: hue.light_onoff_brightness,
        ota: ota.zigbeeOTA,
    },`

**Comment by Koenkk** [comment]
Added, thanks!
