### ISSUE TITLE
connecting TuYa TS0201 (or similar)

### ISSUE THREAD

**Issue by aelray** [Koenkk/zigbee-herdsman-converters#1851]
Hi,

I bought these wall thermostats from aliexpress:

[link](https://www.aliexpress.com/item/4000768249629.html)

I though they would be those:

[link](https://www.zigbee2mqtt.io/devices/TS0201.html)

But zigbee2MQTT doesn't seem to recognize them, and I get the following message:

```
Zigbee2MQTT:warn  2020-12-04 20:41:29: Received message from unsupported device with Zigbee model 'undefined' and manufacturer name '_TZ2000_a476raq2'
Zigbee2MQTT:warn  2020-12-04 20:41:29: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
Zigbee2MQTT:warn  2020-12-04 20:41:29: Received message from unsupported device with Zigbee model 'undefined' and manufacturer name '_TZ2000_a476raq2'
Zigbee2MQTT:warn  2020-12-04 20:41:29: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
```

Is there an easy way to make zigbee2MQTT identify them as the Tuya models? I think they should be identical/compatible.

BR,

Adel

**Comment by guguxfr** [comment]
Same issue here, can't connect it to zigbee2mqtt gateway.

**Comment by guguxfr** [comment]
Ok, I managed to solve the issue.

First, you must add a section in devices.js :

    {
        fingerprint: [{modelID: 'undefined', manufacturerName: '_TZ2000_a476raq2'}],
        model: 'TS0201_compatible',
        vendor: 'TuYa',
        description: 'Temperature & humidity sensor with display',
        supports: 'msTemperatureMeasurement,msRelativeHumidity',
        fromZigbee: [fz.battery, fz.temperature, fz.humidity],
        toZigbee: [],
        exposes: [e.battery(), e.temperature(), e.humidity()],
    },

Then ensure that your device is pairing. To get this to work, I had to remove the device from database.db and (the most important I think), after reading the page about unsuccessfull pairings, I replaced the batteries of the device.

After a restart of zigbee2mqtt all went well.

Maybe I could do a PR for this device ? Please tell me if it's of interest.

**Comment by Koenkk** [comment]
@guguxfr added, thanks!

**Comment by guguxfr** [comment]
Excellent ! You're welcome.

**Comment by Koenkk** [comment]
@guguxfr are you sure this works, @sjorge noticed (https://github.com/Koenkk/zigbee-herdsman-converters/commit/837864ed7dabbfa68b90a2e42c1e112cbc844bae#r44857557) that model ID is 'undefined' as string here, I would expect it to be `undefined` (not a string).

**Comment by guguxfr** [comment]
Indeed I agree this is confusing.
Here is an extract of my log : 

Received message from unsupported device with Zigbee model 'undefined' and manufacturer name '_TZ2000_a476raq2'

So it seems like a string to me :)

**Comment by Koenkk** [comment]
Ah that looks confusing indeed, but it's not a string in this case. Updated the entry.

**Comment by guguxfr** [comment]
Ah ok, sorry about that.
