### ISSUE TITLE
BHT-002-GCLZB Floods with identical messages

### ISSUE THREAD

**Issue by asgothian** [Koenkk/zigbee-herdsman-converters#1854]
Hello,

i have been testing a BHT-002-GCLZB room thermostat for a while now. Overall, it is a nice device and seems to work reasonably well, but it does flood the controller with near identical messages.

I found chains of 50 messages within 2.5 s (roughly 50 ms between two messages) with a payload with is identical save for the 'transid' entry, which increases by one for each message (as it must, as far as i understand the protocol)

I have seen this happen with two messages, one reporting the 'current_heating_setpoint', the other one reporting the 'heat' setpoint.

Any suggestions on how to stop this flood of messages to reach the application ?

I have attached 2 files below - one a raw Log file from the application, run for about 1 minute and a second where i edited the log to only show the message and the effect it has on the application.

An ideal way would be if we could somehow stop this flood on the device, but seeing that it is a TuYa based design i have low hope of that. Is there any way for the converters to drop the repeat messages ?

I have been playing around with storing the message id and checking against the previous to block the repeat messages in the converter, but that is rather late in the chain, and i was wondering if there was a better way to do this.

The code i added was this (inside the moesThermostat function, and of course the lastMoesThermostatMessage variable is defined globally)

`    
if (lastMoesThermostatMessage && lastMoesThermostatMessage.dp == dp) {
      lastMoesThermostatMessage = msg.data;
      return;
    }
    lastMoesThermostatMessage = msg.data;
`

[Zigbee_Log_edited.txt](https://github.com/Koenkk/zigbee-herdsman-converters/files/5647048/Zigbee_Log_edited.txt)
[Zigbee_Log_raw.txt](https://github.com/Koenkk/zigbee-herdsman-converters/files/5647049/Zigbee_Log_raw.txt)

**Comment by insipiens** [comment]
yes, this device's firmware sends in excess of 30 messages each time. Why? when I was analysing this to incorporate it into Z2M I concluded it was because the time lapse between the published message starting a response and the internal relay being activated/switched was the reason - there's a lag of maybe 1 or 2 seconds...however not a great software design by Moes/Tuya, but as you already alluded to that isn't a great surprise.

There is already an option in Z2m you could use to suppress extraneous messages: _debounce_


`
debounce: Debounces messages of this device. When setting e.g. debounce: 1 and a message from a device is received, Zigbee2MQTT will not immediately publish this message but combine it with other messages received in that same second of that device. This is handy for e.g. the WSDCGQ11LM which publishes humidity, temperature and pressure at the same time but as 3 different messages.`

details from this page: https://www.zigbee2mqtt.io/information/configuration.html#all-devices

I tried this myself but found that it did occasionally exclude the changed status so decided to not use it, or mention it.

Give it a try, I might have not chosen the best setting when testing it. Perhaps you can find the sweet-spot?

Would be great if it works as monitoring other devices when tailing the log is hampered by this device's spamming so many messages.

**Comment by AndrelaS** [comment]
Hello. I have Raspberry Pi 4 with HassOS 4.17 + Home Assistant 0.118.5 + Zigbee2mqtt 1.16.2.2 on board. I connect BHT-002-GBLZBW and get flooding message from it.
Trying add to _configuration.yaml_ folowing lines have no effect:
```
devices:
  '0x5c0272fffed75175':
    friendly_name: 'floor_thermostat'
    debounce: 1
```
BTW, in Z2M thermostat detected as BHT-002-GCLZB, I can't see floor temperature, only air temperature.

In Configuration check I get _Component error: devices - Integration 'devices' not found._

How can I solve flooding and add floor temp. (or replace air temp., for floor heating thermostat more important floor temp)?
Please help. Thanks.

> yes, this device's firmware sends in excess of 30 messages each time. Why? when I was analysing this to incorporate it into Z2M I concluded it was because the time lapse between the published message starting a response and the internal relay being activated/switched was the reason, the HEAT setting changes within the 30+ messages, there's a lag of maybe 1 or 2 seconds...however not a great software design by Moes/Tuya, but as you already alluded to that isn't a great surprise.
> 
> There is already an option in Z2m you could use to suppress extraneous messages: _debounce_
> 
> ` debounce: Debounces messages of this device. When setting e.g. debounce: 1 and a message from a device is received, Zigbee2MQTT will not immediately publish this message but combine it with other messages received in that same second of that device. This is handy for e.g. the WSDCGQ11LM which publishes humidity, temperature and pressure at the same time but as 3 different messages.`
> 
> details from this page: https://www.zigbee2mqtt.io/information/configuration.html#all-devices
> 
> I tried this myself but found that it did occasionally exclude the changed status so decided to not use it, or mention it.
> 
> Give it a try, I might have not chosen the best setting when testing it. Perhaps you can find the sweet-spot?
> 
> Would be great if it works as monitoring other devices when tailing the log is hampered by this device's spamming so many messages.

**Comment by insipiens** [comment]
Like I say I let the device send all its messages, that is how they designed it to work. So, unless you need to exclude them I wouldn't worry about it.

To change the temperature source you need to publish a message to the device 

topic would be, in your case: `zigbee2mqtt/floor_thermostat/set/sensor ` 

values options are 1,2,3 where 1 is the internal ntc sensor. I'm not sure whether 2 or 3 is the floor sensor but I guess you will find out by using 2 and 3.

**Comment by AndrelaS** [comment]
For BHT-002-GBLZBW topic _.../sensor_: 0 - IN, 1 - AL, 2 - OU

**Comment by asgothian** [comment]
Seems this is known and not fixable. I made an attempt to reach technical people at the manufacturer but was not successful. Closing the issue.

**Comment by RoGu777** [comment]
Hi all,

I had the same problem with my GIRIER BHT-006 Thermostat.

I've just received a message from Aliexpress shop, that there is a new firmware, which should fix the flooding issue.
I've attached the file, but I have no idea how to update.

How can new firmware be flashed to the device?

[006_CA51F253L3.zip](https://github.com/Koenkk/zigbee-herdsman-converters/files/13920926/006_CA51F253L3.zip)

**Comment by chatoooo** [comment]
Hi, I'm dealing with the same issue. The firmware posted above is in Intel HEX format. OTA files are binary. Has anyone tried to OTA update the thermostat? Does it even support OTA? It might be possible to flash the memory physically, but it is not something I'm looking forward to doing 😄

**Comment by sasswaz** [comment]
From Z2MQTT web interface I opened the device, in Settings tab set ``1`` for ``debounce`` and ``action`` for ``debounce_ignore`` and the flooding stopped.

**Comment by RoGu777** [comment]
this only stops flooding with MQTT messages, ZigBee messages are still sent by the device, which floods the ZigBee network

**Comment by pcrednet** [comment]
I have an installation with several devices like this, and it is impossible to put more than 5. The amount of messages it sends per second makes zigbee2mqtt totally unusable.

Is there any way to limit the number of messages? 
I'm setting up 33 on 7 different networks to be able to use it....

The same thing happens with another smart air quality.... totally unusable. I can't have more than 10 devices, with more, it's totally unstable.
I have tried with Debounce: 1, 5, 10.... 50... and the same. Moreover, the higher the value, the longer it takes to deliver the message when you act on the thermostat.
Is there no possible solution?

Translated with DeepL.com (free version)

**Comment by insipiens** [comment]
Not really, chinese programming. I got rid of mine and implemented a virtual alternative using esp32 devices.

Suggest you find a more refined product if you’re planning on using more than one….sorry, not what one wants to hear.☹️

**Comment by asgothian** [comment]
> Is there no possible solution?

I did try to talk to the manufacturer to tell them what the issue was, but never managed to explain it well enough so that they would be even willing to accept that there is an issue. So yes, I don't see a solution either and I removed the device from my network

A.

**Comment by pcrednet** [comment]
I have a network with 33 devices like this and another 33 moes bht-002 devices with the same problem.
In the end, we had to delay the project to get other thermostats and other co2 sensors.
A real pity, I would put that product as unsupported; it is worse to see that it is supported and at the moment of truth to see that you can not use it.
