### ISSUE TITLE
UK Lidl Silvercrest TS011F (HG06337-BS) Smart Socket

### ISSUE THREAD

**Issue by mattheys** [Koenkk/zigbee-herdsman-converters#1863]
Looks like the UK version of the Lidl Silvercrest TS011F smart socket has a manufacture ID of _TZ3000_00mk2xzy, I tried to create a pull request but the devices.js is too big for me to do it in browser and I'm not comfortable doing it via command line. I updated my own config file and it worked fine.

https://zigbeealliance.org/zigbee_products/lidl-home-smart-plug/

```
    {
        fingerprint: [{modelID: 'TS011F', manufacturerName: '_TZ3000_00mk2xzy'}],
        model: 'HG06337-BS',
        vendor: 'Silvercrest',
        description: 'Smart Plug',
        extend: generic.switch,
    }
```

Also do you want a photo or any other details for the website?

Can I also make a suggestion about having a seperate devices.json file that can be merged with the main one so that docker users of zigbee2mqtt can map that separatly and have a custom file and still benefit from updates to the docker image.

**Comment by Koenkk** [comment]
Added, thanks, no additional actions required from your side.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
