### ISSUE TITLE
Adding support for Saswell SEA801-Z01 - working

### ISSUE THREAD

**Issue by awaldram** [Koenkk/zigbee-herdsman-converters#1878]
Hi,

ordered some SEA801-Zigbee from Amazon what arrived is labled SEA801-Z01 and has a different ID and Model but is visually an identical part.

Assuming it was just a Variant changed added 

{modelID: 'TS0601', manufacturerName: '_TZE200_c88teujp'},

To the fingerprint stanza of the SEA801-Zigbee and it works no issues and no rogue data points so this could be added to support this I guess newer firmware.
Given such a small change could it be added to master .?

**Comment by Koenkk** [comment]
This device is already supported in the latest dev branch (will be recognised as SEA802-Zigbee). (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by awaldram** [comment]
HI Koenkk

Checking the push requests I do not see the addition of this TRV under 802
The closest it
https://github.com/Koenkk/zigbee-herdsman-converters/pull/1650#pullrequestreview-506669844

But that is not the same fingerprint or device , clearly they are probably physically related but firmware is different and will not be detected as an 802 (which is good as its clearly marked 801)

Adding my fingerprint to the 801 Stanza gets it correctly identified and working as a SEA801 derrivatrive.

**Comment by Koenkk** [comment]
It's here: https://github.com/Koenkk/zigbee-herdsman-converters/blob/93c58b09d305e862e199972871ce60910030110b/devices.js#L13817
