### ISSUE TITLE
Exposes information for Silvercrest HG06467 seems incorrect

### ISSUE THREAD

**Issue by itavero** [Koenkk/zigbee-herdsman-converters#1886]
According to the exposes information the Silvercrest HG06467 will publish its color as `{ "color": { "hue": xxx, "saturation": xxx } }`.
However, this is not what it is publishing in my setup (nor what I see in the actual converters for this device):
`{"brightness":124.95,"color":{"b":124.95,"h":204,"s":67},"effect":null,"last_seen":"2020-12-10T08:38:40+01:00","linkquality":78,"state":"ON"}`

**Comment by Koenkk** [comment]
@MichielMag  can you look at this? I think we should also return `hue` and `saturation` in the set converter.

**Comment by MichielMag** [comment]
So just replace 'h' and 's' with 'hue' and 'saturation' in the state?
https://github.com/Koenkk/zigbee-herdsman-converters/blob/0f2334a90d61742545343b8c14b57360170d1d52/converters/fromZigbee.js#L5897

**Comment by itavero** [comment]
I would say `brightness` needs to move up a level as well, in order for it to match what is in the `exposes` information.

**Comment by MichielMag** [comment]
The problem here is that this device uses two different brightness values. One for white light and one for colored light. The brightness it receives there is the brightness for colored mode and is really part of the HSB.

But, we do put that brightness in the state.brightness as well though.

**Comment by itavero** [comment]
I was wondering why I wasn't able to set the white color correctly, but for that I should only send a set with the `brightness` key then?

Interesting. I'm not sure how this can/should be expressed correctly in the `exposes` information though. (at least to me it sounds that the problem is not so much with the converters, but more with the information in the `exposes` that doesn't reflect how the different keys should be used).
Maybe we should consider it as two "endpoints" within the device: one light that only has the `brightness` and another one that has the `brightness` and `color` with `hue` and `saturation`, but that would also influence the converters.

**Comment by MichielMag** [comment]
Yes, I was also wondering how to solve that problem. The problem would be solved if the device supported white color temperature as the box says.
Two endpoints would also be tricky: do you then set the state off the white endpoint to 'off' when it's in colored mode? And would you expect another endpoint for the effects?

Also: yes, sending just the brightness resets it to white.

**Comment by itavero** [comment]
I think I would indeed expect the white endpoint to go off if the color is on and vice versa.
The effects can be part of the color endpoint I guess (not sure if it is required to have an endpoint there).

"Unfortunately" I'm on my work laptop, so I don't have the current `exposes` data at hand, otherwise I would have posted an example of what I would expect there.

**Comment by itavero** [comment]
Forgot to add the proposal I had for the `exposes` data:
```json
{
  "exposes":[
    {
      "endpoint":"rgb",
      "features":[
        {
          "endpoint":"rgb",
          "access":7,
          "description":"On/off state of this light",
          "name":"state",
          "property":"state_rgb",
          "type":"binary",
          "value_off":"OFF",
          "value_on":"ON",
          "value_toggle":"TOGGLE"
        },
        {
          "endpoint":"rgb",
          "access":7,
          "description":"Brightness of this light",
          "name":"brightness",
          "property":"brightness_rgb",
          "type":"numeric",
          "value_max":254,
          "value_min":0
        },
        {
          "endpoint":"rgb",
          "description":"Color of this light expressed as hue/saturation",
          "features":[
            {
              "access":7,
              "name":"hue",
              "property":"hue",
              "type":"numeric"
            },
            {
              "access":7,
              "name":"saturation",
              "property":"saturation",
              "type":"numeric"
            }
          ],
          "name":"color_hs",
          "property":"color_rgb",
          "type":"composite"
        }
      ],
      "type":"light"
    },
    {
      "endpoint":"white",
      "features":[
        {
          "endpoint":"white",
          "access":7,
          "description":"On/off state of this light",
          "name":"state",
          "property":"state_white",
          "type":"binary",
          "value_off":"OFF",
          "value_on":"ON",
          "value_toggle":"TOGGLE"
        },
        {
          "endpoint":"white",
          "access":7,
          "description":"Brightness of this light",
          "name":"brightness",
          "property":"brightness_white",
          "type":"numeric",
          "value_max":254,
          "value_min":0
        }
      ],
      "type":"light"
    }
  ]
}
```

For the effects, I think it can be added with the `rgb` endpoint as well.

**Comment by MichielMag** [comment]
Ah I never knew how the exposing worked but that makes sense.

But as we are splitting up the RGB and white, shouldn't we split effect from RGB as well then? Because the device goes in an actual different mode for all 3 of them.

**Comment by itavero** [comment]
If it's a different mode within the device than that would make sense.
For my own plugin (homebridge-z2m), I don't see a sensible way of exposing the effects to HomeKit, but it might help for other pieces of software that (are going to) use the exposes information.

I hope my proposal is in line with @Koenkk's idea of how the exposes information should be filled in.

**Comment by Koenkk** [comment]
If I understand correctly, the HG06467 only has one endpoint, so how would this work?

**Comment by itavero** [comment]
I consider it to be "virtual" endpoints. If it is "hard linked" to something in the ZigBee protocol, then we need to find another way to provide sensible exposes information for the different modes and the related properties.

**Comment by Koenkk** [comment]
@itavero I see, the definition has to be updated as follows (mapping the endpoints through `endpoints`). However since I don't have this device I don't know if it provides the expected result so please test.

```js
{
    fingerprint: [{modelID: 'TS0601', manufacturerName: '_TZE200_s8gkrkxk'}],
    model: 'HG06467',
    vendor: 'Lidl',
    description: 'Melinera smart LED string lights',
    toZigbee: [tz.on_off, tz.silvercrest_smart_led_string],
    fromZigbee: [fz.on_off, fz.silvercrest_smart_led_string],
    exposes: [e.light_brightness_colorhs()],
    endpoint: (device) => {
        return {'white': 1, 'rgb': 1};
    },
},
```

**Comment by itavero** [comment]
Unfortunately I haven't had the time yet to give this ago, but I think the implementation would also need to change.

The "problem" is that this device has different modes which relate to different properties (but some properties relate to multiple modes if combined with others), but currently there is no way to get this information from the exposes data.
Making it hard (if not impossible) to automatically map this device correctly based on the exposes information.
Right now I'm just ignoring the color and only using the brightness, which at least makes the "white" mode work correctly from my home automation software.

**Comment by itavero** [comment]
PS: "Luckily" it's almost time to take down the Christmas tree 🎄, put these lights in a storage box and not use them again until December. 😅

**Comment by tetsuo55** [comment]
@itavero any updates on this issue for this Christmas?

I'm actually using these lights as a poor man's led strip for accent lighting year round (i got fooled by the individually addressable lights claim when buying it)
