### ISSUE TITLE
Lidl / Silvercrest HG06377 UK (TZ3000_00mk2xzy) shows as Unsupported

### ISSUE THREAD

**Issue by ellnic** [Koenkk/zigbee-herdsman-converters#1894]
I grabbed a Silvercrest HG06377 (BS) today and have been unable to pair it. It looks like it's in the docs, and `TZ3000_00mk2xzy` is in devices.js too.

When attempting to pair, I get this: 

`WARNING: Device '0x842e14fffe50xxxx' with Zigbee model 'undefined' and manufacturer name '_TZ3000_00mk2xzy' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html`

I am running the HA add-on version 1.16.2.2, which is Z2MQTT ver 1.16.2, where support for these was added.

Any ideas what I might be doing wrong?

**Comment by Koenkk** [comment]
Added it.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
