### ISSUE TITLE
BHT-002-GCLZB sensor set and get uses different values ...

### ISSUE THREAD

**Issue by PeterVoronov** [Koenkk/zigbee-herdsman-converters#1905]
Hello, colleagues.

Looking in the code, i see, the FromZigbee the sensor values is returned as a string:
```
    case common.TuyaDataPoints.moesSensor:
        switch (value) {
        case 0:
            return {sensor: 'IN'};
        case 1:
            return {sensor: 'AL'};
        case 2:
            return {sensor: 'OU'};
        default:
            return {sensor: 'Not supported'};
        }
```
But in ToZigbee it uses a numerik values:
```
    // send an mqtt message to topic '/sensor' to change the temperature sensor setting - options [0=IN|1=AL|2=OU]
    moes_thermostat_sensor: {
        key: ['sensor'],
        convertSet: async (entity, key, value, meta) => {
            await sendTuyaDataPointEnum(entity, common.TuyaDataPoints.moesSensor, value);
        },
    },
```
what is version is right?
I'm ready to prepare a PR, but what it better ? 
By my understanding - it have to be identical type of values for in and out

**Comment by Koenkk** [comment]
String is preferred here, but to avoid a breaking change allow both numbers and strings in the toZigbee converter.

**Comment by PeterVoronov** [comment]
Done at [PR](https://github.com/Koenkk/zigbee-herdsman-converters/pull/1912)
