### ISSUE TITLE
Philips Hue model 9290012573A gives 'Failed to setup reporting' in log

### ISSUE THREAD

**Issue by TheStigh** [Koenkk/zigbee-herdsman-converters#1921]
Using Hassio 2020.12.7 with z2m 1.6.2.2 addon.

I can see that all my Philips Hue models 9290012573A constant gives following errors in the log;

`Zigbee2MQTT:error 16-12-2020 16:34:31: Failed to setup reporting for '0x0017880104d303a8' - Error: ConfigureReporting 0x0017880104d303a8/11 genOnOff([{"attribute":"onOff","minimumReportInterval":0,"maximumReportInterval":300,"reportableChange":0}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Timeout - 2165 - 11 - 6 - 6 - 7 after 10000ms)
    at Timeout._onTimeout (/zigbee2mqtt-1.16.2/node_modules/zigbee-herdsman/dist/utils/waitress.js:46:35)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)`

Is there something I can do locally or are this some faulty code in devices.js ?

**Comment by Koenkk** [comment]
Probably your Hue bulb does not support reporting: https://www.zigbee2mqtt.io/information/report.html#support

**Comment by TheStigh** [comment]
I'll test in in my dev and see - it thats the case, I'll make a PR with corrected code 👍
