### ISSUE TITLE
color_temp should be bound to min/max range

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee-herdsman-converters#1928]
As mentioned here https://github.com/Koenkk/zigbee2mqtt/issues/4926#issuecomment-740697631

This is currently not the case, we should update the color_temp convertor to keep this in mind.

I'm not sure what the best way to do this is...

- option a
    - read min/max in device configure and store in meta
    - color_temp converter checks if meta data present, and caps the range according
       - throw error when out of bound (or warning?) || silently use min or max depending which bound we exceeded
- option b
   - color_temp converter read min/max, and caps the range according
       - throw error when out of bound (or warning?) || silently use min or max depending which bound we exceeded

Not sure if this will work and which one is best, I'm leaning more towards A because we do not have to read the range every time. But what if a firmware updates changes the range, we need to run configure again.

What for bulbs that no configure step? Do we add one to read the min/max?

Are there other values we might want to read? I believe we already do so for some of the power measurements, perhaps we need a 'generic' way to query such info similar to configure. Were you just have an extra property with manual configure ranges or a attribute to query to get it, which we then trigger at the end of the configure action.

That would make it easy to read other stuff in the future, but if we want this... is it worth the extra work right now?

**Comment by Koenkk** [comment]
I think the best way to implement this is by doing it similar to e.g. https://github.com/Koenkk/zigbee-herdsman-converters/blob/7623a5855922893e9d47cbad755fc3236fccd794/devices.js#L7773 and then access the values via e.g. https://github.com/Koenkk/zigbee-herdsman-converters/blob/7623a5855922893e9d47cbad755fc3236fccd794/converters/fromZigbee.js#L933

> But what if a firmware updates changes the range, we need to run configure again.

My assumption is that the color temperature depends on the hardware so a firmware update should not change this

**Comment by sjorge** [comment]
```javascript
    light_colortemp: {
        key: ['color_temp', 'color_temp_percent'],
        convertSet: async (entity, key, value, meta) => {
            let color_temp_min;
            let color_temp_max;
            if (entity.constructor.name === 'Group' && entity.members.length > 0) {
                for (const m of entity.members) {
                    let member_color_temp_min = m.getClusterAttributeValue('lightingColorCtrl', 'colorTempPhysicalMin');
                    let member_color_temp_max = m.getClusterAttributeValue('lightingColorCtrl', 'colorTempPhysicalMax');
                    if ((member_color_temp_min === undefined) || (member_color_temp_max === undefined)) {
                        // XXX: perhaps doing this once in configure() is good, but bulbs are the odd extend thing
                        // looks like we have no cached values, lets read query the device
                        await m.read('lightingColorCtrl', ['colorTempPhysicalMin', 'colorTempPhysicalMax']);
                        member_color_temp_min = m.getClusterAttributeValue('lightingColorCtrl', 'colorTempPhysicalMin');
                        member_color_temp_max = m.getClusterAttributeValue('lightingColorCtrl', 'colorTempPhysicalMax');
                    }
                    /*
                     * For groups we want the value to be in range for all devices
                     * So we grab the highest min and lowest max so we are OK in mixed groups.
                     */
                    if ((color_temp_min === undefined) || (member_color_temp_min > color_temp_min)) {
                        color_temp_min = member_color_temp_min;
                    }
                    if ((color_temp_max === undefined) || (member_color_temp_max < color_temp_max)) {
                        color_temp_max = member_color_temp_max;
                    }
                }
            } else {
                color_temp_min = entity.getClusterAttributeValue('lightingColorCtrl', 'colorTempPhysicalMin');
                color_temp_max = entity.getClusterAttributeValue('lightingColorCtrl', 'colorTempPhysicalMax');
                if ((color_temp_min === undefined) || (color_temp_max === undefined)) {
                    // XXX: perhaps doing this once in configure() is good, but bulbs are the odd extend thing
                    // looks like we have no cached values, lets read query the device
                    await entity.read('lightingColorCtrl', ['colorTempPhysicalMin', 'colorTempPhysicalMax']);
                    color_temp_min = entity.getClusterAttributeValue('lightingColorCtrl', 'colorTempPhysicalMin');
                    color_temp_max = entity.getClusterAttributeValue('lightingColorCtrl', 'colorTempPhysicalMax');
                }
            }

            if (key === 'color_temp_percent') {
                value = Number(value) * 3.46;
                value = Math.round(value + 154).toString();
            }

            // ensure value withing range
            if ((color_temp_min !== undefined) && (value < color_temp_min)) {
                meta.logger.warn(`Requested color_temp ${value} is lower than minimum supported ${color_temp_min}, using minimum!`);
                value = color_temp_min;
            }
            if ((color_temp_max !== undefined) && (value > color_temp_max)) {
                meta.logger.warn(`Requested color_temp ${value} is higher than maximum supported ${color_temp_max}, using maximum!`);
                value = color_temp_max;
            }

            value = Number(value);
            const payload = {colortemp: value, transtime: utils.getTransition(entity, key, meta).time};
            await entity.command('lightingColorCtrl', 'moveToColorTemp', payload, utils.getOptions(meta.mapped, entity));
            return {state: {color_temp: value}, readAfterWriteTime: payload.transtime * 100};
        },
        convertGet: async (entity, key, meta) => {
            await entity.read('lightingColorCtrl', ['colorTemperature']);
        },
    },
```

I got it working! But I couldn't figure out how to do the read in configure()... as all bulbs use the `extend`.
And my test bulbs were already setting meta (innr) so I think the configureKey got lost?

**Comment by sjorge** [comment]
OK so the extend is the issue.
It does not do a deep merge... so configureKey gets dropped for innr and co

```
  meta: {
    enhancedHue: false,
    applyRedFix: true,
    turnsOffAtBrightness1: true
  },
```

Added some logging to where they get merged near the bottom.

**Comment by sjorge** [comment]
OK I got a fix, continueing with cleanup

**Comment by sjorge** [comment]
Have a draft PR #2010 open, as having code to look at helps for feedback
