### ISSUE TITLE
New version of Neo Zigbee Siren Alarm

### ISSUE THREAD

**Issue by kemenap** [Koenkk/zigbee-herdsman-converters#1932]
Hello. I'm unable to pair https://zigbee.blakadder.com/Neo_NAS-AB02B0.html.(Model NAS-AB02B0)
I bought it because it should be supported. I have the same device.

But now it seems, the descriptor sent by my device does not match the one present in the zigbee-herdsman-converters.

Log:
Error: Device 0x5c0272fffecaf0a6 "TS0601" not described in statesMapping.. undefined
New device joined '0x5c0272fffecaf0a6' model TS0601
Interview successful: [object Object]
Device '0x5c0272fffecaf0a6' announced itself
Interview started: 0x5c0272fffecaf0a6

 
![102263447-9bc1d780-3f14-11eb-8cc9-090eec950e1c](https://user-images.githubusercontent.com/75466977/102623021-250a2180-4142-11eb-87f5-95f665d77c2d.png)

is a solution possible?
Thanks.

**Comment by esion-net** [comment]
Same/similar here. Bought the device (2 pieces) as it was listed as compatible. Running with Zigbee2Mqtt supervisord plugin (same for regular and edge, docker only version and ) It does get recognized in HA, but none of the functions work as expected. Only the reported link quality seems correct and only the led goes on when triggering an alarm. Values don't seem to be set correctly and no values seem to be read. Also, the device doesn't stop to blink (pairing indicator) most of the times although logs says interview is finished. 

Tried serveral restarts of all components, with and without usb power, different software versions: HA plugin regular & edge, Docker only, master and dev branch bare metal (on armbian)

I've tried to debug but kind of hit a wall [with the tutorial on Tuya devices](https://www.zigbee2mqtt.io/how_tos/how_to_support_new_tuya_devices.html). Editing devices.js works (name/description changes) but no file output dump.txt is generated as described in none of the configurations (might have to file another issue about this). 

There is "NAS-AB02B0-V3 20190910" printed on the pcb. Speakers are working on both devices as they do the short reset beep. 

What can I do to help/debug to get the devices working?

**Comment by leroyloren** [comment]
Same. Please reopen issue. I'm happy to help with debug,

`{
    "id": 15,
    "type": "EndDevice",
    "ieeeAddr": "0x842e14fffee55d51",
    "nwkAddr": 8577,
    "manufId": ,
    "epList": [1],
    "endpoints": {
        "1": {
            "epId": 1,
            "inClusterList": [],
            "outClusterList": [],
            "clusters": {},
            "binds": [],
            "configuredReportings": [],
            "meta": {}
        }
    },
    "interviewCompleted": false,
    "meta": {},
    "lastSeen": 1618074967936
}`

**Comment by kemenap** [comment]
since ioBroker.zigbee 1.4.1 it works for me.

**Comment by zbuh** [comment]
I still think that should be open a new issue to identify the new hardware and make changes to support it. I can help with it. I have setup a sniffer.

**Comment by esion-net** [comment]
> since ioBroker.zigbee 1.4.1 it works for me.

Thanks for the info. Seems like it's not the same issue then. 
@zbuh @leroyloren Should we open a new issue?

**Comment by leroyloren** [comment]
Ok, https://github.com/Koenkk/zigbee2mqtt/issues/7051

Add your logs.

**Comment by aportillagithub** [comment]
Same issue. It's paired and sent empty attributes the whole time

**Comment by michaelroussel2494** [comment]
Same issue
error log:
Received Zigbee message from '0x804b50fffe047558', type 'commandSetTimeRequest', cluster 'manuSpecificTuya', data '{"payloadSize":1536}' from endpoint 1 with groupID 0

No converter available for 'NAS-AB02B0' with cluster 'manuSpecificTuya' and type 'commandSetTimeRequest' and data '{"payloadSize":1536}'

Received Zigbee message from '0x804b50fffe047558', type 'raw', cluster 'manuSpecificTuya', data '{"data":[9,2,17,0,8,68],"type":"Buffer"}' from endpoint 1 with groupID 0

No converter available for 'NAS-AB02B0' with cluster 'manuSpecificTuya' and type 'raw' and data '{"data":[9,2,17,0,8,68],"type":"Buffer"}'

Can someone help us ?
