### ISSUE TITLE
device support Cromcast Keypad

### ISSUE THREAD

**Issue by Holgip** [Koenkk/zigbee-herdsman-converters#1960]
Hello everyone,
unfortunately I have no idea about programming. 
I have here a "Comcast Xfinity Home Classic Keypad", the keypad should be identical to the "CentraLite 3400-D". Is it possible to include the Cromcast keypad in the zigbee-herdsman-converter. 

https://zigbeealliance.org/zigbee_products/comcast-xfinity-home-classic-keypad/
https://www.zigbee2mqtt.io/devices/3400-D.html

![grafik](https://user-images.githubusercontent.com/76516473/102984601-1ccd3000-450e-11eb-9aee-8ab89b7bc282.png)
Many thanks in advance
Holgip

**Comment by Holgip** [comment]
I would be very happy if the topic is not closed and someone finds a little time to insert the Cromcast keypad.
Many greetings
Holger

**Comment by Koenkk** [comment]
currently being worked on in https://github.com/Koenkk/zigbee-herdsman-converters/pull/2115/files (once it's merged it will be supported once iobroker updates)
