### ISSUE TITLE
Retrieving child_lock status of the Moes BHT-002-GCLZB thermostat doesn't work.

### ISSUE THREAD

**Issue by pvermeij** [Koenkk/zigbee-herdsman-converters#1961]
**Zigbee2mqtt version:** 1.16.2 
**Commit:** 1.16.2
**Coordinator type:** zStack3x0
**Coordinator revision:** 20201026

Retrieving child_lock status of the Moes BHT-002-GCZB thermostat doesn't work.

In file tuya.js datapoint: moesChildLock: 40,

In file fromZigbee.js 
            case tuya.dataPoints.**childLock**:
                return {child_lock: value ? 'LOCKED' : 'UNLOCKED'};

This should probably be changed to:
            case tuya.dataPoints.**moesChildLock**:
                return {child_lock: value ? 'LOCKED' : 'UNLOCKED'};

Setting of child_lock works as in file toZigbee.js the following is used:
await sendTuyaDataPointBool(entity, tuya.dataPoints.**moesChildLock**, value === 'LOCK');

**Comment by Koenkk** [comment]
Done, thanks!
