### ISSUE TITLE
adding device Adeo LXEK-1 LXEK-4 from leroy merlin

### ISSUE THREAD

**Issue by jlc38780** [Koenkk/zigbee-herdsman-converters#1966]
Hello , 
I use home assistant and i'm note able to use zigbee_shepherd_devices and device.js (problem to write the Device.js files at the right place)
Can you add the device bellow . 
This device have been test by a tierce person who confirm its work.

`
// Adeo Enki Lampe

    {
        zigbeeModel: ['LXEK-1'],
        model: '9CZA-A806ST',
        vendor: 'Adeo',
        description: 'ENKI Lexman E27 LED RGBW',
        extend: generic.light_onoff_brightness_colortemp_colorxy,
        fromZigbee: [
            fz.brightness, fz.color_colortemp, fz.on_off, fz.xiaomi_bulb_interval,
        ],
    },
 {
        zigbeeModel: ['LXEK-4'],
        model: '9CZA-M350ST-Q1A',
        vendor: 'Adeo',
        description: 'ENKI Lexman GU-10 LED RGBW',
        extend: generic.light_onoff_brightness_colortemp_colorxy,
        fromZigbee: [
            fz.brightness, fz.color_colortemp, fz.on_off, fz.xiaomi_bulb_interval,
        ],
    },

`

Link for e27:
https://www.leroymerlin.fr/v3/p/produits/ampoule-connectee-led-standard-e27-intensite-couleur-variables-enki-lexman-e1506793547

Link for gu10
https://www.leroymerlin.fr/v3/p/produits/ampoule-connectee-led-reflecteur-gu10-intensite-couleur-variables-enki-lexman-e1506797832

db:
`
{
	"id":9,
	"type":"Router",
	"ieeeAddr":"0x5c0272fffe2debf7",
	"nwkAddr":58398,"manufId":4727,
	"manufName":"Adeo",
	"powerSource":"Mains (single phase)",
	"modelId":"LXEK-4",
	"epList":[
	1,242
	],
	"endpoints": {
	"1": {
	"profId":260,
	"epId":1,
	"devId":269,
	"inClusterList":[
		0,
		3,
		4,
		5,
		6,
		8,
		768,
		4096,
		64642
	],
	"outClusterList":[
		25
	],
	"clusters": {
	"genBasic": {
		"attributes": {
		 "modelId":"LXEK-4",
		 "manufacturerName":"Adeo",
		 "powerSource":1,
		 "zclVersion":3,
		 "appVersion":1,
	     "stackVersion":2,
	     "hwVersion":1,
	     "dateCode":"20200526",
	     "swBuildId":"2.4.0"}}},
	     "binds":[],"meta":{}},
	     "242":{"profId":41440,
	     "epId":242,"devId":97,
		  "inClusterList":[],
		  "outClusterList":[33],
		  "clusters":{},
		  "binds":[],
		  "meta":{}}},
		  "appVersion":1,
		  "stackVersion":2,
		  "hwVersion":1,
		  "dateCode":"20200526",
		  "swBuildId":"2.4.0",
		  "zclVersion":3,
		  "interviewCompleted":true,
		  "meta":{},
		  "lastSeen":1608760574735
}
`

List off command:
- on
- off
- brightness_step_up
- brightness_step_down
- color_temperature_step_up
- color_temperature_step_down
- color_saturation_step_up
- color_saturation_step_down
- color_hue_step_up
- color_hue_step_down

Thanks a lot for your awesome works!

**Comment by Koenkk** [comment]
Added, thanks!
