### ISSUE TITLE
Eurotronic TRV missuses system_mode ?

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee-herdsman-converters#1973]
`system_mode`  is heavily used already so I don't think we should change it. 

> Should we also do this for the eurotonic trv’s boost mode?

Don't know the details about this but sounds good

_Originally posted by @Koenkk in https://github.com/Koenkk/zigbee-herdsman-converters/issues/1952#issuecomment-751236758_

**Comment by sjorge** [comment]
Spinning this to have a proper look/discussion about it.

### Preamble as to why we abuse `system_mode`:

- This TRV supports a 'boost' mode where the valve will be opened to the maximum.
- It also has an 'off' mode which can be toggled by setting the window_open flag (valve displays off).

Both of these are now hooked into `system_mode` and we change the mapping the valve returns for it.

The valve **always** returns `system_mode` as `heat`... which makes sense as it well... only provides heat and has no `off` 'real' off mode.

This was done before the heavy work on TuYa TRV's which seem to use `preset` for  various modes, which... make a lot more sense!

### How is the mapping done?
1. we ignore the system_mode we get from att_thermostat here: https://github.com/Koenkk/zigbee-herdsman-converters/blob/b214a424274c076b49057d2e754c184c9a22fa1f/converters/fromZigbee.js#L1605
2. we then parse the manufacturer specific data field here: https://github.com/Koenkk/zigbee-herdsman-converters/blob/b214a424274c076b49057d2e754c184c9a22fa1f/converters/fromZigbee.js#L1610
    1. if boost == on, set system_mode=heat https://github.com/Koenkk/zigbee-herdsman-converters/blob/b214a424274c076b49057d2e754c184c9a22fa1f/converters/fromZigbee.js#L1616
    2. else if window_open, set system_mode=off https://github.com/Koenkk/zigbee-herdsman-converters/blob/b214a424274c076b49057d2e754c184c9a22fa1f/converters/fromZigbee.js#L1617
    3. else set system_mode=auto

It works but it's kind of a hack.

### Benefits of not abusing system_mode
TBD

**Comment by sjorge** [comment]
I just dug up my Eurotronic TRV and immediately get hit with the bug where it ignores everything a few minutes after pairing -_-

**Comment by sjorge** [comment]
[Spirit_ZigBee_BAL_web_EN_November-2019.pdf](https://github.com/Koenkk/zigbee-herdsman-converters/files/5741932/Spirit_ZigBee_BAL_web_EN_November-2019.pdf)

Is the latest manual I managed to get my hands on,...

From that preset should probably be `comfort`, `boost`, `off`...

Back to preset=off and window_open detection...
According to the manual if the valve 'detects' the window it is toggled to off and back to previous mode after 15 minutes. If we set it manually... it remains off.

So we could have a preset=off set it manually as a preset. But also have `window_open_internal` with a logic like:
- current `preset` == off (can only happen by the user setting it via z2m)
  - window_open_external = always false
- current `preset` != off  
  - window_open_external = whatever the valve tells us?

**Comment by asgothian** [comment]
> [Spirit_ZigBee_BAL_web_EN_November-2019.pdf](https://github.com/Koenkk/zigbee-herdsman-converters/files/5741932/Spirit_ZigBee_BAL_web_EN_November-2019.pdf)
> 
> Is the latest manual I managed to get my hands on,...
> 
> From that preset should probably be `comfort`, `boost`, `off`...
> 
> Back to preset=off and window_open detection...
> According to the manual if the valve 'detects' the window it is toggled to off and back to previous mode after 15 minutes. If we set it manually... it remains off.

When integrating the valve into ioBroker i ran a large number of tests on this, and i found 2 facts which were in conflict with the manual:

- the Thermostat was never able to detect an open window.
- When the window open mode was set manually, it did return to normal operation after 15 minutes.

I just run the test again - even a drop in Temperature by 5 degrees within 1 minute did not trigger the window open detection. With regards to setting "window open" - it seems that the Thermostat did indeed move away from "window open" mode after 15 minutes (indicated by changing the display from "off" to "5.0") , but this change was not reported to zigbee. In addition to that, the current_heating_setpnt remained at 5 degrees.

I can confirm that setting the TRV_Mode offers 3 settings:
- 0: OFF
- 1: Manual mode (use the Set_valve_position cluster to set a target percentage for the valve
- 2: Automatic mode (use the set temperature)
Note that setting the value to 0 (off) disables the functions, but does NOT change the display.
Also note that updating the current_heating_setpnt while in TRV_Mode 0 or 1 will result in the display showing said target temperature, even though the internal control is inactive.

A.

**Comment by sjorge** [comment]
> I just run the test again - even a drop in Temperature by 5 degrees within 1 minute did not trigger the window open detection. With regards to setting "window open" - it seems that the Thermostat did indeed move away from "window open" mode after 15 minutes (indicated by changing the display from "off" to "5.0") , but this change was not reported to zigbee. In addition to that, the current_heating_setpnt remained at 5 degrees.
> 
Yeah, I never got it to trigger so It's probably safe to assume it is not doing any detection.

> I can confirm that setting the TRV_Mode offers 3 settings:
> 
>     * 0: OFF
>     * 1: Manual mode (use the Set_valve_position cluster to set a target percentage for the valve
>     * 2: Automatic mode (use the set temperature)
> 
> 
> Note that setting the value to 0 (off) disables the functions, but does NOT change the display.
> Also note that updating the current_heating_setpnt while in TRV_Mode 0 or 1 will result in the display showing said target temperature, even though the internal control is inactive.

Ooh very interesting, so we can indeed map this like:

- `preset`:
   - write:  
      - **off**:  write off to trv_mode (also switch when trv mode reports off)
      - **manual**: write to trv_mode (also switch when trv mode reports manual)
      - **auto** (or comfort?): write to trv_mode (also switch when trv mode reports auto)
      - **boost**: write hostflags boost bit (also switch when hostflags reports boost is set)
   - read: do read for trv_mode + hostflags (triggering the proper updates)
- `valve_position`: 
   - write: valve_position + trv_mode (off) _(do we also write hostflags boost bit?)_ 
   - read:  do read for trv_mode + valve_position
- `current_heating_setpoint`:
   - write: current_heating_setpoint + trv_mode (auto) _(do we also write hostflags boost bit?)_ 
   - read: do read for trv_mode + current_heating_setpoint
- `unoccupied_heating_setpoint `:
    - write: write unoccupied_heating_setpoint + trv_mode (auto) _(do we also write hostflags boost bit?)_ 
    - read: do read for trv_mode + current_heating_setpoint + unoccupied_heating_setpoint
- `occupied_heating_setpoint` :
    - write: write occupied_heating_setpoint + trv_mode (auto)  _(do we also write hostflags boost bit?)_ 
    - read: do read for trv_mode + current_heating_setpoint + occupied_heating_setpoint
- `window_open_external`:
    - write: write hostflags.window_open bit
    - read: do read for hostsflags
- `mirror_display`:
    - write: write hostflags.mirror_display bit
    - read: do read for hostsflags
- `child_lock`:
    - write: write hostflags.child_protection bit
    - read: do read for hostsflags

**Comment by asgothian** [comment]
That does sound doable. There is one issue, though. The Thermostat does not actually have any sheduling / occupation handling, i.e. it is not sensible to expose current_heating_setpoint, unoccupied_heating_setpoint and occupied_heating_setpoint.

Due to the issues with the thermostat in the past, i would reduce those to exposing "occupied_heating_setpoint" as "heating_setpoint", and leave it at that.

The converters for unoccupied and current heating setpoint could remain for compatibility reasons, but i would reduce the amount of DP's exposed to the application.

I would on purpose trigger a read of the host flags whenever heating_setpoint, valve_position and preset are written to ensure that they are current. I have had reporting issues with them from time to time.

A.

**Comment by sjorge** [comment]
I was only including occupied_heating_setpoint and occupied_heating_setpoint, because they come from the standard hvacThermostat implementation. IIRC (I could be wrong,@koenkk?) if we provide our own variants for these... the generic ones are ignored.

We could just have both be aliases for current_heating_setpoint and write it directly. And of course not expose them using exposes.

The manual does say that a write to either of those will  get copied to current_heating_setpoint... so perhaps we don't even need to include them. Not sure that would trigger a reporting update for current_heating_setpoint and friends though.

**Comment by asgothian** [comment]
I was able to verify that setting either occupied or unoccupied heating setpoint will change the target temperature for the thermostat. It will also update the current_heating_setpoint and report this change back to the user.

A.

**Comment by sjorge** [comment]
Great, less custom code the better.

**Comment by mgrom** [comment]
Hi guys, it was me who made this change for tuya trv from system_modes to presets. Before that I've done a lot of reading, and checking the code of HA. 
System mode for me is something more generic and relates to behavior of the valve. So for TRV you can have only Off, Auto, Heat. Off is quite simple - trv is not heating. Auto is more comlicated, but I like to think that this mode should be related to situation when TRV is deciding when to heat and when not, or how much open the valve. Heat is oposite to Off - whatever it means ;) but should be manual - trv shouldn't decide about closing and opening the valve.
But things like "Boost", "Schedule" or whatever non-standard things trv offers should land in Presets. 

I've just added Auto, Off and Heat system modes to Tuya thermostat (Moes to be more precise), because this device has force attribute with values:
0 - normal => translated to Auto system mode
1 - open (100%)  => Heat
2 - close (0%) => Off
So it's like having big decision to make, do I want the valve to automatically decide about heating or not, if yes then I'm choosing Auto, and then is small decision to make, what type of auto mode I'd like to run and this is preset (for example comfort mode, eco mode etc).

**Comment by sjorge** [comment]
@mgrom

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/379665/103280709-57810d80-49d1-11eb-94b4-4afdf258924a.png">

The ZCL is a bit... odd about it, I think it's probably better not not mess with it and just get/set whatever the zigbee allowed values are, if the valve rejects it, it's OK to just error on it.

As each TRV will be different, having the 'modes of operation' abstraction in a `preset` property seems cleaner. 
It can then be something like
> off: write off to trv_mode (also switch when trv mode reports off)
manual: write to trv_mode (also switch when trv mode reports manual)
auto (or comfort?): write to trv_mode (also switch when trv mode reports auto)
boost: write hostflags boost bit (also switch when hostflags reports boost is set)

Or if we generalize this maybe
> off: write off to trv_mode (also switch when trv mode reports off)
manual: write to trv_mode (also switch when trv mode reports manual)
auto: write to trv_mode (also switch when trv mode reports auto)
heat: write hostflags boost bit (also switch when hostflags reports boost is set)

A lot of confusion seems to come from what HA calls 'system_mode' and what ZCL systemMode are not exactly the same, z2m should deal with the ZCL variant.

If we expose a device via the HA discovery protocol, we'll need to do some mapping but that could for example be the `preset` property as nothing prevents us from doing so there.

**Comment by sjorge** [comment]
I'd still like to clean this up eventually, but I am still having so many issues with mine currently where it just stops responding. 

🤞 on a firmware update soon.

**Comment by sygys** [comment]
@sjorge sorry to bother you but im having some issues with this valve. I have been trying for days now to fix the problem where the valve crashes from the network and rejoins it. when this happens some settings like trv_mode are reset back to value 2. i guess the valve restarts the software and rejoins the network. for a short while it will report the standard setpoint temperature of 20 degrees and after that jumps back to the user set value. All goes back to the set value except the trv_mode.

I use these valves to manually open and close and these things crashing is a huge pain. I still cant figure out why it crashes. The z2mqtt logs dont show allot. 

Do you know what causes these crashes? below my logs of the valve when it gets disconnected.  Is there a way to see behind the scenes of z2m what is actually being send and received to the valve? i guess z2m is not showing everything.

```
debug 2022-01-19 10:54:41: Received MQTT message on 'zigbee2mqtt/Mancave thermostaatkraan/set' with data '{"valve_position":0}'
debug 2022-01-19 10:54:41: Publishing 'set' 'valve_position' to 'Mancave thermostaatkraan'


error 2022-01-19 10:55:04: Publish 'set' 'valve_position' to 'Mancave thermostaatkraan' failed: 'Error: Write 0x00158d00077434d9/1 hvacThermostat({"16385":{"value":0,"type":32}}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4151,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 14201 - 1 - 121 - 513 - 4 after 10000ms)'
debug 2022-01-19 10:55:04: Error: Write 0x00158d00077434d9/1 hvacThermostat({"16385":{"value":0,"type":32}}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4151,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 14201 - 1 - 121 - 513 - 4 after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
info  2022-01-19 10:55:04: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'valve_position' to 'Mancave thermostaatkraan' failed: 'Error: Write 0x00158d00077434d9/1 hvacThermostat({\"16385\":{\"value\":0,\"type\":32}}, {\"sendWhenActive\":false,\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":4151,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Timeout - 14201 - 1 - 121 - 513 - 4 after 10000ms)'","meta":{"friendly_name":"Mancave thermostaatkraan"},"type":"zigbee_publish_error"}'

debug 2022-01-19 10:55:14: Device 'Mancave thermostaatkraan' announced itself
info  2022-01-19 10:55:14: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"Mancave thermostaatkraan","ieee_address":"0x00158d00077434d9"},"type":"device_announce"}'
info  2022-01-19 10:55:14: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"Mancave thermostaatkraan"},"type":"device_announced"}'

debug 2022-01-19 10:55:15: Received Zigbee message from 'Mancave thermostaatkraan', type 'attributeReport', cluster 'hvacThermostat', data '{"16387":2000,"16392":1}' from endpoint 1 with groupID 0
info  2022-01-19 10:55:15: MQTT publish: topic 'zigbee2mqtt/Mancave thermostaatkraan', payload '{"battery":100,"battery_low":false,"current_heating_setpoint":20,"eurotronic_error_status":0,"eurotronic_host_flags":{"boost":false,"child_protection":false,"mirror_display":false,"window_open":false},"eurotronic_system_mode":1,"linkquality":60,"local_temperature":27.5,"occupied_heating_setpoint":30,"pi_heating_demand":10,"running_state":null,"system_mode":"auto","trv_mode":null,"unoccupied_heating_setpoint":16,"update":{"state":"idle"},"update_available":false,"valve_position":null}'
debug 2022-01-19 10:55:15: Received Zigbee message from 'Mancave thermostaatkraan', type 'attributeReport', cluster 'hvacThermostat', data '{"localTemp":2000,"occupiedHeatingSetpoint":2000,"pIHeatingDemand":255,"unoccupiedHeatingSetpoint":2000}' from endpoint 1 with groupID 0
info  2022-01-19 10:55:15: MQTT publish: topic 'zigbee2mqtt/Mancave thermostaatkraan', payload '{"battery":100,"battery_low":false,"current_heating_setpoint":20,"eurotronic_error_status":0,"eurotronic_host_flags":{"boost":false,"child_protection":false,"mirror_display":false,"window_open":false},"eurotronic_system_mode":1,"linkquality":60,"local_temperature":20,"occupied_heating_setpoint":20,"pi_heating_demand":100,"running_state":null,"system_mode":"auto","trv_mode":null,"unoccupied_heating_setpoint":20,"update":{"state":"idle"},"update_available":false,"valve_position":null}'

debug 2022-01-19 10:55:16: Retrieving state of 'Mancave thermostaatkraan' after reconnect
debug 2022-01-19 10:55:17: Received Zigbee message from 'Mancave thermostaatkraan', type 'attributeReport', cluster 'hvacThermostat', data '{"localTemp":2700,"occupiedHeatingSetpoint":3000,"pIHeatingDemand":13,"unoccupiedHeatingSetpoint":1600}' from endpoint 1 with groupID 0
info  2022-01-19 10:55:17: MQTT publish: topic 'zigbee2mqtt/Mancave thermostaatkraan', payload '{"battery":100,"battery_low":false,"current_heating_setpoint":20,"eurotronic_error_status":0,"eurotronic_host_flags":{"boost":false,"child_protection":false,"mirror_display":false,"window_open":false},"eurotronic_system_mode":1,"linkquality":57,"local_temperature":27,"occupied_heating_setpoint":30,"pi_heating_demand":5,"running_state":null,"system_mode":"auto","trv_mode":null,"unoccupied_heating_setpoint":16,"update":{"state":"idle"},"update_available":false,"valve_position":null}'
debug 2022-01-19 10:55:17: Received Zigbee message from 'Mancave thermostaatkraan', type 'attributeReport', cluster 'hvacThermostat', data '{"16387":3000}' from endpoint 1 with groupID 0
info  2022-01-19 10:55:17: MQTT publish: topic 'zigbee2mqtt/Mancave thermostaatkraan', payload '{"battery":100,"battery_low":false,"current_heating_setpoint":30,"eurotronic_error_status":0,"eurotronic_host_flags":{"boost":false,"child_protection":false,"mirror_display":false,"window_open":false},"eurotronic_system_mode":1,"linkquality":60,"local_temperature":27,"occupied_heating_setpoint":30,"pi_heating_demand":5,"running_state":null,"system_mode":"auto","trv_mode":null,"unoccupied_heating_setpoint":16,"update":{"state":"idle"},"update_available":false,"valve_position":null}'
debug 2022-01-19 10:55:17: Received Zigbee message from 'Mancave thermostaatkraan', type 'attributeReport', cluster 'hvacThermostat', data '{"localTemp":2700,"occupiedHeatingSetpoint":3000,"pIHeatingDemand":13,"unoccupiedHeatingSetpoint":1600}' from endpoint 1 with groupID 0
info  2022-01-19 10:55:17: MQTT publish: topic 'zigbee2mqtt/Mancave thermostaatkraan', payload '{"battery":100,"battery_low":false,"current_heating_setpoint":30,"eurotronic_error_status":0,"eurotronic_host_flags":{"boost":false,"child_protection":false,"mirror_display":false,"window_open":false},"eurotronic_system_mode":1,"linkquality":60,"local_temperature":27,"occupied_heating_setpoint":30,"pi_heating_demand":5,"running_state":null,"system_mode":"auto","trv_mode":null,"unoccupied_heating_setpoint":16,"update":{"state":"idle"},"update_available":false,"valve_position":null}'
debug 2022-01-19 10:55:17: Received Zigbee message from 'Mancave thermostaatkraan', type 'attributeReport', cluster 'hvacThermostat', data '{"localTemp":2700,"occupiedHeatingSetpoint":3000,"pIHeatingDemand":13,"unoccupiedHeatingSetpoint":1600}' from endpoint 1 with groupID 0
info  2022-01-19 10:55:17: MQTT publish: topic 'zigbee2mqtt/Mancave thermostaatkraan', payload '{"battery":100,"battery_low":false,"current_heating_setpoint":30,"eurotronic_error_status":0,"eurotronic_host_flags":{"boost":false,"child_protection":false,"mirror_display":false,"window_open":false},"eurotronic_system_mode":1,"linkquality":60,"local_temperature":27,"occupied_heating_setpoint":30,"pi_heating_demand":5,"running_state":null,"system_mode":"auto","trv_mode":null,"unoccupied_heating_setpoint":16,"update":{"state":"idle"},"update_available":false,"valve_position":null}'
debug 2022-01-19 10:55:19: Received Zigbee message from 'Zolder kachel smartplug', type 'attributeReport', cluster 'seMetering', data '{"currentSummDelivered":[0,63584]}' from endpoint 1 with groupID 0
```

**Comment by sygys** [comment]
in the graph you can see the crashes occur. both setpoint as current temperatures drop to 20 when it happens
![Knipsel](https://user-images.githubusercontent.com/73538763/150123303-ad2d2edb-be6d-4364-9723-fc6e50ade20a.JPG)

**Comment by sjorge** [comment]
I abandoned this valve a while ago, I started getting the invalid_attribute error and I never managed to get mine into a working order. (Not that I've found a replacement)

The error after your set of valve_position returns a `Timeout - 14201 - 1 - 121 - 513 - 4 after 10000ms` error.
Which can mean 2 things:
- the trv has already crashed and is non-responding
- the trv firmware crashed while trying to do the valve_position change

I'm leaning towards the later of the two given the device announced itself again a few seconds later.

https://github.com/Koenkk/zigbee-herdsman-converters/blob/7cc7863ae8f0ea31d24d63c0ab9e0eca0be13029/converters/toZigbee.js#L3550-L3559

Seems to be using a custom attribute to set the position, so without proper documentation from eurotronics, which, we AFAIK do not have, it's going to be guess work as to why. The code looks simple enough, it just writes the temp to a custom attribute so much z2m can be doing wrong there.

Does it always crash at roughtly the same interval? If so, try increasing and decreasing the frequentcy you update valve_position to see if there is a correlation.

**Comment by sjorge** [comment]
I have no experience with the zwave variant. I don't have any experience with these, but some of the TuYa ones also seem to have a position attribute? https://www.zigbee2mqtt.io/supported-devices/#e=position,climate

**Comment by sygys** [comment]
thanks for the help. i just received an email from eurotronic they pointed me to a github page with an older firmware version and an explaination how to flash it. Im flashing this firmware as we speak. let hope this version atleast fixes the valve position and crashes
