### ISSUE TITLE
Exposes using hue/Saturation and hue_correction configuration

### ISSUE THREAD

**Issue by asgothian** [Koenkk/zigbee-herdsman-converters#1974]
I have been trying to implement the hue_correction feature in when controlling a lamp using the "expose" feature. This was done on this bulb (https://www.zigbee2mqtt.io/devices/9290012573A.html).

Running the tests, i found that the expose did not in fact announce that the lamp could be controlled via hue/saturation, and the hue_correction feature listed on the device page is used only when a lamp is controlled via hue/saturation.

I did patch in the expose on my system and was able to complete my implementation. When checking the exposes in devices.js i found that only a select few lamps actually offer the 'hs' expose, even if their page lists the 'hue_correction' feature, and as such indicates that the light should be controllable via hue/saturation

I wanted to ask if this is "by design" or "an error", before i go through and make a large PR adding this feature to the lamps which (given the documentation) should support it.

A.

**Comment by Koenkk** [comment]
I think we should indeed expose hue/saturation for Hue bulbs, can you make a pr?

**Comment by asgothian** [comment]
Will do. It will take me a few days to crosscheck the device description and the devices to ensure that exposes and fz.tz fit as planned.

A

**Comment by itavero** [comment]
On a related note: if a device supports both `color_hs` and `color_xy`, which one would be the preferred way of controlling the bulb?
If I read this I would say it would be `color_hs`, but I think elsewhere I got the impression that `color_xy` would be preferred as this is supported by most lights.

Asking for itavero/homebridge-z2m#18

**Comment by asgothian** [comment]
This question cannot be answered globally. It depends a lot on what should be done with the light. For link to color pickers and web interfaces or direct color controls, `color_xy` Is often easier. For situations where only the color should be changed but the color intensity and brightness should remain, control via `color_hs` Is easier. This was my reason for looking into this topic to begin with.

I would suggest to always support both if the light itself supports both. Going for only one is a limiting factor in my eyes. I will even go as far as suggesting to always support `color_hs` as incoming format, even on bulbs which internally only allow use of `color_xy`, but this might require some additional magic in the converters - so this is for the future.

A.

**Comment by sjorge** [comment]
Also some bulb respond differently so keep that in mind.

- Innr: xy needs a odd 'redfix', but via Hue/Sat it works without overal I find the colors to be closer to what I expect with hs.
- Osram: bulb seems to become pink when using XY for pure red at 100% brightness, with hs it is a tiny bit dimmer but stays red.

**Comment by itavero** [comment]
Thanks for the feedback. It sounds that, if one had to choose, `color_hs` is the way to go.
For my Homebridge plugin, it makes most sense to choose only one. Otherwise you would see two lights in the Apple Home app instead of one, which would become very confusing I guess.
Besides that, Apple already expresses colors in hue/saturation characteristics, so not having to do any conversion in my plugin but simply passing on the values also seems like a better thing to do.

**Comment by asgothian** [comment]
> Also some bulb respond differently so keep that in mind.
> 
> * Innr: xy needs a odd 'redfix', but via Hue/Sat it works without overal I find the colors to be closer to what I expect with hs.
> * Osram: bulb seems to become pink when using XY for pure red at 100% brightness, with hs it is a tiny bit dimmer but stays red.

Does that mean that Innr Lights and Osram Bulbs support hue/saturation ? If so, i can add the  ..color_xyhs expose to those too. I did not want to do that since i could not verify that it works.

Also, using the comment about "hue_calibration" seems not a good way to go, as it is present on all color bulbs i checked, although i am almost certain that most of the gledopto units do not support hue/saturation. But again ,as i do not have any of those to test, i will not add that to my pull request.

**Comment by sjorge** [comment]
@asgothian my osram, tint and innr* test bulbs do seem to support hue/saturation yes.

* Innr RB 250 C seems to only support basic hue/saturation not the enhancedHue variant.

https://github.com/Koenkk/zigbee-herdsman-converters/blob/3d0b3f82d15f4eba287ac40a7daafe498a4f4f6a/devices.js#L4994

https://github.com/Koenkk/zigbee-herdsman-converters/blob/3d0b3f82d15f4eba287ac40a7daafe498a4f4f6a/devices.js#L5027

https://github.com/Koenkk/zigbee-herdsman-converters/blob/3d0b3f82d15f4eba287ac40a7daafe498a4f4f6a/devices.js#L5132

I did not update the other Innr bulbs/spots as I do not own them. Although it is probably safe to assume, that all Innr color bulbs/spots supports hue/sat with the enhancedHue meta flag set to false.

**Comment by asgothian** [comment]
Ok.. adding the coloxyhs to the innr and osram light sources.

Note that this will only affect the exposes, not the actual converters

**Comment by asgothian** [comment]
Closing this - PR is merged
