### ISSUE TITLE
RTCGQ11LM does not expose illuminance_lux

### ISSUE THREAD

**Issue by itavero** [Koenkk/zigbee-herdsman-converters#1992]
I might be mistaken, but if I look at the [`RTCGQ11LM_illuminance` converter](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/converters/fromZigbee.js#L3474-L3487) in `fromZigbee.js`, I'd say it actually exposes `illuminance_lux` (meaning a value exposed in lux and not a "raw measured value").

Note that there is a comment in there as well:
```js
// DEPRECATED: only return lux here (change illuminance_lux -> illuminance)
```

Currently the [exposes information](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L618) mentions the following in the device definition:
```js
exposes: [e.battery(), e.occupancy(), e.illuminance().withUnit('lx')],
```

I think this should be:
```js
exposes: [e.battery(), e.occupancy(), e.illuminance_lux()],
```

Or perhaps the following if `illuminance_lux` is considered deprecated:
```js
exposes: [e.battery(), e.occupancy(), e.illuminance_lux().withProperty('illuminance')],
```

**Comment by Koenkk** [comment]
`illuminance_lux` is deprecated and should never have been added for the RTCGQ11LM since the `illuminance` value is already the Lux value (not the raw value as other illuminance devices do).

I've updated the deprecated message.

**Comment by itavero** [comment]
In that case the last suggestion mentioned above would be the right one, in my opinion:
```js
exposes: [e.battery(), e.occupancy(), e.illuminance_lux().withProperty('illuminance')],
```

I'll open up a PR for that tomorrow.

**Comment by Koenkk** [comment]
Ah, I see now that the description is indeed incorrect with e.illumance(). Thanks for the pr already

**Comment by itavero** [comment]
Well, the most important part for me is the `name` used in the exposes model.
I use this in itavero/homebridge-z2m for mapping exposes information to HomeKit services and characteristics.

**Comment by Koenkk** [comment]
So the problem is that name `illuminance` is the `raw` value for most devices and Lux for the RTCGQ11LM?

**Comment by itavero** [comment]
Indeed, and by name I mean the `name` mentioned in the exposes information (so not the `property`).

So far it seems that the `name` seems to be the best (if not only way) to handle the mapping.
I kinda assumed that was also the intention of this field: to provide a consistent name for "properties" of a device, despite their endpoints or actual property "keys".
I hope I did not make a wrong assumption. 😅

**Comment by Koenkk** [comment]
@itavero why not use the `unit` property? This is not set for the raw `illuminance`, but for the RTCGQ11LM illuminance it is set to `lx`.

**Comment by itavero** [comment]
I could do that in this particular case.
However, for a lot of other properties this can't be done (a lot of sensors for instance are binary and don't have a unit, but I still need to know if it's a smoke / motion / contact / ... sensor).
Hence I was using the `name` for those and would like to keep my code (as well as the exposes information in this repository) consistent.

**Comment by Koenkk** [comment]
@itavero I understand, but there are no guarantees that the all names will use the same unit.

**Comment by itavero** [comment]
Currently I generally base the mapping on the provided the `type` and `name`.
I might add a check on `unit` as well in cases where it is currently provided.

**Comment by Koenkk** [comment]
Good, #1994 is a bit of a workaround but acceptable for now. Assuming this can be closed.
