### ISSUE TITLE
VisorTech NX6407-944 in Zigbee-Adapter

### ISSUE THREAD

**Issue by Jean-GO** [Koenkk/zigbee-herdsman-converters#1993]
Hallo,

währe es möglich, den Türgriff von VisorTech (NX6407-944) mit in den Adapter einzubinden?

ich möchte ungerne die cloude nutzen, aber in Zigbee-Adapter ist dieser leider nur als Fragezeichen sichtbar.

Grüße und guten Rutsch
![Bild_01](https://user-images.githubusercontent.com/76437060/103276835-e426ce00-49c7-11eb-817e-a965e6199fcd.JPG)
![Bild_02](https://user-images.githubusercontent.com/76437060/103276846-e6892800-49c7-11eb-9921-e65900159990.JPG)

**Comment by Koenkk** [comment]
Englisch only
