### ISSUE TITLE
New manufacturer Zemismart / TuYa curtain (ZM79E-DT)

### ISSUE THREAD

**Issue by ASNNetworks** [Koenkk/zigbee-herdsman-converters#2001]
I have received a TuYa (Zemismart ZM79E-DT) curtain motor. Is should be supported, but I get an error. I checked the devices.js page on Github and noticed the one I have has a different manufacturer. I have this one: `_TZE200_cowvfni3`.

Currently these are listed: 
```
            {modelID: 'TS0601', manufacturerName: '_TZE200_5zbp6j0u'},
            {modelID: 'TS0601', manufacturerName: '_TZE200_nkoabg8w'},
            {modelID: 'TS0601', manufacturerName: '_TZE200_xuzcvlku'},
            {modelID: 'TS0601', manufacturerName: '_TZE200_4vobcgd3'},
            {modelID: 'TS0601', manufacturerName: '_TZE200_nogaemzt'},
            {modelID: 'TS0601', manufacturerName: '_TZE200_pk0sfzvr'},
            {modelID: 'TS0601', manufacturerName: '_TZE200_fdtjuw7u'},
            {modelID: 'TS0601', manufacturerName: '_TZE200_zpzndjez'},
            {modelID: 'TS0601', manufacturerName: '_TZE200_rddyvrci'},
```

Can you add support to this new manufacturer? Is there something I can do myself?

**Comment by Koenkk** [comment]
Added! Will be supported in zigbee2mqtt 1.17.0

**Comment by ASNNetworks** [comment]
> Added! Will be supported in zigbee2mqtt 1.17.0

Is this by any chance sooner available through the edge version?

**Comment by Koenkk** [comment]
Today!

**Comment by ASNNetworks** [comment]
> Today!

I forgot to mention, I’m running the HA add-on. Should I ask there when that version will be updated with your new release, or will that be pushed soon after usually?

**Comment by Koenkk** [comment]
@ASNNetworks should be pushed soon, it's already in the edge version of the addon

**Comment by ASNNetworks** [comment]
Hi @Koenkk I have it connected succesfully, thanks! However, I notice open and close states are reversed. Is there a way to flip this around within zigbee2mqtt? Should I create a new ticket?

**Comment by Koenkk** [comment]
Should be fixed.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by ASNNetworks** [comment]
@Koenkk Hi, I tested the edge version. Open and close works now, thanks!

However the attribute states are still reversed. Sending a close service call does close the curtains, but the state will be open and position at 100. Opening curtains will set state to closed and position to 0. Having it open at 95%, will say it’s open at 5% etc.

**Comment by Koenkk** [comment]
Pushed a possible fix.

position 0 should be closed indeed (100 = open).

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by ASNNetworks** [comment]
Thanks, I can confirm it works properly now!

**Comment by ASNNetworks** [comment]
Hi @Koenkk somehow this has inverted again. I’m not sure if the official or edge add-ons have been updated, but the position is reverted of my curtains. The service call to open/close is correct, but the position is not (just like before). 

Has anything changed again? Can you perhaps push a fix?

**Comment by Koenkk** [comment]
See https://github.com/Koenkk/zigbee2mqtt/issues/6043
