### ISSUE TITLE
miredsToKelvin and kelvinToMireds are same formula?

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee-herdsman-converters#2004]
https://github.com/Koenkk/zigbee-herdsman-converters/blob/aab1a4a993e4a87e554bfee105441ea05fbc28b2/lib/utils.js#L275

https://github.com/Koenkk/zigbee-herdsman-converters/blob/aab1a4a993e4a87e554bfee105441ea05fbc28b2/lib/utils.js#L285

I was looking for a mired to kelvin and back conversion and I found these two... but they are the exact same? Shouldn't one of them be the reverse?

**Comment by Koenkk** [comment]
Looks confusion on first sight but calculations are correct. Happy new year!

![image](https://user-images.githubusercontent.com/2892853/103438273-e9875100-4c31-11eb-87ab-06d70a7525ed.png)

**Comment by sjorge** [comment]
Indeed very confusing! But good to know there was not a bug lurking somewhere haha. Happy new year!
