### ISSUE TITLE
Add `_long` and `_double` to docs for WXKG07LM

### ISSUE THREAD

**Issue by TobiasBg** [Koenkk/zigbee-herdsman-converters#2011]
#1146 added support for the Aqara double switch WXKG07LM (lumi.remote.b286acn02).

In my tests, it also offers `left_long`, `left_double`, `right_long`, `right_double`, `both_long`, and `both_double` values for the `action`. This is however missing in the documentation at https://www.zigbee2mqtt.io/devices/WXKG07LM.html

It would great if these could be added to the docs.

**Comment by Koenkk** [comment]
Added, docs will be updated (regenerated) on next z2m release (1 February).

**Comment by TobiasBg** [comment]
Thanks for the quick fix, @Koenkk! All the best for 2021!
