### ISSUE TITLE
Correctness/accuracy of exposes information for Green Power devices

### ISSUE THREAD

**Issue by itavero** [Koenkk/zigbee-herdsman-converters#2012]
In `devices.js`, I see that `GreenPower_2` can apparently send the following values for `action`:
```
'identify', 'recall_scene_0', 'recall_scene_1', 'recall_scene_2', 'recall_scene_3', 'recall_scene_4', 'recall_scene_5',
'recall_scene_6', 'recall_scene_7', 'store_scene_0', 'store_scene_1', 'store_scene_2', 'store_scene_3', 'store_scene_4',
'store_scene_5', 'store_scene_6', 'store_scene_7', 'off', 'on', 'toggle', 'release', 'press_1_of_1', 'release_1_of_1',
'press_1_of_2', 'release_1_of_2', 'press_2_of_2', 'release_2_of_2', 'short_press_1_of_1', 'short_press_1_of_2',
'short_press_2_of_1'
```

However, I doubt that this is actually accurate for all the devices using this model.
For instance, I see a lot of values I have never seen in my MQTT logs for my Philips Hue Tap remote.
Is there a way for zigbee2mqtt to determine (maybe during pairing) which values are actually supported?

If it's not possible, I probably have to add the ability for the users of homebridge-z2m to list values that should be ignored, to improve the usability of these devices (and not get stuck with a lot of switches in HomeKit that will never get triggered by their device).
It's a totally doable workaround, but the best experience (also for users of other software using this information) would of course be if the information provided from zigbee2mqtt is more accurate.

On a related note: I also noticed that `GreenPower_7` simply lists `e.action(['*'])` for `exposes`.
I haven't checked all the logic that is executed after this, but as far as I can tell (and expect) this `*` is never replaced with a valid/correct value.
Several other devices also have an asterisk (`*`) in values listed for `action` (for instance: Nue / 3A Smart key scene wall switches have `e.action(['recall_*'])` in their `exposes` information).
It's not clear to me how I should interpret these values and how the software using the exposes information can determine the explicit values that these devices are able to send.

**Comment by Koenkk** [comment]
> Is there a way for zigbee2mqtt to determine (maybe during pairing) which values are actually supported?

There is no way to do this. The problem is that green power only identifies the switch on a very high level (e.g. switch). We have no clue if the paired device is a hue tap or any other device.

**Comment by itavero** [comment]
I was afraid that would be the case. I'll add an option to exclude values via the configuration of homebridge-z2m to workaround this in my code.

I do wonder how Philips solve this. I only ever had a Hue Tap connected to their bridge, so I have no clue how the setup for the "Friends of Hue" switches is done. I reckon they just have the user select the right device in the wizard or something like that?

With regards to the `*` in the values, I'll see if I have some time to dive in to the actual converters and figure out if a definitive list of values can easily be determined for these devices.

**Comment by Koenkk** [comment]
> I do wonder how Philips solve this.

If I remember correctly, you first select the device you want to pair so they know what is being paired.

**Comment by sjorge** [comment]
> > I do wonder how Philips solve this.
> 
> If I remember correctly, you first select the device you want to pair so they know what is being paired.

Maybe for these devices we can:
- allow selecting of a 'model' via configuration.yaml (default to 'generic')
- start storing 'models' for the gp devices.

We can then add a picture/name/unique action list and expose the correct info based on the set 'model'.

e.g. GreenPower_2 would have models 'generic', 'Hue Tap', ...

Sure, it will involve a manual step to set it, but looks like that is what happens with Hue Bridge too (well you set it before pairing)

**Comment by itavero** [comment]
It seems that the `fz.command_recall` will put some number behind `recall_*`.
I don't have any of the devices that use this converter, but I reckon the possible numbers it can put behind there is related to the number of buttons the devices have. Maybe it's possible to fill in the "absolute" `action` values manually...

The same goes for `fz.tint_scene`.

Unfortunately `fz.greenpower_7` seems to be a total mystery. 😅
