### ISSUE TITLE
Bticino F20T60A and L4531C

### ISSUE THREAD

**Issue by Giancky79** [Koenkk/zigbee-herdsman-converters#2019]
after update 1.17.0 zigbee2mqtt and re-pairing devices, the description saying Legrand. Tell me what can i do for correct mismatch, please and thank's a lot for your work

**Comment by Koenkk** [comment]
Can you share the data/database.db entry of your device?

**Comment by Giancky79** [comment]
`
{"id":7,"type":"Router","ieeeAddr":"0x0004740000a133ca","nwkAddr":29761,"manufId":4129,"manufName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","powerSource":"Mains (single phase)","modelId":" DIN power consumption module\u0000\u0000","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":13,"inClusterList":[0,3,4,5,64513,2820],"outClusterList":[0,64513,25],"clusters":{"genBasic":{"attributes":{"modelId":" DIN power consumption module\u0000\u0000","manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","powerSource":1,"zclVersion":2,"appVersion":0,"stackVersion":65,"hwVersion":1,"dateCode":" \u000020190808\u0000\u0000\u0000\u0000\u0000","swBuildId":"01b\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 \u0002\u0000\u0001\u0000 \u0002\u0000\u0002\u0000!\u0012\u0000\u0000\u0000\u0000��\u0003\u0000\u0010\u0002\u0001\u0004\u0000\u0018\u0002\u0000��!"}},"haElectricalMeasurement":{"attributes":{"61440":2,"61441":0,"61442":0,"acVoltageMultiplier":0,"acVoltageDivisor":0,"acCurrentMultiplier":0,"acCurrentDivisor":0,"acPowerMultiplier":1,"acPowerDivisor":1,"activePower":236}}},"binds":[{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00124b001ec7d499","endpointID":1},{"cluster":3,"type":"endpoint","deviceIeeeAddress":"0x00124b001ec7d499","endpointID":1}],"configuredReportings":[{"cluster":2820,"attrId":1291,"minRepIntval":5,"maxRepIntval":3600,"repChange":1}],"meta":{}}},"appVersion":0,"stackVersion":65,"hwVersion":1,"dateCode":" \u000020190808\u0000\u0000\u0000\u0000\u0000","swBuildId":"01b\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 \u0002\u0000\u0001\u0000 \u0002\u0000\u0002\u0000!\u0012\u0000\u0000\u0000\u0000��\u0003\u0000\u0010\u0002\u0001\u0004\u0000\u0018\u0002\u0000��!","zclVersion":2,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1609774709729}
`
this one is for Bticino f20t60a

`
{"id":8,"type":"Router","ieeeAddr":"0x0004740000b2247f","nwkAddr":15450,"manufId":4129,"manufName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","powerSource":"Mains (single phase)","modelId":" Light switch with neutral\u0000\u0000\u0000\u0000\u0000","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,3,6,4,5,15,64513],"outClusterList":[0,64513,25],"clusters":{"genBasic":{"attributes":{"modelId":" Light switch with neutral\u0000\u0000\u0000\u0000\u0000","manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","powerSource":1,"zclVersion":2,"appVersion":0,"stackVersion":65,"hwVersion":1,"dateCode":" \u000020200928\u0000\u0000\u0000\u0000\u0000","swBuildId":"00b\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 \u0002\u0000\u0001\u0000 \u0002\u0000\u0002\u0000!\u0012\u0000\u0000\u0000\u0000��\u0003\u0000\u0010\u0002\u0001\u0004\u0000\u0018\u0002\u0000��!"}},"genOnOff":{"attributes":{"onOff":0}},"genIdentify":{"attributes":{"identifyTime":60}},"genBinaryInput":{"attributes":{"presentValue":0}}},"binds":[{"cluster":3,"type":"endpoint","deviceIeeeAddress":"0x00124b001ec7d499","endpointID":1},{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b001ec7d499","endpointID":1},{"cluster":15,"type":"endpoint","deviceIeeeAddress":"0x00124b001ec7d499","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":65,"hwVersion":1,"dateCode":" \u000020200928\u0000\u0000\u0000\u0000\u0000","swBuildId":"00b\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 \u0002\u0000\u0001\u0000 \u0002\u0000\u0002\u0000!\u0012\u0000\u0000\u0000\u0000��\u0003\u0000\u0010\u0002\u0001\u0004\u0000\u0018\u0002\u0000��!","zclVersion":2,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1609715209539}
`
this one is for Bticino L4531C

`
{"id":9,"type":"Router","ieeeAddr":"0x0004740000a1fe6a","nwkAddr":60469,"manufId":4129,"manufName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","powerSource":"Mains (single phase)","modelId":" Connected outlet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[0,3,4,6,5,64513,2820],"outClusterList":[0,64513,25],"clusters":{"genBasic":{"attributes":{"modelId":" Connected outlet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","powerSource":1,"zclVersion":2,"appVersion":0,"stackVersion":65,"hwVersion":1,"dateCode":" \u000020200722\u0000\u0000\u0000\u0000\u0000","swBuildId":"01b\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 \u0002\u0000\u0001\u0000 \u0002\u0000\u0002\u0000!\u0012\u0000\u0000\u0000\u0000��\u0003\u0000\u0010\u0002\u0001\u0004\u0000\u0018\u0002\u0000��!"}},"haElectricalMeasurement":{"attributes":{"acVoltageMultiplier":0,"acVoltageDivisor":0,"acCurrentMultiplier":0,"acCurrentDivisor":0,"acPowerMultiplier":1,"acPowerDivisor":1,"activePower":0}},"genIdentify":{"attributes":{"identifyTime":60}}},"binds":[{"cluster":3,"type":"endpoint","deviceIeeeAddress":"0x00124b001ec7d499","endpointID":1},{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b001ec7d499","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00124b001ec7d499","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":65,"hwVersion":1,"dateCode":" \u000020200722\u0000\u0000\u0000\u0000\u0000","swBuildId":"01b\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 \u0002\u0000\u0001\u0000 \u0002\u0000\u0002\u0000!\u0012\u0000\u0000\u0000\u0000��\u0003\u0000\u0010\u0002\u0001\u0004\u0000\u0018\u0002\u0000��!","zclVersion":2,"interviewCompleted":true,"meta":{"configured":3},"lastSeen":1608825122967}
`

this one is for Bticino K4003C/L4003C/N4003C/NT4003C

![screen](https://user-images.githubusercontent.com/46261713/103558704-58c0a780-4eb5-11eb-8762-68819314e01e.png)

**Comment by Koenkk** [comment]
AFAIK BTicino and Legrand are the same. Based on your database I conclude that it's not possible to regonize if this is a Legrand or BTicino devices.

**Comment by Giancky79** [comment]
yes i know, we can merged in device.js with legrand and deleted  two models of bticino? in supported device i can change the description with linking on legrand counterpart?

**Comment by Koenkk** [comment]
Since you added these, how did you get the `zigbeeModel`: https://github.com/Koenkk/zigbee-herdsman-converters/pull/1969/files#diff-5520dd49755e0a353d3857b8963a91cb4b8d87a01b6b8eb7bb6cce1c180eac83R13242 (did you manually change it after pairing?)

**Comment by Giancky79** [comment]
i copy this from legrand because device is integrated with legrand but is bticino

**Comment by Koenkk** [comment]
But did this zigbeeModel actually show up during: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html#1-pairing-the-device-with-zigbee2mqtt ?  `Device '0x00158d0001dc126a' with Zigbee model '......'` or did you made it up yourself

**Comment by FedeBZ** [comment]
Work only on channel 11 ?

**Comment by Giancky79** [comment]
tomorrow i can re pairing again, or is possible to resume the info?

**Comment by Giancky79** [comment]
`{"date_code":" \u000020190808\u0000\u0000\u0000\u0000\u0000","definition":{"description":"DIN power consumption module","exposes":[{"access":5,"description":"Instantaneous measured power","name":"power","property":"power","type":"numeric","unit":"W"},{"access":5,"name":"power_alarm_active","property":"power_alarm_active","type":"binary","value_off":false,"value_on":true},{"access":7,"description":"Enable/disable the power alarm","name":"power_alarm","property":"power_alarm","type":"binary","value_off":false,"value_on":true},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"412015","vendor":"Legrand"},"endpoints":{"1":{"bindings":[{"cluster":"haElectricalMeasurement","target":{"endpoint":1,"ieee_address":"0x00124b0008c984e4","type":"endpoint"}},{"cluster":"genIdentify","target":{"endpoint":1,"ieee_address":"0x00124b0008c984e4","type":"endpoint"}}],"clusters":{"input":["genBasic","genIdentify","genGroups","genScenes","manuSpecificLegrandDevices","haElectricalMeasurement"],"output":["genBasic","manuSpecificLegrandDevices","genOta"]},"configured_reportings":[{"attribute":"activePower","cluster":"haElectricalMeasurement","maximum_report_interval":3600,"minimum_report_interval":5,"reportable_change":1}]}},"friendly_name":"0x0004740000a133ca","ieee_address":"0x0004740000a133ca","interview_completed":true,"interviewing":false,"model_id":" DIN power consumption module\u0000\u0000","network_address":24444,"power_source":"Mains (single phase)","software_build_id":"01b\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 \u0002\u0000\u0001\u0000 \u0002\u0000\u0002\u0000!\u0012\u0000\u0000\u0000\u0000��\u0003\u0000\u0010\u0002\u0001\u0004\u0000\u0018\u0002\u0000��!","supported":true,"type":"Router"}]'`

from debug that's all, you have other tips for me? i try repairing so much time and that's all i found

**Comment by Giancky79** [comment]
> But did this zigbeeModel actually show up during: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html#1-pairing-the-device-with-zigbee2mqtt ? `Device '0x00158d0001dc126a' with Zigbee model '......'` or did you made it up yourself

yes, sorry

**Comment by Koenkk** [comment]
The modelID is ` DIN power consumption module\u0000\u0000` which matches the legrand one so the `F20T60A` in devices.js is never used (because that modelID is `Bticino Din power consumption module `
