### ISSUE TITLE
Please add support for tint LED-Globeform white+color

### ISSUE THREAD

**Issue by D3rPap55t** [Koenkk/zigbee-herdsman-converters#2020]
Hello,

I got a problem with these lights tint LED-Globeform white+color.
https://www.mueller-licht.de/produktinformationen/artikel/404036/

I created an issuse on the zigbee adapter page https://github.com/ioBroker/ioBroker.zigbee/issues/924 
I was asked to open here a new issue with these informations.

![zigbee](https://user-images.githubusercontent.com/73795363/103536020-1174ef80-4e92-11eb-824b-256e14be9ae5.PNG)

![zigbee_2](https://user-images.githubusercontent.com/73795363/103536026-13d74980-4e92-11eb-9ceb-521c9b18507b.PNG)
 Can you help me or do you need more informations?

Thanks for your help.

**Comment by Koenkk** [comment]
To add support follow this tutorial (zigbee2mqtt: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html, don't know if iobroker also has a tutorial @asgothian ?).

**Comment by D3rPap55t** [comment]
Hi,

thanks for your answer. I think this way is to complicated for me. I just started with iobroker some weeks ago. 
My workaround will be to use the zigbee adapter and the deconz adapter(supports the globe) parallel.

**Comment by Koenkk** [comment]
Good, I assume this can be closed then.

**Comment by asgothian** [comment]
> To add support follow this tutorial (zigbee2mqtt: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html, don't know if iobroker also has a tutorial @asgothian ?).

For future reference (i missed this comment) - there now exists a tutorial how to implement new devices when running iobroker rather than zigbee2mqtt. It is available [here](https://github.com/ioBroker/ioBroker.zigbee/wiki/How-to-support-a-new-device) and mainly describes how to access the information needed. It links back to the documentation on zigbee2mqtt.io.
