### ISSUE TITLE
 @Hacker-CB Hacker-CB mentioned this pull request 13 days ago Lonsonho Zigbee 3.0 Tuya Smart Led Lamp Licht E27 220V Rgb + W + C Werkt Met Smartthings echo Plus Hub Alexa Google Thuis Koenkk/zigbee2mqtt#4944 

### ISSUE THREAD

**Issue by ariekanarie2005** [Koenkk/zigbee-herdsman-converters#2024]
After my request in new devices this device was added in the latest version of zigbee2mqtt. (thanks for that!!!!)
After pairing in domoticz i see the right device 

| ZB-RGBCW | Zigbee 3.0 LED-bulb, RGBW LED | Router | 0x00124b00221cfc64 | 

But no devices are configured under the device in domoticz/eigen/zigbee2mqtt/
i restarted several time domoticz and raspberrypi, but still no devices.
Can someone give me suggestions ?

**Comment by Koenkk** [comment]
Please open an issue here: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues (needs to be added there)
