### ISSUE TITLE
Need options to expose 'preset' values

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee-herdsman-converters#2030]
It would be nice to be able to expose a mixed variable.
e.g. numeric + enum... example below because linking the commit didn't work after a rebase.

<img width="1293" alt="Screen Shot 2021-01-05 at 20 18 24" src="https://user-images.githubusercontent.com/379665/103690343-df988180-4f94-11eb-99a8-ca8d0574c7ec.png">

**Comment by sjorge** [comment]
AS mentioned this came about for color_temp_startup... but it could also be applied to color_temp it self.

<img width="1386" alt="image" src="https://user-images.githubusercontent.com/379665/103751991-638c5100-5009-11eb-832f-7ac2c2a71dea.png">

Is a screencap from the frontend, we could, expose those fixed kelvin presents that way too so there is no special handling needed in the frontend.

**Comment by Koenkk** [comment]
Was thinking about this, maybe we should provide a mapping of special values. So e.g. 

`{"type":"numeric","name":"color_temp_startup","property":"color_temp_startup","access":7,"presets": {"previous": 65535}}`

What do you think @nurikk ?

**Comment by nurikk** [comment]
> Was thinking about this, maybe we should provide a mapping of special values. So e.g.
> 
> `{"type":"numeric","name":"color_temp_startup","property":"color_temp_startup","access":7,"presets": {"previous": 65535}}`
> 
> What do you think @nurikk ?

Yes, this makes sense to have. But I would like to have an array of objects with title and value attributes(this will guarantee that this object will be easily extendable in the future)

Moreover, you can define presets for things like color/color temperature/brightness/etc. Currently, I'm generating these “preset buttons” on the frontend side

**Comment by nurikk** [comment]
> AS mentioned this came about for color_temp_startup... but it could also be applied to color_temp it self.
> 
> <img alt="image" width="1386" src="https://user-images.githubusercontent.com/379665/103751991-638c5100-5009-11eb-832f-7ac2c2a71dea.png">
> 
> Is a screencap from the frontend, we could, expose those fixed kelvin presents that way too so there is no special handling needed in the frontend.

Love this 👍

**Comment by sjorge** [comment]
So something like 

```
{"type":"numeric","name":"color_temp_startup","property":"color_temp_startup","access":7,"presets": [{"name": "previous", "value": 65535, "description": "Restore previous color_temp on cold power on."}]}
```

Where description is optional, but it would be useful to have I think.

**Comment by nurikk** [comment]
> So something like
> 
> ```
> {"type":"numeric","name":"color_temp_startup","property":"color_temp_startup","access":7,"presets": [{"name": "previous", "value": 65535, "description": "Restore previous color_temp on cold power on."}, {"name": "somethingelse", "value": 123}]}
> ```
> 
> Where description is optional, but it would be useful to have I think.

100% agree

**Comment by Koenkk** [comment]
Added, docs: https://github.com/Koenkk/zigbee2mqtt.io/blob/develop/docs/information/exposes.md#numeric

**Comment by nurikk** [comment]
I've added support to frontend. This features would be nice to patch with new presets, so I can remove that logic from frontend.

position
tilt
brightness
color_temp
