### ISSUE TITLE
BHT-002-GCLZB No converter available for 'commandSetTimeRequest'

### ISSUE THREAD

**Issue by pvermeij** [Koenkk/zigbee-herdsman-converters#2033]
**Zigbee2mqtt version:** 1.17.0
**Commit:** 1.17.0
**Coordinator type:** zStack3x0
**Coordinator revision:** 20201026

Zigbee2mqtt log shows the following:
```
Zigbee2MQTT:debug 2021-01-05 23:06:52: Received Zigbee message from 'Woonkamer - Thermostaat', type 'commandSetTimeRequest', cluster 'manuSpecificTuya', data '{"payload":[],"payloadSize":0}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-01-05 23:06:52: No converter available for 'BHT-002-GCLZB' with cluster 'manuSpecificTuya' and type 'commandSetTimeRequest' and data '{"payload":[],"payloadSize":0}'
```
Solution is provided on page [https://www.zigbee2mqtt.io/how_tos/how_to_support_new_tuya_devices.html](url) at _part 2. Adding your device_.

The following should be added to `devices.js` :

`onEvent: tuya.setTime, // Add this if you are getting no converter for 'commandSetTimeRequest'
`

**Comment by Koenkk** [comment]
Done, thanks!
