### ISSUE TITLE
ROB_200-007-0 is in devices.js and stil claimed to be unsupported

### ISSUE THREAD

**Issue by noci2012** [Koenkk/zigbee-herdsman-converters#2034]
The log mentions this after interviewing the device:  After successful pairing....

Device '0xdddddddddddddd' with Zigbee model 'ROB_200-007-0' and manufacturer name 'ROBB smarrt' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

The device is recognized AFTER adding a fingerprint entry to the devices.js entry for ROB_200-007-0
       fingerprint: [ {modelID: 'ROB_200-007-0', manufacturerName: 'ROBB smarrt'}],

The device does have 8 buttons:
4 on and 4 off, not 8 sets of buttons.
so on_5.. on_8 etc. seem to be wrong.

**Comment by Simanias** [comment]
Yup got exactly the same issue.
`Zigbee2MQTT:warn  2021-01-06 08:09:31: Received message from unsupported device with Zigbee model 'ROB_200-007-0' and manufacturer name 'ROBB smarrt'`

**Comment by defcon84** [comment]
This is the changeset where the exposes are added:
https://github.com/Koenkk/zigbee-herdsman-converters/commit/6433de2c950f5b7b403238a8ab298034abad52cf#diff-5520dd49755e0a353d3857b8963a91cb4b8d87a01b6b8eb7bb6cce1c180eac83R7028
These are indeed too many.

While not correct, the device works properly here with zigbee2mqtt version 1.17.0 commit: 07cdc9d.

ROBB smarrt with double 'r' is correct.

**Comment by Simanias** [comment]
Okey @defcon84 , thanks for the quick reply, however no joy here on 1.17.0.1 with home assistant.
Device shows up, but says unsupported and is not added to the MQTT integration.
<img width="1616" alt="Schermafbeelding 2021-01-06 om 10 38 16" src="https://user-images.githubusercontent.com/4976061/103753408-4ce6f980-500b-11eb-9406-55baf0eebb98.png">

**Comment by defcon84** [comment]
Hmm weird. 
Hassio z2m addon v1.17.0.1 uses z2m v1.17.0, so it should be the same as mine.
Can you post the full debug log while pairing.

**Comment by Simanias** [comment]
`Zigbee2MQTT:info  2021-01-06 11:01:43: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"commit":"1.17.0","coordinator":{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190223,"transportrev":2},"type":"zStack12"},"log_level":"info","network":{"channel":11,"extendedPanID":"0xdddddddddddddddd","panID":6754},"permit_join":true,"version":"1.17.0"}'
Zigbee2MQTT:warn  2021-01-06 11:02:34: Received message from unsupported device with Zigbee model 'ROB_200-007-0' and manufacturer name 'ROBB smarrt'`

**Comment by noci2012** [comment]
I upgraded to 1.17.0  (previous was 1.16.2) and it fails again.
until i add the fingerprint in devices.js

**Comment by noci2012** [comment]
PR #2040 fixes it.

**Comment by Koenkk** [comment]
Fixed by https://github.com/Koenkk/zigbee-herdsman-converters/pull/2040 

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
