### ISSUE TITLE
ROB_200-007-0 issues an unsupported command.... 

### ISSUE THREAD

**Issue by noci2012** [Koenkk/zigbee-herdsman-converters#2035]
The following is in the log for such a device:

Received Zigbee message from 'my4buttons', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":1,"fileVersion":22,"imageType":1008,"manufacturerCode":4644}' from endpoint 1 with groupID null

What ota entries are needed, how to find out?

**Comment by Koenkk** [comment]
Does the manufacturer publish OTA files for these devices? 
- If not you can ignore this
- If yes, add the firmware files here: https://github.com/koenkk/zigbee-ota and add `ota: ota.zigbeeOTA,` to the device.

**Comment by noci2012** [comment]
As i can't find firmware with ROBB-shop or manuafacturer, i added zf.ignore_genOta to the fromZigbee.

**Comment by noci2012** [comment]
PR #2040 updates this

**Comment by Koenkk** [comment]
Closing this as https://github.com/Koenkk/zigbee-herdsman-converters/pull/2040 is merged
