### ISSUE TITLE
Adventures with ColorCapabilities

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee-herdsman-converters#2037]
I'm creating this to track info/process in my advendtures with colorCapabilities...

- [x] read ColorCapabilities for all bulbs
- [x] collect data, check if they lie... sadly they do 👎 
- [ ] automatically do the right thing in the color convertor based on value

## read ColorCapabilities for all bulbs
This was easy, done as part of reading ColorTemperaturePhysicalMinMireds and ColorTemperaturePhysicalMaxMireds change. #2010

## collect data
Reported data

- IKEA Trådfri CWS: xy
- IKEA Tradfri WS: ct
- Innr RB 250 C: hs, **ehs**, xy, ct
- Innr RB 285 C: hs, ehs, xy, ct
- Muller Light Tint: hs, **ehs**, xy, ct
- IKEA FLOALT: ct
- IKEA GUNNARP: ct
- Hue E14: hs, ehs, xy, ct
- Osram E27: hs, ehs, xy, ct

This is bad news, as both the Innr RB 250 C, and Tint, report support for enhancedHue... which neither seem to accept.
The neither are also not rejecting it with UNSUPPORT_ATTRIBUTE, which means either: busted firmware or we maybe we're writing values that are out of range. I have not dug out wireshark yet to dig deep.

OK, they actually do respond!
<img width="699" alt="image" src="https://user-images.githubusercontent.com/379665/103805763-53e62a00-5054-11eb-89ee-c8f3aa6a537c.png">

<img width="666" alt="image" src="https://user-images.githubusercontent.com/379665/103805448-e5a16780-5053-11eb-8a5f-2858f8149e35.png">

But why would they announce support if they, in fact, do not support it... this is troublesome.

## automatically do the right thing in the color converter based on value
Looks like we can differentiate between xy and ct capable bulbs with this date...

Hue/Saturation is tricky... but something like this can work:

| bit | support  | converter |
| :-- | :--  | :-- |
| 0 | hs | enable hue/sat support in convertor |
| 1  | eh | enable enhancedHue if on manufacturer whitelist or enhancedHue == true |
| 3 | xy | enable xy |
| 4 | ct | enable ct |

manufacturer list seems to be:
- Hue
- Osram

Tint doesn't seem to work at all
Innr mixed bag of some bulbs working other not, so we should err on the side of not auto enabling.

### raw data dump
| device | lightingColorCtrl |
| --- | --- |
| **RGB(W)** ||
| Hue LCT012    | `{"colorCapabilities":31,"colorTempPhysicalMin":153,"colorTempPhysicalMax":500}` |
| Innr RB 285 C | `{"colorCapabilities":31,"colorTempPhysicalMin":153,"colorTempPhysicalMax":555}` |
| Innr RB 250 C | `{"colorCapabilities":31,"colorTempPhysicalMin":153,"colorTempPhysicalMax":555}` |
| Osram CLA60 RGBW Z3 | `{"colorCapabilities":31,"colorTempPhysicalMin":153,"colorTempPhysicalMax":526}` |
| TRADFRI bulb E27 CWS | `{"colorCapabilities":8}` |
| Tint LED bulb **GU10**/E14/**E27** 350/470/806 | `{"colorCapabilities":31,"colorTempPhysicalMin":153,"colorTempPhysicalMax":556}` |
| **WS** ||
| TRADFRI bulb GU10 WS 400lm | `{"colorCapabilities":16,"colorTempPhysicalMin":250,"colorTempPhysicalMax":454}` |
| GUNNARP panel 40*40 | `{"colorCapabilities":16,"colorTempPhysicalMin":250,"colorTempPhysicalMax":454}` |
| FLOALT panel WS 30x30 | `{"colorCapabilities":16,"colorTempPhysicalMin":250,"colorTempPhysicalMax":454}` |
|  FLOALT panel WS 30x90 | `{"colorCapabilities":16,colorTempPhysicalMin":250,"colorTempPhysicalMax":454}` |

**Comment by sjorge** [comment]
Uh ow, I managed to crash both the Innr and Tint bulbs!
I made a scene with hue/sat as it required enhancedHue, thinking that maybe they only  support it in scenes but not the command's (which is against ZCL spec, but hey)

<img width="1673" alt="image" src="https://user-images.githubusercontent.com/379665/103808992-1e900b00-5059-11eb-856e-337a25a6eeb7.png">

They keep looping this and need a hard poweroff for ~30 secs before working again.

**Comment by sjorge** [comment]
I managed to kill the entire mesh! I made a group with all 3 my test bulbs that have this issues. (Tint E27, Tint GU10, and Innr 250 C)

Added a scene, recalled the scene, all 3 spam like in the above cap.

I double checked that they payload for scene_add looked good, it did and it works fine on Hue/OSRAM/Innr RB 285 C... so pretty sure not a screw up on my side.

I wonder if I should write a short summery and send it to Muller Light and Innr. The later has been... rather hostile when asking for details before about one of there bulbs giving me the use our bridge and go away canned response.

**Comment by sjorge** [comment]
@Koenkk thanks for waiting, so I was wrong a bit on the values. I've added the stuff in the first comment.
But looks like Trådfri WS range from 250 - 454, All the RGB bulbs range from 153 - 500 (hue) or 556 (tint), others are in between those.

**Comment by Koenkk** [comment]
@sjorge cool, could you make a pr for this?

**Comment by sjorge** [comment]
So extend the presets with optional parameters to set the min/max? Something like:

```
    {
        zigbeeModel: ['RB 285 C'],
        model: 'RB 285 C',
        vendor: 'Innr',
        description: 'E27 bulb RGBW',
        extend: preset.light_onoff_brightness_colortemp_color,
        exposes: [e.light_brightness_colortemp_color(153, 555)],
        meta: {enhancedHue: false, applyRedFix: true, turnsOffAtBrightness1: true},
    },
```

**Comment by Koenkk** [comment]
Exactly! Although I think `e.light_brightness_colortemp_color([153, 555])` would be better here (1 argument instead of 2)

**Comment by sjorge** [comment]
Sounds good, I'll have a look at that... probably next week. I got side tracked by #2049 and have a few other things I need to take care of this weekend.

**Comment by sjorge** [comment]
Still on my radar, but not had time yet.

**Comment by MattWestb** [comment]
Müller i can find but the Innr module INNRZBM11 is on netherlander (NXP = X Philips semiconductors)  :-))
https://fccid.io/2AVYZINNRZBM11/Internal-Photos/Innr-ZB-Mod-v1-1-US-Internal-Photos-4718193

Wath MAC address do the müller normally using ?
Comparing the start with other known and if its matching you also knowing its the same chip inside.
deCONZ is using MAC prefix so can bing one good source if not doing like this:
![IMG_20200815_093908](https://user-images.githubusercontent.com/49618193/104779547-91973100-577f-11eb-8638-ac453fbfc2dc.jpg)

It was falling down in the first night from the kitchen ceilings (X-New GU10WS)  :-((((
**Ops someone have stolen the zigbee module !!!**

**Comment by MattWestb** [comment]
Müller is having the same MAC prefix as Xiaomi = NXP so if you is finding one Aqara or Xiaomi bulb you can doing one nice crashing network quartet !!

**Comment by sjorge** [comment]
I'm going to close this, we're using limiting color_temp to be within range. The colorCaps attribute is useless as a lot of  bulbs seem to advertise suporting ehs, but they don't.

The crashing behavior is fixed by setting `meta.enhancedHue` to false and scene_add now properly deals with this.

Also the color weirdness seems to be mostly fixed by picking either XY or hs for settingthe color.

Tint, Osram: use (e)hs
Innr, Hue, Ikea*: use xy

Ikea still had horrible greens, but it's 'by design' according to u/tradfri on reddit :(

**Comment by MattWestb** [comment]
Do you remember witch brands that was reporting the color capacity OK and not ??

Great work getting the scenes working in one good way in Z2M !!!!

**Comment by sjorge** [comment]
> Do you remember witch brands that was reporting the color capacity OK and not ??

First comment under  'collect data', the ones where ehs is bold advertise it but don't support it.
