### ISSUE TITLE
Adeo enki LXEK-2 add

### ISSUE THREAD

**Issue by jlc38780** [Koenkk/zigbee-herdsman-converters#2058]
Hello ,
I use home assistant and i'm note able to use zigbee_shepherd_devices and device.js (problem to write the Device.js files at the right place)
Can you add the device bellow .
This device have been test by a tierce person who confirm its work.

`
// Adeo Enki Lampe

{
    zigbeeModel: ['LXEK-2'],
    model: '9CZA-A806ST-Q1A/9CZA-G1521-Q1A/A806ST-Q1A-KIT',
    vendor: 'Adeo',
    description: 'ENKI Lexman E27 14W to 100W LED RGBW',
    extend: generic.light_onoff_brightness_colortemp_colorxy,
    fromZigbee: [
        fz.brightness, fz.color_colortemp, fz.on_off, fz.xiaomi_bulb_interval,
    ],
},

Link for e27:
https://www.leroymerlin.fr/v3/p/produits/ampoule-connectee-led-globe-95-e27-intensite-couleur-variables-enki-lexman-e1506793510

db:
{"id":14,"type":"Router","ieeeAddr":"0x5c0272fffe460e08","nwkAddr":15117,"manufId":4727,"manufName":"Adeo","powerSource":"Mains (single phase)","modelId":"LXEK-2","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[0,3,4,5,6,8,768,4096,64642],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"LXEK-2","manufacturerName":"Adeo","powerSource":1,"zclVersion":3,"appVersion":1,"stackVersion":2,"hwVersion":1,"dateCode":"20200526","swBuildId":"2.4.0"}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":1,"stackVersion":2,"hwVersion":1,"dateCode":"20200526","swBuildId":"2.4.0","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1610374861993}

List off command:

on
off
brightness_step_up
brightness_step_down
color_temperature_step_up
color_temperature_step_down
color_saturation_step_up
color_saturation_step_down
color_hue_step_up
color_hue_step_down
Thanks a lot for your awesome works!

**Comment by Koenkk** [comment]
Added, thanks!

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
