### ISSUE TITLE
Saswell SEA801-Zigbee running_state not working

### ISSUE THREAD

**Issue by MrFloppy** [Koenkk/zigbee-herdsman-converters#2062]
When trying to get the `running_state`, I always get the following error:
`
{
"level":"error",
"message":"No converter available for 'running_state' ()"
}
`

Is this a bug or is it me? I already set legacy to false for this device.

**Comment by Koenkk** [comment]
Reading (`/get`) the `running_state` is not supported for this device.

**Comment by MrFloppy** [comment]
Thanks for the information. Should the documentation be updated then?

**Comment by Koenkk** [comment]
@MrFloppy it's already fixed, docs will be updated with next release

**Comment by MrFloppy** [comment]
@Koenkk You are awesome. Thank you and keep up the good work.
