### ISSUE TITLE
Wrong recognized device YSR-MINI

### ISSUE THREAD

**Issue by Wasabules** [Koenkk/zigbee-herdsman-converters#2063]
hi,
I have the YSR-MINI RGBW version but i see "CCT" version when i pair it.
Home Assistant give me wrong option like "Warm/Cold light slider" but the RGBW version is not able to use this.

That probably because this version is not recognize ?

https://github.com/Koenkk/zigbee-herdsman-converters/blob/90158fca9813068c04ad8d989e5a3ec7cb712800/devices.js#L7201

My Database.db : 
`{"id":1,"type":"Coordinator","ieeeAddr":"0x00124b0018e3069a","nwkAddr":0,"manufId":0,"epList":[1,2,3,4,5,6,8,10,11,12,13,47,110,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":257,"epId":2,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":261,"epId":3,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"4":{"profId":263,"epId":4,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"5":{"profId":264,"epId":5,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"6":{"profId":265,"epId":6,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"8":{"profId":260,"epId":8,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"10":{"profId":260,"epId":10,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"11":{"profId":260,"epId":11,"devId":1024,"inClusterList":[1281],"outClusterList":[1280,1282],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"12":{"profId":49246,"epId":12,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"13":{"profId":260,"epId":13,"devId":5,"inClusterList":[25],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"47":{"profId":260,"epId":47,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"110":{"profId":260,"epId":110,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"interviewCompleted":true,"meta":{},"lastSeen":null}
{"id":2,"type":"Router","ieeeAddr":"0x00124b00226762e6","nwkAddr":45454,"manufId":0,"manufName":"YSRSAI","powerSource":"Mains (single phase)","modelId":"ZB-CL01","epList":[1,13],"endpoints":{"1":{"profId":49246,"epId":1,"devId":528,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"modelId":"ZB-CL01","manufacturerName":"YSRSAI","powerSource":1,"zclVersion":1,"appVersion":7,"stackVersion":2,"hwVersion":1,"dateCode":"20200914","swBuildId":"1.0.7"}}},"binds":[],"configuredReportings":[],"meta":{}},"13":{"profId":49246,"epId":13,"devId":57694,"inClusterList":[4096],"outClusterList":[4096],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":7,"stackVersion":2,"hwVersion":1,"dateCode":"20200914","swBuildId":"1.0.7","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1610410116177}
{"id":3,"type":"Router","ieeeAddr":"0x00124b002267628e","nwkAddr":24675,"manufId":0,"manufName":"YSRSAI","powerSource":"Mains (single phase)","modelId":"ZB-CL01","epList":[1,13],"endpoints":{"1":{"profId":49246,"epId":1,"devId":528,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"modelId":"ZB-CL01","manufacturerName":"YSRSAI","powerSource":1,"zclVersion":1,"appVersion":7,"stackVersion":2,"hwVersion":1,"dateCode":"20200914","swBuildId":"1.0.7"}}},"binds":[],"configuredReportings":[],"meta":{}},"13":{"profId":49246,"epId":13,"devId":57694,"inClusterList":[4096],"outClusterList":[4096],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":7,"stackVersion":2,"hwVersion":1,"dateCode":"20200914","swBuildId":"1.0.7","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1610410117873}
{"id":4,"type":"Router","ieeeAddr":"0x00124b002265cd3a","nwkAddr":40026,"manufId":0,"manufName":"YSRSAI","powerSource":"Mains (single phase)","modelId":"ZB-CL01","epList":[1,13],"endpoints":{"1":{"profId":49246,"epId":1,"devId":528,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"modelId":"ZB-CL01","manufacturerName":"YSRSAI","powerSource":1,"zclVersion":1,"appVersion":7,"stackVersion":2,"hwVersion":1,"dateCode":"20200914","swBuildId":"1.0.7"}}},"binds":[],"configuredReportings":[],"meta":{}},"13":{"profId":49246,"epId":13,"devId":57694,"inClusterList":[4096],"outClusterList":[4096],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":7,"stackVersion":2,"hwVersion":1,"dateCode":"20200914","swBuildId":"1.0.7","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1610410327975}
{"id":5,"type":"Router","ieeeAddr":"0x00124b0022676119","nwkAddr":50891,"manufId":0,"manufName":"YSRSAI","powerSource":"Mains (single phase)","modelId":"ZB-CL01","epList":[1,13],"endpoints":{"1":{"profId":49246,"epId":1,"devId":528,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"modelId":"ZB-CL01","manufacturerName":"YSRSAI","powerSource":1,"zclVersion":1,"appVersion":7,"stackVersion":2,"hwVersion":1,"dateCode":"20200914","swBuildId":"1.0.7"}}},"binds":[],"configuredReportings":[],"meta":{}},"13":{"profId":49246,"epId":13,"devId":57694,"inClusterList":[4096],"outClusterList":[4096],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":7,"stackVersion":2,"hwVersion":1,"dateCode":"20200914","swBuildId":"1.0.7","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1610410309105}
{"id":6,"type":"Router","ieeeAddr":"0x00124b00226763ca","nwkAddr":40044,"manufId":0,"manufName":"YSRSAI","powerSource":"Mains (single phase)","modelId":"ZB-CL01","epList":[1,13],"endpoints":{"1":{"profId":49246,"epId":1,"devId":528,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"modelId":"ZB-CL01","manufacturerName":"YSRSAI","powerSource":1,"zclVersion":1,"appVersion":7,"stackVersion":2,"hwVersion":1,"dateCode":"20200914","swBuildId":"1.0.7"}}},"binds":[],"configuredReportings":[],"meta":{}},"13":{"profId":49246,"epId":13,"devId":57694,"inClusterList":[4096],"outClusterList":[4096],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":7,"stackVersion":2,"hwVersion":1,"dateCode":"20200914","swBuildId":"1.0.7","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1610410899564}`

![image](https://user-images.githubusercontent.com/39313803/104257852-a3768c80-547e-11eb-83b8-b78dca095c5a.png)

Thanks !

**Comment by Koenkk** [comment]
In https://github.com/Koenkk/zigbee-herdsman-converters/pull/1379 @krencl described this is a RGB+CCT product, so you see both a cct slider and a color selector.

**Comment by Wasabules** [comment]
You have CCT RGBCCT RGB RGBW version for the product
https://fr.aliexpress.com/item/10000038540202.html

But i have the RGBW version and the cct slider is buggy with RGBW, is hard to have only white color on and the rgb off.

**Comment by krencl** [comment]
For me device working correctly. I got https://www.aliexpress.com/item/10000201621618.html RGB+CCT version.
```
{"id":6,"type":"Router","ieeeAddr":"0x00124b001cd6a473","nwkAddr":39018,"manufId":0,"manufName":"YSRSAI","powerSource":"Mains (single phase)","modelId":"ZB-CL01","epList":[1,13],"endpoints":{"1":{"profId":49246,"epId":1,"devId":528,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"modelId":"ZB-CL01","manufacturerName":"YSRSAI","powerSource":1,"zclVersion":1,"appVersion":6,"stackVersion":2,"hwVersion":1,"dateCode":"20200507","swBuildId":"1.0.6"}}},"binds":[],"configuredReportings":[],"meta":{}},"13":{"profId":49246,"epId":13,"devId":57694,"inClusterList":[4096],"outClusterList":[4096],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":6,"stackVersion":2,"hwVersion":1,"dateCode":"20200507","swBuildId":"1.0.6","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1610531819195}
```

![20210113_111116](https://user-images.githubusercontent.com/1188924/104439087-03f5ee80-5591-11eb-8fcd-c6c98363ca07.jpg)
![20210113_111105](https://user-images.githubusercontent.com/1188924/104439093-048e8500-5591-11eb-9ba7-f70371a40172.jpg)
![20210113_111058](https://user-images.githubusercontent.com/1188924/104439094-05271b80-5591-11eb-97ce-dcfa2f407b62.jpg)

**Comment by Wasabules** [comment]
Yes I know but I have the rgbw version and recognize like as rgb cct and that is buggy when I use the slider

**Comment by Koenkk** [comment]
I've compared your database.db entries but these are exactly the same so I don't think we can differentiate. I've ordered the RGBCCT version of this product

**Comment by Wasabules** [comment]
Do you have any tips to turn it as RGBW for have the right things in Home Assistant ? Bypass something ?

**Comment by Koenkk** [comment]
It's still unclear to me what the actual problem is. Why just not use the warm/cold slider?

**Comment by Wasabules** [comment]
Because is a RGBW not CCT, i have only One led for White, i dont have Cold and Warm, just Cold led on the strip.
But when i use the slider, that very buggy, the strip try to do something weird and is hard to have the maximum luminosity only with the with the white led

**Comment by Wasabules** [comment]
RGBW have only Cold White led
![image](https://user-images.githubusercontent.com/39313803/104508764-ff5d2480-55e8-11eb-9c49-a1b6ce70e796.png)

**Comment by Koenkk** [comment]
When this device would be marked as RGBW instead of RGBCCT Zigbee2MQTT will just leave out the color temperature slider (no white slider will be added if you expected that)

**Comment by Wasabules** [comment]
Yes i excepted a white slider but that is not possible ?

**Comment by Koenkk** [comment]
No, the Zigbee spec has no support for white values. If this device does it's a manufacturer specific extension and to support it you should sniff the traffic when controlling it with the original gateway: https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html
