### ISSUE TITLE
devices.js update for Telstra Sengled Bulb ILO Pull Request

### ISSUE THREAD

**Issue by RodWillaims** [Koenkk/zigbee-herdsman-converters#2065]
Hi, Sorry I tried to raise as a Pull request to support this new device but couldn't work how...

This is an update to version 1.17 

This is a variant of the "Sengled Element Touch (A19)" (It looks the same, so same picture can be used) and doesn't need any extra config.

There are two Socket variants of this bulb: ES/B22 both have the same Model.

   	{
        zigbeeModel: ['E11-U21U31'],
        model: 'E11-U21U31',
        vendor: 'Sengled',
        description: 'Telstra Sengled Element Touch(A19)',
        extend: preset.light_onoff_brightness,
        ota: ota.zigbeeOTA,
    },

Same manual MQTT config as the Sengled Element Touch(A19) can be used.

Thanks for all your efforts with this application.
Rod

**Comment by Koenkk** [comment]
Added, thanks!
