### ISSUE TITLE
Fantem MultiSensor ZB003-X

### ISSUE THREAD

**Issue by kirovilya** [Koenkk/zigbee-herdsman-converters#2071]
new strange device for Tuya.

https://aliexpress.ru/item/1005001878974427.html
![image](https://user-images.githubusercontent.com/8360230/104369677-e1cb8480-552e-11eb-8c9a-5cae62a5dc7d.png)
![image](https://user-images.githubusercontent.com/8360230/104369686-e5f7a200-552e-11eb-92b7-a2c0ae58f148.png)
![image](https://user-images.githubusercontent.com/8360230/104369775-09bae800-552f-11eb-911f-b9a473475ba2.png)

sniffer log
[multisensor.zip](https://github.com/Koenkk/zigbee-herdsman-converters/files/5804647/multisensor.zip)

issue for work with the device

**Comment by dsantos21** [comment]
Hi! I've bought this device too, thanks for your PR! Just to let you know, there's a small mistake in this code. Tamper is not been shown, but it's reported as occupancy. And occupancy is not been reported. 

Effect: zigbee2mqtt cannot report this sensor motion, but if you shake it, is does report as occupancy :) believe me, I tried it with 2 different devices (I bought 4 of them!). 

As I could see in debug, zone status first bit is occupancy, and bit 3 is tamper, so:

Motion detect: zonestatus=1

Tamper and motion detect (impossible to cause just one, I think): zonestatus=5

No motion, nor tamper: zonestatus=0

I've no experience with git, but let me know with o can help somehow! 

Ive attached the debug pictures, but obviously they lake context :/
![Screenshot_20210201-214430_Home Assistant](https://user-images.githubusercontent.com/44759158/106536917-1603e680-64d8-11eb-9f03-03fa59c09a25.png)

**Comment by dsantos21** [comment]
I think the bitwise shift was the problem (found it in from Zigbee2mqtt):

Original:
occupancy: (zoneStatus & 1<<2) > 0,

Solution (I think!):
occupancy: (zoneStatus & 1) > 0,

Course, I didn't try it. I have no idea how to test it... :( I just simulated the results using a site that allows you to run python expressions online.

**Comment by dsantos21** [comment]
Just to let you know: I've just edited my "fromZigbee" file with that proposed solution and it's working now :DDD
All I have to do is not reboot my instance :D. On the weekend I'll look how to propose a PR.

**Comment by drzony** [comment]
@dsantos21 @kirovilya 
I'm adding a new type for Tuya cluster. Could you comment with the output of your debug log?
I need something like this, but from this sensor:
```
Zigbee2MQTT:debug 2021-03-23 13:23:32: Received Zigbee message from '0xbc33acfffe462752', type 'raw', cluster 'manuSpecificTuya', data '{"data":[9,127,6,0,56,102,4,0,1,2],"type":"Buffer"}' from endpoint 1 with groupID 0
```
