### ISSUE TITLE
Sengled E1A-AC2 downlights not parsing any data

### ISSUE THREAD

**Issue by pnewnam** [Koenkk/zigbee-herdsman-converters#208]
My setup is Home Assistant, Mosquitto, zigbee2mqtt all running in Docker.  

I also have 2x Sengled bulbs, a Hue lightbulb, a Xiaomi human body sensor which seem to connect correctly.  It's just the 6 x Sengled downlights which are not parsing data correctly.

The Sengled downlights initially get picked up as `E1A-AC2` and not supported:

> 2019-1-13 10:07:06 - warn: Message without device!
> 2019-1-13 10:07:06 - debug: Received zigbee message of type 'devIncoming' with data '"0xb0ce18140307a0e5"' of device 'E1A-AC2' (0xb0ce18140307a0e5)
> 2019-1-13 10:07:06 - info: Device incoming...
> 2019-1-13 10:07:06 - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"device incoming"}'
> 2019-1-13 10:07:06 - info: New device with address 0xb0ce18140307a0e5 connected!
> 2019-1-13 10:07:06 - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":"0xb0ce18140307a0e5"}'
> 2019-1-13 10:07:06 - warn: Device with modelID 'E1A-AC2' is not supported.
> 2019-1-13 10:07:06 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
> 2019-1-13 10:07:06 - debug: Received zigbee message of type 'devStatus' with data '"online"' of device 'E1A-AC2' (0xb0ce18140307a0e5)
> 2019-1-13 10:07:06 - warn: Device with modelID 'E1A-AC2' is not supported.
> 2019-1-13 10:07:06 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
> 2019-1-13 10:07:07 - debug: Received zigbee message of type 'devInterview' with data '"0xb0ce18140307b7ec"'
> 

Following the instructions at https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html I add the following:

>     {
>         zigbeeModel: ['E1A-AC2'],
>         model: 'E1ACA4ABE38A',
>         vendor: 'Sengled',
>         description: 'Classic smart lighting downlight plus driver',
>         supports: 'lights on off and brightness',
>         fromZigbee: [],
>         toZigbee: [],    
>     },

and then in the logs see the following:

> Sat, 12 Jan 2019 23:14:34 GMT zigbee-shepherd:af dispatchIncomingMsg(): type: zclIncomingMsg, msg: [object Object],
>   zigbee2mqtt:debug 2019-1-13 10:14:34 Received zigbee message of type 'devInterview' with data '"0xb0ce18140307b7ec"',
>   zigbee2mqtt:warn 2019-1-13 10:14:34 Message without device!,
> Sat, 12 Jan 2019 23:14:34 GMT zigbee-shepherd Device: 0xb0ce18140307b7ec join the network.,
>   zigbee2mqtt:debug 2019-1-13 10:14:34 Received zigbee message of type 'devIncoming' with data '"0xb0ce18140307b7ec"' of device 'E1A-AC2' (0xb0ce18140307b7ec),
>   zigbee2mqtt:info 2019-1-13 10:14:34 Device incoming...,
>   zigbee2mqtt:info 2019-1-13 10:14:34 MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"device incoming"}',
>   zigbee2mqtt:debug 2019-1-13 10:14:34 Received zigbee message of type 'devStatus' with data '"online"' of device 'E1A-AC2' (0xb0ce18140307b7ec),
> 

but don't see the the keyword: `cid`

Any ideas on how to progress?  Many thanks.

FYI full log below:

> 2019-01-12T23:14:34.841Z serialport:unixRead waiting for readable because of code: EAGAIN,
> 2019-01-12T23:14:34.841Z serialport:poller Polling for "readable",
> Sat, 12 Jan 2019 23:14:34 GMT zigbee-shepherd:af dispatchIncomingMsg(): type: zclIncomingMsg, msg: [object Object],
> Sat, 12 Jan 2019 23:14:34 GMT zigbee-shepherd:request REQ --> AF:dataRequest, transId: 44,
> Sat, 12 Jan 2019 23:14:34 GMT cc-znp:SREQ --> AF:dataRequest, { dstaddr: 6219, destendpoint: 1, srcendpoint: 1, clusterid: 2821, transid: 44, options: 48, radius: 30, len: 9, data: <Buffer 00 2c 00 1b 01 1c 01 1d 01> },
> 2019-01-12T23:14:34.843Z serialport:main _write 24 bytes of data,
> 2019-01-12T23:14:34.843Z serialport:bindings write 24 bytes,
> 2019-01-12T23:14:34.844Z serialport:unixWrite Starting write 24 bytes offset 0 bytesToWrite 24,
> 2019-01-12T23:14:34.844Z serialport:unixWrite write returned null 24,
> 2019-01-12T23:14:34.844Z serialport:unixWrite wrote 24 bytes,
> 2019-01-12T23:14:34.844Z serialport:unixWrite Finished writing 24 bytes,
> 2019-01-12T23:14:34.844Z serialport:main binding.write write finished,
> 2019-01-12T23:14:34.851Z serialport:poller received "readable",
> 2019-01-12T23:14:34.851Z serialport:bindings read,
> 2019-01-12T23:14:34.852Z serialport:unixRead Starting read,
> 2019-01-12T23:14:34.852Z serialport:unixRead Finished read 6 bytes,
> 2019-01-12T23:14:34.852Z serialport:main binding.read finished,
> Sat, 12 Jan 2019 23:14:34 GMT cc-znp { sof: 254,,,
> ,,
>   type: 'SRSP',,
>   subsys: 'AF',,
>   cmd: 'dataRequest',,
>   payload: { status: 0 },,
>   fcs: 100,,
>   csum: 100 },
> 2019-01-12T23:14:34.853Z serialport:main _read reading,
> 2019-01-12T23:14:34.854Z serialport:bindings read,
> 2019-01-12T23:14:34.854Z serialport:unixRead Starting read,
> Sat, 12 Jan 2019 23:14:34 GMT cc-znp:SRSP <-- AF:dataRequest, { status: 0 },
> Sat, 12 Jan 2019 23:14:34 GMT zigbee-shepherd:request RSP <-- AF:dataRequest, status: 0,
> 2019-01-12T23:14:34.855Z serialport:unixRead waiting for readable because of code: EAGAIN,
> 2019-01-12T23:14:34.855Z serialport:poller Polling for "readable",
> 2019-01-12T23:14:34.892Z serialport:poller received "readable",
> 2019-01-12T23:14:34.892Z serialport:bindings read,
> 2019-01-12T23:14:34.893Z serialport:unixRead Starting read,
> 2019-01-12T23:14:34.893Z serialport:unixRead Finished read 8 bytes,
> 2019-01-12T23:14:34.893Z serialport:main binding.read finished,
> Sat, 12 Jan 2019 23:14:34 GMT cc-znp { sof: 254,,,
> ,,
>   type: 'AREQ',,
>   subsys: 'AF',,
>   cmd: 'dataConfirm',,
>   payload: { status: 0, endpoint: 1, transid: 44 },,
>   fcs: 234,,
>   csum: 234 },
> 2019-01-12T23:14:34.895Z serialport:main _read reading,
> 2019-01-12T23:14:34.895Z serialport:bindings read,
> 2019-01-12T23:14:34.895Z serialport:unixRead Starting read,
> Sat, 12 Jan 2019 23:14:34 GMT cc-znp:AREQ <-- AF:dataConfirm, { status: 0, endpoint: 1, transid: 44 },
> Sat, 12 Jan 2019 23:14:34 GMT zigbee-shepherd:af dispatchIncomingMsg(): type: dataConfirm, msg: [object Object],
> Sat, 12 Jan 2019 23:14:34 GMT zigbee-shepherd:msgHdlr IND <-- AF:dataConfirm, transId: 44,
> 2019-01-12T23:14:34.896Z serialport:unixRead waiting for readable because of code: EAGAIN,
> 2019-01-12T23:14:34.896Z serialport:poller Polling for "readable",
> 2019-01-12T23:14:34.897Z serialport:poller received "readable",
> 2019-01-12T23:14:34.897Z serialport:bindings read,
> 2019-01-12T23:14:34.897Z serialport:unixRead Starting read,
> 2019-01-12T23:14:34.897Z serialport:unixRead Finished read 44 bytes,
> 2019-01-12T23:14:34.898Z serialport:main binding.read finished,
> Sat, 12 Jan 2019 23:14:34 GMT cc-znp { sof: 254,,
>   len: 39,,
>   type: 'AREQ',,
>   subsys: 'AF',,
>   cmd: 'incomingMsg',,
>   payload: ,
>    { groupid: 0,,
>      clusterid: 2821,,
>      srcaddr: 6219,,
>      srcendpoint: 1,,
>      dstendpoint: 1,,
>      wasbroadcast: 0,,
>      linkquality: 28,,
>      securityuse: 0,,
>      timestamp: 11817334,,
>      transseqnumber: 0,,
>      len: 19,,
>      data: <Buffer 18 2c 01 1b 01 00 21 00 00 1c 01 00 20 ff 1d 01 00 28 b2> },,
>   fcs: 39,,
>   csum: 39 },
> 2019-01-12T23:14:34.903Z serialport:main _read reading,
> 2019-01-12T23:14:34.903Z serialport:bindings read,
> 2019-01-12T23:14:34.904Z serialport:unixRead Starting read,
> Sat, 12 Jan 2019 23:14:34 GMT cc-znp:AREQ <-- AF:incomingMsg, { groupid: 0, clusterid: 2821, srcaddr: 6219, srcendpoint: 1, dstendpoint: 1, wasbroadcast: 0, linkquality: 28, securityuse: 0, timestamp: 11817334, transseqnumber: 0, len: 19, data: <Buffer 18 2c 01 1b 01 00 21 00 00 1c 01 00 20 ff 1d 01 00 28 b2> },
> Sat, 12 Jan 2019 23:14:34 GMT zigbee-shepherd:af dispatchIncomingMsg(): type: incomingMsg, msg: [object Object],
> Sat, 12 Jan 2019 23:14:34 GMT zigbee-shepherd:msgHdlr IND <-- AF:incomingMsg, transId: 0,
> 2019-01-12T23:14:34.908Z serialport:unixRead waiting for readable because of code: EAGAIN,
> 2019-01-12T23:14:34.909Z serialport:poller Polling for "readable",
> Sat, 12 Jan 2019 23:14:34 GMT zigbee-shepherd:af dispatchIncomingMsg(): type: zclIncomingMsg, msg: [object Object],
>   zigbee2mqtt:debug 2019-1-13 10:14:34 Received zigbee message of type 'devInterview' with data '"0xb0ce18140307b7ec"',
>   zigbee2mqtt:warn 2019-1-13 10:14:34 Message without device!,
> Sat, 12 Jan 2019 23:14:34 GMT zigbee-shepherd Device: 0xb0ce18140307b7ec join the network.,
>   zigbee2mqtt:debug 2019-1-13 10:14:34 Received zigbee message of type 'devIncoming' with data '"0xb0ce18140307b7ec"' of device 'E1A-AC2' (0xb0ce18140307b7ec),
>   zigbee2mqtt:info 2019-1-13 10:14:34 Device incoming...,
>   zigbee2mqtt:info 2019-1-13 10:14:34 MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"device incoming"}',
>   zigbee2mqtt:debug 2019-1-13 10:14:34 Received zigbee message of type 'devStatus' with data '"online"' of device 'E1A-AC2' (0xb0ce18140307b7ec),
>   zigbee2mqtt:debug 2019-1-13 10:18:57 Saving state to file /app/data/state.json,
>   zigbee2mqtt:debug 2019-1-13 10:23:57 Saving state to file /app/data/state.json,
>   zigbee2mqtt:debug 2019-1-13 10:28:57 Saving state to file /app/data/state.json,
>   zigbee2mqtt:debug 2019-1-13 10:33:57 Saving state to file /app/data/state.json,
>   zigbee2mqtt:debug 2019-1-13 10:38:57 Saving state to file /app/data/state.json,
>   zigbee2mqtt:debug 2019-1-13 10:43:57 Saving state to file /app/data/state.json,

**Comment by pnewnam** [comment]
Thanks for the help.  Still not - this is the log information.  Hopefully I am including all of the data needed?

> 
> 2019-01-14T06:25:45.154683447Z Mon, 14 Jan 2019 06:25:45 GMT zigbee-shepherd:af dispatchIncomingMsg(): type: zclIncomingMsg, msg: [object Object],
> 2019-01-14T06:25:45.156258905Z   zigbee2mqtt:debug 2019-1-14 17:25:45 Received zigbee message of type 'devInterview' with data '"0xb0ce18140307a0e5"',
> 2019-01-14T06:25:45.156899520Z   zigbee2mqtt:warn 2019-1-14 17:25:45 Message without device!,
> 2019-01-14T06:25:45.157581067Z Mon, 14 Jan 2019 06:25:45 GMT zigbee-shepherd:request REQ --> AF:dataRequest, transId: 224,
> 2019-01-14T06:25:45.158185776Z Mon, 14 Jan 2019 06:25:45 GMT cc-znp:SREQ --> AF:dataRequest, { dstaddr: 20548, destendpoint: 1, srcendpoint: 1, clusterid: 6, transid: 224, options: 48, radius: 30, len: 6, data: <Buffer 00 df 0c 00 00 f0> },
> 2019-01-14T06:25:45.158571525Z 2019-01-14T06:25:45.158Z serialport:main _write 21 bytes of data,
> 2019-01-14T06:25:45.158742760Z 2019-01-14T06:25:45.158Z serialport:bindings write 21 bytes,
> 2019-01-14T06:25:45.159118032Z 2019-01-14T06:25:45.159Z serialport:unixWrite Starting write 21 bytes offset 0 bytesToWrite 21,
> 2019-01-14T06:25:45.159605617Z 2019-01-14T06:25:45.159Z serialport:unixWrite write returned null 21,
> 2019-01-14T06:25:45.159769751Z 2019-01-14T06:25:45.159Z serialport:unixWrite wrote 21 bytes,
> 2019-01-14T06:25:45.159917102Z 2019-01-14T06:25:45.159Z serialport:unixWrite Finished writing 21 bytes,
> 2019-01-14T06:25:45.160083122Z 2019-01-14T06:25:45.159Z serialport:main binding.write write finished,
> 2019-01-14T06:25:45.168769230Z 2019-01-14T06:25:45.167Z serialport:poller received "readable",
> 2019-01-14T06:25:45.168813839Z 2019-01-14T06:25:45.167Z serialport:bindings read,
> 2019-01-14T06:25:45.168821288Z 2019-01-14T06:25:45.167Z serialport:unixRead Starting read,
> 2019-01-14T06:25:45.168827138Z 2019-01-14T06:25:45.167Z serialport:unixRead Finished read 6 bytes,
> 2019-01-14T06:25:45.168832989Z 2019-01-14T06:25:45.167Z serialport:main binding.read finished,
> 2019-01-14T06:25:45.168838519Z Mon, 14 Jan 2019 06:25:45 GMT cc-znp { sof: 254,,
> 2019-01-14T06:25:45.168844023Z   len: 1,,
> 2019-01-14T06:25:45.168849227Z   type: 'SRSP',,
> 2019-01-14T06:25:45.168854459Z   subsys: 'AF',,
> 2019-01-14T06:25:45.168859648Z   cmd: 'dataRequest',,
> 2019-01-14T06:25:45.168865067Z   payload: { status: 0 },,
> 2019-01-14T06:25:45.168878862Z   fcs: 100,,
> 2019-01-14T06:25:45.168884337Z   csum: 100 },
> 2019-01-14T06:25:45.168889624Z 2019-01-14T06:25:45.168Z serialport:main _read reading,

**Comment by Koenkk** [comment]
@pnewnam the `devInterview` messages are not interesting (you can ignore them). Are you able to turn the bulb on/off?

**Comment by pnewnam** [comment]
No I'm not able to control the downlights.  They appear in database.db though:

> {"id":7,"type":"EndDevice","ieeeAddr":"0xb0ce18140307b7f0","nwkAddr":40720,"manufId":4448,"manufName":"sengled","powerSource":"Unknown","modelId":"E1A-AC2","epList":[1],"status":"online","joinTime":1547444732,"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,8,1794,2821],"outClusterList":[25],"clusters":{}}},"_id":"dEdAq6rYMthE5h1s"}
> {"id":7,"type":"EndDevice","ieeeAddr":"0xb0ce18140307b7f0","nwkAddr":40720,"manufId":4448,"manufName":"sengled","powerSource":"Unknown","modelId":"E1A-AC2","epList":[1],"status":"online","joinTime":1547444732,"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,8,1794,2821],"outClusterList":[25],"clusters":{"genBasic":{"dir":{"value":1},"attrs":{"zclVersion":1,"appVersion":1,"stackVersion":0,"hwVersion":1,"manufacturerName":"sengled","modelId":"E1A-AC2","powerSource":0,"appProfileVersion":0}},"genIdentify":{"dir":{"value":1},"attrs":{"identifyTime":0}},"genGroups":{"dir":{"value":1},"attrs":{"nameSupport":0}},"genScenes":{"dir":{"value":1},"attrs":{"count":0,"currentScene":0,"currentGroup":0,"sceneValid":0,"nameSupport":0}},"genOnOff":{"dir":{"value":1},"attrs":{"onOff":1}},"genLevelCtrl":{"dir":{"value":1},"attrs":{"currentLevel":255,"onLevel":255}},"genOta":{"dir":{"value":2},"attrs":{}},"seMetering":{"dir":{"value":1},"attrs":{"currentSummDelivered":{"0":256,"1":0},"status":0,"unitOfMeasure":0,"multiplier":1,"divisor":10000,"summaFormatting":33,"demandFormatting":33,"historicalConsumpFormatting":33,"meteringDeviceType":0,"instantaneousDemand":0}},"haDiagnostic":{"dir":{"value":1},"attrs":{"averageMacRetryPerApsMessageSent":0,"lastMessageLqi":255,"lastMessageRssi":-85}}}}},"_id":"dEdAq6rYMthE5h1s"}

but never makes it to the MQTT server (except to log pairing is going to happen).  The other devices get sent to the MQTT server so I know the setup is working but the data for the E1A-AC2 downlights does not seem to appear anywhere.

In the MQTT subscription this is all I see when I try to pair again:

**zigbee2mqtt/bridge/log**

> {"type":"pairing","message":"device incoming"}

They also appear in the configuration.yaml:

```
  '0xb0ce18140307b7f0':
    friendly_name: '0xb0ce18140307b7f0'
    retain: false
```

Is there some logging I am missing?  It seems to not be parsing the data coming from the device and maybe failing silently?

**Comment by Koenkk** [comment]
@pnewnam can you provide the log when trying to control the bulb? And what data do you expect from the bulb?

**Comment by pnewnam** [comment]
@Koenkk I'm using MQTT.fx to publish commands.  Works fine with the Sengled bulb.  Odd thing is the Sengled downlight (0xb0ce18140307a0e5) seems to be registered with zigbee2mqtt because I can see it in the configuration.yaml:

```
  '0xb0ce18140307a0e5':
    friendly_name: '0xb0ce18140307a0e5'
    retain: false
```
and in the database.db
```
{"id":13,"type":"EndDevice","ieeeAddr":"0xb0ce18140307a0e5","nwkAddr":2164,"manufId":4448,"manufName":"sengled","powerSource":"Unknown","modelId":"E1A-AC2","epList":[1],"status":"offline","joinTime":null,"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,8,1794,2821],"outClusterList":[25],"clusters":{"genBasic":{"dir":{"value":1},"attrs":{"zclVersion":1,"appVersion":1,"stackVersion":0,"hwVersion":1,"manufacturerName":"sengled","modelId":"E1A-AC2","powerSource":0,"appProfileVersion":0}},"genIdentify":{"dir":{"value":1},"attrs":{"identifyTime":0}},"genGroups":{"dir":{"value":1},"attrs":{"nameSupport":0}},"genScenes":{"dir":{"value":1},"attrs":{"count":0,"currentScene":0,"currentGroup":0,"sceneValid":0,"nameSupport":0}},"genOnOff":{"dir":{"value":1},"attrs":{"onOff":1}},"genLevelCtrl":{"dir":{"value":1},"attrs":{"currentLevel":255,"onLevel":255}},"genOta":{"dir":{"value":2},"attrs":{}},"seMetering":{"dir":{"value":1},"attrs":{"currentSummDelivered":{"0":0,"1":0},"status":0,"unitOfMeasure":0,"multiplier":1,"divisor":10000,"summaFormatting":33,"demandFormatting":33,"historicalConsumpFormatting":33,"meteringDeviceType":0,"instantaneousDemand":121}},"haDiagnostic":{"dir":{"value":1},"attrs":{"averageMacRetryPerApsMessageSent":0,"lastMessageLqi":255,"lastMessageRssi":-76}}}}},"_id":"GsviJtRnSyTIWaA3"}
{"id":13,"type":"EndDevice","ieeeAddr":"0xb0ce18140307a0e5","nwkAddr":2164,"manufId":4448,"manufName":"sengled","powerSource":"Unknown","modelId":"E1A-AC2","epList":[1],"status":"offline","joinTime":null,"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,8,1794,2821],"outClusterList":[25],"clusters":{"genBasic":{"dir":{"value":1},"attrs":{"zclVersion":1,"appVersion":1,"stackVersion":0,"hwVersion":1,"manufacturerName":"sengled","modelId":"E1A-AC2","powerSource":0,"appProfileVersion":0}},"genIdentify":{"dir":{"value":1},"attrs":{"identifyTime":0}},"genGroups":{"dir":{"value":1},"attrs":{"nameSupport":0}},"genScenes":{"dir":{"value":1},"attrs":{"count":0,"currentScene":0,"currentGroup":0,"sceneValid":0,"nameSupport":0}},"genOnOff":{"dir":{"value":1},"attrs":{"onOff":1}},"genLevelCtrl":{"dir":{"value":1},"attrs":{"currentLevel":255,"onLevel":255}},"genOta":{"dir":{"value":2},"attrs":{}},"seMetering":{"dir":{"value":1},"attrs":{"currentSummDelivered":{"0":0,"1":0},"status":0,"unitOfMeasure":0,"multiplier":1,"divisor":10000,"summaFormatting":33,"demandFormatting":33,"historicalConsumpFormatting":33,"meteringDeviceType":0,"instantaneousDemand":121}},"haDiagnostic":{"dir":{"value":1},"attrs":{"averageMacRetryPerApsMessageSent":0,"lastMessageLqi":255,"lastMessageRssi":-76}}}}},"_id":"GsviJtRnSyTIWaA3"}
```

but if I try to send a set command:

`zigbee2mqtt/0xb0ce18140307a0e5/set`
with the payload:
`{"state":"ON"}`

zigbee2mqtt crashes in the docker container with the following error and stack trace:

```

  zigbee2mqtt:debug 2019-1-16 17:51:07 Received MQTT message on 'zigbee2mqtt/0xb0ce18140307a0e5/set' with data '{"state":"ON"}'


/app/lib/extension/devicePublish.js:118


            const converter = model.toZigbee.find((c) => c.key.includes(key));


                                             ^



TypeError: Cannot read property 'find' of undefined


    at Object.keys.forEach (/app/lib/extension/devicePublish.js:118:46)


    at Array.forEach (<anonymous>)


    at DevicePublish.onMQTTMessage (/app/lib/extension/devicePublish.js:117:27)


    at results.extensions.filter.map (/app/lib/controller.js:121:27)


    at Array.map (<anonymous>)


    at Controller.onMQTTMessage (/app/lib/controller.js:121:14)


    at MQTT.onMessage (/app/lib/mqtt.js:81:18)


    at emitThree (events.js:136:13)


    at MqttClient.emit (events.js:217:7)


    at MqttClient._handlePublish (/app/node_modules/mqtt/lib/client.js:987:12)


npm ERR! code ELIFECYCLE


npm ERR! errno 1


npm ERR! zigbee2mqtt@1.0.1 start: `node index.js`


npm ERR! Exit status 1



**Comment by pnewnam** [comment]
Contents of crash log:

```
/app # cat /root/.npm/_logs/2019-01-16T06_51_07_590Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.4.1
3 info using node@v8.14.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle zigbee2mqtt@1.0.1~prestart: zigbee2mqtt@1.0.1
6 info lifecycle zigbee2mqtt@1.0.1~start: zigbee2mqtt@1.0.1
7 verbose lifecycle zigbee2mqtt@1.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle zigbee2mqtt@1.0.1~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle zigbee2mqtt@1.0.1~start: CWD: /app
10 silly lifecycle zigbee2mqtt@1.0.1~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle zigbee2mqtt@1.0.1~start: Returned: code: 1  signal: null
12 info lifecycle zigbee2mqtt@1.0.1~start: Failed to exec start script
13 verbose stack Error: zigbee2mqtt@1.0.1 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid zigbee2mqtt@1.0.1
15 verbose cwd /app
16 verbose Linux 4.15.0-43-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v8.14.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error zigbee2mqtt@1.0.1 start: `node index.js`
22 error Exit status 1
23 error Failed at the zigbee2mqtt@1.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by Koenkk** [comment]
Can you try with
```js
    {
        zigbeeModel: ['E1A-AC2'],
        model: 'E1ACA4ABE38A',
        vendor: 'Sengled',
        description: 'Classic smart lighting downlight plus driver',
        supports: generic.light_onoff_brightness().supports,
        fromZigbee: generic.light_onoff_brightness().fromZigbee,
        toZigbee: generic.light_onoff_brightness().toZigbee,
    },
```

**Comment by pnewnam** [comment]
Success!  That worked great!  Thanks for your help.  Can I do a pull request to add the light? btw - awesome work with the project.

**Comment by Koenkk** [comment]
Yes, please make a pr! :)

**Comment by ryanbeaton** [comment]
Your code block will need to be updated for a PR ;)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pnewnam** [comment]
I saw it broke CI - @ryanbeaton should it be?

`extend: generic.light_onoff_brightness`

**Comment by pnewnam** [comment]
Does docker use an older version?

**Comment by pnewnam** [comment]
@Koenkk I see docker comes from https://github.com/Koenkk/zigbee2mqtt/releases
and is locked into this version of zigbee-shepherd from last year
git+https://github.com/Koenkk/zigbee-shepherd.git#ce52ac4131e2a505af6197b4a26d2b5360e4eb80
 - is there a reason to keep the docker instance at that version?

**Comment by Koenkk** [comment]
The -dev docker image tracks the dev version. See https://koenkk.github.io/zigbee2mqtt/information/docker.html#tags
