### ISSUE TITLE
Paulmann 929.63 doesn't work

### ISSUE THREAD

**Issue by Schmakus** [Koenkk/zigbee-herdsman-converters#2080]
Hi,

Paulmann 929.63 does not work because this lamp is recognized as H036-0006.
In the devices.js, however, this is listed as 929.63

**Comment by Schmakus** [comment]
I've changed the devices.js an now it works fine!

`     {
        zigbeeModel: ['H036-0006'],
        model: '929.63',
        vendor: 'Paulmann',
        description: 'SmartHome Zigbee LED-Modul Coin 1x6W Tunable White',
        extend: preset.light_onoff_brightness_colortemp,
    },`

**Comment by Koenkk** [comment]
Added, thanks!
