### ISSUE TITLE
support for Müller Licht Globe

### ISSUE THREAD

**Issue by simulot** [Koenkk/zigbee-herdsman-converters#2093]
The Müller Licht LED Globe white+color isn't not yet supported by the latest stable version of ZigbeeMqtt  

I managed to set up the device by adding following record do devices.js file:

```js
    //  Device '0x00158d00012e539d' with Zigbee model 'tint-ExtendedColor' and manufacturer name 'MLI' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
    {
        zigbeeModel: ['tint-ExtendedColor'],
        model: '404036',
        vendor: 'Müller Licht',
        description: 'tint LED-Globeform white+color',
        extend: preset.light_onoff_brightness_colortemp_colorxy,
        toZigbee: preset.light_onoff_brightness_colortemp_colorxy.toZigbee.concat([tz.tint_scene]),
    },  
```
I'm not sure how to merge it with existing definition.
[Here is the link to the product](https://www.mueller-licht.de/produktinformationen/artikel/404036/)

I think this is same device as mentioned in #2020

**Comment by Koenkk** [comment]
Added, thanks!
