### ISSUE TITLE
HLQDQ01LM shows 647 entries on toZigbee?

### ISSUE THREAD

**Issue by pedrolamas** [Koenkk/zigbee-herdsman-converters#2095]
```javascript
var zigbeeHerdsmanConverters = require("zigbee-herdsman-converters");

var device = zigbeeHerdsmanConverters.devices
  .find(x => x.model === "HLQDQ01LM");

document.write(device.toZigbee.length); //this outputs 647
```

Here's a sample sandbox showing the issue:

https://codesandbox.io/s/empty-forest-0n28o?fontsize=14&hidenavigation=1&theme=dark

**Comment by pedrolamas** [comment]
I believe the problem is on this line right on the bottom of "devices.js":

```javascript
device = Object.assign({}, device.extend, device);
```

Instead of a copy of the extends, this is assigning the **content** of the extend to the new device entry!

**Comment by pedrolamas** [comment]
Confirmed: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#deep_clone

**Comment by pedrolamas** [comment]
I see 2 ways of fixing this issue:

1. Change the presets to functions (like the ones used with exposes) so it will return a new instance every time it is used
2. Add a deep clone operation to the `Object.assign` code above.

I'm inclined to option 1, but wanted to check with @Koenkk before moving ahead with a fix.

**Comment by Koenkk** [comment]
Lol! Although I like both ways to fix it I prefer option 2 since this keeps the extend simpler.

**Comment by pedrolamas** [comment]
Option 2 is a doable but a bit more tricky, as we can't use a simple JSON deep clone like `JSON.parse(JSON.stringify(obj))`, as there are functions inside the extended stuff (on the `toZigbee` and `fromZigbee` properties)

I will take a look into this, but I have to admit that given the above my inclination is for option 1.

**Comment by Koenkk** [comment]
Agree, now I'm also convinced of option 1 being the best solution here.

**Comment by pedrolamas** [comment]
Going with that then, sending a PR in a bit!

**Comment by pedrolamas** [comment]
PR is in, I've also refactored the way the new device object is created.

Interesting fact: the code before the PR copies all properties from the base (the extends), then copies in the properties from the new object, overwriting any base ones with the same name; however, the exception is the `meta` property, as it will try to merge the sub-properties.

I kept the above behavior in my refactor.
