### ISSUE TITLE
Add new device: Gledopto GL-FL-004P

### ISSUE THREAD

**Issue by 70MM13** [Koenkk/zigbee-herdsman-converters#2109]
Hello,

I have an unsupported device, which identified almost the same as another Gledopto product I have (only model differs).
I added the following to devices.js to make it work:
```
{
        zigbeeModel: ['GL-FL-004P'],
        model: 'GL-FL-004P',
        vendor: 'Gledopto',
        description: 'Zigbee 10W floodlight RGB CCT pro',
        extend: preset.gledopto.light_onoff_brightness_colortemp_colorxy,
},
```
Can you add this please?

Thanks.

**Comment by Koenkk** [comment]
Added!
