### ISSUE TITLE
Entry in wrong section 

### ISSUE THREAD

**Issue by daNick73** [Koenkk/zigbee-herdsman-converters#2114]
Hi

Device

  zigbeeModel: ['NLG-remote', 'Neuhaus remote'],
        model: '100.462.31',
        vendor: 'Paul Neuhaus',

is contained incorrectly in section for vendor "Paulmann", not in "Neuhaus".

Should that cosmetic change to be done by user pull request or rather by the owner as part of "code housekeeping"?

daNick

**Comment by nurikk** [comment]
Raise PR

**Comment by daNick73** [comment]
Done, thx
