### ISSUE TITLE
 Support Lidl Home Smart Wireless Door Bell

### ISSUE THREAD

**Issue by dasfuu** [Koenkk/zigbee-herdsman-converters#2116]
I wrote an external converter for the new Lidl/Silvercrest Smart Wireless Door Bell. Not sure if everything is correct. Especially not sure about the battery status. Action and tamper seems to work correct. Tamper is true if you unlock the battery lid.
I just want to get some feedback before integrating it in the code and making a PR :)

Is "pressed" a good value for the action? The device only seems to support single button presses.

You can find the converter here:
https://gist.github.com/dasfuu/dbcb6f5ad71ec250fedf2d5754ab0943

This is the device:
https://zigbeealliance.org/zigbee_products/lidl-home-smart-wireless-door-bell/
https://www.lidl.de/de/silvercrest-tuerklingel-zigbee-smart-home/p36525

**Comment by Koenkk** [comment]
Code looks good, can you make a PR?

Only question for now, does it also send a `commandStatusChangeNotification` when the button is released?

**Comment by dasfuu** [comment]
No it only seems to be sending a Notification on button down. not on release.
I  just noticed that the battery does not seem to be correct. I never got a value for battery percentage. Gonna test the battery low before making a PR. 
Or should I make one nonetheless? The battery stuff was copied form other TuYa devices.

**Comment by Koenkk** [comment]
Please make a PR, i can provide further support here.

**Comment by dasfuu** [comment]
Will do
