### ISSUE TITLE
Müller Licht Filament 404037 not working (not described in statesmapping)

### ISSUE THREAD

**Issue by greyestapps** [Koenkk/zigbee-herdsman-converters#2120]
[The filament bulb 404037 from Mueller Licht](https://www.mueller-licht.de/produktinformationen/artikel/404037/) is not working despite being added in devices.js

`{
        zigbeeModel: ['tint-ColorTemperature'],
        model: '404037',
        vendor: 'M  ller Licht',
        description: 'Tint retro filament LED-bulb E27, Edison bulb gold, white+ambiance (1800-6500K), dimmable, 5,5W',
        extend: generic.light_onoff_brightness_colortemp,
        toZigbee: generic.light_onoff_brightness_colortemp.toZigbee.concat([tz.tint_scene]),
    }`

iobroker gives me the error message _(6079) Device 0x00158d00013d5547 "404037" not described in statesMapping._

**Comment by Koenkk** [comment]
This error is iobroker specific, please create it here: https://github.com/ioBroker/ioBroker.zigbee/issues
