### ISSUE TITLE
No converter found for power and energy on 

### ISSUE THREAD

**Issue by jekkos** [Koenkk/zigbee-herdsman-converters#2125]
Great that I found the device below as supported in the documentation

https://www.zigbee2mqtt.io/devices/SP_120.html

I have tried to set it up and I'm able to connect it to the zigbee2mqtt. I'm seeing this message on startup
```
{"commit":"9674570","coordinator":{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190619,"transportrev":2},"type":"zStack12"},"log_level":"debug","network":{"channel":11,"extendedPanID":"0xdddddddddddddddd","panID":6754},"permit_join":true,"version":"1.16.2"}
```
When I publish this to the zigbee2mqtt topic of the device

```
 mosquitto_pub -h xxx -u xxx -P xxx -t zigbee2mqtt/power_meter/get -m "{\"power\": \"\"}"
```

I get no reply but see the following in the daemon logs

```
No converter available for 'power' ()
```

Any idea what could be wrong here? Thanks!

**Comment by jekkos** [comment]
On the other hand, when I try to request the device state I see this message

```
{"message":"Publish 'get' 'state' to 'power_meter' failed: 'Error: Read 0x60a423fffe8cce79/1 genOnOff([\"onOff\"], {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null}) failed (Data request failed with error: 'MAC no ack' (233))'","meta":{"friendly_name":"power_meter"},"type":"zigbee_publish_error"}
```

**Comment by travelography** [comment]
Hi Jekkos, maybe the following link will help you https://github.com/Koenkk/zigbee2mqtt/issues/3731

**Comment by jekkos** [comment]
Thanks for the pointer @travelography. I'll look into it.

**Comment by sjorge** [comment]
power doesn't have a toZigbee converter only a fromZigbee one.

It either comes from
- https://github.com/Koenkk/zigbee-herdsman-converters/blob/ac94b3ef958abe299bec2725b93959be087dc8be/converters/fromZigbee.js#L525
- https://github.com/Koenkk/zigbee-herdsman-converters/blob/ac94b3ef958abe299bec2725b93959be087dc8be/converters/fromZigbee.js#L565

To be able to use /get you need a something like

```
    power_electrical_measurement: {
        key: ['power'],
        convertSet: async (entity, key, value, meta) => {
            // can't write to these fields
        },
        convertGet: async (entity, key, meta) => {
            await entity.read('haElectricalMeasurement', ['activePower']);
        },
    },
    power_metering: {
        key: ['power'],
        convertSet: async (entity, key, value, meta) => {
            // can't write to these fields
        },
        convertGet: async (entity, key, meta) => {
            await entity.read('seMetering', ['instantaneousDemand']);
        },
    },
``` for both the electrical_measurement and metering kind. But you can't, as you need convertSet is required but convertGet is optional.

@Koenkk ^ that is correct right? having an entry with just convertGet doesn't work?

**Comment by sjorge** [comment]
I was poking around with some devices I have access too, namely the Ubisys S1/S2 and Niko Plug...

Looks like we can't just add these to every device that supports reading/reporting of power :(

<img width="937" alt="image" src="https://user-images.githubusercontent.com/379665/107873846-d1078900-6eb5-11eb-8264-b3ca6abd9a99.png">


```
Zigbee2MQTT:error 2021-02-14 10:13:50: Publish 'get' 'power' to 'livingroom/light/switch' failed: 'Error: Read 0x001fee00000049be/1 seMetering(["instantaneousDemand"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 43618 - 1 - 24 - 1794 - 1 after 10000ms)'
```

Seems to lock up the S1 and S2 when attempted, if you do 2 or 3 in a row (didn't know plug was 'stuck') it seems to reset the plug too. So not good.

I'll add it for the Niko stuff at least as those seem to be working.

**Comment by jekkos** [comment]
@sjorge any idea if that would also work for this one https://www.zigbee2mqtt.io/devices/SP_120.html? Thanks!

**Comment by sjorge** [comment]
No, I don't own one and I have not found any technical docs for it, although the later can't really be trusted as showed with the Ubisys S1/S2.

**Comment by sjorge** [comment]
Swapping out the devices.js entry for

```
    {
        zigbeeModel: ['SP 120'],
        model: 'SP 120',
        vendor: 'Innr',
        description: 'Smart plug',
        fromZigbee: [fz.electrical_measurement, fz.on_off, fz.ignore_genLevelCtrl_report, fz.metering],
        toZigbee: [tz.on_off, tz.electrical_measurement_power],
        meta: {configureKey: 6},
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'haElectricalMeasurement', 'seMetering']);
            await reporting.onOff(endpoint);
            // Gives UNSUPPORTED_ATTRIBUTE on reporting.readEletricalMeasurementMultiplierDivisors.
            endpoint.saveClusterAttributeKeyValue('haElectricalMeasurement', {
                acCurrentDivisor: 1000,
                acCurrentMultiplier: 1,
            });
            await reporting.activePower(endpoint);
            await reporting.rmsCurrent(endpoint);
            await reporting.rmsVoltage(endpoint);
            // Gives UNSUPPORTED_ATTRIBUTE on reporting.readMeteringMultiplierDivisor.
            endpoint.saveClusterAttributeKeyValue('seMetering', {multiplier: 1, divisor: 100});
            await reporting.currentSummDelivered(endpoint);
        },
        exposes: [e.power().withAccess(ea.STATE_GET), e.current(), e.voltage().withAccess(ea.STATE), e.switch(), e.energy()],
    },
```

Could be used to test, but  there is already a issue reading some of the reporting values as mentioned in the comment, so I'm not very confident.

**Comment by jekkos** [comment]
Ok great! I'll try this.. Btw I think we might have worked together in the past. Did you remember working for Gloriant?

**Comment by sjorge** [comment]
> Ok great! I'll try this.. Btw I think we might have worked together in the past. Did you remember working for Gloriant?

I did my thesis and a few summer jobs there yes :)

**Comment by jekkos** [comment]
Yes I only worked there for a summer job as a PHP dev. Got in though Vincent during those days. I think he's still working there at this moment. Small world ;)

**Comment by sjorge** [comment]
> Yes I only worked there for a summer job as a PHP dev. Got in though Vincent during those days. I think he's still working there at this moment. Small world ;)

Yeah! Also discovered a few people at current $work use zigbee2mqtt and saw me in the release notes.

**Comment by jekkos** [comment]
I have added the snippet you posted to devices.js and now see the following and can read the state output now.. which is nice!

**Comment by jekkos** [comment]
When requesting the following `zigbee2mqtt/power_meter/get -m "{\"power\": \"\"}"` I now see `MQTT publish: topic 'zigbee2mqtt/power_meter', payload '{"state":"ON"}'`

**Comment by jekkos** [comment]
I tried to reuse the code in SP-120 and see the following

```
Feb 15 23:23:35 jpeelaer.net npm[1558158]: Zigbee2MQTT:error 2021-02-15 23:23:35: Failed to configure 'power_meter', attempt 1 (Error: ConfigureReporting 0x60a423fffe8cce79/1 haElectricalMeasurement([{"attribute":"activePower","minimumReportInterval":5,"maximumReportInterval":3600>
Feb 15 23:23:35 jpeelaer.net npm[1558158]:     at Endpoint.checkStatus (/home/jekkos/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:196:23)
Feb 15 23:23:35 jpeelaer.net npm[1558158]:     at Endpoint.<anonymous> (/home/jekkos/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:419:26)
Feb 15 23:23:35 jpeelaer.net npm[1558158]:     at Generator.next (<anonymous>)
Feb 15 23:23:35 jpeelaer.net npm[1558158]:     at fulfilled (/home/jekkos/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:24:58)
Feb 15 23:23:35 jpeelaer.net npm[1558158]:     at process._tickCallback (internal/process/next_tick.js:68:7))
```

**Comment by jekkos** [comment]
Ok it seems I bought the wrong one, there's no more energy meter in this one.. 

```
 Ik heb meerdere SP120's in gebruik in combinatie met mijn Homey. Daarmee is naast het schakelen van de apparatuur ook het energieverbruik te zien. De SP220 ondersteunt die echter niet meer. Navraag bij INNR gedaan: dit is inderdaad een bewuste keus, de functionaliteit zit niet in de SP220. 
```

**Comment by sjorge** [comment]
Yeah, not all Innr plugs support it, most notably the newer ones. That is why I never picked one up. The Niko plugs work great though, and are easily available via Niko or webshops like zelektro.

~ sjorge

**Comment by jekkos** [comment]
Ok thanks for the hint @sjorge . I will return this model as start looking for another one that supports power metering.
