### ISSUE TITLE
Inconsistent colors with set/scene_add vs set/color

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee-herdsman-converters#2128]
As #2017 got rather messy as I was figuring stuff out, one of the discovery will be documented here.

### Intro
I frequently use red colors for my lights, sometimes the colors were off. As I have a mix of Innr and Tint in active use (Hue and Osram for testing). Red is a tricky one for Innr but there is a work around, I initially thought it had to do something with that.

As I was testing with a mix of xy and hs at the time (mostly in relation to scene_add). But the in general it looks like colors are slightly different with set/color vs set/scene_add + set/scene_recall.

### Problem 1: applyRedFix
One of the differences is that scene_add does not do anything with applyRedFix, and Innr bulbs thus ignore `{x: 0.701, y: 0.299}` with using scene_add.

We should also do this check and adjust accordingly for in scene_add

### Problem 2: colors are different with set/scene_add vs set/color
Below is an example of my Tint GU10, it shows the individual leds so its easy to see.

Result of:
```
[root@amethyst /opt/zigbee2mqtt]# mosquitto_pub -t zigbee2mqtt/livingroom/light/annex/bulb/set/scene_add -m '{"ID": 123, "color": {"x": 0.701, "y": 0.299}}'
[root@amethyst /opt/zigbee2mqtt]# mosquitto_pub -t zigbee2mqtt/livingroom/light/annex/bulb/set/scene_recall -m 123
```
![image](https://user-images.githubusercontent.com/379665/105538293-797d5f80-5cf3-11eb-91b1-6633a01a263c.png)

This looks good, clean red as I expect it.

Result of:
```
[root@amethyst /opt/zigbee2mqtt]# mosquitto_pub -t zigbee2mqtt/livingroom/light/annex/bulb/set/state -m 'ON'
[root@amethyst /opt/zigbee2mqtt]# mosquitto_pub -t zigbee2mqtt/livingroom/light/annex/bulb/set/color -m '{"x": 0.701, "y": 0.299}'
```

![image](https://user-images.githubusercontent.com/379665/105538512-c6f9cc80-5cf3-11eb-9bba-984b0bda114a.png)

This is blue mixed in and is not correct. (Not 100% tracked this one down, I was initially also testing with hs which passes through utils.gammaCorrectHSV() which definitely does funky stuff as `{"hue": 0, "saturation": 100}` gets correct and when converting the correction back it is definitely not red, and doesn't look red either.)

But lets ignore Hue/Sat for now as via scenes we can only do enhancedHue. 

That still leaves us with a visible difference in color, and other colors are also a bit off. e.g. blue has a bit of red leaking and green has a bit of blue leaking in it when using set/color vs set/scene_add, where scene_add not show the issue.

Those are much harder to get a picture of as the phone seems to be easily overpowered when I tried :(, but using my eyes (which is a bad idea as it hurts after a while) scene_add seems to yield correcter primary colors at the very least. Harder to say when mixing colors.

**Comment by Koenkk** [comment]
Let's decide on https://github.com/Koenkk/zigbee-herdsman-converters/issues/2129 first

**Comment by sjorge** [comment]
I'll add applyRedFix to scene_add for now.

**Comment by sjorge** [comment]
Opened a PR that addresses *most* of this, scene_add now does a fallback to XY when the bulb does not support enhancedHue which stops the crashing of the bulb discovered in an other issue.

appleRedFix does **not** seem to be needed for Innr bulbs either, I believe my error before was that the Innr RB 250 C was not changing colors because was accidently crashing the bulb instead. (I was setting it to !red using hs, setting it to red using `{"x": 0.701, "y": 0.299}}'` both via scene_add. But the call a second or so before actually crashed the bulb so it was still restarting. And unlike the Tint GU10 the Innr RB 250 C comes back with the previous color.

It's a shame there are such huge differences in firmware and yet they somehow all pass certification :(

**Comment by sjorge** [comment]
Oops did not mean to close, as the Tint GU10 still produces a pinkish color when using set/color but not with set/scene_add, will dig into this more later.

Small steps!

**Comment by sjorge** [comment]
Going to close this, colors now look 'good' on all bulbs, for some it needs to be hs for other xy but once you figure that out, all looks well.
