### ISSUE TITLE
Hue/sat gamma correction results in off primary colors

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee-herdsman-converters#2129]
As #2017 got rather messy as I was figuring stuff out, one of the discovery will be documented here.

### Intro
When messing around with hue/sat, mostly when testing enhancedHue vs Hue I noticed colors when set where off, for the primary colors. They seem to be more washed out.

### Problem
Skipping https://github.com/Koenkk/zigbee-herdsman-converters/blob/cf864be3828ad542cbfcbee2c73d4687e4e43cad/converters/toZigbee.js#L897 seems to help for somewhat, but they still look a bit washed out. (Both with Innr and Tint, so I think it's a general thing and not a brand specific issue)

So I'm not convinced that is the issue, aside from that there are also some odd out of range values send from time to time.  
But the later is fixed by switching to `value.saturation = Math.min(255, hsv.s * (2.54));` as mentioned here https://github.com/Koenkk/zigbee-herdsman-converters/issues/2017#issuecomment-753666345

I wonder if we should only apply the gammeCorrection for enhancedHue and not Hue? I couldn't find much info on why we are doing this correction. Not that it will fix the washed out colors though.

It might be a brightness issue? as lowering the brightness to around 250 instead of 255 gives close to the same result with xy vs hs... which is interesting.

**Comment by Koenkk** [comment]
The gamma correction was added in https://github.com/Koenkk/zigbee-herdsman-converters/pull/1183 by @jasperro  . It seems this was specifically done for OSRAM and Hue. But if I understand @sjorge correctly this makes the color worse with Hue?

**Comment by sjorge** [comment]
This can get confusing quickly... lets try to clarify from the get go.

**Hue** -> hue property
**Philips Hue** -> Ex. Philips, now Signify brand of bulbs.

It seems to make things worse for my Innr and Tint bulbs, my Philips Hue bulb which I have around for testing seems to be fine.

I'm seeing this when setting the colors by having Hue and Saturation in the color payload. Using XY I do not have the issue.

**Comment by Koenkk** [comment]
Gamma correction is not applied for X/Y, only for Hue and Saturation. So I suggest to fix this by only doing the gamma correction when the bulb is OSRAM or Signify Hue

**Comment by sjorge** [comment]
Sounds good, let me think on how to do this cleanly. 

As it gets passed deep into utils.rgbToXY too...

**Comment by sjorge** [comment]
Oh no :( I was doing more testing as I also have an Osram bulb around.

Osram E27: better with correction
Tint E27: better with correction
Innr E27: better with correction
Innr E14: better without correction
Tint GU10: better without correction
Hue E14: better with correction

**Comment by sjorge** [comment]
Makes me curios as to what lightingColorCtl DriftCompensation Primary1X Primary1Y ... are for these bulbs.

**Comment by Koenkk** [comment]
Given that there are differences even between the same manufacturer I guess the color accuracy highly depends on the hardware of the bulb. First impression is that we should keep the gamma correction and also apply it when adding scenes via hue/sat

**Comment by sjorge** [comment]
Innr E14 and Tint GU10 both need enhancedHue to be false for them to take a moveToHueSat command.

I was going over my code and noticed I had the ugly hack in there for Tint GU10 from testing because it has the same model as the Tint E27... which does support enhancedHue and I havent figured out a proper fingure print for it.

So the pattern is clear ish I think, we need to apply gammaCorrection for bulbs that doe enhanchedHue and skip it for those that don't!

**Comment by sjorge** [comment]
I think my plan of action should be:
- [ ] figure out a finger print difference between Tint GU10 vs E27 (colorCaps lies on the GU10, original interesting in that was for this bulb)
- [ ] set enhancedHue=false for Tint GU10 only
- [ ] update toZigbee to only apply gammaCorrection when enhanchedHue is true (default)

**Comment by sjorge** [comment]
@Koenkk I'm running into the same issue again with trying to use a finger print:

```
--- devices.js~ 2021-01-23 15:16:17.618638135 +0000
+++ devices.js  2021-01-23 15:24:26.014628829 +0000
@@ -9902,10 +9902,20 @@
         toZigbee: preset.light_onoff_brightness().toZigbee.concat([tz.tint_scene]),
     },
     {
+        fingerprint: [{modelID: 'ZBT-ExtendedColor', manufacturerID: 4635, endpoints: [
+          {ID: 1, profileID: 260, deviceID: 269, inputClusters: [0,3,4,5,6,8,768,2821,4096,65244], outputClusters: [10,25]},
+        ]}],
+        model: '404005',
+        vendor: 'M_ller Licht',
+        description: 'Tint LED bulb GU107 350 lumen, dimmable, color, opal white',
+        extend: preset.light_onoff_brightness_colortemp_colorxy(),
+        toZigbee: preset.light_onoff_brightness_colortemp_colorxy().toZigbee.concat([tz.tint_scene]),
+    },
+    {
         zigbeeModel: ['ZBT-ExtendedColor'],
-        model: '404000/404005/404012',
+        model: '404000/404012',
         vendor: 'M_ller Licht',
-        description: 'Tint LED bulb GU10/E14/E27 350/470/806 lumen, dimmable, color, opal white',
+        description: 'Tint LED bulb E14/E27 470/806 lumen, dimmable, color, opal white',
         extend: preset.light_onoff_brightness_colortemp_colorxy(),
         toZigbee: preset.light_onoff_brightness_colortemp_colorxy().toZigbee.concat([tz.tint_scene]),
     },
```

The GU10 keeps matching the wrong one.

**Comment by Koenkk** [comment]
I don't think we can separate those two devices by a fingerprint. There is indeed a slight difference between the software version and clusters but I guess another GU10 bulb might ship with different software thus matching the other fingerprint.

**Comment by sjorge** [comment]
Yeah the model is exactly the same :( in/out clusters are different though, the GU10 is missing one of the gp clusters and has a haDiagnostic cluster (Makes you wonder if some of the odd behavior on the bulb is because of the firmware being... old)

**Comment by Koenkk** [comment]
I think you are searching for something like this: https://github.com/Koenkk/zigbee-herdsman-converters/blob/9e4c36cd79e15449830f5e09540157c0e8d686a1/devices.js#L6816

**Comment by sjorge** [comment]
Is using software version the right route though... as it looks like the firmware on the GU10 is newer than the one on the E27 (I'd have expected the other way around)

**Comment by sjorge** [comment]
I think it might just be best to leave this unchanged, the Innr E27 I'm using that does not suffer from the washed out colors also does not support enhancedHue... :(

I'm just going to mark Innr RB 250 C and Tint GU10 on my spreadsheet as bulbs with bad colors I think.

**Comment by sjorge** [comment]
I managed to get the GU10 split of and did a bunch of more testing.

The Innr RB 250 C and the ML Tint GU10 look a bit off with **and** without gammaCorrection, neither looking objectively better than the other. To keep thing consistent, I think it's best to just leave gammaCorrection in place.

For now my strategy is to use XY for both of these bulbs and use Hue/Sat for my others, as Hue/Sat does give better results on my Osram/Hue/Innr RB 285 C/Tiny E27... ¯\_(ツ)_/¯
