### ISSUE TITLE
Zen thermostat does not update 9 times out of 10

### ISSUE THREAD

**Issue by jcam** [Koenkk/zigbee-herdsman-converters#2134]
This is working perfectly in Home Assistant's ZHA, but fails here.
Any updates that are sent when the battery powered thermostat is asleep fail.
Here is the log entry that comes back when sending a request that fails:
```
Zigbee2MQTT:error 2021-01-23 04:19:26: Publish 'set' 'occupied_heating_setpoint' to 'Main House Heat' failed: 'Error: Write 0x00244600000e6969/1 hvacThermostat({"occupiedHeatingSetpoint":1700}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (no response received)'
Zigbee2MQTT:info  2021-01-23 04:19:26: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'occupied_heating_setpoint' to 'Main House Heat' failed: 'Error: Write 0x00244600000e6969/1 hvacThermostat({\"occupiedHeatingSetpoint\":1700}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null}) failed (no response received)'","meta":{"friendly_name":"Main House Heat"},"type":"zigbee_publish_error"}'
```

If I resend the command a half dozen times, it will usually eventually work one of those times.
In smart things and in ZHA updates worked reliably without need to manually re-send.

Any ideas of what could be done to mitigate this? Is there some sort of 'this device goes to sleep' thing that needs to be added to the devices.js for this thermostat? Or worst case, is there a way to tell the converter to re-send the command up to 10 times until a success is received?

**Comment by Codel1417** [comment]
Did you ever solve this as I'm dealing with this exact issue

**Comment by lucacri** [comment]
I have the same problem

**Comment by jcam** [comment]
No this was never resolved, I switched to ZHA and everything works great.

**Comment by Codel1417** [comment]
I have another ZigBee dongle somewhere. I may run ZHA just for the thermostat
