### ISSUE TITLE
Shenzhen Homa HLC821-Z-SC with firmware 1.1.0

### ISSUE THREAD

**Issue by RolandWijnen** [Koenkk/zigbee-herdsman-converters#2141]
I have two of these dimmers (https://www.zigbee2mqtt.io/devices/HLC821-Z-SC.html). One has firmware 1.0.2 and a more recently purchased dimmer has firmware 1.1.0. I discovered that the one with the newer firmware was not properly identified. It turned out that it has another identifier, i.e. '00F'. By adding it to a custom 'devices.js' I got it working.    

    {
        zigbeeModel: ['HOMA1031','00F'],
        model: 'HLC821-Z-SC',
        vendor: 'Shenzhen Homa',
        description: 'ZigBee AC phase-cut dimmer',
        extend: generic.light_onoff_brightness,
    },

One thing that does not work is the reporting of Link Quality (LQI), as indicated on the screenshot of my dashboard. 
<img width="1418" alt="Zigbee2mqtt dashboard" src="https://user-images.githubusercontent.com/24925747/105614212-4a84ed80-5dc8-11eb-890c-645eacd4bb58.png">
That is shown as 'N/A'. Also the dimmer with the new firmware does not report 'Power'. This is shown as '?'.

**Comment by Koenkk** [comment]
Added!

> One thing that does not work is the reporting of Link Quality (LQI), as indicated on the screenshot of my dashboard.

You should get it after controlling it once, if not issue a `/get`, e.g. `zigbee2mqtt/FRIENDLY_NAME/get` with payload `{"brightness": ""}`.

> Also the dimmer with the new firmware does not report 'Power'. This is shown as '?'.

Could either be a bug in the firmware of this device or a hickup in the pairing process. Try repairing it close to the coordinator.
