### ISSUE TITLE
Multiple OTA providers

### ISSUE THREAD

**Issue by mkaay** [Koenkk/zigbee-herdsman-converters#2168]
Hey Koenkk,
Is it possible, to have multiple OTA providers (lib/ota/*.js) that return data for the same manufacturer and image?
And what happens when they return different versions, will the highest version be chosen?
I had a quick look around the code, but I couldn't find the right entry point.
The reason I'm asking is that there is an API for the Hue BT app, that needs no authorization, but it only works for the BT enabled lights.
Would it be possible to have "base" firmware version from the zigbeeOTA.js and potentially newer versions via the API in a new provider?

The API is pretty simple:
https://firmware.meethue.com/v1/checkUpdate?deviceTypeId=100B-11A&version=0
the device type id is just the manufacturer id an image type as hex. You can leave version 0 to get the newest version or use the actual version to check if an update is available

CC @TheJulianJES

**Comment by Koenkk** [comment]
Multiple OTA providers are not supported. For this case a new OTA provider should be created. To do this.

- Create a new OTA provider (use e.g. https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/lib/ota/zigbeeOTA.js as inspiration) and add it here: https://github.com/Koenkk/zigbee-herdsman-converters/tree/master/lib/ota , call it `philips.js`
- Add it to https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/lib/ota/index.js
- In `devices.js` set `ota: ota.philips` for the Hue Bluetooth devices.

**Comment by mkaay** [comment]
Okay, thanks! I will try to think of an elegant solution for this.
