### ISSUE TITLE
TuYa Thermostat error with zigbee2mqtt edge

### ISSUE THREAD

**Issue by boesing** [Koenkk/zigbee-herdsman-converters#2176]
Hey there,

I've upgrade to the edge version as I wanted to test `force` for the TuYa Thermostat.
That works pretty well but after the valve is closed (not sure if thats related, I am just receiving the errors), I get the following error:

```bash
Zigbee2MQTT:error 2021-01-28 21:24:20: Failed to call 'Receive' 'onZigbeeEvent' (TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Object.convert (/app/node_modules/zigbee-herdsman-converters/converters/fromZigbee.js:2955:91)
    at /app/lib/extension/receive.js:159:41
    at Array.forEach (<anonymous>)
    at Receive.onZigbeeEvent (/app/lib/extension/receive.js:158:20)
    at Controller.callExtensionMethod (/app/lib/controller.js:382:44))
```

Related line in code: https://github.com/Koenkk/zigbee-herdsman-converters/blob/eb4df4547cad6021dddab067b8440fc4b7054412/converters/fromZigbee.js#L2955

The last TuYa Thermostat related message I've received before the error(s) were triggered:

```
Zigbee2MQTT:info  2021-01-28 21:24:15: MQTT publish: topic 'zigbee2mqtt/0x123456789abc', payload '{"auto_lock":"MANUAL","away_mode":"OFF","away_preset_days":1,"away_preset_temperature":15,"battery_low":false,"boost_time":300,"child_lock":"UNLOCKED","comfort_temperature":20,"current_heating_setpoint":23,"eco_temperature":15,"force":"close","holidays":[{"hour":6,"minute":0,"temperature":20},{"hour":8,"minute":0,"temperature":15},{"hour":11,"minute":30,"temperature":15},{"hour":12,"minute":30,"temperature":15},{"hour":17,"minute":30,"temperature":20},{"hour":22,"minute":0,"temperature":15}],"linkquality":90,"local_temperature":22,"local_temperature_calibration":-2,"max_temperature":35,"min_temperature":5,"position":100,"preset":"manual","system_mode":"off","update":{"state":"idle"},"update_available":false,"week":"5+2","window_detection":"OFF","window_detection_params":{"minutes":10,"temperature":5},"workdays":[{"hour":6,"minute":0,"temperature":20},{"hour":8,"minute":0,"temperature":15},{"hour":11,"minute":30,"temperature":15},{"hour":12,"minute":30,"temperature":15},{"hour":17,"minute":30,"temperature":20},{"hour":22,"minute":0,"temperature":15}]}'
```

I hope this helps for further debugging 🙈

**Comment by Koenkk** [comment]
What model tuya thermostat is this?

**Comment by boesing** [comment]
Oh, yah... sorry, my fault.
It is the TS0601

**Comment by Koenkk** [comment]
Can you check if this is fixed?

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by boesing** [comment]
Sure, could you point me to the diff? I can just apply it to my local installation and restart the process for quick results.

**Comment by boesing** [comment]
Seems to work. 
Getting some random 
```
Zigbee2MQTT:error 2021-01-30 10:07:12: No converter available for 'force' (close)
```

```

zigbee-herdsman-converters:tuyaThermostat: NOT RECOGNIZED DP #115 with data {"status":35,"transid":94,"dp":115,"datatype":1,"fn":0,"data":{"type":"Buffer","data":[0]}}
```

But the initial error is gone. not sure if these are related tho. Shall I add some debug output for further debugging or are these already adressed somewhere else?

**Comment by Koenkk** [comment]
Cool, other issues seems to be discussed in https://github.com/Koenkk/zigbee2mqtt/issues/3821. `NOT RECOGNIZED DP #115 with data ` is not an error, people haven't figured out what this value is.
