### ISSUE TITLE
Need help to support new device: Heiman RC-EF-3.0

### ISSUE THREAD

**Issue by arnaud-gouder** [Koenkk/zigbee-herdsman-converters#2181]
Hi,

I bought a Heiman RC-EF-3.0 on Aliexpress (https://nl.aliexpress.com/item/32975159931.html)

It works perfectly with Zigbee2Mqtt. I changed the following in devices.js for the 'Heiman HS1RC-N' device that looks exactly the same:

```
        // fingerprint: [{modelID: 'RC-N', manufacturerName: 'HEIMAN'}],
        zigbeeModel: ['RC-N', 'RC-EF-3.0'],
```
I don't think this is really the right way to do this though. Should I instead duplicate the entry for the HS1RC-N and change the modelID ?

Please let me know how to best do this, so I can create a pull request.

Thanks,

Arnaud

**Comment by Koenkk** [comment]
Please create a pr adding a new device (model `HM1RC-2-E`)

**Comment by arnaud-gouder** [comment]
Hi Koen,

I created: https://github.com/Koenkk/zigbee-herdsman-converters/pull/2182

Best regards,

Arnaud

**Comment by Koenkk** [comment]
Good, assuming this can be closed now.
