### ISSUE TITLE
deps zigbee-herdsman

### ISSUE THREAD

**Issue by G1K** [Koenkk/zigbee-herdsman-converters#2189]
https://github.com/Koenkk/zigbee-herdsman-converters/commit/c0e84ece6e0cf2ca20e62315b9831b81850300c5

when refactoring, a dependency was added  zigbee-herdsmannow it is in two directories and takes up more space which is not very much on xiaomi gw. Is it possible to do without this direct relationship?

**Comment by Koenkk** [comment]
The only reason for this dependency is the manufacturer codes (https://github.com/Koenkk/zigbee-herdsman-converters/blob/3ed4ad4430dd7ddc333ceb331aef3faeeea20a91/converters/toZigbee.js#L11). Can you create a PR to move this back in and remove the zigbee-herdsman dependency?

**Comment by G1K** [comment]
I do not know how to solve this nicely and updateable. I can only offer to transfer static codes of Manufacturers.

Is such a solution suitable for PR?

**Comment by Koenkk** [comment]
> I do not know how to solve this nicely and updateable. I can only offer to transfer static codes of Manufacturers.

Yes, exactly what I meant!

**Comment by G1K** [comment]
I tried to do this, but herdsman is still used for herdsman.Zcl.Status, it used to be in common.js. My suggestion is to add herdsman as a dev dependency or you need to move all const zcl into a separate package.

**Comment by G1K** [comment]
Or you can still try updating the version of herdsman along with the main repository. Then the npm shouldn't pull up a specific version.

**Comment by Koenkk** [comment]
> I tried to do this, but herdsman is still used for herdsman.Zcl.Status, it used to be in common.js. My suggestion is to add herdsman as a dev dependency or you need to move all const zcl into a separate package.

I don't think it's an option. That would mean it not always available while it is used in production code

> Or you can still try updating the version of herdsman along with the main repository. Then the npm shouldn't pull up a specific version.

That seems the best solution for now. With next z2m release I will make sure zigbee-herdsman-converters and zigbee2mqtt use the exact same zigbee-herdsman version.
