### ISSUE TITLE
currentHue and currentSaturation not querried anymore with /get

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee-herdsman-converters#2190]
https://github.com/Koenkk/zigbee-herdsman-converters/blob/3ed4ad4430dd7ddc333ceb331aef3faeeea20a91/converters/toZigbee.js#L995

Looks like now we're no longer querying currentHue and currentSaturation for any bulbs?

As far as I can see only for one device do we have `meta.supportsHueAndSaturation` set to false, but the no code seems to also assume `undefined` as not false too so we never take the branch to push the extra attributes. Can we change this back to `if (utils.getMetaValue(entity, meta.mapped, 'supportsHueAndSaturation', 'allEqual') !== false) {` ?

@Koenkk you recently changed it after my first refactor to getMetaValue, I assume you had a reason to? But anyway, as far as I can tell we never hit the branch so we never query these properties now. So we need to either just drop the if, if that is the intented behavior or change it back I think. (ideally I think we do read these)

**Comment by sjorge** [comment]
There seem to be one `if (!utils.getMetaValue(entity, meta.mapped, 'enhancedHue', 'allEqual')` in there too that we need to change to have `!== false` in there too.

**Comment by Koenkk** [comment]
Can you add an additional parameter to `getMetaValue` called `default` (`default=undefined`) which is returned when no such meta key is defined? Than it should be fixed with: `utils.getMetaValue(entity, meta.mapped, 'supportsHueAndSaturation', 'allEqual', true)`

**Comment by sjorge** [comment]
Sure, we can also do it for enhancedHue which we only set when it's false too.
I'll try to get to it tomorrow.
