### ISSUE TITLE
 Fantem MultiSensor ZB003-X occupancy not working (follow up to issue #2071)

### ISSUE THREAD

**Issue by dsantos21** [Koenkk/zigbee-herdsman-converters#2195]
Hi! I've just updated the issue #2071 with some comments about occupancy not working. After some debug I changed my local instance and now it's working (without the bitwase operator):

occupancy: (zoneStatus & 1) > 0,

_Originally posted by @dsantos21 in https://github.com/Koenkk/zigbee-herdsman-converters/pull/2072#r569052440_

**Comment by dsantos21** [comment]
I'm really new to this, not sure if that is the right way to do. Please, let me know if this should be canceled.

**Comment by kirovilya** [comment]
I, too, this sensor did not send an occupation, so I had to do it as it is now. I will check your solution later.

**Comment by dsantos21** [comment]
Also, if you would like to include the tamper detection, it would be something like this (bit 3 of zone status):

tamper: (zoneStatus & 4) > 0,

I just tested it with an online expression tester, with the zoneStatus values I got in debug. Tried a few combinations, worked as expected (for me, at least :).

**Comment by dsantos21** [comment]
I really don't know GIT nor how to do those fix, but on the weekend I can try!

**Comment by kirovilya** [comment]
I think my sensor is broken ... I have never received an occupancy event, but the tamper was received. therefore, I considered that they are confused here.
if your events come, then just replace fz.ZB003X_occupancy with fz.ias_occupancy_alarm_1 in device.js

**Comment by dsantos21** [comment]
Are you using some battery? Try using USB power. One of my sensors was erratic too, but it was caused by bad batteries. Motion was not reported or reported without real motion.

**Comment by kirovilya** [comment]
I used USB power. No motion reported :(

**Comment by dsantos21** [comment]
> I think my sensor is broken ... I have never received an occupancy event, but the tamper was received. therefore, I considered that they are confused here.
> if your events come, then just replace fz.ZB003X_occupancy with fz.ias_occupancy_alarm_1 in device.js

Yes, it did work too. 😄

**Comment by dsantos21** [comment]
Also, I just noticed that the illuminance exposed value are not calibrated. For example:

"illuminance": 3010 (raw value)
"illuminance_lux": 2 (calibrated value)

The calibrated value is 2. But the value reported back to home assistant is 3010.

**Comment by dsantos21** [comment]
Pull request: #2331
