### ISSUE TITLE
Support for VIYU C35 470 RGBW 10297667

### ISSUE THREAD

**Issue by kleinepaul** [Koenkk/zigbee-herdsman-converters#2208]
Dear all,

I have a couple of the following lights: VIYU-A60-806-RGBW-10011725 (from Vendor Hornbach with the following exposes: light (state, brightness, color_temp, color_temp_startup, color_xy), effect, linkquality). 

They work perfectly and are fully supported as mentioned in the zigbee2mqtt supported devices. 

Recently I bought a few similar Flair Viyu lights from Hornbach but then with a C35/E14 socket (instead of the A60/E27 socket), also RGBW and the same exposes. They are listed as: VIYU_C35_470_RGBW_10297667 and are not supported. The CCT version can be found in the support list but the RGBW version not.

Whatever I try I can't get them to work.

Do they need to get a new device support or are there other options?

If I should not ask this here I am sorry (newbie).

**Comment by Koenkk** [comment]
Added. 

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by kleinepaul** [comment]
Works perfect! Thank you!
