### ISSUE TITLE
Missing hold / release actions for QBKG21LM

### ISSUE THREAD

**Issue by arfond** [Koenkk/zigbee-herdsman-converters#2215]
https://www.zigbee2mqtt.io/devices/QBKG21LM.html#xiaomi-qbkg21lm

Device page suggests that hold and release actions are available for this device, however only "single" is currently available.

legacy: false is set for the device in the configuration file.

**Comment by Koenkk** [comment]
Can you try changing https://github.com/Koenkk/zigbee-herdsman-converters/blob/8f857b96b8daa70e6dc8f91c99e76ea1afcdc228/converters/fromZigbee.js#L3657 to `const actionLookup = !isLegacyEnabled(options) && ['QBKG03LM', 'QBKG22LM', 'QBKG04LM', 'QBKG21LM'].includes(model.model) ?` and check if hold release works now?

See https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html on how to modify devices.js

**Comment by arfond** [comment]
> , 'QBKG21LM'

confirmed, that works. many thanks. I'll update and commit.
