### ISSUE TITLE
Add Support for Sylvania LIGHTIFY Contact and Temperature Smart Sensor

### ISSUE THREAD

**Issue by smeranda** [Koenkk/zigbee-herdsman-converters#222]
I'm running Hass.io, and since it's in Docker, I don't have access to the `node_modules` directory to finish the setup. Here's what I have, is this enough to add? Perhaps someone else has this device and can fill in the blanks.

Or, if you have suggestions on getting into `node_modules` on Hass.io I'll run through the rest of the steps.

[Link to Sylvania LIGHTIFY Contact and Temperature Smart Sensor](https://www.amazon.com/gp/product/B07DX5XZK7/ref=ppx_yo_dt_b_asin_title_o00__o00_s00?ie=UTF8&psc=1).

[Image for docs](https://assets2.sylvania.com/media/img/asset-1639561/s,x,923,y,0/Contact_Sensor_800.png).

```
{
    zigbeeModel: ['Contact Sensor-A'],
    model: '74388', 
    vendor: 'Sylvania',
    description: 'Sylvania LIGHTIFY Contact and Temperature Smart Sensor', 
    supports: 'contact and temperature',
    fromZigbee: [], // TBD
    toZigbee: [], // TBD
},
```

**Comment by ryanbeaton** [comment]
Can you try

https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices_on_hassio.html
