### ISSUE TITLE
The action still does not work on QBKG26LM with z2m

### ISSUE THREAD

**Issue by slydiman** [Koenkk/zigbee-herdsman-converters#2221]
Probably it is better to reopen https://github.com/Koenkk/zigbee-herdsman-converters/issues/1986

The action still does not work on QBKG26LM with z2m!
QBKG26LM sends Report Attributes on button pressing from endpoints 41 (left button), 42 (center) and 43 (right) immediately after pairing with Xiaomi Gateway 2. It does not depend on the decoupled mode at all.

The decoupled mode is absolutely useless on QBKG26LM without actions.

Here is the sniff of MiHome pairing and clicking the left button (Source Endpoint: 41):
http://slydiman.me/_t/qbkg26lm/pairing_mihome_test2_click_left.pcapng
ZigBee keys:
5A:69:67:42:65:65:41:6C:6C:69:61:6E:63:65:30:39
60e566b35cb1c25f183ddecb9489baf7

Frame 75:
```
ZigBee Application Support Layer Data, Dst Endpt: 1, Src Endpt: 41
    Frame Control Field: Data (0x00)
    Destination Endpoint: 1
    Cluster: Multistate Input (Basic) (0x0012)
    Profile: Home Automation (0x0104)
    Source Endpoint: 41
    Counter: 19
ZigBee Cluster Library Frame, Command: Report Attributes, Seq: 18
    Frame Control Field: Profile-wide (0x18)
    Sequence Number: 18
    Command: Report Attributes (0x0a)
    Attribute Field, Uint16: 1
        Attribute: Present Value (0x0055)
        Data Type: 16-Bit Unsigned Integer (0x21)
        Uint16: 1 (0x0001)
```
I guess some extra request during the pairing process disables the action reporting. 
Probably it is a new smart Xiaomi's logic.
Xiaomi Gateway 2 requests the Application version (1), but there is no response. 
Instead of it QBKG26LM requests the time and time zone.

**Comment by Koenkk** [comment]
Continuing in https://github.com/Koenkk/zigbee-herdsman-converters/issues/1986
