### ISSUE TITLE
LegacyReporting and Plug genOnoff

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee-herdsman-converters#2229]
I noticed I was no longer getting status updates for my plug, it has a on/off button on the actual device.

I think this was because with the latest release I removed `report: true` and rebound all my bulbs to my remotes.

https://github.com/Koenkk/zigbee-herdsman-converters/blob/372ab0f2fb95babf13adcec96297d413dbac7171/devices.js#L15781

Should we bind the genOnOff cluster in the configure block for this device?

**Comment by Koenkk** [comment]
> Should we bind the genOnOff cluster in the configure block for this device?

This is done? (on the line you linked)

**Comment by sjorge** [comment]
Do we also need to setup reporting or would the bind be enough? I repaired it and I'm not getting updates anymore unless I manual setup reporting again.

I'm 80% sure it worked before (with report: true I guess, but spend 1h reconfiguring reporting after dropping the line so don't want to go back for a quick double check)

**Comment by Koenkk** [comment]
> Do we also need to setup reporting or would the bind be enough?

Seems to vary per device, you can test by factory reseting the device, removing all reports and configure again via frontend.

**Comment by sjorge** [comment]
- I did a leave (which it did)
- checked database.db if it was gone
- enable join
- reset device

No state changes get reported, power does still work.
Is what it looks like:
<img width="1448" alt="image" src="https://user-images.githubusercontent.com/379665/107556681-002daa00-6bd9-11eb-8c18-fff54045b5e7.png">
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/379665/107556715-0facf300-6bd9-11eb-99dc-d29d67ff3b47.png">

**Comment by sjorge** [comment]
Toggling the device with the button only shows a change in 'power' as it has about 30watt drawn or 0 when off

**Comment by sjorge** [comment]
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/379665/107557317-bb564300-6bd9-11eb-93ae-a7e43bb2c634.png">


Manually adding genOnoff,onOff,0,300,1 restores the behavior, so we need to update this device's configure right?

**Comment by Koenkk** [comment]
Exactly! added it.
