### ISSUE TITLE
wrong color temperature range for Innr RS 229 T

### ISSUE THREAD

**Issue by clemensk1** [Koenkk/zigbee-herdsman-converters#2246]
this device only supports 2200K - 5000K (200-454 mired) and not 153-555 mired

**Comment by Koenkk** [comment]
done, thanks!

**Comment by sjorge** [comment]
@Koenkk might be a safer assumption for all T variants? I got the original value for ma C variant which support CWS, so the range might be bigger.

**Comment by Koenkk** [comment]
@sjorge I have no clue, don't have these devices.

**Comment by sjorge** [comment]
> @sjorge I have no clue, don't have these devices.

Let’s leave them at the wider range, until someone can provide database entries for them.
