### ISSUE TITLE
Want a way to configure lightingColorCtrl options

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee-herdsman-converters#2253]
## what ?
I've been playing with the `options` attribute of the `lightingColorCtrl` cluster a bit.

<img width="909" alt="image" src="https://user-images.githubusercontent.com/379665/108092918-77ea5180-707d-11eb-9b9e-73f6b2a3c09f.png">

## why
I am **abusing** scenes to change the color of  bulbs even when they are off, mostly for adaptive lighting. This works, but it's very very ugly. (But on the upside it made me improve scene support ¯\_(ツ)_/¯)

For my FLOALT panels I was not using scenes as they supported setting color_temp (or limited color_xy set) while off. It works a lot smoother (no scene_add, scene_recall dance which is probably not great for the bulb and unneeded traffic on the mesh)

I did some experimenting and the old FLOALT had the ExecuteIfOff bit set to 1, after the upgrade last week it is now set to 0 and it stopped working. 

## options
I already did the preliminary PR Koenkk/zigbee-herdsman#310 as we did not have the attribute listed.

I currently have a 'working' implementation that is rather rough and I am not happy with, I could polish it but there might be a better way?

toZigbee:
```
    light_execute_if_off: {
        key: ['execute_if_off'],
        convertSet: async (entity, key, value, meta) => {
            await entity.write('lightingColorCtrl', {options: value}, utils.getOptions(meta.mapped, entity));
            return {state: {execute_if_off: value}};
        },
        convertGet: async (entity, key, meta) => {
            await entity.read('lightingColorCtrl', ['options']);
        },
    },
```
fromZigbee:
```
    light_execute_if_off: {
        cluster: 'lightingColorCtrl',
        type: ['attributeReport', 'readResponse'],
        convert: (model, msg, publish, options, meta) => {
            const result = {};

            if (msg.data.hasOwnProperty('options')) {
                result.execute_if_off = msg.data['options'];
            }

            return result;
        },
    },
```

Polishing this would probably be something like:
- rename execute_if_off to `light_options`
- make the value a object with a key called `ExecuteIfOff`
- do a proper bitshift based on the key's true/false value

That leaves the door open for future options if ZCL is updated.

@Koenkk some feedback on this would be welcome, polishing this a bit is certainly doable... but I feel like there might be better alternatives? 

Perhaps we can just try/catch this and write the ExecuteIfOff bit inside the bulbs configure() ? We already have one now to read the colorTempMin/Max. We can just set bit 0 to 1. That would remove yet another obscure attribute someone has to know about.

This won't break anything AFAIK, and now when you send a color or color_temp change to a bulb that happens to be off, it applies the change. Instead of z2m updating the result but the bulb ignoring it. Leaving z2m and the bulb out of sync.

As the bulbs don't return errors when bit 0 is set to 0, they just ignore the command. Which, tbh is not really what I expected when I just started using z2m. And probably for many others too.

**Comment by sjorge** [comment]
The alternative seems rather easy, testing now https://github.com/Koenkk/zigbee-herdsman-converters/compare/master...sjorge:light_options?expand=1

**Comment by sjorge** [comment]
Testing:
- [X] Innr RB 250 C
- [X] Innr RB 285 C
- [ ] Osram E27
- [ ] Hue E14
- [ ] Tint E27
- [ ] Tint GU10
- [ ] Tradfri E27 CWS
- [ ] Tradfri FLAOLT
- [ ] Tradfri GUNTARP
- [ ] Tradfri GU10 WS

**Comment by sjorge** [comment]
Just tested this on all the bulbs I own, my Hue E14 and Tradfru GU10 WS don't support it, the others seem to do!

**Comment by sjorge** [comment]
Another alternative is to, not implement it.
😞 As from the tests it looks like not all bulbs implement it.

Unless 8029, seems to indicate we can only set it during commissioning... so I'm not sure my hacky and my PR are even correct. 🤔 What would be the 'commissioning' be in that sentence? Only during the interview process?

**Comment by sjorge** [comment]
Closed the PR for now as I couldn't move it back to draft, 8029 will be key as to how we implement this, if we do. I think it might need to be option C, set this during 'commissioning'... which I currently don't know exactly when that is.

**Comment by Koenkk** [comment]
Commissioning should be the part before the device is actually paired to Zigbee2MQTT (before you see "device joined" in the log). Since you've managed to successfully set this option after this I don't see why this can only be configured during "commissioning". 

I don't think we should touch this option by default (since no issues have been reported about this before). IMHO the best solution is a toZigbee converter to set this option in the form of `zigbee2mqtt/my_light/set`, `{"light_options": {"execute_if_off": true}}`

**Comment by sjorge** [comment]
I wondering if this might be why the GU10 and Hue ignore it, it does accept the new value successfully but it has no effect.

Is there a way to execute it on the proper time in the joining processes? (Just to see if it makes a difference)

~ sjorge

**Comment by Koenkk** [comment]
The configure is the first possible point to do this. If you want to do it earlier you can try it e.g. here: https://github.com/Koenkk/zigbee2mqtt/blob/6484feecb7c4727c0623a8a6264bac8b3403bbb3/lib/controller.js#L231 but at this point the `device` object does not contain the endpoint to do the request. So you will have to directly call the adapter like done here: https://github.com/Koenkk/zigbee-herdsman/blob/7f3f6642a53e0808dd59b04acbbc3229a85c83bc/src/controller/model/endpoint.ts#L299

However I don't expect this will make any difference since this is already after the commissioning process.

**Comment by sjorge** [comment]
I had little succes in trying to move it earlier, when it 'worked' it still had the same effect. I'll will polish hte original design with a simple fz/tz converters.

@Koenkk opinions on expose? I do we add them? Or just document this on the site?

**Comment by Koenkk** [comment]
Preferably expose yes, but depends on how this was implemented.

**Comment by sjorge** [comment]
I'll wrap this up and do a draft pr you can check before doing the expose bits, if you're not happy we can iterate on the actual converters first.

**Comment by lovelylain** [comment]
@Koenkk Can you export `this.zigbee` here so that we can do `coordinator = zigbee.getDevicesByType('Coordinator')[0].getEndpoint(1)`, then `endpoint.bind('xxx', coordinator)`.
https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/extension/publish.js#L199
```js
            const meta = {
                zigbee: this.zigbee,
                endpoint_name: endpointName,
                options,
```

**Comment by Koenkk** [comment]
@lovelylain I don't understand how your request is relevant to this issue

**Comment by sjorge** [comment]
PR got merged
