### ISSUE TITLE
Aldi Lightway / Megos bulbs with E27 and GU10

### ISSUE THREAD

**Issue by shortyHonk** [Koenkk/zigbee-herdsman-converters#2262]
Hello everybody
I have bought today some bulbs of the company megos or lightway and wanted to add them to the adapter, but it won‘t work.

Please adjust the adapter to use these bulbs also.
Many german customer have bought them today, because they were offered in a big warehouase for a low price, so there will be a big request for that.

thanks!

**Comment by letszb** [comment]
Resetting the bulb should work to bind the lights.

Turn off the lamp for at least 10 seconds. Then switch it on and off three times (on-off-on-off-on), waiting around three seconds each time before flipping the light switch. After that, the lamp should pulsate briefly.

**Comment by BMOD89** [comment]
@shortyHonk if you use my fork for testing, it should work for you. https://github.com/Koenkk/zigbee-herdsman-converters/pull/2261

**Comment by shortyHonk** [comment]
> Resetting the bulb should work to bind the lights.
> 
> Turn off the lamp for at least 10 seconds. Then switch it on and off three times (on-off-on-off-on), waiting around three seconds each time before flipping the light switch. After that, the lamp should pulsate briefly.

I‘ve resettet it already, but it doesn‘t work.
There is just a questionmark as a logo and nothing appears in the list.

**Comment by shortyHonk** [comment]
> @shortyHonk if you use my fork for testing, it should work for you. #2261

What do you mean with fork? 
thanks for your reply

**Comment by BMOD89** [comment]
It is now in the new release. I think you can close this issue
