### ISSUE TITLE
BW-SS7 1 gang modelID: 'TS0003', manufacturerName: '_TYZB01_aneiicmq'

### ISSUE THREAD

**Issue by PetersPlace** [Koenkk/zigbee-herdsman-converters#2269]
https://github.com/Koenkk/zigbee2mqtt/issues/5927  
Looks the same as the 2 gang   on row 14888  in the source code devices.js    fingerprint: [{modelID: 'TS0003', manufacturerName: '_TYZB01_digziiav'}],

I added it also as william89731   and it works perfect.
`
//BW-SS7 1 gang

    {

        fingerprint: [{modelID: 'TS0003', manufacturerName: '_TYZB01_aneiicmq'}],
        model: 'BW-SS7',
        vendor: 'BlitzWolf',
        description: 'Zigbee 3.0 smart light switch module 1 gang',
        extend: preset.switch(),
        exposes: [e.switch().withEndpoint('l1')],
        endpoint: (device) => {
            return {'l1': 1};
        },
        toZigbee: [tz.TYZB01_on_off],
        meta: {configureKey: 1, multiEndpoint: true},
        configure: async (device, coordinatorEndpoint, logger) => {
            await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['genOnOff']);
        },
    },
`

**Comment by Koenkk** [comment]
Added!

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
