### ISSUE TITLE
bticino *4027C Connected shutter control switch series support

### ISSUE THREAD

**Issue by antonio-gt** [Koenkk/zigbee-herdsman-converters#2276]
Hi,

I'd like to add support for the bticino series *4027C.
This series includes seven devices: K4027C, N4027C/N4027CIL, NT4027C/NT4027CIL, L4027C/L4027CIL, real difference between them is just color and button shape.

Here is the product sheet: https://catalogue.bticino.com/BTI-N4027C-EN

I'm using a Raspberry Pi4 with a CC2538 usb ZigBee controller, Home Assistant Core + MQTT + ZigBee2mqtt wrapper.

I see one year ago @blackwiz4rd opened issue https://github.com/Koenkk/zigbee-herdsman-converters/issues/1057 which was closed after a  while.

Does anyone have any new news/feedback about that kind of integration?

Thanks!
Antonio

**Comment by blackwiz4rd** [comment]
Hi @antonio-gt . I have not made a pull request for K4027C even if I have a working device, however someone else seems to have added the L4027C/N4027C/NT4027C, with unreliable cover position as stated in the comment:
https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js.
I will try and add the K4027C soon when I have time.

**Comment by antonio-gt** [comment]
Hi @blackwiz4rd, ok thanks, I missed that comment.

**Comment by blackwiz4rd** [comment]
You are welcome. The K4027C was now included in zigbee-herdsman-converters ;)

**Comment by antonio-gt** [comment]
I see that, thanks! ;)
