### ISSUE TITLE
DJT11LM bed_activity

### ISSUE THREAD

**Issue by dlashua** [Koenkk/zigbee-herdsman-converters#228]
When using the Xiaomi Vibration Sensor with the native Gateway, Vibration sensors report status (vibrate, tilt, freefall), coordination, and tilt angle, as they do with zigbee2mqtt. However, the also report bed_activity, which seems to be a number representing just how wiggly the thing was in the last minute. 

This number is useful for knowing, for instance, if the bed was just briefly sat on, or if it is being jumped on. Also useful in measuring the vibration of appliances like a clothes dryer (did someone just slam the door, or is the dryer running? If running, is the load off balance causing more vibration than usual?).

My Clothes Dryer, which doesn't vibrate much at all, reports a number of 24, when someone opens or closes the door, and a number like 91 when it's running. 

I'd be happy to change the code myself to pull this piece of data out of the return values, but I don't have any specs on how the data looks nor do I know how to get the data that was used to write the current implementation. Can you point me in the right direction?

**Comment by Koenkk** [comment]
The code interpreting the values reported by the sensor can be found here: https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/converters/fromZigbee.js#L902

**Comment by dlashua** [comment]
I found the code in zigbee-shepherd-converters already. But, I don't know how to access what else is available in msg.data.data at that point, nor do I have any documentation on the data transmitted by the DJT11LM in order to write the code "blind" and see if it works.

I guess I could add some debugging directly into the zigbee-shepherd-converters library and then go from there. I was hoping you might have some better information to go with. I'll give that a shot though.

**Comment by Koenkk** [comment]
The data transmitted by the DJT11LM is indeed not documented, adding these kind of device is a matter of trial and error (what value changes when you do X with the sensor).

**Comment by FrankZZ** [comment]
I've also ordered the device and am looking forward to reverse engineer the zigbee data of it

**Comment by james-fry** [comment]
Quite a lot of info here:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/748
