### ISSUE TITLE
Add support for MEGOS Panels (Aldi)

### ISSUE THREAD

**Issue by thackel** [Koenkk/zigbee-herdsman-converters#2280]
```
Zigbee2MQTT:warn  2021-02-23 13:36:02: Received message from unsupported device with Zigbee model 'TS0505B' and manufacturer name '_TZ3000_gb5gaeca'
```

https://www.sued.aldi-liefert.de/Wohnen-Einrichten/Smartes-Zigbee-LED-Panel-RGB-CCT-120-x-30-cm.html

![image](https://user-images.githubusercontent.com/1008148/108844863-f21a5900-75dc-11eb-97cf-eaa27835066b.png)

**Comment by Koenkk** [comment]
Added!

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by thackel** [comment]
Why did you revert the change?

**Comment by Koenkk** [comment]
Because after this change I saw a PR that also adds the other light: https://github.com/Koenkk/zigbee-herdsman-converters/commit/3b9420cbfae8efb2295044f4d85eb144279b1288 / https://github.com/Koenkk/zigbee-herdsman-converters/pull/2281
