### ISSUE TITLE
Want StartupCurrentLevel and Level -> ColorTemperature coupling

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee-herdsman-converters#2284]
<img width="725" alt="image" src="https://user-images.githubusercontent.com/379665/108897434-61f90580-7616-11eb-96c6-e0844f4fee08.png">
<img width="717" alt="image" src="https://user-images.githubusercontent.com/379665/108897656-a08ec000-7616-11eb-951a-075aa3e7868a.png">
<img width="758" alt="image" src="https://user-images.githubusercontent.com/379665/108897912-e0ee3e00-7616-11eb-8edb-399261605b96.png">
<img width="770" alt="image" src="https://user-images.githubusercontent.com/379665/108897976-f19eb400-7616-11eb-9dda-eeb7d0ead97d.png">

I thought the ct to level coupling was also on the ligthingColorCtrl cluster, but it looks like it is actually on the levelControl cluster. While looking around I also noticed we have a StartupCurrentLevel property.

The later should be easy and I can implement analogues to color_temp_startup.

The coupling is a bit more complex, based on ZCL it seems the enable/disable is on the levelControl's options property. I can add a level_options like we did for color_options, but the ct->lvl configuration is a property on the ligthingColorCtrl cluster... I'm not sure how to best deal with this. Do I implement this as a new attribute 'color_temp_level_couple' ? Or do we ignore the odd placement and add it to the level_options as a additional attribute, so both enable and lvl setting is configure via level_options ?

@Koenkk some input/ideas would be be welcome. I have some Viessmann stuff I want to poke first this weekend though, and I will do the _startup as a separate PR too.

**Comment by Koenkk** [comment]
What if we rename `color_options` to `light_options` and combine both?

**Comment by sjorge** [comment]
That could work... so something like

```json
{
  "light_options": {
    "execute_if_off": true,
    "color_temp_level_coupled": true,
    "color_temp_level_coupled_min: <whatever default is>,
  }
}
```

or maybe if we move _startup too (that honestly would make sense to me?)


```json
{
  "light_configuration": {
    "execute_if_off": true,
    "color_temp_level_coupled": true,
    "color_temp_level_coupled_min: <whatever default is>,
    "color_temp_startup: 0xff,
    "brightness_startup: 0xff,
  }
}
```

So all 'configuration' for lights is in one spot?

For toZigbee that wont be to hard, we can just do multiple writes to the different clusters. But how would we handle the fromZigbee? How do we merge this? Is there an internal spot to store this state?

**Comment by Koenkk** [comment]
Good idea, you can retrieve the existing `light_configuration` in a fromZigbee converters via `meta.state. light_configuration`

**Comment by sjorge** [comment]
So just have multiple fromZigbee return part of the object, should be easy enough.

I'll probably tackle this after I wip up some testing stuff for the viessman this weekend.

**Comment by sjorge** [comment]
Looks like already have the level bits

https://github.com/Koenkk/zigbee-herdsman-converters/blob/f5491356376189aa3c5d48997e2dd912613dba59/converters/toZigbee.js#L261

**Comment by sjorge** [comment]
```
        light_color_options: () => new Composite('color_options', 'color_options')
            .withDescription('Configure lighting cluster options attribute.')
            .withFeature(new Binary('execute_if_off', access.ALL, true, false).withDescription('Execute color/color_temp changes even when light is off')),
```

Backup here, as we might want to expose this again some/all of this issue. But for select bulbs only.
