### ISSUE TITLE
Pls add new manufacturerName '_TZ3000_wr2ucaj9' for Tuya model: 'TS0215A_sos'

### ISSUE THREAD

**Issue by louismulder** [Koenkk/zigbee-herdsman-converters#2301]
{
        fingerprint: [{modelID: 'TS0215A', manufacturerName: '_TZ3000_4fsgukof'},
		              {modelID: 'TS0215A', manufacturerName: '_TZ3000_wr2ucaj9'}],
        model: 'TS0215A_sos',
        vendor: 'TuYa',
        description: 'SOS button',
        fromZigbee: [fz.command_emergency, fz.battery],
        exposes: [e.battery(), e.action(['emergency'])],
        toZigbee: [],
    },

**Comment by Koenkk** [comment]
Can you provide a link with picture of this device? (e.g. aliexpress)

**Comment by louismulder** [comment]
Hi @Koenkk,

Here is the link: [https://nl.aliexpress.com/item/4001053429015.html?spm=a2g0o.productlist.0.0.761d1c44rBJMxh&algo_pvid=606a6c84-222c-4ad1-83e1-fd244669aa80&algo_expid=606a6c84-222c-4ad1-83e1-fd244669aa80-1&btsid=2100bdd816144397066267422e9371&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_](url)

**Comment by louismulder** [comment]
Sorry @Koenkk,

This is a short link: [https://nl.aliexpress.com/item/4001053429015.html](url)

**Comment by louismulder** [comment]
Hi @Koenkk 

It seems that inserting an URL doesn't work.

Here is the text version
https://nl.aliexpress.com/item/4001053429015.html

**Comment by Koenkk** [comment]
Added!

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by rt400** [comment]
@louismulder Do you have battery info ?

**Comment by louismulder** [comment]
> @louismulder Do you have battery info ?

Hi rt400,

Yes I have battery info

**Comment by rt400** [comment]
> > @louismulder Do you have battery info ?
> 
> Hi rt400,
> 
> Yes I have battery info

did you add something to your external config ?

**Comment by louismulder** [comment]
> > > @louismulder Do you have battery info ?
> > 
> > 
> > Hi rt400,
> > Yes I have battery info
> 
> did you add something to your external config ?

Hi rt400,

No I don't use an external config.
