### ISSUE TITLE
Confused with TS0504B Zigbee RGBW LED Strip from Tuya

### ISSUE THREAD

**Issue by pukamakara** [Koenkk/zigbee-herdsman-converters#2335]
Hello. 
Just got this LEd strip from Tuya, Tried to pair it with z2m, but it appears as an unsupported device. 
I went to logs and saw  this warning:
`Zigbee2MQTT:warn  2021-03-08 01:08:05: Device '0x60a423fffe97e3e1' with Zigbee model 'TS0504B' and manufacturer name '_TZ3000_riwp3k79' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html`

I followed the instructions but I discovered that this  Zigbee model (TS050B) exists in devices.js as Tuya LED strip (which is ok), but with a different manufacturer name. And the manufacturer name from my log belongs to another device (model: HG06104A,
 vendor: Lidl)

Could you explain to me how to add this device to z2m? Thank you.

**Comment by pukamakara** [comment]
Just got another LED strip controller. For this device log says:

`Warning Device '0x60a423fffe97e3f0' with Zigbee model 'TS0504B' and manufacturer name '_TZ3000_ukuvyhaa' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html`

so the manufacturer name seems to be correct, but still, it appears as an unsupported device in z2m, 
Now I have to identical devices connected to z2m - one is wrong model, another unsupported. 
@Koenkk  please help
See screenshot here
[http://vr-3d.ru/1.jpg](url)

**Comment by Koenkk** [comment]
Both are supported in the latest dev branch: https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html
