### ISSUE TITLE
Support of Moes ZTS-EU (3 gang)

### ISSUE THREAD

**Issue by oleynikandrey** [Koenkk/zigbee-herdsman-converters#2344]
Hello, I'm trying to add support for new Moes 3 gang switch, but ran into some problems.

I've added the following description of device:
```js
    {
        fingerprint: [{modelID: 'TS0601', manufacturerName: '_TZE200_tz32mtza'}],
        model: 'ZTS-EU',
        vendor: 'Moes',
        description: 'Wall touch light switch (3 gang)',
        exposes: [
            e.switch().withEndpoint('l1').setAccess('state', ea.STATE_SET),
            e.switch().withEndpoint('l2').setAccess('state', ea.STATE_SET),
            e.switch().withEndpoint('l3').setAccess('state', ea.STATE_SET)
        ],
        fromZigbee: [fz.tuya_switch_2],
        toZigbee: [tz.tuya_switch_state],
        meta: {multiEndpoint: true},
        endpoint: (device) => {
            // Endpoint selection is made in tuya_switch_state
            return {'l1': 1, 'l2': 1, 'l3': 1};
        },
    },
```

It works good, but Home Assistant became define already existing device with the same model but with 1 gang (manufacturerName = `_TZE200_amp6tsvy`) as switch with 3 gangs. 

What is the correct way to support the same model with different number of gangs as one or separate devices?

**Comment by Koenkk** [comment]
Added it (renamed `ZTS-EU` to `ZTS-EU_1gang`)


Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
