### ISSUE TITLE
child_lock Expose does not match toZigbee / fromZigbee

### ISSUE THREAD

**Issue by asgothian** [Koenkk/zigbee-herdsman-converters#2346]
I have been looking into reports that certain Thermostats either don't report the child_lock state correctly or do not allow to set the child_lock. As initial response, i asked for the affected Thermostats to be swapped over to exposes in order to use the expose code. Unfortunately, this did not solve the issue.

Looking more closely, i found
- in toZigbee, most states expect the command 'LOCK' or 'UNLOCK' (with the currently unused hy_thermostat being the sole exception
- in fromZigbee, all child_lock states report 'LOCKED' or 'UNLOCKED'.
- The expose preset for all given scenarios expects 'LOCK' and 'UNLOCK' as default.

As i do not have a device myself and a change would be a breaking change for people using this state i am hesitant to make any change at this point.

**Comment by Koenkk** [comment]
@sjorge do you have a thermostat with child lock?

**Comment by sjorge** [comment]
The viessman has the hvacUserInterfaceCfg keypad_lockout. Is that the one you are talking about?

I think the eurotornic one has a child_lock one that uses LOCKED/UNLOCKED but mine is not paired as it is completely unresponsive.

**Comment by Koenkk** [comment]
Fixed now,  (LOCKED -> LOCK, UNLOCKED -> UNLOCK)
