### ISSUE TITLE
Issue with Legrand 067771 (wrong mqqt message sent)

### ISSUE THREAD

**Issue by moonith** [Koenkk/zigbee-herdsman-converters#2362]
The problem is that adjusting brightness via HA slider is not working, since action being send is missing transition properly (if you send a message via eg. Mqtt explorer with transition property it is working as expected).

SENT TO /set:

- not working: `{"brightness":100, state: "ON"}` 

- working: `{"brightness":100, "transition": 1}`

I am fairly new to whole zigbee2mqtt game, and I don't really know what I should update in pr fixing this. I guess line 15049 in devices.js?

**Comment by moonith** [comment]
Also publishing a message with transition property results in error shown in zigbee2mqtt ui
<img width="233" alt="image" src="https://user-images.githubusercontent.com/7809497/111039929-08277680-8431-11eb-87cf-97c810c92589.png">

**Comment by sbystrov** [comment]
You can fix this by adding line
```
  transition: 1
```
in /config/zigbee2mqtt/devices.yaml

For example:
```
'0x00047400008bf4a9':
  friendly_name: Switch.LightDimmable.BigRoom
  transition: 1
```
