### ISSUE TITLE
Only half of the battery percentage shown for ROBB/Sunricher 8 button wall switch (ROB_200-007-0)

### ISSUE THREAD

**Issue by d-EScape** [Koenkk/zigbee-herdsman-converters#2411]
My brand new ROB_200-007-0 (8 button wall switch) is reporting 50% battery power. I took the battery out and it measures 3.126V, so I suspect the "battery_not_divided" converter is needed. Unfortunately I am not sure where to change it... my first attempt killed all incoming conversions :-$

Can you disable the divider for this device? The same _probably_ goes for the 4 button variant of this wall switch.
8 button version = zigbeeModel: ['ZG2833K8_EU05', 'ROB_200-007-0']
4 button version = zigbeeModel: ['ZG2833K4_EU06', 'ROB_200-008']

**The Zigbee message:**
Received Zigbee message from 'Push8bee', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":100}' from endpoint 1 with groupID 0

**Results in:**
MQTT publish: topic 'zigbee2mqtt/Push8bee', payload '{"battery":50,"linkquality":108}'

**Comment by d-EScape** [comment]
Found it! But my GitHub is a mess right now. Could someone put this in the zigbeeModel: ['ZG2833K8_EU05', 'ROB_200-007-0']?

`meta: {multiEndpoint: true, battery: {dontDividePercentage: true}},`

just like it already is for the 4 button version (zigbeeModel: ['ZG2833K4_EU06', 'ROB_200-008']).
Thanks in advance!

**Comment by Koenkk** [comment]
Fixed. 

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
