### ISSUE TITLE
How to add this herdsman converters

### ISSUE THREAD

**Issue by benalla** [Koenkk/zigbee-herdsman-converters#2412]
Hi all
I try to find out how to add this.
Use npm to install.......   Using ssh npm command cannot be found.

Please help me out, I need to add my Paul Neuhaus Q Remote.

**Comment by Multipage** [comment]
If you can be more specific what you are trying to do maybe somebody can help you.

You want to install npm? Or what is the exact problem

**Comment by benalla** [comment]
I want to add this Paul Neuhaus Q Remote:
https://www.zigbee2mqtt.io/devices/100.462.31.html

Using a CC2531 and Zigbee2mqtt the device cannot be discovered.

As far as I can find out is that I need to use/install the Herdsman converters.

**Comment by sjorge** [comment]
If zigbee2mqtt is running, you already have the converters installed as it won't even start without it.

As long as you're not running a super old version it should just work, or at least throw some sort of error if it fails to join.

**Comment by benalla** [comment]
I have zigbee2mqtt running with other devices: version 1.18.1
This Q Remote device is not recognized/supported, while it should be.

![image](https://user-images.githubusercontent.com/3511603/112903349-abda7d00-90e7-11eb-8003-e246a31e8af3.png)

Zigbee2MQTT version: 1.18.1 commit: 1.18.1
Coordinator type: zStack12
Coordinator revision: 20190608
Frontend version: 0.3.76

**Comment by Multipage** [comment]
So it IS discover but it's unsupported. That's something else.

Give us more info. What does the log say abouth this device. (maybe re-pair it to see the device info in the log)

**Comment by benalla** [comment]
This is part of log after restart of HA:

debug 2021-03-29 21:14:19: Loaded state from file /share/zigbee2mqtt/state.json
info  2021-03-29 21:14:19: Logging to console and directory: '/share/zigbee2mqtt/log/2021-03-29.21-14-17' filename: log.txt
debug 2021-03-29 21:14:19: Removing old log directory '/share/zigbee2mqtt/log/2021-02-15.23-39-19'
info  2021-03-29 21:14:19: Starting Zigbee2MQTT version 1.18.1 (commit #1.18.1)
info  2021-03-29 21:14:19: Starting zigbee-herdsman (0.13.71)
debug 2021-03-29 21:14:19: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null},"backupPath":"/share/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/share/zigbee2mqtt/database.db.backup","databasePath":"/share/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001949B06B-if00"}}'
info  2021-03-29 21:14:22: zigbee-herdsman started
info  2021-03-29 21:14:22: Coordinator firmware version: '{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2},"type":"zStack12"}'
debug 2021-03-29 21:14:22: Zigbee network parameters: {"channel":11,"extendedPanID":"0xdddddddddddddddd","panID":6754}
info  2021-03-29 21:14:22: Currently 6 devices are joined:
info  2021-03-29 21:14:22: Aqara temp sensor slpk (0x00158d00058ca441): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
info  2021-03-29 21:14:22: Aqara temp sensor Yasmine (0x00158d000283e5b8): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
info  2021-03-29 21:14:22: Aqara temp sensor Zidane (0x00158d00044c0370): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
info  2021-03-29 21:14:22: Aqara temp sensor kinderkamer (0x00158d000412f3de): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
info  2021-03-29 21:14:22: Woonkamer schuifpui (0x00158d0003ced195): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
info  2021-03-29 21:14:22: Q Remote (0x00158d000416ef12): Not supported (EndDevice)
warn  2021-03-29 21:14:22: `permit_join` set to  `true` in configuration.yaml.
warn  2021-03-29 21:14:22: Allowing new devices to join.
warn  2021-03-29 21:14:22: Set `permit_join` to `false` once you joined all devices.
info  2021-03-29 21:14:22: Zigbee: allowing new devices to join.
info  2021-03-29 21:14:22: Started frontend on port 0.0.0.0:8099
info  2021-03-29 21:14:22: Connecting to MQTT server at mqtt://192.168.1.202:1883
debug 2021-03-29 21:14:22: Using MQTT login with username: mosquitto
info  2021-03-29 21:14:23: Connected to MQTT server
info  2021-03-29 21:14:23: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
info  2021-03-29 21:14:23: MQTT publish: topic 'zigbee2mqtt/Aqara temp sensor slpk', payload '{"battery":100,"humidity":54.85,"pressure":1029,"temperature":20.17,"voltage":3005}'
info  2021-03-29 21:14:24: MQTT publish: topic 'zigbee2mqtt/Aqara temp sensor Yasmine', payload '{"battery":100,"humidity":47.56,"pressure":1029.4,"temperature":22.74,"voltage":3025}'
info  2021-03-29 21:14:24: MQTT publish: topic 'zigbee2mqtt/Aqara temp sensor Zidane', payload '{"battery":91,"humidity":53.95,"pressure":1030,"temperature":20.28,"voltage":2985}'
info  2021-03-29 21:14:24: MQTT publish: topic 'zigbee2mqtt/Aqara temp sensor kinderkamer', payload '{"battery":100,"humidity":44.64,"pressure":1029,"temperature":22.16,"voltage":3005}'
info  2021-03-29 21:14:24: MQTT publish: topic 'zigbee2mqtt/Woonkamer schuifpui', payload '{"battery":100,"contact":false,"temperature":29,"voltage":3015}'

**Comment by Multipage** [comment]
You didn't rejoin the device
'info 2021-03-29 21:14:22: Q Remote (0x00158d000416ef12): Not supported (EndDevice)'

Rejoin/re-pair the device and post THAT log here. Maybe there is more info there. What you've posted is just e restart of zigbee2mqtt not a re-pair/rejoin

It's step 1 in :
https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
```

Instructions #
1. Pairing the device with Zigbee2MQTT #
The first step is to pair the device with Zigbee2MQTT. It should be possible to pair your unsupported device out of the box because Zigbee2MQTT can pair with any zigbee device. You need to find out how to bring your device into pairing mode, most of the time via a factory reset.

Once you successfully paired the device you will see something like:

Zigbee2MQTT:info  2019-11-09T12:19:56: Successfully interviewed '0x00158d0001dc126a', device has successfully been paired
Zigbee2MQTT:warn  2019-11-09T12:19:56: Device '0x00158d0001dc126a' with Zigbee model 'lumi.sens' and manufacturer name 'some_name' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
NOTE: Make sure that permit_join: true is set in configuration.yaml otherwise new devices cannot join the network.


```

**Comment by benalla** [comment]
I'll be damned......
I have paired and paired it hundreds of times.......
Now I do a factory reset again and pair the remote:
![image](https://user-images.githubusercontent.com/3511603/112956464-cc82f100-9140-11eb-9a3d-3e2c4999fb5f.png)

Log:
Debug Saving state to file /share/zigbee2mqtt/state.json
Warning Device '0x00158d000416ef12' left the network
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"ieee_address":"0x00158d000416ef12"},"type":"device_leave"}'
Info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"left_network","meta":{"friendly_name":"0x00158d000416ef12"},"type":"device_removed"}'
Info Device 'Q Remote' joined
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"Q Remote","ieee_address":"0x00158d000416ef12"},"type":"device_joined"}'
Info Starting interview of 'Q Remote'
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"Q Remote","ieee_address":"0x00158d000416ef12","status":"started"},"type":"device_interview"}'
Info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"Q Remote"},"type":"device_connected"}'
Info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"Q Remote"},"type":"pairing"}'
Debug Device 'Q Remote' announced itself
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"Q Remote","ieee_address":"0x00158d000416ef12"},"type":"device_announce"}'
Info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"Q Remote"},"type":"device_announced"}'
Debug Received Zigbee message from 'Q Remote', type 'readResponse', cluster 'genBasic', data '{"modelId":"NLG-remote"}' from endpoint 1 with groupID 0
Debug Received Zigbee message from 'Q Remote', type 'readResponse', cluster 'genBasic', data '{"manufacturerName":"Neuhaus Lighting Group"}' from endpoint 1 with groupID 0
Debug Received Zigbee message from 'Q Remote', type 'readResponse', cluster 'genBasic', data '{"powerSource":3}' from endpoint 1 with groupID 0
Debug Received Zigbee message from 'Q Remote', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3}' from endpoint 1 with groupID 0
Debug Received Zigbee message from 'Q Remote', type 'readResponse', cluster 'genBasic', data '{"appVersion":1}' from endpoint 1 with groupID 0
Debug Received Zigbee message from 'Q Remote', type 'readResponse', cluster 'genBasic', data '{"stackVersion":1}' from endpoint 1 with groupID 0
Debug Received Zigbee message from 'Q Remote', type 'readResponse', cluster 'genBasic', data '{"hwVersion":1}' from endpoint 1 with groupID 0
Debug Received Zigbee message from 'Q Remote', type 'readResponse', cluster 'genBasic', data '{"dateCode":"20180905"}' from endpoint 1 with groupID 0
Debug Received Zigbee message from 'Q Remote', type 'readResponse', cluster 'genBasic', data '{"swBuildId":"2000-0001"}' from endpoint 1 with groupID 0
Info Successfully interviewed 'Q Remote', device has successfully been paired
Info Device 'Q Remote' is supported, identified as: Paul Neuhaus Q-REMOTE (100.462.31)
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"Q-REMOTE","exposes":[{"access":1,"description":"Triggered action (e.g. a button click)","name":"action","property":"action","type":"enum","values":["on","off","toggle","brightness_step_up","brightness_step_down","color_temperature_move","color_move","brightness_stop","brightness_move_up","brightness_move_down","color_loop_set","enhanced_move_to_hue_and_saturation","recall_*","scene_*"]},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"100.462.31","supports_ota":false,"vendor":"Paul Neuhaus"},"friendly_name":"Q Remote","ieee_address":"0x00158d000416ef12","status":"successful","supported":true},"type":"device_interview"}'
Info MQTT publish: topic 'homeassistant/sensor/0x00158d000416ef12/action/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d000416ef12"],"manufacturer":"Paul Neuhaus","model":"Q-REMOTE (100.462.31)","name":"Q Remote","sw_version":"Zigbee2MQTT 1.18.1"},"icon":"mdi:gesture-double-tap","json_attributes_topic":"zigbee2mqtt/Q Remote","name":"Q Remote action","state_topic":"zigbee2mqtt/Q Remote","unique_id":"0x00158d000416ef12_action_zigbee2mqtt","value_template":"{{ value_json.action }}"}'
Info MQTT publish: topic 'homeassistant/sensor/0x00158d000416ef12/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d000416ef12"],"manufacturer":"Paul Neuhaus","model":"Q-REMOTE (100.462.31)","name":"Q Remote","sw_version":"Zigbee2MQTT 1.18.1"},"icon":"mdi:signal","json_attributes_topic":"zigbee2mqtt/Q Remote","name":"Q Remote linkquality","state_topic":"zigbee2mqtt/Q Remote","unique_id":"0x00158d000416ef12_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
Info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"description":"Q-REMOTE","friendly_name":"Q Remote","model":"100.462.31","supported":true,"vendor":"Paul Neuhaus"},"type":"pairing"}'
Debug Received MQTT message on 'homeassistant/sensor/0x00158d000416ef12/action/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d000416ef12"],"manufacturer":"Paul Neuhaus","model":"Q-REMOTE (100.462.31)","name":"Q Remote","sw_version":"Zigbee2MQTT 1.18.1"},"icon":"mdi:gesture-double-tap","json_attributes_topic":"zigbee2mqtt/Q Remote","name":"Q Remote action","state_topic":"zigbee2mqtt/Q Remote","unique_id":"0x00158d000416ef12_action_zigbee2mqtt","value_template":"{{ value_json.action }}"}'
Debug Received MQTT message on 'homeassistant/sensor/0x00158d000416ef12/linkquality/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d000416ef12"],"manufacturer":"Paul Neuhaus","model":"Q-REMOTE (100.462.31)","name":"Q Remote","sw_version":"Zigbee2MQTT 1.18.1"},"icon":"mdi:signal","json_attributes_topic":"zigbee2mqtt/Q Remote","name":"Q Remote linkquality","state_topic":"zigbee2mqtt/Q Remote","unique_id":"0x00158d000416ef12_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'

**Comment by benalla** [comment]
No I need to find out how to use it in Lovelace dashboard, or TileBoard.

**Comment by Multipage** [comment]
Seems it couldn't be interviewed right for some reason.

Can't help you with adding it to the dashboard, sorry ;)

Please close the issue as it's resolved.
