### ISSUE TITLE
Need help adding support for Friend Heat alarm

### ISSUE THREAD

**Issue by brantje** [Koenkk/zigbee-herdsman-converters#2443]
Hi,
Thank you for writing this wonderful piece of software.
I recently picked up some [Frient Heat Alarms](https://frient.com/products/intelligent-heat-alarm/). 
However they are not yet supported by zigbee2mqtt.

The same model i use is listed as supported: https://www.zigbee2mqtt.io/devices/HESZB-120.html

**Comment by Koenkk** [comment]
Can you provide the data/database.db entry of this device?

**Comment by brantje** [comment]
``` 
{"id":11,"type":"EndDevice","ieeeAddr":"0x0015bc0034000809","nwkAddr":7599,"manufId":4117,"manufName":"frient A/S","powerSource":"Battery","modelId":"HESZB-120","epList":[1,35,38],"endpoints":{"1":{"profId":49353,"epId":1,"devId":1,"inClusterList":[3,5,6],"outClusterList":[],"clusters":{},"binds":[],"meta":{}},"35":{"profId":260,"epId":35,"devId":1026,"inClusterList":[0,1,3,15,32,1280,1282],"outClusterList":[10,25],"clusters":{"genBasic":{"attributes":{"modelId":"HESZB-120","manufacturerName":"frient A/S","powerSource":3,"zclVersion":1,"dateCode":"2020-11-20 12:02"}}},"binds":[],"meta":{}},"38":{"epId":38,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"meta":{}}},"dateCode":"2020-11-20 12:02","zclVersion":1,"interviewCompleted":false,"meta":{},"lastSeen":1617531938163}
```
The model is same, seems frient just changed the manufacturerName.

**Comment by mamrai1** [comment]
it;s already supported.....

**Comment by brantje** [comment]
As i said, it's not. Since the device indentifies with manufacturer "Frient A/S" NOT Develco as in your PR ;)

**Comment by mamrai1** [comment]
![Screenshot_20210405_125647_com android chrome](https://user-images.githubusercontent.com/57288344/113562278-80d3ba00-960e-11eb-9a8b-cb7a7f99e9ff.jpg)

**Comment by mamrai1** [comment]
Weird..

**Comment by brantje** [comment]
@mamrai1 On what branch of z2m are you? I'm currently on the stable channel. The PR is merged 20 days ago, so my guess is that i need to be on the dev branch.

**Comment by mamrai1** [comment]
1.18.2

**Comment by brantje** [comment]
That prob it, i'm on 1.18.1-1 ( )

**Comment by brantje** [comment]
Just updated to latest version which should have support, but still doesn't work.
@Koenkk any idea how to progress further? 

![afbeelding](https://user-images.githubusercontent.com/2758767/113890697-ae626400-97c4-11eb-933f-e27d3baa9b13.png)


```{"id":11,"type":"EndDevice","ieeeAddr":"0x0015bc0034000809","nwkAddr":35829,"manufId":4117,"manufName":"frient A/S","powerSource":"Battery","modelId":"HESZB-120","epList":[1,35,38],"endpoints":{"1":{"profId":49353,"epId":1,"devId":1,"inClusterList":[3,5,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"35":{"profId":260,"epId":35,"devId":1026,"inClusterList":[0,1,3,15,32,1280,1282],"outClusterList":[10,25],"clusters":{"genBasic":{"attributes":{"modelId":"HESZB-120","manufacturerName":"frient A/S","powerSource":3,"zclVersion":1,"dateCode":"2020-11-20 12:02"}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00212effff05e9bc","zoneState":1}}},"binds":[],"configuredReportings":[],"meta":{}},"38":{"profId":260,"epId":38,"devId":770,"inClusterList":[0,3,1026],"outClusterList":[3],"clusters":{"genBasic":{"attributes":{}}},"binds":[],"configuredReportings":[],"meta":{}}},"dateCode":"2020-11-20 12:02","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1617808316931}```

**Comment by mamrai1** [comment]
Zigbee2mqtt in Home assistant or Docker?

**Comment by brantje** [comment]
In home assistant
