### ISSUE TITLE
color_temp_percent and colorTempRange

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee-herdsman-converters#2444]
https://github.com/Koenkk/zigbee-herdsman-converters/blob/ff744d4573a68b8bb558266105986ade8318c218/converters/toZigbee.js#L763

I'm not 100% sure but I think we should use the colorTempPhysicalMin / Max as target mapping range instead of the old 153 / 500 here?

cc: @Koenkk

**Comment by Koenkk** [comment]
Yes, and if no colorTempPhysicalMin/Max is available we should fallback to these defaults.
