### ISSUE TITLE
Device Request: Philips 5995111U5 (Hue)

### ISSUE THREAD

**Issue by srnoth** [Koenkk/zigbee-herdsman-converters#2469]
Recently purchased what I thought would be Philips 5996411U5 (https://www.zigbee2mqtt.io/devices/5996411U5.html).
https://www.homedepot.com/p/Philips-Hue-White-Ambiance-5-6-Integrated-LED-Dimmable-Smart-Wireless-Recessed-Downlight-Retrofit-Kit-801506/303993123

Showed up unsupported. These are exactly as described (Hue white ambiance 5/6” retrofit recessed downlight) but the model number is 5995111U5. 

Got them working with the generic light external_converter (https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/externalConvertersExample/light.js) changing:
```
    zigbeeModel: ['LTD005'],
    model: '5995111U5',
    vendor: 'Philips',
```

I believe this could be officially supported by adding the following to devices.js (identical to the 5996411U5 entry).

```
    {
        zigbeeModel: ['LTD005'],
        model: '5995111U5',
        vendor: 'Philips',
        description: 'Hue white ambiance 5/6" retrofit recessed downlight',
        meta: {turnsOffAtBrightness1: true},
        extend: preset.hue.light_onoff_brightness_colortemp(),
        ota: ota.zigbeeOTA,
    },
```

Unfortunately I'm running the Hassio addon and editing the devices.js file directly seems to be impossible. I'd be happy to test with the Edge version though.

Thanks.

**Comment by srnoth** [comment]
Figured out how to edit the Hassio docker image, added the above code to the devices.js file, can confirm is working correctly. Even OTA updates are working.

**Comment by Koenkk** [comment]
Could you also provide the min/max color temp? (see https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html#31-retrieving-color-temperature-range-only-required-for-lights-which-support-color-temperature). You might need to add `tz.read` to the `toZigbee` list.

**Comment by srnoth** [comment]
@Koenkk getting the following:

"level": "error",
    "message": "Failed to call 'EntityPublish' 'onMQTTMessage' (TypeError: Cannot read property 'key' of undefined\n    at /app/lib/extension/publish.js:185:56\n    at Array.find (<anonymous>)\n    at EntityPublish.onMQTTMessage (/app/lib/extension/publish.js:185:42)\n    at Controller.callExtensionMethod (/app/lib/controller.js:380:44)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5))"

The box says the color range is 2200-6500k, or 454-153 mireds.

**Comment by Koenkk** [comment]
Are you on z2m 1.18.2?

**Comment by srnoth** [comment]
> Are you on z2m 1.18.2?

No idea why HASSIO isn't showing the 1.18.2 update. Manually updated and here is the readout:

```
{
    "level": "info",
    "message": "Read result of 'lightingColorCtrl': {\"colorTempPhysicalMin\":153,\"colorTempPhysicalMax\":454}"
}
```

**Comment by Koenkk** [comment]
Thanks, added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
