### ISSUE TITLE
TS0504B Device pairing incomplete without message

### ISSUE THREAD

**Issue by ahnungsbefreit** [Koenkk/zigbee-herdsman-converters#2471]
Pairing of a new TS0504B device (Tuya LED Controller) ends without error message but the device is not accessible. After some seconds, the tile of the object and all datapoints disappear without any error message.
[2021-04-12 zigbee log.txt](https://github.com/Koenkk/zigbee-herdsman-converters/files/6298586/2021-04-12.zigbee.log.txt)

**Comment by asgothian** [comment]
I tried to go through the log to verify if it was an issue on the iobroker side but could not find a clean cause for this behavior. What i did find is several Lines with 

```zigbee.0 (19099) Wrong device 60a423fffec20422 null```
mixed in with the zigbee-herdsman-debug messages.
Interestingly enough, the device does report its link quality to the system.

A.

**Comment by ahnungsbefreit** [comment]
Any update on this? Any missing information?

**Comment by ahnungsbefreit** [comment]
What do you need to take this up again?
