### ISSUE TITLE
Aurora lightning vintage bulbs

### ISSUE THREAD

**Issue by albertmonzo** [Koenkk/zigbee-herdsman-converters#2477]
Bought [this off Amazon](https://www.amazon.co.uk/gp/product/B081NFZZ6L/)

Made it work with this external converter:

```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const e = exposes.presets;
const ea = exposes.access;

const device = {
        zigbeeModel: ['FWG125Bulb50AU'],
        model: 'AU-A1VG125Z5E/19',
        vendor: 'Aurora Lighting',
        description: 'AOne 4W smart dimmable G125 lamp 1900K',
        fromZigbee: [fz.on_off, fz.brightness, fz.level_config, fz.power_on_behavior, fz.ignore_basic_report],
        toZigbee: [tz.light_onoff_brightness, tz.ignore_transition, tz.ignore_rate, tz.light_brightness_move, tz.light_brightness_step, tz.level_config, tz.power_on_behavior],
        exposes: [e.linkquality(), e.light_brightness()],
};

module.exports = device;    
```

Looking at[ this repo](https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/devicetypes/smartthings/zigbee-dimmer.src/zigbee-dimmer.groovy) there's 2 other vintage lights that will likely work with the exact same config:

* FWST64Bulb50AU Aurora Dimmable Filament Vintage ST64
* FWA60Bulb50AU Aurora Dimmable Filament Vintage GLS

**Comment by Koenkk** [comment]
Added, thanks!

**Comment by Koenkk** [comment]
Forgot to ask, could you also provide the color temp range for this bulb? Add `tz.read` to `toZigbee` and follow: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html#31-retrieving-color-temperature-range-only-required-for-lights-which-support-color-temperature

**Comment by albertmonzo** [comment]
@Koenkk There is no color temp range, it's a vintage filament lamp with a single (very warm) white. I think you added it as a tuneable bulb but it's not. You also forgot to add the other two bulbs I mentioned :) I don't have them but I'm 99% sure they are the exact same as they're basically the same bulb in different shapes released at the same time.

By the way, these bulbs spam my logs with 

```
Zigbee2MQTT:debug 2021-04-18 21:26:43: Received Zigbee message from 'Living room vintage TV', type 'commandQueryNextImageRequest', cluster 'genOta', data 
```

**Comment by Koenkk** [comment]
@albertmonzo thanks, will update.

Those lines are OTA request, but since we don't have a firmware we cannot provide an OTA.
