### ISSUE TITLE
Implementing defaults for devices so editing devices.js is less needed

### ISSUE THREAD

**Issue by sunsear** [Koenkk/zigbee-herdsman-converters#2481]
Just curious, we have a bunch of presets in devices.js. A lot of devices reuse these presets. Would it be possible to implement a sort of investigation method, where the signals the device gives off, are analysed to see if one of the presets matches? 

My Klik-aan-klik-uit hub, the ICS-2000 immediately worked with the 2 matcall devices that I just added. When I transported them to zigbee2mqtt, I found that nobody had added those to devices.js, I had to do that manually before they started working. I think a little bit of sensible defaulting would be helpful right?

**Comment by Koenkk** [comment]
There have been some discussion about this before. Main reason for not doing this as this will prevent people adding their devices which will make them not listed on https://www.zigbee2mqtt.io/information/supported_devices.html

**Comment by sunsear** [comment]
Wouldn’t it be possible to have autodiscovery, but also a preference that says: when autodiscovery finds a new device, send that to github?

**Comment by Koenkk** [comment]
Maybe we can look into generating a proposed converter. But not a fan of sending anything externally due to privacy reasons.

**Comment by sunsear** [comment]
Oh, but if we combine that idea with a change in the UI to give an option to send external converters to GitHub in a pull request, we have come full circle and still have the privacy controls in hands of the user.

**Comment by albertmonzo** [comment]
I agree that allowing the user to at least choose from one of the common presets is desirable. You can still ask them to voluntarily report whether a preset works or not, possibly without needing to involve github. Just collect stats in a simple app then possibly generate github templates once enough users have reported a preset works. You could even suggest "experimental" presets based on what users are reporting to other users before a PR is merged.
