### ISSUE TITLE
IKEA bulbs - improvements proposal 

### ISSUE THREAD

**Issue by muddy79** [Koenkk/zigbee-herdsman-converters#2484]
Hi,

I've created a new pull request with some IKEA bulbs / panels improvements: #2483 :
- new E14 LED1925G6 opal, white and color spectrum, 470lm - it supports both: color_temp and color_xy (contrary to the "old" 600lm bulb, which does not support color_temp directly)
- all bulbs and panels upgraded to ZigBee 3.0 support power on behavior: I've sucessfuly tested it on several devices (LED1536G5, LED1545G12, 	LED1623G12, LED1835C6, LED1925G6, L1527, LED1739R5, LED1923R5) and assumed it works on others, sharing the same firmware version; it DOES not work on drivers like ICPSHC24-10EU-IL-1 / ICPSHC24-30EU-IL-1
- new CWS bulbs do not support effects: tested on LED1923R5 and LED1925G6, assumed the same for other bulbs with the same firmware version.

To make the code cleaner a bit, I've moved the common settings to new presets: preset.tradfri.light_.*

**Comment by Koenkk** [comment]
Let's continue any discussion in https://github.com/Koenkk/zigbee-herdsman-converters/pull/2483
