### ISSUE TITLE
Github action to sort devices.js

### ISSUE THREAD

**Issue by svrooij** [Koenkk/zigbee-herdsman-converters#2495]
Sometimes it is quite hard to find some device in the devices.js file.

Maybe it's a good idea to enforce alphabetical order with some kind of script. And off course a easy to use script to organize all the devices. What do you think off this idea?

**Comment by nurikk** [comment]
Ideally we can split device definitions in sub-packages, like for xiaomi, philips, tuya
```

./devices.js

./devices/

./devices/xiaomi/devices.js

./devices/xiaomi/fromZigbee.js

./devices/xiaomi/toZigbee.js
```

**Comment by Koenkk** [comment]
@nurikk I also had this idea already. Will try to do this soon.

**Comment by Koenkk** [comment]
Created https://github.com/Koenkk/zigbee-herdsman-converters/pull/2500, please review
