### ISSUE TITLE
SmartThings IM6001-OTP01 outlet incorrectly identified 

### ISSUE THREAD

**Issue by mircolino** [Koenkk/zigbee-herdsman-converters#2502]
The SmartThings IM6001-OTP01 outlet is the 2018 version of the SmartThings STS-OUT-US-2, reporting power, current and voltage.
However zigbee2mqtt identifies the outlet as SmartThings IM6001-OTP05 without electrical measurement.

The correct entry in devices.js should be:

```
    {
        zigbeeModel: ['outlet'],
        model: 'IM6001-OTP01',
        vendor: 'Samjin',
        description: 'Outlet',
        fromZigbee: [fz.on_off, fz.electrical_measurement],
        toZigbee: [tz.on_off],
        meta: {configureKey: 2},
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'haElectricalMeasurement']);
            await reporting.onOff(endpoint);
            await reporting.readEletricalMeasurementMultiplierDivisors(endpoint);
            await reporting.activePower(endpoint);
            await reporting.rmsCurrent(endpoint);
            await reporting.rmsVoltage(endpoint, {change: 10});
        },
        exposes: [e.switch(), e.power(), e.current(), e.voltage()],
    }, 
```

which is identical to the STS-OUT-US-2 expect for the reported 'zigbeeModel' and 'vendor'.
Since there is already another ```zigbeeModel: ['outlet']``` entry in devices.js for the IM6001-OTP05 model, I'm not sure which is the best way to resolve this.

**Comment by Koenkk** [comment]
Could you provide the data/database.db entry of your device?

**Comment by mircolino** [comment]
[database.zip](https://github.com/Koenkk/zigbee-herdsman-converters/files/6366900/database.zip)

[configuration.zip](https://github.com/Koenkk/zigbee-herdsman-converters/files/6366905/configuration.zip)

<img width="920" alt="devices" src="https://user-images.githubusercontent.com/1192337/115904674-e64ee580-a419-11eb-9b0f-fd439006aa37.png">

<img width="694" alt="outlet" src="https://user-images.githubusercontent.com/1192337/115904692-eb139980-a419-11eb-866a-4019049a71f7.png">

**Comment by Koenkk** [comment]
Instead of the `zigbeeModel` use:

```js
        fingerprint: [
            {type: 'Router', manufacturerName: 'Samjin', modelID: 'outlet', endpoints: [
                {ID: 1, profileID: 260, deviceID: 2, inputClusters: [0, 3, 6, 8, 9, 2820], outputClusters: [3, 25]},
                {ID: 242, profileID: 41440, deviceID: 97, inputClusters: [], outputClusters: [33]},
            ]},
        ],
```

instead
