### ISSUE TITLE
Add Support For Aqara Smart Scene Panel Switch S1 (Model: ZNCJMB14LM Zigbee ID: lumi.switch.n4anc4)

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [Koenkk/zigbee-herdsman-converters#2520]
New zigbee controlled triple relay / smart scene screen from Aqara.

Device entry on Blackadder can be found here:
[Blackadder](https://zigbee.blakadder.com/Aqara_ZNCJMB14LM.html)

Reverse engineering of endpoints can be found here:
[Deconz](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Aqara-S1-Smart-Scene-Panel-Protocol)

I have one of these devices now, so happy to capture whatever is needed to develop a converter for this device. Due to its complication, this is a little bit too advanced for me to get my head around.

Database.db entry:
`{"id":2,"type":"Router","ieeeAddr":"0x04cf8cdf3c88d48a","nwkAddr":14342,"manufId":4447,"manufName":"LUMI","powerSource":"Mains (single phase)","modelId":"lumi.switch.n4acn4","epList":[1,2,242,3],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,2,3,4,5,6],"outClusterList":[10,25],"clusters":{"genBasic":{"attributes":{"modelId":"lumi.switch.n4acn4","manufacturerName":"LUMI","powerSource":1,"zclVersion":3,"appVersion":26,"stackVersion":2,"hwVersion":1,"dateCode":"06-18-2020"}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":256,"inClusterList":[0,3,4,5,6],"outClusterList":[],"clusters":{"genBasic":{"attributes":{}}},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":256,"inClusterList":[0,3,4,5,6],"outClusterList":[],"clusters":{"genBasic":{"attributes":{}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":26,"stackVersion":2,"hwVersion":1,"dateCode":"06-18-2020","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1619433552334}`

**Comment by danieledwardgeorgehitchcock** [comment]
I have managed to get the relays / switches working with this:

```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const e = exposes.presets;
const ea = exposes.access;

const device = {
    zigbeeModel: ['lumi.switch.n4acn4'],
    model: 'ZNCJMB14LM',
    vendor: 'Xiaomi',
    description: 'Aqara S1 Smart Touch Panel',
    fromZigbee: [fz.on_off],
    toZigbee: [tz.on_off],
    meta: {multiEndpoint: true},
    endpoint: (device) => {
            return {'left': 1, 'center': 2, 'right': 3};
    },
    exposes: [e.switch().withEndpoint('left'), e.switch().withEndpoint('center'), e.switch().withEndpoint('right')],
    configure: async (device, coordinatorEndpoint, logger) => {
            await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['genOnOff']);
            await reporting.bind(device.getEndpoint(2), coordinatorEndpoint, ['genOnOff']);
            await reporting.bind(device.getEndpoint(3), coordinatorEndpoint, ['genOnOff']);
            await reporting.onOff(device.getEndpoint(1));
            await reporting.onOff(device.getEndpoint(2));
            await reporting.onOff(device.getEndpoint(3));
    }
};

module.exports = device;
```

However, Zigbee2MQTT grumbles about a missing Opple converter - I have tried a couple of the Opple converters, and while the message disappears, I don't seem to see much in the way of useful information in the attribute response.

According to the Deconz documentation, the switches can be disabled too which means that my code above is a bit too rigid for this device.

**Comment by Koenkk** [comment]
Code looks good.

If none of the opple converters adds additional properties to the state we don't know yet what these values mean. To reverse engineer this you have to check what the device send and how this affect the state in the original bridge.

> According to the Deconz documentation, the switches can be disabled too which means that my code above is a bit too rigid for this device.

Could you link to the docs?

**Comment by danieledwardgeorgehitchcock** [comment]
@Koenkk - glad I’m on the right track! docs are in my original post :-)

**Comment by Koenkk** [comment]
I've created an example on how to set theme and standby enabled (https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Aqara-S1-Smart-Scene-Panel-Protocol#configure-the-settings). With this code you should be able to set both via the z2m frontend by clicking on the device and going to the exposes tab.

```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const e = exposes.presets;
const ea = exposes.access;

const xiaomiOptions = {manufacturerCode: 0x115F};

const tzLocal = {
    ZNCJMB14LM: {
        key: ['theme', 'standby_enabled'],
        convertSet: async (entity, key, value, meta) => {
            if (key === 'theme') {
                const lookup = {'classic': 0, 'concise': 1};
                // type u8 = uint8 = 0x20 (https://github.com/Koenkk/zigbee-herdsman/blob/608bebf0d1e0d9e538db5e9ae95f72f135c5543d/src/zcl/definition/dataType.ts#L21)
                await entity.write('aqaraOpple', {0x0215: {value: lookup[value], type: 0x20}}, xiaomiOptions);
                return {state: {theme: value}};
            } else if (key === 'standby_enabled') {
                // type bool = uint8 = 0x10 (https://github.com/Koenkk/zigbee-herdsman/blob/608bebf0d1e0d9e538db5e9ae95f72f135c5543d/src/zcl/definition/dataType.ts#L12)
                await entity.write('aqaraOpple', {0x0213: {value: value, type: 0x10}}, xiaomiOptions);
                return {state: {standby_enabled: value}};
            } else {
                throw new Error(`Not supported: '${key}'`);
            }
        },
    },
};

const device = {
    zigbeeModel: ['lumi.switch.n4acn4'],
    model: 'ZNCJMB14LM',
    vendor: 'Xiaomi',
    description: 'Aqara S1 Smart Touch Panel',
    fromZigbee: [fz.on_off],
    toZigbee: [tz.on_off, tzLocal.ZNCJMB14LM],
    meta: {multiEndpoint: true},
    endpoint: (device) => {
            return {'left': 1, 'center': 2, 'right': 3};
    },
    exposes: [e.switch().withEndpoint('left'), e.switch().withEndpoint('center'), e.switch().withEndpoint('right'),
        exposes.binary('standby_enabled', access.STATE_SET, true, false).withDescription('Enable standby'),
        exposes.enum('theme', access.STATE_SET, ['classic', 'concise']).withDescription('Display theme'),
    ],
    configure: async (device, coordinatorEndpoint, logger) => {
            await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['genOnOff']);
            await reporting.bind(device.getEndpoint(2), coordinatorEndpoint, ['genOnOff']);
            await reporting.bind(device.getEndpoint(3), coordinatorEndpoint, ['genOnOff']);
            await reporting.onOff(device.getEndpoint(1));
            await reporting.onOff(device.getEndpoint(2));
            await reporting.onOff(device.getEndpoint(3));
    }
};

module.exports = device;
```

**Comment by danieledwardgeorgehitchcock** [comment]
Great!

Thanks for your pointers!

I will test this and extend with the other attributes! :-)

**Comment by danieledwardgeorgehitchcock** [comment]
@Koenkk as you can see from the pull requests, I have been busy adding all of the other attributes.

Any chance you could give me a hand on enumerating and exposing the settings for the switch settings / icons (0x223 - 0x225) - these are octet strings that are formed by 3 different parameters as can be seen here:

[Switch Name / Icon](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Aqara-S1-Smart-Scene-Panel-Protocol#set-a-switch-text-and-icon-attributes-0x0223-0x0224-and-0x0225)

**Comment by danieledwardgeorgehitchcock** [comment]
yes, it does - the difficulty lies in the way that the octet string is created, and how this would be constructed using expose.

As it is a combination of the icon, and the text, how, could I capture these two, and do the conversion?

**Comment by Koenkk** [comment]
You can use the [composite expose](https://github.com/Koenkk/zigbee-herdsman-converters/blob/061f0d3f87d08843604bd860e23093037b558561/lib/exposes.js#L529) where the `icon` would be a number feature and the text a text feature`.

The `value` in toZigbee will then be e.g. `{"icon": 2, "text": "my text"}`

**Comment by danieledwardgeorgehitchcock** [comment]
Hi @Koenkk - I am close, but still far away with the composite.

So far, I have:

toZigbee (extract):
```
           } else if (key === 'switch_1_text_icon') {
                const lookup = {'1': 1, '2': 2, '3': 3, '4': 4, '5': 5, '6': 6, '7': 7, '8': 8, '9': 9, '10': 10, '11': 11};
                if (value.hasOwnProperty('icon')) {
                   payload = lookup[value.icon];
                }
                if (value.hasOwnProperty('text')) {
                   payload += value.text;
                }
                await entity.write('aqaraOpple', {0x0223: {value: payload, type: 0x41}}, {manufacturerCode: 0x115f});
                return {state: {switch_1_text_icon: payload}};
```

device (extract):
```
        exposes.composite('switch_1_text_icon', 'switch_1_text_icon')
            .withDescription('Switch 1 text and icon')
            .withFeature(exposes.enum('icon', ea.STATE_SET, ['1','2','3','4','5','6','7','8','9','10','11'])
                .withDescription('Icon'))
            .withFeature(exposes.text('text', ea.STATE_SET)
                .withDescription('Text')),
```

The difficulty I am facing is that while the icon number isn't added to the text, it also doesn't seem to be selected when publishing the above payload...

I am sure it is something dead simple, and silly that I am doing wrong... This is quite a steep learning curve for me

**Comment by Koenkk** [comment]
What do you mean it's not added to the payload? Does it work correctly with: https://github.com/Koenkk/zigbee-herdsman-converters/issues/2520#issuecomment-830149129 ?

**Comment by danieledwardgeorgehitchcock** [comment]
Yes it works if sent that way, but if I use an icon value of ‘4’ and a text value of ‘test’ neither of which are pre-formed hex, I.E. a payload of ‘4test’ the device only seems to accept the text value not the icon?

**Comment by Koenkk** [comment]
Can you try with:

```js
} else if (key === 'switch_1_text_icon') {
    const lookup = {'1': 1, '2': 2, '3': 3, '4': 4, '5': 5, '6': 6, '7': 7, '8': 8, '9': 9, '10': 10, '11': 11};
    let payload = [];
    if (value.hasOwnProperty('icon')) {
        payload.push(lookup[value.icon]);
    } else {
        payload.push(1);
    }
    if (value.hasOwnProperty('text')) {
        payload.push(...value.text.split('').map(c => c.charCodeAt(0)));
    } else {
        payload.push(...''.text.split('').map(c => c.charCodeAt(0)));
    }
    await entity.write('aqaraOpple', {0x0223: {value: payload, type: 0x41}}, {manufacturerCode: 0x115f});
    return {state: {switch_1_text_icon: payload}};
}
```

**Comment by danieledwardgeorgehitchcock** [comment]
Thats got it, thanks!

**Comment by danieledwardgeorgehitchcock** [comment]
Next few questions from today's effort:

When I add entries in configure for onOff reporting for endpoints 2 and 3, I get the following error:

`Zigbee2MQTT:info  2021-05-05 16:11:33: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure_reporting', payload '{"data":{},"error":"ConfigureReporting 0x04cf8cdf3c88d48a/2 genOnOff([{\"attribute\":\"onOff\",\"minimumReportInterval\":\"0\",\"maximumReportInterval\":3600,\"reportableChange\":0}], {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Status 'SOFTWARE_FAILURE')","status":"error","transaction":"n5l13-25"}'`

I am also trying to set up my fromZigbee entries now for this device. Here is what I have so far:

```
const fzLocal = {
    ZNCJMB14LM: {
        cluster: 'aqaraOpple',
        type: ['attributeReport', 'readResponse'],
        convert: async (model, msg, publish, options, meta) => {
           const result = {};
           if (msg.data.hasOwnProperty('533')) {
              const lookup = {0: 'classic', 1: 'concise'};
              result.theme = lookup[msg.data['533']];
           } else if (msg.data.hasOwnProperty('532')) {
              const lookup = {0: 'none', 1: 'classic', 2: 'analog clock'};
              result.screen_saver_style = lookup[msg.data['532']];
           } else if (msg.data.hasOwnProperty('531')) {
              result.standby_enabled = msg.data['531'] & 1 ? true : false;
           } else if (msg.data.hasOwnProperty('530')) {
              const lookup = {0: 'mute', 1: 'low', 2: 'medium', 3: 'high'};
              result.beep_volume = lookup[msg.data['530']];
           } else if (msg.data.hasOwnProperty['529']) {
              result.lcd_brightness = msg.data['529'];
           } else if (msg.data.hasOwnProperty['555']) {
              const lookup = {0: 'none', 1: '1', 2: '2', 3: '1 and 2', 4: '3', 5: '1 and 3', 6: '2 and 3', 7: 'all'};
              result.available_switches = lookup[msg.data['555']];
           }
           return result;
        },
    },
};
```
I can see the attributes coming in for the device however, the state doesn't seem to be updating?

```
2MQTT:debug 2021-05-05 16:19:20: Received Zigbee message from '0x04cf8cdf3c88d48a', type 'attributeReport', cluster 'aqaraOpple', data '{"529":95}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-05 16:19:21: Received Zigbee message from '0x04cf8cdf3c88d48a', type 'attributeReport', cluster 'aqaraOpple', data '{"529":90}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-05 16:19:21: Received Zigbee message from '0x04cf8cdf3c88d48a', type 'attributeReport', cluster 'aqaraOpple', data '{"529":85}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-05 16:19:22: Received Zigbee message from '0x04cf8cdf3c88d48a', type 'attributeReport', cluster 'aqaraOpple', data '{"529":80}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-05 16:19:22: Received Zigbee message from '0x04cf8cdf3c88d48a', type 'attributeReport', cluster 'aqaraOpple', data '{"529":85}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-05 16:19:23: Received Zigbee message from '0x04cf8cdf3c88d48a', type 'attributeReport', cluster 'aqaraOpple', data '{"529":90}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-05 16:19:23: Received Zigbee message from '0x04cf8cdf3c88d48a', type 'attributeReport', cluster 'aqaraOpple', data '{"529":85}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-05 16:19:24: Received Zigbee message from '0x04cf8cdf3c88d48a', type 'attributeReport', cluster 'aqaraOpple', data '{"529":80}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-05 16:19:24: Received Zigbee message from '0x04cf8cdf3c88d48a', type 'attributeReport', cluster 'aqaraOpple', data '{"529":75}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-05 16:19:25: Received Zigbee message from '0x04cf8cdf3c88d48a', type 'attributeReport', cluster 'aqaraOpple', data '{"529":70}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-05 16:19:25: Received Zigbee message from '0x04cf8cdf3c88d48a', type 'attributeReport', cluster 'aqaraOpple', data '{"529":65}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-05 16:19:26: Received Zigbee message from '0x04cf8cdf3c88d48a', type 'attributeReport', cluster 'aqaraOpple', data '{"529":60}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-05 16:19:26: Received Zigbee message from '0x04cf8cdf3c88d48a', type 'attributeReport', cluster 'aqaraOpple', data '{"529":55}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-05 16:19:27: Received Zigbee message from '0x04cf8cdf3c88d48a', type 'attributeReport', cluster 'aqaraOpple', data '{"529":50}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-05 16:19:29: Received Zigbee message from '0x04cf8cdf3c88d48a', type 'attributeReport', cluster 'aqaraOpple', data '{"529":55}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-05 16:19:30: Received Zigbee message from '0x04cf8cdf3c88d48a', type 'attributeReport', cluster 'aqaraOpple', data '{"529":60}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-05 16:19:30: Received Zigbee message from '0x04cf8cdf3c88d48a', type 'attributeReport', cluster 'aqaraOpple', data '{"529":65}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-05 16:19:31: Received Zigbee message from '0x04cf8cdf3c88d48a', type 'attributeReport', cluster 'aqaraOpple', data '{"529":71}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-05 16:19:32: Received Zigbee message from '0x04cf8cdf3c88d48a', type 'attributeReport', cluster 'aqaraOpple', data '{"529":76}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-05 16:19:32: Received Zigbee message from '0x04cf8cdf3c88d48a', type 'attributeReport', cluster 'aqaraOpple', data '{"529":81}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-05 16:19:33: Received Zigbee message from '0x04cf8cdf3c88d48a', type 'attributeReport', cluster 'aqaraOpple', data '{"529":86}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-05 16:19:33: Received Zigbee message from '0x04cf8cdf3c88d48a', type 'attributeReport', cluster 'aqaraOpple', data '{"529":91}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-05 16:19:34: Received Zigbee message from '0x04cf8cdf3c88d48a', type 'attributeReport', cluster 'aqaraOpple', data '{"529":96}' from endpoint 1 with groupID 0
```

The from the above, I would expect the state for lcd_brightness to be updated as these messages are reported but I am getting nothing :-(

**Comment by Koenkk** [comment]
- `SOFTWARE_FAILURE` I've seen this more often, I have no clue why this happens. Maybe you can try sleeping between setting up the reporting. To the top of the file add `const utils = require('zigbee-herdsman-converters/lib/utils')` and to sleep use `await utils.sleep(1000)` (1 seconds sleep)
- I think `msg.data.hasOwnProperty['529']` should be `msg.data.hasOwnProperty('529')` or even better `'529' in msg.data`

**Comment by L3H0** [comment]
@danieledwardgeorgehitchcock did you manage to get proper work with switch 2 and 3? From z2m www panel they are working good but not from physical panel. I have another question, it is possible to change/set time on panel, and from what sensors the panel show the temp, humidity etc?

**Comment by danieledwardgeorgehitchcock** [comment]
I have just received my Aqara hub to begin doing some sniffing on the joining procedure between the device and the hub to see what is going on with switches 2 and 3. As for the time setting, this appeared to 'just work' when I joined the device to my network - I don't think any manual intervention was necessary. Finally, for pairing sensors, etc, there is a good documentation for the way that this works in the Deconz link in my original post but, it is a bit beyond my technical ability so, I haven't tried implementing that to-date.

**Comment by danieledwardgeorgehitchcock** [comment]
> @danieledwardgeorgehitchcock did you manage to get proper work with switch 2 and 3? From z2m www panel they are working good but not from physical panel. I have another question, it is possible to change/set time on panel, and from what sensors the panel show the temp, humidity etc?

I have been working a bit more on this recently and have found the following:

- Physical actions from endpoints 2 and 3 (i.e. switch 2 and 3) are not reported by the device
- The time setting is automatically synchronised with Zigbee2MQTT - it takes a little while, but I can confirm that the device displays the incorrect time for ~5 mins then it will just flick over to the correct time
- The temperature / humidity on the main screen is taken from the internal sensor in the device however, there is the facility of adding an external Aqara device and bind it to the S1. This isn't something that I have added to this device handler as the logic is quite complex and out of my knowledge area

**Comment by hongkongkiwi** [comment]
There is another version of this device which has voice control and as well as being a scene controller can also control 3 relays (like the 3 button switches).

I was wondering if any work has been done on the voice control version of this? I am thinking to purchase it, but I am not sure whether the voice control can be changed or used in english (or else disabled).

**Comment by goriasha** [comment]
"Physical actions from endpoints 2 and 3 (i.e. switch 2 and 3) are not reported by the device"
What does that mean? There is no way to fix it? Otherwise It works properly with Aqara App.
