### ISSUE TITLE
Error during discovery and sensor creation - ID LOCK 150

### ISSUE THREAD

**Issue by TheStigh** [Koenkk/zigbee-herdsman-converters#2533]
Hi @Koenkk  

Yesterday all tests was OK the local external converter, even last changes made by you. After you accepted the PR, I today updated the Edge version. Now `doorState` ( `fz.Lock` ) fails creating sensor (related to [#7249](https://github.com/Koenkk/zigbee2mqtt/discussions/7249) you did today?) during pairing without using the local external converter.

[Here are the full pairing log](https://pastebin.com/sJQLbG6n)

EDIT:
Tried another pair (again), this time without any error in the log - but - still no sensor for `doorState`

[Here are the new full pairing log](https://pastebin.com/1F7FXVxL)

**Comment by Koenkk** [comment]
Change has been reverted now: https://github.com/Koenkk/zigbee2mqtt/commit/e9a5ec1a58dd4fbfc4fbe9383e504c0511c29cbd , assuming this can be closed.
