### ISSUE TITLE
Eco-Dim.07 removed by mistake with split of devices.js?

### ISSUE THREAD

**Issue by heinzgert** [Koenkk/zigbee-herdsman-converters#2538]
Just recognized that Eco-Dim.07 has vanished from the list of supported devices.
To me it seems this happened by mistake with the split of devices. js into different files per vendor.
Can you please check? 

Following code from the former devices.js doesn't appear in the new ecodim.js as I would expect:
 // EcoDim
    {
        zigbeeModel: ['Dimmer-Switch-ZB3.0'],
        model: 'Eco-Dim.07',
        vendor: 'EcoDim',
        description: 'Zigbee & Z-wave dimmer ',
        extend: preset.light_onoff_brightness(),
        meta: {configureKey: 1},
        whiteLabel: [{vendor: 'Iolloi', model: 'ID-EU20FW09'}],
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'genLevelCtrl']);
            await reporting.onOff(endpoint);
            await reporting.brightness(endpoint);
        },
    },

**Comment by Koenkk** [comment]
Woops, something went wrong during the split, added it back.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by heinzgert** [comment]
Great, Thanks!
