### ISSUE TITLE
 Yotraya smart plug.

### ISSUE THREAD

**Issue by stephenrjohnson** [Koenkk/zigbee-herdsman-converters#2542]
I purchased a Yotraya smart plug from https://www.amazon.co.uk/YOTRAYA-Compatible-SmartThings-Lightify-Required/dp/B08S7QSMNK . I'm trying to follow the https://www.zigbee2mqtt.io/how_tos/how_to_support_new_tuya_devices.html page but I've just wondering how I get the modelID and manufacturerName for the fingerprint.
The debug messages 
`
zigbee2mqtt     | Zigbee2MQTT:error 2021-05-02 16:43:51: Failed to interview '0x00124b001f945538', device has not successfully been paired
zigbee2mqtt     | Zigbee2MQTT:info  2021-05-02 16:43:51: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x00124b001f945538","ieee_address":"0x00124b001f945538","status":"failed"},"type":"device_interview"}'
zigbee2mqtt     | Zigbee2MQTT:info  2021-05-02 16:43:51: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_failed","meta":{"friendly_name":"0x00124b001f945538"},"type":"pairing"}'
zigbee2mqtt     | Zigbee2MQTT:debug 2021-05-02 16:44:13: Received Zigbee message from '0x00124b001f945538', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0
zigbee2mqtt     | Zigbee2MQTT:warn  2021-05-02 16:44:13: Received message from unsupported device with Zigbee model 'undefined' and manufacturer name 'undefined'
zigbee2mqtt     | Zigbee2MQTT:warn  2021-05-02 16:44:13: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
zigbee2mqtt     | Zigbee2MQTT:debug 2021-05-02 16:44:13: Received Zigbee message from '0x00124b001f945538', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0
zigbee2mqtt     | Zigbee2MQTT:debug 2021-05-02 16:44:13: Received Zigbee message from '0x00124b001f945538', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0
zigbee2mqtt     | Zigbee2MQTT:debug 2021-05-02 16:44:13: Received Zigbee message from '0x00124b001f945538', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0
zigbee2mqtt     | Zigbee2MQTT:debug 2021-05-02 16:44:13: Received Zigbee message from '0x00124b001f945538', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0
zigbee2mqtt     | Zigbee2MQTT:warn  2021-05-02 16:44:13: Received message from unsupported device with Zigbee model 'undefined' and manufacturer name 'undefined'
zigbee2mqtt     | Zigbee2MQTT:warn  2021-05-02 16:44:13: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
zigbee2mqtt     | Zigbee2MQTT:warn  2021-05-02 16:44:13: Received message from unsupported device with Zigbee model 'undefined' and manufacturer name 'undefined'
zigbee2mqtt     | Zigbee2MQTT:warn  2021-05-02 16:44:13: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
 `
The database entry
`
The db entry is {"id":3,"type":"Router","ieeeAddr":"0x00124b001f945538","nwkAddr":25636,"manufId":0,"epList":[1],"endpoints":{"1":{"epId":1,"inClusterList":[],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":1}}},"binds":[],"configuredReportings":[],"meta":{}}},"interviewCompleted":false,"meta":{},"lastSeen":1619970225108
`
Can I interrogate the device for this? as it doesn’t appear in the debug messages

**Comment by stephenrjohnson** [comment]
After moving to ZHA I managed to get the following info 


  "manufacturer": "eWeLink",
  "model": "SA-003-Zigbee",

**Comment by Koenkk** [comment]
Please try pairing it again on Zigbee2MQTT 1.18.3, it contains some improvements related to this.

**Comment by stephenrjohnson** [comment]
Sure that's working now
