### ISSUE TITLE
Add support for Tuya Smart Zigbee Metering Plug 16A Eu 

### ISSUE THREAD

**Issue by oetelaar24** [Koenkk/zigbee-herdsman-converters#2557]
Hi,

I've recently bought a couple of these at ali: https://nl.aliexpress.com/item/1005002344798281.html

Apparently they are quite new, so support is not yet added. It pairs successfully and reports itself as:
`Zigbee model 'TS011F' and manufacturer name '_TZ3000_cphmq0q7'`

I'm not really sure how to go about adding support for this device, as I do not have a Tuya gateway to be able to sniff the traffic. I'm also kinda hoping it's not needed and we can just try and "copy" the converter-settings from a known device like the TS0121_plug or TS0601_din. 

I've tried using the known devices definition in an external converters file (TZ3000_cphmq0q7.js), however, only the TS0121_plug worked a little bit in that I was able to control the switch, but it also errors and turns it off:
`Zigbee2MQTT:error 2021-05-08 12:24:49: Failed to call 'OnEvent' 'onZigbeeEvent' (ReferenceError: globalStore is not defined
,    at Object.onEvent (/app/lib/util/externally-loaded.js:36:20)
,    at OnEvent.callOnEvent (/app/lib/extension/onEvent.js:33:39)
,    at OnEvent.onZigbeeEvent (/app/lib/extension/onEvent.js:17:18)
,    at Controller.callExtensionMethod (/app/lib/controller.js:384:44))
`
Can anyone help me with the best next step to take?

Kind regards,
-Bart

**Comment by oetelaar24** [comment]
Okay, I've given it another shot. But still not getting much further...

Tried with this external converter to get tuya data dumps:

`const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    // Since a lot of Tuya devices use the same modelID, but use different data points
    // it's usually necessary to provide a fingerprint instead of a zigbeeModel
    fingerprint: [
        {
            // The model ID from: Device with modelID 'TS0601' is not supported
            // You may need to add \u0000 at the end of the name in some cases
            modelID: 'TS011F',
            // The manufacturer name from: Device with modelID 'TS0601' is not supported.
            manufacturerName: '_TZ3000_cphmq0q7'
        },
    ],
    model: 'TS011F',
    vendor: 'TuYa',
    description: 'Zigbee smart metering plug 16A EU Zigbee',
    supports: 'metering, on_off',
    fromZigbee: [
        //fz.ignore_basic_report, // Add this if you are getting no converter for 'genBasic'
        fz.tuya_data_point_dump, // This is a debug converter, it will be described in the next part
    ],
    toZigbee: [
        tz.tuya_data_point_test, // Another debug converter
    ],
    //onEvent: tuya.setTime, // Add this if you are getting no converter for 'commandSetTimeRequest'
    meta: {
        configureKey: 1,
    },
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await bind(endpoint, coordinatorEndpoint, ['genBasic']);
    },
    exposes: [
        e.switch(), e.power(), e.current(), e.voltage().withAccess(ea.STATE),
            e.energy(), exposes.enum('power_outage_memory', ea.STATE_SET, ['on', 'off', 'restore'])
                .withDescription('Recover state after power outage')
    ],
};

module.exports = definition;`

however, no file is written, not when i push the button on the device, replug, send commands... nothing... only errors in the z2m logs that no converter is available...

**Comment by oetelaar24** [comment]
Okay, fiddled a little bit more with it, added the two tuya debug converters

```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    fingerprint: [{modelID: 'TS011F', manufacturerName: '_TZ3000_cphmq0q7'}],
    model: 'TS011F',
    vendor: 'TuYa',
    description: 'Zigbee smart metering plug 16A EU Zigbee',
    fromZigbee: [tz.on_off, fz.tuya_data_point_dump],
    toZigbee: [tz.on_off, tz.tuya_data_point_test],
    exposes: [e.switch()],
};

module.exports = definition;

```

However it doesn't create the `data/tuya.dump.txt` file. I don't see it mentioned that debug logging needs to be turned on?

Weird sideeffect, the need to send every command twice and the error of ` error No converter available for 'state' (ON)` is no longer occuring...

**Comment by Koenkk** [comment]
This file will be created next to the `configuration.yaml`, but only if the device sends reports.

**Comment by oetelaar24** [comment]
Well, no file is created. I left a charger in the plug overnight, charging a tablet. Nothing...
I'm starting to think this plug might not even do powermetering... I've contacted the seller that dispite his title that it supports zigbee2mqtt, it clearly does not. Other buyers also state that at first it was a TS0121_plug type, now it is a TS011F... The seller responded by removing the claim of zigbee2mqtt support... just great.
After that I asked what to do, then he said refund... So I'll just send them back and be done with it....

**Comment by oetelaar24** [comment]
Awesome, thanks to #2571 I've been able to get this working for the most part! 💯 
However, a few notes:

When using the globalStore in the external converters file, an extra inclusion needs to be made:
```js
const globalStore = require('zigbee-herdsman-converters/lib/store');
```

There also seems to be something amiss with the solution, so it's not perfect yet. I do still get some errors when the device is configured, reporting and controlling does seem to work well though. The error is:
```
Failed to configure '0x847127fffe8d9579', attempt 3 (TypeError: Cannot read property 'configureKey' of undefined
,    at Configure.configure (/app/lib/extension/configure.js:138:69))
```

If you want to add this via an external converters file, like I did, then the full code (which still has some issues) is:
```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const globalStore = require('zigbee-herdsman-converters/lib/store');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
        fingerprint: [{modelID: 'TS011F', manufacturerName: '_TZ3000_cphmq0q7'},],
        model: 'TS011F',
        description: 'Smart EU Plug',
        vendor: 'TuYa',
        fromZigbee: [fz.on_off, fz.electrical_measurement, fz.metering, fz.ignore_basic_report, fz.tuya_switch_power_outage_memory],
        toZigbee: [tz.on_off, tz.tuya_switch_power_outage_memory],
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'haElectricalMeasurement']);
            endpoint.saveClusterAttributeKeyValue('seMetering', {divisor: 100, multiplier: 1});
            endpoint.saveClusterAttributeKeyValue('haElectricalMeasurement', {
                acVoltageMultiplier: 1, acVoltageDivisor: 1, acCurrentMultiplier: 1, acCurrentDivisor: 1000, acPowerMultiplier: 1,
                acPowerDivisor: 1,
            });
        },
        // This device doesn't support reporting correctly.
        // https://github.com/Koenkk/zigbee-herdsman-converters/pull/1270
        exposes: [e.switch(), e.power(), e.current(), e.voltage().withAccess(ea.STATE),
            e.energy(), exposes.enum('power_outage_memory', ea.STATE_SET, ['on', 'off', 'restore'])
                .withDescription('Recover state after power outage')],
        onEvent: (type, data, device, options) => {
            const endpoint = device.getEndpoint(1);

            if (type === 'stop') {
                clearInterval(globalStore.getValue(device, 'interval'));
                globalStore.clearValue(device, 'interval');
            } else if (!globalStore.hasValue(device, 'interval')) {
                const seconds = options && options.measurement_poll_interval ? options.measurement_poll_interval : 60;
                const interval = setInterval(async () => {
                    try {
                        await endpoint.read('haElectricalMeasurement', ['rmsVoltage', 'rmsCurrent', 'activePower']);
                        await endpoint.read('seMetering', ['currentSummDelivered']);
                    } catch (error) {/* Do nothing*/}
                }, seconds*1000);
                globalStore.putValue(device, 'interval', interval);
            }
        }
};

module.exports = definition;
```
Offcourse, credit to yratanov for making this for the most part :)

**Comment by Koenkk** [comment]
Let's continue further in https://github.com/Koenkk/zigbee-herdsman-converters/pull/2571
