### ISSUE TITLE
New interesting sensor 

### ISSUE THREAD

**Issue by wantsoftat** [Koenkk/zigbee-herdsman-converters#2561]
[https://github.com/wantsoftat/my_pub/blob/main/sensor.png](url)

Zigbee model 'TS0222' and manufacturer name '_TYZB01_kvwjujy9'

debug Received Zigbee message from '0x5c0272fffe0a4792'	 type 'attributeReport'	 cluster 'genPowerCfg'	 data '{"batteryPercentageRemaining":200}' from endpoint 1 with groupID 0
debug Received Zigbee message from '0x5c0272fffe0a4792'	 type 'attributeReport'	 cluster 'msIlluminanceMeasurement'	 data '{"measuredValue":22254}' from endpoint 1 with groupID 0
debug Received Zigbee message from '0x5c0272fffe0a4792'	 type 'attributeReport'	 cluster 'msRelativeHumidity'	 data '{"measuredValue":4132}' from endpoint 2 with groupID 0
debug Received Zigbee message from '0x5c0272fffe0a4792'	 type 'attributeReport'	 cluster 'msTemperatureMeasurement'	 data '{"measuredValue":2741}' from endpoint 2 with groupID 0

**Comment by DavidFFerreira** [comment]
I have this device and no clue how to add to Zigbee2Mqtt

**Comment by wantsoftat** [comment]
> 
> 
> I have this device and no clue how to add to Zigbee2Mqtt

We need to wait for the developers to add or create the converter ourselves.

**Comment by DavidFFerreira** [comment]
:(

**Comment by WildeRNS** [comment]
Also have same device. I make converter and everything work well.

**Comment by darkdragondraco** [comment]
> Also have same device. I make converter and everything work well.

Can you please share your converter?

**Comment by WildeRNS** [comment]
> > Also have same device. I make converter and everything work well.
> 
> Can you please share your converter?

Sensor is added to latest dev.
Here is my converter:
https://pastebin.com/gTaGWUii
