### ISSUE TITLE
Same  product but different zigbee model.

### ISSUE THREAD

**Issue by darkiller22003** [Koenkk/zigbee-herdsman-converters#2579]
<img width="703" alt="Picure TS004F" src="https://user-images.githubusercontent.com/61015530/118371473-61518900-b5df-11eb-8a72-6ddf980b6a4a.png">

**Comment by darkiller22003** [comment]
Hi Koenkk,

This is the first time I encountered any issue with Zigbee2Mqtt, I would like to thank you for your wonderful work.

I have this issue with product TS0044.
I bought a similar or the same product but Zigbee model is TS004F.
I have check Model No : ESW-0ZAA-EU

I have tried to use your documentation for unsupported devices but failed.
so I try to copy the JS for TS0044 and change it to TS004F.

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
        zigbeeModel: ['TS004F'],
        model: 'TS004F',
        vendor: 'TuYa',
        description: 'Wireless switch with 4 buttons',
        whiteLabel: [{vendor: 'Lonsonho', model: 'TS004F'}, {vendor: 'Haozee', model: 'ESW-OZAA-EU'}],
        fromZigbee: [fz.tuya_on_off_action, fz.battery],
        exposes: [e.battery(), e.action(['1_single', '1_double', '1_hold', '2_single', '2_double', '2_hold',
            '3_single', '3_double', '3_hold', '4_single', '4_double', '4_hold'])],
        toZigbee: [],
    };
	
module.exports = definition;

I created a file (TS004F.js) beside Configuration.yaml in Share/Zigbee2Mqtt.
and change the configuration in home assistant zigbee2mqtt add-on.

external_converters:
  - TS004F.js
advanced:
  log_level: debug
  pan_id: 6755

and restarted it .


**Here is my Error from the log**

> zigbee2mqtt@1.18.1 start /app
> node index.js

(node:436) UnhandledPromiseRejectionWarning: internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'zigbee-herdsman-converters/lib/extend'
Require stack:
- /app/lib/util/utils.js
- /app/lib/util/settings.js
- /app/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /app/lib/util/externally-loaded.js:5:16
    at Script.runInContext (vm.js:143:18)
    at Script.runInNewContext (vm.js:148:17)
    at Object.runInNewContext (vm.js:303:38)
    at loadModuleFromText (/app/lib/util/utils.js:156:8)
    at loadModuleFromFile (/app/lib/util/utils.js:162:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:436) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:436) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[00:16:32] INFO: Handing over control to Zigbee2mqtt Core ...

**Comment by darkiller22003** [comment]
Please help

**Comment by Koenkk** [comment]
> zigbee2mqtt@1.18.1 start /app


Make sure you are on the latest zigbee2mqtt version (1.18.3). That is the reason for your error. If on hassio you may need to switch to the new repo by uninstalling the old addon: https://github.com/zigbee2mqtt/hassio-zigbee2mqtt#installation

**Comment by wizu** [comment]
https://community.home-assistant.io/t/zigbee2mqtt-tuya-4-button-scene-switch-ts0044/274735/15

**Comment by darkiller22003** [comment]
> > zigbee2mqtt@1.18.1 start /app
> 
> Make sure you are on the latest zigbee2mqtt version (1.18.3). That is the reason for your error. If on hassio you may need to switch to the new repo by uninstalling the old addon: https://github.com/zigbee2mqtt/hassio-zigbee2mqtt#installation


thanks for the help I got external converter working . But my Js configuration, will trigger mine xiaomi wall switch , QBKG23LM

**Comment by darkiller22003** [comment]
> https://community.home-assistant.io/t/zigbee2mqtt-tuya-4-button-scene-switch-ts0044/274735/15

Will your ts004F trigger any lights switch using the left side top and bottom button?

**Comment by daNick73** [comment]
@darkiller22003 did you get this to work? I have two TS04F and want to use them in iObroker, but I miserably fail ....

**Comment by wizu** [comment]
@darkiller22003 yes, it's workig well with converter from link - no lights and anything strange. It work's as it's supposed to.
If you have already paired button, remove it with "Force remove" checked. Then add converter, reload z2m and then pair button again.
