### ISSUE TITLE
Hello author, before zigbee2mqtt

### ISSUE THREAD

**Issue by yhwl8888** [Koenkk/zigbee-herdsman-converters#2581]
Hello author, before zigbee2mqtt can modify the devices.js file. The new version is not available. I have a curtain that has closed before but can be successfully connected to zigbee2mqtt by modifying the file. After the update, it cannot continue to modify the file form to join. Seek help to solve it.
{
    zigbeeModel: ['FTB56-ZT218AK1.0'],
    model: 'ZNCLDJ12LM',
    vendor: 'Xiaomi',
    description: 'KADRILJ roller blind',
    supports: 'open, close, stop, position',
    fromZigbee: [fz.cover_position_tilt, fz.generic_battery],
    toZigbee: [tz.cover_state, tz.cover_position_tilt],
    meta: {configureKey: 2},
    ota: ota.tradfri,
    configure: async (device, coordinatorEndpoint) => {
        const endpoint = device.getEndpoint(1);
        await bind(endpoint, coordinatorEndpoint, ['genPowerCfg', 'closuresWindowCovering']);
        await configureReporting.batteryPercentageRemaining(endpoint);
        await configureReporting.currentPositionLiftPercentage(endpoint);
};

thankes

**Comment by Koenkk** [comment]
Can you provide a link to this device?
