### ISSUE TITLE
E1743 reports NULL actions when clicking buttons

### ISSUE THREAD

**Issue by EPMatt** [Koenkk/zigbee-herdsman-converters#2618]
### Bug information

Device: IKEA E1743
Firmware: 2.2.010 (latest)
Zigbee2MQTT version: 1.18.3

### Description

Interacting with the IKEA E1743 On/Off switch produces an additional `null` action after the empty `""`  action. This accidentally broke all my smart home automations which had this remote as a trigger.

I don't know when this issue started to occur, but a few versions ago (~1.17) I wasn't experiencing this problem.
I'm reporting here since I guess the issue is related to this package.

### Debug logs

```
Debug: Received Zigbee message from 'my_device_id', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 201
Info: MQTT publish: topic 'zigbee2mqtt/my_device_id', payload '{"action":"on","battery":100,"click":"on","linkquality":114,"update":{"state":"idle"},"update_available":false}'
Info: MQTT publish: topic 'zigbee2mqtt/my_device_id', payload '{"action":"","battery":100,"linkquality":114,"update":{"state":"idle"},"update_available":false}'
Info: MQTT publish: topic 'zigbee2mqtt/my_device_id', payload '{"action":null,"battery":100,"click":"","linkquality":114,"update":{"state":"idle"},"update_available":false}'
Info: MQTT publish: topic 'zigbee2mqtt/my_device_id/action', payload 'on'
Info: MQTT publish: topic 'zigbee2mqtt/my_device_id/click', payload 'on'
```

Thank you for maintaining and developing such an amazing project! 🚀

**Comment by Koenkk** [comment]
This is due to HA now requiring all attributes on publish, see https://github.com/Koenkk/zigbee2mqtt/pull/7032 , you should update your automations.

**Comment by EPMatt** [comment]
Hi,

thank you for the quick reply.
I've just taken a look at the PR, didn't spot it before. I'll update my automations and blueprints accordingly to the implemented change.
Sorry for the bad issue I reported. Thanks again!
