### ISSUE TITLE
NEW device: Thermometer with illuminace and display NEO

### ISSUE THREAD

**Issue by WildeRNS** [Koenkk/zigbee-herdsman-converters#2622]
https://aliexpress.com/item/1005002434961203.html

illuminace and battery received ok, but no temperature and humidity

converter used:
`const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const devices = [
      {
        fingerprint: [
            {type: 'EndDevice', manufacturerID: 4098},
            {manufacturerName: '_TZ2000_a476raq2'},
        ],
        zigbeeModel: ['TS0201', 'SNTZ003'],
        model: 'TS0201',
        vendor: 'NEO',
        description: 'Temperature & humidity sensor with display',
        fromZigbee: [fz.ignore_basic_report, fz.tuya_data_point_dump],
        toZigbee: [],
        exposes: [],
        meta: {
          configureKey: 1,
        },
        configure: async (device, coordinatorEndpoint, logger) => {
           const endpoint = device.getEndpoint(1);
           await reporting.bind(endpoint, coordinatorEndpoint, ['genBasic']);
        },
      },
];
module.exports = devices;`

log:
`uya_gw/bridge/response/permit_join', payload '{"data":{"time":254,"value":true},"status":"ok","transaction":"r0617-1"}'

Zigbee2MQTT:info  2021-05-25 08:51:03: Device 'Cabinet thermometer' joined

Zigbee2MQTT:info  2021-05-25 08:51:03: MQTT publish: topic 'z2m_tuya_gw/bridge/event', payload '{"data":{"friendly_name":"Cabinet thermometer","ieee_address":"0xb4e3f9fffe0c4b7c"},"type":"device_joined"}'

Zigbee2MQTT:info  2021-05-25 08:51:03: Starting interview of 'Cabinet thermometer'

Zigbee2MQTT:info  2021-05-25 08:51:03: MQTT publish: topic 'z2m_tuya_gw/bridge/event', payload '{"data":{"friendly_name":"Cabinet thermometer","ieee_address":"0xb4e3f9fffe0c4b7c","status":"started"},"type":"device_interview"}'

Zigbee2MQTT:info  2021-05-25 08:51:03: MQTT publish: topic 'z2m_tuya_gw/bridge/log', payload '{"message":{"friendly_name":"Cabinet thermometer"},"type":"device_connected"}'

Zigbee2MQTT:info  2021-05-25 08:51:03: MQTT publish: topic 'z2m_tuya_gw/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"Cabinet thermometer"},"type":"pairing"}'

Zigbee2MQTT:info  2021-05-25 08:51:03: MQTT publish: topic 'z2m_tuya_gw/Cabinet thermometer/availability', payload 'online'

Zigbee2MQTT:debug 2021-05-25 08:51:05: Received Zigbee message from 'Cabinet thermometer', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"61441":50}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:51:05: No converter available for 'TS0201' with cluster 'msIlluminanceMeasurement' and type 'attributeReport' and data '{"61441":50}'

Zigbee2MQTT:debug 2021-05-25 08:51:06: Received Zigbee message from 'Cabinet thermometer', type 'readResponse', cluster 'genBasic', data '{"modelId":"TS0201"}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:51:06: Received Zigbee message from 'Cabinet thermometer', type 'raw', cluster '57346', data '{"data":[8,108,10,10,208,41,40,0],"type":"Buffer"}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:51:06: No converter available for 'TS0201' with cluster '57346' and type 'raw' and data '{"data":[8,108,10,10,208,41,40,0],"type":"Buffer"}'

Zigbee2MQTT:debug 2021-05-25 08:51:06: Received Zigbee message from 'Cabinet thermometer', type 'readResponse', cluster 'genBasic', data '{"manufacturerName":"_TZ3000_qaaysllp"}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:51:06: Received Zigbee message from 'Cabinet thermometer', type 'readResponse', cluster 'genBasic', data '{"powerSource":3}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:51:07: Received Zigbee message from 'Cabinet thermometer', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:51:07: Received Zigbee message from 'Cabinet thermometer', type 'readResponse', cluster 'genBasic', data '{"appVersion":68}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:51:08: Received Zigbee message from 'Cabinet thermometer', type 'readResponse', cluster 'genBasic', data '{"stackVersion":0}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:51:08: Received Zigbee message from 'Cabinet thermometer', type 'readResponse', cluster 'genBasic', data '{"hwVersion":1}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:51:09: Received Zigbee message from 'Cabinet thermometer', type 'readResponse', cluster 'genBasic', data '{"dateCode":""}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:51:09: Received Zigbee message from 'Cabinet thermometer', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 1 with groupID 0

Zigbee2MQTT:info  2021-05-25 08:51:09: Successfully interviewed 'Cabinet thermometer', device has successfully been paired

Zigbee2MQTT:info  2021-05-25 08:51:09: Device 'Cabinet thermometer' is supported, identified as: NEO Temperature & humidity sensor with display (TS0201)

Zigbee2MQTT:info  2021-05-25 08:51:09: MQTT publish: topic 'z2m_tuya_gw/bridge/event', payload '{"data":{"definition":{"description":"Temperature & humidity sensor with display","exposes":[{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"icon":"https://i.ibb.co/ggYQ11s/IMG-20210522-160556.jpg","model":"TS0201","supports_ota":false,"vendor":"NEO"},"friendly_name":"Cabinet thermometer","ieee_address":"0xb4e3f9fffe0c4b7c","status":"successful","supported":true},"type":"device_interview"}'

Zigbee2MQTT:info  2021-05-25 08:51:09: Configuring 'Cabinet thermometer'

Zigbee2MQTT:info  2021-05-25 08:51:09: MQTT publish: topic 'z2m_tuya_gw/bridge/log', payload '{"message":"interview_successful","meta":{"description":"Temperature & humidity sensor with display","friendly_name":"Cabinet thermometer","model":"TS0201","supported":true,"vendor":"NEO"},"type":"pairing"}'

Zigbee2MQTT:info  2021-05-25 08:51:09: MQTT publish: topic 'homeassistant/sensor/0xb4e3f9fffe0c4b7c/linkquality/config', payload '{"availability":[{"topic":"z2m_tuya_gw/bridge/state"},{"topic":"z2m_tuya_gw/Cabinet thermometer/availability"}],"device":{"identifiers":["zigbee2mqtt_0xb4e3f9fffe0c4b7c"],"manufacturer":"NEO","model":"Temperature & humidity sensor with display (TS0201)","name":"Cabinet thermometer","sw_version":"Zigbee2MQTT 1.18.3-dev"},"icon":"mdi:signal","json_attributes_topic":"z2m_tuya_gw/Cabinet thermometer","name":"Cabinet thermometer linkquality","state_topic":"z2m_tuya_gw/Cabinet thermometer","unique_id":"0xb4e3f9fffe0c4b7c_linkquality_z2m_tuya_gw","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'

Zigbee2MQTT:debug 2021-05-25 08:51:09: Received MQTT message on 'homeassistant/sensor/0xb4e3f9fffe0c4b7c/linkquality/config' with data '{"availability":[{"topic":"z2m_tuya_gw/bridge/state"},{"topic":"z2m_tuya_gw/Cabinet thermometer/availability"}],"device":{"identifiers":["zigbee2mqtt_0xb4e3f9fffe0c4b7c"],"manufacturer":"NEO","model":"Temperature & humidity sensor with display (TS0201)","name":"Cabinet thermometer","sw_version":"Zigbee2MQTT 1.18.3-dev"},"icon":"mdi:signal","json_attributes_topic":"z2m_tuya_gw/Cabinet thermometer","name":"Cabinet thermometer linkquality","state_topic":"z2m_tuya_gw/Cabinet thermometer","unique_id":"0xb4e3f9fffe0c4b7c_linkquality_z2m_tuya_gw","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'

Zigbee2MQTT:info  2021-05-25 08:51:09: Successfully configured 'Cabinet thermometer'

Zigbee2MQTT:debug 2021-05-25 08:51:11: Received Zigbee message from 'Cabinet thermometer', type 'raw', cluster '57346', data '{"data":[8,109,10,11,208,41,10,0],"type":"Buffer"}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:51:11: No converter available for 'TS0201' with cluster '57346' and type 'raw' and data '{"data":[8,109,10,11,208,41,10,0],"type":"Buffer"}'

Zigbee2MQTT:debug 2021-05-25 08:51:13: Received Zigbee message from 'Cabinet thermometer', type 'raw', cluster '57346', data '{"data":[8,110,10,13,208,41,90,0],"type":"Buffer"}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:51:13: No converter available for 'TS0201' with cluster '57346' and type 'raw' and data '{"data":[8,110,10,13,208,41,90,0],"type":"Buffer"}'

Zigbee2MQTT:debug 2021-05-25 08:51:15: Received Zigbee message from 'Cabinet thermometer', type 'raw', cluster '57346', data '{"data":[8,111,10,14,208,41,20,0],"type":"Buffer"}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:51:15: No converter available for 'TS0201' with cluster '57346' and type 'raw' and data '{"data":[8,111,10,14,208,41,20,0],"type":"Buffer"}'

Zigbee2MQTT:debug 2021-05-25 08:51:17: Received Zigbee message from 'Cabinet thermometer', type 'raw', cluster '57346', data '{"data":[8,112,10,6,208,48,2],"type":"Buffer"}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:51:17: No converter available for 'TS0201' with cluster '57346' and type 'raw' and data '{"data":[8,112,10,6,208,48,2],"type":"Buffer"}'

Zigbee2MQTT:debug 2021-05-25 08:51:19: Received Zigbee message from 'Cabinet thermometer', type 'raw', cluster '57346', data '{"data":[8,113,10,15,208,48,2],"type":"Buffer"}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:51:19: No converter available for 'TS0201' with cluster '57346' and type 'raw' and data '{"data":[8,113,10,15,208,48,2],"type":"Buffer"}'

Zigbee2MQTT:debug 2021-05-25 08:51:21: Received Zigbee message from 'Cabinet thermometer', type 'raw', cluster '57346', data '{"data":[8,114,10,16,208,32,0],"type":"Buffer"}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:51:21: No converter available for 'TS0201' with cluster '57346' and type 'raw' and data '{"data":[8,114,10,16,208,32,0],"type":"Buffer"}'

Zigbee2MQTT:debug 2021-05-25 08:51:29: Received Zigbee message from 'Cabinet thermometer', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":32426}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:51:29: No converter available for 'TS0201' with cluster 'msIlluminanceMeasurement' and type 'attributeReport' and data '{"measuredValue":32426}'

Zigbee2MQTT:debug 2021-05-25 08:51:29: Received Zigbee message from 'Cabinet thermometer', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":32843}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:51:29: No converter available for 'TS0201' with cluster 'msIlluminanceMeasurement' and type 'attributeReport' and data '{"measuredValue":32843}'

Zigbee2MQTT:debug 2021-05-25 08:51:30: Received Zigbee message from 'Cabinet thermometer', type 'read', cluster 'genTime', data '["localTime"]' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:52:31: Saving state to file /app/data/state.json

Zigbee2MQTT:debug 2021-05-25 08:52:39: Received MQTT message on 'z2m_tuya_gw/bridge/request/permit_join' with data '{"device":null,"time":254,"transaction":"r0617-2","value":false}'

Zigbee2MQTT:info  2021-05-25 08:52:39: Zigbee: disabling joining new devices.

Zigbee2MQTT:info  2021-05-25 08:52:39: MQTT publish: topic 'z2m_tuya_gw/bridge/response/permit_join', payload '{"data":{"time":254,"value":false},"status":"ok","transaction":"r0617-2"}'

Zigbee2MQTT:debug 2021-05-25 08:53:00: Received Zigbee message from 'Cabinet thermometer', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":30462}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:53:00: No converter available for 'TS0201' with cluster 'msIlluminanceMeasurement' and type 'attributeReport' and data '{"measuredValue":30462}'

Zigbee2MQTT:debug 2021-05-25 08:53:08: Received Zigbee message from 'Cabinet thermometer', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":31393}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:53:08: No converter available for 'TS0201' with cluster 'msIlluminanceMeasurement' and type 'attributeReport' and data '{"measuredValue":31393}'

Zigbee2MQTT:debug 2021-05-25 08:53:16: Received Zigbee message from 'Cabinet thermometer', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":28746}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:53:16: No converter available for 'TS0201' with cluster 'msIlluminanceMeasurement' and type 'attributeReport' and data '{"measuredValue":28746}'

Zigbee2MQTT:debug 2021-05-25 08:53:24: Received Zigbee message from 'Cabinet thermometer', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":21819}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:53:24: No converter available for 'TS0201' with cluster 'msIlluminanceMeasurement' and type 'attributeReport' and data '{"measuredValue":21819}'

Zigbee2MQTT:debug 2021-05-25 08:53:40: Received Zigbee message from 'Cabinet thermometer', type 'raw', cluster '57346', data '{"data":[8,1,10,15,208,48,1],"type":"Buffer"}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:53:40: No converter available for 'TS0201' with cluster '57346' and type 'raw' and data '{"data":[8,1,10,15,208,48,1],"type":"Buffer"}'

Zigbee2MQTT:debug 2021-05-25 08:53:42: Received Zigbee message from 'Cabinet thermometer', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":30501}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:53:42: No converter available for 'TS0201' with cluster 'msIlluminanceMeasurement' and type 'attributeReport' and data '{"measuredValue":30501}'

Zigbee2MQTT:debug 2021-05-25 08:53:48: Received Zigbee message from 'Cabinet thermometer', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":31032}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:53:48: No converter available for 'TS0201' with cluster 'msIlluminanceMeasurement' and type 'attributeReport' and data '{"measuredValue":31032}'

Zigbee2MQTT:debug 2021-05-25 08:53:56: Received Zigbee message from 'Cabinet thermometer', type 'raw', cluster '57346', data '{"data":[8,5,10,15,208,48,2],"type":"Buffer"}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:53:56: No converter available for 'TS0201' with cluster '57346' and type 'raw' and data '{"data":[8,5,10,15,208,48,2],"type":"Buffer"}'

Zigbee2MQTT:debug 2021-05-25 08:53:58: Received Zigbee message from 'Cabinet thermometer', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":30299}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:53:58: No converter available for 'TS0201' with cluster 'msIlluminanceMeasurement' and type 'attributeReport' and data '{"measuredValue":30299}'

Zigbee2MQTT:debug 2021-05-25 08:54:06: Received Zigbee message from 'Cabinet thermometer', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":29610}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:54:06: No converter available for 'TS0201' with cluster 'msIlluminanceMeasurement' and type 'attributeReport' and data '{"measuredValue":29610}'

Zigbee2MQTT:debug 2021-05-25 08:54:12: Received Zigbee message from 'Cabinet thermometer', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":29290}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:54:12: No converter available for 'TS0201' with cluster 'msIlluminanceMeasurement' and type 'attributeReport' and data '{"measuredValue":29290}'

Zigbee2MQTT:debug 2021-05-25 08:54:28: Received Zigbee message from 'Cabinet thermometer', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":28894}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:54:28: No converter available for 'TS0201' with cluster 'msIlluminanceMeasurement' and type 'attributeReport' and data '{"measuredValue":28894}'

Zigbee2MQTT:debug 2021-05-25 08:54:36: Received Zigbee message from 'Cabinet thermometer', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":25212}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:54:36: No converter available for 'TS0201' with cluster 'msIlluminanceMeasurement' and type 'attributeReport' and data '{"measuredValue":25212}'

Zigbee2MQTT:debug 2021-05-25 08:55:33: Received Zigbee message from 'Cabinet thermometer', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":28983}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:55:33: No converter available for 'TS0201' with cluster 'msIlluminanceMeasurement' and type 'attributeReport' and data '{"measuredValue":28983}'

Zigbee2MQTT:debug 2021-05-25 08:55:41: Received Zigbee message from 'Cabinet thermometer', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":27753}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:55:41: No converter available for 'TS0201' with cluster 'msIlluminanceMeasurement' and type 'attributeReport' and data '{"measuredValue":27753}'

Zigbee2MQTT:debug 2021-05-25 08:55:49: Received Zigbee message from 'Cabinet thermometer', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":25683}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:55:49: No converter available for 'TS0201' with cluster 'msIlluminanceMeasurement' and type 'attributeReport' and data '{"measuredValue":25683}'

Zigbee2MQTT:debug 2021-05-25 08:55:57: Received Zigbee message from 'Cabinet thermometer', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":24956}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:55:57: No converter available for 'TS0201' with cluster 'msIlluminanceMeasurement' and type 'attributeReport' and data '{"measuredValue":24956}'

Zigbee2MQTT:debug 2021-05-25 08:56:13: Received Zigbee message from 'Cabinet thermometer', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":24049}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:56:13: No converter available for 'TS0201' with cluster 'msIlluminanceMeasurement' and type 'attributeReport' and data '{"measuredValue":24049}'

Zigbee2MQTT:debug 2021-05-25 08:56:38: Received Zigbee message from 'Cabinet thermometer', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":23033}' from endpoint 1 with groupID 0

Zigbee2MQTT:debug 2021-05-25 08:56:38: No converter available for 'TS0201' with cluster 'msIlluminanceMeasurement' and type 'attributeReport' and data '{"measuredValue":23033}'`

**Comment by Koenkk** [comment]
Device is already supported in the dev branch: https://github.com/Koenkk/zigbee-herdsman-converters/blob/4a7052e714405d2915b92b16c47fcc4de69fc5e3/devices/tuya.js#L371

(https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by WildeRNS** [comment]
I saw it, but no illumination and no any data for temperature and humidity. That's why I try to make converter and received only illumination.

**Comment by WildeRNS** [comment]
> I saw it, but no illumination and no any data for temperature and humidity. That's why I try to make converter and received only illumination.



> Device is already supported in the dev branch:
> 
> https://github.com/Koenkk/zigbee-herdsman-converters/blob/4a7052e714405d2915b92b16c47fcc4de69fc5e3/devices/tuya.js#L371
> 
> (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

I saw it, but no illumination and no any data for temperature and humidity. That's why I try to make converter and received only illumination.

**Comment by Koenkk** [comment]
Can you try updating the definition to:

```js
{
    fingerprint: [
        {type: 'EndDevice', manufacturerID: 4098, endpoints: [{ID: 1, inputClusters: [], outputClusters: []}]},
        {manufacturerName: '_TZ2000_a476raq2'},
    ],
    zigbeeModel: ['TS0201', 'SNTZ003'],
    model: 'TS0201',
    vendor: 'TuYa',
    description: 'Temperature & humidity sensor with display',
    fromZigbee: [fz.battery, fz.temperature, fz.humidity],
    toZigbee: [],
    exposes: [e.battery(), e.temperature(), e.humidity(), e.battery_voltage()],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['msTemperatureMeasurement']);
        await reporting.temperature(endpoint);
    },
},
```

Also make sure you are on the latest dev (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by WildeRNS** [comment]
> Can you try updating the definition to:
> 
> ```js
> {
>     fingerprint: [
>         {type: 'EndDevice', manufacturerID: 4098, endpoints: [{ID: 1, inputClusters: [], outputClusters: []}]},
>         {manufacturerName: '_TZ2000_a476raq2'},
>     ],
>     zigbeeModel: ['TS0201', 'SNTZ003'],
>     model: 'TS0201',
>     vendor: 'TuYa',
>     description: 'Temperature & humidity sensor with display',
>     fromZigbee: [fz.battery, fz.temperature, fz.humidity],
>     toZigbee: [],
>     exposes: [e.battery(), e.temperature(), e.humidity(), e.battery_voltage()],
>     configure: async (device, coordinatorEndpoint, logger) => {
>         const endpoint = device.getEndpoint(1);
>         await reporting.bind(endpoint, coordinatorEndpoint, ['msTemperatureMeasurement']);
>         await reporting.temperature(endpoint);
>     },
> },
> ```
> 
> Also make sure you are on the latest dev (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

Yes, I'm 9n latest dev, and still no temperature

**Comment by WildeRNS** [comment]
I think temperature and humidity must be received from this:
`Zigbee2MQTT:debug 2021-05-25 08:53:56: No converter available for 'TS0201' with cluster '57346' and type 'raw' and data '{"data":[8,5,10,15,208,48,2],"type":"Buffer"}'`

**Comment by Koenkk** [comment]
Seems this `0xE002` is a new TuYa cluster, someone should reverse engineer it.

**Comment by Vebryn** [comment]
According to your debug, device seems _TZ3000_qaaysllp :

```
Zigbee2MQTT:debug 2021-05-25 08:51:06: Received Zigbee message from 'Cabinet thermometer', type 'readResponse', cluster 'genBasic', data '{"manufacturerName":"_TZ3000_qaaysllp"}' from endpoint 1 with groupID 0
```

Temperature avec humidity are reported from endpoint 2 (cf. https://github.com/zigpy/zha-device-handlers/issues/862 and https://github.com/Koenkk/zigbee-herdsman-converters/issues/2696).

![image](https://user-images.githubusercontent.com/8328247/122348730-c1737c00-cf4b-11eb-98e0-a27aaefb0755.png)

**Comment by SimpleSon** [comment]
Bumping this thread to keep it alive.  I just received these sensors and have the same issue.
