### ISSUE TITLE
Failed to call 'Receive' 'onZigbeeEvent' (Immax Neo Smart Keypad)

### ISSUE THREAD

**Issue by tpettinicchi** [Koenkk/zigbee-herdsman-converters#2623]
Hello,

I try to add the Immax Keypad to my z2m.

I managed to pair the keypad with z2m, but when i try some actions, it fail with this message :
```
Debug Received Zigbee message from 'Keypad', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[0],"type":"Buffer"},"datatype":4,"dp":27,"fn":0,"status":0,"transid":63}' from endpoint 1 with groupID null
Error Failed to call 'Receive' 'onZigbeeEvent' (TypeError: Cannot read property 'type' of undefined at /app/lib/extension/receive.js:117:42 at Array.filter (<anonymous>) at Receive.onZigbeeEvent (/app/lib/extension/receive.js:116:65) at Controller.callExtensionMethod (/app/lib/controller.js:384:44))
```

For information :

I'm using HA integration test with normal and edge z2m.

The keypad is not yet supported by z2m, but a similar command is ok: 

https://www.zigbee2mqtt.io/devices/07046L.html

It's the same device, with numpad :
![image](https://user-images.githubusercontent.com/45467926/119506695-7318f600-bd6e-11eb-9e8b-28bf4ec4031b.png)

Some actions : 

arm_away : 
`Debug Received Zigbee message from 'Keypad', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[0],"type":"Buffer"},"datatype":4,"dp":27,"fn":0,"status":0,"transid":67}' from endpoint 1 with groupID null
Error Failed to call 'Receive' 'onZigbeeEvent' (TypeError: Cannot read property 'type' of undefined at /app/lib/extension/receive.js:117:42 at Array.filter (<anonymous>) at Receive.onZigbeeEvent (/app/lib/extension/receive.js:116:65) at Controller.callExtensionMethod (/app/lib/controller.js:384:44))
Debug Received Zigbee message from 'Keypad', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[0],"type":"Buffer"},"datatype":4,"dp":112,"fn":0,"status":0,"transid":68}' from endpoint 1 with groupID null
Error Failed to call 'Receive' 'onZigbeeEvent' (TypeError: Cannot read property 'type' of undefined at /app/lib/extension/receive.js:117:42 at Array.filter (<anonymous>) at Receive.onZigbeeEvent (/app/lib/extension/receive.js:116:65) at Controller.callExtensionMethod (/app/lib/controller.js:384:44))`

arm_home : 

`Debug Received Zigbee message from 'Keypad', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[0],"type":"Buffer"},"datatype":4,"dp":28,"fn":0,"status":0,"transid":69}' from endpoint 1 with groupID null
Error Failed to call 'Receive' 'onZigbeeEvent' (TypeError: Cannot read property 'type' of undefined at /app/lib/extension/receive.js:117:42 at Array.filter (<anonymous>) at Receive.onZigbeeEvent (/app/lib/extension/receive.js:116:65) at Controller.callExtensionMethod (/app/lib/controller.js:384:44))
Debug Received Zigbee message from 'Keypad', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[0],"type":"Buffer"},"datatype":4,"dp":112,"fn":0,"status":0,"transid":70}' from endpoint 1 with groupID null
Error Failed to call 'Receive' 'onZigbeeEvent' (TypeError: Cannot read property 'type' of undefined at /app/lib/extension/receive.js:117:42 at Array.filter (<anonymous>) at Receive.onZigbeeEvent (/app/lib/extension/receive.js:116:65) at Controller.callExtensionMethod (/app/lib/controller.js:384:44))`

disarm :

`Debug Received Zigbee message from 'Keypad', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[0],"type":"Buffer"},"datatype":4,"dp":26,"fn":0,"status":0,"transid":74}' from endpoint 1 with groupID null
Error Failed to call 'Receive' 'onZigbeeEvent' (TypeError: Cannot read property 'type' of undefined at /app/lib/extension/receive.js:117:42 at Array.filter (<anonymous>) at Receive.onZigbeeEvent (/app/lib/extension/receive.js:116:65) at Controller.callExtensionMethod (/app/lib/controller.js:384:44))
Debug Received Zigbee message from 'Keypad', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[0],"type":"Buffer"},"datatype":1,"dp":23,"fn":0,"status":0,"transid":75}' from endpoint 1 with groupID null
Error Failed to call 'Receive' 'onZigbeeEvent' (TypeError: Cannot read property 'type' of undefined at /app/lib/extension/receive.js:117:42 at Array.filter (<anonymous>) at Receive.onZigbeeEvent (/app/lib/extension/receive.js:116:65) at Controller.callExtensionMethod (/app/lib/controller.js:384:44))
Debug Received Zigbee message from 'Keypad', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[0],"type":"Buffer"},"datatype":4,"dp":112,"fn":0,"status":0,"transid":76}' from endpoint 1 with groupID null
Error Failed to call 'Receive' 'onZigbeeEvent' (TypeError: Cannot read property 'type' of undefined at /app/lib/extension/receive.js:117:42 at Array.filter (<anonymous>) at Receive.onZigbeeEvent (/app/lib/extension/receive.js:116:65) at Controller.callExtensionMethod (/app/lib/controller.js:384:44))`

sos :

`Debug Received Zigbee message from 'Keypad', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[0],"type":"Buffer"},"datatype":4,"dp":29,"fn":0,"status":0,"transid":77}' from endpoint 1 with groupID null
Error Failed to call 'Receive' 'onZigbeeEvent' (TypeError: Cannot read property 'type' of undefined at /app/lib/extension/receive.js:117:42 at Array.filter (<anonymous>) at Receive.onZigbeeEvent (/app/lib/extension/receive.js:116:65) at Controller.callExtensionMethod (/app/lib/controller.js:384:44))
Debug Received Zigbee message from 'Keypad', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[1],"type":"Buffer"},"datatype":1,"dp":23,"fn":0,"status":0,"transid":78}' from endpoint 1 with groupID null
Error Failed to call 'Receive' 'onZigbeeEvent' (TypeError: Cannot read property 'type' of undefined at /app/lib/extension/receive.js:117:42 at Array.filter (<anonymous>) at Receive.onZigbeeEvent (/app/lib/extension/receive.js:116:65) at Controller.callExtensionMethod (/app/lib/controller.js:384:44))
Debug Received Zigbee message from 'Keypad', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[0],"type":"Buffer"},"datatype":4,"dp":112,"fn":0,"status":0,"transid":79}' from endpoint 1 with groupID null
Error Failed to call 'Receive' 'onZigbeeEvent' (TypeError: Cannot read property 'type' of undefined at /app/lib/extension/receive.js:117:42 at Array.filter (<anonymous>) at Receive.onZigbeeEvent (/app/lib/extension/receive.js:116:65) at Controller.callExtensionMethod (/app/lib/controller.js:384:44))`

What else can I do to add it to z2m ?

Thanks in advance,

**Comment by tpettinicchi** [comment]
I resolve my issue :)

`const definition = {
    fingerprint: [
        {
            // The model ID from: Device with modelID 'TS0601' is not supported
            // You may need to add \u0000 at the end of the name in some cases
            modelID: 'TS0601',
            // The manufacturer name from: Device with modelID 'TS0601' is not supported.
            manufacturerName: '_TZE200_n9clpsht'
        },
    ],
    model: '07505L', // Vendor model number, look on the device for a model number
    vendor: 'Immax', // Vendor of the device (only used for documentation and startup logging)
    description: 'Immax Neo Smart Keypad', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
    fromZigbee: [
		fz.ignore_basic_report,
		{
		  cluster: "manuSpecificTuya",
		  type: [
			"commandSetDataResponse",
			"commandGetData",
			"commandActiveStatusReport",
		  ],
		  convert: (model, msg, publish, options, meta) => {
			const dp = msg.data.dp;
			const armModeImmax = {
				26: 'disarm',
				27: 'arm_away',
				28: 'arm_home',
				29: 'sos',
			};

			return {action: armModeImmax[dp]};
		  },
		},
	],
    exposes: [e.action(['disarm', 'arm_home', 'arm_away', 'sos'])],
    toZigbee: [],
};`

An now it's work great :)

**Comment by paffeke** [comment]
> I resolve my issue :)
> 
> ```
> const definition = {
>     fingerprint: [
>         {
>             // The model ID from: Device with modelID 'TS0601' is not supported
>             // You may need to add \u0000 at the end of the name in some cases
>             modelID: 'TS0601',
>             // The manufacturer name from: Device with modelID 'TS0601' is not supported.
>             manufacturerName: '_TZE200_n9clpsht'
>         },
>     ],
>     model: '07505L', // Vendor model number, look on the device for a model number
>     vendor: 'Immax', // Vendor of the device (only used for documentation and startup logging)
>     description: 'Immax Neo Smart Keypad', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
>     fromZigbee: [
> 		fz.ignore_basic_report,
> 		{
> 		  cluster: "manuSpecificTuya",
> 		  type: [
> 			"commandSetDataResponse",
> 			"commandGetData",
> 			"commandActiveStatusReport",
> 		  ],
> 		  convert: (model, msg, publish, options, meta) => {
> 			const dp = msg.data.dp;
> 			const armModeImmax = {
> 				26: 'disarm',
> 				27: 'arm_away',
> 				28: 'arm_home',
> 				29: 'sos',
> 			};
> 
> 			return {action: armModeImmax[dp]};
> 		  },
> 		},
> 	],
>     exposes: [e.action(['disarm', 'arm_home', 'arm_away', 'sos'])],
>     toZigbee: [],
> };
> ```
> 
> An now it's work great :)

Hi mate,
could you kindly help me to configure my Immax NEO 07505L? I tried a lot but i really don't know how to make it works.
Thank you!
