### ISSUE TITLE
Problem with integration 

### ISSUE THREAD

**Issue by andiukas** [Koenkk/zigbee-herdsman-converters#2625]
I have new moes thermostat valve [https://bit.ly/34kWvM0](url)
but have problem with integration to mqtt:
Device '0x847127fffe12d0ec' with Zigbee model 'TS0601' and manufacturer name '_TZE200_b6wax7g0' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
any help ? ;)

**Comment by marpi82** [comment]
I would also like to join the request. I'm attaching the [tuya.dump.txt](https://github.com/Koenkk/zigbee-herdsman-converters/files/6590595/tuya.dump.txt) file that I managed to generate, but I don't know what to do with it now.

**Comment by marpi82** [comment]
I can see that one colleague is already working on it https://github.com/Koenkk/zigbee-herdsman-converters/pull/2652, so it will probably be soon.
