### ISSUE TITLE
devices / insta.js

### ISSUE THREAD

**Issue by fab-gh** [Koenkk/zigbee-herdsman-converters#2626]
Jung ZLLHS4 remote & Domoticz:

To get all keys working properly you need to change the insta.js file,
replacing 

'select_*'

by

'select_0','select_1','select_2','select_3','select_4','select_5'

**Comment by Koenkk** [comment]
Fixed.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
