### ISSUE TITLE
Support UK CMA30036 (2 gang in wall sockets)

### ISSUE THREAD

**Issue by awaldram** [Koenkk/zigbee-herdsman-converters#2628]
[https://zigbee.blakadder.com/ClickSmart_CMA30036.html](url) despite this saying zigbee2mqtt supports this device it doesn't appear in the devices.js (at least my version).

Modifying the existing TS011F_2_gang_wall with the correct manafacturerName corrects this and make the UK variant fully supported.
modified stanza is under tuya:-  {manufacturerName: '_TYZB01_hlla45kx' }

`    {
        fingerprint: [{modelID: 'TS011F', manufacturerName: '_TZ3000_mvn6jl7x' }, {manufacturerName: '_TYZB01_hlla45kx' }],
        model: 'TS011F_2_gang_wall',
        vendor: 'TuYa',
        description: '2 gang wall outlet',
        extend: preset.switch(),
        exposes: [e.switch().withEndpoint('l1'), e.switch().withEndpoint('l2')],
        endpoint: (device) => {
            return {'l1': 1, 'l2': 2};
        },
        meta: {multiEndpoint: true},
    },
`

**Comment by Koenkk** [comment]
`_TYZB01_hlla45kx` has already been added to the latest dev branch. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
