### ISSUE TITLE
Saswell TRV SAE-801/SAE-802 valve position

### ISSUE THREAD

**Issue by onpaj** [Koenkk/zigbee-herdsman-converters#2642]
Hi, I'm highly interested in reading valve position (on/off at least) from Saswell SAE-801/802 TRV. I have found some older threads about this topic and I would like to ask, if someone is making progress with this one. I have no experience with adding/enhancing devices, but with a little guidance, I could try that.

**Comment by Styx85** [comment]
I do not think I could add it, but I own several of those TRVs and can help in testing.
There is some [stale code](https://github.com/zigpy/zha-device-handlers/pull/778) in ZHA github, too. Maybe it is kind of a usable blueprint.
