### ISSUE TITLE
IKEA Styrbar W2051 appeared on the shelf

### ISSUE THREAD

**Issue by fnfid** [Koenkk/zigbee-herdsman-converters#2647]
The unsupported IKEA Styrbar W2051 appeared and is pretty much the same as the Stybar W2049 which is supported. I will try to make my way the support it, but may take a while (do not hesitate to overtake).

**Comment by sjorge** [comment]
Are you sure it's unsuported? The model number starts with E IIRC the W's are the manufacturing week

**Comment by MattWestb** [comment]
Pleas use the real type name of the products and not the manufacturing year and week.
The name is [E2001 (stainless)](https://fccid.io/FHO-E2001) and [E2002 (white)](https://fccid.io/FHO-E2002) and **not** produced in 2020 week 51 (YYWW is the standard for marking electronic products).

My 2 E2002 is W2045 19972 in one of the early series from the factory.

Also the Z2M wiki is very sadly the same :-(((

**Comment by slankes** [comment]
I bought a E2001 a few weeks ago and did not manage to pair it with my z2m. Reading @MattWestb comment I tried again and it turns out that it is supported just fine and that the only problem I was having is that I sometimes need to power-cycle my CC2531 USB stick for it to be able to learn new devices again. 

After I did this the switch paired fine and works with all four buttons:

 * arrow_right_click
 * arrow_left_click
 * on
 * off

```info  2021-06-29 07:14:09: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"description":"STYRBAR remote control N2","friendly_name":"0x842e14fffe891a84","model":"E2001/E2002","supported":true,"vendor":"IKEA"},"type":"pairing"}'```

Unless anyone else is having issues with pairing this I would suggest closing this bug.

**Comment by fnfid** [comment]
Ahh, sorry for beeing misguided by the name in documentation, your absolutely right, it' E2001. As the thing paired easy as all the other stuff, but did not get any command or info, it just thought...
Tried again several times pairing again, now it's up and runnig. 
Thanks for all the help!

**Comment by MattWestb** [comment]
The name is "mostly" fixed in the supported device page only the linking and one wrong spelled / missed  `E` is left.

**Comment by Sierek** [comment]
I have purchased E2001 (stainless) and pairing was successful, but I have the following message:

```
Warning Received message from unsupported device with Zigbee model 'Remote Control N2' and manufacturer name 'IKEA of Sweden'
Warning Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
```

What can I do? Create an external converter file is rather pointless.
