### ISSUE TITLE
Busch Jäger 6737 - Missing row 3 and 4

### ISSUE THREAD

**Issue by Ellerburg** [Koenkk/zigbee-herdsman-converters#2659]
Hi,

after installing and pairing the B+J 6737 with my iobroker Zigbee instance, ibroker is giving some error message in the log.
Finally, I am not able to get any feedback on row 3 and 4 of the device.

Details of my system:
- Zigbee adapter v1.5.6
- Conbee stick in use
- iobroker v4.2.1
- Device ID of BJ 6737: 0xd85def11a1006449

Even if row 2 looks similar to row 3 and 4 in the object properties (see screenshot below), row 2 can be used by pressing the buttons. Row 3 and 4 do not react on any interaction.

Thanks for any hint on how to resolve this issue!

Regards,
E.

`

zigbee.0 | 2021-06-06 10:19:37.467 | warn | at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/adapter/deconzAdapter.js:24:58))
-- | -- | -- | --
zigbee.0 | 2021-06-06 10:19:37.467 | warn | at Generator.next (&lt;anonymous&gt;)
zigbee.0 | 2021-06-06 10:19:37.467 | warn | at DeconzAdapter.&lt;anonymous&gt; (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/adapter/deconzAdapter.js:712:23)
zigbee.0 | 2021-06-06 10:19:37.467 | warn | (21329) DeviceConfigure failed 0xd85def11a1006449 RM01, attempt 5 (Error: Bind 0xd85def11a1006449/12 genLevelCtrl from '0x00212effff06cd99/1' failed (Error: status: 140)
zigbee.0 | 2021-06-06 10:19:35.742 | info | (21329) Configuring 0xd85def11a1006449 RM01
zigbee.0 | 2021-06-06 10:19:31.057 | warn | at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/adapter/deconzAdapter.js:24:58))
zigbee.0 | 2021-06-06 10:19:31.057 | warn | at Generator.next (&lt;anonymous&gt;)
zigbee.0 | 2021-06-06 10:19:31.057 | warn | at DeconzAdapter.&lt;anonymous&gt; (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/adapter/deconzAdapter.js:712:23)
zigbee.0 | 2021-06-06 10:19:31.057 | warn | (21329) DeviceConfigure failed 0xd85def11a1006449 RM01, attempt 4 (Error: Bind 0xd85def11a1006449/12 genLevelCtrl from '0x00212effff06cd99/1' failed (Error: status: 140)
zigbee.0 | 2021-06-06 10:19:30.758 | info | (21329) Configuring 0xd85def11a1006449 RM01
zigbee.0 | 2021-06-06 10:19:26.623 | warn | at processTimers (internal/timers.js:494:9))
zigbee.0 | 2021-06-06 10:19:26.623 | warn | at runNextTicks (internal/process/task_queues.js:62:5)
zigbee.0 | 2021-06-06 10:19:26.623 | warn | at rejected (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/adapter/deconzAdapter.js:25:65)
zigbee.0 | 2021-06-06 10:19:26.623 | warn | at Generator.throw (&lt;anonymous&gt;)
zigbee.0 | 2021-06-06 10:19:26.623 | warn | at DeconzAdapter.&lt;anonymous&gt; (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/adapter/deconzAdapter.js:712:23)
zigbee.0 | 2021-06-06 10:19:26.623 | warn | (21329) DeviceConfigure failed 0xd85def11a1006449 RM01, attempt 3 (Error: Bind 0xd85def11a1006449/18 genLevelCtrl from '0x00212effff06cd99/1' failed (waiting for response TIMEOUT)
zigbee.0 | 2021-06-06 10:19:14.497 | info | (21329) Zigbee: stop joining
zigbee.0 | 2021-06-06 10:18:25.744 | info | (21329) Configuring 0xd85def11a1006449 RM01
zigbee.0 | 2021-06-06 10:18:22.844 | warn | at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/adapter/deconzAdapter.js:24:58))
zigbee.0 | 2021-06-06 10:18:22.844 | warn | at Generator.next (&lt;anonymous&gt;)
zigbee.0 | 2021-06-06 10:18:22.844 | warn | at DeconzAdapter.&lt;anonymous&gt; (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/adapter/deconzAdapter.js:712:23)
zigbee.0 | 2021-06-06 10:18:22.844 | warn | (21329) DeviceConfigure failed 0xd85def11a1006449 RM01, attempt 2 (Error: Bind 0xd85def11a1006449/12 genLevelCtrl from '0x00212effff06cd99/1' failed (Error: status: 140)
zigbee.0 | 2021-06-06 10:18:20.750 | info | (21329) Configuring 0xd85def11a1006449 RM01
zigbee.0 | 2021-06-06 10:18:18.563 | warn | at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/adapter/deconzAdapter.js:24:58))
zigbee.0 | 2021-06-06 10:18:18.563 | warn | at Generator.next (&lt;anonymous&gt;)
zigbee.0 | 2021-06-06 10:18:18.563 | warn | at DeconzAdapter.&lt;anonymous&gt; (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/adapter/deconzAdapter.js:712:23)
zigbee.0 | 2021-06-06 10:18:18.563 | warn | (21329) DeviceConfigure failed 0xd85def11a1006449 RM01, attempt 1 (Error: Bind 0xd85def11a1006449/12 genLevelCtrl from '0x00212effff06cd99/1' failed (Error: status: 140)
zigbee.0 | 2021-06-06 10:18:16.574 | info | (21329) Configuring 0xd85def11a1006449 RM01
zigbee.0 | 2021-06-06 10:18:16.570 | info | (21329) Device '0xd85def11a1006449' is supported, identified as: Busch-Jaeger Zigbee Light Link power supply/relay/dimmer (6735/6736/6737)
zigbee.0 | 2021-06-06 10:18:16.569 | info | (21329) Successfully interviewed '0xd85def11a1006449', device has succesfully been paired
zigbee.0 | 2021-06-06 10:18:15.401 | info | (21329) Starting interview of '0xd85def11a1006449'
zigbee.0 | 2021-06-06 10:18:12.138 | info | (21329) Zigbee: allowing new devices to join.

`

![image](https://user-images.githubusercontent.com/82972590/120917693-e09f1d80-c6b0-11eb-8ed4-b54f9c1a92a6.png)

**Comment by Ellerburg** [comment]
Hi

This is still open.

Does anyone know how I can get the rows to work?

I appreciate any support!!!

E.

**Comment by Kartracer390** [comment]
Hello

I have the same problem as Ellerburg
Would be very grateful for a solution or a tip

**Comment by Kartracer390** [comment]
The Problem still persists

**Comment by guidokanschat** [comment]
I have the same issue as well, running the current docker container
