### ISSUE TITLE
Axis Gear has incorrect battery info

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee-herdsman-converters#2664]
https://support.helloaxis.com/en/articles/5209549-charging-battery-warnings-on-the-app

Both of mine always show around 60-68% but given the device has the don’t divide set, that would fall in the 30% range mentioned if the gear is set to the wrong mode, solar when AC or AC when solar.

This leads me to believe that:
- we **do** need to device the value
- we are missing a way to indicate the power mode

I noticed there is a genPowerCfg on ep 169 and ep1 (current), I will experiment with the other ep and see if that one is correct. My current running theory is ep1 = solar, ep169 = ac power.

If this is correct, I think we will need a easy wat to toggle between both configurations. Not sure how to handle that but let’s figure out if my theory is correct.

**Comment by sjorge** [comment]
@Koenkk this should work righht?

```
mosquitto_pub -t zigbee2mqtt/bridge/request/device/bind -m '{"clusters":["genPowerCfg"],"from":"cover/livingroom/side1/196","to":"Coordinator", "skip_disable_reporting": true}'
```

<img width="408" alt="image" src="https://user-images.githubusercontent.com/379665/121039340-496dbf00-c7b1-11eb-934f-9ad30410f700.png">


```
Zigbee2MQTT:info  2021-06-07 14:56:26: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/bind', payload '{"data":{"clusters":[],"failed":[],"from":"cover/livingroom/side1/196","to":"Coordinator"},"error":"Nothing to bind","status":"error"}'
Zigbee2MQTT:error 2021-06-07 14:56:26: Nothing to bind
```

**Comment by Koenkk** [comment]
That should work indeed, don't understand why it doesn't, can you do some debugging here: https://github.com/Koenkk/zigbee2mqtt/blob/9bd46932c365e886ed0b1f9b8740d8cce632230c/lib/extension/bind.js#L181 ?

**Comment by sjorge** [comment]
<blockquote class="twitter-tweet"><p lang="en" dir="ltr"><a href="https://twitter.com/sjorge?ref_src=twsrc%5Etfw">@sjorge</a> Hi Jorge, if you are using the AC wall adapter, the battery level will always stay within the range of 25-35% as it is continually drawing power from the outlet. The battery level indicator is only relevant to if you are using the solar panel.</p>&mdash; AXIS (@theaxislife) <a href="https://twitter.com/theaxislife/status/1402313486026354694?ref_src=twsrc%5Etfw">June 8, 2021</a></blockquote>

I heard back from them on twitter, looks like we're done. Just not dividing gets the expected range for when using AC power. I will close this once I have done a docs update to indicate that the battery value will be around 25-35% when using AC power.

**Comment by sjorge** [comment]
Note to self or koenk: Close this once https://github.com/Koenkk/zigbee2mqtt.io/pull/789 is merged.
