### ISSUE TITLE
Setting pin_code in closuresDoorLock always sets user status to 1 (enabled) and user type to 1 (unrestricted)

### ISSUE THREAD

**Issue by jpg0** [Koenkk/zigbee-herdsman-converters#2681]
This is clearly undesirable if the user is not currently in this state (may be disabled for example), or of this type (may be restricted to specific time periods, or alternatively may be a master/admin user etc).

These values are currently hardcoded at https://github.com/Koenkk/zigbee-herdsman-converters/blob/96fa306822e36fd2c77e51df8e2f37a95b2ccbe5/converters/toZigbee.js#L178-L179

Ideally they should be left unchanged.

Note that my door lock (Yale) rejects a message which omits them, so presumably they need to be resent from a cache? (Or possibly it's not my lock, but somewhere further down the sending stack.)

**Comment by Koenkk** [comment]
Added, I've also exposes it now so it can be set from the frontend.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by jpg0** [comment]
Awesome, and so quick! I do plan to add explicit support for the different user types (e.g. schedules for user codes) at some point, so it's great that this is done.
