### ISSUE TITLE
Please, add new device _TZE200_fsb6zw01 is a clone _TZE200_byzdayie

### ISSUE THREAD

**Issue by jaroslaw81** [Koenkk/zigbee-herdsman-converters#2682]
It's clone  _TZE200_byzdayie (RTX ZCB16-2P _TZE200_fsb6zw01)  link to device: https://www.rtx24.pl/bezpiecznik-sterowany-2x-16a-zigbee-tuya-pomiar-energii-p-474.html

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    // Since a lot of Tuya devices use the same modelID, but use different data points
    // it's usually necessary to provide a fingerprint instead of a zigbeeModel
    fingerprint: [
        {
            // The model ID from: Device with modelID 'TS0601' is not supported
            // You may need to add \u0000 at the end of the name in some cases
            modelID: 'TS0601',
            // The manufacturer name from: Device with modelID 'TS0601' is not supported.
            manufacturerName: '_TZE200_fsb6zw01'
        },
    ],
    model: 'ZCB16-2P',
    vendor: 'RTX',
    description: 'Zigbee smart energy meter ZCB16-2P Zigbee',
    fromZigbee: [fz.tuya_dinrail_switch],
    toZigbee: [tz.tuya_switch_state],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff']);
    },
    exposes: [e.switch().setAccess('state', ea.STATE_SET), e.voltage(), e.power(), e.current(), e.energy()],
};

module.exports = definition;

**Comment by Koenkk** [comment]
Added, 
Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
