### ISSUE TITLE
Please add device _TZE200_t5p1vj8r is clone Smart9 5p1vj8r

### ISSUE THREAD

**Issue by jaroslaw81** [Koenkk/zigbee-herdsman-converters#2687]
Link to device: [https://www.rtx24.pl/czujnik-detektor-dymu-zigbee-tuya-smart-p-412.html
](url)

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    // Since a lot of Tuya devices use the same modelID, but use different data points
    // it's usually necessary to provide a fingerprint instead of a zigbeeModel
    fingerprint: [
        {
            // The model ID from: Device with modelID 'TS0601' is not supported
            // You may need to add \u0000 at the end of the name in some cases
            modelID: 'TS0601',
            // The manufacturer name from: Device with modelID 'TS0601' is not supported.
            manufacturerName: '_TZE200_t5p1vj8r'
        },
    ],
    model: 't5p1vj8r',
    vendor: 'RTX',
    description: 'Smoke sensor',
    fromZigbee: [fz.tuya_smoke],
    toZigbee: [],
    configure: async (device, coordinatorEndpoint, logger) => {
       const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genBasic']);
    },
    exposes: [e.smoke(), e.battery_low()],
};

module.exports = definition;

**Comment by Koenkk** [comment]
Done!

**Comment by kamilgregorczyk** [comment]
Thanks, do we know when will it be deployed?

**Comment by Koenkk** [comment]
@kamilgregorczyk next z2m release on 1 July
