### ISSUE TITLE
Sunricher sr-zg9001k12-dim-z4 remote is detected as an RGB Genie ZGRC-KEY-013

### ISSUE THREAD

**Issue by meinarsson** [Koenkk/zigbee-herdsman-converters#2703]
My Sunricher 4 channel remote sr-zg9001k12-dim-z4 is detected as a 2 channel RGBGenie ZGRC-KEY-013
When i pair the remote with a Ikea Zigbee hub it is also identified as model ZGRC-KEY-013 som that is probably what the device is reporting. The Ikea hub correctly identifies the remote as a Sunricher device.

The Sunricher remote seems to be sold under many names, in Zigbee2mqtt i can find remotes that look the same under the names Namron 4512705 and iCasa ICZB-RM11S.

How can i get my remote recognized as the right kind of device?

**Comment by meinarsson** [comment]
In the database.db file I have this data about the device, how are devices with the same model I'd handled by lookup? 
{"id":4,"type":"EndDevice","ieeeAddr":"0x000d6f00106a769b","nwkAddr":43871,"manufId":4644,"manufName":"Sunricher","powerSource":"Battery","modelId":"ZGRC-KEY-013","epList":[1,2,3,4],"endpoints":{"1":{"profId":260,"epId":1,"devId":1,"inClusterList":[0,1,3,2821,4096],"outClusterList":[3,4,5,6,8,25,4096],"clusters":{"genBasic":{"attributes":{"modelId":"ZGRC-KEY-013","manufacturerName":"Sunricher","powerSource":3,"zclVersion":2,"appVersion":0,"stackVersion":0,"hwVersion":0,"dateCode":"NULL","swBuildId":"2.2.3_r11"}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":1,"inClusterList":[0,1,3,2821,4096],"outClusterList":[3,4,5,6,8,25,4096],"clusters":{"genPowerCfg":{"attributes":{"batteryPercentageRemaining":95}},"genBasic":{"attributes":{"appVersion":0,"stackVersion":0,"hwVersion":0}}},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":1,"inClusterList":[0,1,3,2821,4096],"outClusterList":[3,4,5,6,8,25,4096],"clusters":{"genBasic":{"attributes":{"appVersion":0,"stackVersion":0,"hwVersion":0}}},"binds":[],"configuredReportings":[],"meta":{}},"4":{"profId":260,"epId":4,"devId":1,"inClusterList":[0,1,3,2821,4096],"outClusterList":[3,4,5,6,8,25,4096],"clusters":{"genBasic":{"attributes":{"appVersion":0,"stackVersion":0,"hwVersion":0}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":0,"hwVersion":0,"dateCode":"NULL","swBuildId":"2.2.3_r11","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1624266230126}

**Comment by Koenkk** [comment]
Probably just a whitelabel, but given that your database.db shows Sunricher it probably means that Sunricher is the manufacturer and RGB Genie is just selling it as a whitelabel. Renamed the vendor to Sunricher now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by meinarsson** [comment]
But the RGN genie and Sunricher devices are not the same HW. The Sunricher is 4 channel with two scene buttons and looks like the  Namron 4512705 and iCasa ICZB-RM11S. The RGBgenie device only has three channels

**Comment by Koenkk** [comment]
But do all actions work correctly?

**Comment by meinarsson** [comment]
The 4 on and off buttons and the 2 scene recall buttons generate OK events, I get both 3_on and on_3 (for button 3 and n_on, on_n for button=n), but maybe that is as designed? 

The master on and off switches generate 3 4_on or 4_off events. Not sure what to expect but thought I should get 4 messages one for each channel.

Zigbee2MQTT

Show only
all
Filter by text
Enter search criteria
Log level
info
 
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"on_4","action_group":24321,"battery":99,"click":"4_on","linkquality":42}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"","battery":99,"linkquality":42}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":null,"battery":99,"click":"","linkquality":42}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b/action', payload 'on_4'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b/click', payload '4_on'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"on_4","action_group":24322,"battery":99,"click":"4_on","linkquality":45}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"on_4","action_group":24323,"battery":99,"click":"4_on","linkquality":45}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"on_4","action_group":24324,"battery":99,"click":"4_on","linkquality":45}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"","battery":99,"linkquality":45}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":null,"battery":99,"click":"","linkquality":45}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"","battery":99,"linkquality":45}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":null,"battery":99,"click":"","linkquality":45}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"","battery":99,"linkquality":45}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":null,"battery":99,"click":"","linkquality":45}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b/action', payload 'on_4'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b/action', payload 'on_4'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b/action', payload 'on_4'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b/click', payload '4_on'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b/click', payload '4_on'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b/click', payload '4_on'

**Comment by Koenkk** [comment]
Can you provide the debug log of each button which generates event which are not correct?

See https://www.zigbee2mqtt.io/information/debug.html on how to enable debug logging.

**Comment by meinarsson** [comment]
When I press the master on button this is logged:
Debug Received Zigbee message from '0x000d6f00106a769b', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 4 with groupID 24321
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"on_4","action_group":24321,"battery":85,"click":"4_on","linkquality":12}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"","battery":85,"linkquality":12}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":null,"battery":85,"click":"","linkquality":12}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b/action', payload 'on_4'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b/click', payload '4_on'
Debug Received Zigbee message from '0x000d6f00106a769b', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 4 with groupID 24322
Debug Received Zigbee message from '0x000d6f00106a769b', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 4 with groupID 24323
Debug Received Zigbee message from '0x000d6f00106a769b', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 4 with groupID 24324
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"on_4","action_group":24322,"battery":85,"click":"4_on","linkquality":12}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"on_4","action_group":24323,"battery":85,"click":"4_on","linkquality":12}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"on_4","action_group":24324,"battery":85,"click":"4_on","linkquality":12}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"","battery":85,"linkquality":12}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":null,"battery":85,"click":"","linkquality":12}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"","battery":85,"linkquality":12}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":null,"battery":85,"click":"","linkquality":12}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"","battery":85,"linkquality":12}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":null,"battery":85,"click":"","linkquality":12}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b/action', payload 'on_4'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b/action', payload 'on_4'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b/action', payload 'on_4'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b/click', payload '4_on'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b/click', payload '4_on'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b/click', payload '4_on'

When I press the master off button this is logged:
Debug Received Zigbee message from '0x000d6f00106a769b', type 'commandOff', cluster 'genOnOff', data '{}' from endpoint 4 with groupID 24321
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"off_4","action_group":24321,"battery":85,"click":"4_off","linkquality":33}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"","battery":85,"linkquality":33}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":null,"battery":85,"click":"","linkquality":33}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b/action', payload 'off_4'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b/click', payload '4_off'
Debug Received Zigbee message from '0x000d6f00106a769b', type 'commandOff', cluster 'genOnOff', data '{}' from endpoint 4 with groupID 24322
Debug Received Zigbee message from '0x000d6f00106a769b', type 'commandOff', cluster 'genOnOff', data '{}' from endpoint 4 with groupID 24323
Debug Received Zigbee message from '0x000d6f00106a769b', type 'commandOff', cluster 'genOnOff', data '{}' from endpoint 4 with groupID 24324
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"off_4","action_group":24322,"battery":85,"click":"4_off","linkquality":33}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"off_4","action_group":24323,"battery":85,"click":"4_off","linkquality":33}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"off_4","action_group":24324,"battery":85,"click":"4_off","linkquality":33}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"","battery":85,"linkquality":33}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":null,"battery":85,"click":"","linkquality":33}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"","battery":85,"linkquality":33}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":null,"battery":85,"click":"","linkquality":33}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"","battery":85,"linkquality":33}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":null,"battery":85,"click":"","linkquality":33}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b/action', payload 'off_4'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b/action', payload 'off_4'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b/action', payload 'off_4'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b/click', payload '4_off'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b/click', payload '4_off'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b/click', payload '4_off'

When i press one of the scene recall buttons this is logged:
Debug Received Zigbee message from '0x000d6f00106a769b', type 'commandRecall', cluster 'genScenes', data '{"groupid":0,"sceneid":1}' from endpoint 4 with groupID 24321
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"recall_1_4","action_group":24321,"battery":85,"linkquality":36}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"","battery":85,"linkquality":36}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b/action', payload 'recall_1_4'
Debug Received Zigbee message from '0x000d6f00106a769b', type 'commandRecall', cluster 'genScenes', data '{"groupid":0,"sceneid":1}' from endpoint 4 with groupID 24322
Debug Received Zigbee message from '0x000d6f00106a769b', type 'commandRecall', cluster 'genScenes', data '{"groupid":0,"sceneid":1}' from endpoint 4 with groupID 24323
Debug Received Zigbee message from '0x000d6f00106a769b', type 'commandRecall', cluster 'genScenes', data '{"groupid":0,"sceneid":1}' from endpoint 4 with groupID 24324
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"recall_1_4","action_group":24322,"battery":85,"linkquality":39}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"recall_1_4","action_group":24323,"battery":85,"linkquality":39}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"recall_1_4","action_group":24324,"battery":85,"linkquality":39}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"","battery":85,"linkquality":39}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"","battery":85,"linkquality":39}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"","battery":85,"linkquality":39}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b/action', payload 'recall_1_4'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b/action', payload 'recall_1_4'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b/action', payload 'recall_1_4'

When I press the on button for one (channel 4) of the channels:
Debug Received Zigbee message from '0x000d6f00106a769b', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 4 with groupID 24324
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"on_4","action_group":24324,"battery":85,"click":"4_on","linkquality":33}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":"","battery":85,"linkquality":33}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":null,"battery":85,"click":"","linkquality":33}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b/action', payload 'on_4'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b/click', payload '4_on'

**Comment by Koenkk** [comment]
And what would you expect to be send instead? (I don't see what is wrong with this)

**Comment by meinarsson** [comment]
I'm not sure what would be considered correct, but for the master on and off buttons the remote generates 4 Zigbee messages with different groupIds but they are all from endpoint 4, this triggers 4 MQTT action messages for on_4. I had expected the 4 actions on_1, on_2, on_3, on_4, but maybe logic should instead be based on the groupId? 

For the scene recall buttons the remote generates 4 Zigbee messages for Cluster genScenes with different groupIds all from endpoint 4, this triggers 4 MQTT action messages for action recall_1_4. I had expected 1 message for each cluster, ie recall_1_1, recall_1_2, recall_1_3, recall_1_4. But considering the messages sent by the remote maybe that is not reasonable and any logic should instead use the GroupId instead?

**Comment by Koenkk** [comment]
What if you disable the legacy integration by adding the following to your `configuration.yaml`:

```yaml
device_options:
  legacy: false
```

**Comment by meinarsson** [comment]
I tried setting legacy: false and restarted. 
Then i got an error message that configure reporting failed, and after that the groupId of endpoint 1 is 0.
I have tried to remove and repair the remote. As soon as the reporting failure has occurred the groupId of endpoint 1 is 0. See the error message bemow. I have tried to create an external converter to try to remove the reporting configuration, but without success. If I do not have any reporting config in my convert, is some default reporting config used? 

Failed to configure '0x000d6f00106a769b', attempt 1 (Error: ConfigureReporting 0x000d6f00106a769b/1 genOnOff([{"attribute":"onOff","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":0}], {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 3872 - 1 - 3 - 6 - 7 after 10000ms) at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:37:35) at listOnTimeout (internal/timers.js:554:17) at processTimers (internal/timers.js:497:7))

**Comment by bayview252** [comment]
I've got a couple of the whitelabel RGBGenie ZB-5004 coming in 2 weeks.  I'll have a play, and let you know.  I've just integrated the RGBGenie ZB-5008/5028 into HA, and it has similar quirks. Master on/off and zone 1 commands don't provide an action_group attribute, but zone 2/3/4 button actions do. From your log, that looks like zigbee-herdsman-containers is recognising your device and providing the payloads of the buttons as provided by the manufacturer (which is quirky!)  I've published a [blueprint](https://community.home-assistant.io/t/zigbee2mqtt-rgbgenie-remote-control-zb-5008-zb-5028-rgbw-4-zone-on-off-switch-dimmer-color-wheel-scenes-and-controls-blueprint-all-actions-should-support-other-multi-zone-remote-controls-and-wall-panels-iluminize-namron-sunricher-muller/320266) on the H-A Community Blueprint exchange for the ZB-5008/5028 which, looking at your logs, should work with your remote with a bit of tweaking (if you are using home-assistant). If not, I'll recode to handle the ZB-5004 as well.

**Comment by bayview252** [comment]
In the The Iluminize 511.344 device definition (which is the same as the RGBGenie 5008/5028 in the devices.db,  someone has pushed a change to modify behaviour for the master on/off key to just provide on or off. The only issue there is that they have hard-coded their own device (each device has its own set of 5 digit id's based on number of zones)  id action_group sequence into the universal db. Should be able to follow this logic within an external converter and provide whatever logic you want.

**Comment by meinarsson** [comment]
Actually for me zone 1 also sends a unigue groupId until the reporting configuration fails with a timeout. After the failure the groupid is 0. If I factory reset the remote and re-pair new groupids are generated for all 4 zones, them reporting configuration fails and zone 1 reverts to groupid 0.
Will try to look at the iluminize you mentioned

**Comment by bayview252** [comment]
Hmm. Well I received the RGBGenie ZB-5004 and it sends the following, so it seems to be acting the same as yours (apart from the failure....). Actually, this behaviour makes the Home Assistant much easier to code. 

**Master On**
Received Zigbee message from 'Dimmer_remote_1', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 4 with groupID 48900
Info MQTT publish: topic 'zigbee2mqtt/Dimmer_remote_1', payload '{"action":"","battery":37.5,"linkquality":21}'
Debug Received Zigbee message from 'Dimmer_remote_1', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 4 with groupID 48897
Info MQTT publish: topic 'zigbee2mqtt/Dimmer_remote_1', payload '{"action":"","battery":37.5,"linkquality":21}'
Debug Received Zigbee message from 'Dimmer_remote_1', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 4 with groupID 48899
Info MQTT publish: topic 'zigbee2mqtt/Dimmer_remote_1', payload '{"action":"","battery":37.5,"linkquality":63}'
Debug Received Zigbee message from 'Dimmer_remote_1', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 4 with groupID 48898

**Master Off**

Info MQTT publish: topic 'zigbee2mqtt/Dimmer_remote_1', payload '{"action":"","battery":37.5,"linkquality":24}'
Debug Received Zigbee message from 'Dimmer_remote_1', type 'commandOff', cluster 'genOnOff', data '{}' from endpoint 4 with groupID 48898
Info MQTT publish: topic 'zigbee2mqtt/Dimmer_remote_1', payload '{"action":"","battery":37.5,"linkquality":24}'
Debug Received Zigbee message from 'Dimmer_remote_1', type 'commandOff', cluster 'genOnOff', data '{}' from endpoint 4 with groupID 48900
Info MQTT publish: topic 'zigbee2mqtt/Dimmer_remote_1', payload '{"action":"","battery":37.5,"linkquality":24}'
Debug Received Zigbee message from 'Dimmer_remote_1', type 'commandOff', cluster 'genOnOff', data '{}' from endpoint 4 with groupID 48897
Info MQTT publish: topic 'zigbee2mqtt/Dimmer_remote_1', payload '{"action":"","battery":37.5,"linkquality":21}'
Debug Received Zigbee message from 'Dimmer_remote_1', type 'commandOff', cluster 'genOnOff', data '{}' from endpoint 4 with groupID 48899

**Individual Zone 1-4 On Command**

Info MQTT publish: topic 'zigbee2mqtt/Dimmer_remote_1', payload '{"action":"","battery":37.5,"linkquality":24}'
Debug Received Zigbee message from 'Dimmer_remote_1', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 48897
Info MQTT publish: topic 'zigbee2mqtt/Dimmer_remote_1', payload '{"action":"","battery":37.5,"linkquality":21}'
Debug Received Zigbee message from 'Dimmer_remote_1', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 2 with groupID 48898
Info MQTT publish: topic 'zigbee2mqtt/Dimmer_remote_1', payload '{"action":"","battery":37.5,"linkquality":21}'
Debug Received Zigbee message from 'Dimmer_remote_1', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 3 with groupID 48899
Info MQTT publish: topic 'zigbee2mqtt/Dimmer_remote_1', payload '{"action":"","battery":37.5,"linkquality":24}'
Debug Received Zigbee message from 'Dimmer_remote_1', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 4 with groupID 48900
Info MQTT publish: topic 'zigbee2mqtt/Dimmer_remote_1', payload '{"action":"","battery":37.5,"linkquality":21}'

**Comment by meinarsson** [comment]
My remote behaved like this when i paired it the first time. After a restart om zigbee2mqtt i started getting the failures and groupid 0 for zone 1.

/Magnus
Sent from my iPhone

13 juli 2021 kl. 00:53 skrev Bayview252 ***@***.***>:

﻿

Hmm. Well I received the RGBGenie ZB-5004 and it sends the following, so it seems to be acting the same as yours (apart from the failure....). Actually, this behaviour makes the Home Assistant much easier to code.

Master On
Received Zigbee message from 'Dimmer_remote_1', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 4 with groupID 48900
Info MQTT publish: topic 'zigbee2mqtt/Dimmer_remote_1', payload '{"action":"","battery":37.5,"linkquality":21}'
Debug Received Zigbee message from 'Dimmer_remote_1', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 4 with groupID 48897
Info MQTT publish: topic 'zigbee2mqtt/Dimmer_remote_1', payload '{"action":"","battery":37.5,"linkquality":21}'
Debug Received Zigbee message from 'Dimmer_remote_1', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 4 with groupID 48899
Info MQTT publish: topic 'zigbee2mqtt/Dimmer_remote_1', payload '{"action":"","battery":37.5,"linkquality":63}'
Debug Received Zigbee message from 'Dimmer_remote_1', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 4 with groupID 48898

Master Off

Info MQTT publish: topic 'zigbee2mqtt/Dimmer_remote_1', payload '{"action":"","battery":37.5,"linkquality":24}'
Debug Received Zigbee message from 'Dimmer_remote_1', type 'commandOff', cluster 'genOnOff', data '{}' from endpoint 4 with groupID 48898
Info MQTT publish: topic 'zigbee2mqtt/Dimmer_remote_1', payload '{"action":"","battery":37.5,"linkquality":24}'
Debug Received Zigbee message from 'Dimmer_remote_1', type 'commandOff', cluster 'genOnOff', data '{}' from endpoint 4 with groupID 48900
Info MQTT publish: topic 'zigbee2mqtt/Dimmer_remote_1', payload '{"action":"","battery":37.5,"linkquality":24}'
Debug Received Zigbee message from 'Dimmer_remote_1', type 'commandOff', cluster 'genOnOff', data '{}' from endpoint 4 with groupID 48897
Info MQTT publish: topic 'zigbee2mqtt/Dimmer_remote_1', payload '{"action":"","battery":37.5,"linkquality":21}'
Debug Received Zigbee message from 'Dimmer_remote_1', type 'commandOff', cluster 'genOnOff', data '{}' from endpoint 4 with groupID 48899

Individual Zone 1-4 On Command

Info MQTT publish: topic 'zigbee2mqtt/Dimmer_remote_1', payload '{"action":"","battery":37.5,"linkquality":24}'
Debug Received Zigbee message from 'Dimmer_remote_1', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 48897
Info MQTT publish: topic 'zigbee2mqtt/Dimmer_remote_1', payload '{"action":"","battery":37.5,"linkquality":21}'
Debug Received Zigbee message from 'Dimmer_remote_1', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 2 with groupID 48898
Info MQTT publish: topic 'zigbee2mqtt/Dimmer_remote_1', payload '{"action":"","battery":37.5,"linkquality":21}'
Debug Received Zigbee message from 'Dimmer_remote_1', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 3 with groupID 48899
Info MQTT publish: topic 'zigbee2mqtt/Dimmer_remote_1', payload '{"action":"","battery":37.5,"linkquality":24}'
Debug Received Zigbee message from 'Dimmer_remote_1', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 4 with groupID 48900
Info MQTT publish: topic 'zigbee2mqtt/Dimmer_remote_1', payload '{"action":"","battery":37.5,"linkquality":21}'

**Comment by bayview252** [comment]
I'm running the zigbee2mqtt-edge add-on.  That may make a difference.  I would delete the device from zigbee2mqtt and re-pair, or use an external converter and set the model to the rgbgenie zb-5004, and see if that makes a difference? good luck, got to do some actual pay-the-bills work now!

**Comment by meinarsson** [comment]
Using an external converter with a copy of the code for rgbgenie zb-5004 the Sunricher works better. 
The change that makes a difference seems to be the removal of:
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff']);
            await reporting.onOff(endpoint);
        },

What is the purpose of that piece of code?

**Comment by meinarsson** [comment]
@bayview252 with the same config as rgbgenie zb-5004  the remote works as expected except for if I leave it unused for a period of time. When I then press a button I don't get any event for the button I pressed only a bunch of announcement and state message, see below, is that the same for your RGBgenie remote? 

 Log from pressing 
Debug Device '0x000d6f00106a769b' announced itself
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x000d6f00106a769b","ieee_address":"0x000d6f00106a769b"},"type":"device_announce"}'
Info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0x000d6f00106a769b"},"type":"device_announced"}'
Debug Received Zigbee message from '0x000d6f00106a769b', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":59}' from endpoint 2 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":null,"battery":59,"linkquality":66}'
Debug Received Zigbee message from '0x000d6f00106a769b', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":59}' from endpoint 2 with groupID 0
Debug Received Zigbee message from '0x000d6f00106a769b', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":59}' from endpoint 2 with groupID 0
Debug Received Zigbee message from '0x000d6f00106a769b', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":59}' from endpoint 2 with groupID 0
Debug Received Zigbee message from '0x000d6f00106a769b', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":59}' from endpoint 2 with groupID 0
Debug Received Zigbee message from '0x000d6f00106a769b', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":59}' from endpoint 2 with groupID 0
Debug Received Zigbee message from '0x000d6f00106a769b', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":59}' from endpoint 2 with groupID 0
Debug Received Zigbee message from '0x000d6f00106a769b', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":59}' from endpoint 2 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":null,"battery":59,"linkquality":66}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":null,"battery":59,"linkquality":66}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":null,"battery":59,"linkquality":66}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":null,"battery":59,"linkquality":66}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":null,"battery":59,"linkquality":66}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":null,"battery":59,"linkquality":66}'
Info MQTT publish: topic 'zigbee2mqtt/0x000d6f00106a769b', payload '{"action":null,"battery":59,"linkquality":66}'

**Comment by bayview252** [comment]
I've seen those messages come through 4-5 hourly as the remotes report status.  Haven't had any issues with it ignoring button presses. I would check what happens when you press all buttons as you test.  Maybe a faulty button? Sometimes the interview process seems to leave devices (in general) in a strange state, so one of the things I do when devices are not behaving as expected is to delete them, take the battery out, put it back in, allow to rejoin.

I don't have anything more for you unfortunately, other than configuring another router/coordinator as a sniffer, and examining what happens when you press buttons rather than the zigbee2mqtt interpretation of what it has received.  This might highlight errors in your custom configuration?  Good luck, it sounds like you're nearly there!
