### ISSUE TITLE
Heiman Siren HS2WD-E not recognized by Zigbee2MQTT under Home Assistant

### ISSUE THREAD

**Issue by stittel** [Koenkk/zigbee-herdsman-converters#2707]
Hi Koen,

I added the Heiman Siren HS2WD-E to Zigbee2MQTT. It is paired, but the messages on the bottom said the device is not supported. Therefor I can't communicate with the device ( I used MQTT Explorer to put messages on th e topic as described in https://www.zigbee2mqtt.io/devices/HS2WD-E.html). I use a ZZH coordinator stick which has the latest firmware (wget https://github.com/Koenkk/Z-Stack-firmware/raw/master/coordinator/Z-Stack_3.x.0/bin/CC2652R_coordinator_20210120.zip && unzip CC2652R_coordinator_20210120.zip)

The only values which are reported back are the friendly name, IEEE address, and LQI.

I also checked for support of this device, it is there in the heiman.js file under Zigbee Herdsman converters. I don't see any debug messages in the log:

logger:
  default: info
  logs:  
    homeassistant.components.zha: debug

_I wonder what the root cause is._

![Schermafbeelding 2021-06-22 om 11 56 17](https://user-images.githubusercontent.com/63233867/122913779-2a972d00-d35a-11eb-8d1b-8ee037d3ef46.png)
![Schermafbeelding 2021-06-22 om 13 03 44](https://user-images.githubusercontent.com/63233867/122913880-4f8ba000-d35a-11eb-8d88-38da3c2ee9d7.png)

**Comment by stittel** [comment]
These are the debug log messages from the Zigbee2MQtt log:

Zigbee2MQTT:debug 2021-06-23 07:54:31: Device '0xec1bbdfffe931013' announced itself
Zigbee2MQTT:info  2021-06-23 07:54:31: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xec1bbdfffe931013","ieee_address":"0xec1bbdfffe931013"},"type":"device_announce"}'
Zigbee2MQTT:info  2021-06-23 07:54:31: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0xec1bbdfffe931013"},"type":"device_announced"}'
Zigbee2MQTT:debug 2021-06-23 07:54:39: Received Zigbee message from '0xec1bbdfffe931013', type 'readResponse', cluster 'genBasic', data '{"manufacturerName":"HEIMAN"}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-06-23 07:54:39: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2021-06-23 07:54:39: Received Zigbee message from '0xec1bbdfffe931013', type 'readResponse', cluster 'genBasic', data '{"powerSource":129}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-06-23 07:54:39: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2021-06-23 07:54:39: Received Zigbee message from '0xec1bbdfffe931013', type 'readResponse', cluster 'genBasic', data '{"zclVersion":2}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-06-23 07:54:39: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2021-06-23 07:54:39: Received Zigbee message from '0xec1bbdfffe931013', type 'readResponse', cluster 'genBasic', data '{"appVersion":19}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-06-23 07:54:39: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2021-06-23 07:54:39: Received Zigbee message from '0xec1bbdfffe931013', type 'readResponse', cluster 'genBasic', data '{"stackVersion":2}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-06-23 07:54:39: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2021-06-23 07:54:40: Received Zigbee message from '0xec1bbdfffe931013', type 'readResponse', cluster 'genBasic', data '{"hwVersion":16}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-06-23 07:54:40: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2021-06-23 07:54:40: Received Zigbee message from '0xec1bbdfffe931013', type 'readResponse', cluster 'genBasic', data '{"dateCode":"2019.5.23"}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-06-23 07:54:40: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2021-06-23 07:54:40: Received Zigbee message from '0xec1bbdfffe931013', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-06-23 07:54:40: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2021-06-23 07:54:40: Received Zigbee message from '0xec1bbdfffe931013', type 'readResponse', cluster 'ssIasZone', data '{"iasCieAddr":"0x0000000000000000","zoneState":0}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-06-23 07:54:40: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2021-06-23 07:54:42: Received Zigbee message from '0xec1bbdfffe931013', type 'readResponse', cluster 'ssIasZone', data '{"iasCieAddr":"0x00124b0022a54b28","zoneState":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-06-23 07:54:42: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:info  2021-06-23 07:54:42: Successfully interviewed '0xec1bbdfffe931013', device has successfully been paired
Zigbee2MQTT:warn  2021-06-23 07:54:42: Device '0xec1bbdfffe931013' with Zigbee model 'undefined' and manufacturer name 'HEIMAN' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
Zigbee2MQTT:info  2021-06-23 07:54:42: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":null,"friendly_name":"0xec1bbdfffe931013","ieee_address":"0xec1bbdfffe931013","status":"successful","supported":false},"type":"device_interview"}'
Zigbee2MQTT:info  2021-06-23 07:54:42: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"friendly_name":"0xec1bbdfffe931013","supported":false},"type":"pairing"}'
Zigbee2MQTT:debug 2021-06-23 07:54:46: Received Zigbee message from '0xec1bbdfffe931013', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":0}' from endpoint 1 with groupID 0
Zigbee2MQTT:warn  2021-06-23 07:54:46: Received message from unsupported device with Zigbee model 'undefined' and manufacturer name 'HEIMAN'
Zigbee2MQTT:warn  2021-06-23 07:54:46: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
Zigbee2MQTT:debug 2021-06-23 07:54:49: Received Zigbee message from '0xec1bbdfffe931013', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":0}' from endpoint 1 with groupID 0
Zigbee2MQTT:warn  2021-06-23 07:54:49: Received message from unsupported device with Zigbee model 'undefined' and manufacturer name 'HEIMAN'
Zigbee2MQTT:warn  2021-06-23 07:54:49: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.

**Comment by stittel** [comment]
Completely removing the Heiman devices and repairing didn't solve the problem

**Comment by malaakso** [comment]
I have same model with firmware 2020.8.20, and it is working fine. It seems that your device doesn't report its model properly.

**Comment by stittel** [comment]
> I have same model with firmware 2020.8.20, and it is working fine. It seems that your device doesn't report its model properly.

Does that mean that my device is damaged? Or is it the combination with the Coordinator stick?

**Comment by malaakso** [comment]
> > I have same model with firmware 2020.8.20, and it is working fine. It seems that your device doesn't report its model properly.
> 
> Does that mean that my device is damaged? Or is it the combination with the Coordinator stick?

Most likely just old firmware in the siren. Unfortunately Heiman firmwares are not publicly available.

**Comment by stittel** [comment]
> > > I have same model with firmware 2020.8.20, and it is working fine. It seems that your device doesn't report its model properly.
> > 
> > 
> > Does that mean that my device is damaged? Or is it the combination with the Coordinator stick?
> 
> Most likely just old firmware in the siren. Unfortunately Heiman firmwares are not publicly available.

The big question than: if is related to the firmware, how can we upgrade the firmware of this Heiman device without having a Heiman hub?
