### ISSUE TITLE
Neo NAS-TH02B mis-identified as TuYa MIR-TE100 sensor

### ISSUE THREAD

**Issue by ali1234** [Koenkk/zigbee-herdsman-converters#2718]
Device I have: https://zigbee.blakadder.com/Neo_NAS-TH02B.html

Device it is identified as: https://zigbee.blakadder.com/Tuya_MIR-TE100.html

This sensor has temperature, humidity and lux readings, but the sensor it is identified as only supports temperature and humidity. Additionally, it never reports any readings unless the reset button is short-pressed, and then it only sends battery level and link quality. I am not sure if this is a result of mis-identification, or if it also needs an additional configuration section.

Information about the device from database.db: 
```
{
   "id":2,
   "type":"EndDevice",
   "ieeeAddr":"0xb4e3f9fffe07a4b6",
   "nwkAddr":46085,
   "manufId":4098,
   "manufName":"_TZ3000_qaaysllp",
   "powerSource":"Battery",
   "modelId":"TS0201",
   "epList":[
      1
   ],
   "endpoints":{
      "1":{
         "profId":260,
         "epId":1,
         "devId":262,
         "inClusterList":[
            0,
            1,
            1024,
            57346
         ],
         "outClusterList":[
            25,
            10
         ],
         "clusters":{
            "genBasic":{
               "attributes":{
                  "modelId":"TS0201",
                  "manufacturerName":"_TZ3000_qaaysllp",
                  "powerSource":3,
                  "zclVersion":3,
                  "appVersion":68,
                  "stackVersion":0,
                  "hwVersion":1,
                  "dateCode":""
               }
            },
            "msIlluminanceMeasurement":{
               "attributes":{
                  "measuredValue":23599
               }
            },
            "genPowerCfg":{
               "attributes":{
                  "batteryPercentageRemaining":200
               }
            }
         },
         "binds":[
            
         ],
         "configuredReportings":[
            
         ],
         "meta":{
            
         }
      }
   },
   "appVersion":68,
   "stackVersion":0,
   "hwVersion":1,
   "dateCode":"",
   "zclVersion":3,
   "interviewCompleted":true,
   "meta":{
      
   },
   "lastSeen":1624556677717
}
```

What I assume is the offending line that incorrectly matches this device:
https://github.com/Koenkk/zigbee-herdsman-converters/blob/767241e236483482576e8947f9a23751509848da/devices/tuya.js#L388

**Comment by blakadder** [comment]
Devices share the same model number `TS0201` and since the manufacturer `_TZ3000_qaaysllp` is not fingerprinted as a new device it is recognized as another sensor.
