### ISSUE TITLE
zigbeeModel.toLowerCase is not a function

### ISSUE THREAD

**Issue by GregoryGost** [Koenkk/zigbee-herdsman-converters#2720]
https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/index.js

function addToLookup(zigbeeModel, definition)
function getFromLookup(zigbeeModel)

Fix:
Replace from

`zigbeeModel = zigbeeModel ? zigbeeModel.toLowerCase() : null;`

to

`if (zigbeeModel) {
    zigbeeModel = String(zigbeeModel);
    zigbeeModel.toLowerCase();
} else {
    zigbeeModel = null;
}`

**Comment by Koenkk** [comment]
How to reproduce this bug? Also please make a PR (click the edit icon in the right top of https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/index.js)

**Comment by GregoryGost** [comment]
> How to reproduce this bug? Also please make a PR (click the edit icon in the right top of https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/index.js)

Thanks for the answer!

I am studying the ZigBee module CC2530 and use such a ZigBee model `gost.dbze18ms1.01`
I am installing zigbee2mqtt in python virtual environment on raspberry pi.
Try my temporary converter with the current mater assembly.

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ep = exposes.presets;
const ea = exposes.access;

const bind = async (endpoint, target, clusters) => {
    for (const cluster of clusters) {
        await endpoint.bind(cluster, target);
    }
};

const dbze18ms1 = {
	zigbeeModel: ['gost.dbze18ms1.01'],
	model: 'DBZE18MS1-01',
	vendor: 'ImAVendor',
	description: 'DBZE18MS1-01',
	fromZigbee: [ fz.battery ],
	toZigbee: [],
	exposes: [ ep.battery(), ep.battery_voltage(), ep.linkquality() ],
};

module.exports = dbze18ms1;
