### ISSUE TITLE
Install external-converters

### ISSUE THREAD

**Issue by PM04290** [Koenkk/zigbee-herdsman-converters#2754]
Hello,
I bought Chinese modules supposedly compatible with Tuya but in fact they do not have the correct TS011F_plug "model type".
I saw that they were in the devices/tuya.js file; I looked for the method to install external-converters on Home assistant but I couldn't find anything specific.
what is the correct method?

**Comment by Koenkk** [comment]
What is the data/database.db entry of this the device? Then I can add support for it out of the box.
