### ISSUE TITLE
Tuya Zigbee Thermostat Smart TRV Thermostatic Radiator Valve Controller not supported anymore

### ISSUE THREAD

**Issue by NittyGritty74141** [Koenkk/zigbee-herdsman-converters#2764]
I have been using this device for a while. 

https://www.aliexpress.com/item/1005001453587650.html?spm=a2g0s.9042311.0.0.27424c4dpjHMJp

After my computer crahed, I had to setup zigbee2mqtt from scratch. When trying to use the device, it shows

/home/zigbee/bridge/logging {"level":"warning","message":"Device with modelID 'undefined' is not supported."}
/home/zigbee/bridge/logging {"level":"warning","message":"Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html"}
I also did not find this valve in the supported devices anymore. Why?

**Comment by MattWestb** [comment]
"Device with modelID 'undefined'" = the system cant reading the device model / name.

Try deleting it and adding it in the system so the system can reading the name of it.
