### ISSUE TITLE
Aqara and Mijia Sensors not mentioned

### ISSUE THREAD

**Issue by scargill** [Koenkk/zigbee-herdsman-converters#2767]
This could well be me missing the point - but I have some new sensors from Banggood and AliExpress - a Xiaomi Mijia Smart Light Sensor part number GZCGQ01LM - and some Aqara sensors all of which work with Zigbee2MQTT - tested - and documented here https://tech.scargill.net/zigbee-development-update/  and here https://tech.scargill.net/zigbee-development-part-2-aqara/ which don't seem to appear on a quick search here https://www.zigbee2mqtt.io/information/supported_devices.html 

Or am I missing something?

**Comment by danieledwardgeorgehitchcock** [comment]
Have you tried looking under the [Xiaomi](https://www.zigbee2mqtt.io/information/supported_devices.html#xiaomi) section?

Aqara and Mijia is a consumer sub-brand of Xiaomi

**Comment by scargill** [comment]
You are of courwe correct. Thank you.
