### ISSUE TITLE
new device - Linkind 5-Key Smart Bulb Dimmer Switch Light Remote Control (ZS23000278)

### ISSUE THREAD

**Issue by kloodhu** [Koenkk/zigbee-herdsman-converters#2768]
I have this remote : https://www.linkind.com/product/5-key-smart-bulb-dimmer-switch/

I made a custom js. I think i managed to add all features into it, but im not sure.
The remote can send brightness, colortemp, color commands to 4 different device/group.

Attached here the js and the jsons for the commands
[LK_5button_mqtt_jsons.txt](https://github.com/Koenkk/zigbee-herdsman-converters/files/6768630/LK_5button_mqtt_jsons.txt)

[ZS23000278.zip](https://github.com/Koenkk/zigbee-herdsman-converters/files/6768637/ZS23000278.zip)

Please let me know if you need more information.

**Comment by Koenkk** [comment]
Added! 

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
