### ISSUE TITLE
White Label Device: ClickSmart+ CMA30036

### ISSUE THREAD

**Issue by uvjim** [Koenkk/zigbee-herdsman-converters#2779]
Hi,

This device paired without issue and was identified as `TS011F_2_gang_wall`.
The device seems to work fine.

URL for the device is: https://click-smart.com/products/2-gang-smart-socket

What's the best way of getting this device on the Supported List as a white label?

**Comment by Koenkk** [comment]
Added it, will be added to supported devices list with next update.
