### ISSUE TITLE
TS0215A SOS Button not working

### ISSUE THREAD

**Issue by jayden-jw** [Koenkk/zigbee-herdsman-converters#2797]
I bought 1 of this Tuya SOS Button, it was detected and shown supported but unfortunately it won't shows battery level and can't do any automation with this. I'm very new in this so really have no idea how to troubleshoot. Please take a look of the screenshot below and the output log, I'm not sure if it's the cluster issue, hope someone can spot the problem.

![image](https://user-images.githubusercontent.com/76594891/125886194-16a12cc4-2d02-40dc-83aa-9ee9c7987f2f.png)

Log output when i pressed the button:
Debug Received Zigbee message from '0x847127fffe0542eb', type 'commandEmergency', cluster 'ssIasAce', data '{}' from endpoint 1 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/0x847127fffe0542eb', payload '{"action":"emergency","battery":null,"linkquality":90}'
Info MQTT publish: topic 'zigbee2mqtt/0x847127fffe0542eb', payload '{"action":"","battery":null,"linkquality":90}'
Info MQTT publish: topic 'zigbee2mqtt/0x847127fffe0542eb/action', payload 'emergency'
Debug Saving state to file /config/zigbee2mqtt/state.json

This is what in the tuya.js for this model

fingerprint: [{modelID: 'TS0215A', manufacturerName: '_TZ3000_4fsgukof'},
            {modelID: 'TS0215A', manufacturerName: '_TZ3000_wr2ucaj9'}],
        model: 'TS0215A_sos',
        vendor: 'TuYa',
        description: 'SOS button',
        fromZigbee: [fz.command_emergency, fz.battery],
        exposes: [e.battery(), e.action(['emergency'])],
        toZigbee: [],

**Comment by JorgeMarron14** [comment]
I have the same problem. Can you fix them finally?

**Comment by rt400** [comment]
@jayden-jw did you found a solution for the battrey info ?
