### ISSUE TITLE
Unable to use the external_converters (tuya.js)

### ISSUE THREAD

**Issue by kalatos86** [Koenkk/zigbee-herdsman-converters#2799]
Dear Colleges,

I am trying to get connect the Tuya 4-gang switch TS004F (https://github.com/Koenkk/zigbee-herdsman-converters/commit/981b092d0292aaef95dbf018a1eeb0f2cb4eb016) through the zigbee2 mqtt module on my Home Assistant instance.

HA version:
core-2021.7.2
supervisor-2021.06.8
Home Assistant OS 6.1

Zigbee2mqtt:
Current version: 1.18.1-1

I downloaded latest tuya.js file from GitLab repository and place the file here:

![image](https://user-images.githubusercontent.com/75856476/125934373-3af85ea2-c66d-49bf-a9ef-61cc62705ab0.png)

I changed the configuration of the add-on, and here is the configuration:

![image](https://user-images.githubusercontent.com/75856476/125934535-ed0b3aa6-a0c3-479e-8572-10273d774c73.png)

After creating the file and change the configuration the Zigbee2mqtt won;t start showing 502: Bad Gateway issue.

Here is the log from the module:

 _node index.js
(node:88774) UnhandledPromiseRejectionWarning: internal/modules/cjs/loader.js:883
  throw err;
  ^
Error: Cannot find module '../lib/exposes'
Require stack:
- /app/lib/util/utils.js
- /app/lib/util/settings.js
- /app/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /app/lib/util/externally-loaded.js:1:17
    at Script.runInContext (vm.js:143:18)
    at Script.runInNewContext (vm.js:148:17)
    at Object.runInNewContext (vm.js:303:38)
    at loadModuleFromText (/app/lib/util/utils.js:156:8)
    at loadModuleFromFile (/app/lib/util/utils.js:162:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:88774) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:88774) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[12:32:32] INFO: Handing over control to Zigbee2mqtt Core ..._

Could you be so kind and advice what might be the issue with?

Thanks in advance,
Lukasz

**Comment by Koenkk** [comment]
Make sure to update z2m to the latest version first (1.20.0).

If you are still on 1.18.1 check first point of https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.19.0

**Comment by hcastanho** [comment]
Dear all,

I'm having the same issue when trying to run herdsman converter with lidl.js.

Using Zigbee2mqtt 1.22.0-2 in  HA OS

![image](https://user-images.githubusercontent.com/426826/140505867-1ebb60c9-ba15-43a6-a0ad-8181cee435bd.png)

![image](https://user-images.githubusercontent.com/426826/140505957-900716a9-2811-49a1-8d4b-0f4c35ac7c20.png)


I don't understand what I'm doing wrong or if I'm missing something. 
Does anyone have a clue on how to solve this?

Thanks in advance!

Best,
Hugo
