### ISSUE TITLE
Trying to add another EcoDim device: Eco-Dim.05

### ISSUE THREAD

**Issue by Rira1234** [Koenkk/zigbee-herdsman-converters#2803]
Hi,

I am trying to add a dual dimmer by EcoDim ([Link](https://www.ecodim.nl/eco-dim05-zigbee.html)) that doesn't appear to be supported. (Smart Dual Dimmer Switch 2x0-100W LED Eco-Dim.05 Zigbee. 

I tried to use your code to make an external converter .js file, but it doesn't work (see code and error below). Would it be possible to add integrate the app? Or how could I change my code to get it to work?

Thank you for your help.

Yours,

Code:
```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['Dimmer-Switch-ZB3.0'],
    model: 'Eco-Dim.05',
    vendor: 'EcoDim',
    description: 'Zigbee dimmer',
    extend: generic.light_onoff_brightness,
    meta: {configureKey: 1},
    configure: async (device, coordinatorEndpoint) => {
        const endpoint = device.getEndpoint(1);
        await bind(endpoint, coordinatorEndpoint, ['genOnOff', 'genLevelCtrl']);
        await configureReporting.onOff(endpoint);
        await configureReporting.brightness(endpoint);
    },
};

module.exports = definition;
```
Error (I pasted 1 node as an example):
`(node:401) UnhandledPromiseRejectionWarning: ReferenceError: generic is not defined
(Use `node --trace-warnings ...` to show where the warning was created)
(node:401) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:401) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by Koenkk** [comment]
`Dimmer-Switch-ZB3.0` is already supported in z2m 1.20.0.

If you are still on 1.18.1 check first point of https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.19.0

**Comment by Rira1234** [comment]
Thank you for your reply.

I actually did the update to 1.20.0-1 before I posted my message. I read your answers to others mentioning the necessary update and the support of 'EcoDim-Zigbee 3.0' type dimmers. I thought it might have to do with the device being another model.  But from you comment I understand that every 'EcoDim-Zigbee 3.0' device should work with the Z2M 1.20.0.

This is my current version of Z2M:
![image](https://user-images.githubusercontent.com/579267/126039761-23dd037c-787b-476f-bc1f-40fafd519dee.png)

For some strange reason it still reports that the device is not supported in the log. Could I be doing something wrong? I removed and re-interviewed the device a couple of times, just to make sure that wasn't the problem.

Yours,

Log:
```
Zigbee2MQTT:warn  2021-07-17 16:03:51: Device '0x847127fffed89c46' with Zigbee model 'EcoDim-Zigbee 3.0' and manufacturer name 'EcoDim BV' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
Zigbee2MQTT:warn  2021-07-17 16:04:12: Received message from unsupported device with Zigbee model 'EcoDim-Zigbee 3.0' and manufacturer name 'EcoDim BV'
Zigbee2MQTT:warn  2021-07-17 16:04:12: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.

```

**Comment by Koenkk** [comment]
I see yours has a slightly different modelID indeed, if I understand correctly it has 2 gangs right?

Can you share your data/database.db entry of this device?

**Comment by Rira1234** [comment]
Correct, it has two rotary nobs.

Is this what you are looking for?

id":12,"type":"Router","ieeeAddr":"0x847127fffed89c46","nwkAddr":35351,"manufId":4714,"manufName":"EcoDim
BV","powerSource":"Mains (single phase)","modelId":"EcoDim-Zigbee
3.0","epList":[1,2,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,8,2821,4096],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"EcoDim-Zigbee
3.0","manufacturerName":"EcoDim
BV","powerSource":1,"zclVersion":3,"appVersion":1,"stackVersion":6,"hwVersion":1,"dateCode":"20210130","swBuildId":"1.0"}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":257,"inClusterList":[0,3,4,5,6,8],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":1,"stackVersion":6,"hwVersion":1,"dateCode":"20210130","swBuildId":"1.0","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1626530699496}

Op za 17 jul. 2021 20:42 schreef Koen Kanters ***@***.***>:

**Comment by Koenkk** [comment]
Added. 

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by Rira1234** [comment]
Fantastic, thank you!

Op ma 19 jul. 2021 19:42 schreef Koen Kanters ***@***.***>:

**Comment by Rira1234** [comment]
Hi,

Unfortunately I did not get the switch to work yet. I installed Z2M Edge as prescribed (on my Home Assistant OS core-2021.7.3 on Raspberry Pi 4).

Re-installed Edge and re-interviewed device a couple of times without success.

Any idea's on what I did wrong?

Yours,

I got the following logs:

`
Zigbee2MQTT:debug 2021-07-21 20:18:52: Received Zigbee message from '0x847127fffed89c46', type 'readResponse', cluster 'genBasic', data '{"modelId":"EcoDim-Zigbee 3.0"}' from endpoint 1 with groupID null
Zigbee2MQTT:debug 2021-07-21 20:18:52: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2021-07-21 20:18:52: Received Zigbee message from '0x847127fffed89c46', type 'readResponse', cluster 'genBasic', data '{"manufacturerName":"EcoDim BV"}' from endpoint 1 with groupID null
Zigbee2MQTT:debug 2021-07-21 20:18:52: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2021-07-21 20:18:52: Received Zigbee message from '0x847127fffed89c46', type 'readResponse', cluster 'genBasic', data '{"powerSource":1}' from endpoint 1 with groupID null
Zigbee2MQTT:debug 2021-07-21 20:18:52: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2021-07-21 20:18:52: Received Zigbee message from '0x847127fffed89c46', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3}' from endpoint 1 with groupID null
Zigbee2MQTT:debug 2021-07-21 20:18:52: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2021-07-21 20:18:52: Received Zigbee message from '0x847127fffed89c46', type 'readResponse', cluster 'genBasic', data '{"appVersion":1}' from endpoint 1 with groupID null
Zigbee2MQTT:debug 2021-07-21 20:18:52: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2021-07-21 20:18:52: Received Zigbee message from '0x847127fffed89c46', type 'readResponse', cluster 'genBasic', data '{"stackVersion":6}' from endpoint 1 with groupID null
Zigbee2MQTT:debug 2021-07-21 20:18:52: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2021-07-21 20:18:52: Received Zigbee message from '0x847127fffed89c46', type 'readResponse', cluster 'genBasic', data '{"hwVersion":1}' from endpoint 1 with groupID null
Zigbee2MQTT:debug 2021-07-21 20:18:52: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2021-07-21 20:18:52: Received Zigbee message from '0x847127fffed89c46', type 'readResponse', cluster 'genBasic', data '{"dateCode":"20210130"}' from endpoint 1 with groupID null
Zigbee2MQTT:debug 2021-07-21 20:18:52: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2021-07-21 20:18:53: Received Zigbee message from '0x847127fffed89c46', type 'readResponse', cluster 'genBasic', data '{"swBuildId":"1.0"}' from endpoint 1 with groupID null
Zigbee2MQTT:debug 2021-07-21 20:18:53: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:info  2021-07-21 20:18:53: Successfully interviewed '0x847127fffed89c46', device has successfully been paired
Zigbee2MQTT:warn  2021-07-21 20:18:53: Device '0x847127fffed89c46' with Zigbee model 'EcoDim-Zigbee 3.0' and manufacturer name 'EcoDim BV' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
Zigbee2MQTT:info  2021-07-21 20:18:53: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":null,"friendly_name":"0x847127fffed89c46","ieee_address":"0x847127fffed89c46","status":"successful","supported":false},"type":"device_interview"}'
Zigbee2MQTT:info  2021-07-21 20:18:53: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"friendly_name":"0x847127fffed89c46","supported":false},"type":"pairing"}'
...
Zigbee2MQTT:debug 2021-07-21 20:19:04: Received Zigbee message from '0x847127fffed89c46', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":16803664,"imageType":61,"manufacturerCode":4714}' from endpoint 1 with groupID null
Zigbee2MQTT:warn  2021-07-21 20:19:04: Received message from unsupported device with Zigbee model 'EcoDim-Zigbee 3.0' and manufacturer name 'EcoDim BV'
Zigbee2MQTT:warn  2021-07-21 20:19:04: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
Zigbee2MQTT:debug 2021-07-21 20:19:07: Received Zigbee message from '0x847127fffed89c46', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":16803664,"imageType":61,"manufacturerCode":4714}' from endpoint 1 with groupID null
Zigbee2MQTT:warn  2021-07-21 20:19:07: Received message from unsupported device with Zigbee model 'EcoDim-Zigbee 3.0' and manufacturer name 'EcoDim BV'
Zigbee2MQTT:warn  2021-07-21 20:19:07: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
Zigbee2MQTT:debug 2021-07-21 20:19:10: Received Zigbee message from '0x847127fffed89c46', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":16803664,"imageType":61,"manufacturerCode":4714}' from endpoint 1 with groupID null
Zigbee2MQTT:warn  2021-07-21 20:19:10: Received message from unsupported device with Zigbee model 'EcoDim-Zigbee 3.0' and manufacturer name 'EcoDim BV'
Zigbee2MQTT:warn  2021-07-21 20:19:10: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
Zigbee2MQTT:debug 2021-07-21 20:19:13: Received Zigbee message from '0x847127fffed89c46', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":16803664,"imageType":61,"manufacturerCode":4714}' from endpoint 1 with groupID null
Zigbee2MQTT:warn  2021-07-21 20:19:13: Received message from unsupported device with Zigbee model 'EcoDim-Zigbee 3.0' and manufacturer name 'EcoDim BV'
Zigbee2MQTT:warn  2021-07-21 20:19:13: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
Zigbee2MQTT:debug 2021-07-21 20:19:16: Received Zigbee message from '0x847127fffed89c46', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":16803664,"imageType":61,"manufacturerCode":4714}' from endpoint 1 with groupID null
Zigbee2MQTT:warn  2021-07-21 20:19:16: Received message from unsupported device with Zigbee model 'EcoDim-Zigbee 3.0' and manufacturer name 'EcoDim BV'
Zigbee2MQTT:warn  2021-07-21 20:19:16: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
`

**Comment by Koenkk** [comment]
Turned out the build of the edge addon was broken, fixed now and should be available in 1 hour from now.
