### ISSUE TITLE
Add Colortemp support for Ikea LED1937T5

### ISSUE THREAD

**Issue by pxStrato** [Koenkk/zigbee-herdsman-converters#2839]
All,

Ikea advertises this bulb with colortemp change capabilities, but the Ikea.js does not include that parameter.
I added it and confirmed it is working fine via Home Assistant for the two bulbs I bought yesterday.

I am a newb when it comes to Git, so failing on how to create a PR for this easy change.
All that is required is to change line 105 of Ikea.js from
`extend: tradfriExtend.light_onoff_brightness(),`
to
`extend: tradfriExtend.light_onoff_brightness_colortemp(),`

Thanks
pxStrato

**Comment by smulle48** [comment]
It support 3 step. 2200, 2700 and 4000 Kelvin

**Comment by Koenkk** [comment]
Does the suggestion from the OP work?

**Comment by smulle48** [comment]
> Does the suggestion from the OP work?

Yes. I can confirm it works 👍

**Comment by Koenkk** [comment]
Thanks, added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by pxStrato** [comment]
Thank you very much, gentlemen. 🙏👏😎
