### ISSUE TITLE
ZNJLBL01LM is not support

### ISSUE THREAD

**Issue by 295171924** [Koenkk/zigbee-herdsman-converters#2840]
warn  2021-07-25 12:47:09: Device '0x**************' with Zigbee model 'lumi.curtain.acn002' and manufacturer name 'LUMI' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
warn  2021-07-25 12:47:12: Received message from unsupported device with Zigbee model 'lumi.curtain.acn002' and manufacturer name 'LUMI'

**Comment by 295171924** [comment]
![image](https://img.youpin.mi-img.com/shopmain/08dedc20d30324885a367c20846b0d15.jpg)

**Comment by 295171924** [comment]
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const fz = {...require('zigbee-herdsman-converters/converters/fromZigbee'), legacy: require('zigbee-herdsman-converters/lib/legacy').fromZigbee};
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const ota = require('zigbee-herdsman-converters/lib/ota');
const constants = require('zigbee-herdsman-converters/lib/constants');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const znjlbl01lm = {
        zigbeeModel: ['lumi.curtain.acn002'],
        model: 'ZNJLBL01LM',
        description: 'Aqara roller shade companion  E1',
        vendor: 'LUMI',
        fromZigbee: [fz.xiaomi_curtain_position, fz.battery, fz.cover_position_tilt, fz.ignore_basic_report, fz.xiaomi_curtain_options],
        toZigbee: [tz.xiaomi_curtain_position_state, tz.xiaomi_curtain_options],
        exposes: [e.cover_position().setAccess('state', ea.ALL), e.battery()],
        ota: ota.zigbeeOTA,
};

module.exports = znjlbl01lm;

**Comment by 295171924** [comment]
```JS
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const fz = {...require('zigbee-herdsman-converters/converters/fromZigbee'), legacy: require('zigbee-herdsman-converters/lib/legacy').fromZigbee};
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const ota = require('zigbee-herdsman-converters/lib/ota');
const constants = require('zigbee-herdsman-converters/lib/constants');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const znjlbl01lm = {
        zigbeeModel: ['lumi.curtain.acn002'],
        model: 'ZNJLBL01LM',
        description: 'Aqara roller shade companion  E1',
        vendor: 'LUMI',
        fromZigbee: [fz.xiaomi_curtain_position, fz.battery, fz.cover_position_tilt, fz.ignore_basic_report, fz.xiaomi_curtain_options],
        toZigbee: [tz.xiaomi_curtain_position_state, tz.xiaomi_curtain_options],
        exposes: [e.cover_position().setAccess('state', ea.ALL), e.battery()],
        ota: ota.zigbeeOTA,
};

module.exports = znjlbl01lm;

```

**Comment by Koenkk** [comment]
Please create a pull request by pressing the edit (pencil) icon here: https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/xiaomi.js
