### ISSUE TITLE
Add support for toggle command on Legrand 067774

### ISSUE THREAD

**Issue by Ravexkgd** [Koenkk/zigbee-herdsman-converters#2841]
With old firmwares supported actions on and off,
while new firmwares only support action toggle.
I suppose that adding action toggle would allow to support all
firmware versions.

The same, as for https://github.com/Koenkk/zigbee-herdsman-converters/pull/2694

**Comment by Ravexkgd** [comment]
Info MQTT publish: topic 'zigbee2mqtt/0x00047400008ab95d', payload '{"action":"","battery":null,"last_seen":"2021-07-26T22:11:23+03:00","linkquality":27,"voltage":3000}'
Debug Received Zigbee message from '0x00047400008ab95d', type 'commandToggle', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 0

**Comment by Ravexkgd** [comment]
And working external converter with toggle and battery level:

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const readInitialBatteryState = async (type, data, device) => {
    if (['deviceAnnounce'].includes(type)) {
        const endpoint = device.getEndpoint(1);
        const options = {manufacturerCode: 0x1021, disableDefaultResponse: true};
        await endpoint.read('genPowerCfg', ['batteryVoltage'], options);
    }
};

const device = {
        zigbeeModel: [' Double gangs remote switch\u0000\u0000\u0000\u0000'],
        model: '067774',
        vendor: '  Legrand',
        description: 'Wireless double remote switch',
        fromZigbee: [fz.identify, fz.command_on, fz.command_off, fz.command_toggle, fz.command_move, fz.command_stop, fz.battery],
        exposes: [e.battery(), e.action(['identify', 'on', 'off', 'toggle', 'brightness_move_up', 'brightness_move_down', 'brightness_stop'])],
        toZigbee: [],
        meta: {multiEndpoint: true, battery: {voltageToPercentage: '3V_2500'}},
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genPowerCfg', 'genOnOff', 'genLevelCtrl']);
            const endpoint2 = device.getEndpoint(2);
            await reporting.bind(endpoint2, coordinatorEndpoint, ['genPowerCfg', 'genOnOff', 'genLevelCtrl']);
        },
        endpoint: (device) => {
            return {left: 1, right: 2};
        },
        onEvent: readInitialBatteryState,
    };
module.exports = device;

**Comment by Koenkk** [comment]
Please create a pr by pressing the edit (pencil) icon here: https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/legrand.js
