### ISSUE TITLE
Ubisys D1: converters for dimming don't work as described

### ISSUE THREAD

**Issue by wb441** [Koenkk/zigbee-herdsman-converters#2842]
**Zigbee2mqtt version info:** 1.20.0 commit: 41b67fd

**What I'm trying to achieve:** Using the 'brightness_move'-command on a Ubisys D1 as described in the documentation.

I'm sending this to zigbee2mqtt/D1/set:
`{
  "brightness_move": 40
}`

**What happens:**
In the logs I get the message that there is no converter available for that particular command:
`Error No converter available for 'brightness_move' (40)`

**Investigation**

In the ubisys file under the device directory, I find that the move command is listed for this device:

`{
        zigbeeModel: ['D1 (5503)', 'D1-R (5603)'],
        model: 'D1',
        vendor: 'Ubisys',
        description: 'Universal dimmer D1',
        fromZigbee: [fz.on_off, fz.brightness, fz.metering, fz.command_toggle, fz.command_on, fz.command_off, fz.command_recall,
            fz.command_move, fz.command_stop, ...`

So, I don't know why the message 'No converter available' is thrown.
I removed and paired the device again, and rebooted zigbee2mqtt as well as NodeRED, but no change.
Test commands sending different brightnesses ("brightness":60 for example) works just fine.

**Comment by wb441** [comment]
@sjorge Could you put me on the right path perhaps? Thanks!

**Comment by sjorge** [comment]
Not sure, I had a quick look at the converters and it looks correct for it to work.
Don't have a D1 to test with though.

**Comment by Danit2** [comment]
I had the same problem but with the transition.

It is now fixed. See link above. 

Is your problem also fixed?

**Comment by wb441** [comment]
Hi Danit2,
Transition works well.
However, brightness_move still doesn't seem to have a converter.

If I dig down into herdsman converters I find this definition for the D1:
` {
        zigbeeModel: ['D1 (5503)', 'D1-R (5603)'],
        model: 'D1',
        vendor: 'Ubisys',
        description: 'Universal dimmer D1',
        fromZigbee: [fz.on_off, fz.brightness, fz.metering, fz.command_toggle, fz.command_on, fz.command_off, fz.command_recall,
            **fz.command_move, fz.command_stop**, fz.lighting_ballast_configuration, fz.level_config, fz.ubisys_dimmer_setup,
            fz.ubisys_dimmer_setup_genLevelCtrl],`

It is quite different to another device I have (a Xiaomi bulb) for which the move command works brilliantly:
`{
        zigbeeModel: ['lumi.light.aqcn02'],
        model: 'ZNLDP12LM',
        vendor: 'Xiaomi',
        description: 'Aqara smart LED bulb',
        toZigbee: xiaomiExtend.light_onoff_brightness_colortemp().toZigbee.concat([
            tz.xiaomi_light_power_outage_memory]),
        fromZigbee: **xiaomiExtend.light_onoff_brightness_colortemp().fromZigbee**,`

If I dig deeper down to fromZigbee definitions, I find the command_move. However, I'm stuck as I don't know how the mapping is done to the actual addresses in the D1's technical spec. I suspect it then hands it over to Zigbee herdsman, but I don't know where to look further.

`command_move: {
        cluster: 'genLevelCtrl',
        type: ['commandMove', 'commandMoveWithOnOff'],
        options: [exposes.options.simulated_brightness()],
        convert: (model, msg, publish, options, meta) => {
            const direction = msg.data.movemode === 1 ? 'down' : 'up';
            const action = postfixWithEndpointName(`brightness_move_${direction}`, msg, model);
            const payload = {action, action_rate: msg.data.rate};
            addActionGroup(payload, msg, model);

            if (options.simulated_brightness) {
                const opts = options.simulated_brightness;
                const deltaOpts = typeof opts === 'object' && opts.hasOwnProperty('delta') ? opts.delta : 20;
                const intervalOpts = typeof opts === 'object' && opts.hasOwnProperty('interval') ? opts.interval : 200;

                globalStore.putValue(msg.endpoint, 'simulated_brightness_direction', direction);
                if (globalStore.getValue(msg.endpoint, 'simulated_brightness_timer') === undefined) {
                    const timer = setInterval(() => {
                        let brightness = globalStore.getValue(msg.endpoint, 'simulated_brightness_brightness', 255);
                        const delta = globalStore.getValue(msg.endpoint, 'simulated_brightness_direction') === 'up' ?
                            deltaOpts : -1 * deltaOpts;
                        brightness += delta;
                        brightness = numberWithinRange(brightness, 0, 255);
                        globalStore.putValue(msg.endpoint, 'simulated_brightness_brightness', brightness);
                        publish({brightness});
                    }, intervalOpts);

                    globalStore.putValue(msg.endpoint, 'simulated_brightness_timer', timer);
                }
            }

            return payload;
        },
    },`


Any pointers so I can troubleshoot & test further?

**Comment by sjorge** [comment]
It might just be the device does not send the commands ( to the coordinator)

Some things to start would be:
- enable debug log level
- use the device
- check logs if you see any data from the D1 wrt to brightness_move command
- post the data here or go to next step
- make sure genLevelCtrl is bound to Coordinator in the bind tab in the frontend
- repeat the first 4 steps

**Comment by wb441** [comment]
Hi Sjorge,

Thanks a lot for the feedback!

Step 1 through 4:

The result: https://pastebin.com/BcXYw5xA
"No converter available for brightness_move". Seems like a classic case of _How to support a new device_ 

Indeed, no brightness_move seems to be in toZigbee or fromZigbee. Instead, there is command_move, command_stop.
Should I use a different MQTT payload to use those commands instead?


- make sure genLevelCtrl is bound to Coordinator in the bind tab in the frontend

According to the [docs  ](https://www.ubisys.de/wp-content/uploads/ubisys-d1-technical-reference.pdf), Application Endpoint 1 is the output of the dimmable light. 
Application Endpoint #0 – ZigBee Device Object
Application Endpoint #1 – Dimmable Light    **The dimmable output**
Application Endpoint #2 – Primary Dimmer Switch **Input 1**
Application Endpoint #3 – Secondary Dimmer Switch **Input 2**
Application Endpoint #4 – Metering
Application Endpoint #232 – Device Management
...


From factory, input 1 is paired to the dimmable light. Zigbee2mqtt registers this binding immediately after pairing the device.
This is how it looks in the bindings tab:
![image](https://user-images.githubusercontent.com/40491548/146191514-e60f2239-4ed4-4476-9ee0-ef5508b5e805.png)


It seems weird to me that the **input** is the one that seems to have the On/Off and LevelCtrl properties. I would have expected the output to be the one to have that?

When trying to check point 5 of your message (make sure genLevelCtrl is bound to Coordinator in the bind tab in the frontend) I try to bind endpoint 1 to the coordinator, but that doesn't seem to do much:
![image](https://user-images.githubusercontent.com/40491548/146191826-7b138a94-59c5-4b0b-a2ea-e853043d6dcb.png)


Sidebar: On, Off and Brightness commands work perfectly.
Therefore, LevelCtrl works to a certain extent, right?

Next steps:
Brightness_move command as in the doc, seems to work through brightness_move parameter in the MQTT command.
But this device seems to have "command_move" and "command_stop", which don't seem to react to this.
Should I try to create a converter for brightness_move to this device OR should I use a different MQTT command to cater for the command_move and command_stop parameters?

Thanks a lot in advance :)

**Comment by sjorge** [comment]
Try adding `tz.light_brightness_move` to the toZigbee array for the D1 in devices/ubysis.js and restart zigbee2mqtt.

**Comment by wb441** [comment]
He shoots... he scores!
That did the trick!
Testament to how good the architecture of z2m is.
I have some other items which have the same thing, like the on_transition_time, off_transition_time and try to submit them.

Thank you so much!
