### ISSUE TITLE
Samsung Smartthings Outlet support

### ISSUE THREAD

**Issue by marc-gist** [Koenkk/zigbee-herdsman-converters#285]
So i'm trying to follow the docs on how to add support for this plug, and have got to the stage where I can see data in the log.

> Feb 17 21:17:10 raspz2m npm[3792]: #033[34m  zigbee2mqtt:debug#033[39m 2/17/2019, 9:17:10 PM Received zigbee message of type 'attReport' with data '{"cid":"genOnOff","data":{"onOff":1}}' of device 'outlet' (0x286d970001051d63)
Feb 17 21:17:10 raspz2m npm[3792]: #033[33m  zigbee2mqtt:warn#033[39m 2/17/2019, 9:17:10 PM No converter available for 'IM6001-OTP05' with cid 'genOnOff', type 'attReport' and data '{"cid":"genOnOff","data":{"onOff":1}}'
Feb 17 21:17:10 raspz2m npm[3792]: #033[33m  zigbee2mqtt:warn#033[39m 2/17/2019, 9:17:10 PM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
Feb 17 21:17:10 raspz2m npm[3792]: #033[34m  zigbee2mqtt:debug#033[39m 2/17/2019, 9:17:10 PM Received zigbee message of type 'devChange' with data '{"cid":"genOnOff","data":{"onOff":1}}' of device 'outlet' (0x286d970001051d63)
Feb 17 21:17:10 raspz2m npm[3792]: #033[33m  zigbee2mqtt:warn#033[39m 2/17/2019, 9:17:10 PM No converter available for 'IM6001-OTP05' with cid 'genOnOff', type 'devChange' and data '{"cid":"genOnOff","data":{"onOff":1}}'
Feb 17 21:17:10 raspz2m npm[3792]: #033[33m  zigbee2mqtt:warn#033[39m 2/17/2019, 9:17:10 PM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
Feb 17 21:17:12 raspz2m npm[3792]: #033[34m  zigbee2mqtt:debug#033[39m 2/17/2019, 9:17:12 PM Received zigbee message of type 'attReport' with data '{"cid":"genOnOff","data":{"onOff":0}}' of device 'outlet' (0x286d970001051d63)
Feb 17 21:17:12 raspz2m npm[3792]: #033[33m  zigbee2mqtt:warn#033[39m 2/17/2019, 9:17:12 PM No converter available for 'IM6001-OTP05' with cid 'genOnOff', type 'attReport' and data '{"cid":"genOnOff","data":{"onOff":0}}'
Feb 17 21:17:12 raspz2m npm[3792]: #033[33m  zigbee2mqtt:warn#033[39m 2/17/2019, 9:17:12 PM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
Feb 17 21:17:13 raspz2m npm[3792]: #033[34m  zigbee2mqtt:debug#033[39m 2/17/2019, 9:17:13 PM Received zigbee message of type 'devChange' with data '{"cid":"genOnOff","data":{"onOff":0}}' of device 'outlet' (0x286d970001051d63)
Feb 17 21:17:13 raspz2m npm[3792]: #033[33m  zigbee2mqtt:warn#033[39m 2/17/2019, 9:17:13 PM No converter available for 'IM6001-OTP05' with cid 'genOnOff', type 'devChange' and data '{"cid":"genOnOff","data":{"onOff":0}}'
Feb 17 21:17:13 raspz2m npm[3792]: #033[33m  zigbee2mqtt:warn#033[39m 2/17/2019, 9:17:13 PM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.

I added this to the `devices.js` file:

    {
        zigbeeModel: ['outlet'],
        model: 'IM6001-OTP05',
        vendor: 'Samsung',
        description: 'Smartthings Outlet',
        supports: 'on/off',
        fromZigbee: [],
        toZigbee: [],
        configure: (ieeeAddr, shepherd, coordinator, callback) => {
                const device = shepherd.find(ieeeAddr, 1);
                const cfg = {direction: 0, attrId: 0, dataType: 16, minRepIntval: 0, maxRepIntval: 1000, repChange: 0};
                            const actions = [
                                                    (cb) => device.bind('genOnOff', coordinator, cb),
                                                    (cb) => device.foundation('genOnOff', 'configReport', [cfg], foundationCfg,     cb),    
                                                ];    
    
                    execute(device, actions, callback);
        },
    },

but now stuck on what to add to `toZigbee.js` to control the device... status updates I think I figured out!

**Comment by marc-gist** [comment]
Well, solved my own question: please check and see if i did this right (sorry, didn't do in git forked  yet, please add from here if you are willing).

**devices.js**

    // smartthings
    {
        zigbeeModel: ['outlet'],
        model: 'IM6001-OTP05',
        vendor: 'Samsung',
        description: 'Smartthings Outlet',
        supports: 'on/off',
        fromZigbee: [fz.samsung_outlet, fz.samsung_outlet_report],
        toZigbee: [tz.samsung_on_off],
        configure: (ieeeAddr, shepherd, coordinator, callback) => {
                const device = shepherd.find(ieeeAddr, 1);
                const cfg = {direction: 0, attrId: 0, dataType: 16, minRepIntval: 0, maxRepIntval: 1000, repChange: 0};
                            const actions = [
                                                    (cb) => device.bind('genOnOff', coordinator, cb),
                                                    (cb) => device.foundation('genOnOff', 'configReport', [cfg], foundationCfg, cb),
                                                ];

                    execute(device, actions, callback);
        },
    },


**fromZigbee.js**

    samsung_outlet: {
                cid: 'genOnOff',
                type: 'devChange',
                convert: (model, msg, publish, options) => {
                        //console.log(msg.data);
                        return {state: msg.data.data.onOff === 1 ? 'ON' : 'OFF'};
                },
        },
        samsung_outlet_report: {
                cid: 'genOnOff',
                type: 'attReport',
                convert: (model, msg, publish, options) => {
                        return;
                },
        },

**toZigbee.js**

    samsung_on_off: {
    key: ['state'],
    convert: (key, value, message, type, postfix) => {
        const cid = 'genOnOff';
        const attrId = 'onOff';

        let state = value.toLowerCase();
        if (state === 'on' ) {
                state = 1;
        } else if ( state === 'off' ) {
                state = 0;
        } else {
                return;
        }

        if (type === 'set') {
            if (typeof value !== 'string') {
                return;
            }

            return {
                cid: cid,
                cmd: state,
                cmdType: 'functional',
                zclData: {
                },
                cfg: cfg.default,
            };
        } else if (type === 'get') {
            return {
                cid: cid,
                cmd: 'read',
                cmdType: 'foundation',
                zclData: [{attrId: zclId.attr(cid, attrId).value}],
                cfg: cfg.default,
                };
            }
        },
    },    

So "get" doesn't do anything... not sure why, but do i care?

**Comment by marc-gist** [comment]
added pull request on cleaned up code and fork. https://github.com/Koenkk/zigbee-shepherd-converters/pull/286

**Comment by marc-gist** [comment]
An issue I found... seems as though the plug doesn't act as a router, even though its labeled as one in the logs and on the admin.  If i fetch a network map it shows as **offline**

**Comment by Koenkk** [comment]
@marc-gist that online/offline state is not accurate, if you can control the device, you can ignore this.
