### ISSUE TITLE
GL-C-007S no white led on RGBW, only RGB

### ISSUE THREAD

**Issue by igorgoc** [Koenkk/zigbee-herdsman-converters#2874]
I just buy new GLEDOPTO RGBW controller GL-C-007S and  I cannot set up only white LED, always it work in RGB mode.
I see in devices.js that GL-C-007S doesn't have a support for colortemp.
I think that `extend: gledoptoExtend.light_onoff_brightness_colorxy(),`
should be changed to `extend: gledoptoExtend.light_onoff_brightness_colortemp_colorxy(),`

I can sh to docker image and change it in devices.js but next time after restart it is again default value. I am not a progarmmer :)
using it on pure hass os as zigbe2mqtt addon.

**Comment by Koenkk** [comment]
>  can sh to docker image and change it in devices.js but next time after restart it is again default value.

If you restart the container with `docker restart CONTAINER_ID` instead of via Home Assistant changes should be persisted.

**Comment by igorgoc** [comment]
Yes it work, so I add:
`extend: gledoptoExtend.light_onoff_brightness_colortemp_colorxy(),`
in devices.js under GL-C-007S.
Now I have TEMP GUI in home assistant LED window.
You can change it in further release.

**Comment by igorgoc** [comment]
it should be :
```
zigbeeModel: ['GL-C-007S'],
        model: 'GL-C-007S',
        vendor: 'Gledopto',
        description: 'Zigbee LED Controller RGBW (plus)',
        extend: preset.gledopto.light_onoff_brightness_colortemp_colorxy(),
```

**Comment by Koenkk** [comment]
Added. 
Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
