### ISSUE TITLE
Replacing a TI Dev Board CC1352-P2 with the Slaesh CC2653RB, will I need to re-pair ?

### ISSUE THREAD

**Issue by TheStigh** [Koenkk/zigbee-herdsman-converters#2875]
Hi,

Just received my Slaesh CC2653RB.
Do have the TI Dev Board CC1352-P2.

When replacing the adapter, will I need to re-pair or should this go without any hickup ?

**Comment by Koenkk** [comment]
It does not require repairing just plug and go: https://www.zigbee2mqtt.io/information/FAQ.html#what-does-and-does-not-require-repairing-of-all-devices
