### ISSUE TITLE
Xiaomi/Honeywell smoke detector does not handle ALARM_2

### ISSUE THREAD

**Issue by froogl** [Koenkk/zigbee-herdsman-converters#2889]
When testing my Xiaomi smoke detector I have discovered that ALARM_2 (zonestatus 2) is currently not handled by any of the IAS-related conververs. For the Xiaomi smoke detector the following code in `fz.ias_smoke_alarm_1` is used:

```javascript
const zoneStatus = msg.data.zonestatus;
return {
    smoke: (zoneStatus & 1) > 0,
    tamper: (zoneStatus & 1<<2) > 0,
    battery_low: (zoneStatus & 1<<3) > 0,
    supervision_reports: (zoneStatus & 1<<4) > 0,
    restore_reports: (zoneStatus & 1<<5) > 0,
    trouble: (zoneStatus & 1<<6) > 0,
    ac_status: (zoneStatus & 1<<7) > 0,
    test: (zoneStatus & 1<<8) > 0,
};
```
As you can see a `zoneStatus` of ``1<<1`` is not handled at all. The big question is how to handle this. DeCONZ for example triggers the alarm for both ALARM_1 and ALARM_2 and does not distinguish between the two (see https://github.com/dresden-elektronik/deconz-rest-plugin/blob/16bd742c6fd67154cc8110fee4d9515c75c0508e/ias_zone.cpp#L465). I think we could just copy that behavior. This would mean:

```javascript
smoke: (zoneStatus & 1) > 0 || (zoneStatus & 1<<1) > 0,
```

@Koenkk Should we copy the deCONZ behavior or should we introduce an entirely new attribute for "ALARM_2"? I can send you a PR for the `fz.ias_smoke_alarm_1` converter, as this is the one I can test. But basically all converters for IAS zones are affected by this and maybe you would like to fix them all at the same time.

**Comment by froogl** [comment]
Ahh, I get it. Sorry for the fuzz. For some devices there is e.g. `ias_gas_alarm_1` and `ias_gas_alarm_2` which refer to a different zonestatus.

But what should we do with devices which use both alarm_1 and alarm_2, such as the Xiaomi smoke detector?

**Comment by Koenkk** [comment]
It depends on wether the device uses alarm 1 or 2 (or both? but I haven't seen that yet). Does the xiaomi smoke sensor use alarm 2?

**Comment by froogl** [comment]
> It depends on wether the device uses alarm 1 or 2 (or both? but I haven't seen that yet). Does the xiaomi smoke sensor use alarm 2?

When I press the test button the device emits alarm 2. I have not tested this with real smoke yet, I hope the person who integrated that device actually tested that. So my _guess_ is that alarm 1 is actual smoke and alarm 2 is the test mode.

But as I said deCONZ triggers the alarm for both alarm_1 and alarm_2. I am still undecided whether this is good or not.

**Comment by Koenkk** [comment]
@froogl once you figured out what `alarm_2` actually is, I suggest to create a new fromZigbee converter based on `ias_smoke_alarm_1` which also exposes alarm 2 like: `test_button_pressed`.

**Comment by Rockman18** [comment]
@Koenkk : why create so much converters for IAS devices where the standard is a simple generic structure with alarm1 and alarm2 ? All IAS devices could share the generic structure and expose all standard fields. 
Alarm1 and Alarm2 are specified according to the device type as describe in the following table.
![image](https://user-images.githubusercontent.com/1739183/128885046-12bab1d2-0453-4883-a8bb-9aa8de52103a.png)

**Comment by Koenkk** [comment]
Because not all properties are used for all devices, we only expose the one relevant for each device.

**Comment by froogl** [comment]
@Rockman18 While the standard is pretty clear about this, the implementations in the real world are quite often a bit "special" (sadly). So I think the current approach is okay. Actuall Z2M already defines a common converter e.g. for fire sensors (`ias_smoke_alarm_1`). I was just suggesting to extend that converter to handle both Alarm1 and Alarm2. (I have updated the title of the bug report accordingly).

@Koenkk I have tested the device with a smoke generator. Alarm1 is indeed real smoke, and Alarm2 is test mode. So I'll create a new converter which redefines the `test` property only for that particular Xiaomi smoke detector. Right now that property is always false, even when the smoke detector is actually tested. Is that okay or do you really want to introduce a new property `test_button_pressed`?
