### ISSUE TITLE
Zemismart ZM-RM02

### ISSUE THREAD

**Issue by daniral** [Koenkk/zigbee-herdsman-converters#2906]
Please add this device:

https://aliexpress.ru/item/1005002616816639.html?srcSns=com.sec.android.app.sbrowser&spreadType=socialShare&bizType=ProductDetail&social_params=60085219143&aff_fcid=0000616dbfee4b24b1fb42de0dd8ada1-1628160261202-07493-_uQfauC&tt=MG&aff_fsk=_uQfauC&aff_platform=default&sk=_uQfauC&aff_trace_key=0000616dbfee4b24b1fb42de0dd8ada1-1628160261202-07493-_uQfauC&shareId=60085219143&businessType=ProductDetail&platform=AE&terminal_id=a80843beb9534822a099b0a1f4690ed4

`warn 2021-08-13 19:14:34: Received message from unsupported device with Zigbee model 'TS0601' and manufacturer name '_TZE200_zqtiam4u'
debug 2021-08-13 19:14:34: Received Zigbee message from '0x0c4314fffe6000c7', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[0,0,0,90],"type":"Buffer"},"datatype":2,"dp":10,"fn":0,"status":0,"transid":46}' from endpoint 1 with groupID 0`

**Comment by DavidFFerreira** [comment]
I have this device, and I will try to do it myself lol

**Comment by qvjester** [comment]
I have one of these devices, did anyone manage to get it working?

**Comment by DavidFFerreira** [comment]
nop, until now no.....I did tryied, but only got 3 buttons to work. this is a very strange control, it dont assume zigbee alliance compliant
