### ISSUE TITLE
Philips Hue wall switch module OTA

### ISSUE THREAD

**Issue by uvjim** [Koenkk/zigbee-herdsman-converters#2916]
Had a couple of errors appear in the logs (Home Assistant add-on) so I enabled debug logging to try and work out which device was causing the error.

Below are the logs... It looks the RDM001 (Philips Hue wall switch module) is having an issue with OTA.

```
debug 2021-08-16 18:39:28: Received Zigbee message from 'Kitchen - Switch', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":1030,"imageType":284,"manufacturerCode":4107}' from endpoint 1 with groupID null
debug 2021-08-16 18:39:28: Check if update available for '0x001788010b00092d' (RDM001)
error 2021-08-16 18:39:28: Failed to call 'OTAUpdate' 'onZigbeeEvent' (AssertionError [ERR_ASSERTION]: No image available for imageType '284'
    at getImageMeta (/app/node_modules/zigbee-herdsman-converters/lib/ota/zigbeeOTA.js:22:5)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at isNewImageAvailable (/app/node_modules/zigbee-herdsman-converters/lib/ota/common.js:265:18)
    at Object.isUpdateAvailable (/app/node_modules/zigbee-herdsman-converters/lib/ota/common.js:256:23)
    at OTAUpdate.onZigbeeEvent (/app/lib/extension/otaUpdate.js:52:31)
    at Controller.callExtensionMethod (/app/lib/controller.js:408:58)
    at Controller.onZigbeeEvent (/app/lib/controller.js:280:24))
info  2021-08-16 18:39:28: MQTT publish: topic 'zigbee2mqtt/Kitchen - Switch', payload '{"action":null,"battery":100,"device":{"applicationVersion":9,"dateCode":"20210115","friendlyName":"Kitchen - Switch","hardwareVersion":3,"ieeeAddr":"0x001788010b00092d","manufacturerID":4107,"manufacturerName":"Signify Netherlands B.V.","model":"929003017102","networkAddress":23621,"powerSource":"Battery","softwareBuildID":"1.0.3","stackVersion":2,"type":"EndDevice","zclVersion":2},"device_mode":"single_rocker","last_seen":"2021-08-16T17:39:28.360Z","linkquality":255}'
debug 2021-08-16 18:39:34: Received Zigbee message from 'Kitchen - Switch', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":1030,"imageType":284,"manufacturerCode":4107}' from endpoint 1 with groupID null
info  2021-08-16 18:39:34: MQTT publish: topic 'zigbee2mqtt/Kitchen - Switch', payload '{"action":null,"battery":100,"device":{"applicationVersion":9,"dateCode":"20210115","friendlyName":"Kitchen - Switch","hardwareVersion":3,"ieeeAddr":"0x001788010b00092d","manufacturerID":4107,"manufacturerName":"Signify Netherlands B.V.","model":"929003017102","networkAddress":23621,"powerSource":"Battery","softwareBuildID":"1.0.3","stackVersion":2,"type":"EndDevice","zclVersion":2},"device_mode":"single_rocker","last_seen":"2021-08-16T17:39:34.572Z","linkquality":255}'
debug 2021-08-16 18:39:40: Received Zigbee message from 'Kitchen - Switch', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":1030,"imageType":284,"manufacturerCode":4107}' from endpoint 1 with groupID null
info  2021-08-16 18:39:40: MQTT publish: topic 'zigbee2mqtt/Kitchen - Switch', payload '{"action":null,"battery":100,"device":{"applicationVersion":9,"dateCode":"20210115","friendlyName":"Kitchen - Switch","hardwareVersion":3,"ieeeAddr":"0x001788010b00092d","manufacturerID":4107,"manufacturerName":"Signify Netherlands B.V.","model":"929003017102","networkAddress":23621,"powerSource":"Battery","softwareBuildID":"1.0.3","stackVersion":2,"type":"EndDevice","zclVersion":2},"device_mode":"single_rocker","last_seen":"2021-08-16T17:39:40.736Z","linkquality":255}'
```

**Comment by Koenkk** [comment]
Thanks, disabled it (we don't have the images for this device).

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by SkyhawkXava** [comment]
Hello @Koenkk,

It looks like there has also been a firmware update for the “Philips/Signify Hue Wall Switch” in the revisions “RDM001” and “RDM004.”
- [https://www.philips-hue.com/en-us/support/release-notes/accessories](url)
- [https://github.com/Koenkk/zigbee2mqtt/issues/19941#issuecomment-2677086992](url)

On my Hue Wall Switches RDM004, which I bought last year, the firmware version 2.60.16 (firmware date: 20220510) is still installed. The current firmware now appears to be version 2.77.35 (firmware date: 20240618).

Is there any possibility that Z2M could offer an OTA firmware update for the Hue Wall Switches?

**Comment by Koenkk** [comment]
@TheJulianJES do we have these fws?

**Comment by TheJulianJES** [comment]
Yeah, we should have all images, including for accessories.

Image type 284 is already in the OTA repo now, so OTAs can be reenabled for this.

**Comment by TheJulianJES** [comment]
No, if the newer revision requests a different image type compared to the old revision when it's fully up-to-date, then it's not possible. (The requested image type will change for some firmware versions.)

**Comment by Pferdebockwurst** [comment]
> No, if the newer revision requests a different image type compared to the old revision when it's fully up-to-date, then it's not possible. (The requested image type will change for some firmware versions.)

I see, thanks. Anyway, the update for the RDM001 might have unwanted consequences for some users, as the functionality is very different when binding this module to a lamp. The old firmware sends a toggle command, the new firmware sends on/off.

As we don't have the firmware images for prior versions (1.0.3 and 1.0.5) it's not possible to return to the old behaviour once the modules are updated. Or is there a way to get these images? Or wouldn't we be able to flash it anyway, because downgrading is not possible?

**Comment by TheJulianJES** [comment]
>  the update for the RDM001 might have unwanted consequences for some users, as the functionality is very different when binding this module to a lamp. The old firmware sends a toggle command, the new firmware sends on/off.

Ah, yeah. It's not an issue when using the Philips Hue Bridge, as you can't bind the remotes directly to lights there. The Bridge deals with everything. These commands are only intended to be used if an individual bulb is paired directly with a remote (no bridge or coordinator). Then, it doesn't matter if it's toggle or on/off, as there's only one remote that can control the bulb.

The only update file that exists for the first revision (with type 284) is the one that's in the repo. So if there's indeed breaking functionality, we may not want to enable updates for that device.
