### ISSUE TITLE
ssIasZone enrollment

### ISSUE THREAD

**Issue by dlashua** [Koenkk/zigbee-herdsman-converters#292]
Currently, enrollment commands are all over devices.js and they look like this:

````
                (cb) => device.write('ssIasZone', 'iasCieAddr', coordinator.device.getIeeeAddr(), cb),
                (cb) => device.functional('ssIasZone', 'enrollRsp', {
                    enrollrspcode: 1,
                    zoneid: 23,
                }, cb),
````

The issue is that this is not exactly correct. While it works in many cases, with two devices I'm attempting to write handlers for, it does not. 

The correct process for enrollment is as follows:

1) CIE sets iasCieAddr in ssIasZone on Zone Device.
2) Zone Device responds with a devChange indicating the change has taken place.
3) (optional) Zone Device sends an Enrollment request to the CIE
4) CIE sends an Enrollment Response indicating zoneID

The issue with the way this is being handled currently is that we are not waiting for step 2. If the device, like mine, takes a particularly long time to set the IEEE address or there are network issues, then when step 4 occurs, the Zone Device does not regard the CIE as authoritative and therefore does not respond to the Enroll Response being sent. 

I don't see an easy way to handle the "waiting" portion with the current infrastructure. I've tried something like this, but it doesn't seem to work. 

````
    device_ssIasZone_devChange: {
      cid: 'ssIasZone',
      type: 'devChange',
      convert: (model, msg, publish, options) => {
        console.log("ssIasZone devChange",msg.data);
        if('iasCieAddr' in msg.data.data) {
          msg.endpoints.functional('ssIasZone', 'enrollRsp', {
                    enrollrspcode: 1,
                    zoneid: 23,
                }, (cb) => console.log(cb));
        }
      }
````

**Comment by Koenkk** [comment]
As a hacky solution, we could increase the delay between the commands, this is an optional fourth argument that can be provided to the `execute` function, can you e.g. set this to `5000` and check if it works?

**Comment by dlashua** [comment]
I've tried it as high as 10000 and it still didn't work.

But... I think I found another issue that, when resolved, allows this to work okay with the assumptions in place. The issue (in zigbee2mqtt) that the "configure" function runs multiple times during devIncoming, so I think the enrollmentResponse is being sent in a time not appropriate for when the multiple attempts to set iasCieAddr are firing. I've made some changes to deviceConfigure.js and if they pan out, I'll send you a PR.

**Comment by ramzanucar** [comment]
Can you share deviceConfiguration.js if you fix? I have same problem.

**Comment by arnidohome** [comment]
> I've tried it as high as 10000 and it still didn't work.
> 
> But... I think I found another issue that, when resolved, allows this to work okay with the assumptions in place. The issue (in zigbee2mqtt) that the "configure" function runs multiple times during devIncoming, so I think the enrollmentResponse is being sent in a time not appropriate for when the multiple attempts to set iasCieAddr are firing. I've made some changes to deviceConfigure.js and if they pan out, I'll send you a PR.

We are facing with this problem. Can you share your fix ?
