### ISSUE TITLE
Re-Pairing Moes TRV BRT-100 (_TZE200_b6wax7g0)

### ISSUE THREAD

**Issue by Styx85** [Koenkk/zigbee-herdsman-converters#2932]
Hi, got anyone an idea how to repair the Tuya TRV _TZE200_b6wax7g0 (Moes BRT-100)?
I deleted it in zigbee2mqtt because not everything was identified correctly. Now I'd like to repair it but the TRV says it has still a network connection. Instruction manual says pressing the "+" for 3 seconds but as said above this does not work. Any tips how to force that one to forget about previous connection? 
Things I tried:
1. just re-press "+"
2. factory reset
3. removing batteries for 10 minutes

Has anyone had a similar problem?

**Comment by vladi1234** [comment]
Hi there,
Long press "-" for 3 sec. Is zigbee paring.

not "+"

"+" for 3sec. is boost heating.

**Comment by vladi1234** [comment]
Have you already made firmware updates?

**Comment by Chriserus** [comment]
Hey, I have the same problem. Cannot re-pair my device. I already did a firmware update. Any help in this field? Thanks

**Comment by vladi1234** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/7941#issuecomment-906243509

**Comment by Chriserus** [comment]
Thank you for your answer, and also thank you for all the work regarding this faulty OTA update. My concern now is, that I have 3 thermostats: unfortunately all of them got the OTA update. I'm only worried that I somehow "bricked" one of them, by deleting it from my z2m, as I can't re-pair it anymore, can't even get it into the pairing mode. Still investigating

**Comment by davrodfer** [comment]
I have 3 thermostats with the zigbee chip dead after an ota update. The thermostats runs as expected for a thermostat, but no longer connecting to zigbee.

If someone have one procedure to relive the devices, please, post the solution here.

Best regards.

**Comment by chilled35** [comment]
Just to add insult to injury....this duff OTA update is STILL being pushed out to Moes BRT-100 TRVs in 2023!

Having spent an age getting Zigbee2MQTT setup in Home Assistant earlier, all was going well being able to control the TRV from HA, then I spotted an update was available for it on the OTA page.  Set about performing that task which took about 40 mins to download/transfer to the device.  It restarted and now I've lost complete control via HA.  Any commands I send, fail after about 5s.  I cannot enter pairing mode on the TRV itself anymore holding the - button down for 3s, it does straight into temperature setting mode and simply holding - down makes the set point tick lower and lower over the time you hold the 'button' down.

Now, having done some digging, I can most likely get this thing opened up and hooked up to one of many D1 Mini ESP8266 boards I have here to have a go at reflashing the device to put the original firmware back in following this guide: https://github.com/Koenkk/zigbee2mqtt/issues/10140

My question is, how on earth is this duff OTA update still be pushed out?

**Comment by vmishurov** [comment]
> Just to add insult to injury....this duff OTA update is STILL being pushed out to Moes BRT-100 TRVs in 2023!

Yesterday my new TRV was update and... dead. Now TRV not zigbee device :(

**Comment by vladi1234** [comment]
Hello @mishurov, which z2m version do you have?

**Comment by vmishurov** [comment]
> Hello @vmishurov , which z2m version do you have?

1.30.4-1

**Comment by chilled35** [comment]
> Hello @vmishurov , which z2m version do you have?

And just in case you wanted to know what version I'm running, since I reported this issue a few weeks ago, its: 1.30.4-1 

Z2M continually reports to me there's an outstanding update for my Moes TRV.

**Comment by vladi1234** [comment]
I had had 1.30.3 and yesterday I made update to 1.30.4 and tested both versions. 

Result:
No update is offered for my TRV Moes TRV BRT-100 _TZE200_b6wax7g0 

So I can not confirm Wrong update effect. 
We fixed the wrong update on 26.08.2021.
I can not imagine how TRV got update, because there is no update for TRV.

Maybe @Koenkk  questions?

**Comment by vmishurov** [comment]
I ordered a new TRV. When I get it and connect it to z2m, I'll take a screenshot of the OTA page.

**Comment by vladi1234** [comment]
![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/45510877/c12a9789-7eaa-44d3-bedc-0e49776e5d4b)

![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/45510877/65d5841e-fa96-4861-8ed2-f4a9ed146f3b)


I don't have an update.

**Comment by vmishurov** [comment]
Maybe not all BRT-100s are "TZE200_b6wax7g0".
Maybe some have a different name...

**Comment by vladi1234** [comment]
![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/45510877/2e41243a-20c1-4c73-87b2-483bafcfce39)

**Comment by vmishurov** [comment]
The same version of z2m, the same device.
Why is there an update in one case and not in the other???
I have no ideas.

**Comment by vladi1234** [comment]
Can someone try deleting TVR and then make new parring?

**Comment by vmishurov** [comment]
You can see which update is found (version) on the device "State" page.
For example, for a Tuya outlet, I see:
`"update": {
        "installed_version": 192,
        "latest_version": 192,
        "state": "idle"
    },
    "update_available": false,`

**Comment by vladi1234** [comment]
![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/45510877/c72481f1-208f-447d-8dff-c2b0a53ce0bc)

Can anyone watch appVersion?

I have appVersion: 64

**Comment by chilled35** [comment]
"running_state": "idle",
    "system_mode": "heat",
    "update": {
        "installed_version": 67,
        "latest_version": 192,
        "state": "available"
    },
    "valve_state": "CLOSED",

Looks like the TRV I have here has an 'old' 67 version...the issue was however, the device sharing the same ident as another valve which *does* require this 192 update.  When we apply the 192, it bricks the zigbee interface.

**Comment by vladi1234** [comment]
"update": {
        "installed_version": -1,
        "latest_version": -1,
        "state": null
    },

**Comment by vmishurov** [comment]
> yesterday my two new BRT-100-TRV's were broken after the wrong OTA update (fw version from 67 to 192)...
> Is it still possible to revive them somehow? :(

Sorry. I ruined one device with this firmware.
The problem is already two years old, but for some reason the author does not fix it :(

**Comment by topperuk** [comment]
Yup - and i've done one today.. This issue is still live..

**Comment by pnewbery** [comment]
I think I may be suffering the same problem, although I'm using the Smartlife app as per the user guide which came with the devices of which I have 11. They were all working fine, but now I find I can no longer control them in any way from Smartlife, although they do seem to be reporting their details OK. As far as I am aware, no device updates have been applied. I removed one of the TRVs from Smartlife, but now the app will not re-pair with it. I have rebooted the phone and uninstalled / re-installed the app with no effect. In desperation, I have ordered a Sonoff USB3 MQTT adapter and will be installing Mosquitto on a Linux server to try and diagnose things further. Any help will be appreciated.

**Comment by almirus** [comment]
1) press "-" and "menu" about 3 sec at the same time
2) after "A1" was displayed, press "menu" until it appears "AE"
3) press "+", then a number will appear 01
4) remove battery

**Comment by rj2s** [comment]
Hi Almirus,
I try your procedure, wait 10 min, restart, go the F1 - F2 ... then press + 3sec until zigbee-net display (but not flashing) when my zigbee was in inluding mode... but mothing was discover....
Any idea ?
Reagrds,
Roland

**Comment by almirus** [comment]
@rj2s need to hold "minus"
