### ISSUE TITLE
Sonoff S26R2ZB smart plug

### ISSUE THREAD

**Issue by cracrama** [Koenkk/zigbee-herdsman-converters#2978]
Hi all
I'm fairly new with Zigbee2Mqtt so please have mercy.:) I'm trying to add new device using standard template for switch
but unfortunately it's still unsupported
( Link to device: https://itead.cc/product/sonoff-s26r2zb-zigbee-smart-plug-uk-de-fr/ )
I have configured it as below

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['S26R2ZB'],
    model: 'S26R2ZB',
    vendor: 'Sonoff',
    description: 'Sonoff zigbee switch',
    fromZigbee: [fz.on_off],
    toZigbee: [tz.on_off],
    exposes: [e.switch()],
    // The configure method below is needed to make the device reports on/off state changes
    // when the device is controlled manually through the button on it.
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff']);
        await reporting.onOff(endpoint);
    },
};

module.exports = definition;

I have removed this: const extend = require('zigbee-herdsman-converters/lib/extend');
because it was preventing Z2M from starting. 
Now it's starting, converter is added in config but it's still unsupported.
What else can I try?
Is it possible to add support for mentioned device?
Please advise.

**Comment by danieledwardgeorgehitchcock** [comment]
It may be that the Sonoff device does not support report binding for its on/off state.

You won't need a reference to the extend library anyway as you are not using it.

Also, please try to use device fingerprints wherever possible to avoid potential clashes with other devices.

Please try the below:

```javascript
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    fingerprint: [{modelID: 'S26R2ZB', manufacturerName: 'Sonoff'}],
    model: 'S26R2ZB',
    vendor: 'Sonoff',
    description: 'Sonoff zigbee switch',
    fromZigbee: [fz.on_off],
    toZigbee: [tz.on_off],
    exposes: [e.switch()],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff']);
    },
};

module.exports = definition;
```

**Comment by cracrama** [comment]
So i have tried your code and after some weird behaviours it  works !!! :) Many thanks- Device exposing on/off switch. However when I'm trying to toggle switch i experiencing delays or erratic behaviours. Is it possible that its issue with link quality? because log shows:

Error Publish 'set' 'state' to 'Heater' failed: 'Error: Command 0x00124b0024c1028c/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 32961 - 1 - 73 - 6 - 11 after 10000ms)'
Error Publish 'set' 'state' to 'Heater' failed: 'Error: Command 0x00124b0024c1028c/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 32961 - 1 - 74 - 6 - 11 after 10000ms)'
 
anyway many thanks for help i will also try  to sort oout fingerprint issue. 
Best regards

**Comment by cracrama** [comment]
OK switch works - after longer testing it seems like it's issue with link quality. (suprisingly weak antenna on the device, or i having some interfernece issues) Anyway seems OK now. Many thanks for assistance and support. Best regards.
