### ISSUE TITLE
Add model 3RDS17BZ to devices/third_reality.js

### ISSUE THREAD

**Issue by RMCob** [Koenkk/zigbee-herdsman-converters#3013]
I have created a model specific converter file that works but don't know how to do a Pull Request, etc. 
[3RDS17BZ.js.txt](https://github.com/Koenkk/zigbee-herdsman-converters/files/7145935/3RDS17BZ.js.txt)

Thanks!

**Comment by Koenkk** [comment]
Has just been added in https://github.com/Koenkk/zigbee-herdsman-converters/pull/3008
