### ISSUE TITLE
人体存在传感器--雷达波

### ISSUE THREAD

**Issue by bbzcx** [Koenkk/zigbee-herdsman-converters#3045]
有没有人做过关于人体存在传感器的，想接入z2m，弄了半天也不行

**Comment by MattWestb** [comment]
Google translate:
>Has anyone done anything about the human presence sensor, and want to connect to z2m, but it won’t work for a long time

**Comment by bbzcx** [comment]
我也有人体存在传感器，但是目前无法接入，没有找到合适案例

**Comment by bbzcx** [comment]
求官方更新个涂鸦人体存在的实例

**Comment by Bartekn86** [comment]
english please

**Comment by bbzcx** [comment]
Request official update Tuya human presence sensor。I have Tuya human presence sensor, but I don't know how to access it。
