### ISSUE TITLE
Typo 'TTRADFRI'

### ISSUE THREAD

**Issue by stefanfr** [Koenkk/zigbee-herdsman-converters#3046]
Hi,

I just noticed a small typo in one of the new additions:
https://github.com/Koenkk/zigbee-herdsman-converters/blob/920b236d54ff90126e271437e5734e0e93f26875/devices/ikea.js#L603

**Comment by Koenkk** [comment]
Added in https://github.com/Koenkk/zigbee-herdsman-converters/pull/3025 by @brhahlen, can you check this?

**Comment by alexwala** [comment]
pr open : fix typo in TRADFRIbulbGU10WS345lm #3047

**Comment by brhahlen** [comment]
Woops! Sorry about that, had it correct in my .js file, but apparently did a copy-paste thing...
Thanks for the spot @stefanfr 

@Koenkk The PR can be merged.
