### ISSUE TITLE
Wrong state and up/down position for K4027C

### ISSUE THREAD

**Issue by blackwiz4rd** [Koenkk/zigbee-herdsman-converters#3052]
Hi,
I am facing some problems with the current configuration in zigbee2mqtt for K4027C. In particular, the  arrows are not properly working in home assistant (the position of the shutter for opening, closing and state reporting is wrong).

As I had reported some time ago in https://github.com/Koenkk/zigbee-herdsman-converters/issues/1057, https://github.com/Koenkk/zigbee-herdsman-converters/issues/2719, the position when the shutter is open is 50, not 0, while the position when it is closed is 100 (probably this only stands for shutters with older firmware and `bticino_4027C_cover_position` flag):

For closing:
```
mosquitto_pub -h 127.0.0.1 -t zigbee2mqtt/shutter_xxx/set -m "{\"position\": \"100\"}"
```
For opening:
```
mosquitto_pub -h 127.0.0.1 -t zigbee2mqtt/shutter_xxx/set -m "{\"position\": \"50\"}"
```
For stopping:
```
mosquitto_pub -h 127.0.0.1 -t zigbee2mqtt/shutter_xxx/set -m "{\"state\": \"stop\"}"
```

I think the behaviour of ``bticino_4027C_binary_input_moving`, bticino_4027C_cover_state` and `bticino_4027C_cover_position` in `converters/toZigbee.js` is incorrect. Could you give some help on how to fix it based on those opening/closing commands?

From what I understand, the `bticino_4027C_cover_state` reports as a state: 100 when opening, 0 when closing and 50 otherwise. 
When `no_position_supported` is set in `bticino_4027C_cover_position`, the new position will be 100 if the value is above 50 and 0 if it is below 50.

Relevant files:
- https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/bticino.js
- https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/converters/toZigbee.js (bticino_4027C_cover_state, bticino_4027C_cover_position)

Thanks.

**Comment by PxPert** [comment]
I'm sorry, The only way I'm currently aware to update the firmware is by using bTicino Gateway. So you should find a gateway, bind the device to it, update, and the rebind the device with zigbee2mqtt. Don't know if there are other ways for these devices

**Comment by blackwiz4rd** [comment]
> I'm sorry, The only way I'm currently aware to update the firmware is by using bTicino Gateway. So you should find a gateway, bind the device to it, update, and the rebind the device with zigbee2mqtt. Don't know if there are other ways for these devices
Hi, thanks for your answer. Here is the firmware version from `database.db`. Can you compare it with your friend's version?
"swBuildId":"00b\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 \u0002\u0000\u0001\u0000 \u0002\u0000\u0002\u0000!\u0012\u0000\u0000\u0000\u0000��\u0003\u0000\u0010\u0002\u0001\u0004\u0000\u0018\u0002\u0000��!"
Thanks,
Luca.
