### ISSUE TITLE
EMIZB-132 - wrong divisor for energy (CurrentSummationDelivered)

### ISSUE THREAD

**Issue by svhelge** [Koenkk/zigbee-herdsman-converters#3066]
I have recently gone from using deconz to zigbee2mqtt. I have one issue, the energy consumption is reported incorrectly. 
According to the manual the energy divisor should be 1000 (see ), but it seems to be read as 512 (see content of db below), hence the energyconsumption is way off.  I have an Aid-on meter and I'm using the "Norwegian HAN" interface. 
Is it possible to hardcode the divisor somehow? 

![ZB 2021-09-22 210855](https://user-images.githubusercontent.com/79386304/134406776-24e455ea-8100-4d00-970e-8f0813e87743.png)

Content of db:
{"id":6,"type":"EndDevice","ieeeAddr":"0x0015bc001b0252b1","nwkAddr":24969,"manufId":4117,"manufName":"Develco Products A/S","powerSource":"DC Source","modelId":"EMIZB-132","epList":[1,2],"endpoints":{"1":{"profId":49353,"epId":1,"devId":1,"inClusterList":[3,5,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":83,"inClusterList":[0,3,32,1794,1796,2820],"outClusterList":[3,10,25],"clusters":{"genBasic":{"attributes":{"modelId":"EMIZB-132","manufacturerName":"Develco Products A/S","powerSource":4,"zclVersion":1,"dateCode":"2019-09-11 01:50"}},"haElectricalMeasurement":{"attributes":{"rmsVoltage":2362,"rmsCurrent":49,"rmsVoltagePhB":2365,"rmsCurrentPhB":65535,"rmsVoltagePhC":2361,"rmsCurrentPhC":74,"acVoltageMultiplier":1,"acVoltageDivisor":10,"acCurrentMultiplier":1,"acCurrentDivisor":10}},"seMetering":{"attributes":{"currentSummDelivered":[0,110257210],"instantaneousDemand":1985,"status":0,"divisor":**512**,"multiplier":1,"currentSummReceived":[0,0]}}},"binds":[{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00212effff070a28","endpointID":1},{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x00212effff070a28","endpointID":1}],"configuredReportings":[{"cluster":1794,"attrId":1024,"minRepIntval":5,"maxRepIntval":3600,"repChange":1},{"cluster":1794,"attrId":0,"minRepIntval":5,"maxRepIntval":3600,"repChange":[1,1]},{"cluster":1794,"attrId":1,"minRepIntval":5,"maxRepIntval":3600,"repChange":[1,1]}],"meta":{}}},"dateCode":"2019-09-11 01:50","zclVersion":1,"interviewCompleted":true,"meta":{"configured":9},"lastSeen":1632332761987}

**Comment by Koenkk** [comment]
When `interface_mode` is set to `kaifa_and_kamstrup` `1000` is used (https://github.com/Koenkk/zigbee-herdsman-converters/blob/8a72f19624e07e246a44b82c1d00f81873b523db/converters/toZigbee.js#L2976)

**Comment by svhelge** [comment]
But this is the energy divisor, not the divisor for the current. 
As I understand the code the divisor value is read (https://github.com/Koenkk/zigbee-herdsman-converters/blob/8a72f19624e07e246a44b82c1d00f81873b523db/devices/develco.js#L123) 
When the energy consumption was updated the second time (happens every hour) the faulty value for the energy appeared. I tried to reconfigure the device, and then the divisor value in the database got set to 1000. Since the manual state that the divisor should be 1000 I was looking for a way to enforce 1000 as the divisor.

**Comment by Koenkk** [comment]
Forcing the divisor to a certain value is also possible, example: https://github.com/Koenkk/zigbee-herdsman-converters/blob/8ffb63cd56d00e0617932ec23565eea9ddcbdb67/devices/heiman.js#L359

**Comment by svhelge** [comment]
I believe that forcing the divisor to the value given in the [documentation ](https://www.develcoproducts.com/media/1783/emizb-132-technical-manual-emi-norwegian-han.pdf) is the most robust solution.  I tried to test that by creating my own copy of EMIZB-132 (by adding it as a external convertor), but I got some errors and I was not able to start zigbee2mqtt. Is it actually possible to use my own version of a device file (when the device is already implemented)?

I also found that the power also seems to be incorrectly calculated. I had a look at the zigbee2mqttlog:

**Info** MQTT publish: topic 'zigbee2mqtt/Strømmåler', payload '{"current":10.4,"current_phase_b":null,"current_phase_c":2.9,**"energy":215685.23**,"interface_mode":"norwegian_han","linkquality":223,**"power":5857.42,**"voltage":232.7,"voltage_phase_b":238.8,"voltage_phase_c":235.1}'
**Debug** Received Zigbee message from 'Strømmåler', type 'attributeReport', cluster 'seMetering', data '{"**currentSummDelivered**":[0,**110430840**],"currentSummReceived":[0,0],"**instantaneousDemand":2969**,"status":0}' from endpoint 2 with groupID null

I assumed then that **currentSummDelivered** (debug mode) correspond to **energy** (info mode) and that **instantaneousDemand** correspond to **power**.  The energy should be currentSummDelivered/1000 (but is currentSummDelivered/512), while the power should be corrected with a factor of 512/1000 (verified and compared with the offical meter readings). 

I expected to find activePower in the debug log (haElectricalMeasurement), but could not find it. Is activePower read? (but without being reported in the debug-log?). 

What is the best way to implement this correction? 
And it would be nice to have the reactivePower as well :-)

**Comment by svhelge** [comment]
Should a call to the readMeteringPowerConverterAttributes be included in the configure method of the device?  

https://github.com/Koenkk/zigbee-herdsman-converters/blob/7ff86de8e035e2e262eb9927b85968d89c85a2b3/converters/fromZigbee.js#L582-L583

Link to device description: https://github.com/Koenkk/zigbee-herdsman-converters/blob/8ffb63cd56d00e0617932ec23565eea9ddcbdb67/devices/develco.js#L110

**Comment by Koenkk** [comment]
@svhelge `readMeteringPowerConverterAttributes` will override the divisors again.

**Comment by Koenkk** [comment]
@svhelge when this happens, can you check if another divisor shows up in your data/database.db entry of this device?

**Comment by svhelge** [comment]
Yes, the divisor is now 512, no other changes. 
If I reconfigure the device (in the frontend), the value is back to 1000 in the database. 

`{"id":6,"type":"EndDevice","ieeeAddr":"0x0015bc001b0252b1","nwkAddr":24969,"manufId":4117,"manufName":"Develco Products A/S","powerSource":"DC Source","modelId":"EMIZB-132","epList":[1,2],"endpoints":{"1":{"profId":49353,"epId":1,"devId":1,"inClusterList":[3,5,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":83,"inClusterList":[0,3,32,1794,1796,2820],"outClusterList":[3,10,25],"clusters":{"genBasic":{"attributes":{"modelId":"EMIZB-132","manufacturerName":"Develco Products A/S","powerSource":4,"zclVersion":1,"dateCode":"2019-09-11 01:50"}},"haElectricalMeasurement":{"attributes":{"rmsVoltage":2380,"rmsCurrent":10,"rmsVoltagePhB":2365,"rmsCurrentPhB":65535,"rmsVoltagePhC":2362,"rmsCurrentPhC":36,"acVoltageMultiplier":1,"acVoltageDivisor":10,"acCurrentMultiplier":1,"acCurrentDivisor":10}},"seMetering":{"attributes":{"currentSummDelivered":[0,110525770],"instantaneousDemand":1030,"status":0,"divisor":512,"multiplier":1,"currentSummReceived":[0,0]}}},"binds":[{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00212effff070a28","endpointID":1},{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x00212effff070a28","endpointID":1}],"configuredReportings":[{"cluster":2820,"attrId":1285,"minRepIntval":5,"maxRepIntval":3600,"repChange":1},{"cluster":2820,"attrId":1288,"minRepIntval":5,"maxRepIntval":3600,"repChange":1},{"cluster":1794,"attrId":1024,"minRepIntval":5,"maxRepIntval":3600,"repChange":1},{"cluster":1794,"attrId":0,"minRepIntval":5,"maxRepIntval":3600,"repChange":[1,1]},{"cluster":1794,"attrId":1,"minRepIntval":5,"maxRepIntval":3600,"repChange":[1,1]}],"meta":{}}},"dateCode":"2019-09-11 01:50","zclVersion":1,"interviewCompleted":true,"meta":{"configured":-1161032114},"lastSeen":1632853001021}`

**Comment by Koenkk** [comment]
Can you provide the debug log starting from the point where everything is OK until it starts using the wrong divisor?

See https://www.zigbee2mqtt.io/information/debug.html on how to enable debug logging.

**Comment by svhelge** [comment]
I started zigbee2mqtt with debug enabled, should take an hour
`DEBUG=zigbee-herdsman* npm start > debug-log.txt 2>&1`

**Comment by svhelge** [comment]
@Koenkk , here is the debug file - The wrong value appears at line 497 
`mZigbee2MQTT:info [39m 2021-09-28 20:44:10: MQTT publish: topic 'zigbee2mqtt/Strømmåler'`
[debug.txt](https://github.com/Koenkk/zigbee-herdsman-converters/files/7247314/debug.txt)

**Comment by Koenkk** [comment]
@svhelge seems the device sends the divisor itself:

```js
[34mZigbee2MQTT:debug[39m 2021-09-28 20:44:07: Received Zigbee message from 'Strømmåler', type 'attributeReport', cluster 'seMetering', data '{"divisor":512}' from endpoint 2 with groupID null
```

Following change should immediately correct it: https://github.com/Koenkk/zigbee-herdsman-converters/pull/3099/files

**Comment by svhelge** [comment]
@Koenkk Thanks a lot! 
I have implemented the new code and I will report back later.

**Comment by svhelge** [comment]
It works! 👌
But I still find it strange that the device suddenly (after 1 hour) sends a very binary like dvivisor value (512?). 
The divisor is correct initially, and if I reconfigure the device in the z2m-frontend (after the energy value "doubles) the divisor is correct.

**Comment by Koenkk** [comment]
Thanks, merged the mr, assuming this can be closed now.
