### ISSUE TITLE
please add support for TRADFRIbulbE27WSglobeopal1055lm

### ISSUE THREAD

**Issue by xroperx** [Koenkk/zigbee-herdsman-converters#3072]
Got this from the database.db in zigbe2mqtt
`{"id":31,"type":"Router","ieeeAddr":"0x84fd27fffeb720ab","nwkAddr":54671,"manufId":4476,"manufName":"IKEA of Sweden","powerSource":"Mains (single phase)","modelId":"TRADFRIbulbE27WSglobeopal1055lm","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[0,3,4,5,6,8,768,4096,64599],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"TRADFRIbulbE27WSglobeopal1055lm","manufacturerName":"IKEA of Sweden","powerSource":1,"zclVersion":3,"appVersion":16,"stackVersion":103,"hwVersion":1,"dateCode":"20201111","swBuildId":"1.0.012"}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":16,"stackVersion":103,"hwVersion":1,"dateCode":"20201111","swBuildId":"1.0.012","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1632424645689}`

On the box
Trådfri LED
1055lm
E27
LED2003G10
# 404.867.83

**Comment by xroperx** [comment]
This converter works!
`
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['TRADFRIbulbE27WSglobeopal1055lm'],
    model: 'LED2003G10',
    vendor: 'IKEA',
    description: 'TRADFRI LED bulb E27 1055 lumen, dimmable, white spectrum, clear',
    // Note that fromZigbee, toZigbee and exposes are missing here since we use extend here.
    // Extend contains a default set of fromZigbee/toZigbee converters and expose for common device types.
    // The following extends are available:
    // - extend.switch
    // - extend.light_onoff_brightness
    // - extend.light_onoff_brightness_colortemp
    // - extend.light_onoff_brightness_color
    // - extend.light_onoff_brightness_colortemp_color
    extend: extend.light_onoff_brightness_colortemp_color(),
};

module.exports = definition;
`

**Comment by Koenkk** [comment]
Already supported in the dev branch. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
