### ISSUE TITLE
New device Aqara E1 (WXKG16LM, WXKG17LM)

### ISSUE THREAD

**Issue by EvgenaNet** [Koenkk/zigbee-herdsman-converters#3075]
Hi!
Help me pls to create converter or pull request to adding new device: Aqara E1. WXKG16LM - 1 gang, WXKG17LM - 2 gang wireless switch.
I don't understand how to create converter. No data recived in debug log when created converter and pressed any buttons.
Thx!

![image](https://user-images.githubusercontent.com/60606013/134659931-e320f200-ed7a-4826-8bcd-626ebeffa885.png)

![image](https://user-images.githubusercontent.com/60606013/134659894-b048275d-dee3-401b-bd0b-0f1a41423220.png)

**Comment by GmasteR** [comment]
Up! I look forward to resolving this issue.

**Comment by EvgenaNet** [comment]
I don't believe, that Aqara E1 use only two people... Give us converter config or explain how i can to do it by myself!!! Next code is't helpfull.


```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['lumi.remote.acn003'], // The model ID from: Device with modelID 'lumi.sens' is not supported.
    model: 'WXKG16LM', // Vendor model number, look on the device for a model number
    vendor: 'Xiaomi', // Vendor of the device (only used for documentation and startup logging)
    description: 'Aqara E1 single key wireless wall switch (2021 model)', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
    meta: {battery: {voltageToPercentage: '3V_2100'}},
    exposes: [e.battery(), e.action(['single', 'double', 'hold']), e.battery_voltage()],
	fromZigbee: [fz.xiaomi_battery, fz.xiaomi_on_off_action, fz.xiaomi_multistate_action, fz.xiaomi_action_click_multistate],
    toZigbee: [],
};

module.exports = definition;
```

**Comment by comword** [comment]
I am also looking forward to it. I have a double key version lumi.remote.acn004, WXKG17LM. By enabling debug mode, I can see the following Zigbee message from device when I fast click button for 5 times.

```
Received Zigbee message from, type 'attributeReport', cluster 'genBasic', data '{"modelId":"lumi.remote.acn004"}' from endpoint 1 with groupID 0.
```

But there is no message when single or double click, so I think some additional configuration is required.
I tried some configuration code from similar devices [#2621](https://github.com/Koenkk/zigbee-herdsman-converters/pull/2621), but they are not helpful.

My current code
```JavaScript
const definition = {
    zigbeeModel: ['lumi.remote.acn004'],
    model: 'WXKG17LM',
    vendor: 'Aqara',
    description: 'Aqara E1 double key wireless wall switch (2021 model)',
    meta: {battery: {voltageToPercentage: '3V_2100'}},
    fromZigbee: [fz.xiaomi_on_off_action, fz.xiaomi_multistate_action, fz.xiaomi_battery],
    exposes: [e.battery(), e.action(['single_left', 'single_right', 'single_both', 'double_left', 'double_right', 'double_both',
            'hold_left', 'hold_right', 'hold_both']), e.battery_voltage()],
    toZigbee: [],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint1 = device.getEndpoint(1);
        await endpoint1.write('aqaraOpple', {'mode': 1}, {manufacturerCode: 0x115f});
        await endpoint1.write('aqaraOpple', {0x0125: {value: 0x02, type: 0x20}}, {manufacturerCode: 0x115f});
        await reporting.bind(endpoint1, coordinatorEndpoint, ['genOnOff']);
    },
};
```
Do you have any idea on how figure out the correct configuration code? Like {0x0125: {value: 0x02, type: 0x20}} in another device.

**Comment by z-x-f** [comment]
@EvgenaNet What is the firmware version of your USB stick?

**Comment by EvgenaNet** [comment]
> @EvgenaNet What is the firmware version of your USB stick?

Do you talk about this?

![image](https://user-images.githubusercontent.com/60606013/144979425-a91658ec-f380-450a-b267-90602b176d03.png)

**Comment by z-x-f** [comment]
Emm, I don't know which ZigBee stick you're using, You can check out the support list [here](https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_3.x.0/bin) for your ZigBee stick.
If your ZigBee sticks are on the support list, try upgrading the latest firmware to get support for E1 devices.

**Comment by EvgenaNet** [comment]
> Emm, I don't know which ZigBee stick you're using, You can check out the support list [here](https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_3.x.0/bin) for your ZigBee stick. If your ZigBee sticks are on the support list, try upgrading the latest firmware to get support for E1 devices.

I have this one.

![IMG_20211207_170456_565](https://user-images.githubusercontent.com/60606013/145043500-d1939cf2-143e-404f-a3f2-b9cc788213d9.jpg)

**Comment by z-x-f** [comment]
![egony](https://user-images.githubusercontent.com/31797512/145048090-e275e805-00c9-4b92-99a6-4670b12245b5.PNG)
Confirm which hardware version you have, and then flash the corresponding firmware.

**Comment by EvgenaNet** [comment]
> I have this one.

![20211207_173306](https://user-images.githubusercontent.com/60606013/145048725-d21cf3f5-ad07-4759-a7bb-abf386abda62.jpg)
![20211207_173338](https://user-images.githubusercontent.com/60606013/145048736-c3163bae-04d2-4843-b0fe-4aeb9b53037c.jpg)

**Comment by EvgenaNet** [comment]
> ![egony](https://user-images.githubusercontent.com/31797512/145048090-e275e805-00c9-4b92-99a6-4670b12245b5.PNG) Confirm which hardware version you have, and then flash the corresponding firmware.

Ok. Thanks! Will try later.

**Comment by EvgenaNet** [comment]
> ![egony](https://user-images.githubusercontent.com/31797512/145048090-e275e805-00c9-4b92-99a6-4670b12245b5.PNG) Confirm which hardware version you have, and then flash the corresponding firmware.

I was flashed the corresponding last firmware, but problem was not solved.

**Comment by z-x-f** [comment]
Version 20211114 in the dev branch

**Comment by EvgenaNet** [comment]
> Version 20211207 in the dev branch

Can you give direct link to this file?

**Comment by z-x-f** [comment]
https://github.com/Koenkk/Z-Stack-firmware/raw/develop/coordinator/Z-Stack_3.x.0/bin/CC1352P2_CC2652P_other_coordinator_20211207.zip

**Comment by EvgenaNet** [comment]
> https://github.com/Koenkk/Z-Stack-firmware/raw/develop/coordinator/Z-Stack_3.x.0/bin/CC1352P2_CC2652P_other_coordinator_20211207.zip

Thanx! Now E1 working well, but all other devices impossible to use - they was died )) Only can see they state, but can't to change state.

**Comment by EvgenaNet** [comment]
If other devices reconnect, they working too. But there is 42 devices...

**Comment by EvgenaNet** [comment]
Hmmmm... After 15-20 minutes all devices working well without any manipulations.
