### ISSUE TITLE
please add support for Schwaiger HAL 550 RGBW GU10 Bulb

### ISSUE THREAD

**Issue by stolly82** [Koenkk/zigbee-herdsman-converters#3080]
Hey,

it would be awesome if you can add support for Schwaiger HAL 550 / ZBT-RGBWLight-GU100114.

The bulb by self is this here:
https://www.ebay.de/itm/254781750443

![image](https://user-images.githubusercontent.com/4883692/134734752-2d6afb78-61cb-4420-b7cc-8eeaf5932d3e.png)

![image](https://user-images.githubusercontent.com/4883692/134734816-47a7f498-0285-4d4b-bca4-df6a3a292970.png)

Thanks a lot!

**Comment by danieledwardgeorgehitchcock** [comment]
Hi,

Please could you try the below external converter?

```javascript
const extend = require('zigbee-herdsman-converters/lib/extend');

const definition = {
        fingerprint: [{modelID: 'ZBT-RGBWLight-GU100114', manufacturerName: 'LDS'}],
        model: 'HAL 550',
        vendor: 'Schwaiger',
        description: 'Schwaiger HAL 550 GU10 RGBW bulb',
        extend: extend.light_onoff_brightness_color(),
    };

module.exports = definition;
```

Information on how to add this is [here](https://www.zigbee2mqtt.io/information/configuration.html#external-converters-configuration)

When doing the above, please remove the device from Zigbee2MQTT (if you have it added), restart Zigbee2MQTT after adding the entry to your config, then re-add the device. It may also be worthwhile to enable debug logging to catch any errors / unsupported functions.

If the above works, there is a little bit of a further process of testing certain functions before it can be added into the Zigbee2MQTT codebase.

**Comment by eljoest** [comment]
Hi, I've added this to my install and was able to switch on/off and select the correct colors. I was unable to control the white channel (brightness).

Right now the bulb doesn't want to re-join the network after being removed, I'll have to move it close to the coordinator for a touchlink run. The power 5x on/off-cycle for the factory reset doesn't seem to work.
