### ISSUE TITLE
FLS/AIRLINK/4  2-gang mode

### ISSUE THREAD

**Issue by marn06** [Koenkk/zigbee-herdsman-converters#3087]
Hi

How do you make the FLS/AIRLINK/4 operate in 2-gang mode? I only see on_top, off_top, and is it possible to work as a stateless switch with 4 endpoints?

Code:
https://github.com/Koenkk/zigbee-herdsman-converters/blob/67918aaaa314c02dc49d7429c0e0af728a5bc9ac/devices/schneider_electric.js#L293

**Comment by poizan42** [comment]
@marn06 I don't know if you found a solution, but someone over at the Home Assistant forum figured out how to switch into 2-channel mode without the Elko/Wiser gateway: https://community.home-assistant.io/t/elko-smart-4-button-switch-setup/425226/2

> I was looking for the same and found this: [Schneider Wiser Remote 1](https://community.home-assistant.io/t/schneider-wiser-remote/407990)
    It works perfectly well for me with the Elko smart switch connected with ConBee USB stick. For some reason I had to activate 2-channel mode by pressing button 1 and 4 for 10 seconds.
