### ISSUE TITLE
Mapping Buffer Data Values For Voltage / Current (TuYa)

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [Koenkk/zigbee-herdsman-converters#3094]
Hi,

I am attempting to create a converter for a TuYa RCBO relay device.

I have successfully found the mappings for all of the datapoints with a combination of Zigbee2MQTT debug converters, Zigbee sniffing, and TuYa API probing.

The data point names are as follows:

- 1: "state",
- 9: "countdown timer",
- 26: "fault code",
- 27: "relay status (power recovery behaviour)",
- 29: "child lock",
- 101: "voltage",
- 102: "current",
- 103: "active power",
- 104: "leakage current",
- 105: "temperature",
- 106: "remaining energy",
- 107: "recharge energy",
- 108: "cost parameters",
- 109: "leakage parameters",
- 110: "voltage threshold",
- 111: "current threshold",
- 112: "temperature threshold",
- 113: "total active power",
- 114: "equipment number and type",
- 115: "clear energy",
- 116: "locking (test button pressed)",
- 117: "total reverse active power",
- 118: "historical voltage",
- 119: "historical current"

I have adapted the example python script to output the values for the above datapoints and I am trying to prioritise voltage and current readings.

I have attached what the python script outputs below:
[tuya_mapped_dump.txt](https://github.com/Koenkk/zigbee-herdsman-converters/files/7243153/tuya_mapped_dump.txt)

I have attached the raw data dump from the TuYa converter below:
[tuya.dump.txt](https://github.com/Koenkk/zigbee-herdsman-converters/files/7243403/tuya.dump.txt)

The database.db entry for the device is as follows:
```json
{"id":41,"type":"Router","ieeeAddr":"0x0c4314fffe1a58fb","nwkAddr":6541,"manufId":4098,"manufName":"_TZE200_hkdl5fmv","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"���(\u0013*��(\u0012+��(\u0012","65506":31,"65508":0,"modelId":"TS0601","manufacturerName":"_TZE200_hkdl5fmv","powerSource":1,"zclVersion":3,"appVersion":72,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":72,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1632823810639}
```

Clusters diagram:
![clusters](https://user-images.githubusercontent.com/19694936/135076851-f38083fd-ad15-47cd-8e34-d9937573fff2.png)

I am really struggling to map the values for any of the voltage / current datapoints to any sort of value that makes sense i.e.:

my voltage at home: `~240v`
voltage reported in TuYa app: `~240v to 1 decimal place`
example voltage reported in python script: `[   9 109   0   0   0   0 ]`
example voltages reported in TuYa API:

Time | Device Event | DP ID | Event Details | Source | 
--- | --- | --- | --- | --- |
2021-09-28 11:15:00 | Report | 电压 | CWwAAAAA | device itself |  
2021-09-28 11:14:29 | Report | 电压 | CWUAAAAA | device itself |  
2021-09-28 11:13:58 | Report | 电压 | CW8AAAAA | device itself |  
2021-09-28 11:13:27 | Report | 电压 | CXYAAAAA | device itself |  
2021-09-28 11:12:25 | Report | 电压 | CW4AAAAA | device itself |  
2021-09-28 11:11:54 | Report | 电压 | CWgAAAAA | device itself |  
2021-09-28 11:11:25 | Report | 电压 | CWcAAAAA | device itself |  
2021-09-28 11:03:26 | Report | 电压 | CXEAAAAA | device itself |  
2021-09-28 11:02:55 | Report | 电压 | CXUAAAAA | device itself |  
2021-09-28 11:02:24 | Report | 电压 | CXMAAAAA | device itself |

Any pointers on how to decipher this would be greatly received! @Koenkk..?

**Comment by Koenkk** [comment]
Did you already try using the following function: https://github.com/Koenkk/zigbee-herdsman-converters/blob/60286b1a263166a4a729b0c72b0491c79d95594d/lib/tuya.js#L26 ?

Note sure about this, but the below conversion gives me `2413`, which could be interpreted as 241.3 volt

<img width="273" alt="Screenshot 2021-09-28 at 20 29 25" src="https://user-images.githubusercontent.com/2892853/135145032-f15531ed-73c2-4956-9d64-d24136bf463a.png">

**Comment by danieledwardgeorgehitchcock** [comment]
Thanks!

I was already using the getDataValue() function but, it was the left shift that I was missing!

Is it correct to do what you did above verbatim i.e. just using the first two of the 5 values?

**Comment by Koenkk** [comment]
> Is it correct to do what you did above verbatim i.e. just using the first two of the 5 values?

I'm not sure about this, but if it provides meaningful values I guess it is ok (I don't have experience with the TuYa protocol)
