### ISSUE TITLE
Porpose improvement to tuya_data_point_dump

### ISSUE THREAD

**Issue by Asleep-at-the-wheel** [Koenkk/zigbee-herdsman-converters#3100]
Hello,
I find (currently) that following this procedure [here](https://www.zigbee2mqtt.io/how_tos/how_to_support_new_tuya_devices.html) causes Hassio containers of Z2MQTT to fail because the directory the converter is trying to use doesn't exist (also seen [here](https://github.com/Koenkk/zigbee2mqtt/issues/6292)).

https://github.com/Koenkk/zigbee-herdsman-converters/blob/d7b9aa4d039734bc840b1efa88d6594ea87fc7e5/converters/fromZigbee.js#L3728-L3759

The problem is that `fs.appendFile('data/tuya.dump.txt', dataStr, (err)` breaks the container the second a message comes in. It does work if you change it to `fs.appendFile('/data/tuya.dump.txt', dataStr, (err)` and then `docker exec` into the container to find and dig out the logs. 

Doing this how ever is serious amount of required knowledge for someone who might just be looking to provide some debug data for help or figure out how to add their own device while using Hassio.

So how about a change to the dump point from `data/` to the same directory that Zigbee2MQTT keeps its logs? That way the procedure will work for both Hassio and regular installations? Hassio users can easily copy paste the external converter and copy paste what ever they find to their request for new device post if they can't figure it out themselves.

Or maybe the other solution is to mount the /data/tuya.dump.txt file into some where accessible?

**Comment by Koenkk** [comment]
> So how about a change to the dump point from data/ to the same directory that Zigbee2MQTT keeps its logs? That way the procedure will work for both Hassio and regular installations?

I'm fine with that, could you make a PR?
