### ISSUE TITLE
Converting Sniffed Data To Converter

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [Koenkk/zigbee-herdsman-converters#3102]
Hi,

I have sniffed some traffic between a TuYa device and its native gateway to ascertain how certain app only functions seem to work with the device.

The data points are as follows:

- wdykState: 1
- wdykCountdownTimer: 9
-  wdykFaultCode: 26
- wdykRelayStatus: 27
- wdykChildLock: 29
- wdykVoltage: 101
- wdykCurrent: 102
- wdykActivePower: 103
- wdykLeakageCurrent: 104
- wdykTemperature: 105
- wdykRemainingEnergy: 106
- wdykRechargeEnergy: 107
- wdykCostParameters: 108
- wdykLeakageParameters: 109
- wdykVoltageThreshold: 110
- wdykCurrentThreshold: 111
- wdykTemperatureThreshold: 112
- wdykTotalActivePower: 113
- wdykEquipmentNumberType: 114
- wdykClearEnergy: 115
-  wdykLocking: 116
- wdykTotalReverseActivePower: 117
- wdykHistoricalVoltage: 118
- wdykHistoricalCurrent: 119

I am trying to add a toZigbee converter for `wdykRelayStatus` (which is power on behaviour), `wdykLocking` (which is a device test), and `wdykClearEnergy` (which clears the devices memory of any historical data).

When I sniff the data in wireshark, I can see an unknown command being sent from the gateway to the device and the data for the different commands looks like this:

Power On Behaviour (Off): 00:1C:1B:04:00:01:00
Power On Behaviour: (On): 00:1D:1B:04:00:01:01 
Power On Behaviour (Previous): 00:1B:1B:04:00:01:02
Test: 00:1E:74:01:00:01:01
Clear: 00:38:73:01:00:01:01

In an attempt to decipher the above, it appears that the 3rd value is the data point, the 5th and 6th value always seems to remain the same, and the 7th value is the actual setting.

I have tried sending the commands in various formats from Zigbee2MQTT including using the toZigbee `tuya_data_point_test` converter.

I cannot however, seem to get any of the commands working - I have managed to get other commands working such as setting the `wdykState` data point

Please does anybody have any hints on how to get this going?

**Comment by Koenkk** [comment]
@drzony  could you maybe help with this?

**Comment by drzony** [comment]
There are 2 commands for sending data to TuYa devices 'setData' and 'sendData'. You can try changing tuya_data_point_test, by adding 'sendData' in all the sendData... functions as the 4th parameter.

**Comment by danieledwardgeorgehitchcock** [comment]
Hi @drzony thanks for the above.

I have tried that but still cannot seem to get the device to do anything using the send data command.

For reference, here is my full external converter:

```javascript
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;

const dataPointsLocal = {
    hochState: 1,
    hochCountdownTimer: 9,
    hochFaultCode: 26,
    hochRelayStatus: 27,
    hochChildLock: 29,
    hochVoltage: 101,
    hochCurrent: 102,
    hochActivePower: 103,
    hochLeakageCurrent: 104,
    hochTemperature: 105,
    hochRemainingEnergy: 106,
    hochRechargeEnergy: 107,
    hochCostParameters: 108,
    hochLeakageParameters: 109,
    hochVoltageThreshold: 110,
    hochCurrentThreshold: 111,
    hochTemperatureThreshold: 112,
    hochTotalActivePower: 113,
    hochEquipmentNumberType: 114,
    hochClearEnergy: 115,
    hochLocking: 116,
    hochTotalReverseActivePower: 117,
    hochHistoricalVoltage: 118,
    hochHistoricalCurrent: 119,
};

const tzLocal = {
    hoch_din: {
        key: ['state',
            'child_lock',
            'countdown_timer'
        ],
        convertSet: async (entity, key, value, meta) => {
            if (key === 'state') {
                await tuya.sendDataPointBool(entity, dataPointsLocal.hochState, value === 'ON');
            } else if (key === 'child_lock') {
                await tuya.sendDataPointBool(entity, dataPointsLocal.hochChildLock, value === 'ON');
            } else if (key === 'countdown_timer') {
                await tuya.sendDataPointValue(entity, dataPointsLocal.hochCountdownTimer, value);
            } else {
                throw new Error(`Not supported: '${key}'`);
            }
        },
    },
    tuya_data_point_test_send_data: {
        key: ['tuya_data_point_test_send_data'],
        convertSet: async (entity, key, value, meta) => {
            const args = value.split(',');
            const mode = args[0];
            const dp = parseInt(args[1]);
            const data = [];

            switch (mode) {
            case 'raw':
                for (let i = 2; i < args.length; i++) {
                    data.push(parseInt(args[i]));
                }
                await tuya.sendDataPointRaw(entity, dp, data, 'sendData');
                break;
            case 'bool':
                await tuya.sendDataPointBool(entity, dp, args[2] === '1', 'sendData');
                break;
            case 'value':
                await tuya.sendDataPointValue(entity, dp, parseInt(args[2]), 'sendData');
                break;
            case 'enum':
                await tuya.sendDataPointEnum(entity, dp, parseInt(args[2]), 'sendData');
                break;
            case 'bitmap':
                for (let i = 2; i < args.length; i++) {
                    data.push(parseInt(args[i]));
                }
                await tuya.sendDataPointBitmap(entity, dp, data, 'sendData');
                break;
            }
        },
    },
};

const fzLocal = {
    hoch_din: {
        cluster: 'manuSpecificTuya',
        type: ['commandGetData', 'commandSetDataResponse'],
        convert: (model, msg, publish, options, meta) => {
            const dp = msg.data.dp;
            const value = tuya.getDataValue(msg.data.datatype, msg.data.data);
            meta.logger.debug(`from hoch_din, msg.data.dp=[${dp}], msg.data.datatype=[${msg.data.datatype}], value=[${value}]`);
            switch (dp) {
            case dataPointsLocal.hochState:
                return {'state': value ? 'ON' : 'OFF'};
            case dataPointsLocal.hochChildLock:
                return {'child_lock': value ? 'ON' : 'OFF'};
            case dataPointsLocal.hochVoltage:
                return {'voltage': (value[1] | value[0] << 8) / 10};
            case dataPointsLocal.hochHistoricalVoltage:
                return {'voltage_rms': (value[1] | value[0] << 8) / 10};
            case dataPointsLocal.hochCurrent:
                return {'current': value[2] | value[1] << 8};
            case dataPointsLocal.hochHistoricalCurrent:
                return {'current_rms': value[2] | value[1] << 8};
            case dataPointsLocal.hochActivePower:
                return {'power': (value[2] | value[1] << 8) / 10};
            case dataPointsLocal.hochLocking:
                return {'trip_test': value ? true : false};
            case dataPointsLocal.hochCountdownTimer:
                return {'countdown_timer': value};
            case dataPointsLocal.hochTemperature:
                return {'temperature': value};
            case dataPointsLocal.hochRelayStatus:
                const lookup = {0: 'off', 1: 'on', 2: 'previous'};
                return {'power_on_behaviour': lookup[value]};
            default:
                meta.logger.debug(`zigbee-herdsman-converters:hoch_din:` +
                    `NOT RECOGNIZED DP #${dp} with data ${JSON.stringify(msg.data)}`);
            }
        },
    },
};

const definition = {
    fingerprint: [{modelID: 'TS0601', manufacturerName: '_TZE200_hkdl5fmv'}],
    model: 'TS0601_din',
    vendor: 'TuYa',
    whiteLabel: [
        {vendor: 'HOCH', model: 'ZJSBL7-100Z'},
        {vendor: 'WDYK', model: 'ZJSBL7-100Z'},
    ],
    description: 'DIN mount RCBO with smart energy metering',
    fromZigbee: [fzLocal.hoch_din, fz.ignore_basic_report, fz.tuya_data_point_dump],
    toZigbee: [tzLocal.hoch_din, tzLocal.tuya_data_point_test_send_data, tz.tuya_data_point_test],
    exposes: [
        exposes.binary('state', ea.STATE_SET, 'ON', 'OFF'),
        exposes.binary('child_lock', ea.STATE_SET, 'ON', 'OFF'),
        exposes.numeric('countdown_timer', ea.STATE_SET).withValueMin(0).withValueMax(86400).withUnit('s'),
        exposes.enum('power_on_behaviour', ea.STATE, ['off', 'on', 'previous']),
        exposes.binary('trip_test', ea.STATE, true, false),
        exposes.numeric('voltage', ea.STATE).withUnit('V'),
        exposes.numeric('voltage_rms', ea.STATE).withUnit('V'),
        exposes.numeric('current', ea.STATE).withUnit('mA'),
        exposes.numeric('current_rms', ea.STATE).withUnit('mA'),
        exposes.numeric('power', ea.STATE).withUnit('W'),
        exposes.numeric('temperature', ea.STATE).withUnit('°C')
    ],
};

module.exports = definition;
```

I am trying to send the commands with the following:

MQTT: topic: `zigbee2mqtt/0x0c4314fffe1a58fb/set/tuya_data_point_test_send_data` payload: `value,27,0` 

or

MQTT: topic: `zigbee2mqtt/0x0c4314fffe1a58fb/set/tuya_data_point_test` payload: `value,27,0`

Anything glaringly obvious that I am doing wrong?

**Comment by drzony** [comment]
The structure of TuYa messages is as follows:
```
{name: 'status', type: DataType.uint8},
{name: 'transid', type: DataType.uint8},
{name: 'dp', type: DataType.uint8},
{name: 'datatype', type: DataType.uint8},
{name: 'length_hi', type: DataType.uint8},
{name: 'length_lo', type: DataType.uint8},
{name: 'data', type: BuffaloZclDataType.LIST_UINT8},
```
So to interpret your example:
`00:1C:1B:04:00:01:00` is
status = 0
transid = 1C
dp = 1B
datatype = enum
length = 1
data = 0
So you should send `enum,27,0`
`value` is 4 byte integer

**Comment by danieledwardgeorgehitchcock** [comment]
Ahh! thanks!

I can now set the power on behaviour, but the device test (116) isn't working..

Here are my payloads

topic: `zigbee2mqtt/0x0c4314fffe1a58fb/set/tuya_data_point_test_send_data` payload: `bool,116,1`

or

topic: `zigbee2mqtt/0x0c4314fffe1a58fb/set/tuya_data_point_test` payload: `bool,116,1`

I can upload my sniff if that would be of any use?

**Comment by drzony** [comment]
Try to compare sniff when using z2m and TuYa gateway, maybe the device needs to be in some special state for test (turned on/off, some other setting set) and/or needs some time between commands.

**Comment by danieledwardgeorgehitchcock** [comment]
Thank you,

I have done that now and confirmed that Zigbee2MQTT was doing what I thought it should!

I have re-run the capture on the TuYa network and have now found that the command seems to be a length of 14.

I have run the command 3 times and confirm that this seems to be the one that does it:

Try 1: 003d6d0000080100000019000001
Try 2: 003e6d0000080100000019000001
Try 3: 003f6d0000080100000019000001

The above logic doesn't seem to work with lengths >7 - how could I decode the captured command so that I can send it via Z2M?

**Comment by drzony** [comment]
No, the decode is:
status = 00 (one byte)
transid = 3d (one byte)
dp = 6d (one byte)
datatype = raw (00 - one byte)
length = 8 (00 08 - two bytes)
data = 01 00 00 00 19 00 00 01 (8 bytes)

**Comment by danieledwardgeorgehitchcock** [comment]
Thank you so much!!

I got it firing!! :-)

**Comment by drzony** [comment]
A PR would be welcome for others to use it :)

**Comment by danieledwardgeorgehitchcock** [comment]
> A PR would be welcome for others to use it :)

Getting there! Koenkk/zigbee-herdsman-converters#2962

**Comment by drzony** [comment]
Great 👍
