### ISSUE TITLE
E-Wand stopped working with latest version

### ISSUE THREAD

**Issue by scottpk** [Koenkk/zigbee-herdsman-converters#3122]
Hello - I have the Current Products Corp E-Wand on several of my windows... After updating to 1.21.2-1 they stopped working with Home Assistant. I reverted back to 1.21.1-1 and they started working again. I'm guessing this might have to do with the recent commit #2663 since I see that in the change log.

**Comment by Koenkk** [comment]
@Leah-Anderson could you check this?

**Comment by scottpk** [comment]
To clarify it seemed to work from Zigbee2MQTT directly but not from
Homeassistant which broke my automations

**Comment by Leah-Anderson** [comment]
@Koenkk I should have some more time this weekend to look into this but I can at least confirm it's not working. Basically the buttons in HA don't do anything. With that said if I do post open/close to the right topic in MQTT that device does respond. 

The only thing that stood out is it looks like in the discovery topic it's no longer putting a command topic...so perhaps that's the issue?

**Comment by scottpk** [comment]
I can try later. I am using this for several things, is it easy to switch back? (Do not want to risk having, for example, my wake-up automation to not work 😉) Mine is the hassio install, do I have to uninstall it before installing the "edge" version?

**Comment by Koenkk** [comment]
Yes, you can just switch backup.

> do I have to uninstall it before installing the "edge" version?

yes

**Comment by scottpk** [comment]
Sorry for lack of response... I updated to the latest new version today and the blinds are working fine. Thanks!
