### ISSUE TITLE
ZNJLBL01LM does not report battery condition

### ISSUE THREAD

**Issue by mchynal** [Koenkk/zigbee-herdsman-converters#3126]
![image](https://user-images.githubusercontent.com/2961339/136014082-c0b2049c-d92a-4b9e-81f6-928e85caf8bc.png)

`{
    "last_seen": "2021-10-05T11:23:29.637Z",
    "linkquality": 70,
    "position": 0,
    "running": false
}`

![image](https://user-images.githubusercontent.com/2961339/136013637-4a9bd377-cba6-4a13-bb6f-a660772198ec.png)

**Comment by HenriMatthijssen** [comment]
As this is a battery operated device it would be really helpful that battery level is reported as well.
