### ISSUE TITLE
New Tuya-based gas detector

### ISSUE THREAD

**Issue by ov1d1u** [Koenkk/zigbee-herdsman-converters#3128]
I bought this Tuya Zigbee gas detector: https://www.aliexpress.com/item/1005002328577004.html

It is not recognised by Zigbee2MQTT but I was able to read its state by creating an external converter file and using the `fz.tuya_gas` converter. Yet there are still some DPs which aren't recognised, any idea what they could be? They are received when I'm pressing the test button on the device:

```
debug 2021-10-06 11:44:15: Received Zigbee message from '0x5c0272fffec3648f', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":9,"fn":0,"status":0,"transid":15}' from endpoint 1 with groupID 0
warn  2021-10-06 11:44:15: zigbee-herdsman-converters:tuya_gas: Unrecognized DP #9 with data {"status":0,"transid":15,"dp":9,"datatype":4,"fn":0,"data":{"type":"Buffer","data":[1]}}
debug 2021-10-06 11:44:15: Received Zigbee message from '0x5c0272fffec3648f', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[0],"type":"Buffer"},"datatype":4,"dp":11,"fn":0,"status":0,"transid":16}' from endpoint 1 with groupID 0
warn  2021-10-06 11:44:15: zigbee-herdsman-converters:tuya_gas: Unrecognized DP #11 with data {"status":0,"transid":16,"dp":11,"datatype":4,"fn":0,"data":{"type":"Buffer","data":[0]}}
debug 2021-10-06 11:44:16: Received Zigbee message from '0x5c0272fffec3648f', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[0],"type":"Buffer"},"datatype":1,"dp":8,"fn":0,"status":0,"transid":16}' from endpoint 1 with groupID 0
```

Also, I'm wondering if there's a way to make the device stop beeping. Meanwhile, this is the fingerprint so the device can be added with `fz.tuya_gas` converter to support the basic functions, at least:

```
fingerprint: [
        {
            // The model ID from: Device with modelID 'TS0601' is not supported
            // You may need to add \u0000 at the end of the name in some cases
            modelID: 'TS0601',
            // The manufacturer name from: Device with modelID 'TS0601' is not supported.
            manufacturerName: '_TZE200_u319yc66'
        },
    ],
```

**Comment by danieledwardgeorgehitchcock** [comment]
Do you have a TuYa gateway?

**Comment by zocimek** [comment]
@ov1d1u have you resolved your issue?

**Comment by ov1d1u** [comment]
@zocimek Unfortunately, not too much. By trial and error I found that DP 16 is for muffling (thanks for your images, those made me to keep trying finding a way to silence the alarm). I haven't bought a Tuya gateway yet, I still plan to, but spending money on something I know I'll never use afterwards doesn't make me too eager to do so.
