### ISSUE TITLE
I have two problems about Tuya device external converter. Some experienced can help me.

### ISSUE THREAD

**Issue by ten-ltw** [Koenkk/zigbee-herdsman-converters#3132]
Hi,

I'm trying to add a custom human move sensor to zigbee2mqtt and it's use Tuya protocal. And I follow the doc [How to support new Tuya devices](https://www.zigbee2mqtt.io/how_tos/how_to_support_new_tuya_devices.html) to add a new device. But now I have two problems about it.

- If we use `tuya_data_point_dump` debug converter, it sounds like we will get a dump output file named `tuya.dump.txt`. But I use **Home Assistant OS** zigbee2mqtt add-on, and I didn't find it in both `config` folder and `zigbee2mqtt` folder.
Is that means I need an Ubuntu environment or I just make some mistake.

- What does adding to `node_modules/zigbee-herdsman-converters/converters/fromZigbee.js` some code means. Does it means that I need to pull a PR to `zigbee-herdsman-converters` to add the new device datapoint converter and If I use the external converters it will import it from Internet when it reload by zigbee2mqtt add-on in Home Assistant.

**Comment by danieledwardgeorgehitchcock** [comment]
Hi,

Regarding your second bullet point, if you are wishing to submit your code back to the Zigbee2MQTT codebase, you will need to fork the zigbee herdsman converters repo, add your changes to fromZigbee, and then push the code / create a pull request to get it merged back into the main codebase.

The above is not required for developing a custom converter though. Please see an example of a device that I have created below with a custom from fromZigbee as well as references to the main fromZigbee library. You should be able to adapt this to suit your needs:

```javascript
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const ota = require('zigbee-herdsman-converters/lib/ota');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require('zigbee-herdsman-converters/lib/tuya');

const fzLocal = {
    rc_110_level_to_scene: {
        cluster: 'genLevelCtrl',
        type: ['commandMoveToLevel', 'commandMoveToLevelWithOnOff'],
        convert: (model, msg, publish, options, meta) => {
            const scenes = {2: '1', 52: '2', 102: '3', 153: '4', 194: '5', 254: '6'};
            return {action: `scene_${scenes[msg.data.level]}`};
        },
    },
};

const definition = {
        zigbeeModel: ['RC 110'],
        model: 'RC 110',
        vendor: 'Innr',
        description: 'Innr RC 110 Remote Control',
        fromZigbee: [
            fz.command_step,
            fz.command_move,
            fz.command_stop,
            fz.command_on,
            fz.command_off,
            fzLocal.rc_110_level_to_scene
        ],
        toZigbee: [],
        meta: {multiEndpoint: true},
        endpoint: (device) => {
            return {'all': 1, 'l1': 3, 'l2': 4, 'l3': 5, 'l4': 6, 'l5': 7, 'l6': 8};
        },
        exposes: [e.action(['on_*', 'off_*', 'brightness_*', 'scene_*'])],
        configure: async (device, coordinatorEndpoint, logger) => {
            await reporting.bind(device.getEndpoint(1), coordinatorEndpoint,
                ['genBasic', 'genGroups', 'genScenes', 'genOnOff', 'genLevelCtrl']);
            for (const ep of [3, 4, 5, 6, 7, 8]) {
                const endpoint = device.getEndpoint(ep);
                await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'genLevelCtrl']);
            }
        },
    };

module.exports = definition;
```

**Comment by danieledwardgeorgehitchcock** [comment]
If you are developing your external converter within the same environment (I.e. Home Assistant)  as your Zigbee2MQTT instance, then you do not need to reference any external libraries and all can be done offline

**Comment by ten-ltw** [comment]
> If you are developing your external converter within the same environment (I.e. Home Assistant)  as your Zigbee2MQTT instance, then you do not need to reference any external libraries and all can be done offline

Thanks a lot. I will try this when I back to home and close this issue.
