### ISSUE TITLE
YDD-D4F0-TSDB Yale Lockwood T-Lock reporting double battery percentage remaining.

### ISSUE THREAD

**Issue by tomlut** [Koenkk/zigbee-herdsman-converters#3133]
EDIT: Ignore this post and see post https://github.com/Koenkk/zigbee-herdsman-converters/issues/3133#issuecomment-938197447

<s>I am using the following external converter that was provided by a third party:</s>

```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const e = exposes.presets;

const definition = {
    zigbeeModel: ['YDD-D4F0 TSDB'],
    model: 'YDD-D4F0-TSDB',
    vendor: 'Yale',
    description: 'Assure lock',
    fromZigbee: [fz.lock, fz.lock_operation_event, fz.battery],
    toZigbee: [tz.lock],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['closuresDoorLock', 'genPowerCfg']);
        await reporting.lockState(endpoint);
        await reporting.batteryPercentageRemaining(endpoint);
    },
    exposes: [e.lock(), e.battery()],
};

module.exports = definition;
```

<s>It works perfectly except that the battery % has recently started being reported as 198% (after the last update?)</s>

<s>I tried changing `fz.battery` to `fz.battery_200`, but neither restarting zigbee2mqtt nor re-adding the lock made any difference, </s>

<s>I'm pretty much flying blind here. Anyone have any advice on how to get my battery reporting back to normal?</s>

**Comment by tomlut** [comment]
Hi Koen, Thank you for the reply. 

While digger further into why is occurred after that last update I see that support was added for the YDD-D4F0-TSDB Yale Lockwood T-Lock in v1.21.2.

What takes preference, external or core/internal converters?

I have removed my external converter file and restarted zigbee2mqtt and see that my locks are still functioning (but retain the battery issue), but suspect I might have to re-add my locks to the network for this to take effect. Something I can try in 12hrs when I get home. 

If this is caused by the newly added device I guess this is what needs the fix https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/yale.js#L106

**Comment by tomlut** [comment]
There does seem to be something wrong with the built in device though.

**Comment by tomlut** [comment]
Scratch that last post. 

I force deleted the devices, removed them from the network (in the device) and removed the external converter.
Restarted zigbee2mqtt.
Added back the locks.

States are now being reported correctly - except for the double battery % which I will open a PR for.

**Comment by jamie-dit** [comment]
Since upgrading to this, the lock_state is stuck to 'not_fully_locked' when unlocking.

 This causes homebridge/homekit to report the lock as 'jammed', until the lock is manually polled after unlocking so the state is changed to 'unlock', homekit is then updated to show the lock as 'unlocked'.

Is there any way to disable that specific lock state?

**Comment by jamie-dit** [comment]
Ok. Seems like when auto-lock is enabled, the lock state remains as locked and jammed in homekit.

Once auto-lock is disabled, the lock state operates as expected. Does anyone have any ideas on how to work around this?

**Comment by tomlut** [comment]
Battery issue fixed
