### ISSUE TITLE
Full support for Xiaomi WRS-R02

### ISSUE THREAD

**Issue by lukasstanek** [Koenkk/zigbee-herdsman-converters#3147]
Hi,

it seems for these Xiaomi switches command-mode is not quite working bug-free. 
It is not possible to bind the left and right switches to different groups / devices. It seems that the switch is always sending the click signal from the first endpoint. 

It's also noted in a todo from this PR #2621
```
// TODO/BUG:
// Did not understand how to separate the left and right keys in command mode -
// the "toggleCommand" always arrives from the first endpoint
```
When I researched this I came upon following comment in the deconz github. Would this be something that we are missing in the Z2M coordinator firmware right now?
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4842#issuecomment-845438855

Apologies if I oversaw something there or it's totally unrelated.

If I could provide anything else to debug this, I'll be glad to do so.

I think this comment also talks about the same problem: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5104#issuecomment-882923413 unfortunately I'm not really knowledgeable in the zigbee space, so I'm no really understanding what they are talking about.

**Comment by lukasstanek** [comment]
Sadly I am not a zigbee expert, so I cannot say for sure, but what I dug up is the following: 
New Xiaomi Smarthome devices only work properly when the Bridge sends some vendor specific manufacturer code.
So maybe both of our problems are connected to the Z2M firmware not sending those codes? 
This is at least what I deducted from the comments I linked below.

**Comment by lukasstanek** [comment]
I dug a bit deeper and found out, that I think we are already sending those cluster configuration codes. https://github.com/Koenkk/zigbee-herdsman/blob/8898a975400aa97f5f3f9053c6134641beb928c1/src/zcl/definition/cluster.ts#L4045

I will need to research a bit further on what the issue could be.

**Comment by gozhev** [comment]
I have the same issue. Currently I unable to bind a double rocker switch (WRS-R02) to a double channel relay (LLKZMK11LM) to be able to control both channels separately.

**Comment by Steekvlam** [comment]
Same problem here, Does someone have a solution for binding the double rocker??

**Comment by Chekedaudau** [comment]
Hello together, any news here? Is it still not possible to to get 2 endpoints with 2 buttons with this switch in Z2M? Thank you 🙏
