### ISSUE TITLE
Add support for TS0601 (_TZE200_3thxjahu)

### ISSUE THREAD

**Issue by zocimek** [Koenkk/zigbee-herdsman-converters#3196]
Hi could someone add support for RGB+CCT LED Controller

https://pl.aliexpress.com/item/1005002788021234.html

![image](https://user-images.githubusercontent.com/1217727/138258759-0bdaacf2-e07d-4818-9e95-6328560dde8a.png)

In case I can help somehow please ping me

**Comment by insipiens** [comment]
@jmceara 

you should be getting the dump but if not check the following

Did you add the entry to configuration.yaml per the instructions (not the tuya page but on here: 

https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

‘
Now set the Zigbee2MQTT log_level to debug and enable the external converter by adding the following to your Zigbee2MQTT configuration.yaml.

advanced:
  log_level: debug
external_converters:
  - WSDCGQ01LM.js
Once finished, restart Zigbee2MQTT and trigger some actions on the device. You will see messages like:

‘

Making sure z2m is fully restart, perhaps try a machine reboot.

**Comment by salvq** [comment]
Hello @zocimek , have you succeeded getting data from WZ1, device seems promising especially the one with RF remote.

Thanks,

**Comment by zocimek** [comment]
Not really I didnt have time for that I was focused on a different solutions in my house as for now. I will spend some time on trying to implement converter probably next year

**Comment by urkarol** [comment]
> Not really I didnt have time for that I was focused on a different solutions in my house as for now. I will spend some time on trying to implement converter probably next year

Hello @zocimek! Are you gonna try to connect this device next year?

**Comment by urkarol** [comment]
To everyone: z2m 1.23.0 - it works!

**Comment by jejunpark** [comment]
> To everyone: z2m 1.23.0 - it works!

is it work 'transition' feature? and is it work rightly?
