### ISSUE TITLE
Hue Motion Sensor as translator for Hue Tap Switch? (No Hue lights or Hub)

### ISSUE THREAD

**Issue by tmugan** [Koenkk/zigbee-herdsman-converters#3249]
Not sure if I am posting in the right place. 

I have been using a Hue Motion sensor (model 9290012607) for some years with automation through an Amazon Alexa Plus that has Zigbee support (never bought the Philips Hue Hub)
I migrated to Zigbee2MQTT on HomeAssistant (Pi with CC2531 USB) and got the Motion sensor working. :)
BTW Zigbee2MQTT also updated the very outdated motion sensor firmware - very nice - thanks! @Koenkk 

Now, I am attempting to setup a Hue Tap Switch but It does not appear to be getting detected (nothing in the Debug Log either).

Given I have no Hue Hub to translate the Zigbee Green Power device communications of the Tap, is there any chance that the Hue motion sensor could suffice as the translator, or do I need a Hue lightbulb on my network?

**Comment by OsteHovel** [comment]
Only the powered devices (not battery) does the Zigbee Green Power translation.
So a Hue bulb or light strip or other device that does the translation is needed.

**Comment by tmugan** [comment]
I had hoped the Hue motion would be that device.

Since posting earlier, I went out and just bought a Hue bulb. It was detected immediately by Zigbee2MQTT and the Tap Switch also then was detected because of that new lightbulb.

I think that answers the question.

But *could* Z2M make use of a battery powered Hue Motion sensor to translate the Hue Tap switch?

**Comment by OsteHovel** [comment]
No, because Hue Motion sensor lacks the cluster/functionality for Zigbee Green Power translation

**Comment by tmugan** [comment]
Thanks for sharing your knowledge. Much appreciated.
