### ISSUE TITLE
Generic toZigbee converters are only added if a device has at least one converter defined

### ISSUE THREAD

**Issue by normanr** [Koenkk/zigbee-herdsman-converters#3261]
The generic `read` and `write` converters are useful for most devices, but they're not added unless a device has at least one toZigbee converter defined already, ref:
https://github.com/Koenkk/zigbee-herdsman-converters/blob/1159051138d83a9aaef69d0e3f6cd5c46b901a45/index.js#L78-L80
They're useful on the dev console to probe which attributes a device supports, but it would be nice if they were added for all devices unconditionally.

**Comment by Koenkk** [comment]
Agree, could you make a pr?

**Comment by normanr** [comment]
To do what? Should all `read`/`write` and scene converters be added? Just `read`/`write`?

**Comment by Koenkk** [comment]
Lets just add all (so remove the if)
