### ISSUE TITLE
Silvercrest/Lidl  TS0601 - _TZE200_chyvmhay did not work but works with https://github.com/Lavisx/lidl-valve-z2m/blob/main/lidl_radiator_valve.js

### ISSUE THREAD

**Issue by gmarchart** [Koenkk/zigbee-herdsman-converters#3266]
Hello, 
using conbee2 on Raspberrypi, zigbee2mqtt latest version - Current version: 1.22.0-2. Ha, latest version.Home Assistant 2021.10.7

---------------------------------------------------------------------------------------------
## System Health

version | core-2021.10.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.17-v7
arch | armv7l
timezone | Europe/Vienna

Host-Betriebssystem | Home Assistant OS 6.6
-- | --
Update-Channel | stable
Supervisor-Version | supervisor-2021.10.8
Docker-Version | 20.10.8
Speicherplatz gesamt | 58.0 GB
Speicherplatz genutzt | 12.7 GB
Gesund | true
Unterstützt | true
Board | rpi3
Supervisor-API | ok
Versions-API | ok
Installierte Add-ons | Mosquitto broker (6.0.1), Samba share (9.5.1), Check Home Assistant configuration (3.9.0), TasmoAdmin (0.15.0), File editor (5.3.3), AirCast (3.1.1), SSH & Web Terminal (9.0.1), Portainer (2.0.0), deCONZ (6.10.0), Node-RED (10.0.1), Duck DNS (1.14.0), Let's Encrypt (4.11.0), Remote Backup (4.2.7), InfluxDB (4.2.1), Grafana (7.2.0), Zigbee2mqtt (1.22.0-2), Log Viewer (0.12.0)
----------------------------------------------------------------------------------------------

Zigbee Modell
TS0601
Zigbee Hersteller
_TZE200_chyvmhay
Beschreibung
Radiator valve with thermostat
Unterstützungsstatus
unterstützt

IEEE Addresse
0x0c4314fffe56bf22
Netzwerk Adresse
0x01BD
Hersteller
TuYa
Modell
TS0601_thermostat

status is supported, but batterie is not recognized, device say full, mqtt say low and blinks...
other settings to change is not possible in mqtt. no reaction. either schedule, or temperatur or something else, nothing works. i have 4 Valves, all does the same, supported, but no reaction on any changes when done in mqtt.

Bevor i used Lavisx converter - that works mostly - but had some issues, but mainly it works, see below -
            There is my custom converter until it will be officially implemented.
             https://github.com/Lavisx/lidl-valve-z2m/blob/main/lidl_radiator_valve.js

Below is the first request i opened about this Valve, Lavisx wrote then a temp. converter - Request was closed in the meantime.
           TS0601 - TZE200_chyvmhay' Thermostat not supported - please add if possible #8934
           Closed
          gmarchart opened this issue on 1 Oct · 29 comments

But with this official converter there is no functionality.
i allready removed the thermostat device from mqtt and re-pair it, also a reset on the valve done, but the situation was the same. Parameter to change in mqtt did not reflect on Thermostat. It seems that the datapoints from the tuya device is not the same as used in Lavisx Converter, because his one works mainly, the official one not.

Do you need additional debug or testing output from the device ?
-----------------------------------------------------------------------
mqtt valve status:

{
    "auto_lock": "AUTO",
    "away_preset_days": 0,
    "away_preset_temperature": {
        "0": 6,
        "1": 34,
        "2": 24,
        "3": 42,
        "4": 36,
        "5": 34,
        "6": 68,
        "7": 42,
        "8": 92,
        "9": 34,
        "10": 96,
        "11": 42,
        "12": 96,
        "13": 34,
        "14": 96,
        "15": 42,
        "16": 96,
        "17": 34
    },
    "battery_low": {
        "0": 2,
        "1": 34,
        "2": 24,
        "3": 42,
        "4": 36,
        "5": 34,
        "6": 68,
        "7": 42,
        "8": 92,
        "9": 34,
        "10": 96,
        "11": 42,
        "12": 96,
        "13": 34,
        "14": 96,
        "15": 42,
        "16": 96,
        "17": 34
    },
    "boost_time": 34,
    "comfort_temperature": false,
    "current_heating_setpoint": 0,
    "holidays": [
        {
            "hour": 5,
            "minute": 34,
            "temperature": 24
        },
        {
            "hour": 42,
            "minute": 36,
            "temperature": 34
        },
        {
            "hour": 4,
            "minute": 42,
            "temperature": 92
        },
        {
            "hour": 34,
            "minute": 96,
            "temperature": 42
        },
        {
            "hour": 32,
            "minute": 34,
            "temperature": 96
        },
        {
            "hour": 42,
            "minute": 96,
            "temperature": 34
        }
    ],
    "linkquality": 255,
    "max_temperature": {
        "0": 19,
        "1": 1,
        "2": 1,
        "3": 0,
        "4": 0,
        "5": 34,
        "6": 0,
        "7": 0
    },
    "min_temperature": 34,
    "position": {
        "0": 1,
        "1": 34,
        "2": 24,
        "3": 42,
        "4": 36,
        "5": 34,
        "6": 68,
        "7": 42,
        "8": 92,
        "9": 34,
        "10": 96,
        "11": 42,
        "12": 96,
        "13": 34,
        "14": 96,
        "15": 42,
        "16": 96,
        "17": 34
    },
    "window_detection": "OFF",
    "window_detection_params": {},
    "workdays": [
        {
            "hour": 4,
            "minute": 34,
            "temperature": 24
        },
        {
            "hour": 42,
            "minute": 36,
            "temperature": 34
        },
        {
            "hour": 4,
            "minute": 42,
            "temperature": 92
        },
        {
            "hour": 34,
            "minute": 96,
            "temperature": 42
        },
        {
            "hour": 32,
            "minute": 34,
            "temperature": 96
        },
        {
            "hour": 42,
            "minute": 96,
            "temperature": 34
        }
    ],
    "away_mode": null,
    "child_lock": null,
    "eco_temperature": null,
    "update_available": null,
    "valve_detection": null
}

--------------------------------------------------------------------------------------
Debug Publishing 'set' 'current_heating_setpoint' to 'Lidl-Thermostat-WZ'
Debug Publishing 'set' 'current_heating_setpoint' to 'Lidl-Thermostat-WZ'
Info MQTT publish: topic 'zigbee2mqtt/Lidl-Thermostat-WZ', payload '{"auto_lock":"AUTO","away_mode":null,"away_preset_days":0,"away_preset_temperature":{"0":6,"1":34,"10":96,"11":42,"12":96,"13":34,"14":96,"15":42,"16":96,"17":34,"2":24,"3":42,"4":36,"5":34,"6":68,"7":42,"8":92,"9":34},"battery_low":{"0":2,"1":34,"10":96,"11":42,"12":96,"13":34,"14":96,"15":42,"16":96,"17":34,"2":24,"3":42,"4":36,"5":34,"6":68,"7":42,"8":92,"9":34},"boost_time":34,"child_lock":null,"comfort_temperature":false,"current_heating_setpoint":0,"eco_temperature":null,"holidays":[{"hour":5,"minute":34,"temperature":24},{"hour":42,"minute":36,"temperature":34},{"hour":4,"minute":42,"temperature":92},{"hour":34,"minute":96,"temperature":42},{"hour":32,"minute":34,"temperature":96},{"hour":42,"minute":96,"temperature":34}],"linkquality":255,"max_temperature":{"0":19,"1":1,"2":1,"3":0,"4":0,"5":34,"6":0,"7":0},"min_temperature":34,"position":{"0":1,"1":34,"10":96,"11":42,"12":96,"13":34,"14":96,"15":42,"16":96,"17":34,"2":24,"3":42,"4":36,"5":34,"6":68,"7":42,"8":92,"9":34},"update_available":null,"valve_detection":null,"window_detection":"OFF","window_detection_params":{},"workdays":[{"hour":4,"minute":34,"temperature":24},{"hour":42,"minute":36,"temperature":34},{"hour":4,"minute":42,"temperature":92},{"hour":34,"minute":96,"temperature":42},{"hour":32,"minute":34,"temperature":96},{"hour":42,"minute":96,"temperature":34}]}'
Info MQTT publish: topic 'zigbee2mqtt/Lidl-Thermostat-WZ', payload '{"auto_lock":"AUTO","away_mode":null,"away_preset_days":0,"away_preset_temperature":{"0":6,"1":34,"10":96,"11":42,"12":96,"13":34,"14":96,"15":42,"16":96,"17":34,"2":24,"3":42,"4":36,"5":34,"6":68,"7":42,"8":92,"9":34},"battery_low":{"0":2,"1":34,"10":96,"11":42,"12":96,"13":34,"14":96,"15":42,"16":96,"17":34,"2":24,"3":42,"4":36,"5":34,"6":68,"7":42,"8":92,"9":34},"boost_time":34,"child_lock":null,"comfort_temperature":false,"current_heating_setpoint":0,"eco_temperature":null,"holidays":[{"hour":5,"minute":34,"temperature":24},{"hour":42,"minute":36,"temperature":34},{"hour":4,"minute":42,"temperature":92},{"hour":34,"minute":96,"temperature":42},{"hour":32,"minute":34,"temperature":96},{"hour":42,"minute":96,"temperature":34}],"linkquality":255,"max_temperature":{"0":19,"1":1,"2":1,"3":0,"4":0,"5":34,"6":0,"7":0},"min_temperature":34,"position":{"0":1,"1":34,"10":96,"11":42,"12":96,"13":34,"14":96,"15":42,"16":96,"17":34,"2":24,"3":42,"4":36,"5":34,"6":68,"7":42,"8":92,"9":34},"update_available":null,"valve_detection":null,"window_detection":"OFF","window_detection_params":{},"workdays":[{"hour":4,"minute":34,"temperature":24},{"hour":42,"minute":36,"temperature":34},{"hour":4,"minute":42,"temperature":92},{"hour":34,"minute":96,"temperature":42},{"hour":32,"minute":34,"temperature":96},{"hour":42,"minute":96,"temperature":34}]}'
Info MQTT publish: topic 'zigbee2mqtt/Lidl-Thermostat-WZ', payload '{"auto_lock":"AUTO","away_mode":null,"away_preset_days":0,"away_preset_temperature":{"0":6,"1":34,"10":96,"11":42,"12":96,"13":34,"14":96,"15":42,"16":96,"17":34,"2":24,"3":42,"4":36,"5":34,"6":68,"7":42,"8":92,"9":34},"battery_low":{"0":2,"1":34,"10":96,"11":42,"12":96,"13":34,"14":96,"15":42,"16":96,"17":34,"2":24,"3":42,"4":36,"5":34,"6":68,"7":42,"8":92,"9":34},"boost_time":34,"child_lock":null,"comfort_temperature":false,"current_heating_setpoint":0,"eco_temperature":null,"holidays":[{"hour":5,"minute":34,"temperature":24},{"hour":42,"minute":36,"temperature":34},{"hour":4,"minute":42,"temperature":92},{"hour":34,"minute":96,"temperature":42},{"hour":32,"minute":34,"temperature":96},{"hour":42,"minute":96,"temperature":34}],"linkquality":255,"max_temperature":{"0":19,"1":1,"2":1,"3":0,"4":0,"5":34,"6":0,"7":0},"min_temperature":34,"position":{"0":1,"1":34,"10":96,"11":42,"12":96,"13":34,"14":96,"15":42,"16":96,"17":34,"2":24,"3":42,"4":36,"5":34,"6":68,"7":42,"8":92,"9":34},"update_available":null,"valve_detection":null,"window_detection":"OFF","window_detection_params":{},"workdays":[{"hour":4,"minute":34,"temperature":24},{"hour":42,"minute":36,"temperature":34},{"hour":4,"minute":42,"temperature":92},{"hour":34,"minute":96,"temperature":42},{"hour":32,"minute":34,"temperature":96},{"hour":42,"minute":96,"temperature":34}]}'
Info MQTT publish: topic 'zigbee2mqtt/Lidl-Thermostat-WZ', payload '{"auto_lock":"AUTO","away_mode":null,"away_preset_days":0,"away_preset_temperature":{"0":6,"1":34,"10":96,"11":42,"12":96,"13":34,"14":96,"15":42,"16":96,"17":34,"2":24,"3":42,"4":36,"5":34,"6":68,"7":42,"8":92,"9":34},"battery_low":{"0":2,"1":34,"10":96,"11":42,"12":96,"13":34,"14":96,"15":42,"16":96,"17":34,"2":24,"3":42,"4":36,"5":34,"6":68,"7":42,"8":92,"9":34},"boost_time":34,"child_lock":null,"comfort_temperature":false,"current_heating_setpoint":0,"eco_temperature":null,"holidays":[{"hour":5,"minute":34,"temperature":24},{"hour":42,"minute":36,"temperature":34},{"hour":4,"minute":42,"temperature":92},{"hour":34,"minute":96,"temperature":42},{"hour":32,"minute":34,"temperature":96},{"hour":42,"minute":96,"temperature":34}],"linkquality":255,"max_temperature":{"0":19,"1":1,"2":1,"3":0,"4":0,"5":34,"6":0,"7":0},"min_temperature":34,"position":{"0":1,"1":34,"10":96,"11":42,"12":96,"13":34,"14":96,"15":42,"16":96,"17":34,"2":24,"3":42,"4":36,"5":34,"6":68,"7":42,"8":92,"9":34},"update_available":null,"valve_detection":null,"window_detection":"OFF","window_detection_params":{},"workdays":[{"hour":4,"minute":34,"temperature":24},{"hour":42,"minute":36,"temperature":34},{"hour":4,"minute":42,"temperature":92},{"hour":34,"minute":96,"temperature":42},{"hour":32,"minute":34,"temperature":96},{"hour":42,"minute":96,"temperature":34}]}'
Debug Received Zigbee message from 'Lidl-Thermostat-Schlafzimmer', type 'commandSetDataResponse', cluster 'manuSpecificTuya', data '{"data":{"data":[0,0,0,148],"type":"Buffer"},"datatype":2,"dp":35,"fn":0,"status":0,"transid":35}' from endpoint 1 with groupID null
Debug Publishing 'set' 'system_mode' to 'Lidl-Thermostat-WZ'
Debug Publishing 'set' 'local_temperature_calibration' to 'Lidl-Thermostat-WZ'
Debug Received MQTT message on 'zigbee2mqtt/Lidl-Thermostat-WZ/set' with data '{"auto_lock":"MANUAL"}'
Debug Received Zigbee message from 'Lidl-Thermostat-WZ', type 'commandSetDataResponse', cluster 'manuSpecificTuya', data '{"data":{"data":[0,0,0,20],"type":"Buffer"},"datatype":2,"dp":116,"fn":0,"status":0,"transid":116}' from endpoint 1 with groupID null
Debug Received Zigbee message from 'Lidl-Thermostat-WZ', type 'commandSetDataResponse', cluster 'manuSpecificTuya', data '{"data":{"data":[0,0,0,20],"type":"Buffer"},"datatype":2,"dp":116,"fn":0,"status":0,"transid":116}' from endpoint 1 with groupID null
Debug Received MQTT message on 'zigbee2mqtt/Lidl-Thermostat-WZ/set/local_temperature_calibration' with data '2'
Debug Publishing 'set' 'local_temperature_calibration' to 'Lidl-Thermostat-WZ'
Debug Publishing 'set' 'local_temperature_calibration' to 'Lidl-Thermostat-Kueche'
Debug Publishing 'set' 'local_temperature_calibration' to 'Lidl-Thermostat-VZ'
Debug Publishing 'set' 'local_temperature_calibration' to 'Lidl-Thermostat-Schlafzimmer'
Debug Publishing 'set' 'local_temperature_calibration' to 'Lidl-Thermostat-WZ'
Debug Received MQTT message on 'zigbee2mqtt/Lidl-Thermostat-Kueche/set/local_temperature_calibration' with data '2.5'
Debug Publishing 'set' 'local_temperature_calibration' to 'Lidl-Thermostat-Kueche'
Debug Publishing 'set' 'local_temperature_calibration' to 'Lidl-Thermostat-VZ'
Debug Publishing 'set' 'local_temperature_calibration' to 'Lidl-Thermostat-Schlafzimmer'

------------------------------------------------------------------------------------------------------------

Thanks for a check, 

Br
Guenther

**Comment by ciB89** [comment]
I can now also confirm, this is not working at all.

**Comment by kasik96** [comment]
Same problem. Funny is that external converted that was provided is working perfectly. I don't get this.

**Comment by xstable** [comment]
Also try to get this thermostat to work. Is there any chance to get it to work with HomeAssistant and CC2652RB?

**Comment by gmarchart** [comment]
i did not have that issue as you have with this external converter. did you have done a reset of z2m too ? 
in the meantime i use the official z2m version (not the edge) - and without external converter, but there is an issue that i get every day a date/time reset ?! on the valve - i have every day a false date/time on the valve through z2m... so the automatic schedule did not work programmed on the valve ...

**Comment by gmarchart** [comment]
Lidl valve works good with official branch (latest). Except the time/date reset every day. This is fixed in the dev/edge branch. Should be available in the next official branch then I guess. 

At the moment with Dev/edge branch I see no issues. 

So I close this problem.

**Comment by gmarchart** [comment]
Issues fixed as described above
