### ISSUE TITLE
Expose Fan broken?

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee-herdsman-converters#3276]
I noticed while poking the IKEA STARKVIND that the fan_mode was not changeable via the frontend but was fine using MQTT manually.

```
class Fan extends Base {
    constructor() {
        super();
        this.type = 'fan';
        this.features = [];
        this.features.push(new Binary('state', access.ALL, 'ON', 'OFF').withDescription('On/off state of this fan').withProperty('fan_state'));
    }

    withModes(modes, access=a.ALL) {
        assert(!this.endpoint, 'Cannot add feature after adding endpoint');
        this.features.push(new Enum('mode', access, modes).withProperty('fan_mode').withDescription('Mode of this fan'));
        return this;
    }
}
```

Changing this line makes it work but I don't see why this would be needed? As .withProperty after should have the same result?

```
        this.features.push(new Enum('mode', access, modes).withProperty('fan_mode').withDescription('Mode of this fan'));
```
to
```
        this.features.push(new Enum('fan_mode', access, modes).withProperty('fan_mode').withDescription('Mode of this fan'));
```

@Koenkk any idea why? The original looks OK to me but it produced:

```
debug Received MQTT message on 'zigbee2mqtt/0xcc86ecfffe6d3377/set' with data '{"mode":"medium"}'
error No converter available for 'mode' (medium)
```

Which is clearly not the correct payload? After the fix it produces `{"fan_mode":"medium"}` as expected.

**Comment by Koenkk** [comment]
This looks like an issue in the frontend, @nurikk could you check this?

**Comment by nurikk** [comment]
Yeah, there is a bug. Fixed

**Comment by sjorge** [comment]
That would explain it, I was messing around with console.log() and it was properly calling the function!
