### ISSUE TITLE
New Livarno/Lidl RGB bulbs not supported

### ISSUE THREAD

**Issue by mribeiro** [Koenkk/zigbee-herdsman-converters#3280]
Just purchased some new Lidl RGB bulbs and the manufacturer/model doesn't seem to be recognised:

> Zigbee2MQTT:warn  2021-11-04 09:58:13: Device '0xb4e3f9fffec0a317' with Zigbee model 'TS0505B' and manufacturer name '_TZ3000_qd7hej8u' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

Will follow tutorial tonight but if someone wants to add this already to the dev branch I'd appreciate.

If there's anything I can help with please let me know.

**Comment by danieledwardgeorgehitchcock** [comment]
If you can add your database.db entry here, I could add it for you...

**Comment by mribeiro** [comment]
@danieledwardgeorgehitchcock Just opened a PR before noticing your comment. Hope the PR is good; if not I can post the database.db entry.

**Comment by LittleBigDev** [comment]
Hello @mribeiro and @Koenkk 

Considering this PR (#3282) how would be the syntax for the same TS0505B (HG07834C) integration, but via a js file (TS0505B.js like explained in the tutorial) ?

I'm under HassOS and have no access to `devices/lidl.js` file, so a little help would be appreciated. It would help me to integrate HG07834B, which is exactly the same, but E14 candle version.

**Comment by mribeiro** [comment]
You mean as an external converter?
This is how I have it at the moment:

```
/**
 Zigbee2MQTT:warn  2021-11-04 09:58:13:
 Device '0xb4e3f9fffec0a317'
 with Zigbee model 'TS0505B' and
 manufacturer name '_TZ3000_qd7hej8u'

 is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
*/

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['TS0505B'], // The model ID from: Device with modelID 'lumi.sens' is not supported.
    model: 'HG07834C', // Vendor model number, look on the device for a model number
    vendor: 'Lidl', // Vendor of the device (only used for documentation and startup logging)
    description: 'Livarno Lux E27 bulb RGB',
	...extend.light_onoff_brightness_colortemp_color({disableColorTempStartup: true}),
	meta: {applyRedFix: true, enhancedHue: false},
	configure: async (device, coordinatorEndpoint, logger) => {
		device.getEndpoint(1).saveClusterAttributeKeyValue('lightingColorCtrl', {colorCapabilities: 29});
	},
};

module.exports = definition;
```

The color range is missing but I'm not stressing about it, it'll be fixed in the regular release. You need to check the log and adapt the model/zigbeeModel accordingly.

**Comment by LittleBigDev** [comment]
Yes [I have done that](https://github.com/Koenkk/zigbee-herdsman-converters/issues/3312).

No PR though... feel free to contribute it if you wish.

**Comment by LittleBigDev** [comment]
To be more verbose, my issue was not in the **syntax** of the converter, but in the way to declare it.  
In HassOS + Z2M add-on, the configuration.yaml can be found in /config/zigbee2mqtt/configuration.yaml. But this file is auto-generated ! So any converter added there is lost at Z2M reboot.

I found the correct method : using the Z2M UI to add the converter file path (under "Parameters").

**Comment by ThibautSLR** [comment]
Hi,
I am also looking to integrate the E14 lidl bulb.
Since it is very alike E27 model, is it not possible to add these lines directly to the lidl.js? 

```
{
        fingerprint: [{modelID: 'TS0505B', manufacturerName: '_TZ3000_th6zqqy6'}],
        model: 'HG07834B',
        vendor: 'Lidl',
        description: 'Livarno Lux E14 candle RGB',
        ...extend.light_onoff_brightness_colortemp_color({disableColorTempStartup: true, colorTempRange: [153, 500]}),
        meta: {applyRedFix: true, enhancedHue: false},
        configure: async (device, coordinatorEndpoint, logger) => {
            device.getEndpoint(1).saveClusterAttributeKeyValue('lightingColorCtrl', {colorCapabilities: 29});
        },
    },
```

Thanks

**Comment by mribeiro** [comment]
> Hi,
> 
> I am also looking to integrate the E14 lidl bulb.
> 
> Since it is very alike E27 model, is it not possible to add these lines directly to the lidl.js? 
> 
> 
> 
> ```
> 
> {
> 
>         fingerprint: [{modelID: 'TS0505B', manufacturerName: '_TZ3000_th6zqqy6'}],
> 
>         model: 'HG07834B',
> 
>         vendor: 'Lidl',
> 
>         description: 'Livarno Lux E14 candle RGB',
> 
>         ...extend.light_onoff_brightness_colortemp_color({disableColorTempStartup: true, colorTempRange: [153, 500]}),
> 
>         meta: {applyRedFix: true, enhancedHue: false},
> 
>         configure: async (device, coordinatorEndpoint, logger) => {
> 
>             device.getEndpoint(1).saveClusterAttributeKeyValue('lightingColorCtrl', {colorCapabilities: 29});
> 
>         },
> 
>     },
> 
> ```
> 
> 
> 
> Thanks

I don't advise trying to change what's deployed. You have two solutions not mutually exclusive:

1. Creating and using an external adaptor. I can help you with that but the instructions are on z2m website.
2. Create a PR with the change in lidl.js and get it approved.

**Comment by ThibautSLR** [comment]
@mribeiro Thanks for your replie !!
LittleBigDev have done all the work (https://github.com/Koenkk/zigbee-herdsman-converters/issues/3312) and I just saw that it has just been validated. There will probably remain the GU10 version that I do not have.
