### ISSUE TITLE
child lock not working on _TZE200_c88teujp

### ISSUE THREAD

**Issue by handfreezer** [Koenkk/zigbee-herdsman-converters#3296]
Hello,

  I just received a TRV with finger_print: _TZE200_c88teujp , it is recognized as SEA801-Zigbee/SEA802-Zigbee , but "child lock" is not working.
  When I click on the "ON" state, few seconds later the "switch" is changing of state to "ON" but the trv is not locked.

Any idea?

**Comment by danieledwardgeorgehitchcock** [comment]
You may need to wake (and keep awake) the device when applying the setting.

As the device is a Zigbee endpoint, it goes to sleep, wakes up, does something, transmits data, then goes back to sleep so, unless the setting change is applied during the wake state, it will likely time out.
