### ISSUE TITLE
_TZE200_b6wax7g0 not working properly

### ISSUE THREAD

**Issue by karlkar** [Koenkk/zigbee-herdsman-converters#3317]
I'm trying to use _TZE200_b6wax7g0 with Home Assistant and it doesn't work properly.
I bought my device here https://pl.aliexpress.com/item/1005002438648783.html?spm=a2g0s.9042311.0.0.27425c0foy7ecd
Zigbee Model: TS0601
Zigbee Manufacturer: _TZE200_b6wax7g0

Right after the valve is paired I can control it from Zigbee2Mqtt control panel in HA. But:
I cannot control the valve when the display is off.
I cannot get OTA update, getting error: "Failed to check if update available for 'rad_mala_lazienka' (No image available for imageType '5634')"
In HA I cannot see boost mode, nor current temperature in room.
I think valve disconnects after some time and I have to pair it again.

I did apply customization changes described here: https://github.com/Koenkk/zigbee-herdsman-converters/issues/2937#issuecomment-917696264
Before that I could not see controller to set temperature. Now that's how HA displays the valve:
<img width="456" alt="Screenshot 2021-11-10 at 09 48 04" src="https://user-images.githubusercontent.com/53021952/141080374-7e2394e1-ea45-4115-b5a4-c44dec5cc75f.png">

What I did at the very beginning, when I bought it few months ago, was flashing the valve with available OTA. Since then the valve was not working properly, but there were some discussions going on in Issues section, so I've been reading it, hoping that sometime it will get fixed. 
I've flashed my device, because I've read that it is needed for the valve to be available even when display is off, but maybe it has crashed something, as I've later read that it might have been an image for different device... 

What can I do to make this valve work properly?

**Comment by vladi1234** [comment]
You don't have to open up new topics.
There was already enough information here.

https://github.com/Koenkk/zigbee2mqtt/issues/7941

You have apparently broken TVR, updated with wrong firmware.

**Comment by vladi1234** [comment]
>What can I do to make this valve work properly?

https://github.com/Koenkk/zigbee2mqtt/issues/7941#issuecomment-907121475

**Comment by karolVimn** [comment]
Oh, I was looking for that issue and couldn't find it anymore. Sorry for duplicate. 
Yeah, I have genBasic.appVersion=87
I thought that you already got the firmware as of https://github.com/Koenkk/zigbee2mqtt/issues/7941#issuecomment-938062556 
I've ordered new valve. How can I read the OTA? Or we have to wait for the new official release?

**Comment by karlkar** [comment]
Oh, I was looking for that issue and couldn't find it anymore. Sorry for duplicate.
Yeah, I have genBasic.appVersion=87
I thought that you already got the firmware as of Koenkk/zigbee2mqtt#7941 (comment)
I've ordered new valve. How can I read the OTA? Or we have to wait for the new official release?

**Comment by vladi1234** [comment]
You can try to read it out like this.
https://github.com/Koenkk/zigbee2mqtt/issues/7941#issuecomment-907148068

**Comment by TomaszBich** [comment]
@karlkar did you have a chance to manage your problem?
I have similar issue but cannot find E2E fix process
