### ISSUE TITLE
Yale DWGW-ZB-DLM-YDM/Onesti module/Homely module for Yale Doorman V2N

### ISSUE THREAD

**Issue by henriklied** [Koenkk/zigbee-herdsman-converters#3326]
I've been testing out the [Yale DWGW-ZB-DLM-YDM](http://www.lascentrum.se/shop/product/view/l/radiomodul-yale-zb), a Zigbee module for the [Yale Doorman V2N ](https://www.yalehome.no/no/kundestotte/smarte-laser/yale-doorman-v2n/kom-i-gang/), the most popular smart lock in Scandinavia.

The module is compatible with the [Onesti line of security products](https://onestiproducts.io/product/) through their hub, and also  the [Homely security system](https://www.homely.no/produkter/) for the Norwegian market.

I've gotten some help from @danieledwardgeorgehitchcock to setup the initial converter, but we're not really understanding how to get it working. Here's what I've got so far:

When booting up Zigbee2MQTT in pairing mode and starting the pairing process, I got these messages:
```info  2021-11-10 17:16:18: Device '0x000d6f000c9f48ed' joined
info  2021-11-10 17:16:18: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x000d6f000c9f48ed","ieee_address":"0x000d6f000c9f48ed"},"type":"device_joined"}'
info  2021-11-10 17:16:18: Starting interview of '0x000d6f000c9f48ed'
info  2021-11-10 17:16:18: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x000d6f000c9f48ed","ieee_address":"0x000d6f000c9f48ed","status":"started"},"type":"device_interview"}'
debug 2021-11-10 17:16:18: Received Zigbee message from '0x000d6f000c9f48ed', type 'raw', cluster '60108', data '{"data":[9,5,254,48,2,4,8,121,249,155,54,14,23,71,231,172,88,176,96],"type":"Buffer"}' from endpoint 1 with groupID 0
debug 2021-11-10 17:16:18: Device '0x000d6f000c9f48ed' announced itself
info  2021-11-10 17:16:18: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x000d6f000c9f48ed","ieee_address":"0x000d6f000c9f48ed"},"type":"device_announce"}'
debug 2021-11-10 17:16:18: Skipping message, definition is undefined and still interviewing
info  2021-11-10 17:16:19: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0x000d6f000c9f48ed"},"type":"device_connected"}'
info  2021-11-10 17:16:19: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x000d6f000c9f48ed"},"type":"pairing"}'
info  2021-11-10 17:16:19: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0x000d6f000c9f48ed"},"type":"device_announced"}'
debug 2021-11-10 17:17:20: Received Zigbee message from '0x000d6f000c9f48ed', type 'raw', cluster '60108', data '{"data":[9,6,254,135,14,117,234,212,163,70,229,163,70,135,103,197,227,205,154],"type":"Buffer"}' from endpoint 1 with groupID 0
debug 2021-11-10 17:17:20: Skipping message, definition is undefined and still interviewing
```

Some time later, it appeared in my database.db file:
```{"id":55,"type":"EndDevice","ieeeAddr":"0x000d6f000c9f48ed","nwkAddr":16968,"manufId":60108,"epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":10,"inClusterList":[0,1,3,4,5,257],"outClusterList":[3,25],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"interviewCompleted":true,"meta":{},"lastSeen":1636561247465}```

@danieledwardgeorgehitchcock then sent me the code for a basic converter which I added. The fingerprint technique worked, and when I restarted Z2M, the device showed up with the right vendor and description, but only the link quality showed up – none of the other properties populated, and the lock and unlock events didn't do anything.
```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const e = exposes.presets;

const definition = {
        fingerprint: [{
            type: 'EndDevice',
            manufacturerID: 60108,
            endpoints: [
               {ID: 1, profileID: 260, deviceID: 10, inputClusters: [0,1,3,4,5,257], outputClusters: [3,25]},
            ]},
        ],
        model: 'kommunikasjonsmodul-yale-doorman',
        vendor: 'Yale',
        description: 'Homely module for Yale Doorman',
        fromZigbee: [fz.lock, fz.lock_operation_event],
        toZigbee: [tz.lock],
        exposes: [e.lock()]
    };

module.exports = definition;
```

In the log file I also got some other events that we weren't able to understand (I renamed the device to `doorlock` here in order to more easily see it in the log file):
```
debug 2021-11-10 21:29:52: Received MQTT message on 'zigbee2mqtt/doorlock/set' with data '{"state":"UNLOCK"}'
debug 2021-11-10 21:29:52: Publishing 'set' 'state' to 'doorlock'
debug 2021-11-10 21:29:54: Received Zigbee message from 'doorlock', type 'raw', cluster '60108', data '{"data":[9,16,254,214,172,83,173,56,123,148,65,130,15,124,154,63,23,76,250],"type":"Buffer"}' from endpoint 1 with groupID 0
debug 2021-11-10 21:29:54: No converter available for 'kommunikasjonsmodul-yale-doorman' with cluster '60108' and type 'raw' and data '{"data":[9,16,254,214,172,83,173,56,123,148,65,130,15,124,154,63,23,76,250],"type":"Buffer"}'

debug 2021-11-10 21:31:32: Publishing 'set' 'state' to 'doorlock'
debug 2021-11-10 21:31:55: Error: Command 0x000d6f000c9f48ed/1 closuresDoorLock.unlockDoor({"pincodevalue":""}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 2074 - 1 - 11 - 257 - 1 after 10000ms)
    at Timeout._onTimeout (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
info  2021-11-10 21:31:55: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'doorlock' failed: 'Error: Command 0x000d6f000c9f48ed/1 closuresDoorLock.unlockDoor({\"pincodevalue\":\"\"}, {\"sendWhenActive\":false,\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Timeout - 2074 - 1 - 11 - 257 - 1 after 10000ms)'","meta":{"friendly_name":"doorlock"},"type":"zigbee_publish_error"}'
```

I assume the easiest way to get things going would be to purchase the bridge for this as well, but the bridge costs about $300, which I feel is a bit too steep.

Like I wrote further up in the post, the device seems to be compatible with Onesti's line of products, and I see the [Onesti Products AS easyCodeTouch_v1 lock](https://www.zigbee2mqtt.io/devices/easyCodeTouch_v1.html) is already supported by Zigbee2MQTT. I tried adding the functions and attributes from that lock's definition file to my custom converter, but that didn't work.

Any thoughts @Koenkk @OsteHovel @eirikd ?

**Comment by danieledwardgeorgehitchcock** [comment]
A strange thing for me to see in the above data is the raw Zigbee message from cluster `60108` which is the same id as the manufacturer - could this be similar to the Xiaomi manufacturer options? - It isn't a cluster that is reported by the device, or a standard cluster in the Zigbee Cluster Library...

**Comment by danieledwardgeorgehitchcock** [comment]
Another thing I am curious about is, that according to the Onsti manual https://github.com/Koenkk/zigbee-herdsman-converters/files/7229993/Easy.Access.E-Life.Zigbee.Module.pdf the message structure is `[Lock Command Id: LOCK 0x00 | UNLOCK 0x01]<Pin Code: LENGTH 0x00>` with a `Pin Code: LENGTH` of always `0`.

Does the current `lock` toZigbee converter send the message in this format? At a quick glance, it looks like it is sending a string..?
