### ISSUE TITLE
Empty action payload - Linkind 5-Key Smart Bulb Dimmer Switch Light Remote Control (ZS23000278)

### ISSUE THREAD

**Issue by brandon-meadows** [Koenkk/zigbee-herdsman-converters#3340]
For every button press, there are 2 messages sent by default. The second message always contains an empty action payload. If I'm trying to extract the action payload to use in an automation or update as a template entity, it always ends with a blank payload. This also happens for other payloads such as "action_color_temperature".

Message 1 received on zigbee2mqtt/Shower Remote at 12:30 PM:
{
    "action": "",
    "battery": 100,
    "battery_low": false,
    "brightness": 64,
    "linkquality": 57,
    "voltage": 3100
}
QoS: 0 - Retain: false
Message 0 received on zigbee2mqtt/Shower Remote at 12:30 PM:
{
    "action": "color_temperature_move",
    "action_color_temperature": 153,
    "action_group": 16388,
    "action_transition_time": 3,
    "battery": 100,
    "battery_low": false,
    "brightness": 64,
    "linkquality": 57,
    "voltage": 3100
}
QoS: 0 - Retain: false

**Comment by Koenkk** [comment]
This is expected when the home assistant integration is enabled, see https://www.zigbee2mqtt.io/guide/faq/#why-is-the-action-property-always-empty
