### ISSUE TITLE
Adding support for Salus Controls KL08RF 8 Zone Wiring Centre

### ISSUE THREAD

**Issue by miguelangel-nubla** [Koenkk/zigbee-herdsman-converters#3354]
Adding support for [Salus Controls KL08RF 8 Zone Wiring Centre](https://salus-controls.com/uk/product/kl08rf/)
It is essentially a bunch of relays.

The first issue is that is reports Zigbee model 'undefined', how can I identify the device correctly so it can use the definition?
I have been looking at the converters for [other devices from the same manufacturer](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/salus_controls.js) but they appear to report the model directly.

The device leaves the network after a few seconds and starts the pairing process again.
Also, it reports raw manuSpecificPhilips messages.

This is the converter I'm using
``` js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['KL08RF'],
    model: 'KL08RF',
    vendor: 'Computime',
    description: 'Salus controls ZigBee network wireless wiring centre',
    fromZigbee: [],
    toZigbee: [],
    exposes: [],
    onfigure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(8);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genBasic']);
        await reporting.onOff(endpoint);
    },
};

module.exports = definition;
```

These are the debug logs
```
Info Device '0x001e5e0902678421' joined
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x001e5e0902678421","ieee_address":"0x001e5e0902678421"},"type":"device_joined"}'
Info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0x001e5e0902678421"},"type":"device_connected"}'
Info Starting interview of '0x001e5e0902678421'
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x001e5e0902678421","ieee_address":"0x001e5e0902678421","status":"started"},"type":"device_interview"}'
Info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x001e5e0902678421"},"type":"pairing"}'
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x001e5e0902678421","ieee_address":"0x001e5e0902678421"},"type":"device_announce"}'
Info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0x001e5e0902678421"},"type":"device_announced"}'
Info Succesfully changed options
Info MQTT publish: topic 'zigbee2mqtt/bridge/response/options', payload '{"data":{"restart_required":false},"status":"ok","transaction":"we3x0-2"}'
Debug Received Zigbee message from '0x001e5e0902678421', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 8 with groupID 0
Debug Skipping message, definition is undefined and still interviewing
Debug Received Zigbee message from '0x001e5e0902678421', type 'raw', cluster 'manuSpecificPhilips', data '{"data":[21,120,16,40,16,255,0,255,34,3,24,32],"type":"Buffer"}' from endpoint 8 with groupID 0
Debug Skipping message, definition is undefined and still interviewing
Debug Received Zigbee message from '0x001e5e0902678421', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 8 with groupID 0
Debug Skipping message, definition is undefined and still interviewing
Debug Received Zigbee message from '0x001e5e0902678421', type 'readResponse', cluster 'genBasic', data '{"manufacturerName":"Computime"}' from endpoint 8 with groupID 0
Debug Skipping message, definition is undefined and still interviewing
Debug Received Zigbee message from '0x001e5e0902678421', type 'readResponse', cluster 'genBasic', data '{"powerSource":0}' from endpoint 8 with groupID 0
Debug Skipping message, definition is undefined and still interviewing
Debug Received Zigbee message from '0x001e5e0902678421', type 'readResponse', cluster 'genBasic', data '{"zclVersion":0}' from endpoint 8 with groupID 0
Debug Skipping message, definition is undefined and still interviewing
Debug Received Zigbee message from '0x001e5e0902678421', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 8 with groupID 0
Debug Skipping message, definition is undefined and still interviewing
Debug Received Zigbee message from '0x001e5e0902678421', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 8 with groupID 0
Debug Skipping message, definition is undefined and still interviewing
Debug Received Zigbee message from '0x001e5e0902678421', type 'readResponse', cluster 'genBasic', data '{"hwVersion":197}' from endpoint 8 with groupID 0
Debug Skipping message, definition is undefined and still interviewing
Debug Received Zigbee message from '0x001e5e0902678421', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 8 with groupID 0
Debug Skipping message, definition is undefined and still interviewing
Debug Received Zigbee message from '0x001e5e0902678421', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 8 with groupID 0
Debug Skipping message, definition is undefined and still interviewing
Info Successfully interviewed '0x001e5e0902678421', device has successfully been paired
Warning Device '0x001e5e0902678421' with Zigbee model 'undefined' and manufacturer name 'Computime' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":null,"friendly_name":"0x001e5e0902678421","ieee_address":"0x001e5e0902678421","status":"successful","supported":false},"type":"device_interview"}'
Info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"friendly_name":"0x001e5e0902678421","supported":false},"type":"pairing"}'
Warning Device '0x001e5e0902678421' left the network
```

**Comment by przemekacx** [comment]
I'm looking forward for help from somebody's wiser than me :) I would like to create link between Nest Google thermostat and KL08RF.
Meanwhile you can take a look at this example:
https://github.com/jvitkauskas/pyit600
It uses gateway to collect data from known devices and set parameters to them. I managed to create python script which reports/connects/sets parameters for all Salus devices however the list is closed to sensors, if we could identify what device in these definitions KL08RF is, we could be closer to the solution.

**Comment by danieledwardgeorgehitchcock** [comment]
Hi,

I have just purchased one of these wiring centres and a gateway to begin creating device support for it.

Unfortunately, through sniffing the traffic, I can see that the device itself is quite dumb - it only has one endpoint.

There is more of a discussion on the Salus devices here #1524

If you look in the Salus app when the wiring centre is bound to the gateway, it is reported as a "Wireless Uncontrollable Device".

I also have a VS20WRF thermostat and on initial setup it requests to join the Zigbee network, then asks for a device ID and node ID for the wiring centre.

This leads me to a rough conclusion, that the wiring centre when joined to a Zigbee network, is just listening for On/Off commands on set groups and has no physical endpoints for manually actuating the relays.

If this is the case, then the only way it will work in Zigbee2MQTT, is if the group associations are the same between the two which isn't ideal for other devices also communicating using groups.

**Comment by przemekacx** [comment]
Attached some pic from KL08RF inside.
CO10RF is a Silicon Labs CP210x USB to UART Bridge, on KL there is a Zigbee board, anyone could maybe identify it? As for me communication from USB and from this Zigbee board goes via UART/I2C to PCF8575. Maybe a solution could be to communicate via this serial interface?
![20220227_162524](https://user-images.githubusercontent.com/92912562/156775377-1054a1a4-9b3a-4207-9c9f-ba3b0b86c846.jpg)
![20220304_141101](https://user-images.githubusercontent.com/92912562/156775386-8b880768-fa93-4881-a115-db5ae8a257be.jpg)
![20220304_141750](https://user-images.githubusercontent.com/92912562/156775402-5b10a476-ffc8-42a0-89b3-fc7ae1de5b40.jpg)
![20220304_141754](https://user-images.githubusercontent.com/92912562/156775421-44cbf18e-b8c2-4089-976e-e33905c16feb.jpg)
![20220304_141757](https://user-images.githubusercontent.com/92912562/156775438-8f13525a-d1d1-4cba-ad04-a7d3c6f89368.jpg)
![20220304_141802](https://user-images.githubusercontent.com/92912562/156775453-10d771f0-6354-489b-b1d6-a11fea895717.jpg)
![20220304_141808](https://user-images.githubusercontent.com/92912562/156775474-6f849dae-a3b3-4d76-a900-3aa79800d3e5.jpg)
