### ISSUE TITLE
multiple endpoints for blind controller

### ISSUE THREAD

**Issue by han-alink** [Koenkk/zigbee-herdsman-converters#3376]
Hi,
Have a device with 4 endpoints.  If I'm not explicitly exposing the endpoints, the first endpoint is working okay. 
As soon as I expose the first  endpoints:  e.cover_position_tilt().withEndpoint('l1') the tilt value is no longer displayed.
In both cases the values are reported by the device:

Zigbee2MQTT:debug 2021-11-18 11:45:18: Received MQTT message on 'zigbee2mqtt/0x00124b001bdd3fba/l1/set' with data '{"state":"OPEN"}'
Zigbee2MQTT:debug 2021-11-18 11:45:18: Publishing 'set' 'state' to '0x00124b001bdd3fba'
Zigbee2MQTT:debug 2021-11-18 11:45:25: Received Zigbee message from '0x00124b001bdd3fba', type 'attributeReport', cluster 'closuresWindowCovering', data '{"currentPositionTiltPercentage":100}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2021-11-18 11:45:25: MQTT publish: topic 'zigbee2mqtt/0x00124b001bdd3fba', payload '{"linkquality":94,"tilt":0}'

The device description:
 {
    zigbeeModel: ['BlindCtrl'],
    model: 'Controler for 4 blinds', 
    vendor: 'Alink',
    description: 'Device for the control of 4 blinds',
    fromZigbee: [fz.cover_position_tilt, fz.command_cover_open, fz.command_cover_close, fz.command_cover_stop],
    toZigbee: [tz.cover_state, tz.cover_position_tilt],
    exposes: [e.cover_position_tilt()],   //not working: [e.cover_position_tilt().withEndpoint('l1')],
    meta: {coverInverted: true}, // open = 100%, close = 0%
    meta: {multiEndpoint: true},
    endpoint: (device) => {
            return {l1: 1, l2: 2, l3: 3, l4: 4};    
            },
        configure: async (device, coordinatorEndpoint, logger) => {
            const overides = {min: 1, max: 3600};
            await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['closuresWindowCovering']);
            await reporting.currentPositionTiltPercentage(device.getEndpoint(1), overides);
            await reporting.bind(device.getEndpoint(2), coordinatorEndpoint, ['closuresWindowCovering']);
            await reporting.currentPositionTiltPercentage(device.getEndpoint(2), overides);
            await reporting.bind(device.getEndpoint(3), coordinatorEndpoint, ['closuresWindowCovering']);
            await reporting.currentPositionTiltPercentage(device.getEndpoint(3), overides);
            await reporting.bind(device.getEndpoint(4), coordinatorEndpoint, ['closuresWindowCovering']);
            await reporting.currentPositionTiltPercentage(device.getEndpoint(4), overides);
        },
    },    

What am I doing wrong? Appreciate some help!

**Comment by han-alink** [comment]
Found the error message:
Zigbee2MQTT:error 2021-11-18 17:10:23: Failed to call 'HomeAssistant' 'start' (AssertionError [ERR_ASSERTION]: Endpoint with tilt not supported for cover type
    at HomeAssistant.exposeToConfig (/app/lib/extension/homeassistant.ts:344:23)
    at HomeAssistant.populateMapping (/app/lib/extension/homeassistant.ts:659:54)
    at HomeAssistant.start (/app/lib/extension/homeassistant.ts:64:14)
    at Controller.callExtensions (/app/lib/controller.ts:312:17)
    at Controller.start (/app/lib/controller.ts:152:9)
    at start (/app/index.js:97:5))

Specific endpoints are not (yet) supported for a 'cover' device.
Is it possible to enable this?

**Comment by Koenkk** [comment]
Should be supported now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by han-alink** [comment]
Still seeing the same behavior. No error message anymore!

**Comment by Koenkk** [comment]
Could you provide the debug log when starting z2m?

**Comment by han-alink** [comment]
Part of the logfile related to the blind controller:

Zigbee2MQTT:debug 2021-11-19 11:06:36: Received MQTT message on 'homeassistant/cover/0x00124b001bdd3fba/cover_l1/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"command_topic":"zigbee2mqtt/0x00124b001bdd3fba/l1/set","device":{"identifiers":["zigbee2mqtt_0x00124b001bdd3fba"],"manufacturer":"Alink","model":"Device for the control of 4 blinds (Controler for 4 blinds)","name":"0x00124b001bdd3fba"},"json_attributes_topic":"zigbee2mqtt/0x00124b001bdd3fba","name":"0x00124b001bdd3fba l1","position_template":"{{ value_json.position_l1 }}","position_topic":"zigbee2mqtt/0x00124b001bdd3fba","set_position_template":"{ \"position_l1\": {{ position }} }","set_position_topic":"zigbee2mqtt/0x00124b001bdd3fba/l1/set","tilt_command_topic":"zigbee2mqtt/0x00124b001bdd3fba/l1/set/tilt","tilt_status_template":"{{ value_json.tilt_l1 }}","tilt_status_topic":"zigbee2mqtt/0x00124b001bdd3fba","unique_id":"0x00124b001bdd3fba_cover_l1_zigbee2mqtt"}'

**Comment by han-alink** [comment]
Issuing the OPEN command, the following log lines are generated:

Zigbee2MQTT:debug 2021-11-19 11:25:07: Received MQTT message on 'zigbee2mqtt/0x00124b001bdd3fba/l1/set' with data '{"state_l1":"OPEN"}'
Zigbee2MQTT:debug 2021-11-19 11:25:07: Publishing 'set' 'state' to '0x00124b001bdd3fba'
Zigbee2MQTT:debug 2021-11-19 11:25:10: Saving state to file /config/zigbee2mqtt/state.json
Zigbee2MQTT:debug 2021-11-19 11:25:15: Received Zigbee message from '0x00124b001bdd3fba', type 'attributeReport', cluster 'closuresWindowCovering', data '{"currentPositionTiltPercentage":100}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2021-11-19 11:25:15: MQTT publish: topic 'zigbee2mqtt/0x00124b001bdd3fba', payload '{"linkquality":86,"tilt":0}'

**Comment by Koenkk** [comment]
seems the `fz.cover_position_tilt` doesn't support `multiEndpoint` yet, added this now. With this change you should see e.g. `tilt_l1` instead of `tilt` in the published payload.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by han-alink** [comment]
Thanks, this solved the issue. When will these changes appear in the "non" dev branche?

**Comment by Koenkk** [comment]
yes, with the next z2m release on 1 december

**Comment by han-alink** [comment]
One more question related to this device. The lovelace display of this device is able to change the color of the icon depending on the value of the tilt percentage. I have another "lift" type device (not multi endpoint), and the lovelace representation is coloring dependant on its state. Is the fact that this is not working for the tilt device a zigbee2mqtt issue?

**Comment by Koenkk** [comment]
@han-alink that sounds like a HA issue.

**Comment by han-alink** [comment]
Well ...
This is the report of a single endpoint lift device:
Zigbee2MQTT:debug 2021-11-23 16:47:23: Received Zigbee message from 'Shade Attic', type 'attributeReport', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":0}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2021-11-23 16:47:23: MQTT publish: topic 'zigbee2mqtt/Shade Attic', payload '{"linkquality":9,"position":100}'

And this is from a multi endpoint tilt device:
Zigbee2MQTT:debug 2021-11-23 16:44:06: Received Zigbee message from 'Blinds', type 'attributeReport', cluster 'closuresWindowCovering', data '{"currentPositionTiltPercentage":100}' from endpoint 2 with groupID 0
Zigbee2MQTT:info  2021-11-23 16:44:06: MQTT publish: topic 'zigbee2mqtt/Blinds', payload '{"linkquality":78,"tilt_l1":0,"tilt_l2":0,"tilt_l3":0,"tilt_l4":0}'

The first device is publishing a "position". The second device a "tilt".

**Comment by Koenkk** [comment]
That is expected, right?

**Comment by han-alink** [comment]
No, I expected a "lift" for the first device and a "tilt" for the second.
Or: a "position" for both devices.

**Comment by Koenkk** [comment]
In z2m, `currentPositionLiftPercentage` is mapped to `position`, `currentPositionTiltPercentage` to `tilt.

**Comment by han-alink** [comment]
I see, thanks.

**Comment by han-alink** [comment]
Not sure if I should address this subject here, but as it's about the same device and maybe due to the multiple endpoint settings. If I should address this somewhere else, let me know ...   
The device description contains the following line: meta: {coverInverted: true}, // open = 100%, close = 0%.This does not invert the position values.
Also: this setting is not reflected in the zigbee2mqtt dashboard "Instellingen (specifiek)". Only if I set the value to TRUE in the dashboard, the values are represented correctly.

**Comment by Koenkk** [comment]
@han-alink could you share the definition?

**Comment by han-alink** [comment]
As requested:
    zigbeeModel: ['BlindCtrl'], // The model ID.
    model: 'Controller for 4 blinds', 
    vendor: 'Alink',
    description: 'Device for the control of 4 blinds',
    fromZigbee: [fz.cover_position_tilt, fz.command_cover_open, fz.command_cover_close, fz.command_cover_stop],
    toZigbee: [tzLocal.cover_state, tz.cover_position_tilt],
    exposes: [e.cover_position().withEndpoint('l1'), e.cover_position().withEndpoint('l2'),e.cover_position().withEndpoint('l3'),e.cover_position().withEndpoint('l4') ],
    meta: {coverInverted: true}, // open = 100%, close = 0%
    meta: {multiEndpoint: true},
    endpoint: (device) => {
            return {l1: 1, l2: 2, l3: 3, l4: 4};    
            },
        configure: async (device, coordinatorEndpoint, logger) => {
            const overides = {min: 1, max: 3600};
            await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['closuresWindowCovering']);
            await reporting.currentPositionLiftPercentage(device.getEndpoint(1), overides);
            await reporting.bind(device.getEndpoint(2), coordinatorEndpoint, ['closuresWindowCovering']);
            await reporting.currentPositionLiftPercentage(device.getEndpoint(2), overides);
            await reporting.bind(device.getEndpoint(3), coordinatorEndpoint, ['closuresWindowCovering']);
            await reporting.currentPositionLiftPercentage(device.getEndpoint(3), overides);
            await reporting.bind(device.getEndpoint(4), coordinatorEndpoint, ['closuresWindowCovering']);
            await reporting.currentPositionLiftPercentage(device.getEndpoint(4), overides);
        },
    },

**Comment by Koenkk** [comment]
the double meta is wrong, they will overwrite each other, use: `meta: {multiEndpoint: true, coverInverted: true},`

**Comment by han-alink** [comment]
yep! Thanks for your help
