### ISSUE TITLE
Hue color floor LCF003

### ISSUE THREAD

**Issue by Matt77CHE** [Koenkk/zigbee-herdsman-converters#3380]
Hi 
I tried to connect to the Philips Hue color floor (mod LCF003).
in Log it shows "Error: Device 0x00178801062bd9a5 "LCF003" not described in statesMapping.. undefined"

I went to the page of support zigbee to mqtt; it looked like there is a 'Hue Signe floor light' - but with a different mod number: "4080248P9"

I was reading the part with somehow to add devices - but I didn't get it how to do this...

Would it be possible to add this device? - Or help me how to get it done?

**Comment by danieledwardgeorgehitchcock** [comment]
Hi,

You should just need to add the model number to the existing zigbeeModel entry in philips.js i.e. `['4080248P9', 'LCF003']` if they are indeed the same fixtures.

You will also need to find the supported colour temperatures of the device too. to do that, follow [this guide](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_3-adding-converter-s-for-your-device).

Once you have done that, please submit a Pull Request in this repo with the changes, or post up the device entry in this post and one of us will submit it on your behalf

**Comment by Matt77CHE** [comment]
... Ok, but there is only one  problem - I have no clue how to do this; I mean I've red all this things, but I still have no clue how to do this...

**Comment by danieledwardgeorgehitchcock** [comment]
Are you using the Home Assistant addon / Docker container / Other?

**Comment by Matt77CHE** [comment]
I'm using a intel nuc - there is proxmox installed and iobroker runs in a container..... in iobroker runs the zigbee adapter.

**Comment by danieledwardgeorgehitchcock** [comment]
You could use a program like MQTT Explorer to send and read the commands
