### ISSUE TITLE
PRZ01 can't pair

### ISSUE THREAD

**Issue by Tao173** [Koenkk/zigbee-herdsman-converters#3394]
I have a PRZ01 device from J.XUAN, I got it today and tried to pair it, but everything is not so easy, it shows an error.
This is the official support link: 
https://www.zigbee2mqtt.io/devices/PRZ01.html

The current connection situation:
it has the link signal quality, but no other information.

This is the error message of the pairing time:
Warning Received message from unsupported device with Zigbee model 'undefined' and manufacturer name 'Beesmart'
Warning Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.

I need some help.

**Comment by lcuwx2016** [comment]
Hi @Tao173 
I have same problem. How did you fix it?
