### ISSUE TITLE
GLEDOPTO GL-C-001P

### ISSUE THREAD

**Issue by slopy** [Koenkk/zigbee-herdsman-converters#3398]
Hello, 

I have been trying to add GLEDOPTO `GL-C-001P` (https://www.gledopto.com/h-col-388.html) but it is being discovered as  `GL-C-007P`
After playing with it as `GL-C-007P` I can it is quite unstable. Seems like when I try to set color temp from outside of range it starts blinking. There are other combination that forces controller to switch from RGBW mode to RGBCTT and then hangs on blinking.
My question is if are you planning to add this device? If not, do you have any advice how can I try to write my own support for this controller?

**Comment by pixeldoc2000** [comment]
Please post your device entry in zigbee2mqtt `database.db`.

Maybe it is a bug in the Device Firmware returning the wrong Device modelId ?

**Comment by slopy** [comment]
Sorry but I have returned this controller. Seems like there was an issue with power supply so it has some weird behavior.
