### ISSUE TITLE
QBKG26LM Does not support two-button press actions

### ISSUE THREAD

**Issue by gnep88** [Koenkk/zigbee-herdsman-converters#3399]
For Aqara 3 button switch (QBKG26LM, lumi.switch.n3acn3, Aqara D1 3 gang smart wall switch (with neutral wire)), there are official supported two-button press actions which sends following messages, seems to be not supported by z2m yet, could you please add the support ? Thank you.

Button 1 and 2 pressed at the same time, receives following message:

Received Zigbee message from '次卧开关', type 'attributeReport', cluster 'genMultistateInput', data '{"presentValue":1}' from endpoint 51 with groupID 0

Button 1 and 3 pressed at the same time, receives following message:

Debug Received Zigbee message from '次卧开关', type 'attributeReport', cluster 'genMultistateInput', data '{"presentValue":1}' from endpoint 52 with groupID 0

Button 2 and 3 pressed at the same time, receives following message:

Debug Received Zigbee message from '次卧开关', type 'attributeReport', cluster 'genMultistateInput', data '{"presentValue":1}' from endpoint 53 with groupID 0

**Comment by z-x-f** [comment]
@gnep88 Will it report <code>data'{"presentValue":2}</code> when the button is double-clicked?

**Comment by gnep88** [comment]
@z-x-f yes I can see it is reporting that value when any button is double-clicked.

**Comment by z-x-f** [comment]
@gnep88 我创建了个PR来对这个型号支持更多的动作，另外还有一些其他修改的想法，但是我没有这个设备测试，你可以帮忙吗？
