### ISSUE TITLE
Osram/Ledvance supports a different mired profile

### ISSUE THREAD

**Issue by Burki24** [Koenkk/zigbee-herdsman-converters#3405]
Hi,

how to change the mired-profile for the Osram/Levance 4058075148338 /(PAR16 TW Z3). As in that profile a range from 150 - 500 mired is fixed. The Bulb only have a range from 153-370 mired. I am firm in adding Tuya-Devices, but not able at the moment, to change the profile for Ledvance/Osram bulbs. Is their a possibility for someone to help?

P.S.: I saw, that this problem exists on different bulbs. It also has impact on some Hue Bulbs (Hue White ambience E14 153-454)

Thanks in advance 
Burkhard

**Comment by danieledwardgeorgehitchcock** [comment]
Hi,

You can follow [this guide](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_3-1-retrieving-color-temperature-range-only-required-for-lights-which-support-color-temperature) for doing that

**Comment by Burki24** [comment]
Hi @danieledwardgeorgehitchcock ,
thanks for that hint. I didn't saw it. So, I will update the color_temp range for the Bulbs, I have.
