### ISSUE TITLE
Add new Heiman Device

### ISSUE THREAD

**Issue by eole210** [Koenkk/zigbee-herdsman-converters#3422]
Hi,
Not sure this is the right way to ask for for an update, if not, my sincere apologies.
I am trying to add a new Heiman device and I am following http://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
documentation. The new device is a CO2 sensor "HS3AQ-EFA-3.0", which is, I guess the replacement of HS2AQ-EM.
Using the code written for HS2AQ-EM, in heiman.js, I created my own HS3AQ-EFA-3.0.js file and converter uses it just fine. However, although I am correctly getting temperature and humidity (in Home Assistant + Zigbee2MQTT), I am missing the main one: the CO2 value.

<img src="https://user-images.githubusercontent.com/23704895/143711001-ef552c89-f705-45cb-9bbe-4ad77d712eb3.png" width="400" height="300">

Log says:
```
debug 2021-11-27 13:37:25: Received Zigbee message from 'Heiman_CO2_Sensor_01', type 'raw', cluster 'heimanSpecificAirQuality', data '{"data":[9,73,2],"type":"Buffer"}' from endpoint 1 with groupID 0
debug 2021-11-27 13:37:25: No converter available for 'HS3AQ-EFA-3.0' with cluster 'heimanSpecificAirQuality' and type 'raw' and data '{"data":[9,73,2],"type":"Buffer"}'
```
I tried to understand the code to see what needed to be modified but I it is too complicate for me.

I understand you may not have the device handy but I am ready to test anything you'd ask me.
Thanks!
Eole

**Comment by eole210** [comment]
Is there any workflow available describing the flow of data from sensor to Zigbee2MQTT? I am trying to wrap my head around this but I really don't know how to convert this data:
`data '{"data":[9,73,2],"type":"Buffer"}'`
to valid CO2 value.

Humidity, for example, is correctly received and correctly converted (i.e. no "_No converter available..._" message):
` Received Zigbee message from 'Heiman_CO2_Sensor_01', type 'attributeReport', cluster 'msRelativeHumidity', data '{measuredValue:4568}' from endpoint 1 with groupID 0`


Thanks!

**Comment by eole210** [comment]
I see that my post is not getting any traction, I am a bit surprised since the article mentioned "In case you require any help feel free to create an issue". The reasons for that silence are probably good but it is not helping.
Can someone at least let me know if the work I have to do resides in modifying my local "js" file or in modifying the GitHub file "heiman.js" (creating a new fork/branch I guess)? And IF the latter, how can I have my local Home Assistant Zigbee2MQTT add-on point to that potential new 'heiman.js" file?

**Comment by eole210** [comment]
up

**Comment by sh4rks** [comment]
Hello

try this:


module.exports = [
    {
        zigbeeModel: ['HS3AQ-EFA-3.0'],
        model: 'HS3AQ',
        vendor: 'HEIMAN',
        description: 'Air quality monitor',
        fromZigbee: [fz.co2, fz.battery, fz.temperature, fz.humidity],
        toZigbee: [],
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, [
                'genPowerCfg', 'genTime', 'msTemperatureMeasurement', 'msRelativeHumidity','heimanSpecificAirQuality']);

            await reporting.batteryPercentageRemaining(endpoint);
            await reporting.temperature(endpoint);
            await reporting.humidity(endpoint);

            await endpoint.read('genPowerCfg', ['batteryPercentageRemaining']);

            // Seems that it is bug in HEIMAN, device does not asks for the time with binding
            // So, we need to write time during configure
            const time = Math.round(((new Date()).getTime() - constants.OneJanuary2000) / 1000);
            // Time-master + synchronised
            const values = {timeStatus: 3, time: time, timeZone: ((new Date()).getTimezoneOffset() * -1) * 60};
            endpoint.write('genTime', values);
        },
        exposes: [e.co2(), e.battery(), e.temperature(), e.humidity()],
    },
];

**Comment by eole210** [comment]
Thanks @sh4rks 
Unfortunately, same issue...

**Comment by sh4rks** [comment]
The device is supported now. Try to update your z2m instance.
