### ISSUE TITLE
genBasic powerSource Attribute - Battery backup

### ISSUE THREAD

**Issue by Wh1terat** [Koenkk/zigbee-herdsman-converters#3429]
Hi,

It's been bugging me that my HEIMAN sirens show as unknown power in z2m:
<img width="1250" alt="Screenshot 2021-11-28 at 22 15 15" src="https://user-images.githubusercontent.com/1288525/143788201-32163b45-ae47-4bde-bd40-d41da3fc32f4.png">

From what I can see, you are not looking at the last bit in powerSource which denotes battery backup:
<img width="634" alt="Screenshot 2021-11-28 at 22 00 36" src="https://user-images.githubusercontent.com/1288525/143788205-b52cbc8f-1dde-4dac-ab16-4aa33f8aecf7.png">

The device is reporting correctly:
```json
            "clusters": {
                "genBasic": {
                    "attributes": {
                        "modelId": "WarningDevice-EF-3.0",
                        "manufacturerName": "HEIMAN",
                        **"powerSource": 129,**
                        "zclVersion": 3,
                        "appVersion": 17,
                        "stackVersion": 2,
                        "hwVersion": 5,
                        "dateCode": "2021.4.8"
                    }
                },
```

**Comment by Wh1terat** [comment]
Or should I raise to Koenkk/zigbee-herdsman ?

**Comment by Koenkk** [comment]
This should be fixed here: https://github.com/Koenkk/zigbee-herdsman/blob/6975c68298d2a14eec6616beba93db796671b21d/src/controller/model/device.ts#L86 , could you make a fix?

**Comment by Wh1terat** [comment]
JS not really my forte.

The quick fix would be simply to add 128-134  with appropriate descriptions to:
https://github.com/Koenkk/zigbee-herdsman/blob/master/src/zcl/definition/powerSource.ts

e.g
```typescript
const powerSource: {[s: number]: string} = {
    0: 'Unknown',
    1: 'Mains (single phase)',
    2: 'Mains (3 phase)',
    3: 'Battery',
    4: 'DC Source',
    5: 'Emergency mains constantly powered',
    6: 'Emergency mains and transfer switch'
    128: 'Unknown (w/ battery backup)',
    129: 'Mains (single phase) (w/ battery backup)'',
    130: 'Mains (3 phase) (w/ battery backup)'',
    131: 'Battery (w/ battery backup)'',
    132: 'DC Source (w/ battery backup)'',
    133: 'Emergency mains constantly powered (w/ battery backup)',
    134: 'Emergency mains and transfer switch (w/ battery backup)'    
};
```

But feels a bit hacky, feels like it would be better with some kind of "has backup battery" attr but appreciate the rework required is somewhat more substantial.

**Comment by Koenkk** [comment]
@Wh1terat the device is mains powered right? Then my preference would be to mark this as AC powered, otherwise existing code which checks on the `powerSource` also has to be adapted.

**Comment by Wh1terat** [comment]
@Koenkk Primarily mains powered but does support running off it's internal backup battery.

The spec (2nd screenshot) is from Zigbee alliance ZCL spec, so it feels like it should be handled appropriately rather than just drop that last bit and pretend it's mains only.

Bit confused as to why they didn't break it out into it's own attribute, but I'm sure they had their reasons.

I appreciate it does require quite the rework to be handled properly, but the spec is the spec - if device manufacturers have bothered to follow it (unusual I know) it seems only right to respect that.

**Comment by Wh1terat** [comment]
Could meet in the middle?

```
powerSource = _powerSource & ~(1 << 7)
hasBatteryBackup = !!(_powerSource >> 7)
```

Can implement hasBatteryBackup logic as/when then without breaking anything currently?

**Comment by Koenkk** [comment]
@Wh1terat where do you plan to use `hasBatteryBackup` ?

**Comment by Wh1terat** [comment]
@Koenkk Can't say _I'm_ going to use it anywhere per se, but could be used in nurikk/zigbee2mqtt-frontend

**Comment by Koenkk** [comment]
@Wh1terat lets add it when there is really a use case for it, anyway with the latest dev branch the power source should be correct now (applied your suggestion from https://github.com/Koenkk/zigbee-herdsman-converters/issues/3429#issuecomment-981940880)

**Comment by Wh1terat** [comment]
@Koenkk 
RFC2119:
```
1. MUST - This word, or the terms "REQUIRED" or **"SHALL",** mean that the
   definition is an absolute requirement of the specification.
```

ZCL Spec:
```
Bit b7 of this attribute SHALL be set to 1 if the device has a secondary power source in the form of a battery
backup. Otherwise, bit b7 SHALL be set to 0.
```

If it's "an absolute requirement" for end devices to report this state it seems incorrect behaviour to simply ignore it.

I suspect we'll have to agree to disagree about this one 😉

**Comment by sammyke007** [comment]
My Heimann still shows "?"
anything else that has to be done after upgrading to 1.22.1?

![image](https://user-images.githubusercontent.com/33524412/144302105-8622f979-1bb2-4129-b83e-5b703db177db.png)

**Comment by sammyke007** [comment]
Devconsole shows 129 correct I think?

![image](https://user-images.githubusercontent.com/33524412/144302521-238810ba-7321-4f38-847f-fe489c1cd499.png)

**Comment by sammyke007** [comment]
Alright it's ok now. 
I've added this:
![image](https://user-images.githubusercontent.com/33524412/144328600-d6e58bda-c446-4d80-89e4-d9a4b6a0b3c5.png)
But probably I wasn't patient enough and this might be not necessary...
