### ISSUE TITLE
Add support for Heiman 'SmartPlug' smart power plug

### ISSUE THREAD

**Issue by mitnits** [Koenkk/zigbee-herdsman-converters#343]
Please consider adding support for Heiman 'SmartPlug' plug and power meter device. They work fine with SmartThings BTW, here is some of device info from SmartThings that I pulled

Name                Heiman Zigbee Smart Metering Plug                                                                                                                                              
Type                  ZigBee Switch Power                                                                                                                                                            
Zigbee Id           000D6F000D3D740B                                                                                                                                                               
Device Network Id   C6BB                                                                                                                                                                           
Data                     application:11  endpointId:01   manufacturer:Heiman   model:SmartPlug                                                                                                                        
Raw Description   01 0104 0051 00 07 0000 0003 0004 0006 0009 0702 0B04 02 0003 0019                                                                                                             
Firmware              Current Version: 0x00000011 Target Version: 0x00000011                                                                                                                         
Current States      switch: on power: 0.0                                                                                                                                                          

I'm actually OK with the support for simple on/off, power reporting is not critical....

**Comment by Koenkk** [comment]
Please follow http://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

**Comment by mitnits** [comment]
Added

    {
        zigbeeModel: ['SmartPlug'],
	model: 'HS2SK',
        description: 'Heiman Smart Metering Plug',
        supports: 'on/off, power measurement',
        vendor: 'Heiman',
        fromZigbee: [],
        toZigbee: [],
    },


to the devices.js

Paired

Now I see 

 "0x000d6f0011088774" [style="rounded", label="{0x000d6f0011088774|Router|Heiman Heiman Smart Metering Plug (HS2SK)|online}"];

in network map (sorry, no idea how to list devices otherwise)

I do have 2nd plug just like the 1st one, and that refuses to pair now saying:

Mar 14 18:41:36 hassbian npm[13833]:   zigbee2mqtt:warn 3/14/2019, 6:41:36 PM Message without device!




Mar 14 18:41:52 hassbian npm[13833]:   zigbee2mqtt:warn 3/14/2019, 6:41:52 PM Device with modelID 'undefined' is not supported.
Mar 14 18:41:52 hassbian npm[13833]:   zigbee2mqtt:warn 3/14/2019, 6:41:52 PM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
Mar 14 18:41:53 hassbian npm[13833]:   zigbee2mqtt:warn 3/14/2019, 6:41:53 PM Message without device!

No idea what I am doing wrong here though.


The next step in the new device support calls for "triggering action on device" - but it's an on/off plug.... What can I trigger there?

**Comment by mitnits** [comment]
Hmm, took the 1st device out of power socket, now it disappeared from the map...

Any attempt to pair it results in logs like:

Mar 14 18:52:49 hassbian npm[14053]:   zigbee2mqtt:warn 3/14/2019, 6:52:49 PM Device with modelID 'undefined' is not supported.
Mar 14 18:52:49 hassbian npm[14053]:   zigbee2mqtt:warn 3/14/2019, 6:52:49 PM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
Mar 14 18:52:52 hassbian npm[14053]:   zigbee2mqtt:info 3/14/2019, 6:52:52 PM Device incoming...
Mar 14 18:52:52 hassbian npm[14053]:   zigbee2mqtt:info 3/14/2019, 6:52:52 PM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"device incoming"}'
Mar 14 18:53:35 hassbian npm[14053]:   zigbee2mqtt:warn 3/14/2019, 6:53:35 PM Device with modelID 'undefined' is not supported.
Mar 14 18:53:35 hassbian npm[14053]:   zigbee2mqtt:warn 3/14/2019, 6:53:35 PM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
Mar 14 18:53:38 hassbian npm[14053]:   zigbee2mqtt:info 3/14/2019, 6:53:38 PM Device incoming...
Mar 14 18:53:38 hassbian npm[14053]:   zigbee2mqtt:info 3/14/2019, 6:53:38 PM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"device incoming"}'

**Comment by mitnits** [comment]
This is what I see in database.db - so it might actually be working (but only one of the two plugs, for some reason, maybe one is bad?)


{"id":12,"type":"Router","ieeeAddr":"0x000d6f0011088774","nwkAddr":44761,"manufId":4619,"manufName":"Heiman","powerSource":"Mains (single phase)","modelId":"SmartPlug","epList":[1],"status":"online","joinTime":1552584031,"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,3,4,6,9,1794,2820],"outClusterList":[3,25],"clusters":{"genBasic":{"dir":{"value":1},"attrs":{"65533":1,"zclVersion":2,"appVersion":17,"hwVersion":16,"manufacturerName":"Heiman","modelId":"SmartPlug","dateCode":"2018.1.11","powerSource":1}},"genIdentify":{"dir":{"value":3},"attrs":{"65533":1,"identifyTime":0}},"genGroups":{"dir":{"value":1},"attrs":{"65533":1,"nameSupport":0}},"genOnOff":{"dir":{"value":1},"attrs":{"65533":1,"onOff":0}},"genAlarms":{"dir":{"value":1},"attrs":{"65533":1}},"genOta":{"dir":{"value":2},"attrs":{}},"seMetering":{"dir":{"value":1},"attrs":{"65533":1,"currentSummDelivered":{"0":0,"1":0},"status":0,"unitOfMeasure":0,"multiplier":1,"divisor":10000,"summaFormatting":170,"demandFormatting":163,"meteringDeviceType":0,"instantaneousDemand":421}},"haElectricalMeasurement":{"dir":{"value":1},"attrs":{"65533":1,"measurementType":0,"rmsVoltage":23495,"rmsCurrent":41,"activePower":399,"acVoltageMultiplier":1,"acVoltageDivisor":100,"acCurrentMultiplier":1,"acCurrentDivisor":100,"acPowerMultiplier":1,"acPowerDivisor":10,"acAlarmsMask":0,"acVoltageOverload":-1,"acCurrentOverload":-1,"acActivePowerOverload":-1}}}}},"_id":"AwVFfDnwVyP9flEp"}
{"id":12,"type":"Router","ieeeAddr":"0x000d6f0011088774","nwkAddr":44761,"manufId":4619,"manufName":"Heiman","powerSource":"Mains (single phase)","modelId":"SmartPlug","epList":[1],"status":"offline","joinTime":null,"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,3,4,6,9,1794,2820],"outClusterList":[3,25],"clusters":{"genBasic":{"dir":{"value":1},"attrs":{"65533":1,"zclVersion":2,"appVersion":17,"hwVersion":16,"manufacturerName":"Heiman","modelId":"SmartPlug","dateCode":"2018.1.11","powerSource":1}},"genIdentify":{"dir":{"value":3},"attrs":{"65533":1,"identifyTime":0}},"genGroups":{"dir":{"value":1},"attrs":{"65533":1,"nameSupport":0}},"genOnOff":{"dir":{"value":1},"attrs":{"65533":1,"onOff":0}},"genAlarms":{"dir":{"value":1},"attrs":{"65533":1}},"genOta":{"dir":{"value":2},"attrs":{}},"seMetering":{"dir":{"value":1},"attrs":{"65533":1,"currentSummDelivered":{"0":0,"1":0},"status":0,"unitOfMeasure":0,"multiplier":1,"divisor":10000,"summaFormatting":170,"demandFormatting":163,"meteringDeviceType":0,"instantaneousDemand":421}},"haElectricalMeasurement":{"dir":{"value":1},"attrs":{"65533":1,"measurementType":0,"rmsVoltage":23495,"rmsCurrent":41,"activePower":399,"acVoltageMultiplier":1,"acVoltageDivisor":100,"acCurrentMultiplier":1,"acCurrentDivisor":100,"acPowerMultiplier":1,"acPowerDivisor":10,"acAlarmsMask":0,"acVoltageOverload":-1,"acCurrentOverload":-1,"acActivePowerOverload":-1}}}}},"_id":"AwVFfDnwVyP9flEp"}
{"id":12,"type":"Router","ieeeAddr":"0x000d6f0011088774","nwkAddr":41843,"manufId":4619,"epList":[1],"status":"online","joinTime":1552584201,"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,3,4,6,9,1794,2820],"outClusterList":[3,25],"clusters":{}}},"_id":"pKip8zYGNMBBUXFy"}
{"id":12,"type":"Router","ieeeAddr":"0x000d6f0011088774","nwkAddr":41843,"manufId":4619,"manufName":"Heiman","powerSource":"Mains (single phase)","modelId":"SmartPlug","epList":[1],"status":"online","joinTime":1552584201,"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,3,4,6,9,1794,2820],"outClusterList":[3,25],"clusters":{}}},"_id":"pKip8zYGNMBBUXFy"}
{"id":12,"type":"Router","ieeeAddr":"0x000d6f0011088774","nwkAddr":41843,"manufId":4619,"manufName":"Heiman","powerSource":"Mains (single phase)","modelId":"SmartPlug","epList":[1],"status":"online","joinTime":1552584201,"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,3,4,6,9,1794,2820],"outClusterList":[3,25],"clusters":{"genBasic":{"dir":{"value":1},"attrs":{"65533":1,"zclVersion":2,"appVersion":17,"hwVersion":16,"manufacturerName":"Heiman","modelId":"SmartPlug","dateCode":"2018.1.11","powerSource":1}},"genIdentify":{"dir":{"value":3},"attrs":{"65533":1,"identifyTime":0}},"genGroups":{"dir":{"value":1},"attrs":{"65533":1,"nameSupport":0}},"genOnOff":{"dir":{"value":1},"attrs":{"65533":1,"onOff":0}},"genAlarms":{"dir":{"value":1},"attrs":{"65533":1}},"genOta":{"dir":{"value":2},"attrs":{}},"seMetering":{"dir":{"value":1},"attrs":{"65533":1,"currentSummDelivered":{"0":0,"1":0},"status":0,"unitOfMeasure":0,"multiplier":1,"divisor":10000,"summaFormatting":170,"demandFormatting":163,"meteringDeviceType":0,"instantaneousDemand":0}},"haElectricalMeasurement":{"dir":{"value":1},"attrs":{"65533":1,"measurementType":0,"rmsVoltage":23447,"rmsCurrent":0,"activePower":0,"acVoltageMultiplier":1,"acVoltageDivisor":100,"acCurrentMultiplier":1,"acCurrentDivisor":100,"acPowerMultiplier":1,"acPowerDivisor":10,"acAlarmsMask":0,"acVoltageOverload":-1,"acCurrentOverload":-1,"acActivePowerOverload":-1}}}}},"_id":"pKip8zYGNMBBUXFy"}

**Comment by Koenkk** [comment]
Please try with the following : 

```js
{
        zigbeeModel: ['SmartPlug'],
        model: 'HS2SK',
        description: 'Smart metering plug',
        supports: 'on/off, power measurement',
        vendor: 'Heiman',
        fromZigbee: [fz.state, fz.ignore_onoff_change, fz.ignore_electrical_change, fz.Z809A_power],
        toZigbee: [tz.on_off],
        configure: (ieeeAddr, shepherd, coordinator, callback) => {
            const device = shepherd.find(ieeeAddr, 1);
            const actions = [
                (cb) => device.report('haElectricalMeasurement', 'rmsVoltage', 1, 1000, 1, cb),
                (cb) => device.report('haElectricalMeasurement', 'rmsCurrent', 1, 1000, 1, cb),
                (cb) => device.report('haElectricalMeasurement', 'activePower', 1, 1000, 1, cb),
            ];

            execute(device, actions, callback);
        },
    },
```

**Comment by mitnits** [comment]
Ok, again, with just one device, now I get:
Mar 17 20:17:50 hassbian npm[13413]:   zigbee2mqtt:info 3/17/2019, 8:17:50 PM MQTT publish: topic 'zigbee2mqtt/0x000d6f000b7a777b', payload '{"state":"OFF","linkquality":23}'
Mar 17 20:17:52 hassbian npm[13413]:   zigbee2mqtt:info 3/17/2019, 8:17:52 PM MQTT publish: topic 'zigbee2mqtt/0x000d6f000b7a777b', payload '{"state":"OFF","linkquality":7,"power":0,"current":0,"voltage":65535}'
Mar 17 20:17:52 hassbian npm[13413]:   zigbee2mqtt:info 3/17/2019, 8:17:52 PM MQTT publish: topic 'zigbee2mqtt/0x000d6f000b7a777b', payload '{"state":"OFF","linkquality":5}'
Mar 17 20:17:52 hassbian npm[13413]:   zigbee2mqtt:info 3/17/2019, 8:17:52 PM MQTT publish: topic 'zigbee2mqtt/0x000d6f000b7a777b', payload '{"state":"OFF","linkquality":13}'
Mar 17 20:17:52 hassbian npm[13413]:   zigbee2mqtt:info 3/17/2019, 8:17:52 PM Device incoming...
Mar 17 20:17:52 hassbian npm[13413]:   zigbee2mqtt:info 3/17/2019, 8:17:52 PM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"device incoming"}'
Mar 17 20:18:04 hassbian npm[13413]:   zigbee2mqtt:warn 3/17/2019, 8:18:04 PM Failed to configure 0x000d6f000b7a777b (0x000d6f000b7a777b) ('Error: Timed out after 10000 ms') (attempt #1)
Mar 17 20:18:04 hassbian npm[13413]:   zigbee2mqtt:warn 3/17/2019, 8:18:04 PM This can be ignored if the device is working properly


Now both devices seem to pair though...

**Comment by mitnits** [comment]
FYI, manually pressing on/off button on the device does not result in any new log messages

**Comment by mitnits** [comment]
Connecting load does result in the following messages:

Mar 17 20:22:42 hassbian npm[13413]:   zigbee2mqtt:info 3/17/2019, 8:22:42 PM MQTT publish: topic 'zigbee2mqtt/0x000d6f0011088774', payload '{"power":323,"voltage":23600,"linkquality":21}'
Mar 17 20:22:49 hassbian npm[13413]:   zigbee2mqtt:info 3/17/2019, 8:22:49 PM MQTT publish: topic 'zigbee2mqtt/0x000d6f0011088774', payload '{"power":531,"current":39,"linkquality":21}'
Mar 17 20:22:58 hassbian npm[13413]:   zigbee2mqtt:info 3/17/2019, 8:22:58 PM MQTT publish: topic 'zigbee2mqtt/0x000d6f0011088774', payload '{"power":581,"voltage":23595,"linkquality":21}

**Comment by mitnits** [comment]
This is what happens (when load connected) when I press on/off button:
Button pressed (off)
Mar 17 20:23:38 hassbian npm[13413]:   zigbee2mqtt:info 3/17/2019, 8:23:38 PM MQTT publish: topic 'zigbee2mqtt/0x000d6f0011088774', payload '{"power":581,"current":0,"linkquality":21}'
Mar 17 20:23:47 hassbian npm[13413]:   zigbee2mqtt:info 3/17/2019, 8:23:47 PM MQTT publish: topic 'zigbee2mqtt/0x000d6f0011088774', payload '{"power":0,"linkquality":21}'


Button pressed again (on)
Mar 17 20:24:12 hassbian npm[13413]:   zigbee2mqtt:info 3/17/2019, 8:24:12 PM MQTT publish: topic 'zigbee2mqtt/0x000d6f0011088774', payload '{"power":198,"voltage":23582,"linkquality":18}'

**Comment by mitnits** [comment]
Other device got paired too, interestingly it reports power but not on/off state:


Mar 17 20:27:10 hassbian npm[13413]:   zigbee2mqtt:info 3/17/2019, 8:27:10 PM MQTT publish: topic 'zigbee2mqtt/0x00158d000233e86d', payload '{"occupancy":true,"linkquality":31,"battery":100,"voltage":3025}'


Mar 17 20:27:18 hassbian npm[13413]:   zigbee2mqtt:info 3/17/2019, 8:27:18 PM MQTT publish: topic 'zigbee2mqtt/0x000d6f000b7a777b', payload '{"state":"OFF","linkquality":31,"power":202,"voltage":23857}'
Mar 17 20:27:26 hassbian npm[13413]:   zigbee2mqtt:info 3/17/2019, 8:27:26 PM MQTT publish: topic 'zigbee2mqtt/0x000d6f000b7a777b', payload '{"state":"OFF","linkquality":31,"power":427,"current":29}'



Mar 17 20:27:34 hassbian npm[13413]:   zigbee2mqtt:info 3/17/2019, 8:27:34 PM MQTT publish: topic 'zigbee2mqtt/0x000d6f000b7a777b', payload '{"state":"OFF","linkquality":15,"power":483,"voltage":23776}'



Mar 17 20:27:43 hassbian npm[13413]:   zigbee2mqtt:info 3/17/2019, 8:27:43 PM MQTT publish: topic 'zigbee2mqtt/0x00158d0001e1876f', payload '{"occupancy":false,"linkquality":26,"battery":100,"voltage":3055}'
Mar 17 20:27:43 hassbian npm[13413]:   zigbee2mqtt:info 3/17/2019, 8:27:43 PM MQTT publish: topic 'zigbee2mqtt/0x000d6f000b7a777b', payload '{"state":"OFF","linkquality":36,"current":0}'
Mar 17 20:27:51 hassbian npm[13413]:   zigbee2mqtt:info 3/17/2019, 8:27:51 PM MQTT publish: topic 'zigbee2mqtt/0x000d6f000b7a777b', payload '{"state":"OFF","linkquality":0,"power":0}'
Mar 17 20:28:00 hassbian npm[13413]:   zigbee2mqtt:info 3/17/2019, 8:28:00 PM MQTT publish: topic 'zigbee2mqtt/0x000d6f000b7a777b', payload '{"state":"OFF","linkquality":31,"power":179,"current":15}'

**Comment by Koenkk** [comment]
Can you check if it also reports manually pushing the on/off button with: 

**devices.js**
```js
{
        zigbeeModel: ['SmartPlug'],
        model: 'HS2SK',
        description: 'Smart metering plug',
        supports: 'on/off, power measurement',
        vendor: 'Heiman',
        fromZigbee: [fz.state, fz.ignore_onoff_change, fz.ignore_electrical_change, fz.HS2SK_power],
        toZigbee: [tz.on_off],
        configure: (ieeeAddr, shepherd, coordinator, callback) => {
            const device = shepherd.find(ieeeAddr, 1);
            const cfg = {direction: 0, attrId: 0, dataType: 16, minRepIntval: 0, maxRepIntval: 1000, repChange: 0};
            const actions = [
                (cb) => device.bind('genOnOff', coordinator, cb),
                (cb) => device.foundation('genOnOff', 'configReport', [cfg], foundationCfg, cb),
                (cb) => device.report('haElectricalMeasurement', 'rmsVoltage', 1, 1000, 1, cb),
                (cb) => device.report('haElectricalMeasurement', 'rmsCurrent', 1, 1000, 1, cb),
                (cb) => device.report('haElectricalMeasurement', 'activePower', 1, 1000, 1, cb),
            ];

            execute(device, actions, callback);
        },
    },
```

**fromZigbee.js**
```js
HS2SK_power: {
        cid: 'haElectricalMeasurement',
        type: ['attReport', 'readRsp'],
        convert: (model, msg, publish, options) => {
            return {
                power: msg.data.data['activePower'] / 10,
                current: msg.data.data['rmsCurrent'] / 100,
                voltage: msg.data.data['rmsVoltage'] / 100,
            };
        },
    },
```
The power readings should also be OK now.

If everything works, can you make a PR?

**Comment by mitnits** [comment]
Something is slightly off with the code you suggested...

Now I get a lot of:
Mar 19 21:57:01 hassbian npm[30038]:   zigbee2mqtt:warn 3/19/2019, 9:57:01 PM No converter available for 'HS2SK' with cid 'haElectricalMeasurement', type 'attReport' and data '{"cid":"haElectricalMeasurement","data":{"rmsVoltage":23656}}'
Mar 19 21:57:01 hassbian npm[30038]:   zigbee2mqtt:warn 3/19/2019, 9:57:01 PM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.


messages....


I did add the HS2SK_power to fromZigbee.js (and restarted) - so don't really understand what is missing now

**Comment by mitnits** [comment]
Also - no, button presses still are not reported

**Comment by Koenkk** [comment]
are you on the latest zigbee2mqtt dev?

**Comment by mitnits** [comment]
What’s the best way to check this?

**Comment by Koenkk** [comment]
zigbee2mqtt version is logged on startup.

**Comment by mitnits** [comment]
Mar 20 14:20:09 hassbian npm[8978]: #033[32m  zigbee2mqtt:info#033[39m 3/20/2019, 2:20:09 PM Logging to directory: '/opt/zigbee2mqtt/data/log/2019-03-20.14-20-08'
Mar 20 14:20:10 hassbian npm[8978]: #033[32m  zigbee2mqtt:info#033[39m 3/20/2019, 2:20:10 PM Starting zigbee2mqtt version 1.2.1 (commit #e5ca977)
Mar 20 14:20:10 hassbian npm[8978]: #033[32m  zigbee2mqtt:info#033[39m 3/20/2019, 2:20:10 PM Starting zigbee-shepherd
Mar 20 14:20:11 hassbian npm[8978]: #033[32m  zigbee2mqtt:info#033[39m 3/20/2019, 2:20:11 PM zigbee-shepherd started
Mar 20 14:20:11 hassbian npm[8978]: #033[32m  zigbee2mqtt:info#033[39m 3/20/2019, 2:20:11 PM Coordinator firmware version: '20181024'
Mar 20 14:20:11 hassbian npm[8978]: #033[32m  zigbee2mqtt:info#033[39m 3/20/2019, 2:20:11 PM Currently 10 devices are joined:

**Comment by Koenkk** [comment]
You are on the zigbee2mqtt release branch, please switch to the dev branch: http://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html

**Comment by mitnits** [comment]
This looks very good so far:

(what you see below is logs with power brick connected to the smart plug, pressing on and off button etc)

Ok, when you say "make a PR?" - do you have a link to instructions?

Mar 23 17:20:37 hassbian npm[7297]:   zigbee2mqtt:info 3/23/2019, 5:20:37 PM MQTT publish: topic 'zigbee2mqtt/0x000d6f0011088774', payload '{"voltage":null,"linkquality":36,"state":"ON","power":63.8,"current":0.58}'
Mar 23 17:20:42 hassbian npm[7297]:   zigbee2mqtt:info 3/23/2019, 5:20:42 PM MQTT publish: topic 'zigbee2mqtt/0x000d6f0011088774', payload '{"voltage":null,"linkquality":36,"state":"OFF","power":63.8,"current":0.58}'
Mar 23 17:20:46 hassbian npm[7297]:   zigbee2mqtt:info 3/23/2019, 5:20:46 PM MQTT publish: topic 'zigbee2mqtt/0x000d6f0011088774', payload '{"voltage":235.92,"linkquality":39,"state":"OFF","power":46.1,"current":null}'
Mar 23 17:20:48 hassbian npm[7297]:   zigbee2mqtt:info 3/23/2019, 5:20:48 PM MQTT publish: topic 'zigbee2mqtt/0x00158d0001e1876f', payload '{"occupancy":false,"linkquality":23,"battery":100,"voltage":3065}'
Mar 23 17:20:51 hassbian npm[7297]:   zigbee2mqtt:info 3/23/2019, 5:20:51 PM MQTT publish: topic 'zigbee2mqtt/0x000d6f0011088774', payload '{"voltage":235.92,"linkquality":36,"state":"ON","power":46.1,"current":null}'
Mar 23 17:20:59 hassbian npm[7297]:   zigbee2mqtt:info 3/23/2019, 5:20:59 PM MQTT publish: topic 'zigbee2mqtt/0x000d6f0011088774', payload '{"voltage":null,"linkquality":31,"state":"ON","power":19,"current":0.16}'
Mar 23 17:21:07 hassbian npm[7297]:   zigbee2mqtt:info 3/23/2019, 5:21:07 PM MQTT publish: topic 'zigbee2mqtt/0x000d6f0011088774', payload '{"voltage":235.7,"linkquality":44,"state":"ON","power":32.6,"current":null}'

**Comment by Koenkk** [comment]
Instructions can be found here: https://help.github.com/en/articles/creating-a-pull-request

**Comment by mitnits** [comment]
https://github.com/Koenkk/zigbee-shepherd-converters/pull/367
