### ISSUE TITLE
using manufacturer specific clusters / homeassistant.js update

### ISSUE THREAD

**Issue by ReneHonig** [Koenkk/zigbee-herdsman-converters#345]
@Koenkk, I have just submitted a pull request for some additional Smartthings devices, updated homeassistant.js entries below:

    '3310-S': [
        configurations.sensor_temperature, 
        configurations.sensor_battery, 
    ],
    '3315-S': [
        configurations.sensor_temperature, configurations.binary_sensor_water_leak,
        configurations.sensor_battery, 
    ],
    'F-MLT-US-2': [
        configurations.sensor_temperature, configurations.binary_sensor_contact,
        configurations.sensor_battery, configurations.binary_sensor_battery_low,
    ], 

Some of the devices use manufacturer defined clusters. Any idea how to implement them (I have some info on what the clusters are), so I can realise the full device functionality?

Thanks.

**Comment by Koenkk** [comment]
Thanks again Rene,

These are the required changes: https://github.com/Koenkk/zcl-id/commit/77ba3058c6c4b09a9958761ae5e3046765c12872 and https://github.com/Koenkk/zcl-packet/commit/39786f72ccc5ade1d4141d9d85d9e9249ce7080f

**Comment by ReneHonig** [comment]
Thanks, will have a go at it.
