### ISSUE TITLE
Lutron Z3-1BRL Needs some Love

### ISSUE THREAD

**Issue by TheRealWaldo** [Koenkk/zigbee-herdsman-converters#3453]
The button on a Lutron Z3-1BRL does not have a converter.

## What did you expect to happen
A button press should trigger a toggle.

From the logs:
```
Debug Received Zigbee message from 'Office Dimmer', type 'read', cluster 'genOnOff', data '["onOff"]' from endpoint 1 with groupID null
Debug No converter available for 'Z3-1BRL' with cluster 'genOnOff' and type 'read' and data '["onOff"]'
```

Further, HASS's resulting 'action' entity is never populated with a state.

It seems an additional converter needs to be added.  I attempted to add an external converter, but it looks like internal converters override the externals?  

Given that I am using the HASS Add-On, is there a way to alter a converter for testing before submitting a PR?

Also, stability seems to be a problem, and it feels like it could be a similar issue to https://github.com/Koenkk/zigbee-herdsman-converters/pull/3330

And lastly, battery levels are not appearing (but are reported by the device).  Also reported at https://github.com/Koenkk/zigbee2mqtt/issues/9736 by others.

**Comment by Koenkk** [comment]
Can you try with the following external converter:

```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['Z3-1BRL'],
    model: 'Z3-1BRL',
    vendor: 'Lutron',
    description: 'Aurora smart bulb dimmer (EXTERNAL CONVERTER)',
    fromZigbee: [fz.command_move_to_level, fz.command_on, fz.command_off],
    toZigbee: [],
    exposes: [e.action(['brightness', 'on', 'off']), exposes.numeric('brightness', ea.STATE)],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genLevelCtrl', 'genOnOff']);
    },
    ota: ota.zigbeeOTA,
};

module.exports = definition;

```

Make sure the configure succeeds, to do this wake up the device and right after that click the yellow refresh button on the device page in the frotend.

**Comment by MatthewGCampbell** [comment]
When running this external converter I get this issue, I think its related to how I added the external converter, but as I'm using    zigbee2mqtt in Home Assistant I used the config file and added 
```
external_converters:
  - lutron.js
```
my data path is
`data_path: /config/zigbee2mqtt`
so `lutron.js` is at `/config/zigbee2mqtt/lutron.js` i feel this is the reason for my issue but then I'm not sure how to install the external converter any other way. 

this is the error I get:

```
[20:36:32] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.1 start
> node index.js
(node:1437) UnhandledPromiseRejectionWarning: ReferenceError: ota is not defined
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1437) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1437) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by TheRealWaldo** [comment]
After correcting the errors in the above external converter, things are actually worse.

Pressing the button exhibits seemingly random behaviour.  Sometimes it doesn't turn on or off, sometimes it goes to full brightness when you expect it to turn off, and it's quite infuriating.

The dimmer, however, continues to work without issue.

Also, the errors about not having a converter continue to appear in the log.

Switching back to zha, things behave as expected.

**Comment by deepcoder** [comment]
I am also not able to use the Aurora dimmer in zigbee2mqtt, I tried your code above as a external converter, however still getting the messages 'No converter available'. I checked to make sure my external converter loaded, and it did. Also, FYI, I have to remove the line :
`    // ota: ota.zigbeeOTA,`
to get the converter to load. 

I'm out of league here, however it looks like the Aurora is sending additional data with the cluster commands:
data '["onOff"]
data '["currentLevel"]'

that is not expected and so the converter is not matching and processing. I tried to find a device in the herdsman libraries with similar pattern but failed to find.

Thank you for your work! And any guidance to get this device working.

```
debug 20220209114045: Received Zigbee message from '0xffff000fe7fca582', type 'read', cluster 'genOnOff', data '["onOff"]' from endpoint 1 with groupID 0
debug 20220209114045: No converter available for 'Z3-1BRL' with cluster 'genOnOff' and type 'read' and data '["onOff"]'

debug 20220209114800: Received Zigbee message from '0xffff000fe7fca582', type 'read', cluster 'genLevelCtrl', data '["currentLevel"]' from endpoint 1 with groupID 0
debug 20220209114800: No converter available for 'Z3-1BRL' with cluster 'genLevelCtrl' and type 'read' and data '["currentLevel"]'
```

```

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['Z3-1BRL'],
    model: 'Z3-1BRL',
    vendor: 'Lutron',
    description: 'Aurora smart bulb dimmer (EXTERNAL CONVERTER)',
    fromZigbee: [fz.command_move_to_level, fz.command_on, fz.command_off],
    toZigbee: [],
    exposes: [e.action(['brightness', 'on', 'off']), exposes.numeric('brightness', ea.STATE)],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genLevelCtrl', 'genOnOff']);
    },
    // ota: ota.zigbeeOTA,
};

module.exports = definition;
```

**Comment by Linn111** [comment]
I am having the same issue.

I am running the latest pure zigbee2mqtt stable in docker on a RPI.  Only Mosquitto running in another separate docker.  Other zigbee devices behave normally.  I have two Z3-1BRL buttons with the same symptom.  

typical debug response:
2022-02-15 05:56:55: Received Zigbee message from 'South Button', type 'read', cluster 'genLevelCtrl', data '["currentLevel"]' from endpoint 1 with groupID 0

zigbee2mqtt    | Zigbee2MQTT:debug 2022-02-15 05:56:55: No converter available for 'Z3-1BRL' with cluster 'genLevelCtrl' and type 'read' and data '["currentLevel"]'

MQQT messages sent from 1) press, 2) slight turn of knob, 3) press (at 1 second intervals):
{"action":"brightness","brightness":255,"linkquality":111,"update":{"state":"idle"},"update_available":false}

{"action":"brightness","brightness":255,"linkquality":78,"update":{"state":"idle"},"update_available":false}

{"action":"brightness","brightness":0,"linkquality":123,"update":{"state":"idle"},"update_available":false}

I tried to add “legacy: false: in the configuration.yaml for both buttons, but when I did so, I received no responses at all.  When I removed it, I got the results as shown.

When adding an unsupported device (a Sylvania BR30 10 year, which surprisingly is unsupported), I could not seem to get zigbee2mqtt to respond to an external converter in my current configuration.  It read the file (it complained if it wasn’t there), but I never got any additional errors or a change in behavior for the unsupported device.  So I can’t help with an External Converter patch at the moment.

zigbee2mqtt is great.  Thanks for all the work.

**Comment by deepcoder** [comment]
I have a very very rudimentary setup 'working' with Home Assistant, using the 'hack' shown below to stop the Aurora from sending any updates thru MQTT that have either the "last_seen" or "linkquality". With these in and being sent, I was not able to get any actionable state change information. I am a noob with Home Assistant Automation triggers, so I'm sure there is a better way.

I can do a basic toggle of a lights state and set a brightness based on a number between 2 and 255 being send by the Aurora. I am still not sure I have 'captured' all the possible message that can be send by zigbee2mqtt with this hack. However as far as I can tell, this is sum total of the controls that possible from the Aurora. No double, triple clicks, no long holds.

The physical interface on this device is questionable as well. If you are not careful with your 'push', you end up with a dimmer message send as last message, so even though you pressed and hear and felt a push click, the last message is a very small move of the dimmer value. With the prior message of the press lost.

Set the following for the devices in zigbee2mqtt, this stops sending these attributes in mqtt messages, if the mqtt message ONLY contains these attributes, then no message is sent. This seems to solve the problem that the device spams out message with only these attributes after sending 'useful' message with level change value:

```
in zigbee2mqtt configuration.yaml file:
devices:
  '0xffff000faafbb582':
    friendly_name: '0xffff000faafbb582'
    filtered_attributes: ["last_seen", "linkquality"]

in home assistant sensor.yaml file:

  - platform: mqtt
    name: "Lutron Kitchen Light Switch Action"
    unique_id: "0x0xffff000faafbb582-Action"
    state_topic: "test_zigbee2mqtt/0xffff000faafbb582"
    value_template: >-
      level : {{ value_json.action_level | default(-1) }}, group : {{ value_json.action_group | default(0) }}
    availability_topic: test_zigbee2mqtt/0xffff000faafbb582/availability
    json_attributes_topic: "test_zigbee2mqtt/0xffff000faafbb582"

this generates a text sensor that has the basic format:

level : n, group : m 

level : 255, group : 48526 <- push button pushed
level :   0, group : 48526 <- push button pushed

level :   2, group : 0 <- dial spun all the way counterclockwise, lowest value 2
level : 255, group : 0 <- dial spun all the way clockwise, highest value 255
level : xxx, group : 0 <- dial spun somewhere between 2 and 255

```

**Comment by TheRealWaldo** [comment]
Still an issue.  I have noticed that the dimmers get less responsive over time.

Restarting zigbee2mqtt makes them more responsive for a time.  Perhaps we have a race condition somewhere?

**Comment by Linn111** [comment]
I am using 2 Lutron dimmers in tandem to control an HASS “12-point circular switch.”  I set up up to 12 scenes, based on the numbers. The dimmers are tricky little devils.  They each behave a little differently, and not intuitively.  One produces json and the other produces text in Jason format.  They appear to have slightly different initial states, also

I take each input via zigbee2mqtt and then merge them into Node Red to create a single mqtt message with a single number 0-11.  0==”OFF” 1==”ON”.  Other numbers are up for grabs.  A button push toggles OFF and ON.  Turning the knob steps through the numbers either CW or CCW.  It is currently a “hack,” but appears fairly stable.

You are welcome to the js code attached to improve, modify or otherwise make better.

[Jscript.txt](https://github.com/Koenkk/zigbee-herdsman-converters/files/8318478/Jscript.txt)
[NodeRed.pdf](https://github.com/Koenkk/zigbee-herdsman-converters/files/8318479/NodeRed.pdf)
[OnStart.txt](https://github.com/Koenkk/zigbee-herdsman-converters/files/8318480/OnStart.txt)
