### ISSUE TITLE
IKEA 2005R5 flagged as unsupported

### ISSUE THREAD

**Issue by segaura** [Koenkk/zigbee-herdsman-converters#3458]
zigbee2mqtt reports one of my gu10 bulbs is not supported but it is present in this file

`/devices/ikea.js`

it is the `2005R5` bulb which is declared supported.
I checked my ikea.js in zigbee2mqtt docker image and it correctly includes

```
    {
        zigbeeModel: ['TRADFRIbulbGU10WS345lm', 'TRADFRI bulb GU10 WW 345lm'],
        model: 'LED2005R5',
        vendor: 'IKEA',
        description: 'TRADFRI LED bulb GU10 345 lumen, dimmable, white spectrum',
        extend: tradfriExtend.light_onoff_brightness_colortemp(),
    },
```
zigbee2mqtt reports

`Received message from unsupported device with Zigbee model 'TRADFRIbulbGU10WS345lm' and manufacturer name 'IKEA of Sweden'`

and, while the model name match exactly what `ikea.js` list, the vendor field is not an exact match, it is `'IKEA of Sweden'` while ikea.js reports `'IKEA'` only.

Dunno if this is the problem or I have to search somewhere else.

Please let me know if it is useful/necessary to test without zigbee2mqtt.

**Comment by segaura** [comment]
While I was filing the new issue somethings changed and now the device is flagged as unsupported no more.
Right below the previously reported log line now I have these also:

```
Debug Received MQTT message on 'zigbee2mqtt/bridge/request/device/configure' with data '{"id":"0xcc86ecfffe6fb547","transaction":"3scy3-1"}'
Info Configuring '0xcc86ecfffe6fb547'
Debug Received Zigbee message from '0xcc86ecfffe6fb547', type 'readResponse', cluster 'lightingColorCtrl', data '{"colorCapabilities":16}' from endpoint 1 with groupID null
Debug Missing colorTempPhysicalMin and/or colorTempPhysicalMax for endpoint 0xcc86ecfffe6fb547!
Info MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffe6fb547', payload '{"color_mode":"xy","linkquality":255,"power_on_behavior":null,"state":null,"update_available":null}'
Debug Received Zigbee message from '0xcc86ecfffe6fb547', type 'readResponse', cluster 'lightingColorCtrl', data '{"colorTempPhysicalMax":454,"colorTempPhysicalMin":250}' from endpoint 1 with groupID null
Info MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffe6fb547', payload '{"color_mode":"xy","linkquality":255,"power_on_behavior":null,"state":null,"update_available":null}'
Info Successfully configured '0xcc86ecfffe6fb547'
Info MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure', payload '{"data":{"id":"0xcc86ecfffe6fb547"},"status":"ok","transaction":"3scy3-1"}'
```

Dunno if this is a normal pattern or if there is a bug somewhere.
Please let me know if further analysis could be useful on my side, otherwise the issue can be closed.

**Comment by Koenkk** [comment]
I'm not sure what went wrong here, but looks the issue has been solved, if yes please close this issue.

**Comment by segaura** [comment]
Yes, the issue is no more present, I have no additional information other than the ones already posted, nor I am able to reproduce the issue anymore.
Closing, thank you.

**Comment by ulicskad** [comment]
Hi all!

I have got the same issue with the same gu10 bulb from IKEA. I have tried to pair it again, recomfigure, restart addon, restart core, but still unsupported. Any ideas? Thanks!
Log entry:

> Zigbee2MQTT:warn  2021-12-12 15:09:50: Received message from unsupported device with Zigbee model 'TRADFRIbulbGU10WS345lm' and manufacturer name 'IKEA of Sweden'
Zigbee2MQTT:warn  2021-12-12 15:09:50: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.

![gu10](https://user-images.githubusercontent.com/32922418/145717362-e0c5198a-2413-46bf-8648-15b57f8c8b99.PNG)

**Comment by Ndrinta** [comment]
IKEA 2005R5 flagged as unsupported, here too.

![Screenshot_20220312-095859](https://user-images.githubusercontent.com/4704172/158013520-fc23105a-a91c-4bc6-b73d-541b75c92ad5.png)

I have waited a decent amount of time, say 1h or so, but the z2m hadn't configured device yet.
Not sure what changed in @segaura's config to make his to work. I'll wait some more time now, failing that, I'll try pairing it again later today.

**Comment by segaura** [comment]
> I have waited a decent amount of time, say 1h or so, but the z2m hadn't configured device yet. Not sure what changed in @segaura's config to make his to work. I'll wait some more time now, failing that, I'll try pairing it again later today.

To my knowledge I changed nothing, simply waited, sorry.

Now I switched coordinator to Sonoff USB from Conbee II so maybe this also is contributing to the issue not showing itself anymore.

**Comment by thejman1989** [comment]
Why is this issue closed? There is no answer yet. I am experiencing the same problem. Dont know if I should return the bulbs now... 

![image](https://user-images.githubusercontent.com/3214644/205451670-2c3a9b6d-5576-43d4-a172-2484af3b6f37.png)

**Comment by Koenkk** [comment]
@thejman1989 update to z2m 1.28.4

**Comment by georgbachmann** [comment]
I just downloaded zigbee2mqtt via home-assistant and added my first lights. IKEA GU 10 spots... Same issue here.
But even though I just installed it right now, my version is `1.18.1-1`. So there is no 1.28.4 for me to upgrade to?!? Any idea how to update? And will it be solved with this new version? Those bulbs made problems with Deconz as well, which is why I bought a new Sonoff Stick and wanted to switch to zigbee2mqtt in the first place :)

**Comment by thejman1989** [comment]
There is a special way to upgrade from that version. It is noted somewhere in the release notes, I cannot check it right now, if I have time later I will provide the proper address. But I would recommend reading the release notes for zigbee2mqtt hassio plugin. I believe you need to change the Hass download location,

**Comment by georgbachmann** [comment]
Yes, that was the issue. I changed the download url and then it worked. Thanks!
