### ISSUE TITLE
Don't forward attribute to MQTT

### ISSUE THREAD

**Issue by vk496** [Koenkk/zigbee-herdsman-converters#3468]
Hello,

This question is related to https://github.com/Koenkk/zigbee2mqtt/issues/9929

A brief summary: A device that reads a lot of data from electrical box, but not all is useful (a user with single phase configuration is not interested in wrong/bad values from three phase and vice versa)

The Q: There is some way to not forward a attribute to the MQTT?

Since it seems not possible to dynamically expose attributes based on specific options right now, maybe I could just not forward it to the MQTT topic? So even all attributes exist and are exposed in Z2M, Home Assistant just receive those that are selected by the user (specific options).

**Comment by Koenkk** [comment]
See the `filtered_attributes` option: https://www.zigbee2mqtt.io/guide/configuration/devices-groups.html#common-device-options

**Comment by vk496** [comment]
Thank you @Koenkk.

I checked the code/examples in order to see how to use/set this options inside the `configure:` with no luck. The only place where it seems possible to access it is inside the converters, with the `meta.options` parameter (ex: https://github.com/Koenkk/zigbee-herdsman-converters/blob/51be4441ebaf0c1f2e4586dfb39083cb32bbcb63/converters/toZigbee.js#L4393 )

That means that I'm forced to manipulate it inside converters? Or there is other way to access it from configurations?

As I understand, it is much cleaner to set what should be forwarded and what no during the configuration step.

Br,
Valentín

**Comment by Koenkk** [comment]
@vk496 this filtering is done on the zigbee2mqtt side, so you just configure everything and the user can decide what to filter out

**Comment by vk496** [comment]
Oh,

Okay. Thank you for the info. I doesn't allow me to limit the useless data sent to HA, but at least it could be a "hack" for the end users.

I will continue looking for some way to do it.

Thanks!
