### ISSUE TITLE
Unable to get Power for Sinope TH1123ZB thermostats

### ISSUE THREAD

**Issue by rigorm** [Koenkk/zigbee-herdsman-converters#3484]
Hi, 
2 things i've found weird.

1. Pairing a Sinope TH1123ZB thermostat, power is not stays Null in State.

When trying to setup in the "reporting" tab, I get the folowing error :
`Request 'zigbee2mqtt/bridge/request/device/configure_reporting' failed with error: 'ConfigureReporting 0x500b914000029683/1 haElectricalMeasurement([{"attribute":"activePower","minimumReportInterval":"0","maximumReportInterval":3600,"reportableChange":0}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNREPORTABLE_ATTRIBUTE')'` 

but, if I try manually in the dev console tab, I can get the value correctly.

2. By default, i'm missing some reported values in the "reporting" tab. Notably, rmsVoltage, rmsCurrent, activePower (and possibly more), But  If I use the code from this part defined in the TH1124ZB thermostat in devices/sinope.js , Reporteing is populated. (but still no activePower).

```
 try {
                await reporting.thermostatRunningState(endpoint);
            } catch (error) {/* Not all support this */}

            await reporting.readMeteringMultiplierDivisor(endpoint);
            await reporting.currentSummDelivered(endpoint, {min: 10, max: 303, change: [1, 1]});
            try {
                await reporting.instantaneousDemand(endpoint, {min: 10, max: 304, change: 1});
            } catch (error) {/* Do nothing*/}

            await reporting.readEletricalMeasurementMultiplierDivisors(endpoint);
            try {
                await reporting.activePower(endpoint, {min: 10, max: 305, change: 1});
            } catch (error) {/* Do nothing*/}
            try {
                await reporting.rmsCurrent(endpoint, {min: 10, max: 306, change: 100}); // divider 1000: 0.1Arms
            } catch (error) {/* Do nothing*/}
            try {
                await reporting.rmsVoltage(endpoint, {min: 10, max: 307, change: 5}); // divider 10: 0.5Vrms
            } catch (error) {/* Do nothing*/}

            try {
                await reporting.thermostatKeypadLockMode(endpoint);
            } catch (error) {
                // Not all support this: https://github.com/Koenkk/zigbee2mqtt/issues/3760
            }
```

i've tested the thermostats with ZHA and they all receive the correct values for power/current/voltage/sum_energy So I know the thermostat is sending the right data.

anyone else having the same issues ?

**Comment by FrAllard** [comment]
Did you solve your problem? I too would like to get activePower working on that thermostat. I too had ZHA with working activePower reported.

**Comment by rigorm** [comment]
Nope.

I suspect that few people are using tvis or they have sinope's zigbee gw so they can update there thermostat to a version wheee it actually works.

Its working great on mt 50A load controler. I tried to copy that part of the code into the thermostat code but doid not work


I wnded up doing static config in HA  and calculate V x A value. But even that is not full proof.



Le 27 sept. 2022 15 h 42, Francois Allard ***@***.***> a écrit :

Did you solve your problem? I too would like to get activePower working on that thermostat. I too had ZHA with working activePower reported.

**Comment by FrAllard** [comment]
The odd thing is it is working in ZHA. I want to use Z2M because I have more control over the devices. Since ZHA is working with that thermostat I don't think it's a firmware issue... I wish I could be more helpfull, since I don't really understand for now how all this is integrated into z2m, modifying code is far in the future for me...

**Comment by rigorm** [comment]
And if you go in the dev console of one of thermostat in  Z2M and set cluster to haElectricalMesurement and attribute to activePower, click on Read then goto to the exposes tab, you will see the value.

Le 11 oct. 2022 08 h 41, Francois Allard ***@***.***> a écrit :

The odd thing is it is working in ZHA. I want to use Z2M because I have more control over the devices. Since ZHA is working with that thermostat I don't think it's a firmware issue... I wish I could be more helpfull, since I don't really understand for now how all this is integrated into z2m, modifying code is far in the future for me...

**Comment by FrAllard** [comment]
You are right, I knew that already, I was too exited to see it "working", but it will not update automatically from that point on. It will stay stuck to the value it read when you did that.

**Comment by rigorm** [comment]
To give an update on this: I got a GT130 from Sinope and updated the firmware on one of them to test.. I had firmware revision 0.6.5 and it updated to 0.6.8. Now I can see power like its suppose to. 

So there you go. the TH1123ZB needs a firmware update.

Now, this year, i bought a fresh new batch and they are now selling TH1123ZG-G2 thermostat and they are not yet supported by Z2M.. (Working on it)
