### ISSUE TITLE
Support Develco SMSZB-120 IAS Zone

### ISSUE THREAD

**Issue by jkaberg** [Koenkk/zigbee-herdsman-converters#3486]
So referring to [this comment](https://github.com/zigpy/zha-device-handlers/issues/854#issuecomment-823194480) over at ZHA aswell as the [official Zigbee documentation](https://www.manualslib.com/manual/1236036/Develco-Smszb-120.html?page=9#manual) (section 4.2.4.2 and 4.2.4.2.1) along with the [technical specification from Develco](https://www.develcoproducts.com/media/1742/smszb-120-technical-manual-smoke-alarm.pdf) (section 4.2.1 and 4.2.4), it's my understanding that these devices should support grouping to trigger the siren without the coordinator present (but needs to coordinator for initial setup?) if any of the devices register smoke (eg smoke detector X detects smoke which will trigger the siren of detector X, Y and Z).

I'll be honest and say I'm out of depth here (technically), but I'd like to help in any way I can to bring this feature (if possible) into Z2M.

**Comment by jkaberg** [comment]
So just for reference I got a few of these, I've set up 2 of them which I'm currently experimenting with.

From section "4.2.1.1.1 Zone State":
> The device will automatically start to scan the network for an IAS Zone client in a predefine interval. When the
client is found it will automatically attempt to enrol. When it has successfully enrolled the Zone Status command
is send every 5 minutes.

Looking up my 2 devices via dev console I can see

```
Device 1 - 0x0015bc003100d36f
Read result of 'ssIasZone': {"zoneState":1,"zoneType":40,"zoneStatus":48,"iasCieAddr":"0x00212effff04246b"}

Device 2 - 0x0015bc003100d2af
Read result of 'ssIasZone': {"zoneState":1,"zoneType":40,"zoneStatus":48,"iasCieAddr":"0x00212effff04246b"}
```

So that seems about right (I guess?)

Further reading, from section "4.2.4 IAS WD – Cluster id 0x0502":
>The IAS WD cluster is described in ZigBee Cluster Library Specification.
Using this cluster, a ZigBee device can access a ZigBee enabled IAS WD device and issue alarm warning
indications (Smoke siren) when a system alarm condition is detected

and at the very end of that section
> Note: The start warning command doesn’t set the alarm bit in the IAS Zone status.
The alarm is only triggered if the devices detect smoke or fire

So triggering the alarm from the UI (START/OFF) is a no go. So I went to my fire place and let out enough smoke for one of them to detect and trigger the siren. However this did not trigger the siren on the other device

So I guess there are some pieces missing?

**Comment by jkaberg** [comment]
@Koenkk @TheStigh do you have any insight? I most eager to get this up and running, so let me know what you think

**Comment by jkaberg** [comment]
Did some digging and someone pointed me at [deconz](https://github.com/dresden-elektronik/deconz-rest-plugin) which allegedly has bindings, [consistent temperature++](https://github.com/Koenkk/zigbee2mqtt/issues/9235) working, and it seems that @SwoopX is the doing the heavy lifting (ref https://github.com/dresden-elektronik/deconz-rest-plugin/pull/2166). I was wondering if you have any insight as to how this work and what [might be missing](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/develco.js#L151-L185) regarding Develco SMSZB-120? I tried looking over the code of deconz, but the device config is spread all over the place it would seem

**Comment by TheStigh** [comment]
Hi @jkaberg 

What you are trying to achieve are not possible. I've discussed this with @SwoopX earlier and it doesn't work like this with deconz either. These devices do not support talking directly to each other. 

Using binding as you refer to would still need the coordinator.

Sorry to let you down on this.

**Comment by Damme** [comment]
Did anyone get this working?
I tried with the latest version and I cannot make the other alarms go off automatically. Do I need to repair them?

**Comment by TheStigh** [comment]
> Did anyone get this working? I tried with the latest version and I cannot make the other alarms go off automatically. Do I need to repair them? At the moment I have a simple python script listening to MQTT messages if anyone alarms it sends out an alarm to everyone. not the best solution IMO.

Please read my last comment
[https://github.com/Koenkk/zigbee-herdsman-converters/issues/3486#issuecomment-997071307](url)

**Comment by SuperBigB** [comment]
I have quite a few of these, and aslo some heat detectors HESZB-120 witch should work together. Verry eager to get these functioning as intended.
