### ISSUE TITLE
[Device Support] Silvercrest (Lidl) Garden Spike (_TZ3000_br3laukf)

### ISSUE THREAD

**Issue by drgrandios** [Koenkk/zigbee-herdsman-converters#3512]
Bought a Lidl garden spike with 2 power sockets (model HG06620 according to sticker on package) - it works when adapting the existing Lidl outdoor plug definition:

```javascript
{
        fingerprint: [{modelID: 'TS0101', manufacturerName: '_TZ3000_br3laukf'}],
        model: 'HG06620',
        vendor: 'Lidl',
        description: 'Silvercrest garden spike with 2 sockets',
        extend: extend.switch(),
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff']);
            await reporting.onOff(endpoint);
        },
    },
```
in file 

https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/lidl.js

Only an icon is missing.

**Comment by Koenkk** [comment]
Added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
