### ISSUE TITLE
Tuya RGBCW bulb new manufacturer

### ISSUE THREAD

**Issue by matthewjm-dev** [Koenkk/zigbee-herdsman-converters#3525]
Hi there, I have previously used (and still have) some Tuya (Lonsonho) ZB-RGBCW bulbs, which work perfectly.

I have just received another 2 bulbs from the same seller (the same listing infact) and they do not work. They have a model of TS0505B (which actually seems to be the same model number as some other Tuya products.. not helpful!) and the manufacturer string I get when the unsupport message pops up is "_TZ3210_remypqqm". 

So it appears that the manufacturer of the bulb has changed, which means they are unsupported even though the design and function of the bulbs is exactly the same as the old models that I already have!

The new device process seems very tricky (no mention of any directories which means I dont even know where to find the files it mentions) as I presume i'd need to first make the edits to my live home assistant files to ensure it works before creating a pull request? The Added difficulty of it being a Tuya device with the extra steps makes it also unappealing, but as the device already exists and works but under a different manufacturer is there any way of more quickly adding support for this device?

Many thanks!

**Comment by maimrn** [comment]
The same here.

**Comment by xstable** [comment]
Same here. 
I've tried to add tuya.js to `/config/zigbee2mqtt`, but if I restart zigbee2mqtt, I got an error: 
```
(node:361) UnhandledPromiseRejectionWarning: internal/modules/cjs/loader.js:905
  throw err;
  ^
Error: Cannot find module '../lib/exposes'
Require stack:
- /app/dist/util/utils.js
- /app/dist/util/settings.js
- /app/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at /app/dist/util/externally-loaded.js:1:17
    at Script.runInContext (vm.js:144:12)
    at Script.runInNewContext (vm.js:149:17)
    at Object.runInNewContext (vm.js:303:38)
    at loadModuleFromText (/app/lib/util/utils.ts:148:8)
    at loadModuleFromFile (/app/lib/util/utils.ts:155:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:361) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:361) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any Idea, whay `../lib/exposes` can't be found? Did I need to install it? If yes, how?

**Comment by maimrn** [comment]
I have just made it working with an external converter:

First create a file (I called led.js) at config/zigbee2mqtt directory:

> const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
> const tz = require('zigbee-herdsman-converters/converters/toZigbee');
> const exposes = require('zigbee-herdsman-converters/lib/exposes');
> const reporting = require('zigbee-herdsman-converters/lib/reporting');
> const extend = require('zigbee-herdsman-converters/lib/extend');
> const e = exposes.presets;
> const ea = exposes.access;
> const tuya = require("zigbee-herdsman-converters/lib/tuya");
> 
> const definition = {
>     zigbeeModel: ['TS0505B'],
>     model: 'TS0505B',
>     vendor: '_TZ3210_remypqqm',
>     description: 'Lampada LED Tuya',
>     // Note that fromZigbee, toZigbee and exposes are missing here since we use extend here.
>     // Extend contains a default set of fromZigbee/toZigbee converters and expose for common device types.
>     // The following extends are available:
>     // - extend.switch
>     // - extend.light_onoff_brightness
>     // - extend.light_onoff_brightness_colortemp
>     // - extend.light_onoff_brightness_color
>     // - extend.light_onoff_brightness_colortemp_color
>     extend: extend.light_onoff_brightness_colortemp_color(),
> };
> 
> module.exports = definition;

Now, stop your z2m service and you need to reference this external converter (led.js) at the setup of your zigbee2mqtt control panel.
Start your z2m and voila !

![image](https://user-images.githubusercontent.com/84946221/146692948-fc7e6786-6cd8-4010-9e90-ef0f6ce3969d.png)

**Comment by Koenkk** [comment]
Just added this in https://github.com/Koenkk/zigbee-herdsman-converters/commit/8593bc042debe7a9f7cbce9c91ce182a752c6801

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by xstable** [comment]
@Koenkk Thank you for acting so fast. I have a newbe question at this point. How to use your "zigbee-hardsman-converters" ?
Do I only have to particular pick the tuya.js file and place it in my /config/zigbee2mqtt Directory of HomeAssistant?

I think there is missing a "How to use" section in the Readme of this Project to help smart-home-automation beginners like me.

**Comment by Koenkk** [comment]
@xstable don't worry about zigbee-herdsman-converters, using the edge version of the addon will give you the latest zigbee-herdsman-converters.  (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by matthewjm-dev** [comment]
Thank you Koenkk! I'm hesitant to switch to the edge branch incase incase I
accidentally screw up my setup (my partner would not be impressed if
suddenly half the house doesn't work), do you have an ETA of when this
change will make it into master? Cheers!

**Comment by Koenkk** [comment]
Next release will be on 1 January

**Comment by xstable** [comment]
@maimrn can you point me to an howTo to see how `external converters` work, and how to create one?

**Comment by xstable** [comment]
@maimrn really great, works like a charm. Thanks

@Koenkk nice, looking forward to this release.
