### ISSUE TITLE
Support for Ajax  zignito gu10

### ISSUE THREAD

**Issue by karlc28** [Koenkk/zigbee-herdsman-converters#3534]
Trying to get support for the following 
Azax zignito zigbee gu10 bulbs
Model TS0505B

https://www.amazon.co.uk/dp/B09KXYYBQQ/ref=cm_sw_r_cp_api_glt_fabc_ZXFD6F9APA75SH89QW5M?_encoding=UTF8&psc=1

**Comment by DavidFFerreira** [comment]
we need the info from log, when you try to pair for the first time....
Model TS0505B, Manufacture: ?????
