### ISSUE TITLE
_TZE200_hue3yfsn : Temperature still the same

### ISSUE THREAD

**Issue by piars777** [Koenkk/zigbee-herdsman-converters#3549]
HEllo,
I have a trv from tuya TS0601 _TZE200_hue3yfsn. Everything works execpt the current temperature is still the same for 20 days. I changed the current_heating_setpoint  to 30° but the current temperature is still 23,3°. 
Can somebody help me please?

**Comment by vladi1234** [comment]
I've already written several times how to get current local_temperature.
See link:
https://github.com/Koenkk/zigbee-herdsman-converters/issues/3142#issuecomment-976885156

**Comment by piars777** [comment]
So If i understood i need to send a request to local_temperature_calibration=0 every time i need to get the local_temperature. am i right?

**Comment by vladi1234** [comment]
Yes.
