### ISSUE TITLE
QBKG26LM don't work with some actions

### ISSUE THREAD

**Issue by SHOOTnick1985** [Koenkk/zigbee-herdsman-converters#3553]
@Koenkk hi!

The Aqara D1 switch QBKG26LM don't work with actions: hold, triple and release for all button. Work only single and double.
Can you help with this?

**Comment by Koenkk** [comment]
@z-x-f could you help with this?

**Comment by z-x-f** [comment]
@SHOOTnick1985 Please provide the debug log when you hold, triple and release buttons

**Comment by SHOOTnick1985** [comment]
@z-x-f  Hi!
First I did a long press (hold), then 3 quick ones (triple). Is that what you needed?

[log.txt](https://github.com/Koenkk/zigbee-herdsman-converters/files/7757398/log.txt)

**Comment by SHOOTnick1985** [comment]
But this only left button. Needed repeat for central and right button?

**Comment by z-x-f** [comment]
I tested D1 3gang(no neutral wire) and found that this device does not provide <code>hold, release, triple</code>, so d1 3gang (with neutral wire)should not support these actions as well.

**Comment by SHOOTnick1985** [comment]
Then I will remove these actions from the description on the page: https://www.zigbee2mqtt.io/devices/QBKG26LM.html#xiaomi-qbkg26lm !?

**Comment by nasprong** [comment]
Hi @Koenkk i saw that in 3563 the QBKG26LM had power_outage_memory, led_disabled_night added which is great as it was missing and very usefull feature. Note the QBKG24LM is same switch with just 2 buttons but the same feature set. Can this one also receive update where these functions are added.
If you need data please let me know altough not yet capable of editing the data base as im mainly a home assistant user.
