### ISSUE TITLE
Zigbee model 'TS011F' and manufacturer name '_TZ3000_rdtixbnu not reporting anything except linkquality and on/off

### ISSUE THREAD

**Issue by grfernandes54** [Koenkk/zigbee-herdsman-converters#3554]
I've tried to add a Zemismart Smart Plug using the another TS011F as a model but nothing was reported.

Followin the TS011F.js coverter file created

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require("zigbee-herdsman-converters/lib/tuya");

const definition = {
fingerprint: [
{
modelID: 'TS011F',
manufacturerName: '_TZ3000_rdtixbnu'
},
],
model: 'LC-011',
vendor: 'Zemistmart',
description: 'Brazil Smart Tuya Zigbee Socket BR Plug Wireless Outlet Timing Plug 16A Energy Monitor',
fromZigbee: [fz.on_off, fz.electrical_measurement, fz.metering, fz.ignore_basic_report, fz.tuya_switch_power_outage_memory],
toZigbee: [tz.on_off, tz.tuya_switch_power_outage_memory],
onEvent: tuya.setTime, // Add this if you are getting no converter for 'commandSetTimeRequest'
configure: async (device, coordinatorEndpoint, logger) => {
const endpoint = device.getEndpoint(1);
await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'haElectricalMeasurement', 'seMetering']);
await reporting.rmsVoltage(endpoint, {change: 1, min: 10, max: 600});
await reporting.rmsCurrent(endpoint, {change: 50, min: 10, max: 600});
await reporting.activePower(endpoint, {change: 1, min: 10, max: 600});
await reporting.currentSummDelivered(endpoint, {change: 1, min:10, max: 600});
endpoint.saveClusterAttributeKeyValue('haElectricalMeasurement', {acCurrentDivisor: 1000, acCurrentMultiplier: 1});
endpoint.saveClusterAttributeKeyValue('seMetering', {divisor: 100, multiplier: 1});
device.save();
},
exposes: [e.switch(), e.power(), e.current(), e.voltage().withAccess(ea.STATE),
e.energy(), exposes.enum('power_outage_memory', ea.STATE_SET, ['on', 'off', 'restore'])
.withDescription('Recover state after power outage')],
};

module.exports = definition;

this is the log that I receive before create the converter

Warning Received message from unsupported device with Zigbee model 'TS011F' and manufacturer name '_TZ3000_rdtixbnu'

this is the log after I've created the converter

Zigbee2MQTT:debug 2021-12-20 17:57:27: Received MQTT message on 'homeassistant/select/0x9035eafffe0839e7/power_outage_memory/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x9035eafffe0839e7/availability"}],"availability_mode":"all","command_topic":"zigbee2mqtt/0x9035eafffe0839e7/set/power_outage_memory","device":{"identifiers":["zigbee2mqtt_0x9035eafffe0839e7"],"manufacturer":"Zemistmart","model":"Brazil Smart Tuya Zigbee Socket BR Plug Wireless Outlet Timing Plug 16A Energy Monitor (LC-011)","name":"0x9035eafffe0839e7"},"entity_category":"config","icon":"mdi:power-settings","json_attributes_topic":"zigbee2mqtt/0x9035eafffe0839e7","name":"0x9035eafffe0839e7 power outage memory","options":["on","off","restore"],"state_topic":"zigbee2mqtt/0x9035eafffe0839e7","unique_id":"0x9035eafffe0839e7_power_outage_memory_zigbee2mqtt","value_template":"{{ value_json.power_outage_memory }}"}'
Zigbee2MQTT:debug 2021-12-20 17:57:27: Received MQTT message on 'homeassistant/sensor/0x9035eafffe0839e7/linkquality/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x9035eafffe0839e7/availability"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x9035eafffe0839e7"],"manufacturer":"Zemistmart","model":"Brazil Smart Tuya Zigbee Socket BR Plug Wireless Outlet Timing Plug 16A Energy Monitor (LC-011)","name":"0x9035eafffe0839e7"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","json_attributes_topic":"zigbee2mqtt/0x9035eafffe0839e7","name":"0x9035eafffe0839e7 linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/0x9035eafffe0839e7","unique_id":"0x9035eafffe0839e7_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
Zigbee2MQTT:warn  2021-12-20 17:57:27: Failed to ping '0x9035eafffe0839e7' (attempt 1/1, Read 0x9035eafffe0839e7/1 genBasic(["zclVersion"], {"timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205)))
Zigbee2MQTT:debug 2021-12-20 17:57:30: Active device '0x9035eafffe0839e7' was last seen '4394.43' minutes ago.

**Comment by grfernandes54** [comment]
At the exposes

only the state, memory and linkquality works

all others only display null

<img width="376" alt="image" src="https://user-images.githubusercontent.com/70862164/146829517-fd9bd6ab-4a0c-475e-876f-16e0bf3f3a01.png">

**Comment by grfernandes54** [comment]
This is my device database

{"id":1,"type":"Coordinator","ieeeAddr":"0x00124b0024bfd5f0","nwkAddr":0,"manufId":0,"epList":[1,2,3,4,5,6,8,10,11,12,13,47,110,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":257,"epId":2,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"4":{"profId":263,"epId":4,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"5":{"profId":264,"epId":5,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"6":{"profId":265,"epId":6,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"8":{"profId":260,"epId":8,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"10":{"profId":260,"epId":10,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"11":{"profId":260,"epId":11,"devId":1024,"inClusterList":[1281],"outClusterList":[1280,1282],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"12":{"profId":49246,"epId":12,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"13":{"profId":260,"epId":13,"devId":5,"inClusterList":[25],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"47":{"profId":260,"epId":47,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"110":{"profId":260,"epId":110,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"interviewCompleted":true,"meta":{},"lastSeen":null}
{"id":2,"type":"EndDevice","ieeeAddr":"0x000d6f00179b2f14","nwkAddr":35089,"manufId":4125,"manufName":"Yale","powerSource":"Battery","modelId":"YRL226L TS","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":10,"inClusterList":[0,1,3,9,10,257,32,2821],"outClusterList":[10,25],"clusters":{"genBasic":{"attributes":{"modelId":"YRL226L TS","manufacturerName":"Yale","powerSource":3,"zclVersion":1,"appVersion":255,"hwVersion":2}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200}},"closuresDoorLock":{"attributes":{"lockState":1}}},"binds":[{"cluster":257,"type":"endpoint","deviceIeeeAddress":"0x00124b0024bfd5f0","endpointID":242},{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b0024bfd5f0","endpointID":242}],"configuredReportings":[{"cluster":257,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0},{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0}],"meta":{}}},"appVersion":255,"hwVersion":2,"zclVersion":1,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1640027509314}
{"id":3,"type":"Router","ieeeAddr":"0x9035eafffe083a0a","nwkAddr":63154,"manufId":4098,"manufName":"_TZ3000_rdtixbnu","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[0,3,4,5,6,1794,2820,57344,57345],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS011F","manufacturerName":"_TZ3000_rdtixbnu","powerSource":1,"zclVersion":3,"appVersion":69,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genOnOff":{"attributes":{"onOff":0}},"seMetering":{"attributes":{"divisor":100,"multiplier":1}},"haElectricalMeasurement":{"attributes":{"acVoltageMultiplier":1,"acVoltageDivisor":1,"acCurrentMultiplier":1,"acCurrentDivisor":1000,"acPowerMultiplier":1,"acPowerDivisor":1}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0024bfd5f0","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00124b0024bfd5f0","endpointID":1},{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x00124b0024bfd5f0","endpointID":1}],"configuredReportings":[{"cluster":2820,"attrId":1285,"minRepIntval":10,"maxRepIntval":600,"repChange":1},{"cluster":2820,"attrId":1288,"minRepIntval":10,"maxRepIntval":600,"repChange":50},{"cluster":2820,"attrId":1291,"minRepIntval":10,"maxRepIntval":600,"repChange":1},{"cluster":1794,"attrId":0,"minRepIntval":10,"maxRepIntval":600,"repChange":1}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":69,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":237349335},"lastSeen":1640033836279}
{"id":4,"type":"Router","ieeeAddr":"0x9035eafffe083a05","nwkAddr":23810,"manufId":4098,"manufName":"_TZ3000_rdtixbnu","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[0,3,4,5,6,1794,2820,57344,57345],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS011F","manufacturerName":"_TZ3000_rdtixbnu","powerSource":1,"zclVersion":3,"appVersion":69,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genOnOff":{"attributes":{"onOff":1}},"seMetering":{"attributes":{"divisor":100,"multiplier":1}},"haElectricalMeasurement":{"attributes":{"acVoltageMultiplier":1,"acVoltageDivisor":1,"acCurrentMultiplier":1,"acCurrentDivisor":1000,"acPowerMultiplier":1,"acPowerDivisor":1}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0024bfd5f0","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00124b0024bfd5f0","endpointID":1},{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x00124b0024bfd5f0","endpointID":1}],"configuredReportings":[{"cluster":2820,"attrId":1285,"minRepIntval":10,"maxRepIntval":600,"repChange":1},{"cluster":2820,"attrId":1288,"minRepIntval":10,"maxRepIntval":600,"repChange":50},{"cluster":2820,"attrId":1291,"minRepIntval":10,"maxRepIntval":600,"repChange":1},{"cluster":1794,"attrId":0,"minRepIntval":10,"maxRepIntval":600,"repChange":1}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":69,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":237349335},"lastSeen":1640033836786,"useImplicitCheckin":true}
{"id":5,"type":"Router","ieeeAddr":"0x9035eafffe0839e7","nwkAddr":20999,"manufId":4098,"manufName":"_TZ3000_rdtixbnu","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[0,3,4,5,6,1794,2820,57344,57345],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS011F","manufacturerName":"_TZ3000_rdtixbnu","powerSource":1,"zclVersion":3,"appVersion":69,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":69,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1639770184670,"useImplicitCheckin":true}

**Comment by grfernandes54** [comment]
I've saw tha this issue was fixe at https://github.com/Koenkk/zigbee2mqtt/issues/9797# 

How Can I create a local converter to replicate the solution ?

**Comment by Toma82** [comment]
> I've saw tha this issue was fixe at [Koenkk/zigbee2mqtt#9797](https://github.com/Koenkk/zigbee2mqtt/issues/9797)
> 
> How Can I create a local converter to replicate the solution ?


Settings->External converters -> + 


![image](https://user-images.githubusercontent.com/81713401/147123667-57ff2f82-4c23-49c6-9cb1-ace21a65c7f9.png)

then create tuya.js in \\ IP_address_homeassistant \ config \ zigbee2mqtt
and paste in it

"const exposes = require('zigbee-herdsman-converters/lib/exposes');
const fz = {...require('zigbee-herdsman-converters/converters/fromZigbee'), legacy: require('zigbee-herdsman-converters/lib/legacy').fromZigbee};
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const globalStore = require('zigbee-herdsman-converters/lib/store');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;




module.exports = [
   
{
        fingerprint: [{modelID: 'TS011F', manufacturerName: '_TZ3000_cphmq0q7'},
            {modelID: 'TS011F', manufacturerName: '_TZ3000_ew3ldmgx'},
            {modelID: 'TS011F', manufacturerName: '_TZ3000_ps3dmato'},
            {modelID: 'TS011F', manufacturerName: '_TZ3000_mraovvmm'},
            {modelID: 'TS011F', manufacturerName: '_TZ3000_jvzvulen'},
            {modelID: 'TS011F', manufacturerName: '_TZ3000_w0qqde0g'},
            {modelID: 'TS011F', manufacturerName: '_TZ3000_nfnmi125'}],
        model: 'TS011F_plug_1',
        description: 'Smart plug (with power monitoring)',
        vendor: 'TuYa',
        whiteLabel: [{vendor: 'LELLKI', model: 'TS011F_plug'}, {vendor: 'NEO', model: 'NAS-WR01B'}],
        fromZigbee: [fz.on_off, fz.electrical_measurement, fz.metering, fz.ignore_basic_report, fz.tuya_switch_power_outage_memory],
        toZigbee: [tz.on_off, tz.tuya_switch_power_outage_memory],
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'haElectricalMeasurement', 'seMetering']);
            await reporting.rmsVoltage(endpoint, {change: 5});
            await reporting.rmsCurrent(endpoint, {change: 50});
            await reporting.activePower(endpoint, {change: 10});
            await reporting.currentSummDelivered(endpoint);
            endpoint.saveClusterAttributeKeyValue('haElectricalMeasurement', {acCurrentDivisor: 1000, acCurrentMultiplier: 1});
            endpoint.saveClusterAttributeKeyValue('seMetering', {divisor: 100, multiplier: 1});
            device.save();
        },
        exposes: [e.switch(), e.power(), e.current(), e.voltage().withAccess(ea.STATE),
            e.energy(), exposes.enum('power_outage_memory', ea.STATE_SET, ['on', 'off', 'restore'])
                .withDescription('Recover state after power outage')],
    },
{
        fingerprint: [
            {modelID: 'TS011F', manufacturerName: '_TZ3000_dpo1ysak', applicationVersion: 69},
            {modelID: 'TS011F', manufacturerName: '_TZ3000_cphmq0q7', applicationVersion: 69},
            {modelID: 'TS011F', manufacturerName: '_TZ3000_5f43h46b', applicationVersion: 69},
            {modelID: 'TS011F', manufacturerName: '_TZ3000_dpo1ysak', applicationVersion: 68},
            {modelID: 'TS011F', manufacturerName: '_TZ3000_cphmq0q7', applicationVersion: 68},
            {modelID: 'TS011F', manufacturerName: '_TZ3000_5f43h46b', applicationVersion: 68},
            {modelID: 'TS011F', manufacturerName: '_TZ3000_ps3dmato', applicationVersion: 69},
            {modelID: 'TS011F', manufacturerName: '_TZ3000_w0qqde0g', applicationVersion: 68},
	    {modelID: 'TS011F', manufacturerName: '_TZ3000_w0qqde0g', applicationVersion: 64},
	    {modelID: 'TS011F', manufacturerName: '_TZ3000_gjnozsaz', applicationVersion: 68},


        ],
        model: 'TS011F_plug_3',
        description: 'Smart plug (with power monitoring by polling)',
        vendor: 'TuYa',
        whiteLabel: [{vendor: 'VIKEFON', model: 'TS011F'}],
        fromZigbee: [fz.on_off, fz.electrical_measurement, fz.metering, fz.ignore_basic_report, fz.tuya_switch_power_outage_memory],
        toZigbee: [tz.on_off, tz.tuya_switch_power_outage_memory],
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff']);
            endpoint.saveClusterAttributeKeyValue('haElectricalMeasurement', {acCurrentDivisor: 1000, acCurrentMultiplier: 1});
            endpoint.saveClusterAttributeKeyValue('seMetering', {divisor: 100, multiplier: 1});
            device.save();
        },
        options: [exposes.options.measurement_poll_interval()],
        exposes: [e.switch(), e.power(), e.current(), e.voltage().withAccess(ea.STATE),
            e.energy(), exposes.enum('power_outage_memory', ea.STATE_SET, ['on', 'off', 'restore'])
                .withDescription('Recover state after power outage')],
        onEvent: (type, data, device, options) => {
            const endpoint = device.getEndpoint(1);
            if (type === 'stop') {
                clearInterval(globalStore.getValue(device, 'interval'));
                globalStore.clearValue(device, 'interval');
            } else if (!globalStore.hasValue(device, 'interval')) {
                const seconds = options && options.measurement_poll_interval ? options.measurement_poll_interval : 60;
                const interval = setInterval(async () => {
                    try {
                        await endpoint.read('haElectricalMeasurement', ['rmsVoltage', 'rmsCurrent', 'activePower']);
                        await endpoint.read('seMetering', ['currentSummDelivered']);
                    } catch (error) {/* Do nothing*/}
                }, seconds*1000);
                globalStore.putValue(device, 'interval', interval);
            }
        },
    },

];
"

**Comment by grfernandes54** [comment]
As a temporary solutions I've created the external converter using the following commands

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require("zigbee-herdsman-converters/lib/tuya");

const definition = {
fingerprint: [
{
modelID: 'TS011F',
manufacturerName: '_TZ3000_rdtixbnu'
},
],
model: 'LC-011',
vendor: 'Zemismart',
description: 'Brazil Smart Tuya Zigbee Socket BR Plug Wireless Outlet Timing Plug 16A Energy Monitor',
fromZigbee: [fz.on_off, fz.electrical_measurement, fz.metering, fz.ignore_basic_report, fz.tuya_switch_power_outage_memory],
toZigbee: [tz.on_off, tz.tuya_switch_power_outage_memory],
onEvent: tuya.setTime, // Add this if you are getting no converter for 'commandSetTimeRequest'
configure: async (device, coordinatorEndpoint, logger) => {
const endpoint = device.getEndpoint(1);
await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'haElectricalMeasurement', 'seMetering']);
await reporting.rmsVoltage(endpoint, {change: 1, min: 10, max: 600});
await reporting.rmsCurrent(endpoint, {change: 50, min: 10, max: 600});
await reporting.activePower(endpoint, {change: 1, min: 10, max: 600});
await reporting.currentSummDelivered(endpoint, {change: 1, min:10, max: 600});
endpoint.saveClusterAttributeKeyValue('haElectricalMeasurement', {acCurrentDivisor: 1000, acCurrentMultiplier: 1});
endpoint.saveClusterAttributeKeyValue('seMetering', {divisor: 100, multiplier: 1});
device.save();
},
exposes: [e.switch(), e.power(), e.current(), e.voltage().withAccess(ea.STATE),
e.energy(), exposes.enum('power_outage_memory', ea.STATE_SET, ['on', 'off', 'restore'])
.withDescription('Recover state after power outage')],
};

module.exports = definition;


this worked for power on and power off the smart plug  but the power monitoring exposes did not worked

When I replace the code that is working for the code that you suggested I reveived several errors

Code 

<img width="557" alt="image" src="https://user-images.githubusercontent.com/70862164/147127725-df49acf5-b890-45d2-bc52-4977677e11a8.png">


error to start zigbee

[13:54:18] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.1 start
> node index.js
(node:396) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of input
(Use `node --trace-warnings ...` to show where the warning was created)
(node:396) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:396) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[13:54:25] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.1 start
> node index.js

**Comment by Toma82** [comment]
@grfernandes54  remove enter and check then

const exposes = require ('zigbee-herdsman-converters / lib / exposes');
const fz = {... require ('zigbee-herdsman-converters / converters / fromZigbee'), legacy: require ('zigbee-herdsman-converters / lib / legacy'). fromZigbee};
const tz = require ('zigbee-herdsman-converters / converters / toZigbee');
const globalStore = require ('zigbee-herdsman-converters / lib / store');
const ota = require ('zigbee-herdsman-converters / lib / ota');
const tuya = require ('zigbee-herdsman-converters / lib / tuya');
const reporting = require ('zigbee-herdsman-converters / lib / reporting');
const extend = require ('zigbee-herdsman-converters / lib / extend');
const e = exposes.presets;
const ea = exposes.access;
