### ISSUE TITLE
Tuya Motion Sensor modelID: 'TS0202', manufacturerName: '_TZ3000_msl6wxk9' missing battery level

### ISSUE THREAD

**Issue by BlueMahib** [Koenkk/zigbee-herdsman-converters#3592]
I'm missing battery level information for TS0202/ _TZ3000_msl6wxk9 (zigbee-herdsman-converters/devices/tuya.js). 

 {                                                                                        
        fingerprint: [{modelID: 'TS0202', manufacturerName: '_TYZB01_ef5xlc9q'},             
            {modelID: 'TS0202', manufacturerName: '_TYZB01_vwqnz1sn'},                       
            {modelID: 'TS0202', manufacturerName: '_TYZB01_2b8f6cio'},                       
            {modelID: 'TS0202', manufacturerName: '_TYZB01_dl7cejts'},                       
            {modelID: 'TS0202', manufacturerName: '_TYZB01_qjqgmqxr'},                       
            {modelID: 'TS0202', manufacturerName: '_TZ3000_mmtwjmaq'},                       
            {modelID: 'TS0202', manufacturerName: '_TZ3000_kmh5qpmb'},                       
            {modelID: 'TS0202', manufacturerName: '_TYZB01_zwvaj5wy'},                       
            {modelID: 'TS0202', manufacturerName: '_TZ3000_mcxw5ehu'},                       
            {modelID: 'TS0202', manufacturerName: '_TZ3000_msl6wxk9'},                       
            {modelID: 'TS0202', manufacturerName: '_TYZB01_tv3wxhcz'},                       
            {modelID: 'TS0202', manufacturerName: '_TYZB01_hqbdru35'},                       
            {modelID: 'WHD02', manufacturerName: '_TZ3000_hktqahrq'}],                       
        model: 'TS0202',                                                                     
        vendor: 'TuYa',                                                                      
        description: 'Motion sensor',                                                        
        whiteLabel: [{vendor: 'Mercator Iku..', model: 'SMA02P'}],                           
        fromZigbee: [fz.ias_occupancy_alarm_1, fz.battery, fz.ignore_basic_report, fz.ias_occ
        toZigbee: [],                                                                        
        exposes: [e.occupancy(), e.battery_low(), e.tamper(), e.battery()],                  
    }, 

Zigbee2MQTT:info:  '{"battery_low":false,"linkquality":255,"occupancy":false,"tamper":false}'

Any help is highly appreciated. Thanks in advance!

**Comment by Roelski** [comment]
I have the _TZ3000_msl6wxk9 and just received my hub and tuya account. I'll try to see if I get any battery information. So far I only see 100%. Also trying to figure out the PIR sensitivity and Keep time.
