### ISSUE TITLE
converter for LED-Trading 2 ch ac wall switch module

### ISSUE THREAD

**Issue by Rico81** [Koenkk/zigbee-herdsman-converters#3609]
I bought this module:
[https://www.led-trading.de/zigbee-unterputz-schalter-aktor-steuergeraet-controller_1](url)
It's a 2 channel ac in wall switch module.
The model number is UP-SA-9127D.
It is recognized as a "Sunricher" device, model "ON/OFF (2CH)" but not supported.

I am a complete noob and have no clue whatsoever about this stuff.
Nevertheless I somehow managed to copy and paste a working js file. 
So I wanted to share this here because I have no idea what to do 
in order to correctly submit all you would need.
So sorry for this.

Now here is the code:

`const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['ON/OFF(2CH)'],
    model: 'LED-Trading UP-SA-9127D',
    vendor: 'Sunricher',
    description: 'LED-Trading 2 Ch AC switch',
    extend: extend.switch(),
    exposes: [e.switch().withEndpoint('l1'), e.switch().withEndpoint('l2')],
    endpoint: (device) => {
        return {'l1': 1, 'l2': 2};
    },
    toZigbee: [tz.TYZB01_on_off],
    meta: {multiEndpoint: true},
    configure: async (device, coordinatorEndpoint, logger) => {
        await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['genOnOff']);
        await reporting.bind(device.getEndpoint(2), coordinatorEndpoint, ['genOnOff']);
    },
};

module.exports = definition;`

Cheers,

Rico

**Comment by Koenkk** [comment]
Added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
