### ISSUE TITLE
[New manufacturerName] Zigbee smart energy meter DDS238-2 Zigbee

### ISSUE THREAD

**Issue by TRAHOMOTO** [Koenkk/zigbee-herdsman-converters#3611]
Just got new version of **DDS238-2 Zigbee**. Device were recognized only after I added external converter with new **manufacturerName**

```
// tuya.js
{
    fingerprint: [
        {modelID: 'TS0601', manufacturerName: '_TZE200_byzdayie'},
        {modelID: 'TS0601', manufacturerName: '_TZE200_fsb6zw01'},
        {modelID: 'TS0601', manufacturerName: '_TZE200_ewxhg6o9'}, // added new fingerprint
    ],
    model: 'TS0601_din',
    vendor: 'TuYa',
    description: 'Zigbee smart energy meter DDS238-2 Zigbee',
    fromZigbee: [fz.tuya_dinrail_switch],
    toZigbee: [tz.tuya_switch_state],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff']);
    },
    exposes: [e.switch().setAccess('state', ea.STATE_SET), e.voltage(), e.power(), e.current(), e.energy()],
}
```
PS I tried to push this fix but got back 403

**Comment by Koenkk** [comment]
thanks, added!

**Comment by francescros** [comment]
Sorry, I'm a newby - how to get that update? I have zigbee2mqtt installed with docker in Raspberry PI 4B. Where can I manually update tuya.js file or add this line to it? Thanks!

**Comment by Beloutcho** [comment]
Hello,
I Have the same problem.

I use Zigbee2mqtt Edge and a  CC2531 adaptater and i receive this message:

"Received message from unsupported device with Zigbee model 'TS0601' and manufacturer name '_TZE200_ewxhg6o9'"

I tried to creat a new file name tuya.js with this information:
`const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require("zigbee-herdsman-converters/lib/tuya");


const definition = {
    // Since a lot of Tuya devices use the same modelID, but use different data points
    // it's usually necessary to provide a fingerprint instead of a zigbeeModel
    fingerprint: [
        {modelID: 'TS0601', manufacturerName: '_TZE200_byzdayie'},
        {modelID: 'TS0601', manufacturerName: '_TZE200_fsb6zw01'},
        {modelID: 'TS0601', manufacturerName: '_TZE200_ewxhg6o9'}, // added new fingerprint
        },
    ],
    model: 'TS0601_din',
    vendor: 'TuYa',
    description: 'Zigbee smart energy meter DDS238-2 Zigbee',
    fromZigbee: [
        fz.ignore_basic_report, // Add this if you are getting no converter for 'genBasic'
        fz.tuya_dinrail_switch, // This is a debug converter, it will be described in the next part
    ],
    toZigbee: [
        tz.tuya_data_point_test, // Another debug converter
    ],
    onEvent: tuya.onEventSetTime, // Add this if you are getting no converter for 'commandMcuSyncTime'
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genBasic']);
    },
    exposes: [
        e.switch().setAccess('state', ea.STATE_SET),
		e.voltage(),
		e.power(),
		e.current(), 
		e.energy()// Here you should put all functionality that your device exposes
    ],
};

module.exports = definition;

;

`
Unfortunatly, when i try to modify the configuration .yaml like this:

`data_path: /share/zigbee2mqtt
external_converters:
  - tuya.js
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto
  user: *******
  password: ********
serial:
  port: /dev/ttyACM0
advanced:
  log_level: debug
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: pty,raw,echo=0,link=/dev/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
`



I have this error: 
`[15:19:53] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.2-dev start
> node index.js
(node:521) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token '}'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:521) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:521) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`


I also try with the code :
`{
    fingerprint: [
        {modelID: 'TS0601', manufacturerName: '_TZE200_byzdayie'},
        {modelID: 'TS0601', manufacturerName: '_TZE200_fsb6zw01'},
        {modelID: 'TS0601', manufacturerName: '_TZE200_ewxhg6o9'}, // added new fingerprint
    ],
    model: 'TS0601_din',
    vendor: 'TuYa',
    description: 'Zigbee smart energy meter DDS238-2 Zigbee',
    fromZigbee: [fz.tuya_dinrail_switch],
    toZigbee: [tz.tuya_switch_state],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff']);
    },
    exposes: [e.switch().setAccess('state', ea.STATE_SET), e.voltage(), e.power(), e.current(), e.energy()],
}`

But always the same error:
`[15:27:25] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.2-dev start
> node index.js
(node:361) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token ':'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:361) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:361) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Can you help me were is my error please ?

**Comment by francescros** [comment]
my implementation - may not be the most elegant but works.
1) create TS0601.js file with this contents:

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require("zigbee-herdsman-converters/lib/tuya");

const definition = {
    // Since a lot of Tuya devices use the same modelID, but use different data points
    // it's usually necessary to provide a fingerprint instead of a zigbeeModel
    fingerprint: [
        {
            // The model ID from: Device with modelID 'TS0601' is not supported
            // You may need to add \u0000 at the end of the name in some cases
            modelID: 'TS0601',
            // The manufacturer name from: Device with modelID 'TS0601' is not supported.
            manufacturerName: '_TZE200_ewxhg6o9'
        },
    ],
    model: 'TS0601_din',
    vendor: 'TuYa',
    description: 'Zigbee smart energy meter DDS238-2',
    fromZigbee: [fz.tuya_dinrail_switch],
    toZigbee: [tz.tuya_switch_state],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff']);
    },
    exposes: [e.switch().setAccess('state', ea.STATE_SET), e.voltage(), e.power(), e.current(), e.energy()],
};

module.exports = definition;

2) Adding those lines to configuration.yaml

external_converters:
  - TS0601.js

3) re-start zigbee2mqtt and solved

**Comment by Beloutcho** [comment]
Thank you so much, it works perfectly !

**Comment by wizardnl** [comment]
hi guys,

need some help i also have a DDs238-2 with a different manufacturer name 

> ```
> ``my implementation - may not be the most elegant but works.
> 1) create TS0601.js file with this contents:
> 
> const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
> const tz = require('zigbee-herdsman-converters/converters/toZigbee');
> const exposes = require('zigbee-herdsman-converters/lib/exposes');
> const reporting = require('zigbee-herdsman-converters/lib/reporting');
> const extend = require('zigbee-herdsman-converters/lib/extend');
> const e = exposes.presets;
> const ea = exposes.access;
> const tuya = require("zigbee-herdsman-converters/lib/tuya");
> 
> const definition = {
>     // Since a lot of Tuya devices use the same modelID, but use different data points
>     // it's usually necessary to provide a fingerprint instead of a zigbeeModel
>     fingerprint: [
>         {
>             // The model ID from: Device with modelID 'TS0601' is not supported
>             // You may need to add \u0000 at the end of the name in some cases
>             modelID: 'TS0601',
>             // The manufacturer name from: Device with modelID 'TS0601' is not supported.
>             manufacturerName: '_TZE200_ewxhg6o9'
>         },
>     ],
>     model: 'TS0601_din',
>     vendor: 'TuYa',
>     description: 'Zigbee smart energy meter DDS238-2',
>     fromZigbee: [fz.tuya_dinrail_switch],
>     toZigbee: [tz.tuya_switch_state],
>     configure: async (device, coordinatorEndpoint, logger) => {
>         const endpoint = device.getEndpoint(1);
>         await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff']);
>     },
>     exposes: [e.switch().setAccess('state', ea.STATE_SET), e.voltage(), e.power(), e.current(), e.energy()],
> };
> 
> module.exports = definition;
> 
> 2) Adding those lines to configuration.yaml
> 
> external_converters:
>   - TS0601.js
> 
> 3) re-start zigbee2mqtt and solved
> ```

hi guys i need some help i also have a manafacturename issue and i followed the steps from francescros

1 i make a js file and added my manafacture name ; 
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require("zigbee-herdsman-converters/lib/tuya");

const definition = {
    // Since a lot of Tuya devices use the same modelID, but use different data points
    // it's usually necessary to provide a fingerprint instead of a zigbeeModel
    fingerprint: [
        {
            // The model ID from: Device with modelID 'TS0601' is not supported
            // You may need to add \u0000 at the end of the name in some cases
            modelID: 'TS0601',
            // The manufacturer name from: Device with modelID 'TS0601' is not supported.
            manufacturerName: '_TZE200_bkkmqmyo'
        },
    ],
    model: 'TS0601_din',
    vendor: 'TuYa',
    description: 'Zigbee smart energy meter DDS238-2',
    fromZigbee: [fz.tuya_dinrail_switch],
    toZigbee: [tz.tuya_switch_state],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff']);
    },
    exposes: [e.switch().setAccess('state', ea.STATE_SET), e.voltage(), e.power(), e.current(), e.energy()],
};

module.exports = definition;

stored this file next to the configuration.yaml in the zigbee folder. i added the lines to the configuration.yaml and restarted zigbee.

now it's not starting completely and looping with the following message ; 
[16:16:57] INFO: Handing over control to Zigbee2MQTT Core ...
/app/node_modules/js-yaml/lib/loader.js:183
  return new YAMLException(message, mark);
         ^
YAMLException: duplicated mapping key (58:1)
 55 |   port: 8099
 56 | experimental: {}
 57 | availability: false
 58 | external_converters:
------^
 59 |   - TS0601.js
    at generateError (/app/node_modules/js-yaml/lib/loader.js:183:10)
    at throwError (/app/node_modules/js-yaml/lib/loader.js:187:9)
    at storeMappingPair (/app/node_modules/js-yaml/lib/loader.js:358:7)
    at readBlockMapping (/app/node_modules/js-yaml/lib/loader.js:1173:9)
    at composeNode (/app/node_modules/js-yaml/lib/loader.js:1441:12)
    at readDocument (/app/node_modules/js-yaml/lib/loader.js:1625:3)
    at loadDocuments (/app/node_modules/js-yaml/lib/loader.js:1688:5)
    at Object.load (/app/node_modules/js-yaml/lib/loader.js:1714:19)
    at Object.read (/app/lib/util/yaml.ts:7:21)
    at read (/app/lib/util/settings.ts:311:20)
[16:16:58] INFO: Handing over control to Zigbee2MQTT Core ...

i am getting a YAMLException: duplicated mapping key (58:1) ?

greetings

Remco

**Comment by wizardnl** [comment]
hi guys,

i also have a dds238 that had another manufacturer name. i juse the steps of francescros not it's reconiced as a tuya device but it not showing any data? i can only switch the state 


logs show the following errors : 

Debug 2022-09-08 23:12:52Received Zigbee message from '0x84b4dbfffeb8b748', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":1,"dp":16}],"seq":12544}' from endpoint 1 with groupID 0
Warning 2022-09-08 23:12:52zigbee-herdsman-converters:TuyaDinRailSwitch: NOT RECOGNIZED DP #16 with data {"dp":16,"datatype":1,"data":{"type":"Buffer","data":[1]}}
Info 2022-09-08 23:12:52MQTT publish: topic 'zigbee2mqtt/0x84b4dbfffeb8b748', payload '{"current":null,"energy":null,"last_seen":"2022-09-08T21:12:52.908Z","linkquality":90,"power":null,"state":"ON","voltage":null}'
Debug 2022-09-08 23:12:53Received Zigbee message from '0x84b4dbfffeb8b748', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,148,0,0,0,165,2,62,0,4,92,9,8],"type":"Buffer"},"datatype":0,"dp":6}],"seq":12800}' from endpoint 1 with groupID 0
Warning 2022-09-08 23:12:53zigbee-herdsman-converters:TuyaDinRailSwitch: NOT RECOGNIZED DP #6 with data {"dp":6,"datatype":0,"data":{"type":"Buffer","data":[0,0,0,148,0,0,0,165,2,62,0,4,92,9,8]}}
Info 2022-09-08 23:12:53MQTT publish: topic 'zigbee2mqtt/0x84b4dbfffeb8b748', payload '{"current":null,"energy":null,"last_seen":"2022-09-08T21:12:53.918Z","linkquality":90,"power":null,"state":"ON","voltage":null}'
Debug 2022-09-08 23:12:56Received Zigbee message from '0x84b4dbfffeb8b748', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,116],"type":"Buffer"},"datatype":2,"dp":1}],"seq":13056}' from endpoint 1 with groupID 0
Info 2022-09-08 23:12:56MQTT publish: topic 'zigbee2mqtt/0x84b4dbfffeb8b748', payload '{"current":null,"energy":null,"last_seen":"2022-09-08T21:12:56.903Z","linkquality":90,"power":null,"state":"ON","voltage":null}'
Debug 2022-09-08 23:12:57Received Zigbee message from '0x84b4dbfffeb8b748', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,116],"type":"Buffer"},"datatype":2,"dp":101}],"seq":13312}' from endpoint 1 with groupID 0
Warning 2022-09-08 23:12:57zigbee-herdsman-converters:TuyaDinRailSwitch: NOT RECOGNIZED DP #101 with data {"dp":101,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,116]}}
Info 2022-09-08 23:12:57MQTT publish: topic 'zigbee2mqtt/0x84b4dbfffeb8b748', payload '{"current":null,"energy":null,"last_seen":"2022-09-08T21:12:57.904Z","linkquality":90,"power":null,"state":"ON","voltage":null}'
Debug 2022-09-08 23:12:58Received Zigbee message from '0x84b4dbfffeb8b748', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,0],"type":"Buffer"},"datatype":2,"dp":102}],"seq":13568}' from endpoint 1 with groupID 0
Warning 2022-09-08 23:12:58zigbee-herdsman-converters:TuyaDinRailSwitch: NOT RECOGNIZED DP #102 with data {"dp":102,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,0]}}
Info 2022-09-08 23:12:58MQTT publish: topic 'zigbee2mqtt/0x84b4dbfffeb8b748', payload '{"current":null,"energy":null,"last_seen":"2022-09-08T21:12:58.903Z","linkquality":93,"power":null,"state":"ON","voltage":null}'
Debug 2022-09-08 23:12:59Received Zigbee message from '0x84b4dbfffeb8b748', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,149],"type":"Buffer"},"datatype":2,"dp":103}],"seq":13824}' from endpoint 1 with groupID 0
Warning 2022-09-08 23:12:59zigbee-herdsman-converters:TuyaDinRailSwitch: NOT RECOGNIZED DP #103 with data {"dp":103,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,149]}}
Info 2022-09-08 23:12:59MQTT publish: topic 'zigbee2mqtt/0x84b4dbfffeb8b748', payload '{"current":null,"energy":null,"last_seen":"2022-09-08T21:12:59.903Z","linkquality":72,"power":null,"state":"ON","voltage":null}'
Debug 2022-09-08 23:13:00Received Zigbee message from '0x84b4dbfffeb8b748', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,92],"type":"Buffer"},"datatype":2,"dp":109}],"seq":14080}' from endpoint 1 with groupID 0
Warning 2022-09-08 23:13:00zigbee-herdsman-converters:TuyaDinRailSwitch: NOT RECOGNIZED DP #109 with data {"dp":109,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,92]}}
Info 2022-09-08 23:13:00MQTT publish: topic 'zigbee2mqtt/0x84b4dbfffeb8b748', payload '{"current":null,"energy":null,"last_seen":"2022-09-08T21:13:00.903Z","linkquality":93,"power":null,"state":"ON","voltage":null}'
Debug 2022-09-08 23:13:01Received Zigbee message from '0x84b4dbfffeb8b748', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,165],"type":"Buffer"},"datatype":2,"dp":110}],"seq":14336}' from endpoint 1 with groupID 0
Warning 2022-09-08 23:13:01zigbee-herdsman-converters:TuyaDinRailSwitch: NOT RECOGNIZED DP #110 with data {"dp":110,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,165]}}
Info 2022-09-08 23:13:01MQTT publish: topic 'zigbee2mqtt/0x84b4dbfffeb8b748', payload '{"current":null,"energy":null,"last_seen":"2022-09-08T21:13:01.903Z","linkquality":90,"power":null,"state":"ON","voltage":null}'
Debug 2022-09-08 23:13:02Received Zigbee message from '0x84b4dbfffeb8b748', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,2,63],"type":"Buffer"},"datatype":2,"dp":111}],"seq":14592}' from endpoint 1 with groupID 0
Warning 2022-09-08 23:13:02zigbee-herdsman-converters:TuyaDinRailSwitch: NOT RECOGNIZED DP #111 with data {"dp":111,"datatype":2,"data":{"type":"Buffer","data":[0,0,2,63]}}
Info 2022-09-08 23:13:02MQTT publish: topic 'zigbee2mqtt/0x84b4dbfffeb8b748', payload '{"current":null,"energy":null,"last_seen":"2022-09-08T21:13:02.903Z","linkquality":93,"power":null,"state":"ON","voltage":null}'
Debug 2022-09-08 23:13:04Received Zigbee message from '0x84b4dbfffeb8b748', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0],"type":"Buffer"},"datatype":5,"dp":9}],"seq":14848}' from endpoint 1 with groupID 0
Warning 2022-09-08 23:13:04zigbee-herdsman-converters:TuyaDinRailSwitch: NOT RECOGNIZED DP #9 with data {"dp":9,"datatype":5,"data":{"type":"Buffer","data":[0]}}
Info 2022-09-08 23:13:05MQTT publish: topic 'zigbee2mqtt/0x84b4dbfffeb8b748', payload '{"current":null,"energy":null,"last_seen":"2022-09-08T21:13:04.905Z","linkquality":90,"power":null,"state":"ON","voltage":null}'
Debug 2022-09-08 23:13:06Received Zigbee message from '0x84b4dbfffeb8b748', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,0,0,0,0,0,0,0,0,100,0,1,14,0,0,170,0,0,0,0,0,10,0,0,0,0,0,0],"type":"Buffer"},"datatype":0,"dp":17}],"seq":15104}' from endpoint 1 with groupID 0
Info 2022-09-08 23:13:06MQTT publish: topic 'zigbee2mqtt/0x84b4dbfffeb8b748', payload '{"current":null,"energy":null,"last_seen":"2022-09-08T21:13:05.978Z","linkquality":90,"power":null,"state":"ON","voltage":null}'
Debug 2022-09-08 23:13:06Received Zigbee message from '0x84b4dbfffeb8b748', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,5,0,100,0,5,0,30,0,60,0,0,0,0,0,0,0],"type":"Buffer"},"datatype":0,"dp":18}],"seq":15360}' from endpoint 1 with groupID 0
Info 2022-09-08 23:13:06MQTT publish: topic 'zigbee2mqtt/0x84b4dbfffeb8b748', payload '{"current":null,"energy":null,"last_seen":"2022-09-08T21:13:06.037Z","linkquality":93,"power":null,"state":"ON","voltage":null}'
Debug 2022-09-08 23:13:07Received Zigbee message from '0x84b4dbfffeb8b748', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,19,136],"type":"Buffer"},"datatype":2,"dp":105}],"seq":15616}' from endpoint 1 with groupID 0
Warning 2022-09-08 23:13:07zigbee-herdsman-converters:TuyaDinRailSwitch: NOT RECOGNIZED DP #105 with data {"dp":105,"datatype":2,"data":{"type":"Buffer","data":[0,0,19,136]}}
Info 2022-09-08 23:13:07MQTT publish: topic 'zigbee2mqtt/0x84b4dbfffeb8b748', payload '{"current":null,"energy":null,"last_seen":"2022-09-08T21:13:07.905Z","linkquality":90,"power":null,"state":"ON","voltage":null}'

**Comment by wizardnl** [comment]
nobody?
