### ISSUE TITLE
Using Ecozy integration

### ISSUE THREAD

**Issue by asgothian** [Koenkk/zigbee-herdsman-converters#363]
Hi,

I have been trying to use the Ecozy integration to get the thermostat to work with iobroker, but have hit a bit of a wall:
Things i got to work:
```
thermostat_local_temperature, 
thermostat_local_temperature_calibration, 
thermostat_occupied_heating_setpoint, 
thermostat_remote_sensing, 
thermostat_control_sequence_of_operation, 
thermostat_system_mode
```
Things which i did not get to work, and suspect won't work:
```
thermostat_unoccupied_heating_setpoint - accessing this this datapoint directly via the debug option in the adapter returns a "unsupAttribute" error message
thermostat_occupancy - can be read, but does not seem to be reported by the thermostat
```
Things i struggle with
- runningMode (30) can be read from the thermostat, but does not change from "idle"
- the Thermostat does not seem to change its valve position, The valve is constantly open, and only moves if set to pair / repair, this matches the fact that the running mode always returns idle.
- ...weekly_shedule - any time i access this the system crashes, i assume i do not have the correct message format.
- i have been trying to formulate a message to be sent using the developer tab on the zigbee adapter, but so far have been unsuccessful, i always got the response 
```
 {"err":"The argument object has incorrect properties"}
```

Right now, i am working off the assumption that the thermostat needs a schedule to start controlling the valve, but i have been unable to identify the message format / content needed to set a schedule, nor the correct properties to read a schedule off the thermostat.

(see comment on pull request on @sebastianheierhoff ,s fork - https://github.com/sebastianheierhoff/zigbee-shepherd-converters/commit/0bf5916c47f035e494d49568abddb902af4aef40)

**Comment by sebastianheierhoff** [comment]
Some of what you wrote might be correct, as the ecozy implementation is still far from perfect and hasn't been tested a lot. Unfortunately I don't have much time at the moment.
Did you check: http://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html? There is a part regarding message structure.
I will try to have a look at this tomorrow/Monday.

**Comment by asgothian** [comment]
Thank you for the information. I will cross that with my notes and see if i can get somewhere.

**Comment by sebastianheierhoff** [comment]
For basic heating, you don't need a schedule. Sending the desired room temperature to the set topic as occupied_heating_setpoint is sufficient.

**Comment by asgothian** [comment]
that's the thing.. the thermostat does not seem to close the valve, even if i set the target temp to 15 degrees with current temp at 22

**Comment by sebastianheierhoff** [comment]
What does system_mode say?

**Comment by asgothian** [comment]
System mode is set to auto (1). I also tried heat (4)
The running_state never changes from 0 (idle), but that one is read only, as reported by the thermostat when trying to set it directly

**Comment by sebastianheierhoff** [comment]
That's really strange. Even without being paired to an active Zigbee2mqtt instance, my ecozy opens and closes the valve depending on the heating setpoint and the current room temperature.

**Comment by sebastianheierhoff** [comment]
Any updates?

**Comment by asgothian** [comment]
I've been travelling, so no updates. I'll give it a go again this week and let you know.

**Comment by Zagitta** [comment]
I can confirm eCozy behaves rather unpredictable and wonky. I have more or less experience the same behavior as you although it seems to come good after a while. 
Currently I'm implementing and testing a few changes:

- `pi_heating_demand` and `voltage` conversion from here: https://github.com/ckpt-martin/Hubitat/blob/master/eCozy/eCozy-ZigBee-Thermostat-Driver.groovy
- One of my two eCozy devices reports some time stuff upon pairing so I've added `fz.generic_time` and `fz.generic_time_change` to devices.js
- Decrease the reporting intervals of temperature to hopefully increase the currently rather poor battery life. Why was it ever set to report every 5-30 seconds? 

However the main problem I'm running into is that calling `(cb) => device.report('hvacThermostat', 'pIHeatingDemand', 60, 600, 1, cb)` results in a reporting configuration timeout BUT the device actually does seem to start reporting it and I haven't quite figured out why yet.

Last but not least I'm going to try and log `pi_heating_demand` now to see if my thermostats actually do anything.

**Comment by Zagitta** [comment]
I also get stuff like this in the debug console:
```
Received zigbee message of type 'attReport' with data '{"cid":"hvacThermostat","data":{"128":2529,"129":2736,"130":2600}}' of device 'Thermostat' (0x70b3d5de000008e2)
```
Any idea what that could be @Koenkk ?

**Comment by Koenkk** [comment]
@Zagitta these are report from the thermostats, I'm not sure what the data inside means, this has to be reverse engineered.

**Comment by sebastianheierhoff** [comment]
> * Decrease the reporting intervals of temperature to hopefully increase the currently rather poor battery life. Why was it ever set to report every 5-30 seconds?

My ecozy branch was integrated to enable more people to test the thermostat and continue developing the functionality. For testing purposes the regular reporting was helpful. I agree, that battery life is poor, though.

**Comment by tb-killa** [comment]
I bought a complete set with base yesterday.
I will sniff the complete procedure and provide the data.
Based on this data we should revise the converter area accordingly!

**Comment by tb-killa** [comment]
Unstar
