### ISSUE TITLE
Integration error: external_convertors not found

### ISSUE THREAD

**Issue by petervandervoort1953** [Koenkk/zigbee-herdsman-converters#3654]
I'm fairly new to Home-Assistant.
My Configuration RP4, Core-2021.12.3 and Home-Assistant OS 6.6

To be able to use z-wave smoke detection sensors (Heiman HS1SA-Z) I used a Z-Stick Gen5 USB controller.
In HA i installed the Add-on 'Z-Wave JS to MQTT' and the integration Z-Wave JS installed and i have the Mosquitto Broker added. 
After configuration, the Z-stick is recognized. 
Also, after coupling the Z-stick with the smoke detector, the detector is shown, but without any further information and signaling. 
The device is not in the list of preconfigured devices 
I followed [this document ](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#instructions) to add a device configurationfile.  I created a devicefile (hs1sa_z.js), and modified configuration.yaml.

external_converters:
  - /config/hs1sa_z.js
advanced:
  log_level: debug

Using Settings-Server Manager and  'Configuration Validation' I get these errormessages: 
Integration error: advanced - Integration 'advanced' not found. 
Integration error: external_converters - Integration 'external_converters' not found. 

What is missing and what should i install and how should I do that? 
I did not find an integration like 'external_converters'

Please leave a comment.

**Comment by petervandervoort1953** [comment]
This is how it looks like in configuration.yaml
external_converters:
  - /config/hs1sa_z.js
advanced:
  log_level: debug

**Comment by Koenkk** [comment]
This repo has nothing to do with zwave, you are probably looking at the wrong repo.
