### ISSUE TITLE
Hue Dimmer - Separated On & Off state instead of single state

### ISSUE THREAD

**Issue by ulimanaio** [Koenkk/zigbee-herdsman-converters#3693]
Hello,
the remote has 4 buttons in total:
![image](https://user-images.githubusercontent.com/95037770/149839217-405a206b-069d-467f-9a7c-5c190791b030.png)
I would like to suggest to have a state for pressing the on-button and another state for the off-button.
Currently the state is turning true when pressing on and false when pressing off.

My problem is that when I turn my lights on using the button, then off using another device (Alexa) then on the next day I cannot turn the lights on by the button again because the state is still/already true.

Thanks
More information:
#https://github.com/ioBroker/ioBroker.zigbee/issues/1282

(iobroker - Zigbee: 1.6.7)

{ "type": "state", "common": { "name": "Switch state", "type": "boolean", "read": true, "write": false, "role": "switch" }, "native": {}, "from": "system.adapter.zigbee.0", "user": "system.user.admin", "ts": 1637680048247, "_id": "zigbee.0.0017880104f7633b.state", "acl": { "object": 1636, "state": 1636, "owner": "system.user.admin", "ownerGroup": "system.group.administrator" } }

**Comment by danieledwardgeorgehitchcock** [comment]
The Hue Dimmer in Zigbee2MQTT only reports an action, not a state - ant this is momentary i.e. it only reports its state when the button is pressed, then reverts back to an empty / null string.

I am not aware of how ioBroker works, but it may be caching the action value and reporting it as a state. If so, this is not a Z2M issue
