### ISSUE TITLE
Please add support for Hue White ambiance Milliskin

### ISSUE THREAD

**Issue by dielessen** [Koenkk/zigbee-herdsman-converters#3704]
Philips
Hue White ambiance Milliskin

['929003045001_01', '929003045001_02', '929003045001_03']

Are the same as : 5041131P9

Thank you.

**Comment by Koenkk** [comment]
Just added by @mdehaas in https://github.com/Koenkk/zigbee-herdsman-converters/pull/3698

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
