### ISSUE TITLE
Change Name of a Value like "withEndpoint" do, but with own text

### ISSUE THREAD

**Issue by Armin-Ka** [Koenkk/zigbee-herdsman-converters#3711]
Hello,
i am about to Build my own Zigbee Sensor. Sending 2 Temperature Values is Done by using 2 Endpoints. With the "withEndpoint" Function the Converter will add a Suffix to the Values like temperature_l1 & temperature_l2
But this will only work when there are 2 values e.g. "temperature" will come from 2 Endpoints.
But the value humidity (coming from Endpoint 1) will not be labeled with the _l1 suffix, as it is unique.
My Problem is, when adding later another humidity value the first value will be label with the _l1 and the new one with _l2
This makes Problems as the Filters done in Node-Red before will not work anymore.
Is there a possibilitty to give own names (e.g. "temperature_bme280" or "humidity_bme280") to the tempereature/humidity value before going to the MQTT server.
Thanks in advance
Armin

**Comment by Koenkk** [comment]
> Is there a possibilitty to give own names (e.g. "temperature_bme280" or "humidity_bme280") to the tempereature/humidity value before going to the MQTT server.


Yes, you can create your own converter based on https://github.com/Koenkk/zigbee-herdsman-converters/blob/cff751ddfe4b81c799d326581a82e80528316755/converters/fromZigbee.js#L342 , then replace ` const property = postfixWithEndpointName('temperature', msg, model); `  with `const property = 'temperature_bme280;`

**Comment by Armin-Ka** [comment]
Dear Koenkk,
thanks for your Answer. If there is no easier possibility, i will try this. But is there a reason, why the withEndpoint in the exposes Lib will Ignore this if there is only a unique value from the ZigBee Device. I can also life with the Endpoint suffix like temperature_l1, but this has to be added for every value i mark with the withEndpoint option.
