### ISSUE TITLE
[Wrong Device Identification]: Moes No Neutral 2 Gang Identified as Tuya TS0012

### ISSUE THREAD

**Issue by CSH1990** [Koenkk/zigbee-herdsman-converters#3747]
Hello,

Thanks for taking time to support this request. Hope the information provided is sufficient:

Moes website: [https://www.moeshouse.com/products/tuya-zigbee-smart-switch-eu-uk-push-button-wall-light-switch-no-neutral-wire-1-gang?_pos=1&_sid=61b6ee22e&_ss=r&variant=32454391660625](url)

data/dabase.db extract:
`{
  "id": 15,
  "type": "EndDevice",
  "ieeeAddr": "0xec1bbdfffe2db611",
  "nwkAddr": 27454,
  "manufId": 4098,
  "manufName": "_TYZB01_vzrytttn",
  "powerSource": "Mains (single phase)",
  "modelId": "TS0012",
  "epList": [
    1,
    2
  ],
  "endpoints": {
    "1": {
      "profId": 260,
      "epId": 1,
      "devId": 256,
      "inClusterList": [
        0,
        4,
        5,
        6
      ],
      "outClusterList": [
        25
      ],
      "clusters": {
        "genBasic": {
          "attributes": {
            "65506": 19,
            "modelId": "TS0012",
            "manufacturerName": "_TYZB01_vzrytttn",
            "powerSource": 3,
            "zclVersion": 3,
            "appVersion": 255,
            "stackVersion": 0,
            "hwVersion": 1,
            "dateCode": ""
          }
        }
      },
      "binds": [
        {
          "cluster": 6,
          "type": "endpoint",
          "deviceIeeeAddress": "0x00124b00238da5f0",
          "endpointID": 1
        }
      ],
      "configuredReportings": [],
      "meta": {}
    },
    "2": {
      "profId": 260,
      "epId": 2,
      "devId": 256,
      "inClusterList": [
        4,
        5,
        6
      ],
      "outClusterList": [],
      "clusters": {},
      "binds": [
        {
          "cluster": 6,
          "type": "endpoint",
          "deviceIeeeAddress": "0x00124b00238da5f0",
          "endpointID": 1
        }
      ],
      "configuredReportings": [],
      "meta": {}
    }
  },
  "appVersion": 255,
  "stackVersion": 0,
  "hwVersion": 1,
  "dateCode": "",
  "zclVersion": 3,
  "interviewCompleted": true,
  "meta": {
    "configured": 2
  },
  "lastSeen": 1643186563988,
  "useImplicitCheckin": true
}`

**Comment by rhayun** [comment]
i am having the same issue - can it be added to next version?
