### ISSUE TITLE
IKEA 345lm GU10 (LED1923R5/TRADFRI bulb GU10 CWS 380lm)

### ISSUE THREAD

**Issue by al3x1337** [Koenkk/zigbee-herdsman-converters#3835]
![image](https://user-images.githubusercontent.com/44815197/152726485-e2842419-b2b7-44ec-8652-893ea36aaa46.png)

From what I can tell comparing to the [ikea.js in the master ](https://raw.githubusercontent.com/Koenkk/zigbee-herdsman-converters/master/devices/ikea.js), the only difference is the vendor name for my device I bought today in Canada is "IKEA of Sweden" instead of "IKEA".

I've tried to make the change by copying the ikea.js and unloading it as an external converter as i have with 3 other devices already but am getting errors:
```
  (node:943) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'precision' of undefined
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by Koenkk** [comment]
This device should work in z2m 1.23.0

**Comment by al3x1337** [comment]
Closing this. I was on the Hassio Edge plugin thinking that it would be more updated than the master but the z2m version there was 1.21.x
Works fine on the regular version of Zigbee2Mqtt in Hassio
