### ISSUE TITLE
[HELP-DEV] Frame for the pilot wire modes of the Legrand 064882 device

### ISSUE THREAD

**Issue by EXP-Carthage** [Koenkk/zigbee-herdsman-converters#3851]
Hello,
in order to finish the support of the Legrand 064882 device, I need your help.
This device does not yet manage the Pilot Wire modes...

deCONZ manages these modes and I came across this code :
``` cpp
bool DeRestPluginPrivate::addTaskControlModeCmd(TaskItem &task, uint8_t cmdId, int8_t mode)
{
    task.taskType = TaskThermostat;

    task.req.setClusterId(LEGRAND_CONTROL_CLUSTER_ID);  /* 0xFC40 */
    task.req.setProfileId(HA_PROFILE_ID);               /* 0x0104 */        

    task.zclFrame.payload().clear();
    task.zclFrame.setSequenceNumber(zclSeq++);
    task.zclFrame.setCommandId(cmdId);                  /* 0x00 */
    task.zclFrame.setFrameControl(deCONZ::ZclFCClusterCommand |
            deCONZ::ZclFCDirectionClientToServer);     /* 0x01 | 0x00 */

    // payload
    QDataStream stream(&task.zclFrame.payload(), QIODevice::WriteOnly);
    stream.setByteOrder(QDataStream::LittleEndian);

    if (cmdId == 0x00)
    {
        stream << (qint8) mode;
    }
    else
    {
        return false;
    }

    { // ZCL frame
        task.req.asdu().clear(); // cleanup old request data if there is any
        QDataStream stream(&task.req.asdu(), QIODevice::WriteOnly);
        stream.setByteOrder(QDataStream::LittleEndian);
        task.zclFrame.writeToStream(stream);
    }

    return addTask(task);
}
```
I also saw that on Domoticz, these modes are also managed :
``` python
sqn = get_and_inc_SQN(self, nwkid)

fcf = "15"
manufcode = "1021"
cmd = "00"
data = "%02x" % CABLE_OUTLET_MODE[Mode]
payload = fcf + manufcode[2:4] + manufcode[0:2] + sqn + cmd + data
raw_APS_request(
    self,
    nwkid,
    EPout,
    "fc40",
    "0104",
    payload,
    zigate_ep=ZIGATE_EP,
    ackIsDisabled=is_ack_tobe_disabled(self, nwkid),
)
```

So I decided to take inspiration from it but the task is more complicated than expected...
Here is what I have now :
``` javascript
legrand_cableOutletMode: {
    key: ['cable_outlet_mode'],
    convertSet: async (entity, key, value, meta) => {
        const mode = {
            'comfort': 0x00,
            'comfort-1': 0x01,
            'comfort-2': 0x02,
            'eco': 0x03,
            'frost_protection': 0x04,
            'off': 0x05,
        };
        const options = {
            direction: 0,
            manufacturerCode: 0x1021,
        };
        const payload = {0: {value: mode[value], type: 48}};
        await entity.write(64576, payload, options);
    },
    convertGet: async (entity, key, meta) => {
        await entity.read(64576, [0x0000], manufacturerOptions.legrand);
    },
},
```
Here is what I can observe in the terminal by adding a `console.log` on the ZclFrame :
```
ZclFrame {
  Header: {
    frameControl: {
      reservedBits: 0,
      frameType: 0,
      direction: 0,
      disableDefaultResponse: true,
      manufacturerSpecific: true
    },
    transactionSequenceNumber: 9,
    manufacturerCode: 4129,
    commandIdentifier: 2
  },
  Payload: [ { attrId: 0, attrData: 5, dataType: 48 } ],
  Cluster: {
    ID: 64576,
    attributes: {},
    manufacturerCode: null,
    name: '64576',
    commands: {},
    commandsResponse: {},
    getAttribute: [Function: getAttribute],
    hasAttribute: [Function: hasAttribute],
    getCommand: [Function: getCommand],
    getCommandResponse: [Function: getCommandResponse]
  },
  Command: {
    ID: 2,
    name: 'write',
    parameters: [ [Object], [Object], [Object] ],
    response: 4
  }
}
```
And here is the error from the terminal :
``` bash
Zigbee2MQTT:error 2022-02-10 13:47:50: Publish 'set' 'cable_outlet_mode' to '0x000474000011041c' failed: 'Error: Write 0x000474000011041c/1 64576({"0":{"value":5,"type":48}}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4129,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'READ_ONLY')'
```

You will have noticed that the 0x0000 attribute of the 0xFC40 cluster is read only.
And from what I could read and understand, only a specific frame can be sent so that the device interprets it and updates this attribute by itself...

For all this, I ask for your help. I also specify that I own this device so if you have some code to test, don't hesitate to propose it to me

**Comment by EXP-Carthage** [comment]
@Koenkk You will surely know how to answer me.
Is there a solution to display in the terminal the raw frame sent ?
Like `18 C3 0A 55 00 21 01 00` ?

It would allow me to debug all this and to move forward on this subject.

**Comment by Koenkk** [comment]
Could you make a sniff when this frame is send by deconz? https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html#with-cc2531

Share the sniff (pcapng file) + network key here.

**Comment by EXP-Carthage** [comment]
I currently don't have the necessary equipment to sniff this frame...

**Comment by EXP-Carthage** [comment]
Here, I just sniffed the frames.
The commands sent via deCONZ are in this order :
`Comfort > Off > Comfort`.

The pcapng file is available [here](https://store4.gofile.io/download/bb2ab079-06f0-45cc-9824-3de8dcf16abd/legrand_064882.pcapng).
The network key is as follows : `31:35:36:64:37:66:62:36:31:65:66:62:32:65:32:62`.

I took a quick look at the pcapng file and honestly, I didn't understand much...

**Comment by Koenkk** [comment]
I cannot decrypt the sniff with `31:35:36:64:37:66:62:36:31:65:66:62:32:65:32:62`, can you provide another sniff where you pair the device to deconz so I can get the network key from that?

**Comment by Koenkk** [comment]
I've added the command, update to the latest dev and try sending it by calling: `await entity.command('manuSpecificLegrandDevices2', 'command0', {data: Buffer.from([0])};`, the value in the buffer.from array indicates the mode (0x00 - 0x05)

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by EXP-Carthage** [comment]
After testing, I have this error :
```
Zigbee2MQTT:error 2022-02-15 20:44:52: Publish 'set' 'cable_outlet_mode' to '0x000474000011041c' failed: 'Error: Command 0x000474000011041c/1 manuSpecificLegrandDevices2.command0({"data":5}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4129,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Write for 'BUFFER' not available)'
```

It will work one day :smile:

**Comment by EXP-Carthage** [comment]
Well, it seems to work pretty well. I'll finish the integration and do the pull request next.
Many thanks for your precious help :+1:
