### ISSUE TITLE
Aqara P1 contact sensor extra option

### ISSUE THREAD

**Issue by DJTerentjev** [Koenkk/zigbee-herdsman-converters#3865]
By copy&paste I add [converter](https://github.com/Koenkk/zigbee-herdsman-converters/pull/3858) for Aqara P1 contact sensor, but it should have extra option. 
According to manual with device, distance on which it will be counted "off" can be adjusted to 10, 20 or 30 mm. 
Could you please help me to add this option. Is it possible to do without  Aqara hub?  Please let me know if required extra information.

**Comment by Koenkk** [comment]
If you sniff the traffic when setting this via the Aqara hub we can add this (we need to know what to send).

Once you have the sniff share the network key + pcpang file here: https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html#with-cc2531

**Comment by DJTerentjev** [comment]
I don't have Aqara hub. 
Should device send current setting? Then we can guess what can be send to device ... may be?
If it's impossible to do without Aqara hub better to close the issue.

**Comment by Koenkk** [comment]
We need the hub, maybe @z-x-f has one

**Comment by tjxism** [comment]
I have a Aqara Hub and I am planning to flasher a sniffer. How to determine what channel aqara is using?

**Comment by z-x-f** [comment]
Can only try which channel aqara gateway uses.
First, pair p1 with aqara gateway, set the sensing distance of P1 in the aqara app, and then you can sniff the packets you need.

**Comment by DJTerentjev** [comment]
> But what’s more broken is the sensor isn’t reporting open/close after the newest update.

What type of stick do you have? And what firmware? Recently firmware was updated to be able to work with new aqara stuff. I don't have aqara gateway, but try channel 11 first.
