### ISSUE TITLE
KSentry state_report

### ISSUE THREAD

**Issue by gadolithium** [Koenkk/zigbee-herdsman-converters#389]
KSentry onoff supports the 'attReport' feature. 

`4/7/2019, 4:39:32 AM - debug: Received zigbee message of type 'attReport' with data '{"cid":"genOnOff","data":{"onOff":0}}' of device 'Lamp_01' (0xxxxxxxxxxxxxxxxxxxxxxxxxx)`

The converter state_report needs to be added to ksentry at line 2806 of devices.js:
https://github.com/Koenkk/zigbee-shepherd-converters/blob/00a725573f89b2d14e9e52b588b050429f12efd1/devices.js#L2806

**Comment by Koenkk** [comment]
Could you  make a pr for this?
