### ISSUE TITLE
Add support to the existing Lidl Livarno E14 due to a new version model _TZ3000_wr6g6olr

### ISSUE THREAD

**Issue by alexandervis** [Koenkk/zigbee-herdsman-converters#3910]
Hi Koenk,
I bought 2 new Zigbee bulb from Lidl today and to my supprise Livarno has multiple versions of the same model because the first bulb the _TZ3000_th6zqqy6 configures fine, but the 2nd one, the _TZ3000_wr6g6olr gives the not supported message and is not defined in the lidl.js file. 

Zigbee2MQTT:warn 2022-02-21 20:01:13: Device '0x847127fffe0c939a' with Zigbee model 'TS0505B' and manufacturer name '_TZ3000_wr6g6olr' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

Could you add the _TZ3000_wr6g6olr bulb the same as the _TZ3000_th6zqqy6
Bulb data:
360063_2010
Model:HG07834B
Version:07/2021

`{
        fingerprint: [
              {modelID: 'TS0505B', manufacturerName: '_TZ3000_wr6g6olr'},
              {modelID: 'TS0505B', manufacturerName: '_TZ3000_th6zqqy6'},
        ],
        model: 'HG07834B',
        vendor: 'Lidl',
        description: 'Livarno Lux E14 candle RGB',
        ...extend.light_onoff_brightness_colortemp_color({disableColorTempStartup: true, colorTempRange: [153, 500]}),
        meta: {applyRedFix: true, enhancedHue: false},
        configure: async (device, coordinatorEndpoint, logger) => {
            device.getEndpoint(1).saveClusterAttributeKeyValue('lightingColorCtrl', {colorCapabilities: 29});
        },
    },`

**Comment by Koenkk** [comment]
Added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
