### ISSUE TITLE
Add support for Humidity & Temperature Sensor _TZ3000_fllyghyj 

### ISSUE THREAD

**Issue by danielk117** [Koenkk/zigbee-herdsman-converters#3914]
Hi,

I add this Humidity & Temperature Sensor (https://www.aliexpress.com/item/1005003718187629.html). I tought it is a WSD500A, but it was recognized as TS0201.

I tried the following as external converter. I didn't know the model... So I just stay at WSD500A for now.
```
const exposes = require('/app/node_modules/zigbee-herdsman-converters/lib/exposes');
const fz = {...require('/app/node_modules/zigbee-herdsman-converters/converters/fromZigbee'), legacy: require('/app/node_modules/zigbee-herdsman-converters/lib/legacy').fromZigbee};
const tz = require('/app/node_modules/zigbee-herdsman-converters/converters/toZigbee');
const ota = require('/app/node_modules/zigbee-herdsman-converters/lib/ota');
const tuya = require('/app/node_modules/zigbee-herdsman-converters/lib/tuya');
const reporting = require('/app/node_modules/zigbee-herdsman-converters/lib/reporting');
const extend = require('/app/node_modules/zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

module.exports = {
        fingerprint: [{modelID: 'TS0201', manufacturerName: '_TZ3000_fllyghyj'}],
        model: 'WSD500A',
        vendor: 'TuYa',
        description: 'Temperature & humidity sensor',
        fromZigbee: [fz.battery, fz.temperature, fz.humidity],
        toZigbee: [],
        exposes: [e.battery(), e.temperature(), e.humidity(), e.battery_voltage()],
};
```

I will make a PR, when finishing my investigation.

**Comment by LivArt01** [comment]
Hi, I also have this sensor - it shows bad temperature (like -10 for 20 and so on) and for humidity too. Does it work normally with this external converter? It seems not working on HA for now.

**Comment by orrpan** [comment]
Something like this should work
```js
...
    {
        fingerprint: [
            {modelID: 'TS0201', manufacturerName: '_TZ3000_bguser20'},
            {modelID: 'TS0201', manufacturerName: '_TZ3000_fllyghyj'},
        ],
        model: 'WSD500A',
        vendor: 'TuYa',
        description: 'Temperature & humidity sensor',
        fromZigbee: [fz.battery, fz.temperature, fz.humidity],
        toZigbee: [],
        exposes: [e.battery(), e.temperature(), e.humidity(), e.battery_voltage()],
    },
...
```

**Comment by danielk117** [comment]
@orrpan Thats right. But battery and battery_voltage seems to be defferent and isn't working.
Can someone with the previous WSD500A (_TZ3000_bguser20) confirm, that battery is working for this device?

**Comment by orrpan** [comment]
@danielk117 okey, I’ve added the line on my setup now to see if I get any different result (regarding battery/voltage, as it switches to the correct device directly). 

I unfortunately don’t have any device made by the other manufacturer.

**Comment by Tendonitis** [comment]
I have the same issue, where can I change this external connector so it works? 
Thanks!

**Comment by danielk117** [comment]
Problem with battery still exists, but there seems no fix for this. As `_TZ3000_fllyghyj` was already added, i close this now.

**Comment by danielk117** [comment]
I did some tests with `_TZ3000_fllyghyj` and `_TZ3000_dowj6gyi`. I was able to get battery reporting working. See PR

**Comment by JohnMcLear** [comment]
On mine after successful pairing I get 0 values for humidity and temp, it's probably unrelated but I wanted to post for posterity because I'm probably going to put this sensor in a draw as it doesn't appear to function.

```
{
    "last_seen": "2022-08-08T17:49:49.684Z",
    "linkquality": 21,
    "battery": 100,
    "humidity": 0,
    "temperature": 0,
    "voltage": 3000
}
```

**Comment by Mistic92** [comment]
I have the same issue. It was working for long time but stopped reporting anything other than 0 
```
{
    "battery": 100,
    "humidity": 0,
    "last_seen": "2025-08-11T16:52:31.189Z",
    "linkquality": 128,
    "temperature": 0,
    "voltage": 3000
}
```

For TS0201 - _TZ3000_fllyghyj
