### ISSUE TITLE
IKEA E1842 Knycklan valve missing "leak" binary sensor

### ISSUE THREAD

**Issue by sliwma** [Koenkk/zigbee-herdsman-converters#3949]
As mentioned in the [discussion](https://github.com/Koenkk/zigbee2mqtt/discussions/10627), @MarkoMarjamaa states that in ZHA it supports water leak binary sensor.

**Comment by MarkoMarjamaa** [comment]
Hi, 
I added the water leak sensor to my custom converter. Can this be added to official version also? 

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const ota = require('zigbee-herdsman-converters/lib/ota');

const definition = {
        zigbeeModel: ['KNYCKLAN receiver'],
        model: 'E1842',
        description: 'KNYCKLAN receiver electronic water valve shut-off',
        vendor: 'IKEA',
        extend: extend.switch(),
        extend: extend.switch(),
        fromZigbee: extend.switch().fromZigbee.concat([fz.ias_water_leak_alarm_1]),
        exposes: extend.switch().exposes.concat([e.water_leak()]),
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff']);
            await reporting.onOff(endpoint);
        },
        ota: ota.tradfri,
    };

module.exports = definition;

If anyone need this too before official version, you can add it like this: 
https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_2-adding-your-device

**Comment by sliwma** [comment]
Hey Marko, I think you should raise a PR to merge it with the code. Thanks for solving the issue.

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
