### ISSUE TITLE
Help to integrate Connecte Smart thermostat

### ISSUE THREAD

**Issue by frankis78** [Koenkk/zigbee-herdsman-converters#3969]
Hi, 
Can someone help me to create a converter for This Underfloor Thermostat?
https://www.connecte.no/termostat
[For utviklere og avanserte smarthus systemer som krever koding av Connecte termostat.docx](https://github.com/Koenkk/zigbee-herdsman-converters/files/8206026/For.utviklere.og.avanserte.smarthus.systemer.som.krever.koding.av.Connecte.termostat.docx)

I think maybe this converter can be used as a base.
https://gist.github.com/geoffreylagaisse/bb90214dbaf687465e5841f49685cf66?fbclid=IwAR15VWWydzMFwawYACieviTSE4DtvjEaMOQ0WqZHJ-kVlK5gHHF4VPV_gaI#file-tv01-zg-js

The Thermostat went into system as unsupported
Device type: Router
Zigbee Model: TS0601
Zigbee Manufacturer: _TZE200_4hbx5cvx
Support status: Not supported

Thank you

**Comment by ihelland** [comment]
I am really interested in this as well. Unfortunately I am not a very skilled programmer myself. 

@frankis78: how do you plan to integrate the Connecte thermostat?

I have tried with ZHA, Deconz and Zigbee2MQTT (all via Conbee 2), but without any success. 
Attached you will find all the information I got from the thermostat in the Zigbee2MQTT interface.

Also, I have read the following documentation regarding use of external converters (with Zigbee2MQTT), but so far not tested anything.
[https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#instructions]
<img width="1552" alt="Screenshot 2022-03-09 at 19 52 07" src="https://user-images.githubusercontent.com/81987012/157514043-8586b126-7c0d-4fcc-967d-08aa2b5d9141.png">
(url)

I really hope we can get this thermostat supported. :
<img width="1552" alt="Screenshot 2022-03-09 at 19 51 59" src="https://user-images.githubusercontent.com/81987012/157514096-84ee0c16-89ef-4f60-8f0f-39bda1d56715.png">
<img width="1552" alt="Screenshot 2022-03-09 at 19 52 46" src="https://user-images.githubusercontent.com/81987012/157514215-145a84fa-2921-497b-a9ca-e6758eb111a8.png">
)

**Comment by frankis78** [comment]
Im also not a programmer, but i still can manage some things. 
I think i should be able to do some adjustments on the external converter, but there is one thing in the manual i dont understand.
Can someone tell me if it is enough to work with ONLY the external converter file while testing, and that this file will work as an override file before it is merged into the source?
Or do i also NEED to add parts of the external converter file code to the source files while testing.
The source files im mentioning are these 3 files in picture.
![2022-03-09_20-21-34](https://user-images.githubusercontent.com/26933092/157516741-780084e4-34ef-4bd1-88fe-3093de5fc4f0.png)

**Comment by frankis78** [comment]
The only message i get from the thermostat is this
Received Zigbee message from 'Termostat stue', type 'attributeReport', cluster 'genBasic', data '{"appVersion":67}' from endpoint 1 with groupID 0

**Comment by frankis78** [comment]
Duplicate issue, please look.
https://github.com/Koenkk/zigbee2mqtt/issues/11895
