### ISSUE TITLE
Xiaomi WRS-R02 can't pair to Zigbee2MQTT

### ISSUE THREAD

**Issue by OBubnik** [Koenkk/zigbee-herdsman-converters#4011]
I can't pair this "Aqara wireless remote switch H1 (double rocker)"
It returns:
Device '0x54ef4410001af49a' with Zigbee model 'lumi.remote.b28ac1' and manufacturer name 'LUMI' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html"
But even with this page I'm not successful.

**Comment by z-x-f** [comment]
What version is your z2m?

**Comment by OBubnik** [comment]
MQTT broker in Home Assistant is 6.0.1
And version of Zigbee2MQTT is 1.18.1

**Comment by z-x-f** [comment]
Ah, WRS-02 is only supported since 1.19, you need to update your z2m.

**Comment by OBubnik** [comment]
> Ah, WRS-02 is only supported since 1.19, you need to update your z2m.

Yes. I!ve reinstalled Z2M on a new version and problem have been solved.
Thanks!
