### ISSUE TITLE
TuYa U86KCJ-ZP

### ISSUE THREAD

**Issue by unpack8866** [Koenkk/zigbee-herdsman-converters#4030]
TuYa U86KCJ-ZP there is another model of this device. Please add it. thank you！
zigbeeModel: 005f0c3
<img width="924" alt="7A65CC8A-00A2-4493-8349-3D2AC1F39E81" src="https://user-images.githubusercontent.com/40196105/159493369-7ed078a5-c587-439d-9d37-d0c2ae2d9c25.png">
b

**Comment by Koenkk** [comment]
Done

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by unpack8866** [comment]
> Done
> 
> Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

Not added in version 1.25.0
