### ISSUE TITLE
"Min rep change" seems not to work as I expect

### ISSUE THREAD

**Issue by pcornill** [Koenkk/zigbee-herdsman-converters#4056]
Hello, I used to manage my Zigbee devices with 3 Sonoff bridges runing Tasmota firmaware.
From the configuration point of you and to save IoT battery, I used to set the "Reportable change" to 0.5 °C, MaxInterval: 3600 sec and MinInterval: 300 sec.
The result of that configuration was: No more than 1 report per 5 minutes, at least a report every hour and more frequently if change of temperature > 0.5 °C.
When I set "Min rep change" to 0.5 and Min rep Interval to 300 I alway get a report every 300 sec (5 mn) even if temperature doesn't change much (Ex: 20.29, 20.32, 20.38, etc...)

Am I wrongly interpreting the "Min rep change" parameter?

**Comment by sjorge** [comment]
On what attribute are you adding the reporting? if it is msTemperature.meassuredValue ? Then you need to use `50`to get 0.5C change.
10 -> 0.1 C
25 -> 0.25 C
50 -> 0.5 C
100 -> 1 C
250 -> 2.5 C
and so forth.

**Comment by pcornill** [comment]
Excellent, I actually used 0.5 value!
What about humidity %, is-it the same or 10 is 10%?
Is that documented somewhere?
Thanks a lot
________________________________

**Comment by sjorge** [comment]
IIRC for humidy `10` = 1%.

This info is available in the [Zigbee-Cluster-Library.pdf](https://github.com/Koenkk/zigbee-herdsman/blob/master/docs/07-5123-08-Zigbee-Cluster-Library.pdf) for msTempetature ...

```
7031 4.4.2.1.1.1 MeasuredValue At tribute
7032 MeasuredValue represents the temperature in degrees Celsius as follows:
7033 MeasuredValue = 100 x temperature in degrees Celsius.
7034 Where -273.15°C <= temperature <= 327.67 ºC, corresponding to a MeasuredValue in the range 0x954d to 0x7fff.
7035 The maximum resolution this format allows is 0.01 ºC.
7036 A MeasuredValue of 0x8000 indicates that the temperature measurement is unknown, otherwise the range SHALL be
7037 as described in 4.1.3.
7038 MeasuredValue is updated continuously as new measurements are made. MinMeasuredValue and MaxMeasuredValue
7039 define the range of the sensor.
```

**Comment by PaJaSoft** [comment]
> IIRC for humidy `10` = 1%.

Based on provided docs, I can read from there the spec for `msRelativeHumidity` is the same like for `msTemperatureMeasurement` - see 4.7.2.1.1. MeasuredValue Attribute (for Water Content Measurement):

> 4.7.2.1.1  MeasuredValue Attribute
MeasuredValue represents the water content in % as follows:
MeasuredValue = 100 x water content
Where 0% <= water content <= 100%, corresponding to a MeasuredValue in the range 0 to 0x2710.
The maximum resolution this format allows is 0.01%.
