### ISSUE TITLE
Tried but couldn't PR an unsupported TS0601 Curtain motor.

### ISSUE THREAD

**Issue by SirGoodenough** [Koenkk/zigbee-herdsman-converters#4063]
// Roman Rod - I Type - Curtains Track (Multi-Motor)
        {modelID: 'TS0601', manufacturerName: '_TZE200_cf1sl3tj'},

        {vendor: 'Zemismart', model: 'ZM85EL-2Z', description: 'Roman Rod - I Type - Curtains Track'},

It should be an easy add.  
To make it work I added my device specific information(above) to this external converter showing in another issue:
https://github.com/Koenkk/zigbee-herdsman-converters/pull/4001#issuecomment-1067956559

This is the actual external converter that is working for me:
https://github.com/SirGoodenough/Home-Assistant-Config/blob/master/zigbee2mqtt/ZM85EL-2Z.js

For reference I saw the instructions and it said create a markdown file. [reference these instructions](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_4-add-device-picture-to-zigbee2mqtt-io-documentation) There was already a file for TS0601_cover.md.  The only thing I needed to edit was add the name info but the file said that is auto-generated, don't edit there, only edit notes.  I didn't know where to go with that.
Then it said edit the other file, and the only thing I got to work was that long and complicated external file on my addon version, so stuck 2x.
If I had the wrong instructions or something, please guide me and I will try again.

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
