### ISSUE TITLE
Tried to change Prolight.js multiple times, but changes didn't fall through

### ISSUE THREAD

**Issue by JWvdVeer** [Koenkk/zigbee-herdsman-converters#4070]
Probably it's due to my lack of experience with github and I didn't find a manual, therefore I decided to post it here...

I tried to change the code for the PROLIGHT_REMOTE_CONTROL many times, because the code lacks some functionality this remote has:
```
{
	zigbeeModel: ['PROLIGHT REMOTE CONTROL'],
	model: 'PROLIGHT_REMOTE_CONTROL',
	vendor: 'Prolight',
	description: 'Remote control',
	fromZigbee: [fz.command_on, fz.command_off, fz.command_move_to_level, fz.command_move, fz.command_stop, fz.command_move_to_color_temp, fz.command_move_to_color, fz.command_move_color_temperature, fz.battery],
	exposes: [e.battery(), e.action(['on', 'off', 'color_temperature_move', 'color_temperature_move_up', 'color_temperature_move_down', 'color_move', 'brightness_move_up', 'brightness_move_down', 'brightness_stop', 'brightness_move_to_level'])],
	toZigbee: []
}
```

So, I hope it will find it's way to the code from here. And if someone is willing to give me some pointers how to make this problem not happen again next time, I would be grateful.

**Comment by Koenkk** [comment]
Instead of changing `prolight.js` directly you can use an external converter which overrides the definition in `prolight.js`:

```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
	zigbeeModel: ['PROLIGHT REMOTE CONTROL'],
	model: 'PROLIGHT_REMOTE_CONTROL',
	vendor: 'Prolight',
	description: 'Remote control CUSTOM',
	fromZigbee: [fz.command_on, fz.command_off, fz.command_move_to_level, fz.command_move, fz.command_stop, fz.command_move_to_color_temp, fz.command_move_to_color, fz.command_move_color_temperature, fz.battery],
	exposes: [e.battery(), e.action(['on', 'off', 'color_temperature_move', 'color_temperature_move_up', 'color_temperature_move_down', 'color_move', 'brightness_move_up', 'brightness_move_down', 'brightness_stop', 'brightness_move_to_level'])],
	toZigbee: []
};

module.exports = definition;

```

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, go to the frontend, verify that the description of the device ends with CUSTOM (this means that external converter has been loaded correctly)

**Comment by JWvdVeer** [comment]
> Instead of changing `prolight.js` directly you can use an external converter which overrides the definition in `prolight.js`:
> 
> ```js
> const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
> const tz = require('zigbee-herdsman-converters/converters/toZigbee');
> const exposes = require('zigbee-herdsman-converters/lib/exposes');
> const reporting = require('zigbee-herdsman-converters/lib/reporting');
> const extend = require('zigbee-herdsman-converters/lib/extend');
> const ota = require('zigbee-herdsman-converters/lib/ota');
> const e = exposes.presets;
> const ea = exposes.access;
> 
> const definition = {
> 	zigbeeModel: ['PROLIGHT REMOTE CONTROL'],
> 	model: 'PROLIGHT_REMOTE_CONTROL',
> 	vendor: 'Prolight',
> 	description: 'Remote control CUSTOM',
> 	fromZigbee: [fz.command_on, fz.command_off, fz.command_move_to_level, fz.command_move, fz.command_stop, fz.command_move_to_color_temp, fz.command_move_to_color, fz.command_move_color_temperature, fz.battery],
> 	exposes: [e.battery(), e.action(['on', 'off', 'color_temperature_move', 'color_temperature_move_up', 'color_temperature_move_down', 'color_move', 'brightness_move_up', 'brightness_move_down', 'brightness_stop', 'brightness_move_to_level'])],
> 	toZigbee: []
> };
> 
> module.exports = definition;
> ```
> 
> * save this as file next to `configuration.yaml` as `ext_converter.js`
> * add it to `configuration.yaml`:
> 
> ```yaml
> external_converters:
>   - ext_converter.js
> ```
> 
> * start z2m, go to the frontend, verify that the description of the device ends with CUSTOM (this means that external converter has been loaded correctly)

I already did, and it's working like a charm. This was actually a copy-paste from my definition file. But I wanted you share it for the greater benefit of all ;).

But apparently I turned out not to be trusted or clumsy, so my code changes didn't end up in the final master branch.

So, I thought: asking probably can't hurt #durf-te-vragen
