### ISSUE TITLE
Philips Hue Flourish -  929003053601

### ISSUE THREAD

**Issue by krukka** [Koenkk/zigbee-herdsman-converters#4136]
Model number: 929003053601 is not detected/unsupported.
This is the same as:

 zigbeeModel: ['4090531P9'],
        model: '4090531P9',
        vendor: 'Philips',
        description: 'Hue Flourish white and color ambiance ceiling light with Bluetooth',
        meta: {turnsOffAtBrightness1: true},
        extend: hueExtend.light_onoff_brightness_colortemp_color(),
        ota: ota.zigbeeOTA,

**Comment by Koenkk** [comment]
Added.
