### ISSUE TITLE
Tuya Device S05-LN not correct included

### ISSUE THREAD

**Issue by larryxxl2** [Koenkk/zigbee-herdsman-converters#4158]
device is QS-Zigbee-S05-LN (⭐EXP) (QS-Zigbee-S05-LN) with neutral.

undefined not described in states Mapping error. Device displayed in iobroker as Zigbee TS0001.

**Comment by larryxxl2** [comment]
Lonsonho QS-Zigbee-S05-LN   / wrong identify as Tuya TS0001 1gang switch

**Comment by larryxxl2** [comment]
![image](https://user-images.githubusercontent.com/96195330/170230435-3c3ee262-208a-4fbd-a295-77f3120007fa.png)

**Comment by larryxxl2** [comment]
Überdachung Licht Relais
![IMG_20220404_180532](https://user-images.githubusercontent.com/96195330/170231617-b6b30dea-45de-4484-af38-5da7aa5cb205.jpg)

**Comment by larryxxl2** [comment]
Lonsonho QS-Zigbee-S05-LN / wrong identify as Tuya TS0001 1gang switch
![image](https://user-images.githubusercontent.com/96195330/170232229-304afb3a-6e37-4340-930e-d480db2fde9c.png)

**Comment by larryxxl2** [comment]
The difference between a relay and a button is that the relay needs incoming connections in order to work

**Comment by suarezcp87** [comment]
Hello i have the same problem in z2m Lonsonho QS-Zigbee-S05-LN / wrong identify as Tuya TS0001 1gang switch? must be if i am not wrong 
 fingerprint: [{modelID: 'TS0003', manufacturerName: '_TYZB01_ncutbjdi'}],
 model: 'QS-Zigbee-S05-LN',
 vendor: 'Lonsonho',
 description: '1 gang switch module with neutral wire',
maybe there is some solution to the problem??

**Comment by disTuRb3dx** [comment]
Is there now a solution to the problem?
