### ISSUE TITLE
Tradfri bulbs also loses other configuration like color_options.execute_if_off

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee-herdsman-converters#4192]
I ran into this while looking up something:
https://github.com/Koenkk/zigbee-herdsman-converters/blob/e0788055412bf0ceb28224a1e0033ff747e7ded4/devices/ikea.js#L16

I have a work around in my devicequirks extension to restore color_options.execute_if_off when it's found in the state.

It probably makes sense to add it here too, I'll try to do so during the next weekend.

**Comment by Koenkk** [comment]
@sjorge it is not passed yet, but this can easily be done by changing https://github.com/Koenkk/zigbee2mqtt/blob/3f6a13786e67445840521cf8f41b030221a24dee/lib/extension/onEvent.ts#L46 to `await device.definition.onEvent(type, data, device.zh, device.options, this.state.get(device));`

**Comment by sjorge** [comment]
Aha! That would explain why I couldn’t find it at all, I’ll do the change locally while working on this and do 2 PR’s the.

**Comment by sjorge** [comment]
Hmmm looks like it's not happy with that change:
```
lib/extension/onEvent.ts:46:84 - error TS2554: Expected 4 arguments, but got 5.

46             await device.definition.onEvent(type, data, device.zh, device.options, this.state.get(device));
                                                                                      ~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in lib/extension/onEvent.ts:46
```

I'm guessing that there is some definition somewhere I missed that is making tsc comaplian.

**Comment by sjorge** [comment]
z2m pr: https://github.com/Koenkk/zigbee2mqtt/pull/12407
zhc pr: https://github.com/Koenkk/zigbee-herdsman-converters/pull/4217

**Comment by Koenkk** [comment]
Merged, thanks!
