### ISSUE TITLE
The file fromZigbee.js is too large to be indexed by GitHub search

### ISSUE THREAD

**Issue by wixoff** [Koenkk/zigbee-herdsman-converters#4257]
The size of the file is 396 KB, and per GitHub documentation the maximum size for search indexing is 384 KB.  See https://docs.github.com/en/search-github/searching-on-github/searching-code#considerations-for-code-search.

Background: I have been struggling to search for the root cause behind https://github.com/Koenkk/zigbee2mqtt/issues/12230.  A code search for the string "action_user" turned up no hits in the  zigbee2mqtt, zigbee-herdsman, or zigbee-herdsman-converters repositories.  It turns out the hits would have been in `fromZigbee.js` which isn't currently indexed.

The file `toZigbee.js` is approaching this threshold size as well.

Can we consider a way to split these files?

**Comment by Koenkk** [comment]
> Can we consider a way to split these files?

Best way to do this is to move some manufacturer specific converters into the manufacturer file (e.g. https://github.com/Koenkk/zigbee-herdsman-converters/blob/2da3d247108773e69d87310ddd8e72e7232fb370/devices/tuya.js#L48)
