### ISSUE TITLE
S-LUX-ZB (_TZE200_pisltm67) battery state

### ISSUE THREAD

**Issue by leroyloren** [Koenkk/zigbee-herdsman-converters#4310]
Would it be possible for the device to round the decimal to 0?

`{
    "battery": "92.0",
    "battery_low": "0.0",
    "illuminance_lux": "0",
    "last_seen": "2022-06-01T23:47:50+02:00",
    "linkquality": 83
}`

![obrazek](https://user-images.githubusercontent.com/57643470/171508846-da602263-0e4f-44f5-8a48-e9cef0063d2a.png)

**Comment by Koenkk** [comment]
fixed.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
