### ISSUE TITLE
Add support to Zemismart Wall 6 Gang Switch (Tuya TS0601_TZE200_9mahtqtg)

### ISSUE THREAD

**Issue by jairbj** [Koenkk/zigbee-herdsman-converters#4311]
Please add support for Zemismart Wall 6 Gang Switch (Tuya TS0601_TZE200_9mahtqtg)

Device type: EndDevice
Zigbee Model: TS0601
Zigbee Manufacturer: _TZE200_9mahtqtg

As reference, it has been added in ZHA by this pull request:
https://github.com/zigpy/zha-device-handlers/pull/1559

**Comment by jairbj** [comment]
I found how to configure that. Will make a pull request later.

**Comment by platbr** [comment]
Hi Jair,
I have subscribe this issue to test it as soon as you release it.

Saudações =D

**Comment by platbr** [comment]
I found your code.

**Comment by Koenkk** [comment]
Fixed by https://github.com/Koenkk/zigbee-herdsman-converters/pull/4315

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
