### ISSUE TITLE
Add color-temperature to device settings

### ISSUE THREAD

**Issue by Zaunmich** [Koenkk/zigbee-herdsman-converters#4349]
I wanted to set the minimum and maximum color temperature values for my LED Controller (e.g., https://www.zigbee2mqtt.io/devices/GL-C-006P.html#gledopto-gl-c-006p) and saw that it was not possible in the GUI.

The color temp is hardcoded to lie between 150 and 500 mired (the default values). However, the device could be connected to any LED strip which has a different color temperature range. It could be beneficial if the user could specify the color temp range on a device-to-device basis.

For example, the device in mention even has a `{noConfigure: true}` option in the settings file:
https://github.com/Koenkk/zigbee-herdsman-converters/blob/3e30868e19b75fc163801055bb724f9adce649e9/devices/gledopto.js#L129

Here is an example where the color temp was specified in the settings file (which makes sense, as it is a light-bulb with a known color range:
https://github.com/Koenkk/zigbee-herdsman-converters/blob/3e30868e19b75fc163801055bb724f9adce649e9/devices/adeo.js#L21

My question now is: Is it possible to add [device-specific settings](https://www.zigbee2mqtt.io/guide/configuration/devices-groups.html#specific-device-options), where the user could specify the range?

**Comment by tommials** [comment]
@Koenkk would it be possible to implemet this? In my case I would need this setting for Gledopto GL-C-006P. This setting should really be a standard for all led WW/CW controllers.

**Comment by karipov** [comment]
I have the exact same question. Is this fixable software-side or is this a hardware issue?

**Comment by tommials** [comment]
> I have the exact same question. Is this fixable software-side or is this a hardware issue?

I resolved it by building a two channel ESP32 led controller, maybe you should consider it also 😁https://www.espthings.io/index.php/2021/05/02/5-channel-analog-led-controller-et-al01/
