### ISSUE TITLE
Add model 'TS0505B' and manufacturer name '_TZ3000_q50zhdsc'

### ISSUE THREAD

**Issue by Tra2x** [Koenkk/zigbee-herdsman-converters#4371]
Could somebody please add Zigbee model 'TS0505B' and manufacturer name '_TZ3000_q50zhdsc' in the lidl.js

        fingerprint: [{modelID: 'TS0505B', manufacturerName: '_TZ3000_q50zhdsc'}],
        model: 'HG08131C',
        vendor: 'Lidl',
        description: 'Livarno Home outdoor E27 bulb in set with flare',

I don't know if I could change it by myself or how to do it. Sorry completly noob.
Thanks in advance

**Comment by Koenkk** [comment]
Will be handled in https://github.com/Koenkk/zigbee-herdsman-converters/pull/4377
