### ISSUE TITLE
fromZigbee.tuya_switch_power_outage_memory doesn't work, because of attribute check

### ISSUE THREAD

**Issue by gorbunovav** [Koenkk/zigbee-herdsman-converters#4385]
There is a check for attribute `0x8002`:
https://github.com/Koenkk/zigbee-herdsman-converters/blob/a88c04ce95062e78c09a356bb94dc8a3959ec616/converters/fromZigbee.js#L7276

But this attribute is listed under name `moesStartUpOnOff` in cluster definition:
[moesStartUpOnOff](https://github.com/Koenkk/zigbee-herdsman/blob/772d2edcc0e442a84fe8faa91dff2f0ae36e81ad/src/zcl/definition/cluster.ts#L460)
so the method receives it as a string and the check always fails.

There is also newer `moes_power_on_behavior` converter, which looks similar, but uses correct attribute name:
https://github.com/Koenkk/zigbee-herdsman-converters/blob/a88c04ce95062e78c09a356bb94dc8a3959ec616/converters/fromZigbee.js#L2561

At the `toZigbee` side converters look close also, but the `moes_power_on_behavior` variant contains the `get` converter in addition:
https://github.com/Koenkk/zigbee-herdsman-converters/blob/a88c04ce95062e78c09a356bb94dc8a3959ec616/converters/toZigbee.js#L2580

https://github.com/Koenkk/zigbee-herdsman-converters/blob/a88c04ce95062e78c09a356bb94dc8a3959ec616/converters/toZigbee.js#L3583

**Comment by Koenkk** [comment]
Could you submit a pr for this?

**Comment by Koenkk** [comment]
> The simple fix would be to just update the attribute reference in tuya_switch_power_outage_memory.

Sounds good

> But I wanted to clarify first - do we need both moes_power_on_behavior and tuya_switch_power_outage_memory converters or can they be merged?

Lets keep both since changing this would be somewhat a breaking change.

**Comment by ansantos** [comment]
Hi, I have this Moes smart switch (https://moeshouse.com/products/eu-star-ring-smart-light-switch-1?variant=45282168340795), and I have an issue with z2m when setting power-on behavior. I can see this option but cannot change it. I get this error message when z2m is trying to set the attribute:

z2m: Publish 'set' 'power_on_behavior' to 'Interruptor Casa de Banho' failed: 'Error: Unknown attribute 'moesStartUpOnOff', specify either an existing attribute or a number'

I get this when z2m tries to get the attribute:

z2m: Publish 'get' 'power_on_behavior' to 'Interruptor Casa de Banho' failed: 'Error: ZCL command 0xa4c138b44f88c9c2/1 genOnOff.read(["moesStartUpOnOff"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Status 'FAILURE')'

This works well with the dimmer version of these switches.

Z2M version is 2.10.0-1, running HA 2026.04.

Thanks
