### ISSUE TITLE
Support for GL-G-003P Garden lights

### ISSUE THREAD

**Issue by Hjelen** [Koenkk/zigbee-herdsman-converters#4444]
Hi! I would be thrilled if anyone added support for GL-G-003P, 7w garden lights. I tried myself, but didn't work.

**Comment by Hjelen** [comment]
I tried to copy te raw text into my file, and get all these warnings.

**Comment by Koenkk** [comment]
Please fill in https://github.com/Koenkk/zigbee2mqtt/issues/new?assignees=&labels=new+device+support&template=new_device_support.yaml&title=%5BNew+device+support%5D%3A+
