### ISSUE TITLE
The ubisys H1 uses a pIHeatingDemand scale of 0-100 not 0-254 as per the ZCL

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee-herdsman-converters#4514]
The ubisys H1 uses a pIHeatingDemand scale of 0-100 not 0-254 as per the ZCL, 

https://github.com/Koenkk/zigbee-herdsman-converters/blob/f575f5789f48067cca3148615e5e970034cd5e95/converters/fromZigbee.js#L111-L114

Does a straight mapping, so I can either create a copy of that one specifically for ubisys that takes the raw value. Or introduce a meta property to not map the value.

I'm leaning towards the 2nd solution as it can probably be used for other devices too,  but I have no time this weekend to look at this so mostly a issue to track this so I do not forget.

**Comment by sjorge** [comment]
having a meta option for this seems the way to go, then we can eliminate:
https://github.com/Koenkk/zigbee-herdsman-converters/blob/f575f5789f48067cca3148615e5e970034cd5e95/converters/fromZigbee.js#L2491-L2502
and
https://github.com/Koenkk/zigbee-herdsman-converters/blob/f575f5789f48067cca3148615e5e970034cd5e95/converters/fromZigbee.js#L3520-L3523

**Comment by Koenkk** [comment]
Meta looks as the best choice indeed.
