### ISSUE TITLE
MOES UFO-R11 doesn't work as a remote

### ISSUE THREAD

**Issue by shaysudm** [Koenkk/zigbee-herdsman-converters#4543]
Zigbee2MQTT shows that the device exposes all required fields for the universal remote to work:
![image](https://user-images.githubusercontent.com/106470158/185478844-99aad5d3-52bd-4937-83bb-690c11f435ef.png)

but in MQTT send IR code is missing:
![image](https://user-images.githubusercontent.com/106470158/185479063-579286fb-d229-44a1-b939-df750731dca5.png)

and in general its not being recognized as a remote thus the remote integration doesn't work with it.

**Comment by shaysudm** [comment]
@mak-42 any recommendations?

**Comment by mak-42** [comment]
> @mak-42 any recommendations?
It looks like you are trying to add the device to Home Assistant, am I right? If it is you should ask HA community forum. I use openHab.
