### ISSUE TITLE
How To Map Exposed Controls To Settings (Specific) Instead Of Exposes?

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [Koenkk/zigbee-herdsman-converters#4546]
Hi,

Just wondering if there is a way to split out and expose some of the configure once type settings for my device in the Settings (Specific) tab / screen in the WebUI as opposed to bundling them all into the Exposes tab / screen.

The settings are for things such as:

- Cycle Timer Value
- Random Timer Value
- Language
- Inching Switch Behaviour

The above are applied at a device level as opposed to individual endpoints

**Comment by Koenkk** [comment]
The difference between the settings and expose tab is that settings are set at the z2m side, everything under exposes is set at the device side.
