### ISSUE TITLE
Four gang switch paired in zigbee2mqtt pressing one of the buttons by Home Assistant only switches the buttons simultaneously.

### ISSUE THREAD

**Issue by mdanilohome** [Koenkk/zigbee-herdsman-converters#4603]
Hi, i performed pairing in zigbee2mqtt from a 4 gang switch. Once the pairing was completed, I activated one of the buttons through Home Assistant and observed that all the other buttons simultaneously toggled on or off.
I cannot activate the buttons individually by HA. In the physical, when I touch one of the buttons, it works correctly, that is, it switches only the button that I touch.
I removed the device from zigbee 2mqtt and decided to pair through a tuya hub in smart life.
By the APP, this simultaneous command does not happen when I activate only one of the buttons.
In the APP there is a button to turn on and another to turn off all buttons at the same time, in addition to individual buttons.
What I noticed with this is that when pairing is done in zigbee2mqtt, only commands are enabled for simultaneous switching only and it doesn't allow to do commands individually on buttons in Home Assistant. I would like to know if an external converter would solve it and if so, help me in the elaboration of the codes to create the command lines for the creation of the external converter file. 

https://user-images.githubusercontent.com/86743538/188316730-b22e6713-9dfa-4673-aa0d-9a98cf9a3f35.mp4

![Switch Meakiss TS0004 no Z2m](https://user-images.githubusercontent.com/86743538/188316732-e27303e8-908a-4be9-8a2e-198570552ada.jpeg)

Thanks.

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by mdanilohome** [comment]
OK thank you! Just one more question, as I'm a beginner, how should I proceed? Just pair the device again in zigbee2mqtt?

**Comment by Koenkk** [comment]
Just upgrade, if that doesn't help also repair it.
