### ISSUE TITLE
Aqara D1  is also support Exposes  voltage

### ISSUE THREAD

**Issue by phoenixxie0** [Koenkk/zigbee-herdsman-converters#4608]
Aqara D1 3 gang smart wall switch (with neutral wire) is also support voltage.
In MQTT message 
Info 2022-09-05 14:12:06MQTT publish: topic 'zigbee2mqtt/0x54ef44100025279f', payload '{"action":null,"consumption":0.01,"current":0,"device":{"applicationVersion":32,"dateCode":"08-26-2020","friendlyName":"0x54ef44100025279f","hardwareVersion":1,"ieeeAddr":"0x54ef44100025279f","manufacturerID":4447,"manufacturerName":"LUMI","model":"QBKG26LM","networkAddress":22119,"powerSource":"Mains (single phase)","stackVersion":2,"type":"Router","zclVersion":3},"device_temperature":31,"energy":0.01,"flip_indicator_light":"OFF","last_seen":"2022-09-05T14:12:06+08:00","led_disabled_night":false,"linkquality":163,"operation_mode_center":"decoupled","operation_mode_left":"decoupled","operation_mode_right":"decoupled","power":0.01,"power_outage_count":5,"power_outage_memory":true,"state":"OFF","state_center":"OFF","state_left":"OFF","state_right":"OFF","update":{"state":"available"},"update_available":true,"voltage":238.4}'

We can see the voltage is support. And it is 238.4V.. But on the page [https://www.zigbee2mqtt.io/devices/QBKG26LM.html#xiaomi-qbkg26lm](url).  There is only Exposes | switch (state), operation_mode, power, power_outage_memory, led_disabled_night, device_temperature, flip_indicator_light, action, linkquality

**Comment by Koenkk** [comment]
Added!
