### ISSUE TITLE
[REQUEST] Sonoff Zigbee OTA provider for Sonoff branded Zigbee devices by ITead

### ISSUE THREAD

**Issue by Hedda** [Koenkk/zigbee-herdsman-converters#4610]
@Daniel-zhan-itead Now that ITead's official Sonoff Zigbee OTA provider server is online and available for third-party use, please also consider convincing ITead management to have their engineers also work on a Sonoff Zigbee OTA provider for Sonoff branded Zigbee devices by ITead to this zigbee-herdsman-converters project which is used by Zigbee2MQTT and IoBroker.

https://zigbee-ota.sonoff.tech/releases/upgrade.json

https://github.com/Koenkk/zigbee-herdsman-converters/tree/master/lib/ota

https://sonoff.tech/products/

https://itead.cc/?s=Zigbee&post_type=product&type_aws=true

PS: For reference; [lisongjun12](https://github.com/lisongjun12) has ex. contributed OTA provider code to zigpy library used by ZHA integration in Home Assistant:

https://github.com/zigpy/zigpy/pull/1040

https://github.com/zigpy/zigpy/blob/dev/zigpy/ota/provider.py#L413-619

**Comment by Daniel-zhan-itead** [comment]
> @Daniel-zhan-itead Now that ITead's official Sonoff Zigbee OTA provider server is online and available for third-party use, please also consider convincing ITead management to have their engineers also work on a Sonoff Zigbee OTA provider for Sonoff branded Zigbee devices by ITead to this zigbee-herdsman-converters project which is used by Zigbee2MQTT and IoBroker.
> 
> https://zigbee-ota.sonoff.tech/releases/upgrade.json
> 
> https://github.com/Koenkk/zigbee-herdsman-converters/tree/master/lib/ota

Our team will develop Zigbee devices OTA for Zigbee2MQTT and IoBroker application as you requested. Expected Q4 of 2022.

**Comment by Hedda** [comment]
@Koenkk May I suggest you reopen this and mark it as not-stale as ITead/Sonoff product manager wrote they will work on this?

**Comment by Daniel-zhan-itead** [comment]
As [guozi7788](https://github.com/Koenkk/zigbee-OTA/commits?author=guozi7788) update the ZBMINI-L firmware image to the repository https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/lib/ota/OTA_URLs.md#koenkk-zigbee-ota-repository, I've updated the ZBMINI-L firmware via OTA successfully in Zigbee2mqtt.

I would like to confirm that if the SONOFF OTA Provider [https://zigbee-ota.sonoff.tech/releases/upgrade.json] follow the override OTA index file structure as the [main index file](https://github.com/Koenkk/zigbee-OTA/blob/master/index.json), users are able to update the firmware via OTA if they configure the URL field to SONOFF OTA Provider?
![image](https://user-images.githubusercontent.com/54268313/197492571-f235087e-df56-45c3-be80-709efadc2888.png)

Please advise, thanks.
