### ISSUE TITLE
Enocean PTM 216Z: missing command

### ISSUE THREAD

**Issue by THorst92** [Koenkk/zigbee-herdsman-converters#4621]
Hi @Koenkk,
I've already created an issue in the zigbee2mqtt repository for this topic (Koenkk/zigbee2mqtt#13804), but after some investigation I think I've found the problem, which is related to the converter.

In the following snippet the ID is put together by the commandID and the whole commandFrame. 
https://github.com/Koenkk/zigbee-herdsman-converters/blob/811789fbae0d3570d666f1141dde2b9091a9a99a/converters/fromZigbee.js#L5122

According to the log, the commandFrame does include more than the needed information. For example if I press the top left button the following commandID and commandFrame is sent:
`data '{"commandFrame":{"raw":{"data":[1,254,165,76],"type":"Buffer"}},"commandID":105`
The expected ID is `105_1` but with the code mentioned above the ID is `105_1_254_165_76`. So only the first item of the commandFrame must be appended. The last item (here value 76) seems to be the link quality.

What do you think about this?

I use zigbee2mqtt as an addon in home assistant and unfortunately I do not know how I could test the adaption. 

Best regards,

Thorsten

**Comment by Koenkk** [comment]
Can you try changing `msg.data.commandFrame.raw.join('_')` to `msg.data.commandFrame.raw.slice(0,2).join('_')`

**Comment by THorst92** [comment]
Do you know if I can do this directly in the HomeAssistant Addon?

**Comment by Koenkk** [comment]
You can use this external converter:

```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;

const fzLocal = {
    enocean_ptm216z: {
        cluster: 'greenPower',
        type: ['commandNotification', 'commandCommisioningNotification'],
        convert: (model, msg, publish, options, meta) => {
            const commandID = msg.data.commandID;
            if (hasAlreadyProcessedMessage(msg, msg.data.frameCounter, `${msg.device.ieeeAddr}_${commandID}`)) return;
            if (commandID === 224) return;

            // Button 1: A0 (top left)
            // Button 2: A1 (bottom left)
            // Button 3: B0 (top right)
            // Button 4: B1 (bottom right)
            const lookup = {
                '105_1': 'press_1', '105_2': 'press_2', '105_3': 'press_1_and_2', '105_4': 'press_3', '105_5': 'press_1_and_3',
                '105_6': 'press_3_and_4', '105_7': 'press_1_and_2_and_3', '105_8': 'press_4', '105_9': 'press_1_and_4',
                '105_10': 'press_2_and_4', '105_11': 'press_1_and_2_and_4', '105_12': 'press_3_and_4', '105_13': 'press_1_and_3_and_4',
                '105_14': 'press_2_and_3_and_4', '105_15': 'press_all', '105_16': 'press_energy_bar', '106_0': 'release',
            };

            const ID = `${commandID}_${msg.data.commandFrame.raw.slice(0,2).join('_')}`;
            if (!lookup.hasOwnProperty(ID)) {
                meta.logger.error(`PTM 216Z: missing command '${ID}'`);
            } else {
                return {action: lookup[ID]};
            }
        },
    }
};

const definition = {
    fingerprint: [{modelID: 'GreenPower_7', ieeeAddr: /^0x00000000015.....$/}],
    model: 'PTM 216Z',
    vendor: 'EnOcean',
    description: 'Pushbutton transmitter module',
    fromZigbee: [fzLocal.enocean_ptm216z],
    toZigbee: [],
    exposes: [e.action(['press_1', 'press_2', 'press_1_and_2', 'press_3', 'press_1_and_3', 'press_3_and_4', 'press_1_and_2_and_3',
        'press_4', 'press_1_and_4', 'press_2_and_4', 'press_1_and_2_and_4', 'press_3_and_4', 'press_1_and_3_and_4',
        'press_2_and_3_and_4', 'press_all', 'press_energy_bar', 'release'])],
};

module.exports = definition;

```

**Comment by THorst92** [comment]
After changing the line to
`            const ID = `${commandID}_${msg.data.commandFrame.raw.slice(0,1).join('_')}`;`
and adding the line 
`
const {
    precisionRound, mapNumberRange, isLegacyEnabled, toLocalISOString, numberWithinRange, hasAlreadyProcessedMessage,
    calibrateAndPrecisionRoundOptions, addActionGroup, postfixWithEndpointName, getKey,
    batteryVoltageToPercentage, getMetaValue,
} = require('zigbee-herdsman-converters/lib/utils');
`
it is working!

Thanks a lot!

**Comment by Koenkk** [comment]
Great, integrated the fix!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
