### ISSUE TITLE
Read State Of Another Cluster After Receiving Event

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [Koenkk/zigbee-herdsman-converters#4653]
Is it possible to trigger a read of another cluster after receiving an event?

An example would be that an alarm event is received on genAlarms which is actually an unlock / lock event - could I then trigger a read from closuresDoorLock to fetch the state?

The closuresDoorLock state is not returned automatically on event of the device (but can be read manually) whereas the genAlarms notification is.

**Comment by Koenkk** [comment]
Yes this is possible, but do you know the state of the lock/unlock based on the genAlarms message?

To read in fromZigbee:

```
const result = await msg.endpoint.read('genOnOffSwitchCfg', ['switchType']);
```

**Comment by danieledwardgeorgehitchcock** [comment]
Short answer - not necessarily. Alarm events seem to be generated for other things as well as lock / unlock so, the most reliable way to determine the lock state would be to read it each time on an alarm event..?

Thanks, I'll give the above a try

**Comment by Koenkk** [comment]
Change `convert: (model, msg, publish, options, meta) => {` to `convert: async (model, msg, publish, options, meta) => {`
