### ISSUE TITLE
Saswell SEA801-Zigbee/SEA802-Zigbee - ME167 Zigbee Thermostat

### ISSUE THREAD

**Issue by BastiKN** [Koenkk/zigbee-herdsman-converters#4694]
Hello,

please put the Device in the Supported List :-) Thank and sorry for my Bad English

https://github.com/Koenkk/zigbee2mqtt/issues/13727
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6318

Thank You an have a nice Day

**Comment by BastiKN** [comment]
Can me help by the Problem?
I have 6 from this Thermostate ( ME167 )
My ioBroker Show no Temperatur in the Zigbee Adapter.

**Comment by chbmuc** [comment]
There is already a custom converter: https://github.com/twhittock/avatto_me167

But it would be nice if this would be merged upstream.

**Comment by Thesola10** [comment]
No no no, this should definitely be reopened

**Comment by Koenkk** [comment]
Should be supported now. 
Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
