### ISSUE TITLE
Aqara E1 3 gang switch (with neutral) action show us null

### ISSUE THREAD

**Issue by fata1ityz** [Koenkk/zigbee-herdsman-converters#4706]
Hi all, I have some issue with getting action to work when trigger from Aqara E1 3 gang switch (with neutral). Device was not officially supported and I created the device manually with the below definition based on the 2 gang switch (with neutral) setup. Action is show as null and logs not showing anything when I try to trigger single or double click. Using Sonoff zigbee dongle-E with zigbee2mqtt edge. Greatly appreciate any help on this. Thank You!

`const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const preventReset = async (type, data, device) => { // PLEASE READ: can be deleted as /devices/xiaomi.js already have it.
    if (
        // options.allow_reset ||
        type !== 'message' ||
        data.type !== 'attributeReport' ||
        data.cluster !== 'genBasic' ||
        !data.data[0xfff0] ||
        // eg: [0xaa, 0x10, 0x05, 0x41, 0x87, 0x01, 0x01, 0x10, 0x00]
        !data.data[0xFFF0].slice(0, 5).equals(Buffer.from([0xaa, 0x10, 0x05, 0x41, 0x87]))
    ) {
        return;
    }
    const options = {manufacturerCode: 0x115f};
    const payload = {[0xfff0]: {
        value: [0xaa, 0x10, 0x05, 0x41, 0x47, 0x01, 0x01, 0x10, 0x01],
        type: 0x41,
    }};
    await device.getEndpoint(1).write('genBasic', payload, options);
}; // PLEASE READ: THE END OF THE BLOCK THAT CAN BE DELETE WHEN MERGING WITH XIAOMI.JS

const definition = {
    zigbeeModel: ['lumi.switch.acn040'],
    model: 'ZNQBKG31LM',
    vendor: 'Xiaomi',
    description: 'Aqara E1 3 gang switch (with neutral)',
    fromZigbee: [fz.on_off, fz.xiaomi_multistate_action, fz.aqara_opple],
    toZigbee: [tz.on_off, tz.xiaomi_switch_operation_mode_opple, tz.xiaomi_switch_power_outage_memory,
        tz.xiaomi_flip_indicator_light],
    meta: {multiEndpoint: true},
    endpoint: (device) => {
        return {'left': 1, 'center': 2, 'right': 3};
    },
    exposes: [
        e.switch().withEndpoint('left'), e.switch().withEndpoint('center'), e.switch().withEndpoint('right'),
        exposes.enum('operation_mode', ea.ALL, ['control_relay', 'decoupled'])
            .withDescription('Decoupled mode for left button')
            .withEndpoint('left'),
		exposes.enum('operation_mode', ea.ALL, ['control_relay', 'decoupled'])
            .withDescription('Decoupled mode for center button')
            .withEndpoint('center'),
        exposes.enum('operation_mode', ea.ALL, ['control_relay', 'decoupled'])
            .withDescription('Decoupled mode for right button')
            .withEndpoint('right'),
        e.action([
            'single_left', 'double_left', 'single_center', 'double_center',
            'single_right', 'double_right', 'single_left_center', 'double_left_center',
            'single_left_right', 'double_left_right', 'single_center_right', 'double_center_right',
            'single_all', 'double_all']),
        e.power_outage_memory(), e.device_temperature(), e.flip_indicator_light(),
    ],
    onEvent: preventReset,
    configure: async (device, coordinatorEndpoint, logger) => {
        await device.getEndpoint(1).write('aqaraOpple', {'mode': 1}, {manufacturerCode: 0x115f, disableResponse: true});
    },
	};

module.exports = definition;` 

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/102287386/192160626-639512bb-5855-470e-931d-4d912a090915.png">

<img width="718" alt="image" src="https://user-images.githubusercontent.com/102287386/192160642-e584f024-fbdb-4ca9-b179-df150453843e.png">

<img width="734" alt="image" src="https://user-images.githubusercontent.com/102287386/192160652-fcbb36b5-ea4a-4c0a-ab75-dc8746f029e7.png">

**Comment by sxrcm** [comment]
[ZNQBKG31LM](https://www.zigbee2mqtt.io/devices/ZNQBKG31LM.html#xiaomi-znqbkg31lm)can not pair now
