### ISSUE TITLE
#469 broke CALEX lightbulb

### ISSUE THREAD

**Issue by Fossdal** [Koenkk/zigbee-herdsman-converters#471]
The definition for Calex white led (modelID "EC-Z3.0-CCT "s missing an space at the ending of its definition. it was right but got changed in #469. 
i just  updated my zigbee2mqtt and now the lightbulb dos not work and i get in the log 
Jun 05 23:51:51 raspberrypi npm[12814]:   zigbee2mqtt:warn 6/5/2019, 11:51:51 PM Device with modelID 'EC-Z3.0-CCT ' is not supported.

if you look closly there is an space character after the T in the modelID

**Comment by Koenkk** [comment]
Can you make a PR to fix it?
