### ISSUE TITLE
WS-EUK01 - Aqara smart wall switch H1 EU (no neutral, single rocker) - decoupled not working and action is N/A

### ISSUE THREAD

**Issue by clmun** [Koenkk/zigbee-herdsman-converters#4722]
For switch WS-EUK01 the action is not exposed. I think that's why also decouple mode is not possible.
![image](https://user-images.githubusercontent.com/16850783/193122027-6178fd5e-7398-45f9-90cb-59e875a33592.png)

Has anybody managed to solve this?

**Comment by clmun** [comment]
I also have a switch Xiaomi WXKG01LM and I see that also for this action is N/A

2 days ago I had Z2M version 1.18 and this switch worked, I could have seen when switch was pressed (once, twice, long hold) but I upgraded to last version because of new switch WS-EUK01 which was not supported.

**Comment by Koenkk** [comment]
What coordinator/firmware are you using?

**Comment by clmun** [comment]
I have slaesh’s CC2652RB stick. Don't know which firmware.
I don't know how can I check this... (noob alert!)

**Comment by Koenkk** [comment]
Are you using the latest firmware? You can find it here: https://www.zigbee2mqtt.io/guide/adapters/#recommended . After updating to the latest firmware you might have to repair (only) the WS-EUK01 to get it working.

**Comment by clmun** [comment]
I manage to update to last firmware. (CC2652RB_coordinator_20220219.hex)
Then I paired again the switch, but still the same. On action i always get NULL when I togle in software and if click the button i see this: "empty string"
![image](https://user-images.githubusercontent.com/16850783/193443661-d13b8976-825b-45ec-947e-3ae36d9c33aa.png)

same looking at xiaomi switch. Always show Null no mater if i single press or any action i make:
![image](https://user-images.githubusercontent.com/16850783/193443818-aa5fd184-a016-4e61-bdd0-2547a39110f6.png)

**Comment by Koenkk** [comment]
You should see the action very shortly if you have the HA integration enabled (take a look at the z2m logging to see the actual action).

https://www.zigbee2mqtt.io/guide/faq/#why-is-the-action-property-always-empty

**Comment by clmun** [comment]
Thank you for your help.
It worked in the end. Action is visible only for couple of ms. I only seen it in logging (z2m).
Then I checked in logs in HA, but action is not shown at all. 
Nevertheless I tried an automation and I could trigger 'single' and 'double' action for device ... in the end it worked.

So thank you. I think this can be closed now.
