### ISSUE TITLE
Add Tuya Device

### ISSUE THREAD

**Issue by cabanossi** [Koenkk/zigbee-herdsman-converters#4739]
Hello!

I have a new Tuya Zigbee Smart Switch with a new ModelID. Can you add 
"{modelID: 'TS000F', manufacturerName: '_TZ3000_mx3vgyea'},"
on Line 227 in the tuya.js on the device folder?

With the setting, the device works perfectly!

Thanks a lot!

**Comment by danieledwardgeorgehitchcock** [comment]
Hi,

There is a method in the main Z2M repo for raising new device requests however;

line 227 doesn't seem to relate to the device you are requesting.

If you could add the database.db entry and a link to the device on AliExpress / other, I can look into helping you out.

In the meantime, I will create a draft PR as a placeholder

**Comment by danieledwardgeorgehitchcock** [comment]
I have just checked, and the fingerprint already exists for this device so, I have removed my PR
