### ISSUE TITLE
Support for new Tuya device (switch with power monitoring)

### ISSUE THREAD

**Issue by mczerski** [Koenkk/zigbee-herdsman-converters#4753]
Device presents itself as model: TS0001 producer: _TZ3000_qnejhcsu.

With current version of zigbee2mqtt 1.28 device is recognized as switch without power monitoring (TS0001). After adding entry:
```
{modelID: 'TS0001', manufacturerName: '_TZ3000_qnejhcsu'}
```
here:
https://github.com/Koenkk/zigbee-herdsman-converters/blob/09b2176dbaec7649488d877922db0b3be429caa5/devices/tuya.js#L1655

the device is recognized as TS0001_power and power monitoring works.
![Zrzut ekranu z 2022-10-07 17-46-23](https://user-images.githubusercontent.com/2772080/194594796-92420289-21cf-4402-aa73-958c3b17acd9.png)
Below is the picture of the device:
![IMG_20221007_174729](https://user-images.githubusercontent.com/2772080/194595198-3ed9fc33-3286-4add-8614-b2770838ba3c.jpg)

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
