### ISSUE TITLE
TS0006 listed in supported devices, converter found (?), z2m says unsupported

### ISSUE THREAD

**Issue by rafareusch** [Koenkk/zigbee-herdsman-converters#4769]
Hey. Bought an Avatto Tuya 6 gang with neutral wire TS0006, z2m reports unsupported
link: https://pt.aliexpress.com/item/1005004766292754.html?spm=a2g0o.order_list.0.0.6b32caa4CVTy77&gatewayAdapt=glo2bra

Docs says its supported as vendor tuya, products seems to be avatto white-labeled?
supported-devices-docs: https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/devices/TS0601_switch.md

Info 2022-10-11 00:50:02 Successfully interviewed '0xa4c138a1a987ea58', device has successfully been paired
Warning 2022-10-11 00:50:02Device '0xa4c138a1a987ea58' with Zigbee model 'TS0006' and manufacturer name '_TZ3000_jyupj3fw' is NOT supported, please follow [...]

Am I missing something? Or this is a brand new device? 

ps: I am also receiving a TS0001, maybe the same will occur?

Thanks!!

**Comment by danieledwardgeorgehitchcock** [comment]
This would be a new device.

TuYa really messes with the Zigbee standard - they create generic modules and dev kits which all report the same models for similar device types, but with different manufacturer ID's.

The device that you have purchased will have 6 endpoints, whereas the documentation that you linked to is for a device with up to 4 therefore demonstrating the issue.

It should be pretty trivial to use the device that you have linked in the documentation as a base for creating a converter for your device...

**Comment by rafaeltoth** [comment]
> This would be a new device.
> 
> 
> 
> TuYa really messes with the Zigbee standard - they create generic modules and dev kits which all report the same models for similar device types, but with different manufacturer ID's.
> 
> 
> 
> The device that you have purchased will have 6 endpoints, whereas the documentation that you linked to is for a device with up to 4 therefore demonstrating the issue.
> 
> 
> 
> It should be pretty trivial to use the device that you have linked in the documentation as a base for creating a converter for your device...

My bad... The correct doc link is:
https://www.zigbee2mqtt.io/devices/TS0006.html

I tried messing with the converter with no luck, maybe someone will make it available soon

**Comment by danieledwardgeorgehitchcock** [comment]
I'll see if I can sling something together in an external converter for you.

Can you upload your database.db entry here for the device?

**Comment by rafaeltoth** [comment]
Sure, can you instruct me how to get the db file?

**Comment by danieledwardgeorgehitchcock** [comment]
It should be in the config directory of wherever you installed Z2M - I'm just in the process of putting an external converter together for you to try - hopefully it's a whitelabel as you suggest

**Comment by danieledwardgeorgehitchcock** [comment]
Try this [external converter](https://gist.github.com/danieledwardgeorgehitchcock/a0cbe5c0ba3ff0c9e4436adce4a48217)

**Comment by rafareusch** [comment]
Daniel, I'm happy to report it works!
So it's really a white label... great news....

Thanks for the code, when the 1 switch version arrives, I'll probably have to use a similar converter too.

Maybe you can contribute to the repo with the support of this device

**Comment by rafareusch** [comment]
Just saw the PR, Daniel, 
Thanks very much!

**Comment by rafareusch** [comment]
I just wanted to give some feedback. Seems that there's some kind of problem with this switch/integration
- I have more than 6 of this switches in different HA instances.

If you turn on and off the lights of this switch via z2m, after some time (3-5 uses) the switch stop responding via Z2M but keep responding physically ( switch.turn_off / on -> Nothing happens ). BUT after 4-5 seconds the switch catches up to all past commands and changes the switch state accordingly. (even if means flickering the light on and off, exacly as commanded)
 The issue is exacerbated if two or more switches are in the same HA Switch Group. If you turn on the group, only some switches will turn on, then after 4-5 seconds the rest will.

I use this switches in Tuya instances just fine.

How can I open a discussion about this?

Thanks
