### ISSUE TITLE
[Lixee device] Does not handle 0 values

### ISSUE THREAD

**Issue by arenoux** [Koenkk/zigbee-herdsman-converters#4779]
Issue tracked here :
- https://github.com/fairecasoimeme/Zlinky_TIC/issues/62
- https://github.com/Koenkk/zigbee2mqtt/issues/13991

0 values are not handled because of bad check in the code.
I will open a PR soon to suggest a fix :)

**Comment by Koenkk** [comment]
Merged https://github.com/Koenkk/zigbee-herdsman-converters/pull/4780 so this should be fixed now.
