### ISSUE TITLE
[REQUEST] Inovelli Zigbee OTA provider for Inovelli branded Zigbee devices

### ISSUE THREAD

**Issue by Hedda** [Koenkk/zigbee-herdsman-converters#4799]
@InovelliUSA Inovelli has an official Zigbee OTA provider server that is online from you as a first-party and also publicly available for third-party use, so requesting that you please also consider convincing Inovelli management to have their engineers also work on an Inovelli Zigbee OTA provider for providing downloading code of firmware update images for Inovelli branded Zigbee devices to this zigbee-herdsman-converters project which is used by Zigbee2MQTT (and IoBroker).

https://files.inovelli.com/firmware/firmware.json

https://files.inovelli.com/firmware

https://www.zigbee2mqtt.io/guide/usage/ota_updates.html

https://github.com/Koenkk/zigbee-herdsman-converters/tree/master/lib/ota

PS: For reference; @InovelliUSA has ex. contributed OTA provider code to zigpy library used by ZHA integration in Home Assistant:

https://github.com/zigpy/zigpy/pull/980

https://github.com/zigpy/zigpy/blob/dev/zigpy/ota/provider.py#L622-L701

**Comment by nathanfiscus** [comment]
https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/lib/ota/inovelli.js

**Comment by Hedda** [comment]
Ah, missed it, closing
