### ISSUE TITLE
Add supported TuYa Smart 1 gang switch with power monitiring TS0001 ( _TZ3000_x3ewpzyr)

### ISSUE THREAD

**Issue by MityaDVG** [Koenkk/zigbee-herdsman-converters#4843]
Add supported TuYa Smart 1 gang switch with power monitiring TS0001 ( _TZ3000_x3ewpzyr)

**Comment by Koenkk** [comment]
Done!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by mrmaximas** [comment]
@Koenkk Hello! 
I use these device `_TZ3000_x3ewpzyr` aka https://www.zigbee2mqtt.io/devices/XSH01A.html#tuya-xsh01a. Today I accidentally discovered that, for some unknown reason, the coordinator (SLZB-06P7 / 20250321) requests reports from device once a minute, even though the device itself sends them independently at intervals specified in the Reporting Tab. The coordinator does not request anything from other devices with power measurement (like IKEA E2206 for example). I attempted to reconfigure it, but it did not change the coordinator. 
What could this be? Could it be that pulling is built into the converter? If so, for what purpose?
Thanks and have a nice weekend!

<img width="1621" height="1197" alt="Image" src="https://github.com/user-attachments/assets/d21c0ec1-479d-4867-8e69-74dfd3a7147a" />

<img width="1621" height="1192" alt="Image" src="https://github.com/user-attachments/assets/a76fa218-b017-4bdc-8327-c1259e4110b9" />

<img width="1623" height="1191" alt="Image" src="https://github.com/user-attachments/assets/c257addc-494e-4083-b388-ca355375df44" />

<img width="1627" height="1199" alt="Image" src="https://github.com/user-attachments/assets/68ffbbbd-2434-48dc-9566-1cca54892495" />

**Comment by Koenkk** [comment]
Yes; https://github.com/Koenkk/zigbee-herdsman-converters/blob/4361fb3b4022d615326a569797cb610bce3b8d01/src/devices/tuya.ts#L5048, otherwise it's not working  (https://github.com/Koenkk/zigbee2mqtt/issues/23155) but likely you device is a little bit different.
Let's continue there.
