### ISSUE TITLE
Wrong values for Hystererse

### ISSUE THREAD

**Issue by SKJOAN** [Koenkk/zigbee-herdsman-converters#4864]
https://github.com/Koenkk/zigbee-herdsman-converters/blob/141d1b77e4709f53a7e49dc684a594da783d715a/devices/namron.js#L613

The values for Hysterersis  is wrong. Default should be 0.5. don't know about range but definitely less the 5-50. Maybe 0.1 to 5

ithDescription('Hysterersis setting, range is 5-50, unit is 0.1oC,  Default: 5.'),

From manual:
![image](https://user-images.githubusercontent.com/73289571/199240129-a914e809-8a87-4c40-b257-b9547316a8ac.png)

**Comment by SKJOAN** [comment]
I see that the Touch Thermostat has this config, shuld probobly be the same?:
 .withDescription('Hysteresis setting, between 0.5 and 2 in 0.1 °C.  Default: 0.5.'),

**Comment by Koenkk** [comment]
can you create a PR to fix this?

**Comment by SKJOAN** [comment]
Sorry im not used to working in github. I forked the reposetory and changed the data for Hysterersis and created a Pull Request? Is this then the correct way?

**Comment by Koenkk** [comment]
Yes, perfect, thanks!
