### ISSUE TITLE
clicks for WXKG01LM

### ISSUE THREAD

**Issue by arteck** [Koenkk/zigbee-herdsman-converters#487]
zigbeeModel: ['lumi.sensor_switch'],
        model: 'WXKG01LM',
        vendor: 'Xiaomi',
        description: 'MiJia wireless switch',
        supports: 'single, double, triple, quadruple, many, long, long_release click',
        fromZigbee: [fz.xiaomi_battery_3v, fz.WXKG01LM_click, fz.ignore_onoff_change, fz.ignore_basic_change],
toZigbee: [],

where are other click states ??

**Comment by Koenkk** [comment]
All are here: https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/converters/fromZigbee.js#L406
