### ISSUE TITLE
Add exposes for various Legrand devices led_in_dark/led_if_on don't work

### ISSUE THREAD

**Issue by novisys** [Koenkk/zigbee-herdsman-converters#4871]
Hi,
i think this two new exposed options don't work with my devices :
067775/741811 : led_in_dark
The PR : Fixes for Legrand 067775/741811 #4583
the option from this PR added to Z2M dashboard but don't work
Any advice ?

**Comment by Koenkk** [comment]
@EXP-Carthage could you check this/

**Comment by EXP-Carthage** [comment]
@Koenkk I just tested on 4 of my outlets and it works very well

**Comment by novisys** [comment]
on wich FW version are your outlet ?

**Comment by EXP-Carthage** [comment]
I have the firmwares in version 016 and 023.
However, I see that you have Dooxie devices. Personally, I use Céliane devices and the tests were done on these devices and I could not test them on the Dooxie.

**Comment by novisys** [comment]
I have some question:
How did you update your firmware ? (personnaly i used Z2M to update the firmware)
Can you tell me how do you did the test to have it working ?
*I thinked Celiane and Dooxie product have the same fonctionalities and just difere in the design/material of conception.

**Comment by EXP-Carthage** [comment]
The firmwares present on my devices are the original firmwares.
Concerning the tests, I made them via the Z2M interface

**Comment by novisys** [comment]
> 

i mean how you did to get this parameter "led_in_dark" and other that has been added to Z2M after?
if you help me, i can try to find the parameter for mine, maybe it's difere fron celiane !?
(also, i will try to buy an LEGRAND coordinator to update my products, maybe the problem come from the update.)

**Comment by EXP-Carthage** [comment]
I had recovered the clusters when I had my installation under Deconz

**Comment by novisys** [comment]
> I had recovered the clusters when I had my installation under Deconz

Ok, i will try to connect it to Deconz and check the clusters.

**Comment by novisys** [comment]
it's ok !
my appologies for inconveniance, but the error come from the Joinning Network Open alltime that make the Legrand devices have Green light all-time and the others led options don't work 
Issue closed !
