### ISSUE TITLE
TS0601_thermostat_1: cannot set weekly schedule (No converter available for "undefined")

### ISSUE THREAD

**Issue by matthieudrenou** [Koenkk/zigbee-herdsman-converters#4902]
Hello,
Trying to set a weekly schedule for my device... Can't get it working:

Posting a message with payload :
`{"undefined": {"monday_schedule": "6h:0m 25°C, 12h:0m 15°C, 18h:0m 22°C, 22h:0m 15°C ", "tuesday_schedule": "6h:0m 20°C, 12h:0m 15°C, 18h:0m 22°C, 22h:0m 15°C ", "wednesday_schedule": "6h:0m 20°C, 12h:0m 15°C, 18h:0m 22°C, 22h:0m 15°C ", "thursday_schedule": "6h:0m 20°C, 12h:0m 15°C, 18h:0m 22°C, 22h:0m 15°C ", "friday_schedule": "6h:0m 20°C, 12h:0m 15°C, 18h:0m 22°C, 22h:0m 15°C ", "saturday_schedule": "6h:0m 20°C, 12h:0m 15°C, 18h:0m 22°C, 22h:0m 15°C ", "sunday_schedule": "6h:0m 20°C, 12h:0m 15°C, 18h:0m 22°C, 22h:0m 15°C "}}`
as mentioned in [doc](https://www.zigbee2mqtt.io/devices/TS0601_thermostat_1.html#tuya-ts0601_thermostat_1) 

I get an error message: `No converter available for "undefined"
`
Looking at [tuya.js](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/tuya.js) I wonder whether a `tz.tuya_thermostat_weekly_schedule` clause is missing in the `toZigbee `section for the model `model: 'TS0601_thermostat_1'` (just guessing?)

Thanks in advance

**Comment by chrisssssy** [comment]
I exactly the same problem here. Any fixes to this?
