### ISSUE TITLE
[REQUEST] ThirdReality (3reality) OTA provider for Third Reality branded Zigbee devices

### ISSUE THREAD

**Issue by Hedda** [Koenkk/zigbee-herdsman-converters#4928]
ThirdReality (3reality) Zigbee OTA firmware images are made publicly available by Third Reality, Inc. (first-party) at the following URL:

https://tr-zha.s3.amazonaws.com/firmware.json

Official website and Facebook group for reference:

https://www.3reality.com/

https://www.facebook.com/ThirdReality.offical/

Z2M devs might want to contact @hwzolin from Third Reality, Inc. for sample hardware if they are interested in [Zigbee2MQTT](https://www.zigbee2mqtt.io/) support. 

FYI; code for Third Reality (3reality) OTA provider support and custom image format parser were recently added to zigpy library:

https://github.com/zigpy/zigpy/pull/1096

https://github.com/zigpy/zigpy/pull/1090

https://github.com/zigpy/zigpy/pull/1089

BTW, also read that [Third Reality (3reality)](https://www.3reality.com) joined "Works with Home Assistant"/"Works via Zigbee with Home Assistant" partner program.

https://www.home-assistant.io/blog/2022/10/13/third-reality-partner/

https://www.home-assistant.io/blog/2022/07/12/partner-program/

@hwzolin please see the backstory below for reference:

As [Third Reality, Inc.](https://www.3reality.com) as a company probably do not know yet, [zigbee-herdsman](https://github.com/Koenkk/zigbee-herdsman) is the Zigbee framework used by [Zigbee2MQTT](https://www.zigbee2mqtt.io/) and [IoBroker](https://github.com/ioBroker/ioBroker.zigbee) as a dependency in their open source Zigbee gateway/hub implementations.

Providing a "3reality Zigbee OTA provider" and matching downloader code support for Zigbee devices from [ThirdReality (3reality)](https://www.3reality.com/) in this [zigbee-herdsman-converters](https://github.com/Koenkk/zigbee-herdsman-converters) library could potentially enable much easier OTA firmware upgrades for end-users of those in the future, and currently Zigbee2MQTT is probably the worlds most popular open source  Zigbee gateway/hub implementation among DIY home automation enthusiasts.

https://github.com/Koenkk/zigbee-herdsman-converters/tree/master/lib/ota

That way it will be a single trusted and official primary source of official Zigbee OTA files released by Third Reality, and that OTA provider source repository with your Zigbee OTA files could not only be used by zigbee-herdsman / Zigbee2MQTT / IoBroker as it could also be reused by other Zigbee implementations independently (both other open-source implementations as well as closed source and proprietary implementations).

Maybe also consider copying concept of `index.json` with metadata on all files like Koenkk repository has to make scripting easier:

https://github.com/Koenkk/zigbee-OTA/blob/master/index.json

PS: [Zigbee2MQTT](https://www.zigbee2mqtt.io/) allows users to use it locally as described here:

https://github.com/Koenkk/zigbee2mqtt.io/blob/develop/docs/guide/usage/ota_updates.md#local-ota-index-and-firmware-files

And of course `README.md` file which among other things could contain some basic information on how to update those:

https://github.com/Koenkk/zigbee-OTA/blob/master/README.md

Perhaps also as keeping some kind of `CHANGELOG.md` with changelog release history for each device firmware version:

https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_3.x.0/CHANGELOG.md

**Comment by Hedda** [comment]
> FYI; code for Third Reality (3reality) OTA provider support and custom image format parser were recently added to zigpy library:
> 
> [zigpy/zigpy#1096](https://github.com/zigpy/zigpy/pull/1096)
> 
> [zigpy/zigpy#1090](https://github.com/zigpy/zigpy/pull/1090)
> 
> [zigpy/zigpy#1089](https://github.com/zigpy/zigpy/pull/1089)

Note comments on current issues in Third Reality OTA image file format:

> 



> The OTA images from https://tr-zha.s3.amazonaws.com/firmware.json are not in any known OTA format and contain a 152 byte prefix. This PR identifies them and strips the header, allowing zigpy to utilize the OTA images.
> 
> All OTA images have the same manufacturer ID (4659/0x1233) but many images are indistinguishable from one another despite targeting seemingly different hardware.
> 
> ```python
> # These three images are indistinguishable from one another, since they contain the same image type and file version
> 3RSS007Z_0_010_000_20190218_054240.bin    (image_type=20841, file_version=10, header_string='3RSS007Z-UNENCRYPTED-80205JN5169')
> 3RSS007Z_2_010_000_20200511_085155.hub    (image_type=20841, file_version=10, header_string='3RSS007Z-UNENCRYPTED-80205JN5169')
> 3RSS008Z_3_010_000_20190801_080629.hub    (image_type=20841, file_version=10, header_string='3RSS008Z-JN5169-HW03-UNENCRYPTED')
> 
> # Same thing
> 3RSL011Z_1_009_000_20190416_124702.bin    (image_type=268,   file_version=9,  header_string='3RSL011Z-JN5169-2PWM-UNENCRYPTED')
> 3RSL012Z_1_009_000_20190416_124714.bin    (image_type=268,   file_version=9,  header_string='3RSL011Z-JN5169-2PWM-UNENCRYPTED')
> 
> 3RSC015Z_1_006_000_20190910_083414.hub    (image_type=3,     file_version=6,  header_string='3RSC015Z-JN5189-HW01-UNENCRYPTED')
> 
> 3RMS16BZ_0_031_20220817_022402.bin        (image_type=54177, file_version=49, header_string='Telink OTA Sample Usage')
> 3RDS17BZ_0_031_20220817_022334.bin        (image_type=54178, file_version=49, header_string='Telink OTA Sample Usage')
> 3RWS18BZ_0_031_20220817_022437.bin        (image_type=54179, file_version=49, header_string='Telink OTA Sample Usage')
> 3RSS009Z_1_012_20220722_012055.bin        (image_type=54181, file_version=18, header_string='Telink OTA Sample Usage')
> 3RSP019B_012_20210720_074020.bin          (image_type=54182, file_version=18, header_string='Telink OTA Sample Usage')
> 3RSP019BZ_1_019_20210823_104706.bin       (image_type=54182, file_version=25, header_string='Telink OTA Sample Usage')
> 3RSB015BZ_056_20220816_100333.bin         (image_type=54183, file_version=86, header_string='Telink OTA Sample Usage')
> 3RSB22BZ_021_20221009_085224.bin          (image_type=54184, file_version=33, header_string='Telink OTA Sample Usage')
> 3RTHS24BZ_020_20220901_032612.bin         (image_type=54185, file_version=32, header_string='Telink OTA Sample Usage')
> ```
> 
> @hwzolin Are these groups of images with the same `image_type` and `file_version` all cross-compatible?

**Comment by hwzolin** [comment]
> 
The OTA images from https://tr-zha.s3.amazonaws.com/firmware.json have been modified, please check it out, thank you.

**Comment by hwzolin** [comment]
> > FYI; code for Third Reality (3reality) OTA provider support and custom image format parser were recently added to zigpy library:
> > [zigpy/zigpy#1096](https://github.com/zigpy/zigpy/pull/1096)
> > [zigpy/zigpy#1090](https://github.com/zigpy/zigpy/pull/1090)
> > [zigpy/zigpy#1089](https://github.com/zigpy/zigpy/pull/1089)
> 
> Note comments on current issues in Third Reality OTA image file format:
> 
> > 
> 
> > The OTA images from https://tr-zha.s3.amazonaws.com/firmware.json are not in any known OTA format and contain a 152 byte prefix. This PR identifies them and strips the header, allowing zigpy to utilize the OTA images.
> > All OTA images have the same manufacturer ID (4659/0x1233) but many images are indistinguishable from one another despite targeting seemingly different hardware.
> > ```python
> > # These three images are indistinguishable from one another, since they contain the same image type and file version
> > 3RSS007Z_0_010_000_20190218_054240.bin    (image_type=20841, file_version=10, header_string='3RSS007Z-UNENCRYPTED-80205JN5169')
> > 3RSS007Z_2_010_000_20200511_085155.hub    (image_type=20841, file_version=10, header_string='3RSS007Z-UNENCRYPTED-80205JN5169')
> > 3RSS008Z_3_010_000_20190801_080629.hub    (image_type=20841, file_version=10, header_string='3RSS008Z-JN5169-HW03-UNENCRYPTED')
> > 
> > # Same thing
> > 3RSL011Z_1_009_000_20190416_124702.bin    (image_type=268,   file_version=9,  header_string='3RSL011Z-JN5169-2PWM-UNENCRYPTED')
> > 3RSL012Z_1_009_000_20190416_124714.bin    (image_type=268,   file_version=9,  header_string='3RSL011Z-JN5169-2PWM-UNENCRYPTED')
> > 
> > 3RSC015Z_1_006_000_20190910_083414.hub    (image_type=3,     file_version=6,  header_string='3RSC015Z-JN5189-HW01-UNENCRYPTED')
> > 
> > 3RMS16BZ_0_031_20220817_022402.bin        (image_type=54177, file_version=49, header_string='Telink OTA Sample Usage')
> > 3RDS17BZ_0_031_20220817_022334.bin        (image_type=54178, file_version=49, header_string='Telink OTA Sample Usage')
> > 3RWS18BZ_0_031_20220817_022437.bin        (image_type=54179, file_version=49, header_string='Telink OTA Sample Usage')
> > 3RSS009Z_1_012_20220722_012055.bin        (image_type=54181, file_version=18, header_string='Telink OTA Sample Usage')
> > 3RSP019B_012_20210720_074020.bin          (image_type=54182, file_version=18, header_string='Telink OTA Sample Usage')
> > 3RSP019BZ_1_019_20210823_104706.bin       (image_type=54182, file_version=25, header_string='Telink OTA Sample Usage')
> > 3RSB015BZ_056_20220816_100333.bin         (image_type=54183, file_version=86, header_string='Telink OTA Sample Usage')
> > 3RSB22BZ_021_20221009_085224.bin          (image_type=54184, file_version=33, header_string='Telink OTA Sample Usage')
> > 3RTHS24BZ_020_20220901_032612.bin         (image_type=54185, file_version=32, header_string='Telink OTA Sample Usage')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @hwzolin Are these groups of images with the same `image_type` and `file_version` all cross-compatible?

The OTA images from https://tr-zha.s3.amazonaws.com/firmware.json have been modified, please check it out, thank you.

**Comment by Hedda** [comment]
> Hello, I noticed that some of the devices (such as water leak sensor) have DEV in OTA file name in the json descriptor file - such as TRTL_WaterLeak_DEV_V31_v1.00.31.ota while others have PROD as part of name. Are these DEV versions safe/proper to use when updating firmware on devices?

IMHO, preferably PROD and DEV should have separate repositories or at least separate JSON index files with different URLs. See the example IKEA which at least used to have separate download URLs for Test/Beta versions of firmware images. See examples: 

IKEA download URL for their Production versions of OTOU firmware images:

http://fw.ota.homesmart.ikea.net/feed/version_info.json

IKEA download URL for their Test/Beta versions of OTOU firmware images:

http://fw.test.ota.homesmart.ikea.net/feed/version_info.json

Also, see IKEA's release changelogs for reference (which is not so nice but at least they have a public changelog for firmware):

https://ww8.ikea.com/ikeahomesmart/releasenotes/releasenotes.html

**Comment by Hedda** [comment]
> In support, thanks.

@hwzolin Any updates on your ThirdReality (3reality) OTA provider for zigbee-herdsman (for use in Zigbee2MQTT and IoBroker)?

**Comment by Hedda** [comment]
@hwzolin Any updates on your ThirdReality (3reality) OTA provider for zigbee-herdsman (for use in Zigbee2MQTT and IoBroker)?

**Comment by ahahamyan** [comment]
I have successfully used (updated all my devices to latest firmware) the OTA features for the ThirdReality Water Leak Sensors via Zigbee2MQTT - details are at https://github.com/Koenkk/zigbee-OTA
