### ISSUE TITLE
TS0601 _TZE204_ztc6ggyl defined but shows as not supported

### ISSUE THREAD

**Issue by artlov** [Koenkk/zigbee-herdsman-converters#4940]
Despite the fact that the fingerprint is present in the tuja.js file, this device on add-on is considered as not supported:
`Received message from unsupported device with Zigbee model 'TS0601' and manufacturer name '_TZE204_ztc6ggyl'`
Works with a separate external converter (without icon, though).

**Comment by danieledwardgeorgehitchcock** [comment]
What version of Z2M are you running?

As this was only added to the codebase 12 days ago, you will have to [switch to the Dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) to use it or wait until the beginning of next month for it to be merged into main.

**Comment by vaderag** [comment]
Same issue with this device - listed as supported here https://www.zigbee2mqtt.io/devices/TS0601_smart_human_presense_sensor.html but I'm getting a bunch of errors

**Comment by danieledwardgeorgehitchcock** [comment]
> Same issue with this device - listed as supported here https://www.zigbee2mqtt.io/devices/TS0601_smart_human_presense_sensor.html but I'm getting a bunch of errors

Is it the same manufacturer and model ID as above? Which Z2M branch are you using?

**Comment by vaderag** [comment]
Yup - same
`Received message from unsupported device with Zigbee model 'TS0601' and manufacturer name '_TZE204_ztc6ggyl'`

Zigbee2MQTT version [1.28.2](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.28.2)

**Comment by danieledwardgeorgehitchcock** [comment]
You'll have to do the same as advised above then

**Comment by vaderag** [comment]
Okay. Guess I'll wait then...

OOI, is it normal for devices to be added to the supported list before they're actually supported?
I ordered this a number of weeks ago from Ali and it was listed as supported then (hence ordering), but if this is normal the I'd like to know how I can be more careful in future!

**Comment by artlov** [comment]
Ah I see - in release version this version not yet added. I don't want to switch to the dev branch and temporarily I'm use converter instead.

**Comment by danieledwardgeorgehitchcock** [comment]
It depends, there's two processes for the supported devices page being updated:

Auto (CI/CD): the support page is updated and built on a release

Manual: a contributor can create a PR in the zigbee2mqtt.io repo, and when merged, the support page is updated and built

My guess (without looking into it), is that this was a manual push which is why it is shown as supported prior to being merged into a release

**Comment by artlov** [comment]
> is it normal for devices to be added to the supported list before they're actually supported?
Older verion is supported (_TZE200). Newer versions have different chip inside and thus it detecteda as _TZE204. This not in the supported list yet.

**Comment by artlov** [comment]
Now it's OK with last release. Closing.
