### ISSUE TITLE
Clarrification: How do you force a full state dump from a Tuya device (Lidl 368308_2010)

### ISSUE THREAD

**Issue by nathan-gs** [Koenkk/zigbee-herdsman-converters#4980]
I'm working on improving the [Lidl/Silvercrest 368308_2010](https://www.zigbee2mqtt.io/devices/368308_2010.html#lidl-368308_2010) converters.

One issue I'm facing is that the state of the device is only sent property by property and that some properties like battery or the schedule are not updated very frequently. 

I would like to poll the device (every 30m) for the full state and was wondering if there's a Tuya command available?

My work so far:
https://github.com/nathan-gs/nix-conf/blob/lidl-36308/smarthome/lidl-368308_2010-converter.js#L389-L412

Ps. I already got battery state working (voltage calc) and fixed the UI issues for scheduling by removing the expose.compose. A PR will follow later.

**Comment by Koenkk** [comment]
AFAIK this is not possible (TuYa api doesn't support reading anything). 

When refactoring, take into account the new TuYa format, you can find an example for a TuYa thermostat here: https://github.com/Koenkk/zigbee-herdsman-converters/blob/69bbcbec35ea99a4744911ffcc57c4614d98c289/devices/tuya.js#L2217

**Comment by MattWestb** [comment]
Some tuya TRVs need being online for updating there status to the host system but i dont know the command used.
tuya have one function implanted here https://github.com/Koenkk/zigbee-herdsman/commit/22c41a81f4f6ef49538f2ea2cae27bdbe69a6b0b that perhaps can doing it ?
