### ISSUE TITLE
How to: Is there a way to have a numeric exposed attributes but with an option to disable the attribute

### ISSUE THREAD

**Issue by faucherc** [Koenkk/zigbee-herdsman-converters#5007]
For a device that I'm trying to enhance the converter, I have a numeric attribute with a range between 5 to 36 with a step of 1.  But this attribute can also be disabled to tell the device to ignore the param.  To disable the attribute, I need to send the value -32768 to the device.

How can I code the exposes to represent this behavior?  

I understand that I will need to adjust the fromZigbee and toZigbee methods to support this behavior, but for now, I can't figure out how to do the exposes.

**Comment by Danit2** [comment]
Yes. 
You can do it like in the level_config exposes: 
'''
.withFeature(new Numeric('current_level_startup', access.ALL)
                .withValueMin(1).withValueMax(254)
                .withPreset('minimum', 0, 'Use minimum permitted value')
                .withPreset('previous', 255, 'Use previous value')
'''

**Comment by faucherc** [comment]
Thank you very much! That's exactly what i'm searching!
