### ISSUE TITLE
TS0215A SOS Button not working

### ISSUE THREAD

**Issue by rt400** [Koenkk/zigbee-herdsman-converters#5014]
Hi,
I have SOS button that recognize as TS0215A and _TZ3000_pkfazisv.
i add the external convert and he recognize it but i have not battery info and no click info.
<img width="488" alt="image" src="https://user-images.githubusercontent.com/38878996/203704934-b862cb80-2341-4655-b09b-7f077a165d16.png">
and this : 
<img width="291" alt="image" src="https://user-images.githubusercontent.com/38878996/203705004-d42bf792-a3e1-41cd-807a-278e0fd42a8b.png">

any idea how to recognize it well ?

**Comment by rt400** [comment]
@Koenkk can you help with this? i really need the battery info...

**Comment by rt400** [comment]
@Koenkk OK i just start to play with the config and now can get the Battery info.
Plz can you add this to the juya.js convert ?
`module.exports = [
    {
        fingerprint: [{modelID: 'TS0215A', manufacturerName: '_TZ3000_4fsgukof'},
            {modelID: 'TS0215A', manufacturerName: '_TZ3000_wr2ucaj9'},
            {modelID: 'TS0215A', manufacturerName: '_TZ3000_zsh6uat3'},
            {modelID: 'TS0215A', manufacturerName: '_TZ3000_tj4pwzzm'},
            {modelID: 'TS0215A', manufacturerName: '_TZ3000_pkfazisv'}],
        model: 'TS0215A_sos',
        vendor: 'TuYa',
        description: 'SOS Panic Button',
        fromZigbee: [fz.command_emergency, fz.battery],
        exposes: [e.battery(), e.battery_voltage(), e.action(['emergency'])],
        toZigbee: [],
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genPowerCfg', 'genTime', 'genBasic', 'ssIasAce', 'ssIasZone']);
            await endpoint.read('genPowerCfg', ['batteryVoltage', 'batteryPercentageRemaining']);
            await reporting.batteryPercentageRemaining(endpoint);
            await reporting.batteryVoltage(endpoint);
        },
    },
];`
My model is _TZ3000_pkfazisv so its not add yet...
many thanks for your work...

**Comment by Koenkk** [comment]
Done!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by rt400** [comment]
@Koenkk Do you why the battery icon is in black ? this should be in green like other battery sensor..
<img width="773" alt="image" src="https://user-images.githubusercontent.com/38878996/204205639-5d6cfc6f-d4c0-42f1-9fc2-f64090a723fb.png">

**Comment by Koenkk** [comment]
@nurikk can you explain this?

**Comment by nurikk** [comment]
> @Koenkk Do you why the battery icon is in black ? this should be in green like other battery sensor..
> <img alt="image" width="773" src="https://user-images.githubusercontent.com/38878996/204205639-5d6cfc6f-d4c0-42f1-9fc2-f64090a723fb.png">

Green shows if device exposes battery_ok or something like that

**Comment by nurikk** [comment]
> @nurikk I guess you are talking about `battery_low` == `false`?

Yes, something like that. But it more complex check. Need to verify exposes and device state

**Comment by rt400** [comment]
@nurikk So need to add to expose : e.battery_low() ?

**Comment by rt400** [comment]
<img width="320" alt="image" src="https://user-images.githubusercontent.com/38878996/204492182-73002d0b-1b5e-49e4-9a37-1e6ee4a6a6cc.png">
 with e.battery_low() i get green in battery icon
