### ISSUE TITLE
Support for _TZ3000_0zfrhq4i smart plug

### ISSUE THREAD

**Issue by passy05** [Koenkk/zigbee-herdsman-converters#5052]
I have an energy monitor smart plug detected as unsupported: Zigbee model 'TS011F' and manufacturer name '_TZ3000_0zfrhq4i'.
Is there an easy way to check if it is compatible with the devices found in the Tuya "const TS011Fplugs" list?

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by passy05** [comment]
Thank you very much @Koenkk for adding this device so quickly!
Everything seems to work but the energy which reports NULL (see screenshot).
Do I need to reset it to 0 (what is the payload for the reset)?
I don't have any Tuya gateway, so I don't how I can troubleshoot this issue further.
![_TZ3000_0zfrhq4i](https://user-images.githubusercontent.com/36485688/205315460-533b6d4e-06c6-41cd-ac66-7a4f4aec6788.png)

**Comment by Koenkk** [comment]
Can you provide the data/database.db entry of this device?

**Comment by passy05** [comment]
@Koenkk here it is:

{"id":66,"type":"Router","ieeeAddr":"0xa4c1386167fbd460","nwkAddr":51726,"manufId":4417,"manufName":"_TZ3000_0zfrhq4i","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,3,4,5,6,10,57344,1794,2820,4096,6280],"outClusterList":[25],"clusters":{"genOnOff":{"attributes":{"32768":0,"tuyaBacklightMode":1,"onOff":1,"moesStartUpOnOff":2,"onTime":0,"offWaitTime":0}},"haElectricalMeasurement":{"attributes":{"rmsVoltage":247,"rmsCurrent":152,"activePower":7}},"genBasic":{"attributes":{"modelId":"TS011F","manufacturerName":"_TZ3000_0zfrhq4i","powerSource":1,"zclVersion":3,"appVersion":66,"stackVersion":2,"hwVersion":0,"swBuildId":"0122052017"}},"seMetering":{"attributes":{"currentSummDelivered":[0,4]}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b00216005c2","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00124b00216005c2","endpointID":1},{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x00124b00216005c2","endpointID":1}],"configuredReportings":[{"cluster":2820,"attrId":1285,"minRepIntval":5,"maxRepIntval":3600,"repChange":5},{"cluster":2820,"attrId":1288,"minRepIntval":5,"maxRepIntval":3600,"repChange":50}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":66,"stackVersion":2,"hwVersion":0,"swBuildId":"0122052017","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1669998714951,"defaultSendRequestWhen":"immediate"}

**Comment by Koenkk** [comment]
Could you check if the issue is fixed with the following external converter (first update to z2m 1.28.4):

```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const utils = require('zigbee-herdsman-converters/lib/utils');
const globalStore = require('zigbee-herdsman-converters/lib/store');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    fingerprint: [160, 69, 68, 65, 64, 66].map((applicationVersion) => {
        return {modelID: 'TS011F', applicationVersion, priority: -1};
    }),
    model: 'TS011F_plug_3',
    description: 'Smart plug (with power monitoring by polling)',
    vendor: 'TuYa',
    whiteLabel: [{vendor: 'VIKEFON', model: 'TS011F'}, {vendor: 'BlitzWolf', model: 'BW-SHP15'},
        {vendor: 'Avatto', model: 'MIUCOT10Z'}, {vendor: 'Neo', model: 'NAS-WR01B'}],
    ota: ota.zigbeeOTA,
    extend: tuya.extend.switch({electricalMeasurements: true, powerOutageMemory: true, indicatorMode: true, childLock: true}),
    configure: async (device, coordinatorEndpoint, logger) => {
        await tuya.configureMagicPacket(device, coordinatorEndpoint, logger);
        const endpoint = device.getEndpoint(1);
        endpoint.saveClusterAttributeKeyValue('haElectricalMeasurement', {acCurrentDivisor: 1000, acCurrentMultiplier: 1});
        endpoint.saveClusterAttributeKeyValue('seMetering', {divisor: 100, multiplier: 1});
        device.save();
    },
    options: [exposes.options.measurement_poll_interval()],
    onEvent: (type, data, device, options) =>
        tuya.onEventMeasurementPoll(type, data, device, options, false, true),
};

module.exports = definition;

```

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if issue is fixed

**Comment by Koenkk** [comment]
Integrated the changes, you can keep using the external converter until the next release.

**Comment by passy05** [comment]
OK
