### ISSUE TITLE
Tuya  _TZE200_bkkmqmyo configure reporting support

### ISSUE THREAD

**Issue by marcoNieddu** [Koenkk/zigbee-herdsman-converters#5073]
I bought a Zigbee device _TZE200_bkkmqmyo
I'm trying to change the reporting interval for the attributes InstantaneousDemand and summationDelivered.
I tried to use the standard command "Configure Reporting" for those attributes but I received a response that the attributes are not supported.

How can i change the interval in order to have a report every 5 seconds?
At the moment I received a periodic reporting by the not standard command=0x02 for the cluster=0xef00 of the profile=0x0104

![Cattura](https://user-images.githubusercontent.com/5930844/205435741-8ec0cd59-599d-40be-93b1-d21735e7b605.PNG)

I also create a ticket into the Tuya support portal
Thanks for your help

**Comment by marcoNieddu** [comment]
Using the Zigbee2Mqqt frontend, the cluster manuSpecificTuya has not any attributes and it is impossible to execute a Configure Reporting using the  specific section
![Cattura1](https://user-images.githubusercontent.com/5930844/205435976-2cc7edb0-0408-478b-a01a-d3fe8e96f480.PNG)

**Comment by Koenkk** [comment]
TuYa devices don't support the standard Zigbee configure reporting commands.
