### ISSUE TITLE
Centralite 3-Series Pearl Thermostat running state false positive

### ISSUE THREAD

**Issue by dgagnon-rdx** [Koenkk/zigbee-herdsman-converters#5111]
When "system_mode" is set to "emergency_heating", the running_state didn't change to "idle" when the system stops heating.  It always stay to "heat".  Under "system_mode": "heat", running_state is correct, it changes to idle after heating cycle is completed.

This is the message on the mqtt broker.  At this moment, the system didn't heat at all, but running_state is set to heat instead of idle.

{"battery":98,"fan_mode":"auto","fan_state":"ON","linkquality":93,"local_temperature":21.93,"occupied_cooling_setpoint":28,"occupied_heating_setpoint":21,"running_state":"heat","system_mode":"emergency_heating","temperature_setpoint_hold":false,"voltage":2700}

**Comment by bigun27** [comment]
There are two different Centralite thermostats supported by Z2M, is this the 3157100 or 3156105?

**Comment by dgagnon-rdx** [comment]
it's the 3157100.
