### ISSUE TITLE
Support for Avatto ME167 manufacturerName _TZE200_6rdj8dzm

### ISSUE THREAD

**Issue by markusj** [Koenkk/zigbee-herdsman-converters#5112]
I bought some Tuya/Avatto TRVs which were branded as ME167 (according to manual). However, they have a manufacturer name different from the one in #5081 are thus not recognized. They identify themselves with manufacturer name _TZE200_6rdj8dzm

The TRV works fine (as far as I can tell) with Zigbee2MQTT using the [external converter](https://github.com/twhittock/avatto_me167) from twhittock, after manually adding the missing manufacturer name, of course.

It would be great if support for this model could be added, too. Thanks for your outstanding work!

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by markusj** [comment]
Works, thanks. I noticed that TS0601_thermostat_3 imposes a limit on LocalTemperatureCalibration of +-3 whereas twhittock had limits of +-10. I did not find any discussion or information on the choice of this limit. 

I guess this might cause issues with BetterThermostat if one attempts to use the local calibration mode.

**Comment by wols89** [comment]
> Добавлен!
> 
> Изменения будут доступны в ветке разработки через несколько часов. ( https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html )



> twhittock

Hello!
Please tell me, is there a separate z2m converter for _TZE200_6rdj8dzm? For me, z2m swears that it does not support it. The converter from the respected twhittock was picked up, but the entities are not active there.
Tnx!
![photo_2023-10-16_20-15-28](https://github.com/Koenkk/zigbee-herdsman-converters/assets/137924572/fefefdb7-6906-45f6-8ca2-b6ff29e090e7)
![photo_2023-10-16_20-15-22](https://github.com/Koenkk/zigbee-herdsman-converters/assets/137924572/e29278d3-3dd4-4af6-8f2c-e791f363f374)
