### ISSUE TITLE
1ch switch module TS110E / _TZ3210_zxbtub8r, no switch_type option

### ISSUE THREAD

**Issue by ComicBit** [Koenkk/zigbee-herdsman-converters#5155]
Hi,

I have 1ch, 2ch, switch modules bought from one shop. 2 channel modules support switch_type. The 1ch module unfortunately supports only switching on/off, there is no switch_type option. The problem is, that I have standard switches and the standard configuration implies that the switch is a momentary switch.

Isn't it possible that this module has wrong support in Z2M?

**Comment by Koenkk** [comment]
What is the manufacturer name (e.g. `_TZ3210_zxbtub8r`) for the 2 channel one?

**Comment by ComicBit** [comment]
They are both manifactured by [Lonsonho](https://www.zigbee2mqtt.io/supported-devices/#v=Lonsonho)

**Comment by Koenkk** [comment]
I meant the `manufacturerName` from the data/database.db (like `_TZ3210_zxbtub8r` for the 1 channel)

**Comment by ComicBit** [comment]
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/15569
