### ISSUE TITLE
Expose power and current rounding precision to the UI

### ISSUE THREAD

**Issue by rodolpheAV** [Koenkk/zigbee-herdsman-converters#5157]
Hello,

I'm using some electrical plugs in my home (TS011F_plug_1) perfectlty detected by zigbee2mqtt.
I would like to be able to detect low electrical support (like standby consumption of a washing machine).

The issue I'm facing is that the power consuption precision returned by zigbee2mqtt is lower than the precision of the smart plug due to the rounding logic.
It seems that lib/utils.js defines a rounded precision of 2 so I canot detect very low power consumption.

It would be great to enable the user to change this precision if needed. As far as I understand the code, it may be done by editing the electrical_measurement converter in the [converters/fromZigbee.js](https://github.com/Koenkk/zigbee-herdsman-converters/blob/e09d5a5768ece2a73a5c4644de27b8f2f6eaafac/converters/fromZigbee.js#L730) and expose the following options : 

`options: [exposes.options.calibration('power', 'percentual'), exposes.options.calibration('current', 'percentual'),
            exposes.options.calibration('voltage', 'percentual'), exposes.options.precision('power'), exposes.options.precision('current')]`

Thanks

Rodolphe

**Comment by danieledwardgeorgehitchcock** [comment]
I think you can add the [precision option](https://github.com/Koenkk/zigbee-herdsman-converters/blob/237049b231610c1a781baff60d982874a2ce720b/lib/exposes.js#L505) into your converter which should allow you to do what is needed
