### ISSUE TITLE
Add MOES Smart Socket ZK-EU16M in tuya.js

### ISSUE THREAD

**Issue by clfberlin** [Koenkk/zigbee-herdsman-converters#5169]
MOES ZK-EU16M is a smart wallsocket that also monitors power usage. It comes in various colors. IT shows up in iobroker as an unidentified _TS011F_ and needs an entry as manufacturer '_TZ3000_ss98ec5d' in the _const TS011Fplugs_ section of devices/tuya.js.
Thanks and cheers,
clfberlin

**Comment by Koenkk** [comment]
Will be detected correctly when iobroker updates to the latest zigbee-herdsman-converters.
