### ISSUE TITLE
Zigbee model 'TS0601' and manufacturer name '_TZE200_6rdj8dzm' says unsupported

### ISSUE THREAD

**Issue by SuperDobbo** [Koenkk/zigbee-herdsman-converters#5178]
I have added an Avatto ME167 Thermostatic Radiator Valve, it pairs but then says unsupported.

Looking in https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/tuya.js I can see the exact device around line 2243, it has the matching ZigbeeModel and Manufacturer.

Any idea why its not appearing as supported?

Thanks.

**Comment by Koenkk** [comment]
It is only supported in the dev branch (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) and the next release on 1 January.

**Comment by SuperDobbo** [comment]
Thanks for letting me know.
