### ISSUE TITLE
smoke detector TS0601 not recognized

### ISSUE THREAD

**Issue by monfiston** [Koenkk/zigbee-herdsman-converters#5188]
hello
the TS0601 smoke detector is indicated as not recognized
the manufacturer is _TZE200_ntcy3xu1, but it seems to be a tuya

https://fr.aliexpress.com/item/1005004093193754.html?spm=a2g0o.order_list.order_list_main.11.18285e5bWFY1mW&gatewayAdapt=glo2fra
the pb would seem to be dealt with here, but it is still not recognized
https://github.com/KiwiHC16/Abeille/issues/2380

![Capture d’écran 2022-12-22 132422](https://user-images.githubusercontent.com/109015014/209134019-b371c151-dfcb-43e3-9fd9-1dc65b557ce3.jpg)

**Comment by Koenkk** [comment]
This device shoudl be supported in z2m 1.28.4.
