### ISSUE TITLE
Zlinky_TIC Tarif Sem WE Lundi

### ISSUE THREAD

**Issue by su2626** [Koenkk/zigbee-herdsman-converters#5194]
Hi, 

The "Tarif" parameter seems to be incomplete. It only show Sem WE Mercredi but "Lundi" and "Vendredi" are missing from the list and occurs some issue on the HA energy dashboard.

Is there any chance those two missing days will be added soon ?

**Comment by SilentT-FR** [comment]
Can you give me your current_tarif state ? Like:  "current_tarif": "H PLEINE/CREUSE",

**Comment by su2626** [comment]
Hi, 

Thank you for the reply. 

My current_tarif :  HC SEM WE LUNDI

**Comment by SilentT-FR** [comment]
Ok we need to create a new tarif

@su2626 you can give a complete State of zlinky without personal information ( meter_serial_number site_id )

and if you can find via the counter the indexes which are not empty
i think its because the tarif  "SEM WE MERCREDI" is not HC/HP so its lack of : EASD02 state the HC kwh


@vk496 PI

**Comment by vk496** [comment]
I created that filter because I selected Mercredi as cheap day. But is only a filter. The indexes are not based on that.

And yes, the filter assume is Standard mode. The best thing in my opinion is create that filter for legacy mode or @su2626 unselect the predefined filter to see all indexes and use the option to filter by yourself what you need.

Salu2

**Comment by SilentT-FR** [comment]
@su2626 If you want you can add on "tic_command_whitelist" parameter to retrive the missing parameters during the time to do the merges

@vk496 because EDF create Two tarif 

[HC] SEM WE {LUNDI/MERCREDI/VENDREDI}

And the tarif : https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/lixee.js#L257 exclude EASD02
I think indexes was fill depending on the day of the tarif or its the same but i dont know and the documentation of Enedis was not clear about that

**Comment by vk496** [comment]
@SilentT-FR it depends of the company. In case of EDF, there is a tarif "Zen Plus" or something like that, where you can choose which day you want cheap (besides weekends and holidays)

**Comment by SilentT-FR** [comment]
Yes this one : https://particulier.edf.fr/fr/accueil/electricite-gaz/offres-electricite/offres-marche/electricite-weekend/zen-week-end-plus.html

**Comment by su2626** [comment]
> @su2626 you can give a complete State of zlinky without personal information ( meter_serial_number site_id )

Here you go : 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/SLEFEU~1.SPA/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/SLEFEU~1.SPA/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

<div style='box-sizing: border-box;--bs-gutter-x:24px;--bs-gutter-y:0;
display:flex;flex-wrap: wrap;margin-left:calc(var(--bs-gutter-x)*-0.5);
margin-right:calc(var(--bs-gutter-x)*-0.5);margin-top:calc(var(--bs-gutter-y)*-1);
border-bottom:var(--bs-border-width) var(--bs-border-style) var(--bs-border-color) !important;
align-items: center !important;padding-bottom:0.25rem !important;padding-top:
0.25rem !important;font-variant-ligatures: normal;font-variant-caps: normal;
orphans: 2;text-align:start;widows: 2;-webkit-text-stroke-width: 0px;
text-decoration-thickness: initial;text-decoration-style: initial;text-decoration-color: initial'>



ADSC | XXXXXXXXXXXXXX
-- | --
Numéro    de Série |  
NGTF | HC SEM WE LUNDI
Supplier    pricing schedule name |  
LTARF | HP SEMAINE
Libellé    de prix du founisseur de courant |  
NTARF | 2
Numéro    d'indice tarifaire actuel |  
VTIC | 2
Version    du protocole de télé-information client |  
DATE | H230103125925
Date    et heure actuels |  
EAST | 19485.44kWh
Total    active power delivered |  
EASF01 | 18632.229kWh
Total    provider active power delivered (index 01) |  
EASF02 | 671.55kWh
Total    provider active power delivered (index 02) |  
EASF03 | 57.488kWh
Total    provider active power delivered (index 03) |  
EASF04 | 70.62kWh
Total    provider active power delivered (index 04) |  
EASF05 | 24.487kWh
Total    provider active power delivered (index 05) |  
EASF06 | 29.067kWh
Total    provider active power delivered (index 06) |  
EASF07 | 0kWh
Puissance    active totale fournie par le fournisseur (index 07) |  
EASF08 | 0kWh
Puissance    active totale fournie par le fournisseur (index 08) |  
EASF09 | 0kWh
Puissance    active totale fournie par le fournisseur (index 09) |  
EASF10 | 0kWh
Puissance    active totale fournie par le fournisseur (index 10) |  
EASD01 | 13124.182kWh
Puissance    active totale fournie par le fournisseur (index 01) |  
EASD02 | 5173.963kWh
Puissance    active totale fournie par le fournisseur (index 02) |  
EASD03 | 524.187kWh
Puissance    active totale fournie par le fournisseur (index 03) |  
EASD04 | 663.137kWh
Puissance    active totale fournie par le fournisseur (index 04) |  
IRMS1 | 8A
Courant    efficace |  
URMS1 | 242V
Tension    efficace |  
PREF | 9kVA
Apparent    power of reference |  
STGE | XXX
Registre    des statuts |  
PCOUP | 9kVA
Seuil    de puissance apparente |  
CCASN | 224W
Point    actuel de la courbe de charge active dessinée |  
CCASN-1 | 284W
Point    précédent de la courbe de charge active dessinée |  
UMOY1 | 241V
Tension    efficace moyenne (phase 1) |  
SINSTS | 1868VA
Immediate    apparent power delivered |  
SMAXN | 2760VA
Apparent    power delivered peak |  
SMAXN-1 | 4420VA
Puissance    apparente max. retirée n-1 |  
MSG1 | PAS DE MESSAGE
Message    court |  
MSG2 | Chaîne vide ("")
Message    ultra-court |  
PRM | XXXXXXXXXXXX
Numéro    PMR |  
DPM1 | 0
Start    mobile point 1 |  
FPM1 | 0
Stop    mobile point 1 |  
DPM2 | 0
Start    mobile point 2 |  
FPM2 | 0
Stop    mobile point 2 |  
DPM3 | 0
Start    mobile point 3 |  
FPM3 | 0
Stop    mobile point 3 |  
RELAIS | 0
NJOURF | 0
Calendrier    du fournisseur du numéro du jour en cours |  
NJOURF+1 | 0
Calendrier    du fournisseur de numéro du jour suivant |  
PJOURF+1 | 00008002 011EC001 071E8002 0F1EC001    111E8002 NONUTILE NONUTILE NONUTILE
Profil    du jour calendaire fournisseur suivant |  
PPOINTE1 | Chaîne vide ("")
Profil    du prochain jour d'enregistrement |  
linkquality | 108lqi
Qualité    du lien (force du signal) |  



</body>

</html>

**Comment by SilentT-FR** [comment]
Sorry for the late, I saw that you did it all alone very good works !
