### ISSUE TITLE
FrankeverValve NOT RECOGNIZED DP #102

### ISSUE THREAD

**Issue by duzorg** [Koenkk/zigbee-herdsman-converters#5206]
Hello. 
The FrankEver Valve is indicated as not recognized DP #102

`Zigbee2MQTT:warn  2022-12-26 12:03:30: zigbee-herdsman-converters:FrankeverValve: NOT RECOGNIZED DP #102 with data {"dp":102,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,70]}}`

This option shows the actual position of the valve. The "tz.frankever_threshold" from the converter shows the set position.

Log From Z2M:
`Zigbee2MQTT:debug 2022-12-26 15:40:10: Received Zigbee message from 'Test Valve', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,50],"type":"Buffer"},"datatype":2,"dp":102}],"seq":0}' from endpoint 1 with groupID 0
Zigbee2MQTT:warn  2022-12-26 15:40:10: zigbee-herdsman-converters:FrankeverValve: NOT RECOGNIZED DP #102 with data {"dp":102,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,50]}}
Zigbee2MQTT:info  2022-12-26 15:40:10: MQTT publish: topic 'zigbee2mqtt/Test Valve', payload '{"last_seen":"2022-12-26T15:40:10+07:00","linkquality":156,"state":"ON","threshold":100,"timer":0}'
Zigbee2MQTT:debug 2022-12-26 15:40:12: Received Zigbee message from 'Test Valve', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,60],"type":"Buffer"},"datatype":2,"dp":102}],"seq":0}' from endpoint 1 with groupID 0
Zigbee2MQTT:warn  2022-12-26 15:40:12: zigbee-herdsman-converters:FrankeverValve: NOT RECOGNIZED DP #102 with data {"dp":102,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,60]}}
Zigbee2MQTT:info  2022-12-26 15:40:12: MQTT publish: topic 'zigbee2mqtt/Test Valve', payload '{"last_seen":"2022-12-26T15:40:12+07:00","linkquality":149,"state":"ON","threshold":100,"timer":0}'
Zigbee2MQTT:debug 2022-12-26 15:40:14: Received Zigbee message from 'Test Valve', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,70],"type":"Buffer"},"datatype":2,"dp":102}],"seq":0}' from endpoint 1 with groupID 0
Zigbee2MQTT:warn  2022-12-26 15:40:14: zigbee-herdsman-converters:FrankeverValve: NOT RECOGNIZED DP #102 with data {"dp":102,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,70]}}
Zigbee2MQTT:info  2022-12-26 15:40:14: MQTT publish: topic 'zigbee2mqtt/Test Valve', payload '{"last_seen":"2022-12-26T15:40:14+07:00","linkquality":149,"state":"ON","threshold":100,"timer":0}'
Zigbee2MQTT:debug 2022-12-26 15:40:16: Received Zigbee message from 'Test Valve', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,80],"type":"Buffer"},"datatype":2,"dp":102}],"seq":0}' from endpoint 1 with groupID 0
Zigbee2MQTT:warn  2022-12-26 15:40:16: zigbee-herdsman-converters:FrankeverValve: NOT RECOGNIZED DP #102 with data {"dp":102,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,80]}}
Zigbee2MQTT:info  2022-12-26 15:40:16: MQTT publish: topic 'zigbee2mqtt/Test Valve', payload '{"last_seen":"2022-12-26T15:40:16+07:00","linkquality":149,"state":"ON","threshold":100,"timer":0}'
Zigbee2MQTT:debug 2022-12-26 15:40:19: Received Zigbee message from 'Test Valve', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,90],"type":"Buffer"},"datatype":2,"dp":102}],"seq":0}' from endpoint 1 with groupID 0
Zigbee2MQTT:warn  2022-12-26 15:40:19: zigbee-herdsman-converters:FrankeverValve: NOT RECOGNIZED DP #102 with data {"dp":102,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,90]}}
Zigbee2MQTT:info  2022-12-26 15:40:19: MQTT publish: topic 'zigbee2mqtt/Test Valve', payload '{"last_seen":"2022-12-26T15:40:19+07:00","linkquality":145,"state":"ON","threshold":100,"timer":0}'
Zigbee2MQTT:debug 2022-12-26 15:40:22: Received Zigbee message from 'Test Valve', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,100],"type":"Buffer"},"datatype":2,"dp":102}],"seq":0}' from endpoint 1 with groupID 0
Zigbee2MQTT:warn  2022-12-26 15:40:22: zigbee-herdsman-converters:FrankeverValve: NOT RECOGNIZED DP #102 with data {"dp":102,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,100]}}
Zigbee2MQTT:info  2022-12-26 15:40:22: MQTT publish: topic 'zigbee2mqtt/Test Valve', payload '{"last_seen":"2022-12-26T15:40:22+07:00","linkquality":138,"state":"ON","threshold":100,"timer":0}'`

**Comment by BradleyFord** [comment]
I get the same error, it seems that Frankever also changes the DPs on different production runs...
