### ISSUE TITLE
Update support of IKEA 4 buttons Styrbar Remote with 2.4.5 firmware

### ISSUE THREAD

**Issue by rdu70** [Koenkk/zigbee-herdsman-converters#5210]
Hello.  Latest 2.4.5 firmware broke support for this device.  An update should be able to solve that issue as done in ZHA.  Thanks

**Comment by tefracky** [comment]
Do you have a link for the fix in ZHA?

**Comment by rdu70** [comment]
Hi,
Here is what I've seen : 
https://github.com/zigpy/zha-device-handlers/pull/2028
https://github.com/zigpy/zigpy/discussions/660#discussioncomment-4460743

https://github.com/zigpy/zha-device-handlers/pull/2028/files

I can also give you a zigbee-herdsman debug log.  I grabbed the log when pairing the device.  After a few minutes there is an OTA request log from the device, then nothing.  Even pressing buttons does not generate any log.  Device id to look in the log is 0x385b44fffe38ba50.

[ikea_styrbar_2_5_4.txt](https://github.com/Koenkk/zigbee-herdsman-converters/files/10320084/ikea_styrbar_2_5_4.txt)

**Comment by mattmole** [comment]
Hi,

I've been affected by this as well. Let me know if I can provide any support in testing a fix etc

Matt

**Comment by Berlusconi13** [comment]
At least you were able to update😅
