### ISSUE TITLE
Add Philips 5047130P6 (essentially the same as 5047130P9)

### ISSUE THREAD

**Issue by steschi** [Koenkk/zigbee-herdsman-converters#5217]
I am not entirely sure why there are multiple models (maybe revisions?) of the same lamp, but 5047130P6 is not automatically detected. Using a custom converter which essentially works the same as for the already supported 5047130P9 does work without any issue for now. 

It also looks exactly like https://www.zigbee2mqtt.io/devices/5047130P9.html

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
