### ISSUE TITLE
Add support for Phillips 929003047001

### ISSUE THREAD

**Issue by adamlc** [Koenkk/zigbee-herdsman-converters#5254]
Hello, is it please possible to add support for the Phillips `929003047001`?

The device is exactly the same as [929003047101](https://www.zigbee2mqtt.io/devices/929003047101.html#philips-929003047101) and came as part of a bundle with the later versions. I have no idea why this device has a different model number.

Up until recently I had been using an external converter to get round it, but for some reason thats broken in the latest Z2M.

```js
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const ota = require('zigbee-herdsman-converters/lib/ota');
const extendDontUse = require('zigbee-herdsman-converters/lib/extend');

const hueExtend = {
    light_onoff_brightness_colortemp: (options={}) => ({
        ...extendDontUse.light_onoff_brightness_colortemp(options),
        ota: ota.zigbeeOTA,
        meta: {turnsOffAtBrightness1: true},
        toZigbee: extendDontUse.light_onoff_brightness_colortemp(options).toZigbee
            .concat([tz.hue_power_on_behavior, tz.hue_power_on_error]),
    }),
};

const definition = {
    zigbeeModel: ['929003047001'],
    model: '929003047001',
    vendor: 'Philips',
    description: 'Hue White ambiance Milliskin (round)',
    extend: hueExtend.light_onoff_brightness_colortemp({colorTempRange: [153, 454]}),
};

module.exports = definition;
```

Many thanks!

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
