### ISSUE TITLE
Missing ieeeAddr for Sunricher ZGP dimmer switch

### ISSUE THREAD

**Issue by repvik** [Koenkk/zigbee-herdsman-converters#5266]
I have a SR-ZGP2801K4-DIM with the address 0x000000001faf8c32. 
Adding {modelID: 'GreenPower_2', ieeeAddr: /^0x000000001fa.....$/} fixed the "unknown device" errors, and all buttons work as expected.

**Comment by repvik** [comment]
Got another one with the same model number, with ieeeAddr 0x0000000034b7ac76

**Comment by Koenkk** [comment]
Added both, thanks!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
