### ISSUE TITLE
Mimic momentary events in fromZigbee converter

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [Koenkk/zigbee-herdsman-converters#5343]
I have recently created a fromZigbee converter for an Osram Lightify PBC.

While the device should report events as momentary actions, it seems to instead latch on the last action.

Is there a way in Z2M, to mimic a momentary action so that triggers, etc work in Home Automation systems?

**Comment by Koenkk** [comment]
Is https://github.com/Koenkk/zigbee-herdsman-converters/pull/5276 what you are looking for?

**Comment by danieledwardgeorgehitchcock** [comment]
I don't think so..?

I need my converter to report the action, then revert to null/empty/n/a straight after like a standard momentary action device.

At present, the last action is retained which doesn't work in Home Automation systems if you are using a state change comparison event as a trigger.

The behaviours are as follows:

| Type | Press Event | Release Event | State After Release Event |
| ---- | ---------- | ------------ | ------------------------ |
Current Behaviour | L1_press | L1_release | L1_release
Desired Behaviour | L1_press | L1_release | N/A

**Comment by danieledwardgeorgehitchcock** [comment]
This is still required

**Comment by Koenkk** [comment]
@danieledwardgeorgehitchcock `action` values should be automatically cleared (at least when you enable the Home Assistant integration (https://www.zigbee2mqtt.io/guide/faq/#why-is-the-action-property-always-empty)

**Comment by Koenkk** [comment]
Can you provide the debug log of this and your `configuration.yaml`?
