### ISSUE TITLE
Yale Lock update

### ISSUE THREAD

**Issue by poma** [Koenkk/zigbee-herdsman-converters#538]
There are a few new events in my log:

```
No converter available for 'YRD426NRSC' with cid 'genPowerCfg', type 'devChange' and data '{"cid":"genPowerCfg","data":{"batteryVoltage":48,"batteryPercentageRemaining":72}}'
No converter available for 'YRD426NRSC' with cid 'genPowerCfg', type 'devChange' and data '{"cid":"genPowerCfg","data":{"batteryPercentageRemaining":74}}'
```

But I'm not sure how to add them correctly to the config to not break something for other users.

**Comment by Koenkk** [comment]
The `devChange` event is generated after an `attReport` or `readRsp` which is already converted by `fz.battery_200`.  As `devChange` will be removed in the future anyway, I think you can add `fz.ignore_power_change` which will suppress the message.
