### ISSUE TITLE
support for battery reporting for Ikea devices with FW 24.x.x

### ISSUE THREAD

**Issue by thatslolo** [Koenkk/zigbee-herdsman-converters#5387]
I converted my Ikea tradfri setup last week from the Dirigera hub to z2m and it seems that the newer fw provided only to the Dirigera Hub corrects the battery reporting to 0-200 instead of 0-100.
Now I have multiple devices with a battery reported to be > 100%.
I do have a few devices (E1926, E2102, E1743, E1766, E1812) with this version of fw, so if I can provide logs to correct this issue, I would gladly help.
I assume "dontDividePercentage" has to be set to false for devices with this fw.

**Comment by thatslolo** [comment]
Actually I do have one device with a battery of 255, so it seems that the new fw reports 0-255

**Comment by MattWestb** [comment]
Is the 255 reporting device Styrbar ?

I have 2 of them that is reporting more then 200% and HA is showing more then 100 % = not OK for one Zigbee device.

I think the Styrabar is not doing it OK and it was the first device getting 24.X firmware so its very likely some bugs that is being fixed in the  later versions.

**Comment by Koenkk** [comment]
With the latest dev branch, some of these issues should already be fixed (100 -> 200). I don't know about the 255, can you provide the debug log when the device **first** reports this? (first stop z2m, remove `battery` from `data/state.json` and start z2m)

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable debug logging.

**Comment by thatslolo** [comment]
I don't own a styrbar remote, and I don't remember which device reported >200%. 
Right now I can't reproduce it and with the latest dev branch all my devices currently report a sane battery state. So this issue can be closed from my side.
