### ISSUE TITLE
OTA Tradfri N2001/N2002'(No image available for imageType '4555')

### ISSUE THREAD

**Issue by Berlusconi13** [Koenkk/zigbee-herdsman-converters#5393]
**What happened?**

I tried to upgrade Ikea E2001/E2002 to the latest version using Zigbee2mqtt — 1.29.2-1 on HomeAssistant.
The message „Failed to check if update available for 'Tradfri Dimmer' (No image available for imageType '4555')“ appears.
When I open „[http://fw.ota.homesmart.ikea.net/feed/version_info.json“](http://fw.ota.homesmart.ikea.net/feed/version_info.json%E2%80%9C) I can see that the respective imagetype is/should be availale
„{"fw_binary_url":"[http://fw.ota.homesmart.ikea.net/global/GW1.0/01.19.046/bin/10078031-zingo_kt_styrbar_remote-2.4.5.ota.ota.signed","fw_file_version_LSB":581,"fw_file_version_MSB":0,"fw_filesize":218698,"fw_image_type":4555,"fw_manufacturer_id":4476,"fw_type":2}“](http://fw.ota.homesmart.ikea.net/global/GW1.0/01.19.046/bin/10078031-zingo_kt_styrbar_remote-2.4.5.ota.ota.signed%22,%22fw_file_version_LSB%22:581,%22fw_file_version_MSB%22:0,%22fw_filesize%22:218698,%22fw_image_type%22:4555,%22fw_manufacturer_id%22:4476,%22fw_type%22:2%7D%E2%80%9C)

I tried the same with the IKEA test url/server, it‘s the same behaviour.

It seems, that there‘s an issue with the json parser, since that image type is obviosly available 

**What did you expect to happen?**

Update of IKEA Tradfri E2001/E2002 device

**How to reproduce it (minimal and precise)**

No response

**Zigbee2MQTT version**

1.29.2-1

**Adapter firmware version**

20220219

**Adapter**

CC2652P (Sonoff EBDongle-P)

**Debug log**

No response

**Comment by Koenkk** [comment]
Could you provide me the debug log of this?

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable debug logging.

**Comment by Berlusconi13** [comment]
Now it shows a different message:
„2023-01-25 21:50:26 Firmware on '0x040d84fffe9049ea' is newer than latest firmware online.“

Debug log:
https://jpst.it/35geO

**Comment by Koenkk** [comment]
The device requests the following, `fileVersion` == `65572` and `imageType` == `4555`:

```
Received Zigbee message from 'Tradfri Dimmer', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":1,"fileVersion":65572,"imageType":4555,"manufacturerCode":4476}' from endpoint 1 with groupID 0
```

The test version on http://fw.ota.homesmart.ikea.net/feed/version_info.json is:

```
{"fw_binary_url":"http://fw.ota.homesmart.ikea.net/global/GW1.0/01.19.046/bin/10078031-zingo_kt_styrbar_remote-2.4.5.ota.ota.signed","fw_file_version_LSB":581,"fw_file_version_MSB":0,"fw_filesize":218698,"fw_image_type":4555,"fw_manufacturer_id":4476,"fw_type":2},
```

`"fw_file_version_LSB":581,"fw_file_version_MSB":0,` -> `(image.fw_file_version_MSB << 16) | image.fw_file_version_LSB` = `(0 << 16) | 581` = `fileVersion`: `581`

So the fw on your device is indeed newer than the ones on the IKEA OTA update site (if you follow the Zigbee spec)

Given that you previously got `No image available for imageType '4555'` and now `Firmware on '0x040d84fffe9049ea' is newer than latest firmware online.“` it seems that IKEA is making some changes to their OTA site, maybe they will fix this later.

**Comment by Berlusconi13** [comment]
See: https://github.com/zigpy/zha-device-handlers/pull/2028

they seem have changed something, so that fileversion of current fw is lower now

**Comment by Berlusconi13** [comment]
Or here:
https://github.com/zigpy/zigpy/discussions/660#discussioncomment-4460743

**Comment by Koenkk** [comment]
Given that their Dirigera hub is not doing these updates and that it removes support for group binding, I don't think its wise to push this fw to all z2m users. In case you want to use it, read this: https://www.zigbee2mqtt.io/guide/usage/ota_updates.html#local-ota-index-and-firmware-files to `force` the update.

**Comment by MattWestb** [comment]
OTA file with patched version in the meta data that making it working normal (its one upgrade not one downgrade the system and device is thinking).
The GBL file inside is signed and not touched and the device is accepting it and flashing it and its working so the signing is not broke = safe.
https://github.com/zigpy/zigpy/issues/1153#issuecomment-1416078425
