### ISSUE TITLE
Device Driver Sub-Module??

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [Koenkk/zigbee-herdsman-converters#5428]
I am currently in the process of picking apart a Control4 lua driver that I have managed to pick apart for a Yale door lock Zigbee module (Koenkk/zigbee2mqtt#4778).

I have encountered quite a unique problem that I need guidance on.

As this module is quite a universal item, it can be fitted in many different lock models so, on initial Zigbee interview, it presents generic attributes. It then queries the lock to determine its model, capabilities, etc.

Finally, once the lock model is known, it selects from one of two different configurations:

```lua
local function createCapabilities()
    capabilities = {
        Doorman = {
            [CAP_LANGUAGE_VALUES] = "Danish, English, Norwegian, Swedish",
            [CAP_AUTO_LOCK_TIME_VALUES] = "0, 10",
            [CAP_AUTO_LOCK_TIME_DISPLAY_VALUES] = "Off, On",
            [CAP_HAS_LOCK_MODES] = false,
            [CAP_HAS_WRONG_CODE_ATTEMPTS] = false,
            [CAP_HAS_SHUTOUT_TIMER] = false,
            [CAP_HAS_ONE_TOUCH_LOCKING] = false
        },
        RealLiving = {
            [CAP_LANGUAGE_VALUES] = "English, Spanish, French",
            [CAP_AUTO_LOCK_TIME_VALUES] = "0, 30, 60, 120, 180",
            [CAP_AUTO_LOCK_TIME_DISPLAY_VALUES] = "Off, 30 seconds, 60 seconds, 2 minutes, 3 minutes",
            [CAP_HAS_LOCK_MODES] = true,
            [CAP_HAS_WRONG_CODE_ATTEMPTS] = true,
            [CAP_HAS_SHUTOUT_TIMER] = true,
            [CAP_HAS_ONE_TOUCH_LOCKING] = true
        }
    }
```

Can this functionality be mimicked in Z2M? - I think the difficulty lies in that you'd have to await the lock model query before continuing the device setup..?

**Comment by Koenkk** [comment]
The exposes can be changed dynamically, see e.g.: https://github.com/Koenkk/zigbee-herdsman-converters/blob/c5c28c4df9bda53cc9d6fec9f1123fb28fbe444a/devices/develco.js#L556

**Comment by danieledwardgeorgehitchcock** [comment]
Thanks!
