### ISSUE TITLE
Device request Smart Siren Immax Neo 07504L

### ISSUE THREAD

**Issue by haade-administrator** [Koenkk/zigbee-herdsman-converters#5455]
immax cz send me Uart table

|DP ID | DP Name | Identifier | Data Transfer Type | Data Type | Properties|
|-- | -- | -- | -- | -- | --|
|4 | alert | alert_state | Send and Report | Bool |  
|5 | Alarm Volume | alarm_volume | Send and Report | Enum | Enum Value: mute, low, middle, high|
|6 | Power supply state | supply_state | Report Only | Bool |  
|13 | Alarm Switch | alarm_switch | Send and Report | Bool |  
|14 | Battery level | battery_percentage | Report Only | Value | Value Range: 0-500, Pitch: 1, Scale: 0, Unit: %|
|17 | Brightness Adjustment | alarm_bright | Send and Report | Enum | Enum Value: dark, weak, middle, strong|
|18 | alarm time | alarm_time2 | Send and Report | Value | Value Range: 0-180, Pitch: 1, Scale: 0, Unit:|

my js:
    
fingerprint: [
    {
        modelID: 'TS0219',
        manufacturerName: '_TYZB01_b6eaxdlh',
    },
],
model: '07504L',
vendor: 'Immax',
description: 'Smart siren',
    fromZigbee: [fz.battery, fz.ts0216_siren, fz.power_source],
    toZigbee: [tz.warning, tz.ts0216_alarm, tz.ts0216_duration, tz.ts0216_volume],
    exposes: [
        e.battery(), 
        e.battery_voltage(),
        exposes.binary('alarm', ea.STATE_SET, true, false), 
        exposes.numeric('volume', ea.ALL).withValueMin(0).withValueMax(50).withDescription('Volume of siren'),
        exposes.numeric('duration', ea.STATE_SET).withValueMin(0).withValueMax(240).withValueStep(5)
                .withUnit('s').withDescription('Alarm time'),
        ],
    meta: {disableDefaultResponse: true,},
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        const bindClusters = ['genPowerCfg', 'genBasic', 'ssIasZone', 'ssIasWd'];
        await endpoint.read('ssIasZone', ['zoneState', 'zoneStatus', 'iasCieAddr', 'zoneId']);
        await endpoint.read('ssIasWd', ['1', '2', '3', 'maxDuration']);
        await reporting.bind(endpoint, coordinatorEndpoint, bindClusters);
        await reporting.batteryVoltage(endpoint);
        await reporting.batteryPercentageRemaining(endpoint);
        if (device.powerSource == 'Mains (3 phase)') {
        device.powerSource = 'Mains (single phase)';
        } else if (device.powerSource == 'Emergency mains and transfer switch') {
        device.powerSource = 'Battery';
        }
        device.save();
    },

![immax](https://user-images.githubusercontent.com/76404800/220135085-3db3958a-2a06-46de-bf8a-0433c8fad7bf.png)

and state:

`{
    "ac_status": false,
    "alarm": false,
    "battery": 90,
    "battery_low": false,
    "linkquality": 58,
    "power_source": "mains_three_phase",
    "restore_reports": false,
    "state": "OFF",
    "supervision_reports": true,
    "tamper": false,
    "test": false,
    "voltage": 4100,
    "volume": 111
}`

db:

`
{"id":42,"type":"Router","ieeeAddr":"0x847127fffea490bf","nwkAddr":12466,"manufId":0,"manufName":"_TYZB01_b6eaxdlh","powerSource":"Mains (3 phase)","modelId":"TS0219","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1027,"inClusterList":[0,1,3,4,5,1280,1282,61183],"outClusterList":[3,25],"clusters":{"genBasic":{"attributes":{"modelId":"TS0219","manufacturerName":"_TYZB01_b6eaxdlh","powerSource":2}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b0008c98813","zoneState":1,"zoneStatus":16,"zoneId":23}},"genPowerCfg":{"attributes":{"batteryVoltage":42,"batteryPercentageRemaining":200}},"ssIasWd":{"attributes":{"1":50,"2":100,"3":0,"maxDuration":10}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b0008c98813","endpointID":1},{"cluster":0,"type":"endpoint","deviceIeeeAddress":"0x00124b0008c98813","endpointID":1},{"cluster":1280,"type":"endpoint","deviceIeeeAddress":"0x00124b0008c98813","endpointID":1},{"cluster":1282,"type":"endpoint","deviceIeeeAddress":"0x00124b0008c98813","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":32,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0},{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0}],"meta":{}}},"appVersion":80,"stackVersion":2,"hwVersion":2,"dateCode":"20190430","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1678613392},"lastSeen":1676900513514,"defaultSendRequestWhen":"immediate"}
`

any help please

_Originally posted by @haade-administrator in https://github.com/Koenkk/zigbee-herdsman-converters/issues/2470#issuecomment-1422192041_

**Comment by roudou** [comment]
Hello ,

begin with

siren.js
```
const exposes = require('/app/node_modules/zigbee-herdsman-converters/lib/exposes');
const reporting = require('/app/node_modules/zigbee-herdsman-converters/lib/reporting');
const fz = {...require('/app/node_modules/zigbee-herdsman-converters/converters/fromZigbee'), legacy: require('/app/node_modules/zigbee-herdsman-converters/lib/legacy').fromZigbee};
const tz = require('/app/node_modules/zigbee-herdsman-converters/converters/toZigbee');
const tuya = require('/app/node_modules/zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;



module.exports = [

    {
	fingerprint: [
    {
        modelID: 'TS0219',
        manufacturerName: '_TYZB01_vpffpbju',
    },
	],
	model: '07504L',
	vendor: 'Immax',
	description: 'Smart siren',
    fromZigbee: [fz.battery, fz.ts0216_siren, fz.power_source],
    toZigbee: [tz.ts0216_alarm, tz.ts0216_duration, tz.ts0216_volume],
    exposes: [
        e.battery(), 
        e.battery_voltage(), 
        exposes.binary('alarm', ea.STATE_SET, true, false), 
        exposes.numeric('volume', ea.ALL).withValueMin(0).withValueMax(50).withDescription('Volume of siren')
        ],
    meta: {disableDefaultResponse: true,},
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        const bindClusters = ['genPowerCfg'];
        await reporting.bind(endpoint, coordinatorEndpoint, bindClusters);
        await reporting.batteryVoltage(endpoint);
        await reporting.batteryPercentageRemaining(endpoint);
        if (device.powerSource == 'Mains (3 phase)') {
        device.powerSource = 'Mains (single phase)';
        } else if (device.powerSource == 'Emergency mains and transfer switch') {
        device.powerSource = 'Battery';
        }
        device.save();
    },

    },
];
```

![image](https://user-images.githubusercontent.com/21971655/218317012-2725f98c-7408-4931-943a-a1a50120da12.png)

__

**Comment by gustonator** [comment]
Hi. Any progress on this?

**Comment by haade-administrator** [comment]
you can use the code but is not perfect:

```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const utils = require('zigbee-herdsman-converters/lib/utils');
const tuya = require('/app/node_modules/zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;


const definition = {
    
fingerprint: [
    {
        modelID: 'TS0219',
        manufacturerName: '_TYZB01_b6eaxdlh',
    },
],
model: '07504L',
vendor: 'Immax',
description: 'Smart siren',
    fromZigbee: [fz.battery, fz.ts0216_siren, fz.power_source],
    toZigbee: [tz.warning, tz.ts0216_alarm, tz.ts0216_duration, tz.ts0216_volume],
    exposes: [
        e.battery(), 
        e.battery_voltage(),
        exposes.binary('alarm', ea.STATE_SET, true, false), 
        exposes.numeric('volume', ea.ALL).withValueMin(0).withValueMax(50).withDescription('Volume of siren'),
        exposes.numeric('duration', ea.STATE_SET).withValueMin(0).withValueMax(240).withValueStep(5)
                .withUnit('s').withDescription('Alarm time'),
        ],
    meta: {disableDefaultResponse: true,},
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        const bindClusters = ['genPowerCfg', 'genBasic', 'ssIasZone', 'ssIasWd'];
        await endpoint.read('ssIasZone', ['zoneState', 'zoneStatus', 'iasCieAddr', 'zoneId']);
        await endpoint.read('ssIasWd', ['maxDuration']);
        await reporting.bind(endpoint, coordinatorEndpoint, bindClusters);
        await reporting.batteryVoltage(endpoint);
        await reporting.batteryPercentageRemaining(endpoint);
        if (device.powerSource == 'Mains (3 phase)') {
        device.powerSource = 'Mains (single phase)';
        } else if (device.powerSource == 'Emergency mains and transfer switch') {
        device.powerSource = 'Battery';
        }
        device.save();
    },
};

module.exports = definition;
```

**Comment by gustonator** [comment]
Hi.
yes, I downloaded this code from github.
I thought that you have some new and polished code :)

thanks anyway

S Pozdravom / Kind regards
Rudolf Brösztl

**Comment by gustonator** [comment]
Hi @haade-administrator 
Last year when I used your code, it was working, but few months later it stopped, and I'm unable to get it to work again. I think there was a change in library? 
Do you have some updated version? Or did you bought some other siren? I need it for my garage :/

thanks
