### ISSUE TITLE
Fischer & Honsel lamp model 020B0B incorrectly configured

### ISSUE THREAD

**Issue by Rwin1234** [Koenkk/zigbee-herdsman-converters#5463]
I am moving from Lidl/Silvercrest HUB to HA+ZB2MQTT - works great so far. But I have one Fischer & Honsel wall lamp with model number 020B0B that is recognized by a converter https://github.com/Koenkk/zigbee-herdsman-converters/blob/300d75007b6e2d2bd559bf1767eb34fd3956573d/devices/seastar_intelligence.js but doesnt work at all. Interview is completed. I can see the clusters map.

My model 020B0B lamp looks differently, it is not a desk lamp but a wall lamp, and it seems to have its main clusters on endpoint 2, not endpoint 1. So, the manufacturer used the same model number for two different lamps and two different firmware versions. Great...

I can switch the lamp on/off in the dev console by using endpoint 2, cluster 6, command 0 and 1. So that all works. Now I was fiddling with the existing converter to somehow use endpoint 2. I am a total noob in JS but dived into the code tree and tried to bind the endpoint 2 to the coordinator, using some examples, and then restart the ZB2MQTT addon. By the way I am running HA OS latest release, all updated. My attempt:

```
const definition = {
    zigbeeModel: ['020B0B'],
    model: '020B0B',
    vendor: 'Fischer & Honsel',
    description: 'LED Wall lamp',

    extend: extend.light_onoff_brightness_colortemp_color({noConfigure: true}),
    
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(2);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genBasic', 'genGroups', 'genOnOff', 'lightingColorCtrl']);
     },
};

module.exports = definition;
```

In the "Bind" tab of ZB2MQTT I see that the clusters are bound to Endpoint 2. But it still doesnt work, all commands timeout, for example when reading the on/off state I get:

`023-02-11 14:59:39Publish 'get' 'state' to 'FH Wall Lamp' failed: 'Error: Read 0x00158d0002a7749c/1 genOnOff(["onOff"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 40909 - 1 - 11 - 6 - 1 after 10000ms)'`

So it is still reading on /1 ? I am not on the experience level yet to solve this but like to learn. Is binding the correct way of approaching this? How can I set the Endpoint? Thanks in advance!

**Comment by Koenkk** [comment]
To use endpoint 2 as the default use the following:

```js
const definition = {
    zigbeeModel: ['020B0B'],
    model: '020B0B',
    vendor: 'Fischer & Honsel',
    description: 'LED Wall lamp',

    extend: extend.light_onoff_brightness_colortemp_color({noConfigure: true}),
    
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(2);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genBasic', 'genGroups', 'genOnOff', 'lightingColorCtrl']);
     },
        endpoint: (device) => {
            return {'default': 2};
        },
};

module.exports = definition;
```

**Comment by Rwin1234** [comment]
Thanks a lot! This works as my converter, I dont need to configure it myself, extend works, I just have to change the default endpoint as you indicated:

```javascript
const extend = require('zigbee-herdsman-converters/lib/extend');

module.exports = [
    {
        zigbeeModel: ['020B0B'],
        model: '020B0B',
        vendor: 'Fischer & Honsel',
        description: 'LED Wall lamp',
        extend: extend.light_onoff_brightness_colortemp_color(),
        endpoint: (device) => {
            return {'default': 2};
        },
    },
];
```
Two questions: would it be possible to detect this default endpoint 2 during the interview? I mean, its clear from where the clusters are, you can see them in the "Clusters" tab of Z2M frontend.
Secondly, how can we distinguish this lamp from the desk lamp that the other user has submitted as converter? The model number is the same. Again this could be resolved if the endpoint detection would be automatic.

Anyway, wifey is happy, lamp works.

**Comment by Koenkk** [comment]
Can yo provide the data/database.db entry of this device?

**Comment by Koenkk** [comment]
- I've fixed the controlling issue. 
Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
- I cannot do much about the OTA requests, z2m replies correctly but the device keeps spamming.
-

**Comment by Rwin1234** [comment]
Thanks a lot Koen! Indeed the device is behaving silly with the OTA requests. It suggests the manufacturer would offer OTA updates but I have no clue where to find them at the moment. Will try an email to Fischer and Honsel Germany.
