### ISSUE TITLE
Niko 552-721X2 Endpoints configuration error

### ISSUE THREAD

**Issue by nicotino2000** [Koenkk/zigbee-herdsman-converters#5476]
Hi,
I have just received a series of Niko 552-721X2 double switches and I found a few issues when try to use them in "uncoupled" mode. In the descriptor page it is stated that the device is using 2 endpoints for the 2 switches while going through debug mode it seems like the endpoint is unique.

Pressing switch 1
Debug 2023-02-12 12:39:09Received Zigbee message from 'Switch_sala_2', type 'attributeReport', cluster 'manuSpecificNiko2', data '{"switchAction":64}' from endpoint 1 with groupID 0
Info 2023-02-12 12:39:09MQTT publish: topic 'zigbee2mqtt/Switch_sala_2', payload '{"action":"single","action_l1":null,"action_l2":null,"led_enable":true,"led_enable_l1":true,"led_enable_l2":false,"led_state":"ON","led_state_l1":"OFF","led_state_l2":"ON","linkquality":255,"operation_mode":"unknown","operation_mode_l1":"decoupled","operation_mode_l2":"decoupled","state_l1":"ON","state_l2":"ON"}'

Pressing switch 2
Debug 2023-02-12 12:39:10Received Zigbee message from 'Switch_sala_2', type 'attributeReport', cluster 'manuSpecificNiko2', data '{"switchAction":16384}' from endpoint 1 with groupID 0
Info 2023-02-12 12:39:10MQTT publish: topic 'zigbee2mqtt/Switch_sala_2', payload '{"action_l1":null,"action_l2":null,"led_enable":true,"led_enable_l1":true,"led_enable_l2":false,"led_state":"ON","led_state_l1":"OFF","led_state_l2":"ON","linkquality":255,"operation_mode":"unknown","operation_mode_l1":"decoupled","operation_mode_l2":"decoupled","state_l1":"ON","state_l2":"ON"}'

looking at the configuration in niko.js:
const actionMap = {16: null, 64: 'single', 32: 'hold', 48: 'release'}; this works for switch 1

this should be something like
const actionMap = {16: null, 64: 'single_L1', 32: 'hold_L1', 48: 'release_L1', 4096: null, 16384: 'single_L2', 8192: 'hold_L2', 12288: 'release_L2'}; 

The same goes for the led implementation, currently it seems not possible to handle the 2 LEDs separately.
I am not a developer but I have the units already installed so I am glad to help fixing the issue.
Ciao

Nicola

**Comment by sjorge** [comment]
See https://github.com/Koenkk/zigbee2mqtt/issues/13737

There is also a test converter there but it doesnt seem to work 😑
