### ISSUE TITLE
Osram smart+ plug: warnings about haElectricalMeasurement, type 'devChange'

### ISSUE THREAD

**Issue by ovitters** [Koenkk/zigbee-herdsman-converters#549]
It seems that the newer Osram smart+ plugs provide power measurements.

From my log:
npm[804]:   zigbee2mqtt:warn 7/31/2019, 7:33:49 PM No converter available for 'AB3257001NJ' with cid 'haElectricalMeasurement', type 'devChange' and data '{"cid":"haElectricalMeasurement","data":{"activePower":28000}}'
npm[804]:   zigbee2mqtt:warn 7/31/2019, 7:33:49 PM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.

The 28000 is weird though, I don't think it's in Watt. I've also seen "400" (probably a different device). I do not have a power meter so I'm not sure how to contribute. Suggestion appreciated!

FYI, I did read the link. Looking at the existing code, it seems often something different is done for haElectricalMeasurement; though I might be mistaken.

**Comment by Koenkk** [comment]
This device always seems to report this value, AFAIK it doesn't support power measurements and this message should be ignored.
