### ISSUE TITLE
P7 coordinator firmware

### ISSUE THREAD

**Issue by joachim-lazaroms-isolectra** [Koenkk/zigbee-herdsman-converters#5502]
Hi,

When i create a zigbee coordinator, i prefer to use the LP___P-2 model over de R model. The launchepad P model seems low stock and i'm not sure if TI will produce new board soon. im wondering if there are plans to create coordinator firmware for the P7-4 model. This look the follow up model to me. Unfortunately there is no P7-2 model.

P7-4 [https://nl.mouser.com/ProductDetail/Texas-Instruments/LP-CC1352P7-4?qs=Rp5uXu7WBW8ko7Yt6PTsig%3D%3D](https://nl.mouser.com/ProductDetail/Texas-Instruments/LP-CC1352P7-4?qs=Rp5uXu7WBW8ko7Yt6PTsig%3D%3D)
P-2 [https://nl.mouser.com/ProductDetail/Texas-Instruments/LAUNCHXL-CC1352P-2?qs=w%2Fv1CP2dgqoV5fpcbCFzdg%3D%3D](https://nl.mouser.com/ProductDetail/Texas-Instruments/LAUNCHXL-CC1352P-2?qs=w%2Fv1CP2dgqoV5fpcbCFzdg%3D%3D)

Is the source code of the P model somewhere shared?

Thank you for your time.

Regards Joachim
Netherlands

**Comment by Koenkk** [comment]
As longs as the P7 chip is not used in well available USB adapters I will not make a firmware. If you want to compile a firmware yourself you can use https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_3.x.0/COMPILE.md as a base.
