### ISSUE TITLE
Schwaiger HAL300 - manufacturer name 'LDS' is NOT supported

### ISSUE THREAD

**Issue by JohnPaul2023** [Koenkk/zigbee-herdsman-converters#5530]
The LED Schwaiger HAL300, running with this name under Phoscon/Conbee,  is not recognized correctly.

I get following message:

Received message from unsupported device with Zigbee model 'HAL300' and manufacturer name 'LDS'
Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html

Gerätename                 0x00158d0001602313
Zuletzt gesehen            N/A
Verfügbarkeit                [Deaktiviert]
Geräte-Typ                    Router
Zigbee Modell               HAL300
Zigbee Hersteller           LDS
Unterstützungsstatus    Nicht unterstützt
Firmware-Datum           20160913-109
Firmware-Version          2.1
Interview erfolgreich     Wahr

May I have a FW problem, that the correct manufacturer is not recognized?

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by JohnPaul2023** [comment]
Thanks!
