### ISSUE TITLE
ZTH02 - WSD500A - Tuya T° sensor - No Data

### ISSUE THREAD

**Issue by nakedfoot** [Koenkk/zigbee-herdsman-converters#5560]
Hello,

I have 2 WSD500A T° and humidity sensor,
No problem to connect it with zigbee2mqtt. It seems to be supported (I see it in the Tuya.js).
But no data in json (only link quality).

I tried to add manually the converter, 
But no data neither.

I tried with ZTH01 (another sensor), it works fine. but ZTH02 didn't.

Did I miss something ?

Thx for helping

my converter file :

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require("zigbee-herdsman-converters/lib/tuya");

const definition = {
    // Since a lot of Tuya devices use the same modelID, but use different data points
    // it's usually necessary to provide a fingerprint instead of a zigbeeModel
    fingerprint: [
        {
            // The model ID from: Device with modelID 'TS0601' is not supported
            // You may need to add \u0000 at the end of the name in some cases
            modelID: 'TS0601',
            // The manufacturer name from: Device with modelID 'TS0601' is not supported.
            manufacturerName: '_TZE200_9yapgbuv'
        },
    ],
    model: 'WSD500A',
    vendor: 'TuYa',
    description: 'Temperature & humidity sensor',
    fromZigbee: [tuya.fz.datapoints, tuya.fz.gateway_connection_status,],
    toZigbee: [tuya.tz.datapoints],
    configure: tuya.configureMagicPacket,
    //onEvent: tuya.onEventSetTime, // Add this if you are getting no converter for 'commandMcuSyncTime'
   
    exposes: [e.temperature(), e.humidity(), tuya.exposes.batteryState(), e.battery_low()],
    meta: {
        tuyaDatapoints: [
            [1, 'temperature', tuya.valueConverter.divideBy10],
            [2, 'humidity', tuya.valueConverter.raw],
            [3, 'battery_state', tuya.valueConverter.batteryState],
            ],
        }
};

module.exports = definition;

**Comment by JerryLutor** [comment]
please, help. same problem .

**Comment by nakedfoot** [comment]
Problem solved here : https://github.com/Koenkk/zigbee2mqtt/discussions/16366#discussioncomment-5354527
