### ISSUE TITLE
TS011F _TZ3000_qeuvnohg converter

### ISSUE THREAD

**Issue by muusc** [Koenkk/zigbee-herdsman-converters#5565]
The tuya converter don't work correct for the device TS011F _TZ3000_qeuvnohg. This device needs polling to do power monitoring.
I have add this lines to the converter and now it works correct:
`options: [exposes.options.measurement_poll_interval()],
onEvent: tuya.onEventMeasurementPoll`

**Comment by Koenkk** [comment]
Can you provide the data/database.db entry of this device?

**Comment by muusc** [comment]
I'm not sure, if this is, what you are looking for:
`{"id":17,"type":"Router","ieeeAddr":"0x84b4dbfffeac2ef0","nwkAddr":29359,"manufId":4098,"manufName":"_TZ3000_qeuvnohg","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[0,3,4,5,6,1794,2820,1026,57344,57345],"outClusterList":[25,10],"clusters":{"57344":{"attributes":{"53251":"AAAA"}},"genBasic":{"attributes":{"65503":"��q+\u0016","65506":31,"65508":0,"65534":0,"modelId":"TS011F","manufacturerName":"_TZ3000_qeuvnohg","stackVersion":0,"dateCode":"","zclVersion":3,"appVersion":65,"powerSource":1}},"haElectricalMeasurement":{"attributes":{"acCurrentDivisor":1000,"acCurrentMultiplier":1,"rmsVoltage":226,"rmsCurrent":5708,"activePower":1249}},"seMetering":{"attributes":{"divisor":100,"multiplier":1,"currentSummDelivered":[0,262709]}},"genOnOff":{"attributes":{"32768":0,"onOff":1,"tuyaBacklightMode":0,"onTime":0,"offWaitTime":0,"moesStartUpOnOff":1,"tuyaBacklightSwitch":1}},"msTemperatureMeasurement":{"attributes":{"measuredValue":-630}},"manuSpecificTuya_3":{"attributes":{"53248":1,"53249":0,"53250":2674,"53251":15997,"53252":12491,"53253":3109,"powerOnBehavior":1,"switchType":0}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-522437996},"lastSeen":1678697455693,"defaultSendRequestWhen":"immediate"}`

**Comment by muusc** [comment]
I accidentally took the wrong account for this issue. This is related to my issue https://github.com/Koenkk/zigbee-herdsman-converters/pull/4907#event-7807427582

**Comment by muusc** [comment]
How should that work? If I remove the `_TZ3000_qeuvnohg`, than there will be no converter that handle this device.

**Comment by Koenkk** [comment]
Because all `TS011F` devices will be marked as supported in z2m 1.30.2

**Comment by muusc** [comment]
I have a problem to do this test, since I determine that changes of a connector configuration in the tuya.js file has no effect. OK, if I produce a syntax error, this will have an effect, but simple changes will be ignored on zigbee instance restart.
Because of this, I made my previously needed changes in an external converter.
Independed of that, this is what I try:
- remove my external converter
- remove the `_TZ3000_qeuvnohg` fingerprint from the tuya.js
- restart the zigbee instance
After this, the power monitoring of the device don't work. But maybe the reason is, that my changes on the tuya.js will be ignored.
