### ISSUE TITLE
Bosch Twinguard 'smoke sensitivity' convertSet bugged

### ISSUE THREAD

**Issue by rmi1974** [Koenkk/zigbee-herdsman-converters#5578]
Trying to change 'smoke sensitivity' setting of Bosch Twinguard devices has no effect in Home Assistant or zigbee2mqtt GUI.

Home Assistant logs tell:

```
2023-03-14 16:44:56.620 ERROR (MainThread) [homeassistant.components.mqtt.select] Invalid option for select.schlafzimmer_rauchmelder_sensitivity: 'LOW' (valid options: ['low', 'medium', 'high'])
2023-03-14 16:44:56.634 ERROR (MainThread) [homeassistant.components.mqtt.select] Invalid option for select.schlafzimmer_rauchmelder_sensitivity: 'MEDIUM' (valid options: ['low', 'medium', 'high'])
2023-03-14 16:45:14.317 ERROR (MainThread) [homeassistant.components.mqtt.select] Invalid option for select.schlafzimmer_rauchmelder_sensitivity: 'MEDIUM' (valid options: ['low', 'medium', 'high'])
```

Going a level lower, the same problem exists with zigbee2mqtt GUI. The selection in the device "exposes" tab is not retained. Click the selection "low", "medium", "high" .. the setting becomes black "selected". Switch to another tab, for example "bind". Switch back to "exposes" tab -  the selection is cleared. This does not happen with other fields, such as "heartbeat", "pre_alarm" etc. Their setting becomes permanent and reflected in UI:

Trying to figure out why it doesn't work lead me to this:

https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/bosch.js#L15
https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/bosch.js#L150
https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/bosch.js#L500

The following code snippet seems to be the cause:

```
...
// Twinguard
const smokeSensitivity = {
    'low': 3,
    'medium': 2,
    'high': 1,
};
...
    bosch_twinguard: {
        key: ['sensitivity', 'pre_alarm', 'self_test', 'alarm', 'heartbeat'],
        convertSet: async (entity, key, value, meta) => {
            if (key === 'sensitivity') {
                value = value.toUpperCase();
                const index = smokeSensitivity[value];
                await entity.write('manuSpecificBosch', {0x4003: {value: index, type: 0x21}}, boschManufacturer);
                return {state: {sensitivity: value}};
            }
```

The new value is converted to uppercase and then used as lookup key for the map to get the index value
But the map keys are all lowercase hence the lookup can't work?

Some device converters use this pattern:

```
 utils.validateValue(value, Object.keys( <map> ));
```

which probably would have caught this kind of bug.

**Comment by DerDreschner** [comment]
The `validateValue` call would have triggered another error message. I'm not sure if it would have triggered any error message e.g. when starting Z2M. But you're right, that's a little bit bugged. Will fix that this week.

**Comment by DerDreschner** [comment]
This issue is fixed since Z2M version 1.32.0 due to typescript refactorings from @Koenkk . Can you confirm that, @rmi1974 ?

**Comment by rmi1974** [comment]
I think so. At least I didn't see them anymore a few months ago (already being at 1.32.x+).

Side-note: Unfortunately I had to switch all Bosch TwinGuards from Z2M setup back to be paired with Bosch's own SH controller, effectively creating a second zigbee network again. All of them (five) started misbehaving after exactly one year being on Z2M network, around one month ago (November). They started making beeping sound every 45 secs and yellow light flashing (in Bosch speak: "there is a problem"). I couldn't figure it out why (new batteries, reset + re-pair few times). There was no firmware update either after connecting them to Bosch SHC again (latest device FW was Nov. 2022). They work fine with Bosch SHC now, being "silent" as they should but at the cost that I need to use a proprietary hub again, and having a second zigbee network :(

**Comment by DerDreschner** [comment]
Good to hear the issue really is solved! Bad, that the TwinGuard made problems with Z2M. Unfortunately, I don't have one to debug the issue any further. In case you're able to lend me one of your units, you can contact me at github-twinguard@dreschner.net.

Merry Christmas anyway! :christmas_tree:
