### ISSUE TITLE
Converter QOTO QT-05

### ISSUE THREAD

**Issue by werdy64** [Koenkk/zigbee-herdsman-converters#5580]
Dear Koenkk,

I have installed zigbee2mqtt according with the guide including frontend. I tried to pair QOTO water valve QT-05. Unfortunately this device was identified as "unsupported". When I tried to use zigbee-herdsman-converters/devices/qoto.js I've got a mistake. Have I to change these paths or create these folders which specified in this converter?
const fz = require('../converters/fromZigbee');
const exposes = require('../lib/exposes');
const tuya = require('../lib/tuya');

**Comment by rotilho** [comment]
Which manufacture name? I just created https://github.com/Koenkk/zigbee-herdsman-converters/pull/5591
