### ISSUE TITLE
Duplicate Model number 'Z111PL0H-1JX'

### ISSUE THREAD

**Issue by mikedm139** [Koenkk/zigbee-herdsman-converters#5590]
I was attempting to add support for my Woolley SA-028, US-style switch plug. It reports model number Z111PL0H-1JX and vendor 'SONOFF'. Upon adding it to the [sonoff.js](https://github.com/Koenkk/zigbee-herdsman-converters/pull/5589/files#diff-371be97b35202a0b01c5397ac28e33156275c238d29ce61d31fb1ed47797203a) and creating a pull request #5589, I was notified by a failing test that the model number was a duplicate. I see now that there is a [woolley.js](https://github.com/Koenkk/zigbee-herdsman-converters/blob/d2c37da6717dedafb1be8e879de3cb3e2b81fa23/devices/woolley.js#L6) in which it is listed.

It is my understanding that the SA-029 defined in the existing woolley.js is the EU version, whereas the SA-028 is the US version. Documentation also lists a model SA-030 which I suspect will have the same zigbee model number.
What is the best way to handle the different region devices using the same zigbee model number?

**Comment by Koenkk** [comment]
We cannot distinguish these devices, therefore rename the existing device to `SA-028/SA-029`

**Comment by mikedm139** [comment]
To confirm; that should be done in the woolley.js? Should anything extra be done to handle that fact that the SA-028 reports SONOFF as the vendor?

**Comment by Koenkk** [comment]
Yes, question: what vendor shows up in the data/database.db entry of this device?

**Comment by mikedm139** [comment]
I believe the relevant part of the database.db entry reads as follows (full entry hidden for conciseness).
<details>
  <summary>"manufId":4742, "manufName":"SONOFF", "powerSource":"Mains (single phase)","modelId":"Z111PL0H-1JX",</summary>

```json
{ 
  "id":13,
  "type":"Router",
  "ieeeAddr":"0x00124b002579875d",
  "nwkAddr":25261,
  "manufId":4742,
  "manufName":"SONOFF",
  "powerSource":"Mains (single phase)",
  "modelId":"Z111PL0H-1JX",
  "epList":[1,13,242],
  "endpoints":{
    "1":{
      "profId":260,"epId":1,"devId":256,"inClusterList":[0,3,4,5,6,64599,64672],"outClusterList":[25],
      "clusters":{
        "genOnOff":{"attributes":{"onOff":0}},
        "genBasic":{
          "attributes":{
            "modelId":"Z111PL0H-1JX",
            "manufacturerName":"SONOFF",
            "powerSource":1,
            "zclVersion":3,
            "hwVersion":1,
            "dateCode":"20211223",
            "swBuildId":"1.0.1"
          }
        }
      },
      "binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c83671","endpointID":1}],
      "configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0}],
      "meta":{}
    },
    "13":{
      "profId":49246,
      "epId":13,
      "devId":57694,
      "inClusterList":[4096],
      "outClusterList":[4096],
      "clusters":{},
      "binds":[],
      "configuredReportings":[],
      "meta":{}
    },
    "242":{
      "profId":41440,
      "epId":242,
      "devId":97,
      "inClusterList":[],
      "outClusterList":[33],
      "clusters":{},
      "binds":[],
      "configuredReportings":[],
      "meta":{}
    }
  },
  "hwVersion":1,
  "dateCode":"20211223",
  "swBuildId":"1.0.1",
  "zclVersion":3,
  "interviewCompleted":true,
  "meta":{"configured":1466202208},
  "lastSeen":1679178862298,
  "defaultSendRequestWhen":"immediate"
}
```
</details>

The packaging/instructions mention pairing using the eWeLink app. It was sold as "Woolley" brand but the only branding is a sticker on the box and it reports SONOFF as the manufacturer name. I'm happy to add it wherever you think it makes most sense.

**Comment by Koenkk** [comment]
Then it can be moved to SONOFF.js
