### ISSUE TITLE
Add support for NUE 3a 4 gang light switch model LXN-4S27LX1.0

### ISSUE THREAD

**Issue by chris-chensy** [Koenkk/zigbee-herdsman-converters#5592]
I found there is a missing support for the NUE 3a 4 gang model in zigbee2mqtt. I believe it is different from the 4-gang scene switch but likely to be similar with the 3gang model. The photo looks like this.

![](https://m.media-amazon.com/images/I/51fCl5YkTGL._AC_SL1024_.jpg)

`{
        zigbeeModel: ['LXN-4S27LX1.0'],
        model: 'HGZB-4S',
        vendor: 'Nue / 3A',
        description: 'Smart light switch - 4 gang v2.0',
        extend: extend.switch(),
        exposes: [e.switch().withEndpoint('top'), e.switch().withEndpoint('center_1'), e.switch().withEndpoint('center_2'), e.switch().withEndpoint('bottom')],
        endpoint: (device) => {
            return {'top': 1, 'center_1': 2, 'center_2': 3, 'bottom': 4};
        },
        meta: {multiEndpoint: true},
        configure: async (device, coordinatorEndpoint, logger) => {
            await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['genOnOff']);
            await reporting.bind(device.getEndpoint(2), coordinatorEndpoint, ['genOnOff']);
            await reporting.bind(device.getEndpoint(3), coordinatorEndpoint, ['genOnOff']);
            await reporting.bind(device.getEndpoint(4), coordinatorEndpoint, ['genOnOff']);
        },
    }`

I didn't test the configuration above. Please help.

**Comment by Koenkk** [comment]
Can you provide the data/database.db entry of this device?

**Comment by chris-chensy** [comment]
here it is.
`{"id":8,"type":"Router","ieeeAddr":"0x3ed00600e00bfdb0","nwkAddr":22841,"manufId":0,"manufName":"3A Smart Home DE","powerSource":"Mains (single phase)","modelId":"LXN-4S27LX1.0","epList":[1,2,3,4],"endpoints":{"1":{"profId":49246,"epId":1,"devId":0,"inClusterList":[0,4,3,6,5,4096,8],"outClusterList":[0],"clusters":{"genBasic":{"attributes":{"modelId":"LXN-4S27LX1.0","manufacturerName":"3A Smart Home DE"}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":49246,"epId":2,"devId":0,"inClusterList":[0,4,3,6,5,4096,8],"outClusterList":[0],"clusters":{"genBasic":{"attributes":{}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":49246,"epId":3,"devId":0,"inClusterList":[0,4,3,6,5,4096,8],"outClusterList":[0],"clusters":{"genBasic":{"attributes":{}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[],"configuredReportings":[],"meta":{}},"4":{"profId":49246,"epId":4,"devId":0,"inClusterList":[0,4,3,6,5,4096,8],"outClusterList":[0],"clusters":{"genBasic":{"attributes":{}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":1,"hwVersion":1,"dateCode":"20220526","swBuildId":"1.2.0","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1679722855124,"defaultSendRequestWhen":"immediate"}`

**Comment by Koenkk** [comment]
Added, thanks!
