### ISSUE TITLE
_TZ3000_qeuvnohg switch entity is inverted

### ISSUE THREAD

**Issue by beaver1983467** [Koenkk/zigbee-herdsman-converters#5608]
I purchased Tongou TO-Q-SY1-JZT with power monitoring from AliExpress.
The device is paired fine as _TZ3000_qeuvnohg (Din smart relay (with power monitoring)) and it seems like power monitoring is in general working, however when I change the state of switch in HA it is changed on the load (the lamp-load of the device changes the state from off to on or vice versa) and stays in a new state, but the state inside z2m goes back to previous, so it is reverted from the actual state of the load.
As an example for the easier understanding: the lamp (load) is off, when I press "on" in z2m inside HA it physically turns on the lamp and this state is retained physically, in the frontend it changes the state to on for the second and than get back to off.
Also it seems like the power monitoring in z2m is only working when the state of the switch is on, as when switch wrongfully get back to off it zeroes power and current even though the load is on and consumes electricity. 

https://user-images.githubusercontent.com/81297701/227641308-9f6243b7-19ec-48ef-ad2a-46396483ba08.mp4

This is illustrated on the attached video. The device itself is fine, at least in Tuya app through Tuya gateway it works fine, so I assume the problem is in the convertor somewhere. 
Can you please to resolve this issue. If any data is needed from my side let me know.
Thanks.
Volodymyr

**Comment by beaver1983467** [comment]
I made a few tests. After disconnecting the device from z2m, than connecting to native gateway and choosing in the settings Memory option ON, then deleting with wiping the data from Tuya app and reconnect to z2m this device switch works fine, unless you choose any option other than installed in "power_outage_memory". When you click for ANY option there (on, off or restore) the behavior of switch is again reverted (when the load is on the status of the switch is off and vice versa, in both states power monitoring is not working). I am not sure what causes this but that is how it works for me, assume selecting the option somehow affects behavior of the switch. I don't have any other devices using the same converter so not sure if the problem is device specific or only for my device. If I can further help in any way to resolve this issue - let me know. 
UPD: As a temporary ductaping if you need to restore the state after electricity outage I found the following solution: connect device to z2m, click on restore option, then enter the pairing mode by button on device without deleting device from z2m, connect the native tuya gateway and select Settings -> Memory -> On in device plugin. After that - Settings -> Delete -> Wipe data. Enter pairing mode again and make sure device reconnects to z2m. After that the power_outage_memory will stay the same as chosen on step 1, however switch will work properly, unless you change it again.

**Comment by omolko** [comment]
Hello I have a similar problem. when I click on one of the 3 buttons then it fires automatically the two others. Did you get this kind of problem?

https://user-images.githubusercontent.com/20817709/233796537-e356200c-18cc-43bf-a439-af8891abc0ab.mov

**Comment by beaver1983467** [comment]
> Hello I have a similar problem. when I click on one of the 3 buttons then it fires automatically the two others. Did you get this kind of problem?
> Enregistrement.de.l.ecran.2023-04-22.a.16.58.20.mov

It seems that you have some kind of 3 channel relay, mine has only 1. Does your manID = _TZ3000_qeuvnohg?
