### ISSUE TITLE
Missing support for KnockautX Smoke sensor "SMOAL024" 

### ISSUE THREAD

**Issue by pgfeller** [Koenkk/zigbee-herdsman-converters#5609]
The [KnockautX SMOAL024](https://www.brelag.com/shop/smoal024-knockautx-rauchwarnmelder-4714#attr=) is a smoke detector based on the popular [tuya stack](https://developer.tuya.com/en) and integration should not be too dificulat as there is already a freamework for integration of such devices present.

According to the manfuctuer/distributor the following data points are available:
![dp](https://user-images.githubusercontent.com/9395643/227711170-d190dad0-7a5c-4421-b444-e576401beed3.PNG)

As support for a new devices does not touch the zigbee2mqtt core code I decided to create the issue here in the converters repo. Let me know if this is the wrong place.

As the additional of a new device is well documented I'll give it a go myself - but would like to create the issue here for tracking purpose in case someone else needs support for this device.

**Comment by pgfeller** [comment]
I created a fork and did setup the IDE on Microsoft Windows 10 using VS-Code; but if I execute the tests on the un-modified code I get an error; one test fails:

![image](https://user-images.githubusercontent.com/9395643/227719756-1e2f49df-6658-482a-bf46-ba5d00fe95db.png)

![image](https://user-images.githubusercontent.com/9395643/227719790-c7031e43-55ec-4705-b3ee-8247d6adc4c2.png)

Is this a known problem - or an issue with my environment setup?

**Comment by Koenkk** [comment]
If you have the latest checkout, test should pass. Does line 305 of test/colortemp_range_missing_allowed.txt contain `rgbw2.zbee27`?

**Comment by pgfeller** [comment]
Yes - it does:
![image](https://user-images.githubusercontent.com/9395643/227764310-b5627c56-8982-4da5-8e17-279a47251af7.png)

These are the latest commits I have in my branch:
![image](https://user-images.githubusercontent.com/9395643/227764363-3d3388c5-8789-458b-9afc-12998328670c.png)

I'm working on windows - should not be related; but just in case ...

**Comment by pgfeller** [comment]
Strange - I also get a failing CI when I check-in the code; I'm not aware of any changes that could cause this ...

https://github.com/Koenkk/zigbee-herdsman-converters/actions/runs/4524790173/jobs/7968846911?pr=5613

**Comment by Koenkk** [comment]
Then ignore this test case, maybe something windows related.
