### ISSUE TITLE
new device 2 gang dimmer LoraTap Zigbee model 'TS0601' and manufacturer name '_TZE200_gwkapsoq'

### ISSUE THREAD

**Issue by lobernat** [Koenkk/zigbee-herdsman-converters#5669]
Hi, 
Following the instructions of https://www.zigbee2mqtt.io/advanced/support-new-devices/02_support_new_tuya_devices.html and copying all parameters of the deviecs _TZE200_fjjbhx9d', '_TZE200_e3oitdyu I've could managed to add this 2 gang dimmer 
https://www.aliexpress.com/item/1005005035307347.html?spm=a2g0o.productlist.main.3.10a9DrFCDrFCH7&algo_pvid=90ee85b7-7afc-428e-ac8c-7300737bbdb4&algo_exp_id=90ee85b7-7afc-428e-ac8c-7300737bbdb4-1&pdp_npi=3%40dis%21EUR%2127.53%2113.76%21%21%21%21%21%40211be72e16816317758755712d07b6%2112000031408989337%21sea%21ES%21731801094&curPageLogUid=ic2cdgjs12nN

I guess if some one add this model "_TZE200_gwkapsoq" on the line 1313 it will work out of the box
        fingerprint: tuya.fingerprint('TS0601', ['_TZE200_fjjbhx9d', '_TZE200_e3oitdyu']),

Regards

**Comment by Koenkk** [comment]
This has already been done and the device will be supported out-of-the-box in the next release.

https://github.com/Koenkk/zigbee-herdsman-converters/blob/d2f4be34ac5b3dc4a95ffe4e04c555147f7e25a9/devices/tuya.js#L1313
