### ISSUE TITLE
RGBW LED dimmer HOMA1001: No control of RGB LEDs

### ISSUE THREAD

**Issue by Stefan-3** [Koenkk/zigbee-herdsman-converters#5680]
# Issue
It's not possible to control the RGB LEDs when using the RGBW LED dimmer HOMA1001 in RGBW mode. Controlling the white LEDs is fine but there is are no datapoints in IoBroker objects to control the RGB LEDs.

# Corresponding issues
Several people in issue
[https://github.com/Koenkk/zigbee2mqtt/issues/3594](url)
reported that the modifications of
/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/shenzhen_homa.js
made by gitjho (commented on Nov 22, 2021) are working fine (with RGBW stripe and DIP switches on HOMA1001 set to RGBW (D1=1, D2=1)).
Unfortunately I don't get a datapoint object with the modifications of gitjho to control the RGB LEDs. I only can control the white LEDs. Thus, I was quite sure it's a matter of the IoBroker zigbee adapter respectively the file
/opt/iobroker/node_modules/iobroker.zigbee/lib/devices.js
So I created the issue
[https://github.com/ioBroker/ioBroker.zigbee/issues/1721#issue-1668832202](url)
but @arteck says this is a converter issue and asked me to create a new issue for the converter. Here it is ;-)
Has someone an idea how to control the RGB LEDs (with HOMA1001 and IoBroker)?

**Comment by Stefan-3** [comment]
Issue
https://github.com/ioBroker/ioBroker.zigbee/issues/1721#issue-1668832202
was closed as it's no issue of the IoBroker zigbee adapter but of the herdsman converter. Thus, the issue of the adapter was closed but the issue
https://github.com/ioBroker/ioBroker.zigbee/issues/1721#issue-1668832202
is still open.

**Comment by Stefan-3** [comment]
The IoBroker zigbee adapter has the possibility to move zigbee devices to an "exclude group". By moving the device "HOMA1001" to this exclude group, it's possible to create IoBroker datapoints to control the RGB and white LEDs as wanted (brightness_rgb, brightness_white, ...):
![image](https://user-images.githubusercontent.com/124084681/233435119-9de95743-93a4-4e96-ac5f-96a972c1443c.png)
But as the HOMA1001 is a quite popular LED dimmer, it should be useable as all other zigbee devices, this means without such handmade workarounds.

**Comment by Stefan-3** [comment]
I've modified the converter (shenzhen_homa.js) and now it supports the HOMA1001 with all its 4 DIP switch positions :-)

[HOMA1001.zip](https://github.com/Koenkk/zigbee-herdsman-converters/files/11415333/HOMA1001.zip)

**Comment by Koenkk** [comment]
@Stefan-3 could you make a PR?

**Comment by Stefan-3** [comment]
@Koenkk I need some help for the PR: The PR asks for temperature range. HOMA1001 is a LED driver without a specific LED stripe.  So, from my understanding the colour temperature is no capability of the HOMA1001.

**Comment by Koenkk** [comment]
Let's continue in https://github.com/Koenkk/zigbee-herdsman-converters/pull/5728
