### ISSUE TITLE
Support for Ynoa LA-A60FD-CCT

### ISSUE THREAD

**Issue by gizmocuz** [Koenkk/zigbee-herdsman-converters#5698]
Hello,

I am a bit in the dark with adding support for this device...

I managed to create a converter and found a image matching the exact device (docs/devices/3802968.jpg)

Do I need to add this to zigbee-herdsman-converters-master\devices\ynoa.js and docs/devices/ZBT-CCTfilament-D0001.md that's it for a PR?
How do I match this with the device image? Or is this only needed for the documentation?

This is the converter that's working: (I have read the min/max temp range)

```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const utils = require('zigbee-herdsman-converters/lib/utils');
const globalStore = require('zigbee-herdsman-converters/lib/store');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['ZBT-CCT-LA-A60FD'],
    model: 'ZBT-CCTfilament-D0001',
    vendor: 'LDS',
    description: 'Ynoa Smart Led CCT LA-A60FD',
    extend: extend.light_onoff_brightness_colortemp({colorTempRange: [250, 454]}),
};

module.exports = definition;
```

It seems that there is a entry for a 'Effect', but this does nothing, How to remove this?

**Comment by Koenkk** [comment]
> Do I need to add this to zigbee-herdsman-converters-master\devices\ynoa.js and docs/devices/ZBT-CCTfilament-D0001.md that's it for a PR?

Yes, next to the `.md`. you also need to add a 150x150 jpg picture to https://github.com/Koenkk/zigbee2mqtt.io/tree/master/public/images/devices

> It seems that there is a entry for a 'Effect', but this does nothing, How to remove this?

Use: 
`extend: extend.light_onoff_brightness_colortemp({colorTempRange: [250, 454], disableEffect: true}),`


Regarding the model (`ZBT-CCTfilament-D0001`), I do not get any results when googling on it, please use the model listed on the product site/device itself.

**Comment by gizmocuz** [comment]
Thanks for the explanations..

Do I need to add a new jpg/picture or can I use an already existing picture (3802968.jpg) that looks exactly like on the box?

About 'model', I assume the converter script matches the device by vendor/model, and the field zigbeeModel is user defined?

In the web gui it displays LDS/ZBT-CCTfilament-D0001

![image](https://user-images.githubusercontent.com/2265299/235340102-62939fb9-0c05-4833-a471-19f71e51d312.png)

The item itself (on the box of the bulb) is called LA-A60FD-CCT

In the  zigbee-herdsman-converters\devices\ynoa.js file, for model they used the barcode ID on the box, which is in this case 8718801528204, which seems to be using in the Netherlands only (if you google for the number, you will find some websites)

It's still unclear what field I have to use where.... 
- How does it match the Manufacturer / Model in the GUI to the config files
- The box brand says Ynoa, in the GUI it says LDS, but I think we need to add this to the ynoa.js file, if this ok?

```
    {
        zigbeeModel: ['ZBT-CCTfilament-D0001'],
        model: '8718801528204',
        vendor: 'Ynoa',
        description: 'Smart LED E27 CCT',
        extend: extend.light_onoff_brightness_colortemp({colorTempRange: [250, 454]}, disableEffect: true),
    },

```

- How does it match the right documentation, should ik create a file ZBT-CCTLight-A60FD.md ?
The file says it is doxy generated, is this something we should do and how?

Probably LDS stands for Leedarson, what's with the ZBT in the ynoa.js file? That was the reason I used it as well

(Just trying to understand things as I might can contribute support for other new devices in the feature)
(But it might be easier if you add support for it, but I would like to see what's changed 😎)

**Comment by Koenkk** [comment]
- The picture should be called `8718801528204.jpg`, markdown file `8718801528204.md` (but no need to add this manually, it will be generated automatically). The match is made based on the `model`.
- The converter looks good, lets add it to `ynao.js`

**Comment by gizmocuz** [comment]
Done, made two PR's

**Comment by Koenkk** [comment]
Great! Assuming this can be closed now.
