### ISSUE TITLE
Please add new device "TuYa TS0601_smart_air_house_keeper"

### ISSUE THREAD

**Issue by exaware** [Koenkk/zigbee-herdsman-converters#5709]
I don't think the values are realistic. My CO2 value is always around 360ppm, even in the bedroom before airing in the morning. That can't be right? I suspect that the conversion is incorrect.

**Comment by Eales** [comment]
Hello! If you have a Tuya gateway, you can check if the readings are different. Unfortunately, my similar device does not have a carbon dioxide (CO2) monitoring feature. However, this value is often calculated based on data from other sensors, such as VOC.
