### ISSUE TITLE
Osram smart plug "Device with modelID 'Plug Z3' is not supported."

### ISSUE THREAD

**Issue by Matten-Matten** [Koenkk/zigbee-herdsman-converters#572]
Ich kann machen was ich will ich bekomme die 4 neuen Osram Smartplugs nicht angelernt! Bitte um Hilfe.

**Comment by Matten-Matten** [comment]
in der **_names.json_** tauchen die plugs dann so auf:

```
  "xxxxxxxxxxxx": {
    "name": "LEDVANCE Plug 4",
    "epDesc": [
      {
        "profId": 260,
        "epId": 1,
        "devId": 266,
        "inClusterList": [
          0,
          3,
          4,
          5,
          6,
          2821,
          4096,
          64527
        ],
        "outClusterList": [
          25
        ]
      },
      {
        "profId": 41440,
        "epId": 242,
        "devId": 97,
        "inClusterList": [],
        "outClusterList": [
          33
        ]
      }
    ],
    "type": "Router",
    "ieeeAddr": "xxxxxxxxxxxx",
    "nwkAddr": 4949,
    "manufId": 4489,
    "manufName": "LEDVANCE",
    "powerSource": "Mains (single phase)",
    "modelId": "Plug Z3",
    "epList": [
      1,
      242
    ],
    "status": "offline",
    "joinTime": null,
    "ts": 1566210550234
  }
```

**Comment by Riedies** [comment]
Hallo, ich habe leider das gleiche Problem, 
Modell Osram Plug = AB3257001NJ funktioniert ohne Problem, 
Modell Osram Plug = Plug Z3 funktioniert nicht, meldet  ->>  modelID 'Plug Z3' is not supported.

Gibt es hier eine Lösung oder ist diese Hardware nicht mehr kompatibel?

**Comment by Matten-Matten** [comment]
ich musste aber folgendes in der **_device.js_** hinzufügen, damit sie funktionieren:

```
{
        zigbeeModel: ['Plug Z3'],
        model: 'AC10691',
        description: 'Smart+ plug',
        supports: 'on/off',
        vendor: 'LEDVANCE',
        fromZigbee: [fz.ignore_onoff_change, fz.state],
        toZigbee: [tz.on_off],
        configure: (ieeeAddr, shepherd, coordinator, callback) => {
            const device = shepherd.find(ieeeAddr, 3);
            const cfg = {direction: 0, attrId: 0, dataType: 16, minRepIntval: 0, maxRepIntval: 1000, repChange: 0};
            const actions = [
                (cb) => device.bind('genOnOff', coordinator, cb),
                (cb) => device.foundation('genOnOff', 'configReport', [cfg], foundationCfg, cb),
            ];

            execute(device, actions, callback);
        },
    },
```

und in der **_fromZigbee.js_** folgendes:
```
	// LEDVANCE
	AC10691_on: {
        cid: 'genOnOff',
        type: 'cmdOn',
        convert: (model, msg, publish, options) => {
            return {action: 'on'};
        },
    },
    AC10691_off: {
        cid: 'genOnOff',
        type: 'cmdOff',
        convert: (model, msg, publish, options) => {
            return {action: 'off'};
        },
    },
	//
```

###########################################################################

**Comment by Riedies** [comment]
Super,
danke für die schnelle Antwort, jetzt funktioniert bei mir auch dieser Osram Plug 

Kleiner Tipfehler oben, bei mir ist es die Datei devices.js

**Comment by MyNameIsRatchet** [comment]
Wäre super wenn man das mit in zukünftige Versionen übernehmen würde...

**Comment by Moeinator** [comment]
Habe 8 LEDVance Plugs. Leider bekomme ich sie nur als Unbekanntes Gerät eingebunden. Bin Relativ neu wohin muss ich die Sachen die oben erwähnt sind hinkopieren ? Gibt es dort vielleicht eine fertige Datei zum Austausch ? Würde mich auf schnelle Antwort freuen

**Comment by Matten-Matten** [comment]
Das ist schon behoben worden!
Probier's mal indem du denen z-stack also den Stick einmal aus dem USB heraus ziehst dann wieder ein steckst so dass er sich neu verbindet und dann Versuch i Steckdose an zu lernen das dauert manchmal eine ganze Weile bis endlich auch die ganzen Werte gefunden werden anfangs steht da immer unbekannt. Das ganze würde ich mit jedem einzelnen Gerät so durchführen. Und ja es ist leider sehr aufwendig so, soll aber nur bei diesem neuen Osram Plug sein die anderen Geräte sind wohl nicht so zickig

**Comment by Moeinator** [comment]
Also der Anlernprozess geht relativ schnell. Danach wird mir der Plug als Z3 mit ? Angezeigt mehr passiert nicht. In der Ordnerstruktur findet man auch den Plug Nicht als Ordner sondern als eine Datei. Und mehr passiert dort leider nicht.

**Comment by Moeinator** [comment]
So sieht das ganze aus

![42E40C93-B275-47E3-B17A-511A9FBD247F](https://user-images.githubusercontent.com/58535071/70387312-0b1cf700-19a4-11ea-9403-d89f5c4459c7.png)

![43F64699-34F6-4E27-83FC-7230F5C026F2](https://user-images.githubusercontent.com/58535071/70387313-0bb58d80-19a4-11ea-8670-6898dad336f9.png)

**Comment by Matten-Matten** [comment]
Wie genau das in iobroker funktioniert weiß ich leider nicht. Ich nutze das in nodered

**Comment by Smiggel** [comment]
Same here. I have a plug here too. It pairs, but then the problem starts. I have a good connection from the coordinator to the plug (signal is 200+) but back it's 0. Most of the time the plug also does not respond to the on/off call. 

According to Zigbee2mqtt the powerplug is registered as a Osram smartplug +.

When I connect it to my hue bridge it shows up as a Ledvance Z3.

**Comment by P-Verbrugge** [comment]
Same issue here. According to the device support list, it should be supported. However, the image that is displayed looks different then the plug itself.

Also when connecting the plug to my hue bridge, I see it as a Ledvance Z3 and not as an Osram.

**Comment by Koenkk** [comment]
@P-Verbrugge can you share your `database.db`? (and first make sure you are on the zigbee2mqtt latest dev).

**Comment by tdn131** [comment]
I also have problems with the new AC10691. I run the latest dev as per 9 december. When I try pairing, nothing of the AC10691 is shown. It doesn't recognize it. When pairing with hue, I had no problems.

zigbee2mqtt:info 2019-12-09 18:33:08: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.7.1+dev","commit":"bcf79a7","coordinator":{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}},"log_level":"debug","permit_join":true}'

(Also the network performance of AC10691 in Hue is worse then the previous Osram plug)

**Comment by P-Verbrugge** [comment]
> @P-Verbrugge can you share your `database.db`? (and first make sure you are on the zigbee2mqtt latest dev).

@Koenkk I will share it somewhere this weekend.

**Comment by P-Verbrugge** [comment]
@Koenkk I have just paired the plug again. Here is the output during paring:
`zigbee2mqtt:info  2019-12-13T09:15:56: Device '0xf0d1b800001345e6' joined
zigbee2mqtt:info  2019-12-13T09:15:56: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":{"friendly_name":"0xf0d1b800001345e6"}}'
zigbee2mqtt:info  2019-12-13T09:15:56: Starting interview of '0xf0d1b800001345e6'
zigbee2mqtt:info  2019-12-13T09:15:56: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"0xf0d1b800001345e6"}}'
zigbee2mqtt:info  2019-12-13T09:15:57: MQTT publish: topic 'homeassistant/switch/0xf0d1b800001345e6/switch/config', payload '{"payload_off":"OFF","payload_on":"ON","value_template":"{{ value_json.state }}","command_topic":"zigbee2mqtt/0xf0d1b800001345e6/set","state_topic":"zigbee2mqtt/0xf0d1b800001345e6","name":"0xf0d1b800001345e6_switch","unique_id":"0xf0d1b800001345e6_switch_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0xf0d1b800001345e6"],"name":"0xf0d1b800001345e6","sw_version":"Zigbee2mqtt 1.7.1","model":"Smart+ plug (AC10691)","manufacturer":"OSRAM"},"availability_topic":"zigbee2mqtt/bridge/state"}'
zigbee2mqtt:info  2019-12-13T09:15:57: MQTT publish: topic 'homeassistant/sensor/0xf0d1b800001345e6/linkquality/config', payload '{"unit_of_measurement":"-","value_template":"{{ value_json.linkquality }}","state_topic":"zigbee2mqtt/0xf0d1b800001345e6","json_attributes_topic":"zigbee2mqtt/0xf0d1b800001345e6","name":"0xf0d1b800001345e6_linkquality","unique_id":"0xf0d1b800001345e6_linkquality_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0xf0d1b800001345e6"],"name":"0xf0d1b800001345e6","sw_version":"Zigbee2mqtt 1.7.1","model":"Smart+ plug (AC10691)","manufacturer":"OSRAM"},"availability_topic":"zigbee2mqtt/bridge/state"}'
zigbee2mqtt:info  2019-12-13T09:15:57: Successfully interviewed '0xf0d1b800001345e6', device has successfully been paired
zigbee2mqtt:info  2019-12-13T09:15:57: Device '0xf0d1b800001345e6' is supported, identified as: OSRAM Smart+ plug (AC10691)
zigbee2mqtt:info  2019-12-13T09:15:57: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0xf0d1b800001345e6","model":"AC10691","vendor":"OSRAM","description":"Smart+ plug","supported":true}}'
zigbee2mqtt:info  2019-12-13T09:15:57: Configuring '0xf0d1b800001345e6'
zigbee2mqtt:info  2019-12-13T09:15:58: Succesfully configured '0xf0d1b800001345e6'`

This is how my database.db looks like:
``

**Comment by P-Verbrugge** [comment]
@Koenkk I just paired the plug again. I use Zigbee2Mqtt 1.7.1 on HomeAssistant:

This is the output during paring. The plug is about 3 meters away from the coordinator:
> zigbee2mqtt:info  2019-12-13T09:28:29: Device '0xf0d1b800001345e6' joined
zigbee2mqtt:info  2019-12-13T09:28:29: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":{"friendly_name":"0xf0d1b800001345e6"}}'
zigbee2mqtt:info  2019-12-13T09:28:29: Starting interview of '0xf0d1b800001345e6'
zigbee2mqtt:info  2019-12-13T09:28:29: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"0xf0d1b800001345e6"}}'
zigbee2mqtt:info  2019-12-13T09:28:32: Successfully interviewed '0xf0d1b800001345e6', device has successfully been paired
zigbee2mqtt:info  2019-12-13T09:28:32: Device '0xf0d1b800001345e6' is supported, identified as: OSRAM Smart+ plug (AC10691)
zigbee2mqtt:info  2019-12-13T09:28:32: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0xf0d1b800001345e6","model":"AC10691","vendor":"OSRAM","description":"Smart+ plug","supported":true}}'
zigbee2mqtt:info  2019-12-13T09:28:32: Configuring '0xf0d1b800001345e6'
zigbee2mqtt:info  2019-12-13T09:28:33: Succesfully configured '0xf0d1b800001345e6'
zigbee2mqtt:info  2019-12-13T09:28:44: MQTT publish: topic 'zigbee2mqtt/0xf0d1b800001345e6', payload '{"state":"OFF","linkquality":0}'

This is what my database looks like:

> {"id":1,"type":"Coordinator","ieeeAddr":"0x00124b0014b92997","nwkAddr":0,"manufId":0,"epList":[1,2,3,4,5,6,8,11,110],"endpoints":{"1":{"profId":260,"epId":1,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]},"2":{"profId":257,"epId":2,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]},"3":{"profId":261,"epId":3,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]},"4":{"profId":263,"epId":4,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]},"5":{"profId":264,"epId":5,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]},"6":{"profId":265,"epId":6,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]},"8":{"profId":260,"epId":8,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]},"11":{"profId":260,"epId":11,"devId":1024,"inClusterList":[],"outClusterList":[1280],"clusters":{},"binds":[]},"110":{"profId":260,"epId":110,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]}},"interviewCompleted":false,"meta":{}}
{"id":2,"type":"Router","ieeeAddr":"0x00124b0014b940c7","nwkAddr":25009,"manufId":4447,"manufName":"LUMI","powerSource":"Mains (single phase)","modelId":"lumi.router","epList":[8],"endpoints":{"8":{"profId":260,"epId":8,"devId":256,"inClusterList":[0,6],"outClusterList":[0,6],"clusters":{"genBasic":{"attributes":{"modelId":"lumi.router","manufacturerName":"LUMI","powerSource":1,"zclVersion":1,"hwVersion":1,"dateCode":"2018-09-26"}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[]}},"hwVersion":1,"dateCode":"2018-09-26","zclVersion":1,"interviewCompleted":true,"meta":{}}
{"id":3,"ieeeAddr":"0x00158d0003029b0a","nwkAddr":46869,"epList":[1],"endpoints":{"1":{"epId":1,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]}},"interviewCompleted":false,"meta":{}}
{"id":4,"type":"EndDevice","ieeeAddr":"0x00158d0003029b0a","nwkAddr":50287,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_motion.aq2","epList":[1],"endpoints":{"1":{"epId":1,"inClusterList":[],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"65281":{"1":2995,"3":23,"4":5032,"5":87,"6":[0,32],"10":25009,"11":6,"100":0},"modelId":"lumi.sensor_motion.aq2","appVersion":5}},"msIlluminanceMeasurement":{"attributes":{"measuredValue":39}},"msOccupancySensing":{"attributes":{"occupancy":1}},"msTemperatureMeasurement":{"attributes":{"measuredValue":2309}},"msRelativeHumidity":{"attributes":{"measuredValue":7060}},"msPressureMeasurement":{"attributes":{"16":10012,"20":-1,"measuredValue":1001}}},"binds":[]}},"appVersion":5,"interviewCompleted":true,"meta":{}}
{"id":5,"type":"EndDevice","ieeeAddr":"0x00158d0003058ec0","nwkAddr":24399,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_motion.aq2","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":263,"inClusterList":[0,65535,1030,1024,1280,1,3],"outClusterList":[0,25],"clusters":{"msIlluminanceMeasurement":{"attributes":{"measuredValue":48}},"msOccupancySensing":{"attributes":{"occupancy":1}},"genBasic":{"attributes":{"65281":{"1":3005,"3":25,"4":5032,"5":66,"6":[0,3],"10":25009,"11":33,"100":0}}}},"binds":[]}},"appVersion":5,"interviewCompleted":true,"meta":{}}
{"id":6,"type":"EndDevice","ieeeAddr":"0x00158d0002320b4d","nwkAddr":6842,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.weather","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":24321,"inClusterList":[0,3,65535,1026,1027,1029],"outClusterList":[0,4,65535],"clusters":{"msTemperatureMeasurement":{"attributes":{"measuredValue":1889}},"msRelativeHumidity":{"attributes":{"measuredValue":4518}},"msPressureMeasurement":{"attributes":{"16":9707,"20":-1,"measuredValue":970}},"genBasic":{"attributes":{"65281":{"1":2905,"4":17320,"5":62,"6":[0,1],"10":25009,"100":1907,"101":4600,"102":97056},"modelId":"lumi.weather","manufacturerName":"LUMI","powerSource":3,"zclVersion":1,"appVersion":3,"stackVersion":2,"hwVersion":30,"dateCode":"20161129","swBuildId":"3000-0001"}}},"binds":[]}},"appVersion":3,"stackVersion":2,"hwVersion":30,"dateCode":"20161129","swBuildId":"3000-0001","zclVersion":1,"interviewCompleted":true,"meta":{}}
{"id":7,"type":"EndDevice","ieeeAddr":"0x00158d000247caea","nwkAddr":51905,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.weather","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":24321,"inClusterList":[0,3,65535,1026,1027,1029],"outClusterList":[0,4,65535],"clusters":{"msTemperatureMeasurement":{"attributes":{"measuredValue":2020}},"msRelativeHumidity":{"attributes":{"measuredValue":4864}},"msPressureMeasurement":{"attributes":{"16":9759,"20":-1,"measuredValue":975}},"genBasic":{"attributes":{"65281":{"1":2885,"4":17320,"5":147,"6":[0,1],"10":55982,"100":2011,"101":4411,"102":97556},"modelId":"lumi.weather","manufacturerName":"LUMI","powerSource":3,"zclVersion":1,"appVersion":3,"stackVersion":2,"hwVersion":30,"dateCode":"20161129","swBuildId":"3000-0001"}}},"binds":[]}},"appVersion":3,"stackVersion":2,"hwVersion":30,"dateCode":"20161129","swBuildId":"3000-0001","zclVersion":1,"interviewCompleted":true,"meta":{}}
{"id":8,"type":"EndDevice","ieeeAddr":"0x00158d00023761f8","nwkAddr":10943,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.weather","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":24321,"inClusterList":[0,3,65535,1026,1027,1029],"outClusterList":[0,4,65535],"clusters":{"msTemperatureMeasurement":{"attributes":{"measuredValue":2088}},"msRelativeHumidity":{"attributes":{"measuredValue":5087}},"msPressureMeasurement":{"attributes":{"16":9700,"20":-1,"measuredValue":970}},"genBasic":{"attributes":{"65281":{"1":2895,"4":17320,"5":148,"6":[0,1],"10":0,"100":2082,"101":5098,"102":96974},"modelId":"lumi.weather","manufacturerName":"LUMI","powerSource":3,"zclVersion":1,"appVersion":3,"stackVersion":2,"hwVersion":30,"dateCode":"20161129","swBuildId":"3000-0001"}}},"binds":[]}},"appVersion":3,"stackVersion":2,"hwVersion":30,"dateCode":"20161129","swBuildId":"3000-0001","zclVersion":1,"interviewCompleted":true,"meta":{}}
{"id":9,"type":"EndDevice","ieeeAddr":"0x00158d0003f044cc","nwkAddr":14775,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.weather","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":24321,"inClusterList":[0,3,65535,1026,1027,1029],"outClusterList":[0,4,65535],"clusters":{"msTemperatureMeasurement":{"attributes":{"measuredValue":2029}},"msRelativeHumidity":{"attributes":{"measuredValue":5277}},"msPressureMeasurement":{"attributes":{"16":9708,"20":-1,"measuredValue":970}},"genBasic":{"attributes":{"65281":{"1":2995,"4":5032,"5":5,"6":[0,1],"10":0,"100":2030,"101":5264,"102":97075},"modelId":"lumi.weather","manufacturerName":"LUMI","powerSource":3,"zclVersion":1,"appVersion":3,"stackVersion":2,"hwVersion":30,"dateCode":"20161129","swBuildId":"3000-0001"}}},"binds":[]}},"appVersion":3,"stackVersion":2,"hwVersion":30,"dateCode":"20161129","swBuildId":"3000-0001","zclVersion":1,"interviewCompleted":true,"meta":{}}
{"id":10,"type":"EndDevice","ieeeAddr":"0x00158d000349595d","nwkAddr":717,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.weather","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":24321,"inClusterList":[0,3,65535,1026,1027,1029],"outClusterList":[0,4,65535],"clusters":{"msTemperatureMeasurement":{"attributes":{"measuredValue":2018}},"msRelativeHumidity":{"attributes":{"measuredValue":7034}},"msPressureMeasurement":{"attributes":{"16":9701,"20":-1,"measuredValue":970}},"genBasic":{"attributes":{"65281":{"1":2965,"4":17320,"5":23,"6":[0,1],"10":55982,"100":2020,"101":7062,"102":97021},"modelId":"lumi.weather","manufacturerName":"LUMI","powerSource":3,"zclVersion":1,"appVersion":3,"stackVersion":2,"hwVersion":30,"dateCode":"20161129","swBuildId":"3000-0001"}}},"binds":[]}},"appVersion":3,"stackVersion":2,"hwVersion":30,"dateCode":"20161129","swBuildId":"3000-0001","zclVersion":1,"interviewCompleted":true,"meta":{}}
{"id":11,"type":"Router","ieeeAddr":"0x00124b00193675ad","nwkAddr":57011,"manufId":4447,"manufName":"LUMI","powerSource":"Mains (single phase)","modelId":"lumi.router","epList":[8],"endpoints":{"8":{"profId":260,"epId":8,"devId":256,"inClusterList":[0,6],"outClusterList":[0,6],"clusters":{"genBasic":{"attributes":{"modelId":"lumi.router","manufacturerName":"LUMI","powerSource":1,"zclVersion":1,"hwVersion":1,"dateCode":"2018-09-26"}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[]}},"hwVersion":1,"dateCode":"2018-09-26","zclVersion":1,"interviewCompleted":true,"meta":{}}
{"id":12,"type":"EndDevice","ieeeAddr":"0x00158d00023f519d","nwkAddr":37934,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.weather","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":24321,"inClusterList":[0,3,65535,1026,1027,1029],"outClusterList":[0,4,65535],"clusters":{"msTemperatureMeasurement":{"attributes":{"measuredValue":2017}},"msRelativeHumidity":{"attributes":{"measuredValue":5369}},"msPressureMeasurement":{"attributes":{"16":9699,"20":-1,"measuredValue":969}},"genBasic":{"attributes":{"65281":{"1":2875,"4":17320,"5":44,"6":[0,1],"10":0,"100":2029,"101":5309,"102":96992},"modelId":"lumi.weather","manufacturerName":"LUMI","powerSource":3,"zclVersion":1,"appVersion":3,"stackVersion":2,"hwVersion":30,"dateCode":"20161129","swBuildId":"3000-0001"}}},"binds":[]}},"appVersion":3,"stackVersion":2,"hwVersion":30,"dateCode":"20161129","swBuildId":"3000-0001","zclVersion":1,"interviewCompleted":true,"meta":{}}
{"id":13,"type":"EndDevice","ieeeAddr":"0x00158d000321742b","nwkAddr":41686,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.weather","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":24321,"inClusterList":[0,3,65535,1026,1027,1029],"outClusterList":[0,4,65535],"clusters":{"msTemperatureMeasurement":{"attributes":{"measuredValue":2086}},"msRelativeHumidity":{"attributes":{"measuredValue":5251}},"msPressureMeasurement":{"attributes":{"16":9703,"20":-1,"measuredValue":970}},"genBasic":{"attributes":{"modelId":"lumi.weather","manufacturerName":"LUMI","powerSource":3,"zclVersion":1,"appVersion":3,"stackVersion":2,"hwVersion":30,"dateCode":"20161129","swBuildId":"3000-0001"}}},"binds":[]}},"appVersion":3,"stackVersion":2,"hwVersion":30,"dateCode":"20161129","swBuildId":"3000-0001","zclVersion":1,"interviewCompleted":true,"meta":{}}
{"id":14,"type":"EndDevice","ieeeAddr":"0x00158d000247cc45","nwkAddr":42879,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.weather","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":24321,"inClusterList":[0,3,65535,1026,1027,1029],"outClusterList":[0,4,65535],"clusters":{"msTemperatureMeasurement":{"attributes":{"measuredValue":2108}},"msRelativeHumidity":{"attributes":{"measuredValue":5095}},"msPressureMeasurement":{"attributes":{"16":9704,"20":-1,"measuredValue":970}},"genBasic":{"attributes":{"65281":{"1":2985,"4":5032,"5":66,"6":[0,1],"10":0,"100":2111,"101":5093,"102":97038},"modelId":"lumi.weather","manufacturerName":"LUMI","powerSource":3,"zclVersion":1,"appVersion":3,"stackVersion":2,"hwVersion":30,"dateCode":"20161129","swBuildId":"3000-0001"}}},"binds":[]}},"appVersion":3,"stackVersion":2,"hwVersion":30,"dateCode":"20161129","swBuildId":"3000-0001","zclVersion":1,"interviewCompleted":true,"meta":{}}
{"id":15,"type":"EndDevice","ieeeAddr":"0x00158d000208e0b2","nwkAddr":18546,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_magnet.aq2","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":24321,"inClusterList":[0,3,65535,6],"outClusterList":[0,4,65535],"clusters":{"genBasic":{"attributes":{"65281":{"1":3015,"3":13,"4":5032,"5":310,"6":[1,33554435],"10":57011,"100":0},"modelId":"lumi.sensor_magnet.aq2","manufacturerName":"LUMI","powerSource":3,"zclVersion":1,"appVersion":3,"stackVersion":2,"hwVersion":2,"dateCode":"20161128","swBuildId":"3000-0001"}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[]}},"appVersion":3,"stackVersion":2,"hwVersion":2,"dateCode":"20161128","swBuildId":"3000-0001","zclVersion":1,"interviewCompleted":true,"meta":{}}
{"id":16,"type":"EndDevice","ieeeAddr":"0x00158d000208e26b","nwkAddr":21183,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_magnet.aq2","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":24321,"inClusterList":[0,3,65535,6],"outClusterList":[0,4,65535],"clusters":{"genOnOff":{"attributes":{"onOff":0}},"genBasic":{"attributes":{"65281":{"1":3005,"3":21,"4":17320,"5":166,"6":[0,1],"10":25009,"100":0},"modelId":"lumi.sensor_magnet.aq2","appVersion":3}}},"binds":[]}},"appVersion":3,"interviewCompleted":true,"meta":{}}
{"id":17,"type":"Router","ieeeAddr":"0x00124b0018df40d8","nwkAddr":55982,"manufId":4447,"manufName":"LUMI","powerSource":"Mains (single phase)","modelId":"lumi.router","epList":[8],"endpoints":{"8":{"profId":260,"epId":8,"devId":256,"inClusterList":[0,6],"outClusterList":[0,6],"clusters":{"genBasic":{"attributes":{"modelId":"lumi.router","manufacturerName":"LUMI","powerSource":1,"zclVersion":1,"hwVersion":1,"dateCode":"2018-09-26"}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[]}},"hwVersion":1,"dateCode":"2018-09-26","zclVersion":1,"interviewCompleted":true,"meta":{}}
{"id":18,"ieeeAddr":"0xd0cf5efffe720208","nwkAddr":51054,"epList":[],"endpoints":{},"interviewCompleted":false,"meta":{}}
{"id":19,"ieeeAddr":"0x000d6ffffec6089b","nwkAddr":29357,"epList":[],"endpoints":{},"interviewCompleted":false,"meta":{}}
{"id":20,"type":"EndDevice","ieeeAddr":"0x00158d00044941b4","nwkAddr":1784,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_motion.aq2","epList":[1],"endpoints":{"1":{"epId":1,"inClusterList":[],"outClusterList":[],"clusters":{"msIlluminanceMeasurement":{"attributes":{"measuredValue":38}},"msOccupancySensing":{"attributes":{"occupancy":1}},"genBasic":{"attributes":{"65281":{"1":3035,"3":28,"4":5032,"5":17,"6":[0,2],"10":0,"11":7,"100":0}}}},"binds":[]}},"appVersion":5,"interviewCompleted":true,"meta":{}}
{"id":21,"type":"Router","ieeeAddr":"0xf0d1b800001345e6","nwkAddr":34924,"manufId":4489,"manufName":"LEDVANCE","powerSource":"Mains (single phase)","modelId":"Plug Z3","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[0,3,4,5,6,2821,4096,64527],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"Plug Z3","manufacturerName":"LEDVANCE","powerSource":1,"zclVersion":2,"appVersion":1,"stackVersion":2,"hwVersion":1,"dateCode":"Dec 10 2018\u0000\u0000\u0000\u0000\u0000","swBuildId":"00103101"}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0014b92997","endpointID":1}]},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[]}},"appVersion":1,"stackVersion":2,"hwVersion":1,"dateCode":"Dec 10 2018\u0000\u0000\u0000\u0000\u0000","swBuildId":"00103101","zclVersion":2,"interviewCompleted":true,"meta":{"configured":1}}

**Comment by Koenkk** [comment]
Looks like it works fine? What is the problem? You can control it by publishing to `zigbee2mqtt/0xf0d1b800001345e6/set` with payload `TOGGLE` (as an example)

**Comment by P-Verbrugge** [comment]
> Looks like it works fine? What is the problem? You can control it by publishing to `zigbee2mqtt/0xf0d1b800001345e6/set` with payload `TOGGLE` (as an example)

It pairs, but it is often not available in the network. It drops often. Also devices can connect to it, but it does not route anything. The connection to the plug is ok. Devices connecting to the plug have signal strength of 100+. The plug itself does not connect to the coordinator. Yeah, it does connect, but the signal strength is 0/1 when it connects to other routers and the coordinator. It can not route anything.

**Comment by Koenkk** [comment]
@P-Verbrugge unfortunately that is not a problem that can be fixed by zigbee2mqtt, you might want to increase the network strength https://www.zigbee2mqtt.io/how_tos/how_to_improve_network_range.html

I will close this issue as the OP problem (support of this devices) has been solved now.
