### ISSUE TITLE
 Oz Smart Things DL41-03-10-R-ZB

### ISSUE THREAD

**Issue by Gurgeh88** [Koenkk/zigbee-herdsman-converters#5755]
Hi there,

Have recently installed two of these lights and integrated into Home Assistant using Zigbee2MQTT.
Problem is, when I turn them on after they've been off for a little while, they turn off again straight away (instantly almost).
When this happens, they appear in HA UI as being on but they are definitely off.
The only way to get them to turn when this happens is to call the light to turn on again via HA.

Does anyone have any experience of this happening for them/have any suggestions for how to fix this?

My Home Assistant and Zigbee2MQTT are all up to date. This behaviour is completely isolated to these two new lights. Both of them have great link quality according to Zigbee2MQTT and don't show signs of regular service calls being unreliable. Only when they've been off for a while. I have reset them and re-paired with Zigbee2MQTT which didn't help. Have also tried adding them to the Tuya Smart or Smart Life apps on my phone but was not able to do this successfully (couldn't work out which option to pick from the Add Device list and nothing showed up when scanning for devices ready to pair). I wanted to do this so I could update the firmware.

Any help would be greatly appreciated as otherwise I like these bulbs and would happily use them in the rest of the house but for this one flaw which makes them pretty much useless.

Many thanks :)

**Comment by Gurgeh88** [comment]
Can anyone offer some advice on how to further debug this issue? Still remains despite latest Z2M update.

**Comment by Gurgeh88** [comment]
Just an update, I purchased a Tuya Zigbee hub to see if there was an update available (as Z2M showed none).
No luck there.
These lights are on the latest firmware according to the Tuya app.
Unfortunately, without any extra support to fix these lights I couldn't honestly say they were worth buying and using with Z2M and Home Assistant. My bodge job automation to get them to work is simply not clean enough.

**Comment by Scales82** [comment]
I did the PR for the original external converter. I can honestly say the lights work fine for me. Either left on permanently (which is what I do via shelly relays). or when switching on/off entirely (as my wife does). What zigbee co-ordinator are you using?

**Comment by Gurgeh88** [comment]
> I did the PR for the original external converter. I can honestly say the lights work fine for me. Either left on permanently (which is what I do via shelly relays). or when switching on/off entirely (as my wife does). What zigbee co-ordinator are you using?

Hi there, I use the Sonoff USB 3.0 Dongle Plus running firmware revision "20220219".
I've tried changing all the different configurable settings for these lights in Zigbee2MQTT but that hasn't helped.
My next step is to try updating the firmware on the Sonoff dongle as I believe there is a newer version.
