### ISSUE TITLE
Help to add MYQ-ZSA02 zigbee siren

### ISSUE THREAD

**Issue by ririck0** [Koenkk/zigbee-herdsman-converters#5798]
Hi, I've bought an MYQ-ZSA02 zigbee siren on aliexpress.

I would like to support this device in zigbee2mqtt, but I don't really know how to start. Is there a way to know which command and which values are handled by this siren?

By enabling debugging, I found this information:
Model ID: 'TS0219', Manufacturer Name: '_TYZB01_rs7ff6o7'

I have also tried using the Woox R7051 configuration with no success. Could you please give me some help to support this device?

Thanks a lot

Best regards, ririck0

**Comment by Koenkk** [comment]
Could you check if the issue is fixed with the following external converter: https://gist.github.com/Koenkk/a03866a6456847fd7d138f4a572122f1

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if issue is fixed

**Comment by ririck0** [comment]
Hi,
Thank you for your file.  Unfortunately, this only partially works.  I was able to activate/deactivate the buzzer, but nothing else (impossible to manage the volume and the leds).  Could you tell me what I need to do to find the commands and values supported by this device?

Best regards,

**Comment by Koenkk** [comment]
To add support for this you need to reverse engineer the calls made when setting the volume via the TuYa gateway: https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html

**Comment by ririck0** [comment]
I don't have a tuya gateway, but I've found this sensor is supported by jeedom zigbee plugin. Is there anyway to get some info from there ?
