### ISSUE TITLE
Troubleshooting Device

### ISSUE THREAD

**Issue by razzam21** [Koenkk/zigbee-herdsman-converters#581]
I am attempting to add a SmartThings motion sensor to my system.  I see all of the fields that should be there (temperature, battery, and if there is motion).  The motion field is triggering properly but the temperature and battery fields are blank.  I am attempting to troubleshoot where the issue and read the documentation but I am must be missing something.  Here is what I have in the devices.js file.

`    {
        zigbeeModel: ['motionv5'],
        model: 'STS-IRM-250',
        vendor: 'SmartThings',
        description: 'Motion sensor (2017 model)',
        supports: 'occupancy and temperature',
        fromZigbee: [
            fz.generic_temperature, fz.ignore_temperature_change, fz.ias_zone_motion_dev_change,
            fz.generic_ias_zone_occupancy_status_change, fz.generic_batteryvoltage_3000_2500,
        ],
        toZigbee: [],
        configure: (ieeeAddr, shepherd, coordinator, callback) => {
            const device = shepherd.find(ieeeAddr, 1);
            const actions = [
                (cb) => device.write('ssIasZone', 'iasCieAddr', coordinator.device.getIeeeAddr(), cb),
                (cb) => device.functional('ssIasZone', 'enrollRsp', {enrollrspcode: 0, zoneid: 23}, cb),
                (cb) => device.bind('msTemperatureMeasurement', coordinator, cb),
                (cb) => device.report('msTemperatureMeasurement', 'measuredValue', 30, 600, 1, cb),
                (cb) => device.bind('genPowerCfg', coordinator, cb),
                (cb) => device.report('genPowerCfg', 'batteryVoltage', 0, 1000, 0, cb),
            ];
            execute(device, actions, callback);
        },
    },`

To troubleshoot the battery I take a look at the generic_temperature function and the generic_batteryvoltage_3000_2500 functions?  I have put console.log files in there to see the raw data but they don't seem to be logging anything.  I do have now see some lines like this in the log files.  Not sure if this is a result of what I did or just a coincidence.  
`zigbee2mqtt:warn 8/25/2019, 4:45:17 PM Failed to configure 0x24fd5b0001040425 (0x24fd5b0001040425) ('Error: Timed out after 30000 ms') (attempt #1)
  zigbee2mqtt:warn 8/25/2019, 4:45:17 PM This can be ignored if the device is working properly
`
Thanks for all of your help.  I love this application as it lets me decouple my zigbee devices from Home Assistant.  And decoupling in my life is a good thing.

**Comment by Koenkk** [comment]
In order to get the temperature reporting, the configure must succeed.

Please:
- Remove all occurrences of `0x24fd5b0001040425` from `database.db`
- Restart zigbee2mqtt
- Re-pair the device
- See if configure succeeds.
