### ISSUE TITLE
Please, please, please help me with the backlight on TS0601   

### ISSUE THREAD

**Issue by 1060778506** [Koenkk/zigbee-herdsman-converters#5828]
I've been working on this problem for a week

So far the converter is working. The converter is working, but the backlight is out of control

 
I tried to change my current converter using TS0601_switch_4_gang_2(This converter supports backlit code with backlit code)

Please help me. I'm going crazy,

This is the doodle device six buttons,

In the Doodle APP, I can turn on or off the backlight, so this switch supports the function of turning on or off the backlight

 

This is the original
![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/24760769/1b94db8e-529b-474c-ab7b-4431cdcce058)
![QQ截图20230601140935](https://github.com/Koenkk/zigbee-herdsman-converters/assets/24760769/0b7bc822-190d-4900-a19d-db9a02678d3f)

This is what I changed 
![QQ截图20230601141048](https://github.com/Koenkk/zigbee-herdsman-converters/assets/24760769/9d362c75-35a2-4020-9faf-88fb7d53ad35)

But he made a mistake(But everything else, the open button works, the signal works)
![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/24760769/dd76ee80-b899-42e9-9bf7-dfae52d85253)

Then I try the send data of this post
https://github.com/Koenkk/zigbee2mqtt/issues/15970
But he still made mistakes
![QQ截图20230601135735](https://github.com/Koenkk/zigbee-herdsman-converters/assets/24760769/6ca2b866-8d7d-4218-8ab7-86e5de558086)

---------------Device information--------------
![QQ截图20230601135810](https://github.com/Koenkk/zigbee-herdsman-converters/assets/24760769/370e79b7-334f-4d6b-9f74-fb9bed3f1c62)
![QQ截图20230601135816](https://github.com/Koenkk/zigbee-herdsman-converters/assets/24760769/cb49e302-e46b-475d-a9ea-84799688e85a)
![QQ截图20230601135827](https://github.com/Koenkk/zigbee-herdsman-converters/assets/24760769/f371c223-9085-40d4-864f-3b3c9c539140)
---------------Device information--------------

-----------code------------
![QQ截图20230601135759](https://github.com/Koenkk/zigbee-herdsman-converters/assets/24760769/d93bc62c-ac91-467a-acda-3de7cc456290)

`const exposes = require('zigbee-herdsman-converters/lib/exposes');
const legacy = require('zigbee-herdsman-converters/lib/legacy');
const fz = {...require('zigbee-herdsman-converters/converters/fromZigbee'), legacy: legacy.fromZigbee};
const tz = {...require('zigbee-herdsman-converters/converters/toZigbee'), legacy: legacy.toZigbee};
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const libColor = require('zigbee-herdsman-converters/lib/color');
const utils = require('zigbee-herdsman-converters/lib/utils');
const zosung = require('zigbee-herdsman-converters/lib/zosung');
const fzZosung = zosung.fzZosung;
const tzZosung = zosung.tzZosung;
const ez = zosung.presetsZosung;
const globalStore = require('zigbee-herdsman-converters/lib/store');
const {ColorMode, colorModeLookup} = require('zigbee-herdsman-converters/lib/constants');

const definition = {
    fingerprint: tuya.fingerprint('TS0601', ['_TZE200_h2rctifa']),
    model: 'TS0601_switch_6_gang_设备型号不是这个型号',
    vendor: 'TuYa_厂家品牌',
    description: '6组开关_功能描述',
    fromZigbee: [tuya.fz.datapoints],
    toZigbee: [tuya.tz.datapoints],
    configure: tuya.configureMagicPacket,
    exposes: [
        tuya.exposes.switch().withEndpoint('l1'),
        tuya.exposes.switch().withEndpoint('l2'),
        tuya.exposes.switch().withEndpoint('l3'),
        tuya.exposes.switch().withEndpoint('l4'),
        tuya.exposes.switch().withEndpoint('l5'),
        tuya.exposes.switch().withEndpoint('l6'),
        tuya.exposes.backlightModeOffOn(),//背光但是无效的可以删除
    ],
    endpoint: (device) => {
        return {'l1': 1, 'l2': 1, 'l3': 1, 'l4': 1, 'l5': 1, 'l6': 1};
    },
    meta: {
        multiEndpoint: true,
        tuyaDatapoints: [
            [1, 'state_l1', tuya.valueConverter.onOff],
            [2, 'state_l2', tuya.valueConverter.onOff],
            [3, 'state_l3', tuya.valueConverter.onOff],
            [4, 'state_l4', tuya.valueConverter.onOff],
            [5, 'state_l5', tuya.valueConverter.onOff],
            [6, 'state_l6', tuya.valueConverter.onOff],
            [7, 'backlight_mode', tuya.valueConverter.onOff],//背光但是无效的可以删除
        ],
    },
}

module.exports = definition;`

**Comment by 1060778506** [comment]
求求拜托不要沉

**Comment by mayongze** [comment]
@1060778506 你搞定背光了嘛

**Comment by 1060778506** [comment]
> @1060778506 你搞定背光了嘛

没有

**Comment by mayongze** [comment]
> > @1060778506 你搞定背光了嘛
> 
> 没有

加我v: 1014057907, 有兴趣可以一起研究下

**Comment by 1060778506** [comment]
> > > @1060778506 你搞定背光了嘛
> > 
> > 
> > 没有
> 
> 加我v: 1014057907, 有兴趣可以一起研究下

哈哈 我房子都卖了
