### ISSUE TITLE
IKEA Fyrtur 24.4.11 drains battery

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee-herdsman-converters#5836]
```
debug 2023-06-03 16:09:38: Received Zigbee message from 'cover/livingroom/side_front_window', type 'commandCheckIn', cluster 'genPollCtrl', data '{}' from endpoint 1 with groupID 0
debug 2023-06-03 16:09:38: Received Zigbee message from 'cover/livingroom/side_back_window', type 'commandCheckIn', cluster 'genPollCtrl', data '{}' from endpoint 1 with groupID 0
debug 2023-06-03 16:09:39: Received Zigbee message from 'cover/livingroom/side_front_window', type 'commandCheckIn', cluster 'genPollCtrl', data '{}' from endpoint 1 with groupID 0
debug 2023-06-03 16:09:39: Received Zigbee message from 'cover/livingroom/side_back_window', type 'commandCheckIn', cluster 'genPollCtrl', data '{}' from endpoint 1 with groupID 0
debug 2023-06-03 16:09:40: Received Zigbee message from 'cover/livingroom/side_front_window', type 'commandCheckIn', cluster 'genPollCtrl', data '{}' from endpoint 1 with groupID 0
debug 2023-06-03 16:09:40: Received Zigbee message from 'cover/livingroom/side_back_window', type 'commandCheckIn', cluster 'genPollCtrl', data '{}' from endpoint 1 with groupID 0
debug 2023-06-03 16:09:41: Received Zigbee message from 'cover/livingroom/side_front_window', type 'commandCheckIn', cluster 'genPollCtrl', data '{}' from endpoint 1 with groupID 0
```

Got the low battery alert just now, these were updated yesterday.

Looks like the pull every second! This seems ver excessive, a reconfigure doesnt update it.

I think we should probably set a more sane poll interval in the configure() function.

Will look at this when I'm home tomorrow.

@Koenkk not 100% sure but since this seems to have been added in the latest update, a remove + join might also fix this no? I think we configure some sort of genPollCtrl defaults during interview?

If not, what would be a good one to add to configure? 1min? 30sec? I guess we also don't want them to respond too slowly.

**Comment by sjorge** [comment]
```
Info 2023-06-03 16:18:22Read result of 'genPollCtrl': {"checkinInterval":4,"longPollInterval":4,"fastPollTimeout":1}
```

Are the settings currently after the upgrade.

**Comment by sjorge** [comment]
Looks like we cannot change these poll intervals, they are READ_ONLY 😒

**Comment by Koenkk** [comment]
Did you already try to factory reset the device?

**Comment by sjorge** [comment]
> Did you already try to factory reset the device?

Not at home now, but i do plan on removing one from the network and resetting it. Would suck if that fixes it though, as many will run into this when updating the firmware.

**Comment by MattWestb** [comment]
"checkinInterval":4 is very wrong sett.
ZHA is having it 13200 1/4 seconds.

**Comment by sjorge** [comment]
> "checkinInterval":4 is very wrong sett.
> ZHA is having it 13200 1/4 seconds.

Does ZHA set it during it’s equalivant of configure() ?

**Comment by MattWestb** [comment]
ZHA is not setting pull control at all for all IKEA controllers so the device is using its default.

**Comment by MattWestb** [comment]
![IKEA Blind01](https://github.com/Koenkk/zigbee-herdsman-converters/assets/49618193/b61432c7-e5b7-451d-8e4e-d9f9d595783f)

**Comment by sjorge** [comment]
> ![IKEA Blind01](https://github.com/Koenkk/zigbee-herdsman-converters/assets/49618193/b61432c7-e5b7-451d-8e4e-d9f9d595783f)
> 
> 

Once I get home I will remove one and reset it (holding both buttons until the led blinks ?)

Both start spamming the checking after they updated with OTA, before it definitely was not like that.

**Comment by MattWestb** [comment]
All IKEA controllers is now real Zigbee 3 and is using most of the advanced functions like pull control and have doing it for the early for many years now but i think Z2M have setting bad parameters and it was working OK before but its many things with the settings that must being OK and 4,4,4 is 110% not one valid setting then long pull must being longer as fast pull and Chechen must being longer then long pull interval.

**Comment by sjorge** [comment]
Yeah, the settings looked wrong to me too. 

In anycase checkininterval is writable so we can just write 13200 to it during configure, if others are also seeing this weird values it will be fixed.

**Comment by MattWestb** [comment]
13200  is default if not setting it and is from the firmware so shall working as long Z2M is not setting it to somthing else.

I have sniffed Tradfri parings how they is setting up and poll is not being done and the device is working great (ZHA was doing it but we was taking it away for getting better battery lifetime).

**Comment by MattWestb** [comment]
Some Z2M user have the same problem and its one open issue for it.

**Comment by MattWestb** [comment]
Also your battery fix looks not working so reporting 200% some have complaining.

**Comment by sjorge** [comment]
> Also your battery fix looks not working so reporting 200% some have complaining / reported.

Battery before and after the update still looks fine though.

But not sure all ikea battery devices use the other battery converter. It could also be that version check is not 100% correct (https://github.com/Koenkk/zigbee-herdsman-converters/blob/be6691946b9b098fa56bdb19dd903db9cd94fc13/src/devices/ikea.js#L209) but more likely is that the fwVersion did not correctly get updated after the OTA was completed, which happens a lot for z2m. But it’s probably best to keep this issues just to the checkininterval being wrong.

**Comment by MattWestb** [comment]
All IKEA OTA files is signed and if its not OK in the flash the device is throwing the OTA and need redo the download and cant flashing one bad firmware (If not IKEA have doing it wrong that they have doing some times) or the main flash is broken so its not  being OK flashed.

All released 24.X controllers firmware is using Zigbee standard battery reporting and i have sniffing all from Dirigera for some week ago and installed them with ZHA.

**Comment by sjorge** [comment]
> All IKEA OTA files is signed and if its not OK in the flash the device is throwing the OTA and need redo the download and cant flashing one bad firmware (If not IKEA have doing it wrong that they have doing some times) or the main flash is broken so its not being OK flashed.
> 
> All released 24.X controllers firmware is using Zigbee standard battery reporting and i have sniffing all from Dirigera for some week ago and installed them with ZHA.

So the fw check should be fine then, and fyrtur is already using the ikea specific converter. So that would explain why the battery level is still correct.

**Comment by sjorge** [comment]
removing, hold both buttons to reset and rejoin also seems to 'fix' it. The checkin time is indeed `13200`.

I grabbed one of the soon to be installed blinds, joined it, updated it and it was also set wrong after. I will set the value to `13200` in the configure() function to fix this so it will be fine for people in the future without factory resetting.

**Comment by MattWestb** [comment]
Great work done !!
I think the user with battery 200% problem has the system red still the old version from the device and need getting it red one more time for using the new battery fix or deleting it and adding it new and it shall working.
Also if doing functional upgrade (endpoints and clusters) it can being needed deleting and adding new so the system is having the right profile of the device and not the old / mixed version of it.
