### ISSUE TITLE
Wrong measuring unit for formaldehyd at TS0601_TZE200 Smart air house keeper

### ISSUE THREAD

**Issue by uli-rpi** [Koenkk/zigbee-herdsman-converters#5857]
The measuring unit of formaldehyd is displayed as **Âµg/mÂ** instead of µg/m³

I think the reason is in tuya.ts at line 650 / 651 
```
        exposes: [e.temperature(), e.humidity(), e.co2(), e.voc().withUnit('ppm'), e.formaldehyd().withUnit('Âµg/mÂ³'),
            e.pm25().withValueMin(0).withValueMax(999).withValueStep(1)],
```
Zigbee2MQTT Version 1.31.0 commit: f440c860

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
