### ISSUE TITLE
modelID mixed up  in /src/devices/alecto.ts

### ISSUE THREAD

**Issue by joehacker42** [Koenkk/zigbee-herdsman-converters#5900]
modelID for SMART-SMOKE10 is defined in SMART-HEAT10, smoke detector is detected as thermostat.
{modelID: 'TS0601', manufacturerName: '_TZE200_qtbrwrfv'} needs to be moved to SMART-SMOKE10

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
