### ISSUE TITLE
Help to add TS0202 from _TZ3210_0aqbrnts

### ISSUE THREAD

**Issue by DChe47** [Koenkk/zigbee-herdsman-converters#5929]
Hello zigbee experts,
I bought the device, but unfortunately it is not supported (see link: [https://ekfgroup.com/catalog/products/umnyj-datchik-4v1-zigbee-ekf-connect](url) ) (sorry, Russian only)
This device is defined as
   modelID: 'TS0202'
   manufacturerName: '_TZ3210_0aqbrnts'
Here is the log from this device:
[TS0202_log.txt](https://github.com/Koenkk/zigbee-herdsman-converters/files/11914147/TS0202_log.txt)

I found that this device is like ZB003-X (Vendor Fantem) or 07502L (Vendor Immax).
I tried to make .js for support new device:

`const exposes = require('zigbee-herdsman-converters/lib/exposes');
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const legacy = require('zigbee-herdsman-converters/lib/legacy');
const e = exposes.presets;
const ea = exposes.access;
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const tuya = require('zigbee-herdsman-converters/lib/tuya');

const definition = 
    {
        fingerprint: [{modelID: 'TS0202', manufacturerName: '_TZ3210_0aqbrnts'}],
        model: 'is-thpl-zb',
        vendor: 'EKF',
        description: '4 in 1 multi sensor',
        fromZigbee: [fz.battery, fz.ignore_basic_report, fz.illuminance, legacy.fz.ZB003X, fz.ZB003X_attr, fz.ZB003X_occupancy],
        toZigbee: [legacy.tz.ZB003X],
        exposes: [e.occupancy(), e.tamper(), e.illuminance_lux(), e.illuminance(), e.temperature(), e.humidity(),
            e.battery(), e.battery_voltage(),
            e.numeric('battery2', ea.STATE).withUnit('%').withDescription('Remaining battery 2 in %'),
            e.numeric('illuminance_calibration', ea.STATE_SET).withDescription('Illuminance calibration in lux')
                .withValueMin(-20).withValueMax(20),
            e.numeric('temperature_calibration', ea.STATE_SET).withDescription('Temperature calibration (-2.0...2.0)')
                .withValueMin(-2).withValueMax(2).withValueStep(0.1),
            e.numeric('humidity_calibration', ea.STATE_SET).withDescription('Humidity calibration')
                .withValueMin(-15).withValueMax(15),
            e.binary('reporting_enable', ea.STATE_SET, true, false).withDescription('Enable reporting'),
            e.numeric('reporting_time', ea.STATE_SET).withDescription('Reporting interval in minutes')
                .withValueMin(0).withValueMax(1440).withValueStep(5),
            e.binary('led_enable', ea.STATE_SET, true, false).withDescription('Enable LED'),
            e.binary('pir_enable', ea.STATE_SET, true, false).withDescription('Enable PIR sensor'),
            e.enum('sensitivity', ea.STATE_SET, ['low', 'medium', 'high']).withDescription('PIR sensor sensitivity'),
            // eslint-disable-next-line
            e.enum('keep_time', ea.STATE_SET, ['0', '30', '60', '120', '240', '480'])
                .withDescription('PIR keep time in seconds')],
    };

module.exports = definition;`

But I have a mistake:
`[09:52:44] INFO: Preparing to start...
[09:52:45] INFO: Socat not enabled
[09:52:45] INFO: Zigbee Herdsman debug logging enabled
[09:52:45] INFO: Starting Zigbee2MQTT...
/app/data/extension/externally-loaded.js:18
        fromZigbee: [fz.battery, fz.ignore_basic_report, fz.illuminance, legacy.fz.ZB003X, fz.ZB003X_attr, fz.ZB003X_occupancy],
                                                                                   ^

TypeError: Cannot read properties of undefined (reading 'ZB003X')
    at /app/data/extension/externally-loaded.js:18:84
    at Script.runInContext (node:vm:141:12)
    at Script.runInNewContext (node:vm:146:17)
    at Object.runInNewContext (node:vm:306:38)
    at loadModuleFromText (/app/lib/util/utils.ts:150:8)
    at loadModuleFromFile (/app/lib/util/utils.ts:157:12)
    at Object.getExternalConvertersDefinitions (/app/lib/util/utils.ts:167:25)
    at getExternalConvertersDefinitions.next (<anonymous>)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:12:20)
    at new Controller (/app/lib/controller.ts:84:58)`

Please help me.

**Comment by Koenkk** [comment]
Try again with tomorrows news z2m release.

**Comment by DChe47** [comment]
Unfortunately, the sensor is still not supported
`info  2023-07-02 09:16:38: Device '0x8cf681fffebf9c5e' joined
info  2023-07-02 09:16:38: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x8cf681fffebf9c5e","ieee_address":"0x8cf681fffebf9c5e"},"type":"device_joined"}'
info  2023-07-02 09:16:38: Starting interview of '0x8cf681fffebf9c5e'
info  2023-07-02 09:16:38: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x8cf681fffebf9c5e","ieee_address":"0x8cf681fffebf9c5e","status":"started"},"type":"device_interview"}'
debug 2023-07-02 09:16:38: Device '0x8cf681fffebf9c5e' announced itself
info  2023-07-02 09:16:38: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x8cf681fffebf9c5e","ieee_address":"0x8cf681fffebf9c5e"},"type":"device_announce"}'
debug 2023-07-02 09:16:38: Received Zigbee message from '0x8cf681fffebf9c5e', type 'readResponse', cluster 'genBasic', data '{"manufacturerName":"_TZ3210_0aqbrnts","modelId":"TS0202"}' from endpoint 1 with groupID 0
debug 2023-07-02 09:16:38: Skipping message, definition is undefined and still interviewing
debug 2023-07-02 09:16:39: Received Zigbee message from '0x8cf681fffebf9c5e', type 'readResponse', cluster 'genBasic', data '{"powerSource":3}' from endpoint 1 with groupID 0
debug 2023-07-02 09:16:39: Skipping message, definition is undefined and still interviewing
debug 2023-07-02 09:16:39: Received Zigbee message from '0x8cf681fffebf9c5e', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3}' from endpoint 1 with groupID 0
debug 2023-07-02 09:16:39: Skipping message, definition is undefined and still interviewing
debug 2023-07-02 09:16:40: Received Zigbee message from '0x8cf681fffebf9c5e', type 'readResponse', cluster 'genBasic', data '{"appVersion":161}' from endpoint 1 with groupID 0
debug 2023-07-02 09:16:40: Skipping message, definition is undefined and still interviewing
debug 2023-07-02 09:16:41: Received Zigbee message from '0x8cf681fffebf9c5e', type 'readResponse', cluster 'genBasic', data '{"stackVersion":0}' from endpoint 1 with groupID 0
debug 2023-07-02 09:16:41: Skipping message, definition is undefined and still interviewing
debug 2023-07-02 09:16:43: Received Zigbee message from '0x8cf681fffebf9c5e', type 'readResponse', cluster 'genBasic', data '{"hwVersion":1}' from endpoint 1 with groupID 0
debug 2023-07-02 09:16:43: Skipping message, definition is undefined and still interviewing
debug 2023-07-02 09:16:44: Received Zigbee message from '0x8cf681fffebf9c5e', type 'read', cluster 'genTime', data '["localTime"]' from endpoint 1 with groupID 0
debug 2023-07-02 09:16:44: Skipping message, definition is undefined and still interviewing
debug 2023-07-02 09:16:44: Received Zigbee message from '0x8cf681fffebf9c5e', type 'readResponse', cluster 'genBasic', data '{"dateCode":""}' from endpoint 1 with groupID 0
debug 2023-07-02 09:16:44: Skipping message, definition is undefined and still interviewing
debug 2023-07-02 09:16:44: Received Zigbee message from '0x8cf681fffebf9c5e', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 1 with groupID 0
debug 2023-07-02 09:16:44: Skipping message, definition is undefined and still interviewing
debug 2023-07-02 09:16:45: Received Zigbee message from '0x8cf681fffebf9c5e', type 'readResponse', cluster 'ssIasZone', data '{"iasCieAddr":"0x0000000000000000","zoneState":0}' from endpoint 1 with groupID 0
debug 2023-07-02 09:16:45: Skipping message, definition is undefined and still interviewing
debug 2023-07-02 09:16:49: Received Zigbee message from '0x8cf681fffebf9c5e', type 'readResponse', cluster 'ssIasZone', data '{"iasCieAddr":"0x00124b00256cd1bc","zoneState":1}' from endpoint 1 with groupID 0
debug 2023-07-02 09:16:49: Skipping message, definition is undefined and still interviewing
info  2023-07-02 09:16:49: Successfully interviewed '0x8cf681fffebf9c5e', device has successfully been paired
warn  2023-07-02 09:16:49: Device '0x8cf681fffebf9c5e' with Zigbee model 'TS0202' and manufacturer name '_TZ3210_0aqbrnts' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
info  2023-07-02 09:16:49: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":null,"friendly_name":"0x8cf681fffebf9c5e","ieee_address":"0x8cf681fffebf9c5e","status":"successful","supported":false},"type":"device_interview"}'
debug 2023-07-02 09:16:56: Received Zigbee message from '0x8cf681fffebf9c5e', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":1}' from endpoint 1 with groupID 0
warn  2023-07-02 09:16:56: Received message from unsupported device with Zigbee model 'TS0202' and manufacturer name '_TZ3210_0aqbrnts'
warn  2023-07-02 09:16:56: Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
`

**Comment by Koenkk** [comment]
great!
