### ISSUE TITLE
MFKZQ01LM side and to_side

### ISSUE THREAD

**Issue by jamestutton** [Koenkk/zigbee-herdsman-converters#597]
For the MFKZQ01LM Intelligent Magic Cube Controller the current implementation publishes 2 different values for flip90  (from_side/to_side) but only "side" for flip180 .

This means code wise you cant simply use side or to_side as depending on how the cube is moved on one of these values is actually correct and the other is possible eronious. 

As such i propose that "side" should always been published ie side == to_side for flip90 
```
else if (value >= 512) action = {'action': 'tap', 'side': value-512};
            else if (value >= 256) action = {'action': 'slide', 'side': value-256};
            else if (value >= 128) action = {'action': 'flip180', 'side': value-128};
            else if (value >= 64) {
                action = {'action': 'flip90', 'from_side': Math.floor((value-64) / 8), 'to_side': value % 8, 'side': value % 8};
            }
```
To this end technically to_side could be removed or the other optionn is flip180 could also be extened to include to/from_side attributes as if we know the final side then we can work out the from_side. Unfortunetly it appears we cant use simple math to add the the sides to 5.  As sides are not ordered like a normal dice.  As such we would need a lookup of some sort it seems.

**Comment by Koenkk** [comment]
Could you make a PR as proposal?
