### ISSUE TITLE
Add support for Xiaomi QBKG18LM (Aqara T1 double rocker without neutral)

### ISSUE THREAD

**Issue by cloudyngcloudy** [Koenkk/zigbee-herdsman-converters#5993]
Worked properly using the existing code for QBKG19LM
line:1612 
(https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/devices/xiaomi.ts)

QBKG18LM:

    zigbeeModel: ['lumi.switch.b2lacn01'], 
    model: 'QBKG18LM', 
    vendor: 'Xiaomi',
    description: 'Aqara T1 double rocker without neutral',

**Comment by Koenkk** [comment]
added, thanks!

**Comment by zhechenzhu** [comment]
The QBKG19LM code doesn't work for QBKG18LM. QBKG19LM is a single rocker switch while QBKG18LM is a double rocker version. The device config need to define left and right endpoints plus actions. Doing so fixs the issue.
