### ISSUE TITLE
Add support for TuYa ceiling radar presence sensor, model TS0225 

### ISSUE THREAD

**Issue by sozonnyk** [Koenkk/zigbee-herdsman-converters#6001]
I've got a no-name 240V AC ceiling radar presence sensor,  identified as `Tuya`  model `TS0225` manufacturer name: `_TZFED8_egngmrzh`

I've managed to create a very simple converter to only provide occupancy, distance and illumination.
I can see other messages in the log with datapoint `109`  but I can't figure out what it means.
I don't have a TuYa gateway, to get exact values.

So basically I'm stuck here, I'm wondering if someone can help me to move forward?

```javascript
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require('zigbee-herdsman-converters/lib/tuya');

const definition = {
    fingerprint: [{ modelID: 'TS0225',manufacturerName: '_TZFED8_egngmrzh'}],
    model: 'TS0225',
    vendor: 'TuYa',
    description: 'Smart Human presence sensor',
    onEvent: tuya.onEventSetTime, 
    configure: async (device, coordinatorEndpoint, logger) => {
                const endpoint = device.getEndpoint(1);
                await reporting.bind(endpoint, coordinatorEndpoint, ['genTime', 'genBasic', 'ssIasZone']);
            },

    fromZigbee: [tuya.fz.datapoints, fz.ias_occupancy_alarm_1],
    toZigbee: [tuya.tz.datapoints],

    exposes: [
            e.occupancy(),
            e.illuminance_lux(),
            e.numeric('target_distance', ea.STATE).withDescription('Distance to target').withUnit('m'),
        ],
    meta: {
        tuyaDatapoints: [
            [101, 'illuminance_lux', tuya.valueConverter.raw],
            [103, 'target_distance', tuya.valueConverter.divideBy10],
        ],
    },
};

module.exports = definition;

```

![20230723_093137](https://github.com/Koenkk/zigbee-herdsman-converters/assets/1960621/2b2ac8e3-ff16-487e-a6f7-80626f809b8f)
![20230723_093158](https://github.com/Koenkk/zigbee-herdsman-converters/assets/1960621/7750490e-deb2-4214-8dc1-1608772eafca)
![20230723_093208](https://github.com/Koenkk/zigbee-herdsman-converters/assets/1960621/a1d15eb9-b7e7-48ae-a580-0d68610c6b62)
![20230724_101828](https://github.com/Koenkk/zigbee-herdsman-converters/assets/1960621/a13f2b7b-8d17-4936-bb48-80ac61c86568)
![Screenshot_20230724_101736_Google](https://github.com/Koenkk/zigbee-herdsman-converters/assets/1960621/6cb1e940-5f43-4aee-bb52-8efb1c06f2ea)

**Comment by makstech** [comment]
This looks the same as what I implemented in https://github.com/Koenkk/zigbee-herdsman-converters/pull/6036 but just in a different enclosure

**Comment by sozonnyk** [comment]
@makstech I've tried your code and unfortunately it is not working for my sensor. 
I'm pretty sure that my sensor has datapoint 101 for the illuminance.

**Comment by sozonnyk** [comment]
Bumping this

**Comment by Burki24** [comment]
> @makstech I've tried your code and unfortunately it is not working for my sensor. I'm pretty sure that my sensor has datapoint 101 for the illuminance.

Can you please give a link to the seller?

**Comment by sozonnyk** [comment]
@Burki24 Here you are: [https://www.aliexpress.com/item/1005005791465694.html](https://www.aliexpress.com/item/1005005791465694.html)

**Comment by Burki24** [comment]
> @Burki24 Here you are: https://www.aliexpress.com/item/1005005791465694.html

Thanks, I've ordered one piece and when I got it, I will analyze via tuYa-Gateway.

**Comment by sozonnyk** [comment]
@Burki24 Thank you!

**Comment by sozonnyk** [comment]
Bump

**Comment by sozonnyk** [comment]
@Burki24 Any luck?

**Comment by sozonnyk** [comment]
Bump

**Comment by Koenkk** [comment]
@sozonnyk if basic functionality works, just add it with a PR, remaining functions can be added later.
