### ISSUE TITLE
ZigbeeModel  NimlyIn (Nimly Indoor) is missing in the model array of supported devices

### ISSUE THREAD

**Issue by bergetun** [Koenkk/zigbee-herdsman-converters#6043]
When the Nimly Connect Module (https://nimly.no/product/connect-module-no/) is installed in a Nimly InDoor ( https://nimly.no/product/indoor/ ) the zigbee model shows as NimlyIn . This means that it zigbee2mqtt will show as unsuported . 
See screenshot 1 : 

Solution: Add 'NimlyIn' to the array here: https://github.com/Koenkk/zigbee-herdsman-converters/blob/ab9958a0e8fbbb6cb22aae4cea71a5168c740cb1/src/devices/onesti.ts#L61
See screenshot 2 that the solution works  

Screenshot 1: 
<img width="895" alt="Skjermbilde 2023-08-03 kl  15 14 41" src="https://github.com/Koenkk/zigbee-herdsman-converters/assets/572407/ccdd0603-fb00-4f68-be73-b19cf124d158">

 Screenshot 2
<img width="852" alt="Skjermbilde 2023-08-04 kl  09 31 04" src="https://github.com/Koenkk/zigbee-herdsman-converters/assets/572407/154ab8e8-28c6-406c-9f2b-01dab47ce91a">

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
