### ISSUE TITLE
New version of AC0251100NJ OSRAM Smart+ switch mini

### ISSUE THREAD

**Issue by b1g1an** [Koenkk/zigbee-herdsman-converters#606]
I recently bought some OSRAM Smart+ switch minis which have the code AC0251400NJ rather than AC0251100NJ which is already a device. 

In the past I created a device for AC08559 OSRAM SMART+ Spot GU10 Multicolor which went fine just copying devices.js into share/zigbee2mqtt and taking an existing OSRAM bulb in it and tweaking to suit. So following the same approach with these switches I took a copy of AC0251100NJ and changed the number to AC0251400NJ. The switches now pair and return the following at start up...

```
zigbee2mqtt:info` 9/10/2019, 4:02:10 PM switch_mini_1 (0x000d6f001082b438): AC0251400NJ - OSRAM Smart+ switch mini (EndDevice)'
zigbee2mqtt:info 9/10/2019, 4:02:12 PM MQTT publish: topic 'zigbee2mqtt/switch_mini_1', payload '{"battery":"100.00","voltage":3100,"linkquality":0}'
```

All good so far, when pressing the buttons I get a response from all combinations of short and long presses along the lines of...

```
  zigbee2mqtt:info 9/10/2019, 4:02:43 PM MQTT publish: topic 'zigbee2mqtt/switch_mini_1', payload '{"battery":"100.00","voltage":3100,"linkquality":18,"action":"circle_click"}'
  zigbee2mqtt:info 9/10/2019, 4:02:43 PM MQTT publish: topic 'zigbee2mqtt/switch_mini_1', payload '{"battery":"100.00","voltage":3100,"linkquality":18,"action":""}'
  zigbee2mqtt:info 9/10/2019, 4:12:37 PM MQTT publish: topic 'zigbee2mqtt/switch_mini_1', payload '{"battery":"100.00","voltage":3000,"linkquality":23}'
  zigbee2mqtt:info 9/10/2019, 4:16:05 PM MQTT publish: topic 'zigbee2mqtt/switch_mini_1', payload '{"battery":"100.00","voltage":3000,"linkquality":21,"action":"circle_hold"}'
  zigbee2mqtt:info 9/10/2019, 4:16:05 PM MQTT publish: topic 'zigbee2mqtt/switch_mini_1', payload '{"battery":"100.00","voltage":3000,"linkquality":21,"action":""}'
  zigbee2mqtt:info 9/10/2019, 4:16:06 PM MQTT publish: topic 'zigbee2mqtt/switch_mini_1', payload '{"battery":"100.00","voltage":3000,"linkquality":23,"action":"circle_release"}'
  zigbee2mqtt:info 9/10/2019, 4:16:06 PM MQTT publish: topic 'zigbee2mqtt/switch_mini_1', payload '{"battery":"100.00","voltage":3000,"linkquality":23,"action":""}'
```

Which in mqtt explorer produces this...

![image](https://user-images.githubusercontent.com/26139271/64627133-ffdb1f00-d3e6-11e9-8ad2-8bfe33b6a581.png)

Home Assistant integrations sees all my other zigbee2mqtt devices but can't see this one so haven't got it to do anything constructive yet.

I have to admit I'm not 100% sure what I'm doing but hopefully someone can point me in the right direction so we can get this device added. Thanks.

**Comment by Koenkk** [comment]
For the device to appear in Home Assistant it has to be added to https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/extension/homeassistant.js#L620.

If the device works properly and produces the expected MQTT messages, make a PR, I will take care of further (Home assistant) integration.

**Comment by b1g1an** [comment]
Thanks, I've set it up manually in HA and it seems to work fine, will make PR.
