### ISSUE TITLE
Add W599501 Wiser Smoke Alarm to schneider_electric.js

### ISSUE THREAD

**Issue by ronniebach** [Koenkk/zigbee-herdsman-converters#6145]
I just got a new 230V edition of the Schneider Electric Wiser smoke alarm.
It reports itself as model: W599501 - which is not currently supported.

I managed to get it to work in Z2M by an external custom converter - based on the already supported model (W599001) in schneider_electric.js - which I think is the version only powered by battery.

So please just add the same functionality for the W599501 model as W599001

        zigbeeModel: ['W599001'],
        model: 'W599001',
        vendor: 'Schneider Electric',
        description: 'Wiser smoke alarm',
        fromZigbee: [fz.temperature, fz.battery, fz.ias_enroll, fz.ias_smoke_alarm_1],
        toZigbee: [],
        ota: ota.zigbeeOTA, // local OTA updates are untested
        exposes: [e.smoke(), e.battery_low(), e.tamper(), e.battery(), e.battery_voltage(),
            // the temperature readings are unreliable and may need more investigation.
            e.temperature(),
        ],
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(20);
            const binds = ['msTemperatureMeasurement', 'ssIasZone', 'genPowerCfg'];
            await reporting.bind(endpoint, coordinatorEndpoint, binds);
            await reporting.batteryPercentageRemaining(endpoint);
            await reporting.batteryVoltage(endpoint);
            await reporting.temperature(endpoint);
            await endpoint.read('msTemperatureMeasurement', ['measuredValue']);
            await endpoint.read('ssIasZone', ['iasCieAddr', 'zoneState', 'zoneStatus', 'zoneId']);
            await endpoint.read('genPowerCfg', ['batteryVoltage', 'batteryPercentageRemaining']);
        },

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by ronniebach** [comment]
great. thanks @Koenkk :-)

**Comment by ronniebach** [comment]
I see you removed the battery properties - which you should. Although this is a 230v mains connected it also has a built in battery and reports as well on that.

**Comment by Koenkk** [comment]
Added the battery!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by ronniebach** [comment]
Great. It appears in Z2M overview with ?/Unknown POWER 

How is this determined? It it hardcoded properties in the schneider_electric.js file - or is it retrieved in a status message from the device itself?
And does it behave as a router only if the coordinator knows it is non-battery powered?

**Comment by Koenkk** [comment]
It's based on a property read from the device.

> And does it behave as a router only if the coordinator knows it is non-battery powered?

Yes, the coordinator has no influence over the type (router/end device) of a device

**Comment by ronniebach** [comment]
Just wondering....

I can see in other issues that you have fixed the ?/Unknown POWER

And fixed by hardcoding on the specific device? (here in xiaomi.js )

```
            device.powerSource = 'Mains (single phase)';
            device.save();
```


https://github.com/Koenkk/zigbee2mqtt/issues/15568
https://github.com/Koenkk/zigbee-herdsman-converters/commit/2f98eac1b1ea98b03b980b259f25c68d53a57b84

**Comment by Koenkk** [comment]
@ronniebach applied the fix!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
