### ISSUE TITLE
 Add new fingerprint ({modelID: "TS0601", manufacturer name: "_TZE200_1fuxihti"})

### ISSUE THREAD

**Issue by eantonov-ea** [Koenkk/zigbee-herdsman-converters#6170]
Add new fingerprint ({modelID: "TS0601", manufacturer name: "**_TZE200_1fuxihti**"})

model: 'TS0601_cover_1

**Comment by eantonov-ea** [comment]
Add new fingerprint ({modelID: "TS0601", manufacturer name: "_TZE200_1fuxihti"})

model: 'TS0601_cover_1
![1233](https://github.com/Koenkk/zigbee-
![123](https://github.com/Koenkk/zigbee-herdsman-converters/assets/77960444/d30f0d89-f023-4827-ae77-5000d7f775c7)
herdsman-converters/assets/77960444/4ed58765-2464-4447-b743-0bc6f6fdcac7)

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by eantonov-ea** [comment]
Thank you very much!
