### ISSUE TITLE
Add Zigbee fingerbot plus fingerprint _TZ3210_j4pdtz9v

### ISSUE THREAD

**Issue by clau-bucur** [Koenkk/zigbee-herdsman-converters#6207]
I have bought a Fingerbot plus from Aliexpress and was recognized as a " TuYa TS0001 1 gang switch".

I expanded the TS0001_fingerbot fingerprint as follows:
```
fingerprint: tuya.fingerprint('TS0001', ['_TZ3210_dse8ogfy', '_TZ3210_j4pdtz9v']),
        ...
        whiteLabel: [
            ...
            tuya.whitelabel('Adaprox', 'TS0001_fingerbot_1', 'Zigbee fingerbot plus', ['_TZ3210_j4pdtz9v']),
        ],
```
And now my Fingerbot is working properly:
![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/47672949/8e6e82ab-c779-4d19-9685-e10998df283f)

**Comment by Koenkk** [comment]
`_TZ3210_j4pdtz9v` will be supported in todays release.
