### ISSUE TITLE
Support DC values in electrical_measurement converter (or all possible values)

### ISSUE THREAD

**Issue by juantxorena** [Koenkk/zigbee-herdsman-converters#6248]
I'm not sure if this is a bug report, a feature request, or a request for help, but here is it.

In the electrical_measurement converter there is a [lookup table](https://github.com/Koenkk/zigbee-herdsman-converters/blob/54973c12c30a287e6c9fd7b841f859f4a85d8496/src/converters/fromZigbee.js#L810) with a bunch of possible values, which AFAIK they are the supported values for this converted.

However, the standard and actually the [haElectricalMeasurement](https://github.com/Koenkk/zigbee-herdsman/blob/a93af4a886085ba8b944b5f6a46597d04328db9a/src/zcl/definition/cluster.ts#L3777) in the utils.ts file has all of them. If I understand the code correctly, all the possible values that come from zigbee will be identified, but then ignored in the converter, unless they are in the lookup table.

I actually need some dc values for a non commercial device I'm developing, so I don't know if I should do a pull request with them or not. However, I'm of the opinion that, if they are in the standard, they should be supported, so maybe all of them should be there in that table.

In any case, is there a way to support those values only for my installation? I'm not sure if I can put all of the things needed in an external converter.

**Comment by Koenkk** [comment]
Please make a PR to add those
