### ISSUE TITLE
nimly / easyAccess is limited to place usercodes on locations 0 - 49

### ISSUE THREAD

**Issue by DagBertelsen** [Koenkk/zigbee-herdsman-converters#6249]
The newer models of nimly supports pin code location from 000  to 999, however this seems to be limited to max 50 in code here:
https://github.com/Koenkk/zigbee-herdsman-converters/blob/54973c12c30a287e6c9fd7b841f859f4a85d8496/src/devices/onesti.ts#L68

Reference in the nimly code manual (in norwegian):
https://nimly.io/guides/no/code/no-code-installation-manual.pdf

the first locations 000, 001 and 002 are reserved for the master codes.
Locations 003 to 999 are reserved for user codes.

So could we increase the pinCodeCount to 1000 ?

**Comment by Koenkk** [comment]
Yes, please make a PR

**Comment by Koenkk** [comment]
Fixed in https://github.com/Koenkk/zigbee-herdsman-converters/pull/6271 thanks to @torarnehelgesen
