### ISSUE TITLE
TRADFRI bulb E14 WS candle 470lm LED2107C4

### ISSUE THREAD

**Issue by ggtimtom** [Koenkk/zigbee-herdsman-converters#6253]
Hello, i never did a pullrequest, so i dropped my definition of the "IKEA bulb E14 WS candle" here.
Perhaps its not perfect, but it works for me.

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const legacy = require('zigbee-herdsman-converters/lib/legacy');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const utils = require('zigbee-herdsman-converters/lib/utils');
const globalStore = require('zigbee-herdsman-converters/lib/store');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['TRADFRI bulb E14 WS candle 470lm'],
    model: 'LED2107C4',
    vendor: 'IKEA',
    description: 'TRADFRI bulb E14 WS candle 470lm, wireless dimmable white spectrum/chandelier opal white',
    extend: extend.light_onoff_brightness_colortemp({colorTempRange: [250, 454]}), 
    ota: ota.tradfri,
};

module.exports = definition;

Regards, Günter

**Comment by Koenkk** [comment]
Added, thanks!

**Comment by ascriba** [comment]
thank you! worked for me!

**Comment by WeMakeComputersWork** [comment]
Since the last firmware update (3.0.10), the state switch reacts incorrectly.
Both events (state=true, state=false) lead to toggling instead of setting the status.
