### ISSUE TITLE
Hue smart button - version 9290030171A

### ISSUE THREAD

**Issue by ygageot** [Koenkk/zigbee-herdsman-converters#6269]
I just received yesterday new **Hue smart button**. on the back it is written model 9290030171A and reported as zigbeeModel RDM004. I imagine it is compatible with 929003017102... Is it possible to add it as Philips device

**Comment by Koenkk** [comment]
Could you check if the issue is fixed with the following external converter: https://gist.github.com/Koenkk/b66f2d1c013a0d7ea69a971f9a0734d0

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if issue is fixed

**Comment by ygageot** [comment]
thanks for the file. 
I had a small syntax error about e**.enum**.
I replace it with **exposes.enum**
I hope it is the good method..
After reset  the module is visible as previous ones.
**But it doesn't work ! 
when I close any of 2 contacts nothing happens (usually I have _left_press_,.......)**
I set it in _dual_push_button_ mode

log seems to me 👍 
Warning 2023-10-12 07:14:15Device '0x001788010d000539' left the network
Info 2023-10-12 07:14:15MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x001788010d000539","ieee_address":"0x001788010d000539"},"type":"device_leave"}'
Info 2023-10-12 07:14:55Device '0x001788010d000539' joined
Info 2023-10-12 07:14:55MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x001788010d000539","ieee_address":"0x001788010d000539"},"type":"device_joined"}'
Info 2023-10-12 07:14:55Starting interview of '0x001788010d000539'
Info 2023-10-12 07:14:56MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x001788010d000539","ieee_address":"0x001788010d000539","status":"started"},"type":"device_interview"}'
Debug 2023-10-12 07:14:56Device '0x001788010d000539' announced itself
Info 2023-10-12 07:14:56MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x001788010d000539","ieee_address":"0x001788010d000539"},"type":"device_announce"}'
Debug 2023-10-12 07:14:56Device '0x001788010d000539' announced itself
Info 2023-10-12 07:14:56MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x001788010d000539","ieee_address":"0x001788010d000539"},"type":"device_announce"}'
Info 2023-10-12 07:14:56Successfully interviewed '0x001788010d000539', device has successfully been paired
Info 2023-10-12 07:14:56Device '0x001788010d000539' is supported, identified as: Philips Hue wall switch module (929003017102)
Info 2023-10-12 07:14:56MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"Hue wall switch module","exposes":[{"access":1,"description":"Remaining battery in %, can take up to 24 hours before reported.","name":"battery","property":"battery","type":"numeric","unit":"%","value_max":100,"value_min":0},{"access":1,"description":"Triggered action (e.g. a button click)","name":"action","property":"action","type":"enum","values":["left_press","left_press_release","right_press","right_press_release","left_hold","left_hold_release","right_hold","right_hold_release","toggle"]},{"access":7,"name":"device_mode","property":"device_mode","type":"enum","values":["single_rocker","single_push_button","dual_rocker","dual_push_button"]},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"929003017102","options":[],"supports_ota":false,"vendor":"Philips"},"friendly_name":"0x001788010d000539","ieee_address":"0x001788010d000539","status":"successful","supported":true},"type":"device_interview"}'

**Comment by Koenkk** [comment]
```
{"friendly_name":"0x001788010d000539","ieee_address":"0x001788010d000539"},"type":"device_leave"}'
Info 2023-10-12 07:14:55Device '0x001788010d000539' joined
Info 2023-10-12 07:14:55MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x001788010d000539","ieee_address":"0x001788010d000539"},"type":"device_joined"}'
```

It looks like you reset the device somehow, do you get any `Received zigbee message` in the log when triggering an action?

**Comment by ygageot** [comment]
That"s true.
There is no action message... 
with another moule RDM004, ir works as usual. 
On the first module I made so many resets.... Usually I know how to do reset (I have 10 module in house) but for this one, perhaps something changed after the >10sec reset button procedure.... Thanks

**Comment by Koenkk** [comment]
So one of your RDM04 module works with this converter and one not?

**Comment by yodax** [comment]
This works for me! 

I had a paired module and I had to remove it from zigbee2mqtt to get it to work. After repairing with the fix in place it works as expected. Thanks for this incredible work.

**Comment by yodax** [comment]
I can’t get one of these newer switches to go into dual rocker mode. When I try to set the device mode to dual rocker mode I get an error: 


Error 2023-10-28 18:56:53Publish 'set' 'device_mode' to 'Gang beneden meterkast switch' failed: 'Error: Write 0x001788010d0006ae/1 genBasic({"52":{"value":2,"type":48}}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4107,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 64222 - 1 - 137 - 0 - 4 after 10000ms)'

Is this something I’m doing wrong? Or is it related to the new switch support. It is wired on port s2 to a different rocker. When you toggle that rocker nothing triggers in the status screen too.

**Comment by yodax** [comment]
Never mind, it needed to be recently active for it to be stored. Found it in the other docs for the previous switches. 

So everything is working as expected with the fix!
