### ISSUE TITLE
Adding support for icasa Zigbee 3.0 keypad ICZB-KPD18S

### ISSUE THREAD

**Issue by rutgerhendriks** [Koenkk/zigbee-herdsman-converters#629]
The ICZB-KPD18S has 8 buttons, top left is O (OFF), top right is I (ON), then there are buttons S1, S3 and S5 on the left under the OFF button and S2, S4 and S6 on the right under the ON button.

I added initial support by adding to devices.js:
>
        {
        zigbeeModel: ['ICZB-KPD18S'],
        model: 'ICZB-KPD18S',
        vendor: 'iCasa',
        description: 'Zigbee 3.0 Keypad 6',
        supports: 'on/off',
        fromZigbee: [],
        toZigbee: [],
    },

then pressing the 8 buttons gives the logging as attached.
How to proceed with getting the buttons configured/functioning? I'm missing the documentation for that it seems..

[icasa keypad pulse 8S.txt](https://github.com/Koenkk/zigbee-shepherd-converters/files/3639675/icasa.keypad.pulse.8S.txt)

**Comment by Koenkk** [comment]
Can you try with

```js
    {
    zigbeeModel: ['ICZB-KPD18S'],
    model: 'ICZB-KPD18S',
    vendor: 'iCasa',
    description: 'Zigbee 3.0 Keypad 6',
    supports: 'on/off',
    fromZigbee: [fz.nue_click, fz.tint404011_on, fz.tint404011_off],
    toZigbee: [],
},
```

**Comment by rutgerhendriks** [comment]
Cool, that seems to do stuff, see updated logging at the bottom.
I'll check homeassistant next when I have time. I'll add to 
lib/extension/homeassistant.js something like:
'ICZB-KPD18S': [configurations.sensor_action],

Is that ok?

[icasa keypad pulse 8S.txt](https://github.com/Koenkk/zigbee-shepherd-converters/files/3640076/icasa.keypad.pulse.8S.txt)

**Comment by Koenkk** [comment]
It should be click, but the fromZigbee converters are not consistent with each other.

Can you make a pr with the current definition? I will integrate and fix it further.
