### ISSUE TITLE
Sending a message to eWeLink smart plugs occasionally stalls

### ISSUE THREAD

**Issue by chetbox** [Koenkk/zigbee-herdsman-converters#6332]
Calling [`await converter.convertSet(...)`](https://github.com/Koenkk/zigbee-herdsman-converters/blob/06ff10bd56b50e402ecd51740df9d5cfbc5ffc99/src/lib/types.ts#L134) with an eWeLink Smart Plug device occasionally never resolves and this breaks the control flow of our application.

Currently I am working around this using a timeout implemented with `Promise.race` however I'm not sure if this is causing a memory leak with unresolved promises internally in the library.

[This PR](https://github.com/Koenkk/zigbee-herdsman-converters/pull/6306) was intended to fix the issue but I misunderstood the code so I am creating an issue instead.

**Comment by Koenkk** [comment]
There should always be a default timeout, could you provide the herdsman debug logging of this?

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

**Comment by chetbox** [comment]
> There should always be a default timeout, could you provide the herdsman debug logging of this?
> 
> See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

Thanks for confirming that! I'm not using `zigbee2mqtt` but using `zigbee-herdsman-converters` directly. Is there an equivalent?

**Comment by Koenkk** [comment]
Since you are still using zigbee-herdsman, setting `DEBUG=zigbee-herdsman*` will still show the required logging.

**Comment by chetbox** [comment]
Thanks! I'll give that a go. I only see this problem after a day or two of operation so I'll report back when I catch it in the act.

**Comment by chetbox** [comment]
I have seen the same issue a couple of times but I haven't seen any logging coming from Zigbee Herdsman even with `DEBUG=zigbee-herdsman*` set. I also didn't seen a unhandled exception coming from `convertSet(...)` so I believe the promise did not resolve.

It's great to know that there should be a timeout internally within the call to `convertSet(...)`. I was missing some logic to handle the rejected promise which I've now added back in.

I'll keep monitoring the logs and report back if I find anything.
