### ISSUE TITLE
Add support for Namron 4512768 16a 2ch wall switch

### ISSUE THREAD

**Issue by xses79** [Koenkk/zigbee-herdsman-converters#6362]
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const extend = require('zigbee-herdsman-converters/lib/extend');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const utils = require('zigbee-herdsman-converters/lib/utils');
const e = exposes.presets;
const ea = exposes.access;

module.exports = [
    {
        zigbeeModel: ['4512768'],
        model: '4512768',
        vendor: 'Namron',
        description: 'Zigbee 2 channel switch Namron',
        fromZigbee: [fz.on_off, fz.electrical_measurement, fz.metering, fz.power_on_behavior, fz.ignore_genOta,],
        toZigbee: [tz.on_off, tz.power_on_behavior],
        exposes: [e.switch().withEndpoint('l1'), e.switch().withEndpoint('l2'),
            e.power_on_behavior(['off', 'on', 'previous']), 
            e.energy(),
            e.numeric('voltage_l1', ea.STATE).withUnit('V').withDescription('Phase 1 voltage'),
            e.numeric('voltage_l2', ea.STATE).withUnit('V').withDescription('Phase 2 voltage'),
            e.numeric('current_l1', ea.STATE).withUnit('A').withDescription('Phase 1 current'),
            e.numeric('current_l2', ea.STATE).withUnit('A').withDescription('Phase 2 current'),
            e.numeric('power_l1', ea.STATE).withUnit('W').withDescription('Phase 1 power'),
            e.numeric('power_l2', ea.STATE).withUnit('W').withDescription('Phase 2 power'),],
        endpoint: (device) => {
            return {'l1': 1, 'l2': 2};
        },
        meta: {multiEndpoint: true, publishDuplicateTransaction: true},
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint1 = device.getEndpoint(1);
            const endpoint2 = device.getEndpoint(2);
            await reporting.bind(endpoint1, coordinatorEndpoint, ['genOnOff', 'haElectricalMeasurement', 'seMetering']);
            await reporting.bind(endpoint2, coordinatorEndpoint, ['genOnOff']);
            await reporting.onOff(endpoint1);
            await reporting.onOff(endpoint2);
            await reporting.currentSummDelivered(endpoint1);
        },
    },
];
![4512768](https://github.com/Koenkk/zigbee-herdsman-converters/assets/76107252/2c898e3c-827d-471a-8751-fcdc26a6129f)

**Comment by Koenkk** [comment]
Could you make a pull request for this?

**Comment by bruberg** [comment]
I tried adding this code as an external converter for a wall switch configured as a single channel switch.

`Zigbee2MQTT:error 2023-11-06 10:42:13: Device 'namron_switch' has no endpoint 'l2'`

Correspondingly, L2 voltage/energy/power are all NULL values.

I am not familiar with how to add or modify code for device support, but this case should probably be handled somehow.

**Comment by xses79** [comment]
> I tried adding this code as an external converter for a wall switch configured as a single channel switch.
> 
> `Zigbee2MQTT:error 2023-11-06 10:42:13: Device 'namron_switch' has no endpoint 'l2'`
> 
> Correspondingly, L2 voltage/energy/power are all NULL values.
> 
> I am not familiar with how to add or modify code for device support, but this case should probably be handled somehow.

Which kind of switch?

**Comment by bruberg** [comment]
Btw it looks like the readings are 10x the real values. With a ~30W lamp connected, L1 voltate reports 2348 V and L1 current reports 169A.

**Comment by xses79** [comment]
Yes, i see that. This is the first attempt and i totally forgot that it can be configured as a 1ch switch...

**Comment by bruberg** [comment]
Seems we will need some assistance on this one. @Koenkk any pointers on how to move forward?

In short: The initial config seems quite OK, but the readings need adjustments and we need to somehow tackle that the device can act as a one or two gang switch.

**Comment by Koenkk** [comment]
Could you provide the data/database.db entry of this device?

**Comment by bruberg** [comment]
```
{
  "id": 91,
  "type": "Router",
  "ieeeAddr": "0xdc8e95fffe3579e7",
  "nwkAddr": 28630,
  "manufId": 4098,
  "manufName": "Namron AS",
  "powerSource": "Mains (single phase)",
  "modelId": "4512768",
  "epList": [
    1
  ],
  "endpoints": {
    "1": {
      "profId": 260,
      "epId": 1,
      "devId": 256,
      "inClusterList": [
        0,
        3,
        4,
        5,
        6,
        1794,
        2820,
        4096
      ],
      "outClusterList": [
        25
      ],
      "clusters": {
        "genBasic": {
          "attributes": {
            "32768": 1,
            "modelId": "4512768",
            "manufacturerName": "Namron AS",
            "powerSource": 1,
            "zclVersion": 8,
            "appVersion": 0,
            "stackVersion": 0,
            "hwVersion": 0,
            "dateCode": "20230410",
            "swBuildId": "1.09"
          }
        },
        "haElectricalMeasurement": {
          "attributes": {
            "rmsVoltage": 2390,
            "activePower": 0,
            "rmsCurrent": 0
          }
        },
        "seMetering": {
          "attributes": {
            "currentSummDelivered": [
              0,
              144
            ]
          }
        },
        "genOnOff": {
          "attributes": {
            "startUpOnOff": 1,
            "onOff": 0
          }
        }
      },
      "binds": [
        {
          "cluster": 6,
          "type": "endpoint",
          "deviceIeeeAddress": "0x00124b0024c94620",
          "endpointID": 1
        },
        {
          "cluster": 2820,
          "type": "endpoint",
          "deviceIeeeAddress": "0x00124b0024c94620",
          "endpointID": 1
        },
        {
          "cluster": 1794,
          "type": "endpoint",
          "deviceIeeeAddress": "0x00124b0024c94620",
          "endpointID": 1
        }
      ],
      "configuredReportings": [],
      "meta": {}
    }
  },
  "appVersion": 0,
  "stackVersion": 0,
  "hwVersion": 0,
  "dateCode": "20230410",
  "swBuildId": "1.09",
  "zclVersion": 8,
  "interviewCompleted": true,
  "meta": {},
  "lastSeen": 1701407955098,
  "defaultSendRequestWhen": "immediate"
}
```

Note: This is when using this post's config as an external converter. Please let me know if I should provide these data without the external converter.

**Comment by Koenkk** [comment]
Are you really sure this is a 2 gang switch? It has only 1 endpoint where I would expect 2 (each for a gang)

**Comment by bruberg** [comment]
> Are you really sure this is a 2 gang switch? It has only 1 endpoint where I would expect 2 (each for a gang)

The switch can be configured as 1 or 2 gang. Mine is configured as 1 gang. Perhaps OP could provide the same database entry for a 2 gang switch.

**Comment by bruberg** [comment]
Looks like some work has been done in Koenkk/zigbee2mqtt/issues/19837

**Comment by Koenkk** [comment]
That should work with the external converter from the [OP](https://github.com/Koenkk/zigbee-herdsman-converters/issues/6362#issue-1967752045)

**Comment by bruberg** [comment]
With the latest release the switch seems to integrate perfectly. Thank you!

**Comment by Koenkk** [comment]
Do `current_l2`, `power_l2` and `voltage_l2` also work correctly?
