### ISSUE TITLE
Philips Hue Dimmer Switch Not Working / Intermittent Issue

### ISSUE THREAD

**Issue by rm2kdev** [Koenkk/zigbee-herdsman-converters#637]
Okay so I'll try my best to describe this, i saw a few people talking recently about hue dimmer switches not working i am also experiencing something similar (i have 20 other devices working, and have written my own driver for the 3a/nue switches so i'm feeling confidant its not a user error issue)

So pairing the hue dimmer switch (brand new, never used) pulled battery tab zigbee2mqtt found it and registered an entry in my configuration.yaml
![image](https://user-images.githubusercontent.com/845245/65506699-c209ea80-defe-11e9-9929-74cd97e24dfa.png)

Zigbee2mqtt found it and paired and identified it as a hue remote.

Pressing buttons i can see events emitting on its mqtt namespace. So far so good.

I come back a few hours later press a button, nothing little green light flashes on the device no message in zigbee2mqtt logs i reset the device holding down 4 buttons light goes green, flickers red/orange back to green then off.

Press buttons, no events.

I leave it for a few hours come back, press buttons the events are now working as expected.

A few hours later pressing buttons on the remote no green light device appears dead now? (i saw someone else mention a similar issue) 

So i deleted all entries from DB and Conf.yaml restarted zigbee2mqtt, repaired, db and conf entries are back lights working on the controller again when pressing buttons events are arriving. 10 to 15 minutes later back to no events, restart zigbee2mqtt events are arriving 10 to 15 mins later no events.

If its worth noting my current setup consists of a bunch of outlets acting as routers throughout the house, a couple of hue lights paired zigbee direct.

I'm using 1.6 and coordinator 20190619 on the cc2531 usb stick

`615]:   zigbee2mqtt:info 9/24/2019, 7:16:44 PM Logging to directory: '/opt/zigbee2mqtt/data/log/2019-09-24.19-16-42'
Sep 24 19:16:44 raspberrypi npm[6615]:   zigbee2mqtt:info 9/24/2019, 7:16:44 PM Starting zigbee2mqtt version 1.6.0 (commit #e26ad2a)
Sep 24 19:16:44 raspberrypi npm[6615]:   zigbee2mqtt:info 9/24/2019, 7:16:44 PM Starting zigbee-shepherd
Sep 24 19:16:46 raspberrypi npm[6615]:   zigbee2mqtt:info 9/24/2019, 7:16:46 PM zigbee-shepherd started
Sep 24 19:16:46 raspberrypi npm[6615]:   zigbee2mqtt:info 9/24/2019, 7:16:46 PM Coordinator firmware version: '20190619'
`

upon restarting zigbee2mqtt it does seem to receive a single event from the device.
`Sep 24 19:16:48 raspberrypi npm[6615]:   zigbee2mqtt:info 9/24/2019, 7:16:48 PM MQTT publish: topic 'zigbee2mqtt/0x0017880106b7a3b5', payload '{"battery":100,"linkquality":26,"counter":1,"brightness":155}'
`

Anyway I'm not 100% sure what is going on with this one, but i'd seen a couple of other reports recently and also am experiencing some weirdness so i figured i'd raise it and see if any of my details can help pinpoint whats going on.

**Comment by rm2kdev** [comment]
Just deleted it from DB and Conf again, restarted zb2mqtt, put the device next to the cc2531 and held the pair button for 10 seconds, waited for the lights to "do their thing"

Came back to the computer, no pairing notification in the console however
`Sep 24 19:23:41 raspberrypi npm[6694]:   zigbee2mqtt:error 9/24/2019, 7:23:41 PM Cannot get the Node Descriptor of the Device: 0x0017880106b7a3b5 (Error: Timed out after 10000 ms)
Sep 24 19:24:01 raspberrypi npm[6694]:   zigbee2mqtt:error 9/24/2019, 7:24:01 PM Cannot get the Node Descriptor of the Device: 0x0017880106b7a3b5 (Error: Timed out after 10000 ms)
`

From previous attempts i know this is the right device the ieeeAddr matches previous successful pairs

**Comment by rm2kdev** [comment]
Just pulled another brand new one from the box (have a stack here ready to go) initiated the pairing

`Sep 24 19:34:13 raspberrypi npm[6782]:   zigbee2mqtt:error 9/24/2019, 7:34:13 PM Cannot get the Node Descriptor of the Device: 0x001788010672aacb (Error: Timed out after 10000 ms)
Sep 24 19:34:25 raspberrypi npm[6782]:   zigbee2mqtt:info 9/24/2019, 7:34:25 PM New device 'RWL021' with address 0x001788010672aacb connected!
Sep 24 19:34:25 raspberrypi npm[6782]:   zigbee2mqtt:info 9/24/2019, 7:34:25 PM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":"0x001788010672aacb","meta":{"modelID":"RWL021"}}'
Sep 24 19:34:33 raspberrypi npm[6782]:   zigbee2mqtt:info 9/24/2019, 7:34:33 PM MQTT publish: topic 'zigbee2mqtt/0x001788010672aacb', payload '{"battery":100,"linkquality":26}'
Sep 24 19:35:04 raspberrypi npm[6782]:   zigbee2mqtt:info 9/24/2019, 7:35:04 PM Device incoming...
`

It found the device, identified it, connected to it then for some reason said a device was incoming (only new connecting device is this one)

And none of the buttons do anything, no green light when pressing, no mqtt events.

Update: 5 minutes later this device is also now working i will monitor and report back, there was something funky going on i started attempting to use these devices 3 days ago and have not been able to make a reliable device until just now.

**Comment by rm2kdev** [comment]
Its been 3 hours since all of this just want to post an update.

I installed 3 more direct zigbee connected hue lights in an attempt to bolster the network thinking maybe the signal strength was too low?

After doing so both dimmers were getting between 30 ~ 70 link quality depending on position in the room (3x4m room)

Both worked fine for about 3 hours, and the last hour both have stopped working, the last message i got from either of them was me pressing buttons

`Sep 24 21:41:58 raspberrypi npm[7731]:   zigbee2mqtt:info 9/24/2019, 9:41:58 PM MQTT publish: topic 'zigbee2mqtt/Hue Remote DEV', payload '{"battery":100,"linkquality":70,"counter":1,"brightness":255,"action":"off-press","duration":0}'
`

**Comment by rm2kdev** [comment]
Update 10 hours since last comment,

Both hue remotes have continued to not work, no logs available as there is nothing in the logs.

Power cycled both remotes (holding 4 buttons) neither are responding.

One difference between the other days, the green light flickers when pressing buttons but nothing comes through to z2m

**Comment by rm2kdev** [comment]
Update a further 10 hours later,

I've been working for most of the day so i haven't had much time to test. periodically throughout the day i hit a button on the remote to observe the action.

Throughout the day both remotes were not talking to z2m, green light no message at lunch i repaired one of them holding the setup button for 10 seconds until the lights flashed still no messages or anything in console.

I've just tried repairing both, no messages no incoming devices etc and neither are emitting messages in the z2m console.

It may be worth noting that i have a stack of temp sensors, motion sensors, zigbee power switches and hue lights all connected and functioning normally its just these remotes having this weird behavior.

I've re flashed my cc2531 stick with the source routing firmware (thinking maybe i had too many devices currently at 20ish connected) but that has not helped.

Distance to cc2531 stick is about 6 meters, however in the room i am in i have 3 hue lights and 3 Nue/3a outlets which should be functioning as repeaters

here is my network graph, this was taken last night before i added 4 more hue lights (trying to add more devices that can route) 3 of those power switches were in this room with the hue dimmers 
![download](https://user-images.githubusercontent.com/845245/65593750-baf8e000-dfc3-11e9-8db1-bda3ae18e542.png)

**Comment by Koenkk** [comment]
It might be interesting to see what happens when you sniff the traffic and press a button (https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html).

**Comment by rm2kdev** [comment]
Interesting, okay i've ordered another cc stick i'll flash it when it gets here and report back 😄

**Comment by rm2kdev** [comment]
Yeah, at this stage, I'm thinking I will sell the Hue Dimmer, as I can't get it to work reliability, it tends to stop working on a 2-3 day basis. A couple of notes:

- The input is been recorded by zigbee-shepherd, which shows almost all the information, so its not dropping out per-se, it just stops working for some reason.

- To (re)establish connection, Zigbee2MQTT must be restarted and the Hue must be repaired (holding all four buttons). Re-pairing without restarting does not work. 

- This model is a newer model of the Hue Dimmer, so I expect others may experience this issue in the near future. For now my intention is to use an IR remote and write a MQTT python script integration.

It's frustrating but I'm really not sure how to proceed from here.

_Originally posted by @thehaxxa in https://github.com/Koenkk/zigbee2mqtt/issues/531#issuecomment-435305969_



Following the steps outlined by this user i was able to get my hue remotes paired, however the are still experiencing dropouts and when those dropouts occur just like the users on that thread the whole system has to be restarted and repaired in order to get communication going again (and even then its not reliable, having to restart z2m multiple times and repair multiple times before it catches)

if it helps the hue dimmer switches are both model 324131137411 @Koenkk i saw in another thread you mentioned yours are working as expected, could we compare model numbers and see if there is a silent revision or possibly a location based revision (i am in Australia, maybe we got a different version of the product here)

**Comment by rm2kdev** [comment]
Following along with the notes in https://github.com/Koenkk/zigbee2mqtt/issues/531 i changed to another zigbee channel and repaired everything.

So far, everything has connected including hue remotes and appear to be working reliably however since this issue can take days to present i'll continue monitoring and upload some more details when my sniffer arrives.

**Comment by allofmex** [comment]
You may also have a look at  https://github.com/Koenkk/zigbee2mqtt/issues/1474 . If possible it would be good to know if the dimmer are stable if no router devices (powered) are in network.

**Comment by rm2kdev** [comment]
Thats an interesting angle i will sniff this as soon as the sniffer arrives! i do have lots of routers connected as of 2 hours ago they appear to be stable but i will keep monitoring.

**Comment by Koenkk** [comment]
This may be caused due to https://github.com/Koenkk/zigbee2mqtt/issues/2017

**Comment by rm2kdev** [comment]
@Koenkk Interesting I had a read through that, it could be that.

To keep the thread updated i've not replied in 7 days mainly becuase
1, I'm still waiting for my second cc stick to arrive so i can do some sniffing and
2, I flashed to source routing, deleted z2m, started again, set my channel to 20 in config and repaired everything starting with the 3A Switches (Hoping that they get picked up as the first 5 devices)

Since doing #2 my hue dimmer switches have been connected reliably, they have stopped working however pressing all four buttons on the remote and giving it 10 seconds to repair seems to be working now.

There is probably still an issue going on, but its much much better than it was before i performed #2 and the 4 button reset is actually working where as before it wasnt (which was probably related to Koenkk/zigbee2mqtt#2017)

I'll wait for my sniffer to arrive so i can verify whats happening when they drop.

**Comment by Koenkk** [comment]
Just released a fix for https://github.com/Koenkk/zigbee2mqtt/issues/2017 in the dev branch, let me know if this also fixes this issue.

**Comment by rm2kdev** [comment]
Okay so not great so far, i just git checked out dev, npm installed and restarted z2m it wiped my database and everything is gone.

Will take a while before i can get back to you regarding fixed or not as i have to rebuild my network.

**Comment by rm2kdev** [comment]
With dev, while trying to pair im getting permission errors on the pi
Oct 06 14:50:48 raspberrypi npm[13681]: (node:13696) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, open '/opt/zigbee2mqtt/data/configuration.yaml'

**Comment by rm2kdev** [comment]
Making progress on restoring the network,

Some devices are responding others however:

Oct 06 15:09:00 raspberrypi npm[14082]: zigbee2mqtt:error 2019-10-06T07:09:00: Entity 'ROLamp' is unknown
Oct 06 15:09:00 raspberrypi npm[14082]: zigbee2mqtt:debug 2019-10-06T07:09:00: Received MQTT message on 'zigbee2mqtt/Hue/Lights/Laundry/Roof/set' with data '{"state":"OFF"}'
Oct 06 15:09:00 raspberrypi npm[14082]: zigbee2mqtt:info  2019-10-06T07:09:00: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"entity_not_found","message":{"friendly_name":"Hue/Lights/Laundry/Roof"}}'
Oct 06 15:09:00 raspberrypi npm[14082]: zigbee2mqtt:error 2019-10-06T07:09:00: Entity 'Hue/Lights/Laundry/Roof' is unknown
Oct 06 15:09:00 raspberrypi npm[14082]: zigbee2mqtt:debug 2019-10-06T07:09:00: Received MQTT message on 'zigbee2mqtt/Hue/Lights/3DPrint/Roof/set' with data '{"state":"OFF"}'
Oct 06 15:09:00 raspberrypi npm[14082]: zigbee2mqtt:info  2019-10-06T07:09:00: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"entity_not_found","message":{"friendly_name":"Hue/Lights/3DPrint/Roof"}}'
Oct 06 15:09:00 raspberrypi npm[14082]: zigbee2mqtt:error 2019-10-06T07:09:00: Entity 'Hue/Lights/3DPrint/Roof' is unknown
Oct 06 15:09:00 raspberrypi npm[14082]: zigbee2mqtt:debug 2019-10-06T07:09:00: Received MQTT message on 'zigbee2mqtt/Hue/Lights/RyansOffice/Lamp/set' with data '{"state":"OFF"}'
Oct 06 15:09:00 raspberrypi npm[14082]: zigbee2mqtt:info  2019-10-06T07:09:00: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"entity_not_found","message":{"friendly_name":"Hue/Lights/R

"are unknown" they are in the database and configuration but appear to not be connecting

**Comment by Koenkk** [comment]
Are they in configuration.yaml under that name?

**Comment by rm2kdev** [comment]
Yep, i migrated it in from my 1.6.0-stable build :) just going around reparing everything manually they say something like "Device announced its self" after I repair them.

**Comment by rm2kdev** [comment]
One strange thing, i have a stack of power outlets throughout the house.
4 in the lounge room specifically assigned to a group "Lounge Room Power" those are working with no problem, no need to repair.

the rest (same model) scattered throughout the house "Device is unknown" then i repair them and get "Device announced its self" and they work fine.

not a huge problem, just a pain to repair it but im not sure why they are disconnected with the restored data from 1.6.0-stable.

**Comment by rm2kdev** [comment]
Okay everything is back up and running.

I've got another hue remote here, paired it first try no problems.

Old remote /dimmer/dev1 and /dimmer/dev2
did not work initially, held 4 buttons, connected paired no problems.

Have attempted to make it fail by moving around the house resetting them at various locations (4 button reset) and every time z2m picks them up and pairs without issue.

I dont have a sniffter yet, but im going to go out on a limb and say this is resolved now, they were working reliably on another channel but 4 button reset was still sketchy wouldn't take 100% of the time.

Now they are all taking 100% of the time.

**Comment by rm2kdev** [comment]
Just so this doesnt go stale without anyone knowing what happened.

Long story short... few resync's later, updated to -dev branch... using a new ccusb stick with a bigger antenna on it and i haven't had this problem happen again.
