### ISSUE TITLE
zigbee2mqtt-Docker, how can i use zigbee-shepherd-converters ?

### ISSUE THREAD

**Issue by ulli07** [Koenkk/zigbee-herdsman-converters#638]
Hi together,

I'm a newbie.
I use a synology DS918+ and 3 dockers -> zigbee2mqtt 1.6.0, mosquitto-mqtt and node-red.
That works fine together with the CC2531 USB sniffer and the xiaomi door sensor MCCGQ11LM.

And now, I want to use the xiaomi-body-sensor RTCGQ11LM and i got an error "..Device with modelID '' is not supported."

So, i read and i know, that I have to use the "zigbee-shepherd-converters", but I don't know how to handle the "zigbee-shepherd-converters" with my dockers.

Could anyone help me ?

Thanks a lot !

Ulli

**Comment by Koenkk** [comment]
This device is already be supported, probably something went wrong during pairing or you didn't follow https://www.zigbee2mqtt.io/devices/MCCGQ11LM.html#pairing.

You should be able to fix your issue by pressing the reset button on the sensor once.
