### ISSUE TITLE
Issue integrating "unsupported" ZB Motion & Illuminance Sensor 

### ISSUE THREAD

**Issue by maudasilva-10** [Koenkk/zigbee-herdsman-converters#6385]
The device I am trying to integrate in HA is this one: https://www.aliexpress.us/item/3256803705327106.html
It is a TS0601 by the '_TZE200_f1pvdgoh' manufacturer. It was advertised as a Tuya device. 
I don't have a Tuya Hub and use Zigbee2MQTT over a Sonoff Coordinator. 

I got so far as getting the illuminance to work with the code below. The 'linkquality' works to no credit to me. I honestly don't know how. But I have no idea how to get the needed information 'tuyaDatapoints' for battery level and the most important motion/occupancy. 

I am new to coding and any help would be greatly appreciated. 

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const definition = {
    // Since a lot of TuYa devices use the same modelID, but use different datapoints
    // it's necessary to provide a fingerprint instead of a zigbeeModel
    fingerprint: [
        {
            // The model ID from: Device with modelID 'TS0601' is not supported
            // You may need to add \u0000 at the end of the name in some cases
            modelID: 'TS0601',
            // The manufacturer name from: Device with modelID 'TS0601' is not supported.
            manufacturerName: '_TZE200_f1pvdgoh',
        },
    ],
    model: 'TS0601',
    vendor: 'TuYa', // _TZE200_f1pvdgoh ???
    description: 'Motion and Illuminance Zigbee Sensor',
    fromZigbee: [tuya.fz.datapoints],
    toZigbee: [tuya.tz.datapoints],
    onEvent: tuya.onEventSetTime, // Add this if you are getting no converter for 'commandMcuSyncTime'
    configure: tuya.configureMagicPacket,
    exposes: [
        e.battery(), 
        e.illuminance_lux(), 
        e.linkquality(), 
        e.occupancy()],
        // Here you should put all functionality that your device exposes
    meta: {
        // All datapoints go in here
        tuyaDatapoints: [
            //[1, 'occupancy' , tuya.valueConverter.trueFalse1],
            [101, 'illuminance_lux' , tuya.valueConverter.raw],
            //[3, 'battery' , tuya.valueConverter.battery],
        ],
    },
};

module.exports = definition;

This is the state reported last for the device: 
"0xa4c138558fb7dff5": {
        "linkquality": 120,
        "illuminance_lux": 26,
        "illuminance": 34,
        "presence": true,
        "occupancy": false
    }

**Comment by MD0005** [comment]
Hello, Im having issue integrating the same device in ZHA / TS0601 by the '_TZE200_f1pvdgoh'.
I wuld be very happy with any solution. Thank you.
