### ISSUE TITLE
TRADFRI bulb GU10 WS 345lm 

### ISSUE THREAD

**Issue by trinoklingenberg** [Koenkk/zigbee-herdsman-converters#6388]
Hello 

there is probably a new 
TRADFRI bulb GU10 WS 345lm 

https://www.ikea.com/de/de/p/tradfri-led-leuchtmittel-gu10-345-lm-
smart-wireless-dimmable-white-spectrum-50547413/

These are not recognised in the Zigbee adapter.

thank you for taking the time and effort to provide us with this

**Comment by Koenkk** [comment]
Supported in z2m 1.33.2

**Comment by trinoklingenberg** [comment]
Hello
I have the current version vomn zigbee
they are new from ikea and are not recognized.
i just bought them 2 days ago from ikea and they are declared as new in the store

trino
Von: Koen Kanters ***@***.***>
Gesendet: Freitag, 3. November 2023 19:50
An: Koenkk/zigbee-herdsman-converters ***@***.***>
Cc: Trino Klingenberg ***@***.***>; Author ***@***.***>
Betreff: Re: [Koenkk/zigbee-herdsman-converters] TRADFRI bulb GU10 WS 345lm (Issue #6388)


Supported in z2m 1.33.2
