### ISSUE TITLE
SONOFF SNZB-02P unsupported attribute

### ISSUE THREAD

**Issue by Pferdebockwurst** [Koenkk/zigbee-herdsman-converters#6396]
With commit #5796 support for the new temperature and humidity sensor SNZB-02P from SONOFF has been added. I have bought a couple of these. While I have been able to add them to my network and they work fine so far, during configuration the following error occurred:

`02Configure failed: Error: ConfigureReporting 0x84ba20fffed24028/1 genPowerCfg([{"attribute":"batteryVoltage","minimumReportInterval":3600,"maximumReportInterval":7200,"reportableChange":0}], {"sendWhen":"active","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')`

**Comment by Pferdebockwurst** [comment]
@Koenkk Is there anything I can do to debug and solve this error? Do you need additional information?

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by Pferdebockwurst** [comment]
Thanks! So that means the device doesn't support reporting the battery voltage at all, right? That's kind of weird, as I thought the initial commit to support this device was authored by the SONOFF developers.

**Comment by Koenkk** [comment]
Yes based on your logging it doesn't support it
