### ISSUE TITLE
Missing value "current_heating_setpoint"

### ISSUE THREAD

**Issue by xstable** [Koenkk/zigbee-herdsman-converters#6397]
I've found that there is a parameter: `current_heating_setpoint` for the heat-valve: 

![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/1778068/a8cc24f9-cb3d-49e1-a2c6-45a967882746)

![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/1778068/8bfa0d3e-3374-4b50-957b-7d46dcaa246b)

But you are not able to find it in HA-Automation. There you only have `current_heating_setpoint_auto`

![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/1778068/f92f57e3-c1e5-453b-ae63-6937453ffb8b)

![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/1778068/77bbaf2d-ec0f-4c12-a0de-a816043e5337)

![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/1778068/5652330d-06e1-4b4d-a80e-8593d40a5731)

Can you please add this?

The Problem is, that both modes are related to the typo of Heating you've set in the valve. 
If you set `manual` it would use `current_heating_setpoint`, if you set it to `auto` it use `current_heating_setpoint_auto`. 

So it's heavily needed to be able to use the valves in right way with automation (with external temperature sensors)

**Comment by xstable** [comment]
BTW: What are those parameters for: 
![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/1778068/fa337d94-ed7c-4894-8e55-a649de53f57b)

**Comment by skorokithakis** [comment]
I had the same issue, it works with the latest version of Home Assistant.

**Comment by xstable** [comment]
@skorokithakis 
> I had the same issue, it works with the latest version of Home Assistant.

not at mine, wich is also the last recent version : 
![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/1778068/185ddbb9-a48b-4e7f-8c64-5a5306827ea8)
