### ISSUE TITLE
update Immax 07502L fingerprint

### ISSUE THREAD

**Issue by mazany** [Koenkk/zigbee-herdsman-converters#6407]
https://github.com/Koenkk/zigbee-herdsman-converters/blob/6339b6034de34f8a633e4f753dc6e506ac9b001c/src/devices/immax.ts#L189C29-L189C29

Please add additional fingerprint for this device − mine identifies as:
`{modelID: 'TS0202', manufacturerName: '_TZ3210_m3mxv66l'}`

**Comment by Koenkk** [comment]
Done!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
