### ISSUE TITLE
TuYa TS0601 - Not supported while existing in the repo

### ISSUE THREAD

**Issue by atulrnt** [Koenkk/zigbee-herdsman-converters#6432]
Hi,

I connected [this device](https://www.aliexpress.com/item/1005004509406130.html) to Zigbee2MQTT inside my Home Assistant instance and it says the device is not supported.

The error message I receive from Zigbee2MQTT is `Received message from unsupported device with Zigbee model 'TS0601' and manufacturer name '_TZE200_iuk8kupi'`.

I checked in this repo and I was able to find this device in /src/devices/tuya.ts [at the end of the file](https://github.com/Koenkk/zigbee-herdsman-converters/blob/3afd0be2a6dcc5f863d7499923b5884efb02c61a/src/devices/tuya.ts#L6491).

I also tried to copy/paste that part of the external converter inside a custom one and loaded it in Zigbee2MQTT configuration but that didn't seem to change anything.

I'm running: 
- **Zigbee2MQTT** version 1.33.2-1
- **Home Assistant OS** version 11.0
- **Home Assistant Core** version 2023.10.3

Thanks a lot for all the hard work on this and various other repos!
Also thanks in advance for your much appreciated help on that issue!

<img width="847" alt="image" src="https://github.com/Koenkk/zigbee-herdsman-converters/assets/894203/5f8210f3-491e-429a-a207-001683fbaf9c">

EDIT: I realized this device has been added 4 days ago by @marvinroman so that would explain why I don't have access to it yet.
Not sure why my custom external converter is not working though but that's probably an issue on my side.
Do you guys have any idea when this will be added to Zigbee2MQTT and when that version will be released?

**Comment by marvinroman** [comment]
When you go to the Zigbee2MQTT tab is the external converter showing like below?
Are you sure you put the file in the correct place?

I am not running Home Assistant and instead the stand alone docker so I am not certain how to load within Home Assistant.

![Screenshot_20231107_145459](https://github.com/Koenkk/zigbee-herdsman-converters/assets/341606/2f12c45e-92e5-4ce8-bf8b-b997005ddbf2)

**Comment by atulrnt** [comment]
I think I did something wrong before because I retested from scratch and it's now working!

Thanks again for the great work you guys are doing!

**Comment by marvinroman** [comment]
@atulrnt I just got a TuYa gateway to see how the values are reported when I connected it. There needs to  be some value conversions to match it. Here is the external converter with the adjustments. I will make a pull request to fix these values.

```js
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;

const definition = {
  fingerprint: [{modelID: 'TS0601', manufacturerName: '_TZE200_iuk8kupi'}],
  model: 'TS0601_Carbon_Monoxide_Sensor_Gas_Leak_Detector',
  vendor: 'TuYa',
  description: 'Carbon Monoxide Sensor Gas Leak Detector',
  fromZigbee: [tuya.fz.datapoints],
  toZigbee: [tuya.tz.datapoints],
  onEvent: tuya.onEventSetTime,
  configure: tuya.configureMagicPacket,
  whiteLabel: [tuya.whitelabel('Tuya', 'DCR-RQJ', 'Carbon Monoxide Sensor Gas Leak Detector', ['_TZE200_iuk8kupi']),],
  exposes: [ 
    e.gas()
    , tuya.exposes.gasValue().withUnit('LEL %')
    , e.carbon_monoxide()
    , e.co()
  ],
  meta: {
    tuyaDatapoints: [
      [1, 'gas', tuya.valueConverter.trueFalseEnum0]
      , [2, 'gas_value', tuya.valueConverter.divideBy1000]
      , [18, 'carbon_monoxide', tuya.valueConverter.trueFalseEnum0]
      , [19, 'co', tuya.valueConverter.divideBy100]
     ],
  },
};

module.exports = definition;
```

**Comment by atulrnt** [comment]
Amazing, thanks a lot!
I'm gonna update my converter right away!

**Comment by Koenkk** [comment]
@marvinroman great, looking forward to the pr!
