### ISSUE TITLE
Trust ZLED-RGB9 and ZLED-2709 bulbs are not fully supported

### ISSUE THREAD

**Issue by groenmarsmannetje** [Koenkk/zigbee-herdsman-converters#644]
Issues:
- Linkquality is failed and remains empty
- Grouping doesn’t work

**Comment by groenmarsmannetje** [comment]
Trust ZLED-2709 does report linkquality. The RGB bulb doesn’t.

**Comment by Koenkk** [comment]
- Linkquality is only known when the bulb sends messages to the coordinator; some bulbs don't do this; you might check if it does by enabling reporting https://www.zigbee2mqtt.io/information/report.html
- What doesn't work for the grouping, can you share the `database.db` entry?

**Comment by groenmarsmannetje** [comment]
I already had put reporting on.

I updated to latest firmware and had to repair all devices. And now grouping also works for these lamps.
