### ISSUE TITLE
Revert "busch-jaeger new states" #6282

### ISSUE THREAD

**Issue by klada** [Koenkk/zigbee-herdsman-converters#6444]
Dear @Koenkk,

I think we should revert #6282 for now until all issues are resolved. The changes are very problematic in my point of view, because:

- Support for existing devices (especially all combinations with a BJ 6710U) is dropped (see discussion in PR)
- A lot of code is duplicated needlessly (violates the DRY principle and makes converter harder to maintain)
- Historic documentation/comments about these very special devices have been ignored and dropped without replacement
- Useless bindings are created (endpoint10 on dimmer/relay does not need to be bound)
- **All existing automations of people will break** because of the changed action payload
- Splitting up the devices into subdevices (if that's the correct term) will cause a reconfiguration. That is very problematic for the battery-operated devices as waking them up for configuration is very hard. After a Z2M update many users will get error messages regarding failed configuration when this goes live.

CC @muhlatte, @arteck as they have been involved in the discussion

The issue which was supposed to be fixed apparently is a workaround for a bug in iobroker (long-press not working). I don't think we should break all existing setups because of this.

The other issue that too many actions might be exposed is rather cosmetic. This could also be fixed in [the `exposes` closure](https://github.com/Koenkk/zigbee-herdsman-converters/blob/5be8bf3d5d4eaa611b38b7701ad6f102fb0e6073/src/devices/busch-jaeger.ts#L54) without splitting the devices up.

**Comment by Koenkk** [comment]
Agree, in [6268](https://github.com/Koenkk/zigbee-herdsman-converters/pull/6282#issuecomment-1769086640) we also agreed that the `action` values don't change, I missed this when merging this.

**Comment by klada** [comment]
CC @muhlatte, @arteck Please don't get this wrong, I was not trying to block anything here. The PR just felt a little rushed over and not complete. You also mentioned in #6282 that action payloads would change and we should simply not do that. So let's take a second attempt and do this in a more coordianted way. 

I did some further digging in the code and double-checked the current MQTT payloads. There are indeed a few things that we can do:

1. The actions in the [Z2M docs](https://www.zigbee2mqtt.io/devices/6735_6736_6737.html) are not up to date any more. I am going to fix the docs so they contain the current payloads of the actions. This will just be a doc update.
2. Then we can have a look at your ioroker issue. My guess is that iobroker relies on the `exposes` defintion and we need to make sure that this definition is actually correct.
3. I have all combinaitons of BJ devices for testing (1 row, 2 row, 4 row and all the back-ends (power supply, relay, dimmer)). My goal is that any changes we make will not affect zigbee2mqtt users.
4. Changes to the battery-operated versions should only happen if really necessary. Reconfiguring them is a pain and if we require a reconfiguration, we should nail it in the first attempt.

**Comment by Koenkk** [comment]
@klada thanks for looking into this. Regarding point 1 (the docs), this is generated from the `e.action()` expose, so don't update the docs directly.

**Comment by klada** [comment]
I guess the docs for this device are as special as the device itself. :) They contain a [table of possible action values](https://www.zigbee2mqtt.io/devices/6735_6736_6737.html#action-values), and this part is not auto-generated. I think we can at least fix this for starters.

@Koenkk When it comes to splitting up the device across individual converters, what is your personal opinion about this? Right now we have one single converter for `RM01` which handles everything. The `RM01` can be 9 different device variants in total (3 different backends which can be used with 1/2/4 rocker panels).

My personal opinion about this is that these should only be split up if they need to be handled differently. And actually the `RM01` with a dimmer/relay backend needs to be handled a little differently than the `RM01` with a power supply backend. Key differences:

* `RM01` with dimmer/relay has endpoint18, needs to expose `light_brightness().withEndpoint('relay')`, cannot use the first button row and needs the polling hack
* `RM01` with power supply backend does not have endpoint 18, does not expose any light (only actions, it's basically a powered remote). It can also expose the first row as actions. And it does not need the polling hack.

So my proposal is to split up the current `RM01` into just two different devices, instead of 6/9. This reduces code duplication and focuses on the main differences between these device.

**Comment by Koenkk** [comment]
That part is indeed not generated, I agree with your splitting proposal 👍

**Comment by klada** [comment]
It turned out that the action payload of the changes that would have been introduced by #6282 only affected users with the `legacy` setting. But again, let's try not to break these setups.

@muhlatte, @arteck Could you please have a look [at this code](https://github.com/klada/zigbee-herdsman-converters/blob/bj_fixes/src/devices/busch-jaeger.ts) if it addresses your iobroker issue? This is still completely untested (sorry about that) since it will take me a few days to get my ZigBee lab setup working again. But maybe you already have some suggestions or feedback. Thanks.

**Comment by arteck** [comment]
i'm only here a PR creator.. @muhlatte is your tester for this device...sry

**Comment by klada** [comment]
@muhlatte Could you please explain how you are including/using zigbee-herdsman-converters? Are you using z2m or does iobroker use the converters directly? I am starting to think that your actual issue is that you are using the device with the `legacy` option. If you are using zigbee2mqtt, you would set this config option to disable legacy mode:

```yaml
device_options:
  legacy: false
```

For whatever reason `legacy` mode is still enabled by default in zigbee2mqtt. And in legacy mode the long-press actions are indeed not working for some reason.

**Comment by muhlatte** [comment]
Hi Dan,

sorry for the late response, but i was out for a business trip. I use the iobroker zigbee adapter which has no legacy. We as I know use the converter directly. I lived with the solution of manipulating the existing busch-jaeger.js after each adapter update. For a while i contacted arteck if it would be possible to implement the changes into the main herdsman.

With the actual changes of the herdsman unfortunately there is no statechange detected with the batterie driven devices. The device was successfully interviewed but no state changes at all. The states in the zigbee adapter are all the same for any device. Here i named the two tested devices like their product name: 
![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/104367123/19363d12-3cee-40ea-a5a4-f1986604c20c)
![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/104367123/ce537426-f14f-4b22-a111-a5745634e53d)
As you see in the zigbee adapter I only states of true (✓) and false, so no long press differenciate and also no brightness_move or such usefull things.

With the former converter which worked at zigbee2mqtt adapter, the states changed, so now the version is buggy.

With my converter solution i had 5 states for each row as shown here:
![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/104367123/37effbfe-5223-4803-8fc9-c629610817fc)

If there is no common solution I will keep on overwriting the existing converter. Maybe in future I will switch to zigbee2mqtt adapter, but the entry barrier now solution is too high to change anything in my object structure due to all my other zigbee devices beside the light switches.

Really a big thank you for your efforts and best regards,
Daniel

**Comment by klada** [comment]
I think you did not compile the TypeScript to JavaScript and that's why you are getting that import error. But by looking at your first screenshot it still seems like iobroker is using legacy mode.

Unfortunately legacy mode still seems to be the default operation mode of the converts. In Z2M you have to disable this explicitly. So I am wondering if iobroker has an option to disable this as well. I am not familiar with iobroker, but I guess there needs to be a place where device specific options can be set and that's where you would need to disable legacy mode.

Nevertheless you have discovered a different issue: Long-Press and release should also be working in legacy mode (albeit with legacy payloads). But in fact those actions are indeed not working at all right now. However they are working just fine when legacy mode is off. I'll have a look at this in the next few days and I'll try to also fix the legacy mode. Maybe this will also help you with your iobroker problem

**Comment by klada** [comment]
Still discussing how to proceed with this in ioBroker (in German): https://github.com/ioBroker/ioBroker.zigbee/issues/1842#issuecomment-1946963292
