### ISSUE TITLE
Yale Lock integration

### ISSUE THREAD

**Issue by lejroberts** [Koenkk/zigbee-herdsman-converters#647]
Hi,
    I am trying to add support for a Yale lock;
```json
{"ieeeAddr":"0x000d6f0010fa0510","type":"EndDevice","model":"YRD226/246 TSDB","friendly_name":"0x000d6f0010fa0510","nwkAddr":2916,"manufId":4125,"manufName":"Yale","powerSource":"Battery","modelId":"YRD226/246 TSDB","hwVersion":2}]'
```
I copied 1 of the other Yale devices and replaced the model in devices.js
This works for battery and LQI but the lock state always shows as locked and cannot lock or unlock remotely.
I cannot edit any files in Hass.io containers to try and add convertors.
I have attached the integrators guide for you to add support but would really like to help out if you could provide a step by step to setup a test environment.

[Yale Locks ZigBee HA Integrators Guide RevC.pdf](https://github.com/Koenkk/zigbee-shepherd-converters/files/3668808/Yale.Locks.ZigBee.HA.Integrators.Guide.RevC.pdf)

**Comment by Koenkk** [comment]
I would recommend setting up the following environment for development: https://www.zigbee2mqtt.io/getting_started/running_zigbee2mqtt.html

Please provide the debug logging when try to lock/unlocking the device.

To enable debug logging set in `configuration.yaml`:
```yaml
advanced:
  log_level: debug
```

**Comment by lejroberts** [comment]
Setup as suggested, thanks.
Did not get any output from debug with basic devices.js setup - blank from and to [] and no config:
Copied in to,from and config from top Yale device - Assure SL
Attached log file - first action is Unlock, second is Lock.(both manual using thumbturn)

[log.txt](https://github.com/Koenkk/zigbee-shepherd-converters/files/3680761/log.txt)

**Comment by Koenkk** [comment]
Can you try with:

```js
{
    zigbeeModel: ['YRD226/246 TSDB'],
    model: 'YRD226/246 TSDB',
    vendor: 'Yale',
    description: 'TODO',
    supports: 'lock/unlock, battery',
    fromZigbee: [fz.generic_lock_operation_event],
    toZigbee: [tz.generic_lock],
    configure: (ieeeAddr, shepherd, coordinator, callback) => {
        const device = shepherd.find(ieeeAddr, 1);

        const actions = [
            (cb) => device.report('closuresDoorLock', 'lockState', 0, 3, 0, cb),
            (cb) => device.report('genPowerCfg', 'batteryPercentageRemaining', 0, 3, 0, cb),
        ];

        execute(device, actions, callback);
    },
},
```

**Comment by lejroberts** [comment]
Sorry for the delay, I was away for a few days. Edited file as above. See attached log.
Lock state was initially locked, unlocked manually and then locked manually.
[log.txt](https://github.com/Koenkk/zigbee-shepherd-converters/files/3710435/log.txt)

**Comment by Koenkk** [comment]
Can you try with:

```js
{
    zigbeeModel: ['YRD226/246 TSDB'],
    model: 'YRD226/246 TSDB',
    vendor: 'Yale',
    description: 'TODO',
    supports: 'lock/unlock, battery',
    fromZigbee: [fz.generic_lock, fz.generic_battery_remaining],
    toZigbee: [tz.generic_lock],
    configure: (ieeeAddr, shepherd, coordinator, callback) => {
        const device = shepherd.find(ieeeAddr, 1);

        const actions = [
            (cb) => device.report('closuresDoorLock', 'lockState', 0, 3, 0, cb),
            (cb) => device.report('genPowerCfg', 'batteryPercentageRemaining', 0, 3, 0, cb),
        ];

        execute(device, actions, callback);
    },
},
```

**Comment by lejroberts** [comment]
Tried with above device.js entry. See log attached.
[log.txt](https://github.com/Koenkk/zigbee-shepherd-converters/files/3721328/log.txt)

**Comment by Koenkk** [comment]
Seems to work now, right?

**Comment by lejroberts** [comment]
Hey, sorry I was away for a week and then my whole system died. Had to rebuild everything and reflash cc2531 for some reason. Anyway, attached log file. first event is unlock by thumbturn, second is lock by thumbturn.
[log.txt](https://github.com/Koenkk/zigbee-herdsman-converters/files/3766554/log.txt)

Could you explain a bit more on how to write a converter.

**Comment by Koenkk** [comment]
For this case a converter already exists,

With snippet below it should fully work:

```js
{
    zigbeeModel: ['YRD226/246 TSDB'],
    model: 'YRD226/246 TSDB',
    vendor: 'Yale',
    description: 'TODO',
    supports: 'lock/unlock, battery',
    fromZigbee: [fz.generic_lock, fz.generic_battery_remaining, fz.generic_lock_operation_event],
    toZigbee: [tz.generic_lock],
    configure: (ieeeAddr, shepherd, coordinator, callback) => {
        const device = shepherd.find(ieeeAddr, 1);

        const actions = [
            (cb) => device.report('closuresDoorLock', 'lockState', 0, 3, 0, cb),
            (cb) => device.report('genPowerCfg', 'batteryPercentageRemaining', 0, 3, 0, cb),
        ];

        execute(device, actions, callback);
    },
},
```

**Comment by lejroberts** [comment]
So, still says "state":"LOCK" even though just unlocked it. Again attached log file.
There are other messages it sends when certain pin is entered, autolocked etc. 

Could you explain what the below lines mean;
```
const actions = [
            (cb) => device.report('closuresDoorLock', 'lockState', 0, 3, 0, cb),
            (cb) => device.report('genPowerCfg', 'batteryPercentageRemaining', 0, 3, 0, cb),
        ];
```
[log.txt](https://github.com/Koenkk/zigbee-herdsman-converters/files/3770959/log.txt)

**Comment by Koenkk** [comment]
Could you indicate what lines appear **after** you unlock?

**Comment by lejroberts** [comment]
Unlock operation was here;
```
10/25/2019, 5:39:09 PM - debug: Received zigbee message of type 'cmdOperationEventNotification' with data '{"cid":"closuresDoorLock","data":{"opereventsrc":2,"opereventcode":14,"userid":65535,"pin":0,"zigbeelocaltime":315659200,"data":0}
10/25/2019, 5:39:09 PM - info: MQTT publish: topic 'zigbee2mqtt/0x000d6f0010fa0510', payload '{"state":"LOCK","linkquality":94,"battery":95,"user":65535,"source":2}'
```
Lock operation here;
```
10/25/2019, 5:39:19 PM - debug: Received zigbee message of type 'cmdOperationEventNotification' with data '{"cid":"closuresDoorLock","data":{"opereventsrc":2,"opereventcode":13,"userid":65535,"pin":0,"zigbeelocaltime":315659211,"data":0}}' of device 'YRD226/246 TSDB' (0x000d6f0010fa0510) of endpoint 1
10/25/2019, 5:39:19 PM - info: MQTT publish: topic 'zigbee2mqtt/0x000d6f0010fa0510', payload '{"state":"LOCK","linkquality":94,"battery":95,"user":65535,"source":2}'
```

**Comment by Koenkk** [comment]
Thanks, exactly what I needed, I should be fully supported in the latest zigbee2mqtt dev branch now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html).

**Comment by lejroberts** [comment]
Thanks mate. Tested in dev branch ok, just need to sort out HA.
Cheers.
