### ISSUE TITLE
TS0601_thermostat_1 white label and position

### ISSUE THREAD

**Issue by marckar** [Koenkk/zigbee-herdsman-converters#6482]
Hello @Koenkk,

I bought a [GTZ06 thermostatic valve](https://allegro.pl/oferta/glowica-termostatyczna-gtz06-zigbee-3-0-tuya-12770977099) which identifies itself with manufacturerName  `_TZE200_rtrmfadk` and noticed 2 thing that can be adjusted while tracing back issues of `TS0601_thermostat_1`.

1st thing:
`_TZE200_rtrmfadk` can be added to white label next to the `_TZE200_z1tyspqw` to be seen as `GTZ06` instead of `TS0601_thermostat_1`.
I have traced back issue of [_TZE200_dv8abrrz](https://github.com/Koenkk/zigbee2mqtt/issues/14672) which says its a GTZ06 as well.
So with this we have 3 confirmed GTZ06 manufacturer names (with already added _TZE200_z1tyspqw and the 2 above).

But I am confused with `_TZE200_a4bpgplm` and the `valve position` `datapoint` that is added for `TS0601_thermostat_1`.
[One issue](https://github.com/Koenkk/zigbee-herdsman-converters/issues/3190) said it's a Rti-Tek TRV601, with `valve position` at datapoint 102.
[Another (already merged) issue](https://github.com/Koenkk/zigbee-herdsman-converters/pull/3595) confirmed that `_TZE200_a4bpgplm` is a GTZ06.

With my `_TZE200_rtrmfadk` I have confirmed that `valve position` at `datapoint 102` doesn't work - it was always displayed as `null`.
After adding custom converter from [here](https://gist.github.com/Koenkk/3993885d51baf82ed334afe0781c7d55), removing `datapoint` for `valve position` and enabling debug mode I confirmed that `valve position` is actually on datapoint 108 (already mentioned in [this issue](https://github.com/Koenkk/zigbee2mqtt/issues/18892)).
Adjusting the converter fixed the issue and `valve position` (0 or 100) was displayed correctly in z2m.

So I think it should be safe to apply to the manufacturer names  _TZE200_z1tyspqw, _TZE200_dv8abrrz and _TZE200_rtrmfadk.

This brings me to 2nd thing that can be adjusted:
Either  [_TZE200_a4bpgplm](https://github.com/Koenkk/zigbee-herdsman-converters/issues/3190) with `valve position` at `datapoint 102` is **one device** and other three manufacturer names should be **a separate GTZ06 device** with `valve position` at `datapoint 108`, or **all of them** are actually GTZ06 and datapoint 102 is a typo.

Hopefull this help the community using those TRVs
BR

**Comment by sbialkowski-pixel** [comment]
I would like to refresh this issue.
I also have _TZE200_rtrmfadk and my valve position is always null.

I would be grateful for fixing this issue.
Best.
