### ISSUE TITLE
Please add "Philips Hue White and Color Ambiance LED Outdoor Lightstrip"

### ISSUE THREAD

**Issue by andre1974** [Koenkk/zigbee-herdsman-converters#651]
Could you please add the Philips Hue White and Color Ambiance LED Outdoor Lightstrip?
![Lightstrip](https://user-images.githubusercontent.com/11474126/65955425-65e81e80-e448-11e9-8c0e-94220a1fdc3e.jpg)

**Comment by arteck** [comment]
done
