### ISSUE TITLE
Add new fingerprint ({modelID: "WHD02", manufacturer name: " _TZ3000_skueekg3"})

### ISSUE THREAD

**Issue by misha1183** [Koenkk/zigbee-herdsman-converters#6516]
Add new fingerprint ({modelID: "WHD02", manufacturer name: " _TZ3000_skueekg3"})

**Comment by Koenkk** [comment]
to which definition?

**Comment by misha1183** [comment]
I'm sorry for my english.

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const utils = require('zigbee-herdsman-converters/lib/utils');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;
const globalStore = require('zigbee-herdsman-converters/lib/store');

const definition = {
    fingerprint: [{modelID: 'TS0001', manufacturerName: '_TZ3000_skueekg3'}],
    model: 'WHD02',
    vendor: 'TuYa',
    description: '1 gang switch',
//    toZigbee: [tz.on_off, tuya.tz.power_on_behavior_1],
//    fromZigbee: [tz.on_off, tuya.tz.power_on_behavior_1],
//    extend:  tuya.extend.switch({switch_type: true, endpoints: ['l1']}),
    extend: tuya.extend.switch({powerOnBehavior_1: true, endpoints: ['l1']}),
    whiteLabel: [{vendor: 'WHD02', model: 'WHD02'}],
    endpoint: (device) => {
        return {l1: 1};
        },
    meta: {multiEndpoint: true},


    configure: async (device, coordinatorEndpoint, logger) => {
            await tuya.configureMagicPacket(device, coordinatorEndpoint, logger);
            await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['genOnOff']);


        },
};

module.exports = definition;

**Comment by Koenkk** [comment]
It's already there: https://github.com/Koenkk/zigbee-herdsman-converters/blob/a93da0b31a4cc29a601150220c0460ceb1a1b440/src/devices/tuya.ts#L802

**Comment by misha1183** [comment]
But it is relay, not wall switch. Don't work momentary/toggle/ switch mode. Thank you.

**Comment by misha1183** [comment]
and i buy dac4161c-bl. what need to make converter. this is unsupported device. this is a very interesting device. thank you.
https://sl.aliexpress.ru/p?key=T6inUeR
