### ISSUE TITLE
Support for Innr SP 224

### ISSUE THREAD

**Issue by iautom8things** [Koenkk/zigbee-herdsman-converters#652]
I'm working with hassio's zigbee2mqtt addon, so I'm not exactly sure the process for attempting to add support myself.  Any help would be great!  Thanks

**Comment by Koenkk** [comment]
https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices_on_hassio.html

It will probably work with the following configuration:

```js
{
        zigbeeModel: ['SP 224'],
        model: 'SP 224',
        vendor: 'Innr',
        description: 'Smart plug',
        supports: 'on/off',
        fromZigbee: [fz.state, fz.ignore_onoff_change],
        toZigbee: [tz.on_off],
    },

```

**Comment by iautom8things** [comment]
Thank you, @Koenkk!

This is definitely on me for not doing a thorough look over on all of the _how-to_ guides.  However, it may be super helpful for future users to have a footnote on this guide: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

That links back to the hassio _how-to_.  Something like:

```* If you're using hassio, you may want to follow this guide: ...`

If you agree, and if you can point me at the doc repo I can make a PR for that.

**Comment by Koenkk** [comment]
Yes feel free to make a pr.

**Comment by iautom8things** [comment]
Thank you for your help, again!  Closing this, and opened this koenkk/zigbee2mqtt.io#124

**Comment by iautom8things** [comment]
So I may have closed this prematurely.  I finally had the chance to play with the documentation you linked, and the configuration you provided for `devices.js`.

I was able to get the plugs to pair:

```
 zigbee2mqtt:info 10/4/2019, 8:53:31 AM New device 'SP 224' with address 0x90fd9ffffe5ac614 connected!
  zigbee2mqtt:info 10/4/2019, 8:53:32 AM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":"0x90fd9ffffe5ac614","meta":{"modelID":"SP 224"}}'
  zigbee2mqtt:info 10/4/2019, 8:53:33 AM MQTT publish: topic 'zigbee2mqtt/0x90fd9ffffe5ac614', payload '{"state":"OFF","linkquality":115}'
```
However, beyond that I have not had success with zigbee2mqtt seeing when I turn the plugs on/off.  Nor does it actually get picked up / viewable in home assistant.

Is there anything else I can provide you to help figure out what I might have done wrong?  Thanks!

**Comment by Koenkk** [comment]
- First switch to the latest zigbee2mqtt dev branch (edge for hassio)
- For home assistant discovery add to https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/extension/homeassistant.js#L582 `'SP 224': [configurations.switch],`. If you don't know how to do this try to control it directly via MQTT (`zigbee2mqtt/[DEVICE_ID]/set`, payload: `OFF` or `ON`)
- Use the following for `devices.js`

```
 {
        zigbeeModel: ['SP 224'],
        model: 'SP 224',
        vendor: 'Innr',
        description: 'Smart plug',
        supports: 'on/off',
        fromZigbee: [fz.state, fz.ignore_onoff_change],
        toZigbee: [tz.on_off],
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            await bind(endpoint, coordinatorEndpoint, ['genOnOff']);
            await configureReporting.onOff(endpoint);
        },
    },
```

Note that for the latest zigbee2mqtt the zigbee-herdsman-converters branch needs to be used (https://github.com/koenkk/zigbee-shepherd-converters)

**Comment by brettpappas** [comment]
I just purchased a couple of these plugs and was able to pair them successfully. I am not able to control them with the configuration you gave.

1. I am running off of the dev branch for `zigbee2mqtt`.
2. I added the config for `SP 224` to the devices.js file and restarted the service.
3. I manually turned the plug off and then on using the button on the side.

Here is what shows up in the logs:

```
debug 2019-11-09T15:51:03: Received Zigbee message from 'plug_1', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0
error 2019-11-09T15:51:03: Failed to call 'DeviceReceive' 'onZigbeeEvent' (TypeError: Cannot read property 'type' of undefined
    at mappedDevice.fromZigbee.filter (/opt/zigbee2mqtt/lib/extension/deviceReceive.js:83:42)
    at Array.filter (<anonymous>)
    at DeviceReceive.onZigbeeEvent (/opt/zigbee2mqtt/lib/extension/deviceReceive.js:82:52)
    at Controller.callExtensionMethod (/opt/zigbee2mqtt/lib/controller.js:320:44)
    at Controller.onZigbeeEvent (/opt/zigbee2mqtt/lib/controller.js:228:14)
    at Zigbee.emit (events.js:198:13)
    at Controller.herdsman.on (/opt/zigbee2mqtt/lib/zigbee.js:57:52)
    at Controller.emit (events.js:198:13)
    at Controller.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/controller.js:415:22)
    at Generator.next (<anonymous>))
debug 2019-11-09T15:51:08: Received Zigbee message from 'plug_1', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
error 2019-11-09T15:51:08: Failed to call 'DeviceReceive' 'onZigbeeEvent' (TypeError: Cannot read property 'type' of undefined
    at mappedDevice.fromZigbee.filter (/opt/zigbee2mqtt/lib/extension/deviceReceive.js:83:42)
    at Array.filter (<anonymous>)
    at DeviceReceive.onZigbeeEvent (/opt/zigbee2mqtt/lib/extension/deviceReceive.js:82:52)
    at Controller.callExtensionMethod (/opt/zigbee2mqtt/lib/controller.js:320:44)
    at Controller.onZigbeeEvent (/opt/zigbee2mqtt/lib/controller.js:228:14)
    at Zigbee.emit (events.js:198:13)
    at Controller.herdsman.on (/opt/zigbee2mqtt/lib/zigbee.js:57:52)
    at Controller.emit (events.js:198:13)
    at Controller.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/controller.js:415:22)
    at Generator.next (<anonymous>))
```

I am happy to do further troubleshooting if you have any suggestions.

--Brett

**Comment by Koenkk** [comment]
@brettpappas can you share your `devices.js`?

**Comment by iquark13** [comment]
Hello, I do not have branch privileges, but using the above devices.js configuration and a slight modification to your homeassistant.js entry, this is working great on my setup.

I'm new to github, but am happy to try and branch herdsman and zigbee2mqtt if I get permissions and submit a pull request.

devices.js:
`{
        zigbeeModel: ['SP 224'],
        model: 'SP 224',
        vendor: 'Innr',
        description: 'Smart plug',
        supports: 'on/off',
        fromZigbee: [fz.state, fz.ignore_onoff_change],
        toZigbee: [tz.on_off],
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            await bind(endpoint, coordinatorEndpoint, ['genOnOff']);
            await configureReporting.onOff(endpoint);
        },
    },`

homeassistant.js
`'SP 224': [cfg.switch]`

**Comment by Koenkk** [comment]
Added, thanks @iquark13 !
