### ISSUE TITLE
Zigbee 3.0 DALI CONV LI - unsupported attribute 

### ISSUE THREAD

**Issue by SmarthomeEmmi** [Koenkk/zigbee-herdsman-converters#6556]
Please add 'colortemp' in the extends of the following zigbee-Model in 'osram.js'

The Zigbee 3.0 DALI Converter is a DALI DT8 Converter which supports also changing color temperature

_zigbeeModel: ['Zigbee 3.0 DALI CONV LI', 'Zigbee 3.0 DALI CONV LI\u0000'],
        model: '4062172044776_1',
        vendor: 'OSRAM',
        description: 'Zigbee 3.0 DALI CONV LI dimmer for DALI-based luminaires (only one device)',
        extend: extend.ledvance.light_onoff_brightness(),_

Thank you!

**Comment by Koenkk** [comment]
It's already there: https://github.com/Koenkk/zigbee-herdsman-converters/blob/90c24344c3b100967445e45d882f9ede73c81280/src/devices/osram.ts#L418
