### ISSUE TITLE
Problem on _TZE200_rks0sgb7 (Bidirectional energy meter with 80A current clamp)

### ISSUE THREAD

**Issue by PM04290** [Koenkk/zigbee-herdsman-converters#6610]
There is error on received datas
error 10 (here) seems a counter from up-time (or other, i don't know).
![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/65124804/3a493a66-e529-443a-a86b-5c58ddc23efc)

**Comment by PM04290** [comment]
it's 10 at the time of screenshot, but before it was 2..... 3.... 4.... etc
i don't know what is this counter
how can i help you to fix the bug ?
i'am on version 1.34.0-1, is it possible to modify locally _TZE200_rks0sgb7 ? (HAOS with addon Z2M)
the number is not important for me (consuming / producing)

**Comment by Koenkk** [comment]
We need to know what the other values mean, you probably need a TuYa bridge to figure out what the datapoints mean ([tutorial](https://www.zigbee2mqtt.io/advanced/support-new-devices/03_find_tuya_data_points.html))

**Comment by PM04290** [comment]
i don't have TuYa bridge and not plan to buy it.
is there a solution to have localy configuration that drop (ignore) this data ?

**Comment by Koenkk** [comment]
I can map them to unknown, are there any other values besides 10?

**Comment by PM04290** [comment]
I think it's a counter, so it will continue to rise, I don't know how much.
Is it possible that I override this converter with a local converter in order to make test?

**Comment by PM04290** [comment]
i have modified a little your file to read raw on 102/104
```

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    fingerprint: tuya.fingerprint('TS0601', ['_TZE204_81yrt3lo', '_TZE200_rks0sgb7']),
    model: 'PJ-1203A',
    vendor: 'TuYa',
    description: 'Bidirectional energy meter with 80A current clamp',
    fromZigbee: [tuya.fz.datapoints],
    toZigbee: [tuya.tz.datapoints],
    onEvent: tuya.onEventSetTime,
    configure: tuya.configureMagicPacket,
    exposes: [
        e.ac_frequency(), e.voltage(),
        tuya.exposes.powerWithPhase('a'), tuya.exposes.powerWithPhase('b'), tuya.exposes.powerWithPhase('ab'),
        tuya.exposes.currentWithPhase('a'), tuya.exposes.currentWithPhase('b'),
        tuya.exposes.powerFactorWithPhase('a'), tuya.exposes.powerFactorWithPhase('b'),
        tuya.exposes.energyFlowWithPhase('a'), tuya.exposes.energyFlowWithPhase('b'),
        tuya.exposes.energyWithPhase('a'), tuya.exposes.energyWithPhase('b'),
        tuya.exposes.energyProducedWithPhase('a'), tuya.exposes.energyProducedWithPhase('b'),
        e.numeric('update_frequency', ea.STATE).withUnit('s').withDescription('Update frequency'),
    ],
    meta: {
        tuyaDatapoints: [
            [111, 'ac_frequency', tuya.valueConverter.divideBy100],
            [101, 'power_a', tuya.valueConverter.divideBy10],
            [105, 'power_b', tuya.valueConverter.divideBy10],
            [115, 'power_ab', tuya.valueConverter.divideBy10],
            [112, 'voltage', tuya.valueConverter.divideBy10],
            [113, 'current_a', tuya.valueConverter.divideBy1000],
            [114, 'current_b', tuya.valueConverter.divideBy1000],
            [110, 'power_factor_a', tuya.valueConverter.raw],
            [121, 'power_factor_b', tuya.valueConverter.raw],
            [102, 'energy_flow_a', tuya.valueConverter.raw],
            [104, 'energy_flow_b', tuya.valueConverter.raw],
            [106, 'energy_a', tuya.valueConverter.divideBy100],
            [108, 'energy_b', tuya.valueConverter.divideBy100],
            [107, 'energy_produced_a', tuya.valueConverter.divideBy100],
            [109, 'energy_produced_b', tuya.valueConverter.divideBy100],
            [129, 'update_frequency', tuya.valueConverter.raw],
        ],
    },
};

module.exports = definition;

```
it needs to uncomment "const ea".
i have clamp on two different raw of my electric panel, and results are strange but now i haven't error.... i don't know what is the counter.

![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/65124804/ba2935a8-825f-49ae-8f56-ffb89747746d)

**Comment by Koenkk** [comment]
So it seems there is also a `22` value, are there any other values?

**Comment by mrmaximas** [comment]
> So it seems there is also a `22` value, are there any other values?

Do You know that tuya messages that look like garbage in the iot.tuya logs are actually base64 encoded strings, right?

**Comment by PM04290** [comment]
@Koenkk , i finally plan to buy a Tuya bridge to solve the problem, and another one
i have this device (https://fr.aliexpress.com/item/1005005946786561.html) and it's impossible to paire it.
There is many (many) Tuya zigbee bridge; can you provide a link of model who can permit a succesfull debug ?

**Comment by PM04290** [comment]
i have received my HUB (MOES Wired + BLE) model MHUB
on Tuya IoT i have the information below and i'm going keep all data point
the model is not TZE200 but PC311_Z_TY... why Z2M have detected TZE200 instead of PC311_Z_TY ?
i can create a dedicated converter for PC311 but how to call it if TZE200 is detected ?
![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/65124804/02799d54-b837-4de7-b4ee-88ba0260555c)
