### ISSUE TITLE
Add Backlight switch for TS0001 (_TZ3000_myaaknbq)

### ISSUE THREAD

**Issue by mrbluebrett** [Koenkk/zigbee-herdsman-converters#6625]
Hello, 
I previously added a similar feature request that's already completed [https://github.com/Koenkk/zigbee-herdsman-converters/issues/6370](url) .
Now I purchased a new wall switch: TS0001 (_TZ3000_myaaknbq).
As usual pairing and on/off with z2m works flawlessly, but there's no backlight switch.
And I have checked that the backlight switch works in the same way as the previous ones:

-  Endpoint: 1
-  Cluster: OnOff
-  Attribute: tuyaBacklightSwitch
-  Value: 0 (off) / 1 (on)

Can it be added to this device?
Thanks in advance.

**Comment by novittukyll** [comment]
I would also like to have backlight switch for this device. TS0001 (_TZ3000_0qdfq5nr)
