### ISSUE TITLE
Legrand 067772

### ISSUE THREAD

**Issue by vlehko** [Koenkk/zigbee-herdsman-converters#6628]
after update of Zigbee2mqtt i started to get error message in the log related to legrand switch

error 2023-12-05 11:50:08: Publish 'set' 'device_mode' to 'Svetlo_Vstupna_Chodba' failed: 'Error: Write 0x0004740000241682/1 manuSpecificLegrandDevices({"0":{"value":256,"type":9}}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4129,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'

**Comment by Koenkk** [comment]
@sangecz since you added this in https://github.com/Koenkk/zigbee-herdsman-converters/pull/6247, could you check this?
