### ISSUE TITLE
HELP: How do I set the timeout period for the OTA Server to receive the Upgrade End Request?

### ISSUE THREAD

**Issue by lcheng33775823** [Koenkk/zigbee-herdsman-converters#6657]
I added a Zigbee device to Zigbee2Mqtt, which is composed of two MCUS (Zigbee Mcu + Mcu 2), so when doing OTA, I combined the OTA files of the two MCUS into one. When the Zigbee device receives the last packet of Block Response, it will Upgrade Mcu 2 first. After the Mcu 2 upgrade is successful, it will send the Upgrade End Request, but the upgrade time is 30 minutes, which will cause Zigbee2Mqtt to report an error.

![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/47738738/f2ed56d0-c69c-4307-8ac3-61fa98a69220)

**Comment by lcheng33775823** [comment]
thanks

**Comment by HermesHonshappo** [comment]
Is it possible to specify these OTA timeout values when using the Z2M add-on in HA?
