### ISSUE TITLE
Another manufacturer ID for Moes UFO-R11 `TS1201`

### ISSUE THREAD

**Issue by MicaelJarniac** [Koenkk/zigbee-herdsman-converters#6663]
### [Moes UFO-R11](https://www.zigbee2mqtt.io/devices/UFO-R11.html)

https://github.com/Koenkk/zigbee-herdsman-converters/blob/5385ab824c3f2ca7c2f3c58ccd3ebcfeda09de34/src/devices/moes.ts#L350-L353

![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/19514231/0193ff7d-1f4c-4a8e-a0e6-153c7ddd7b31)

`_TZ3290_xjpbcxn92aaxvmlz`

[Ekaza EKNH-T304Z](https://store.ekaza.com.br/controle_remoto_universal_sem_fio_zigbee_3_0_eknh_t304z/p)

![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/19514231/6c64050c-bb38-4bfe-bff4-c77101a5368f)

**Comment by MicaelJarniac** [comment]
Also, why do they have all these different manufacturer IDs, with seemingly random strings at the end? Is it to obfuscate it and make it harder for us to control these devices without their proprietary bridges? And would it be possible to adapt this software to support these randomized manufacturer IDs automatically, like specifying `_TX3290_*` and having it automatically support any random ending?

**Comment by Koenkk** [comment]
Added!

> like specifying _TX3290_* and having it automatically support any random ending?

Unfortunately no, multiple devices are using this prefix.
