### ISSUE TITLE
VOCKQJK11LM Improvements and switch to modernExtends

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee-herdsman-converters#6721]
The PR https://github.com/Koenkk/zigbee-herdsman-converters/pull/6709 was getting a bit big and messy, I've decided to break it up in a few [smaller PRs ](https://github.com/Koenkk/zigbee-herdsman-converters/pull/6709#issuecomment-1858788532)to get this in in smaller steps.

- [x] basic improvements  (phase 1)
   - [x] wait for https://github.com/Koenkk/zigbee-herdsman/pull/829
      - [x] use more readable attribute names
   - [X] implement air_quality as modernExtend
   - [X] move voc to modernExtend
     - [X] cleanup fz.xiaomi_tvoc
   - [X] move display_unit to modernExtend
      - [X] cleanup fzLocal.VOCKQJK11LM_display_unit
      - [X] cleanup lib.xiaomi numericAttributes2Payload
   - [x] Update modernExtend.numeric and modernExtend.enumLookup
      - [x] read attribute during configure (Do we need a toggle for this? I think we always want to do  this)
      - [x] configure attribute reporting (Only when reporting config is set in args)
    - [x] setup reporting of batteryVoltage (until phase 3 where we can use a modernExtend) 
- [x] allow reading of additional attributes, we get this for free with modernExtends! (phase 2)
   - [ ] ~~integrate precision and calibration in the numeric modernExtend and auto expose these options~~
   - [x] add temperature + humidity modernExtend presets beased on numeric modernExtend
     - [ ] ~~add a 'filter' function so we don't need to reinvent the wheel for things like `fz.SNZB_temperature`~~
   - [x] move temperature to modernExtend (don't forget about the reporting setup and options!)
   - [x] move humidity to modernExtend (don't forget about the reporting setup and options!)
- [ ] want modernExtend for battery things
   - [ ] add batteryPercentageRemaining modernExtend (do reporting, reading, ...)
   - [ ] add batteryVoltage modernExtend (do reporting, reading, have the 'battery type configrable', ...)
   - [ ] add xiaomiBatteryVoltage modernExtend (use aqaraOpple attribute as it offers better precision)
      - [ ] add to cluster.ts
      - [ ] update all devices and test I own
- [ ] move more stuff from lib.xiaomi's numericAttributes2Payload to modernExtends (phase 4)
   - [ ] move device_temperature to modernExtend
   - [ ] ...

**Comment by sjorge** [comment]
Phase 1 notes:
- updating a modernExtend configure() function does **not** trigger a reconfigure! (@Koenkk is this expected? I would have expected it to trigger a re-configure)
- LUMI devices have incorrect inputCluster information 😢, so we can't just 'grab all endpoints with a cluster' to try and read from them, so we have to pass the endpointId if not 1, I have not figured out a way to map the endpoint name for the expose info to the endpoint/endpoint id inside a modernExtend

Made some progress though, expect a PR tomorrow unless I can't out the reporting

**Comment by sjorge** [comment]
My VOCKQJK11LM dropped of the network for a few hours and when it came back the reporting interval configure and the one actually happening did not seem to match.

I think the device might forget the reporting. Re-applying them seem to make it work again. Will check next time it drops if that is the case too. If that is the case we can probably do the same as we do here:

https://github.com/Koenkk/zigbee-herdsman-converters/blob/15f6a570fa14c1492e062c00bf62228dcb2576de/src/devices/legrand.ts#L439-L456

But need to collect some more data before implementing this.

**Comment by sjorge** [comment]
@Koenkk can we in theory inject present (and working) but not discovered msTemperatureMeasurement, msRelativeHumidity, and genAnalogInput clusters? 

Using something similar to:
https://github.com/Koenkk/zigbee-herdsman-converters/blob/9c7f6dd30a1e96b238584ac0e66339da9b5fafa3/src/lib/modernExtend.ts#L521-L527

I was messing with editing the database.db on my dev z2m instance and I think if we can, the auto endpoint selector for hte modernExtend works without the endpoint hint we need to give it now. 

More importantly, initial messing about seem to indicate binding for those then also work via the frontend, which now only work inside a zhc functions and not via mqtt/frontend -> z2m. 

zippy/zha seems to be doing similar injection for a lot of lumi (xiamo/aqara/maji) devices e.g. https://github.com/zigpy/zha-device-handlers/blob/dev/zhaquirks/xiaomi/aqara/magnet_agl02.py where they inject the onOff cluster.

I think it would be good to do the same, especially if we're going to convert more things to modernExtend that some of the nice auto reporting/bind endpoint selection just works TM and it brings the bonus of making manual bind/reporting setup via the frontend/mqtt also work.

**Comment by Koenkk** [comment]
Yes, sounds like a good idea!

**Comment by sjorge** [comment]
> Yes, sounds like a good idea!

Excellent, I'll look at writing a generic modernExtend to like the `forcePowerSource` one that takes a cluster + endpointID(s) as argument to then inject them. Seems at first glance we can just have multiple calls to it like

```
[
    modernExtend.forceAddClusters('msTemperatureMeasurement', 1);
    modernExtend.forceAddClusters('msRelativeHumidity', [1,2,3,4]);
   ...
]
```

So it's reusable for other device, although I don't own any others, I would expect this to be usable for other lumi devices and probably others too.

**Comment by Koenkk** [comment]
I think the force prefix is not needed, just use `addEndpointCluster`

**Comment by sjorge** [comment]
Made some progress:

<img width="1024" alt="image" src="https://github.com/Koenkk/zigbee-herdsman-converters/assets/379665/cd40e68c-812e-4495-bb91-026d8b5064a5">

I can now also bind/unbind those to clusters to the coordinator via the frontend, before if you unbound say Humidity you couldn't rebind it outside of hitting reconfigure.

**Comment by sjorge** [comment]
Ok so the device definately forgets it's bindings/reporting when power_outage attribute increase.

Seems like a good candidate to move out of the massive parser function and into a proper attribute with modernExtend.

Just need to figure out how i can save the previous value even when the state cache is disabled, so I can add a restore binding/reporting argument to the extend.

**Comment by sjorge** [comment]
I setup a bunch of extra logging to make 100% sure hte device does not emit a deviceAnnounce when it's outage_count goes up and it loses all bindings/reporting :( sadly I can confirm that.

```
debug 2024-01-12 15:04:15: Received Zigbee message from 'airquality/livingroom', type 'attributeReport', cluster 'msTemperatureMeasurement', data '{"measuredValue":1971}' from endpoint 1 with groupID 0
info  2024-01-12 15:04:16: MQTT publish: topic 'zigbee2mqtt/airquality/livingroom', payload '{"air_quality":"good","battery":100,"device_temperature":19,"display_unit":"ppb_celsius","humidity":43.22,"last_seen":"2024-01-12T14:04:15.702Z","linkquality":76,"power_outage_count":20,"temperature":19.71,"voc":215,"voltage":3035}'
debug 2024-01-12 15:08:34: Received Zigbee message from 'airquality/livingroom', type 'attributeReport', cluster 'msRelativeHumidity', data '{"measuredValue":4316}' from endpoint 1 with groupID 0
info  2024-01-12 15:08:35: MQTT publish: topic 'zigbee2mqtt/airquality/livingroom', payload '{"air_quality":"good","battery":100,"device_temperature":19,"display_unit":"ppb_celsius","humidity":43.16,"last_seen":"2024-01-12T14:08:34.528Z","linkquality":134,"power_outage_count":20,"temperature":19.71,"voc":215,"voltage":3035}'
debug 2024-01-12 15:11:33: Received Zigbee message from 'airquality/livingroom', type 'attributeReport', cluster 'msTemperatureMeasurement', data '{"measuredValue":1995}' from endpoint 1 with groupID 0
info  2024-01-12 15:11:34: MQTT publish: topic 'zigbee2mqtt/airquality/livingroom', payload '{"air_quality":"good","battery":100,"device_temperature":19,"display_unit":"ppb_celsius","humidity":43.16,"last_seen":"2024-01-12T14:11:33.795Z","linkquality":109,"power_outage_count":20,"temperature":19.95,"voc":215,"voltage":3035}'
debug 2024-01-12 15:19:11: Received Zigbee message from 'airquality/livingroom', type 'attributeReport', cluster 'msTemperatureMeasurement', data '{"measuredValue":2016}' from endpoint 1 with groupID 0
info  2024-01-12 15:19:12: MQTT publish: topic 'zigbee2mqtt/airquality/livingroom', payload '{"air_quality":"good","battery":100,"device_temperature":19,"display_unit":"ppb_celsius","humidity":43.16,"last_seen":"2024-01-12T14:19:11.806Z","linkquality":80,"power_outage_count":20,"temperature":20.16,"voc":215,"voltage":3035}'
debug 2024-01-12 15:19:31: Received Zigbee message from 'airquality/livingroom', type 'attributeReport', cluster 'msRelativeHumidity', data '{"measuredValue":4210}' from endpoint 1 with groupID 0
info  2024-01-12 15:19:32: MQTT publish: topic 'zigbee2mqtt/airquality/livingroom', payload '{"air_quality":"good","battery":100,"device_temperature":19,"display_unit":"ppb_celsius","humidity":42.1,"last_seen":"2024-01-12T14:19:31.686Z","linkquality":109,"power_outage_count":20,"temperature":20.16,"voc":215,"voltage":3035}'
debug 2024-01-12 15:30:58: Received Zigbee message from 'airquality/livingroom', type 'attributeReport', cluster 'msTemperatureMeasurement', data '{"measuredValue":2046}' from endpoint 1 with groupID 0
info  2024-01-12 15:30:59: MQTT publish: topic 'zigbee2mqtt/airquality/livingroom', payload '{"air_quality":"good","battery":100,"device_temperature":19,"display_unit":"ppb_celsius","humidity":42.1,"last_seen":"2024-01-12T14:30:58.793Z","linkquality":76,"power_outage_count":20,"temperature":20.46,"voc":215,"voltage":3035}'
debug 2024-01-12 15:34:07: Received Zigbee message from 'airquality/livingroom', type 'attributeReport', cluster 'msTemperatureMeasurement', data '{"measuredValue":2053}' from endpoint 1 with groupID 0
info  2024-01-12 15:34:08: MQTT publish: topic 'zigbee2mqtt/airquality/livingroom', payload '{"air_quality":"good","battery":100,"device_temperature":19,"display_unit":"ppb_celsius","humidity":42.1,"last_seen":"2024-01-12T14:34:07.920Z","linkquality":112,"power_outage_count":20,"temperature":20.53,"voc":215,"voltage":3035}'
debug 2024-01-12 15:34:27: Received Zigbee message from 'airquality/livingroom', type 'attributeReport', cluster 'msRelativeHumidity', data '{"measuredValue":4209}' from endpoint 1 with groupID 0
info  2024-01-12 15:34:28: MQTT publish: topic 'zigbee2mqtt/airquality/livingroom', payload '{"air_quality":"good","battery":100,"device_temperature":19,"display_unit":"ppb_celsius","humidity":42.09,"last_seen":"2024-01-12T14:34:27.780Z","linkquality":112,"power_outage_count":20,"temperature":20.53,"voc":215,"voltage":3035}'
debug 2024-01-12 15:49:04: Received Zigbee message from 'airquality/livingroom', type 'attributeReport', cluster 'msTemperatureMeasurement', data '{"measuredValue":2065}' from endpoint 1 with groupID 0
info  2024-01-12 15:49:04: MQTT publish: topic 'zigbee2mqtt/airquality/livingroom', payload '{"air_quality":"good","battery":100,"device_temperature":19,"display_unit":"ppb_celsius","humidity":42.09,"last_seen":"2024-01-12T14:49:04.046Z","linkquality":91,"power_outage_count":20,"temperature":20.65,"voc":215,"voltage":3035}'
debug 2024-01-12 15:49:23: Received Zigbee message from 'airquality/livingroom', type 'attributeReport', cluster 'msRelativeHumidity', data '{"measuredValue":4232}' from endpoint 1 with groupID 0
info  2024-01-12 15:49:24: MQTT publish: topic 'zigbee2mqtt/airquality/livingroom', payload '{"air_quality":"good","battery":100,"device_temperature":19,"display_unit":"ppb_celsius","humidity":42.32,"last_seen":"2024-01-12T14:49:23.943Z","linkquality":83,"power_outage_count":20,"temperature":20.65,"voc":215,"voltage":3035}'
debug 2024-01-12 15:54:12: Received Zigbee message from 'airquality/livingroom', type 'attributeReport', cluster 'aqaraOpple', data '{"247":{"data":[1,33,221,11,3,40,20,4,33,168,19,5,33,21,0,6,36,19,0,0,0,0,8,33,29,1,10,33,167,86,12,32,1,100,41,19,8,101,33,108,16,102,33,188,0,103,32,2],"type":"Buffer"}}' from endpoint 1 with groupID 0
info  2024-01-12 15:54:13: MQTT publish: topic 'zigbee2mqtt/airquality/livingroom', payload '{"air_quality":"good","battery":100,"device_temperature":20,"display_unit":"ppb_celsius","humidity":42.04,"last_seen":"2024-01-12T14:54:12.798Z","linkquality":109,"power_outage_count":20,"temperature":20.67,"voc":215,"voltage":3037}'
debug 2024-01-12 15:54:13: Received Zigbee message from 'airquality/livingroom', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryVoltage":27}' from endpoint 1 with groupID 0
debug 2024-01-12 15:54:13: Received Zigbee message from 'airquality/livingroom', type 'attributeReport', cluster 'aqaraOpple', data '{"247":{"data":[1,33,181,10,3,40,20,4,33,168,19,5,33,22,0,6,36,0,0,0,0,0,8,33,29,1,10,33,167,86,12,32,1,100,41,18,8,101,33,134,16,102,33,53,0,103,32,1],"type":"Buffer"}}' from endpoint 1 with groupID 0
info  2024-01-12 15:54:14: MQTT publish: topic 'zigbee2mqtt/airquality/livingroom', payload '{"air_quality":"good","battery":0,"device_temperature":20,"display_unit":"ppb_celsius","humidity":42.3,"last_seen":"2024-01-12T14:54:13.908Z","linkquality":109,"power_outage_count":21,"temperature":20.66,"voc":215,"voltage":2741}'
debug 2024-01-12 15:54:33: Received Zigbee message from 'airquality/livingroom', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryVoltage":25}' from endpoint 1 with groupID 0
debug 2024-01-12 15:54:33: Received Zigbee message from 'airquality/livingroom', type 'attributeReport', cluster 'aqaraOpple', data '{"247":{"data":[1,33,6,10,3,40,20,4,33,168,19,5,33,22,0,6,36,2,0,0,0,0,8,33,29,1,10,33,167,86,12,32,1,100,41,18,8,101,33,110,16,102,33,53,0,103,32,1],"type":"Buffer"}}' from endpoint 1 with groupID 0
info  2024-01-12 15:54:34: MQTT publish: topic 'zigbee2mqtt/airquality/livingroom', payload '{"air_quality":"good","battery":0,"device_temperature":20,"display_unit":"ppb_celsius","humidity":42.06,"last_seen":"2024-01-12T14:54:33.988Z","linkquality":134,"power_outage_count":21,"temperature":20.66,"voc":215,"voltage":2566}'
debug 2024-01-12 15:54:45: Received Zigbee message from 'airquality/livingroom', type 'attributeReport', cluster 'aqaraOpple', data '{"airQuality":1}' from endpoint 1 with groupID 0
debug 2024-01-12 15:54:45: Received Zigbee message from 'airquality/livingroom', type 'attributeReport', cluster 'genAnalogInput', data '{"presentValue":5}' from endpoint 1 with groupID 0
info  2024-01-12 15:54:46: MQTT publish: topic 'zigbee2mqtt/airquality/livingroom', payload '{"air_quality":"excellent","battery":0,"device_temperature":20,"display_unit":"ppb_celsius","humidity":42.06,"last_seen":"2024-01-12T14:54:45.968Z","linkquality":134,"power_outage_count":21,"temperature":20.66,"voc":5,"voltage":2566}'
debug 2024-01-12 15:55:45: Received Zigbee message from 'airquality/livingroom', type 'attributeReport', cluster 'aqaraOpple', data '{"airQuality":1}' from endpoint 1 with groupID 0
debug 2024-01-12 15:55:45: Received Zigbee message from 'airquality/livingroom', type 'attributeReport', cluster 'genAnalogInput', data '{"presentValue":53}' from endpoint 1 with groupID 0
info  2024-01-12 15:55:46: MQTT publish: topic 'zigbee2mqtt/airquality/livingroom', payload '{"air_quality":"excellent","battery":0,"device_temperature":20,"display_unit":"ppb_celsius","humidity":42.06,"last_seen":"2024-01-12T14:55:45.677Z","linkquality":109,"power_outage_count":21,"temperature":20.66,"voc":53,"voltage":2566}'
debug 2024-01-12 15:56:15: Received Zigbee message from 'airquality/livingroom', type 'attributeReport', cluster 'aqaraOpple', data '{"airQuality":1}' from endpoint 1 with groupID 0
debug 2024-01-12 15:56:15: Received Zigbee message from 'airquality/livingroom', type 'attributeReport', cluster 'genAnalogInput', data '{"presentValue":131}' from endpoint 1 with groupID 0
info  2024-01-12 15:56:16: MQTT publish: topic 'zigbee2mqtt/airquality/livingroom', payload '{"air_quality":"excellent","battery":0,"device_temperature":20,"display_unit":"ppb_celsius","humidity":42.06,"last_seen":"2024-01-12T14:56:15.557Z","linkquality":109,"power_outage_count":21,"temperature":20.66,"voc":131,"voltage":2566}'
debug 2024-01-12 15:56:45: Received Zigbee message from 'airquality/livingroom', type 'attributeReport', cluster 'aqaraOpple', data '{"airQuality":2}' from endpoint 1 with groupID 0
debug 2024-01-12 15:56:45: Received Zigbee message from 'airquality/livingroom', type 'attributeReport', cluster 'genAnalogInput', data '{"presentValue":215}' from endpoint 1 with groupID 0
info  2024-01-12 15:56:45: MQTT publish: topic 'zigbee2mqtt/airquality/livingroom', payload '{"air_quality":"good","battery":0,"device_temperature":20,"display_unit":"ppb_celsius","humidity":42.06,"last_seen":"2024-01-12T14:56:45.486Z","linkquality":109,"power_outage_count":21,"temperature":20.66,"voc":215,"voltage":2566}'
debug 2024-01-12 15:57:15: Received Zigbee message from 'airquality/livingroom', type 'attributeReport', cluster 'aqaraOpple', data '{"airQuality":2}' from endpoint 1 with groupID 0
debug 2024-01-12 15:57:15: Received Zigbee message from 'airquality/livingroom', type 'attributeReport', cluster 'genAnalogInput', data '{"presentValue":254}' from endpoint 1 with groupID 0
info  2024-01-12 15:57:15: MQTT publish: topic 'zigbee2mqtt/airquality/livingroom', payload '{"air_quality":"good","battery":0,"device_temperature":20,"display_unit":"ppb_celsius","humidity":42.06,"last_seen":"2024-01-12T14:57:15.365Z","linkquality":112,"power_outage_count":21,"temperature":20.66,"voc":254,"voltage":2566}'
debug 2024-01-12 15:57:45: Received Zigbee message from 'airquality/livingroom', type 'attributeReport', cluster 'aqaraOpple', data '{"airQuality":3}' from endpoint 1 with groupID 0
debug 2024-01-12 15:57:45: Received Zigbee message from 'airquality/livingroom', type 'attributeReport', cluster 'genAnalogInput', data '{"presentValue":294}' from endpoint 1 with groupID 0
info  2024-01-12 15:57:45: MQTT publish: topic 'zigbee2mqtt/airquality/livingroom', payload '{"air_quality":"moderate","battery":0,"device_temperature":20,"display_unit":"ppb_celsius","humidity":42.06,"last_seen":"2024-01-12T14:57:45.245Z","linkquality":83,"power_outage_count":21,"temperature":20.66,"voc":294,"voltage":2566}'
```

Gets bumped at debug 2024-01-12 15:54:13 and then all none default reporting/binding config is gone... leaving just genAnalogInput, the non configurable aqaraOpple.airQuality and aqaraOpple one with all the non-decoded date.

Funny enough the two times I captured it, it had a report of batteryVoltage right before that where it dropped segnificantly, but it slowly stablesied again after. I did swap the shipped batteries with some higher quality varta industrial ones but that doesn't seem to have any effect. This device does have an e-ink display and I wonder if the occasional full refresh cylces just draw to much power.

In anycase, we should try and restore the bindings/reporting when this happens. The main question is how to get that information, it seems to come from 247 attribute which is some weird buffer array thing.

I guess an onEvent that looks for power_outage_count and compares it to the last known value might work.

**Comment by sjorge** [comment]
@Koenkk https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/lib/store.ts is not persistent across z2m restarts right ?

**Comment by Koenkk** [comment]
@sjorge it's not indeed.

**Comment by sjorge** [comment]
> @sjorge it's not indeed.

OK will need to look for another way then, can't save the cluster value as it's pulled out of the weird buffer structure.

**Comment by Koenkk** [comment]
You can use the `device.meta` to persist values across restarts, this is saved in the `database.db`. [example](https://github.com/Koenkk/zigbee-herdsman-converters/blob/ec95294f063279679f6ecb3ade68e3d896991311/src/devices/xiaomi.ts#L134)

**Comment by sjorge** [comment]
> You can use the `device.meta` to persist values across restarts, this is saved in the `database.db`. [example](https://github.com/Koenkk/zigbee-herdsman-converters/blob/ec95294f063279679f6ecb3ade68e3d896991311/src/devices/xiaomi.ts#L134)

Excellent, that should do nicely.

**Comment by sjorge** [comment]
@Koenkk I'm going to close this for now, there is definitely more cleanup and moving to modernExtend for Aqara/Xiaomi/LUMI devices that should happen at some point, but I don't have enough of them (I only have one) to push that to the end.

A low hanging fruit is mapping these attribute ID's properly in zcl/cluster.ts and probably renaming aqaraOpple to manuSpecificLumi. https://github.com/Koenkk/zigbee-herdsman-converters/blob/42cb4ddfe285b2468767483a7a3199735de1b924/src/lib/xiaomi.ts#L165

But I have no good way of testing this.
