### ISSUE TITLE
Ubisys C4 wong cluster manuSpecificUbisysHeatingRegulatorLevelCtrl  instead of LevelCtrl

### ISSUE THREAD

**Issue by devildant** [Koenkk/zigbee-herdsman-converters#6756]
Good morning,

given the configuration, I think there is a problem on the ubisys c4, the cluser manuSpecificUbisysHeatingRegulatorLevelCtrl  appears instead of levelCtrl.
but I have no idea how or where to correct this

**Comment by devildant** [comment]
![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/8700106/7258a35d-aed5-4d76-9f6a-0c4ca0c94f17)

**Comment by devildant** [comment]
link maybe : https://github.com/Koenkk/zigbee2mqtt/issues/19316

**Comment by devildant** [comment]
@Koenkk i think need help :p 

I've been searching for 5 hours, I can't find any reference to manuSpecificUbisysHeatingRegulatorLevelCtrl

**Comment by devildant** [comment]
I think it is this impl which causes the problem : https://github.com/Koenkk/zigbee-herdsman/pull/712

it's possible to override cluster ?

**Comment by Koenkk** [comment]
Cluster has just been removed in https://github.com/Koenkk/zigbee-herdsman/pull/835

**Comment by devildant** [comment]
> Cluster has just been removed in [Koenkk/zigbee-herdsman#835](https://github.com/Koenkk/zigbee-herdsman/pull/835)

hi @Koenkk , thx 
Well I just have to wait for an update to z2m :) I'm using HAos, it's practical but it blocks the hacks :(
Do you have any idea when a release will be made with this patch?

**Comment by Koenkk** [comment]
1 January

**Comment by devildant** [comment]
> 1 January

thank you, I wish you a happy Christmas Eve 🎉

**Comment by sjorge** [comment]
@devildant should be available in the latest release

**Comment by devildant** [comment]
> @devildant should be available in the latest release

yes it works like a charm thank you

**Comment by sjorge** [comment]
@Koenkk can you close it, doesn't look like I can as I didn't open this one.
