### ISSUE TITLE
Support for Nue/3A 3A12S-15 RGBW Controller

### ISSUE THREAD

**Issue by Frank1604** [Koenkk/zigbee-herdsman-converters#677]
Can you please add this device?

![grafik](https://user-images.githubusercontent.com/10420590/66338256-0bb3f580-e941-11e9-95a3-44834e3099bb.png)

![IMG_20191007_203018](https://user-images.githubusercontent.com/10420590/66338631-d065f680-e941-11e9-9585-a211ed25773f.jpg)

It looks similar to [this device](https://www.zigbee2mqtt.io/devices/XY12S-15.html).

zigbee.0 | 2019-10-07 19:44:40.814 | error | Unknown device model LXT56-LS27LX1.4 emit event readRsp with  data:{"cid":"genBasic","data":{"zclVersion":2,"appVersion":1,"stackVersion":1,"hwVersion":1,"dateCode":"20190604","swBuildId":"1000-0001"}
-- | -- | -- | --
zigbee.0 | 2019-10-07 19:44:40.705 | error | Unknown device model LXT56-LS27LX1.4 emit event readRsp with  data:{"cid":"genBasic","data":{"manufacturerName":"3A Smart Home  DE","modelId":"LXT56-LS27LX1.4","powerSource":1}}

**Comment by tushjd** [comment]
I have the same rbgw controller. Is there a possibility to add it?

**Comment by Koenkk** [comment]
See https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

**Comment by panachoi** [comment]
Is this helpful ?
[https://storage.googleapis.com/wzukusers/user-22742145/documents/40843fc7b2cb44888b00b1ac229bb4ab/Nue%20ZigBee%203.0%20RGBW%20Light%20Device%20Handler.docx](url)

**Comment by panachoi** [comment]
I just managed to pair this, which showed this:
info  2020-03-27 16:51:47: Successfully interviewed '0x00158d00047717ea', device has successfully been paired
info  2020-03-27 16:51:47: Device '0x00158d00047717ea' is supported, identified as: Smart Home Pty RGBW Downlight (HGZB-07A)
info  2020-03-27 16:51:47: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0x00158d00047717ea","model":"HGZB-07A","vendor":"Smart Home Pty","description":"RGBW Downlight","supported":true}}

Alas, I dont have my strip yet to see if it actually works correctly. Of course its not a Downlight.

**Comment by Koenkk** [comment]
Could you share your `database.db` file?

**Comment by panachoi** [comment]
{"id":10,"type":"Router","ieeeAddr":"0x00158d00047717ea","nwkAddr":56080,"manufI
d":4478,"manufName":"3A Smart Home DE","powerSource":"Mains (single phase)","mod
elId":"LXT56-LS27LX1.7","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"de
vId":269,"inClusterList":[0,4,3,6,8,5,768,4096,25],"outClusterList":[25],"cluste
rs":{"genBasic":{"attributes":{"modelId":"LXT56-LS27LX1.7","manufacturerName":"3
A Smart Home DE","powerSource":1,"zclVersion":3,"appVersion":1,"stackVersion":1,
"hwVersion":1,"dateCode":"20190604","swBuildId":"1000-0001"}}},"binds":[]}},"app
Version":1,"stackVersion":1,"hwVersion":1,"dateCode":"20190604","swBuildId":"100
0-0001","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1585324307
405}

**Comment by Koenkk** [comment]
Besides the wrong description, does it work correctly?

**Comment by panachoi** [comment]
As soon as I get my actual RGBW stripe, I can let you know, but it seems to accept mqtt commands without error:
mosquitto_pub -h localhost -u XXX -P YYY -t "zigbee2mqtt/3A-12S-RGBW/set" -m '{ "brightness": "100", "state":"on", "color":{"rgb":"51,52,53"} }
info  2020-03-29 10:09:33: MQTT publish: topic 'zigbee2mqtt/3A-12S-RGBW/state', payload 'ON'
info  2020-03-29 10:09:33: MQTT publish: topic 'zigbee2mqtt/3A-12S-RGBW/brightness', payload '100'
info  2020-03-29 10:09:33: MQTT publish: topic 'zigbee2mqtt/3A-12S-RGBW/color-x', payload '0.3158'
info  2020-03-29 10:09:33: MQTT publish: topic 'zigbee2mqtt/3A-12S-RGBW/color-y', payload '0.3252'
info  2020-03-29 10:09:33: MQTT publish: topic 'zigbee2mqtt/3A-12S-RGBW/state', payload 'ON'
info  2020-03-29 10:09:33: MQTT publish: topic 'zigbee2mqtt/3A-12S-RGBW/brightness', payload '100'
info  2020-03-29 10:09:33: MQTT publish: topic 'zigbee2mqtt/3A-12S-RGBW/color-x', payload '0.3158'
info  2020-03-29 10:09:33: MQTT publish: topic 'zigbee2mqtt/3A-12S-RGBW/color-y', payload '0.3252'

**Comment by panachoi** [comment]
This works I think as it should with RGBW strip that I have. I can happily change the RGB values and brightness by varying the values in the following command:

mosquitto_pub -h localhost -u XXX -P XXX -t "zigbee2mqtt/3A-12S-RGBW/set" -m '{ 
"brightness": "100", "state":"on", "color":{"rgb":"51,52,53"} }'

Not sure how to work the White bit, though. The json state shows this:

    "0x00158d00047717ea": {
        "state": "ON",
        "brightness": 20,
        "color": {
            "x": 0.1724,
            "y": 0.7468
        },
        "color_temp": 154

**Comment by Bladeacus** [comment]
> I just managed to pair this, which showed this:
> info 2020-03-27 16:51:47: Successfully interviewed '0x00158d00047717ea', device has successfully been paired
> info 2020-03-27 16:51:47: Device '0x00158d00047717ea' is supported, identified as: Smart Home Pty RGBW Downlight (HGZB-07A)
> info 2020-03-27 16:51:47: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0x00158d00047717ea","model":"HGZB-07A","vendor":"Smart Home Pty","description":"RGBW Downlight","supported":true}}
> 
> Alas, I dont have my strip yet to see if it actually works correctly. Of course its not a Downlight.

Hi, how did you manage to pair this device? 
I've tried by holding the reset button down for 10-15 seconds and the light flashes to signal a reset, but nothing on zigbee2mqtt side..
