### ISSUE TITLE
Model TS011F_plug_1 Zigbee Manufacturer _TZ3000_okaz9tjs incorrect current unit

### ISSUE THREAD

**Issue by izayash** [Koenkk/zigbee-herdsman-converters#6771]
Model TS011F_plug_1 Zigbee Manufacturer _TZ3000_okaz9tjs incorrect current unit
The current is displayed in amperes, although in fact the reading corresponds to milliamps.
![rrrrr](https://github.com/Koenkk/zigbee-herdsman-converters/assets/24999619/b1170219-31f2-4297-baee-968865f01972)

**Comment by Koenkk** [comment]
This should be fixed in the Z2M 1 January release.
