### ISSUE TITLE
VOCKQJK11LM: temperature unit should be °C and not ºC

### ISSUE THREAD

**Issue by F3lich** [Koenkk/zigbee-herdsman-converters#6808]
This causes a log warning and loss of sensor data in home assistant after updating to z2m 1.35.0-1:

Entity sensor.VOCKQJK11LM_temperature (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'ºC' which is not a valid unit for the device class ('temperature') it is using; expected one of ['°C', 'K', '°F']; 

https://github.com/Koenkk/zigbee-herdsman-converters/blob/30722e41aca92d23154cc8f9610fe5fbc1d112cc/src/lib/modernExtend.ts#L552

**Comment by svadel** [comment]
Hi, I have the same problem. Fixing the parameter in file modernExtend.js line 459 "unit: 'ºC'" solved the issue.

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
