### ISSUE TITLE
IDlock 150(0402946 - Datek) - Door state missing

### ISSUE THREAD

**Issue by christian1986** [Koenkk/zigbee-herdsman-converters#6820]
Hoping someone can change the integration for this one. Door state would be really nice to have(and is included in the zwave integration).

The door state is exposed in Z2M, but not forwarded to Home-Assistant.
![3ecdee02-5ab5-4b55-b2f7-b1309b5f8903](https://github.com/Koenkk/zigbee-herdsman-converters/assets/4373980/fc613b59-e631-4d1e-ae20-bb988e03e65a)

Should be a quick fix(?), but I'm not capable of making a PR for it.

**Comment by christian1986** [comment]
Z2M gets the information.

![PNG-bilde](https://github.com/Koenkk/zigbee-herdsman-converters/assets/4373980/4198ba5e-67e3-40f0-810a-d46fbdb664d7)

Found a smilar issue for ZHA(where its solved).

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5739

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by christian1986** [comment]
Thanks!
