### ISSUE TITLE
Lower bound of "turnsOffAtBrightness1" ignored by "brightness_move" & "brightness_step" commands

### ISSUE THREAD

**Issue by burmistrzak** [Koenkk/zigbee-herdsman-converters#6877]
Hi Koen 👋

just stumbled upon an interesting issue, apparently first reported [here](https://github.com/itavero/homebridge-z2m/issues/673), that sent me down a deep rabbit hole to find the root cause. 🕳️🐇

My findings so far:
When a light, that has the `turnsOffAtBrightness1` option set (e.g. Philips Hue), and receives either a `brightness_move` or `brightness_step` (e.g. -85) [command](https://github.com/Koenkk/zigbee-herdsman-converters/blob/6939b177651897c964a577279103c22c7e58f372/src/converters/toZigbee.ts#L854), it will _almost always_ be dimmed down to a brightness level of `1`, causing all sorts of weird issues downstream.
One does only encounter this bug when controlling lights with automations (Node-RED, etc.) which utilize the aforementioned commands.

**Note:** This behavior is reproducible, but _sometimes_ the `bightness_move` will just stop at `5` instead of going all the way down to `1`... Why that's happening, I'm not quite sure yet. 🤷

### Expected behavior
Dimming stops at a brightness level of `2`, when a given bulb has `turnsOffAtBrightness1` set.

### Actual behavior
Lights always get dimmed down to `1`, ignoring any lower bound set by the `turnsOffAtBrightness1` option.

### System details
Zigbee2MQTT version: 1.35.1@9eaaa0f
Coordinator type: zStack3x0
Coordinator revision: 20230507
Frontend version: 0.6.151
Zigbee-herdsman-converters version: 18.9.0
Zigbee-herdsman version: 0.30.0

**Comment by Koenkk** [comment]
> As far as I know, and please someone correct me here, the actual brightness range is controlled by a given bulb's firmware...

That's true, I don't this is fixable for z2m for these native commands.

**Comment by Koenkk** [comment]
> While brightness_move most likely can't be fixed at our end, brightness_step could, at least in theory, take turnsOffAtBrightness1 into account and stop at 2, right?

True, would you mind submitting a PR for that?

**Comment by Koenkk** [comment]
That's indeed the solution I expect!

> There's also the slight possibility of a hit in performance, because we would have to run that code before every single dimming step...

A lot of code runs before this command, I have no worries about a performance hit 😄

**Comment by Koenkk** [comment]
I don't have any modern Hue lights to test with, but you can try and see if it works without.

**Comment by Koenkk** [comment]
>  without creating a custom build?

Yes, by making an external converter: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_2-creating-the-external-definition

**Comment by Koenkk** [comment]
@burmistrzak you mean fixing it for `brightness_step`?
