### ISSUE TITLE
Elko regulator (4523430) gives error message when trying to set display text

### ISSUE THREAD

**Issue by Kodemikkel** [Koenkk/zigbee-herdsman-converters#6883]
I have a flow in Node-Red in Home Assistant that normally sets the text on my Elko regulator (4523430) to display the temperature and humidity, but I noticed this stopped working. I am not sure for how long this has not been working.

To see if it was a Home Assistant problem or a Z2M problem, I opened my Z2M dashboard and tried setting the text manually on the device using the "Exposes" tab and the "Display text" input field.
Doing this, I get the error message:
`Publish 'set' 'display_text' to 'Bathroom regulator' failed: 'Error: Value is not an array, got string (test)'`

The text in the parentheses is what I'm currently trying to set.

After digging through some of the code, I think this is caused by the line added in `toZigbee.ts` 2 months ago when converting the converter to TS (according to the merge):
https://github.com/Koenkk/zigbee-herdsman-converters/blame/42e1cecd35fd7c45919a2d7d102bba78dec3e684/src/converters/toZigbee.ts#L1809

This is also why I posted this issue in this repo.

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
