### ISSUE TITLE
Energy consumption unit is wrong for LLKZMK12LM (Aqara dual relay module T2)

### ISSUE THREAD

**Issue by alexpirine** [Koenkk/zigbee-herdsman-converters#6889]
The reported energy consumption is displayed in kWh, while the device reports it in Wh.

Example:

<img width="427" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/1610035/4e815d27-26f9-4637-b0dc-dd5993da76f9">

I checked xiaomi.ts file, and I see:

```typescript
    {
        zigbeeModel: ['lumi.switch.acn047'],
        model: 'LLKZMK12LM',
        vendor: 'Xiaomi',
        whiteLabel: [{vendor: 'Xiaomi', model: 'DCM-K01'}],
        description: 'Aqara dual relay module T2',
        fromZigbee: [fz.on_off, xiaomi.fromZigbee.aqara_opple, fz.xiaomi_power],
        toZigbee: [tz.on_off],
        meta: {multiEndpoint: true},
        endpoint: (device) => {
            return {'l1': 1, 'l2': 2};
        },
        exposes: [e.switch().withEndpoint('l1'), e.switch().withEndpoint('l2'),
            e.power(), e.current(), e.energy(), e.voltage(), e.device_temperature(),
        ],
...
```

But `energy` is defined in kWh in the presets:

```
energy: () => new Numeric('energy', access.STATE).withUnit('kWh').withDescription('Sum of consumed energy'),
```

I am new to this project, I'm not sure how to fix and test it.

Maybe this?

```typescript
        exposes: [e.switch().withEndpoint('l1'), e.switch().withEndpoint('l2'),
            e.power(), e.current(), e.energy().withUnit('Wh'), e.voltage(), e.device_temperature(),
        ],
```

I am also trying to figure out how items in the "exposes" list map to the device's cluster attributes.

**Comment by mrskycriper** [comment]
> Maybe this?
Looks good, I'd suggest creating a pull request.

**Comment by kevin-dumont** [comment]
Hi,
I have the device as well and I can confirm the exposed value for energy is wrong.

But I'm not sure it's a unit issue, because I manually calculated the energy for my use case, based on the power.

I use this device since 1 month, and every day, I turn it on for 2 hours (with an automation, so it's exactly 2 hours), with a constant power of approximately 800W.
Normally, I should get 800W * 2h = 16000Wh = 1,6KWh.

But the device exposes, every day a value between 700 and 750kWh.
If it was a unit issue, I should have something like 1600kWh.

**Comment by alexpirine** [comment]
> But the device exposes, every day a value between 700 and 750kWh. If it was a unit issue, I should have something like 1600kWh.

So in your case, the reported value is about 500 times higher.

I don't know the exact consumption of my devices, but it seemed about 1000 times lower than the reported value.

When I have a chance, I will measure the error, maybe in a few weeks.

**Comment by kevin-dumont** [comment]
The power of 800W comes from the module and seems realistic for my device.

May be you can check if the power exposed by the module to have an idea

**Comment by mrskycriper** [comment]
Any progress on figuring out, what is really wrong with the unit of measurement? I can help with the implementation (or rather will implement it myself) if the problem is identified. E.g. what is the correct offset or devider needed here?

**Comment by nicolinuxfr** [comment]
@mrskycriper 

Not sure, but here are some data from my device. As far as I can tell, the energy unit is wrong, it should be Wh and not kWh. But it's more than that I think, dividing by 1000 would not be enough if we can trust the power reported by the T2.

<img width="1634" alt="Capture d’écran 2024-03-11 à 20 41 37" src="https://github.com/Koenkk/zigbee-herdsman-converters/assets/2078386/eb1aaef7-6555-4f7f-b426-ca793dfb1a81">

It's more clear here, where the power stayed around 110 W for about an hour and the energy was up around 220 kWh during the same time. For this one, it should be divided by 2000 but I don't have an easy way to verify the power measure.

<img width="1651" alt="Capture d’écran 2024-03-11 à 20 42 35" src="https://github.com/Koenkk/zigbee-herdsman-converters/assets/2078386/f9bda64d-0fd9-423d-bada-7e808d661a1a">

Here are the raw data if needed : 
[history.csv](https://github.com/Koenkk/zigbee-herdsman-converters/files/14563879/history.csv)

For what it worth, the power data seems correct, at least it makes sense for my use. The T2 controls a kitchen hood and it reports around 5W of power when only the lights are on, and up to 160 W or so when using the device at maximal speed. 

Let me know if I can help debug by an other way.

**Comment by mrskycriper** [comment]
@nicolinuxfr I'd suggest temporarily using a [Riemann sum integral](https://www.home-assistant.io/integrations/integration/) integration. It should accurately count the energy from power readings. And then sharing the results after some data is collected. Right now division by 1000 seems to be the best choice overall

**Comment by alexpirine** [comment]
I have equipment to make precise measurements. Maybe we can use the 437 value for now, which seems good enough already, and when I will have a bit of time, I will measure the exact ratio, and we'll refine it if needed.

**Comment by mrskycriper** [comment]
I can add an extra option for configuring this divider within zigbee2mqtt web interface
