### ISSUE TITLE
Color Control Cluster,  Command "Move color temperature", parameter "mode" interpreted wrong

### ISSUE THREAD

**Issue by GerardHaagh** [Koenkk/zigbee-herdsman-converters#6918]
(found in release 18.9.0, also present in master branch)

**Problem:**
The Prolight remote control can send the "Move color temperature command" (Color Control Cluster 0x0300, command 0x4b).
When using this device with zigbee2mqtt, it passes only color_temperature_move_up and color_temperature_move_down commands and never a color_temperature_move_stop. 

- When the button that causes a color_temperature_move_down was released it sent a color_temperature_move_up (I expected something with 'stop' instead)
- When the button that causes a color_temperature_move_up was released it also sent a (second) color_temperature_move_up (I expected something with 'stop' instead)

**Tested/detected with device:**
        zigbeeModel: ['PROLIGHT REMOTE CONTROL'],
        model: '5412748727388',
        vendor: 'Prolight',

**Analysis:**
I traced this down to the zigbee-herdsman-converters source (fromZigbee.js in the Z2M distro) where the command parameters are parsed/processed. The "Move mode" parameter is parsed incorrectly. 
According to the Cluster Library Specification this should be: 0=Stop, 1=Up, 3=Down  (2=Reserved, other values unspecified).
When making the indicated change locally (see below), I got the expected messages from Zigbee2mqtt.

zigbee-herdsman-converters/src/converters/fromZigbee.ts (near line 1350):
```
   command_move_color_temperature: {
        cluster: 'lightingColorCtrl',
        type: ['commandMoveColorTemp'],
        convert: (model, msg, publish, options, meta) => {
            if (hasAlreadyProcessedMessage(msg, model)) return;

--->        //const direction = msg.data.movemode === 1 ? 'down' : 'up';
--->        const direction = (msg.data.movemode === 1 ? 'up': (msg.data.movemode === 3 ? 'down' : 'stop'));			

            const action = postfixWithEndpointName(`color_temperature_move_${direction}`, msg, model, meta);
            const payload = {action, action_rate: msg.data.rate, action_minimum: msg.data.minimum, action_maximum: msg.data.maximum};
            addActionGroup(payload, msg, model);
            return payload;
        },
    } satisfies Fz.Converter,
```
**I don't know how to fix this using pull requests etc. Can someone please do this?**

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
