### ISSUE TITLE
Ikea Parasoll E2013 Battery feedback 0%

### ISSUE THREAD

**Issue by HomeSeerRobbie** [Koenkk/zigbee-herdsman-converters#6927]
Hi, thx for creating the Ikea Sensors so quick after they became available here in Belgium. I got them working in HS4 now with version 1.35.1 since a few days. Only thing not working is the battery level feedback - stays at 0%. is that a Zigbee issue or a HS4 issue (they show up with 5 different levels red to green during config)
rgds. R.

**Comment by mklooss** [comment]
has already been fixed in #6892 in zigbee-herdsman-converters [v18.12.0](https://github.com/Koenkk/zigbee-herdsman-converters/releases/tag/v18.12.0)

zigbee2mqtt@1.35.1 use herdsman Version: 18.9.0

**Comment by metbril** [comment]
Sorry for cross-posting.

I have added a sensor 3 days ago, but the battery is still reporting `Null` for the battery. Should I submit a new issue?

I'm running the latest HA addon `1.35.1-1`

![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/559346/fc150b54-d564-4f55-b1be-5f1aae2d506a)

**Comment by Koenkk** [comment]
@metbril should be fixed in the 1 February release.
