### ISSUE TITLE
Ikea blinds switch E1743 not showing in mqtt

### ISSUE THREAD

**Issue by Kiwifranky** [Koenkk/zigbee-herdsman-converters#694]
Hi, maybe I missed something...

I installed z2m like following the excellent instructions on the webpage. I also updated to the latest version. I am using a stick with the software preinstalled from 06 2019 running on a raspberry.
When I try to connect a E1743 it shows up under devices in the configuration.yaml, but not as a mqtt endpoint.

Log says:
10/18/2019, 6:35:47 PM - warn: Device with modelID 'TRADFRI open/close remote' is not supported.

Do I have to install a special version, because the documentation says it is supported? 
How will this be done, if there are extra steps to follow? (Linux noob!)

Are the blind (Fyrtur) also integrated or will this happen later?

Thanks for your help!!!

**Comment by Koenkk** [comment]
These are only supported in the dev branch, read zigbee2mqtt.io on how to switch to it.
