### ISSUE TITLE
[Question] Need help with modernExtend

### ISSUE THREAD

**Issue by mrskycriper** [Koenkk/zigbee-herdsman-converters#6956]
I was trying to make a custom converter for may bricked ZNLDP12LM Aqara light that doesn't support power_outage_memory because of broken OTA. However I got stuck, trying to import xiaomiModernExtend into custom converter.

This is my attempt at removing them:
```js
const xiaomi = require('zigbee-herdsman-converters/lib/xiaomi');
const {xiaomiLight} = xiaomi.modernExtend;

const definition = {
    zigbeeModel: ['lumi.light.aqcn02'],
    model: 'ZNLDP12LM',
    vendor: 'Xiaomi',
    description: 'Aqara smart LED bulb',
    extend: [xiaomiLight({colorTemp: true})],
};

module.exports = definition;
```

But it fails to load on startup with this error: `Failed to load external converter file 'ZNLDP12LM.js' (xiaomiLight is not a function)`. How to do it the right way?

**Comment by Koenkk** [comment]
Are you using the [latest dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)?

**Comment by mrskycriper** [comment]
Oh, I forgot that those changes are not in the release yet. It's supposed to be a quick and dirty fix on my main setup. I'll use an old converter for reference then for now.
