### ISSUE TITLE
HELP: Tuya Curtain Motor AM43

### ISSUE THREAD

**Issue by Chicken123321** [Koenkk/zigbee-herdsman-converters#6979]
MOES AM43
TS0601
_TZE200_zah67ekd
^ this works perfectly

I bought new AM43 from MOES lately and it is not reading any exposes, manufacturer unsupported
Zigbee Manufacturer changed to _TZE200_icka1clh

So I can't use new motors and idk what to do

**Comment by Koenkk** [comment]
`_TZE200_icka1clh` will be supported in the 1 February release.
