### ISSUE TITLE
Use of wildcard in list of possible values for enum expose

### ISSUE THREAD

**Issue by spudwebb** [Koenkk/zigbee-herdsman-converters#7024]
The Vesternet VES-ZB-REM-013 device use some wildcards like "on_*"
 in the definition of its Action expose 
https://github.com/Koenkk/zigbee-herdsman-converters/blob/0fcaeef8210c6c2635abe85c37e2a26c6f17d4f3/src/devices/vesternet.ts#L77-L78

This is causing some problems in the integration of Z2M with HomeSeer as it doesn't expect any wildcard here, and it prevents it to know exactly the number of buttons for this device. Is the use of wildcards standard here? I don't think I saw that for any other products.

Couldn't this be replaced by enumerating all the possible values instead, like for this other Vesternet device (ZG2833K8_EU05)

https://github.com/Koenkk/zigbee-herdsman-converters/blob/0fcaeef8210c6c2635abe85c37e2a26c6f17d4f3/src/devices/vesternet.ts#L187-L191

**Comment by Koenkk** [comment]
Yes, could you make a PR?
