### ISSUE TITLE
FEATURE REQUEST: Files devices.js and fromzigbee.js are getting long & unwieldly.  Can we considder splitting by manufacturer or device type?

### ISSUE THREAD

**Issue by wixoff** [Koenkk/zigbee-herdsman-converters#706]
Not only are the existing files very long, but they do not have many comments or whitespace.  I'd recommend splitting them by manufacturer or device type, and I'd further recommend encouraging PRs to include code comments to explain how each device converter works, where isn't obvious.

**Comment by Koenkk** [comment]
Both have it's pros and cons, but I currently feel that the single file solution is a better one (when e.g. wanted to add support for new devices and finding definitions of already supported devices).

**Comment by skandragon** [comment]
Is part of the problem that older entries are not removed, in favor of a more complete entry?
