### ISSUE TITLE
Proposal: Don't enable legacy mode by default

### ISSUE THREAD

**Issue by klada** [Koenkk/zigbee-herdsman-converters#7076]
For quite some time now there have been a few converters out there which create a so-called "legacy payload" (see `src/lib/legacy.ts`).

Even new installs have to deal with those legacy payloads. We have the option to disable `legacy` per device to get "non-legacy" payloads. According to the description of the `legacy` exposes definition it's even recommended to set `legacy` to `false` ([see this](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/lib/exposes.ts#L616)):

| _Set to false to disable the legacy integration (highly recommended)_

Now the question is: if it's highly recommended to disable the legacy integration, why is it still active by default? Maybe the time has finally come to change the default value of `legacy` from `true` to `false`.

Pro arguments:

- New installs will use new-style payloads by default
- We have some issues with legacy payloads in ioBroker, which uses zigbee-herdsman-converters. Unfortunately ioBroker apparently cannot disable `legacy` on a per-device basis.
- The term "legacy" refers to something that we should get rid of at some point. So it's not good to keep this stuff enabled by default.
- When only changing the default value, existing setups which rely on legacy payloads just need to set the `legacy` attribute and are done

Con arguments:

- This needs to be communicated clearly in the release notes. It may break automations (but fortunately the fix is easy, as legacy-mode could still be enabled explicitly per-device when needed)

**Comment by Koenkk** [comment]
Its already disabled by default for new installs

**Comment by klada** [comment]
@Koenkk I think you are referring to [this commit](https://github.com/Koenkk/zigbee2mqtt/commit/0401a13d5d4f813c95b6728fc4599fc7db6eb400) in zigbee2mqtt, right?

There is one issue with this. If `legacy` is not set (neither to `true` nor to `false`) then zigbee-herdsman-converters assumes `legacy=true`. This is what I am referring to.

The thing is that other tools such as ioBroker are using zigbee-herdsman-converters as well and will keep using the legacy converters forever if the defaults in zigbee-herdsman-converters don't change. I'll ask if they can disable legacy mode in their environment as well to work around an issue they are having with the Busch-Jaeger devices.

But nevertheless any tool relying on the converters will need to explicitly do this. Maybe it's still a consideration to change the default at some point.

**Comment by lattice0** [comment]
Sorry but what is legacy option?

**Comment by Koenkk** [comment]
@klada the default will not be changed, instead the legacy converters will be removed at a certain point. But this is a breaking change so not soon.

**Comment by klada** [comment]
> @klada the default will not be changed, instead the legacy converters will be removed at a certain point. But this is a breaking change so not soon.

Thanks for the clarification. I'll close this issue then and forward the info to the ioBroker developers.
