### ISSUE TITLE
Paulmann 500.67 RGB-CCT remote control not recognized

### ISSUE THREAD

**Issue by aurimasfgit** [Koenkk/zigbee-herdsman-converters#7091]
Hello,

I have Paulmann Gent Remote Control (https://en.paulmann.com/p/remote-control-smart-home-zigbee-3.0-gent-black/50067) and trying to add it to my Zigbee network. I'm using newest Home Assistant version and Sonoff Zigbee 3.0 USB Dongle Plus-P. When I add device I see message that it's NOT supported: `Device 'Remote 1' with Zigbee model '50067' and manufacturer name 'Paulmann Licht GmbH' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html`. In this repo (https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/devices/paulmann.ts) I see that this device is included, but there's wrong model name: 
```
{
        zigbeeModel: ['RemoteControl'],
        model: '500.67',
        vendor: 'Paulmann',
        description: 'RGB remote control',
        fromZigbee: [fz.command_on, fz.command_off, fz.command_toggle, fz.command_step, fz.command_move_to_color_temp,
            fz.command_move_to_color, fz.command_stop, fz.command_move, fz.command_color_loop_set,
            fz.command_ehanced_move_to_hue_and_saturation, fz.tint_scene],
        toZigbee: [],
        exposes: [e.action([
            'on', 'off', 'toggle', 'brightness_step_up', 'brightness_step_down', 'color_temperature_move', 'color_move', 'brightness_stop',
            'brightness_move_down', 'brightness_move_up', 'color_loop_set', 'enhanced_move_to_hue_and_saturation', 'scene_*'])],
}
```
Any ideas how to fix it? Do need to add '50067' into zigbeeModel array?

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
