### ISSUE TITLE
The Philips Bulb 9290018216 was found as Philips Bulb 8718699673147 "Wrong recognition"

### ISSUE THREAD

**Issue by cracyfloyd** [Koenkk/zigbee-herdsman-converters#7092]
What did you expect to happen?
The result is now that i have the wrong firmware flashed. Can you help to fix.

How to reproduce it (minimal and precise)
every time i learn the device new. new recognition of bulb.

Zigbee2MQTT version
1.35.3-dev commit: https://github.com/Koenkk/zigbee2mqtt/commit/2aaf878889b4211b8a470c847721c75b5a91e39e

Adapter firmware version
0x26500900

Adapter
Conbee 3

Setup
Docker

Debug log
No response

**Comment by mrskycriper** [comment]
Philips Hue models are currently a giant mess of different devices mashed together. I'll try cleaning it up a little bit soon. 

As for the wrong firmware, what zigbee model does it report now and is it the same as before the update?
