### ISSUE TITLE
Add Battery status for Yale YMF40 Lock

### ISSUE THREAD

**Issue by matisaul** [Koenkk/zigbee-herdsman-converters#710]
I created a PR for add battery status for Yale YMF40 Lock (just need to add 'attReport' type in battery_200 on fromZigbee.js: https://github.com/Koenkk/zigbee-herdsman-converters/pull/709

And add the battery propertie in YMF40 on devices.js: https://github.com/Koenkk/zigbee-herdsman-converters/pull/708

`
zigbee2mqtt:warn 10/23/2019, 9:37:33 AM No converter available for 'YMF40' with cid 'genPowerCfg', type 'attReport' and data '{"cid":"genPowerCfg","data":{"batteryPercentageRemaining":90}}'
`
`
 zigbee2mqtt:warn 10/23/2019, 9:37:33 AM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
`

Thanks!

**Comment by Koenkk** [comment]
Merged, thanks!
