### ISSUE TITLE
Select exposed device functions based on the version number

### ISSUE THREAD

**Issue by lcheng33775823** [Koenkk/zigbee-herdsman-converters#7108]
I looked at previous examples from other vendors and implemented them, and found that when it existed with extend, it reported an error. Is there another way to do this function: "Expose device function based on version number"?

![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/47738738/d965979b-72be-40c5-9a3a-2b92547141cc)

**Comment by lcheng33775823** [comment]
Hi @Koenkk , Please help me look at this problem.

**Comment by Koenkk** [comment]
It's currently not possible to use both the modernExtend and function expose.

**Comment by lcheng33775823** [comment]
All right. Thank you for your reply
