### ISSUE TITLE
Lumi TRV RangeError on post-pairing empty buffer message

### ISSUE THREAD

**Issue by Nerivec** [Koenkk/zigbee-herdsman-converters#7128]
_I'm not familiar with the Lumi stuff at all, so, not creating a PR right away on this one... just in case (though it should just need a check on value)._

I've clocked a `RangeError: Attempt to access memory outside buffer bounds` originating from this line:
https://github.com/Koenkk/zigbee-herdsman-converters/blob/919166ad8f8948be51b20dff32a0986c331ed022/src/lib/lumi.ts#L2061

and caused by:
https://github.com/Koenkk/zigbee-herdsman-converters/blob/919166ad8f8948be51b20dff32a0986c331ed022/src/lib/lumi.ts#L1016

```log
debug 2024-02-23 10:07:06: Received Zigbee message from '0x54ef441000700586', type 'readResponse', cluster 'manuSpecificLumi', data '{"630":{"data":[],"type":"Buffer"}}' from endpoint 1 with groupID 0
```

The buffer seems to be empty in the post-pairing message, which throws since the buffer is assumed to always have a value.

Caught in a log provided by @Mar1usW3 (device identified as `Aqara Smart radiator thermostat E1 (SRTS-A01)`)

**Comment by Koenkk** [comment]
Pushed a fix!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
