### ISSUE TITLE
Support for NUE/3A - HGZB-4D-UK

### ISSUE THREAD

**Issue by Twit123** [Koenkk/zigbee-herdsman-converters#717]
Hi,

EDIT: I think I figured out how to add it myself, just leaving this here in case I got it wrong, I've never done a pull request on git.
-------------------------------------------------------------------------------------------

Could you please add the NUE/3A HGZB-4D-UK dimmer switch.
It actually reports as "FNB56-ZBW01LX1.2" but has a different model name, presumably the UK version is the same as the EU version besides the model number. 

I just change the following FROM:
```
    {
        zigbeeModel: ['FB56+ZSC05HG1.0', 'FNB56-ZBW01LX1.2'],
        model: 'HGZB-04D',
        vendor: 'Nue / 3A',
        description: 'Smart dimmer wall switch',
        supports: 'on/off, brightness',
        toZigbee: [tz.on_off, tz.light_brightness],
        fromZigbee: [fz.state, fz.brightness],
    },
```
TO:
```
    {
        zigbeeModel: ['FB56+ZSC05HG1.0', 'FNB56-ZBW01LX1.2'],
        model: 'HGZB-04D / HGZB-4D-UK',
        vendor: 'Nue / 3A',
        description: 'Smart dimmer wall switch',
        supports: 'on/off, brightness',
        toZigbee: [tz.on_off, tz.light_brightness],
        fromZigbee: [fz.state, fz.brightness],
    },
```
This works perfectly. 

Thanks

Simon

**Comment by Koenkk** [comment]
Merged, you PR, thanks.
