### ISSUE TITLE
Proposal: deprecation of legacy clicks

### ISSUE THREAD

**Issue by mrskycriper** [Koenkk/zigbee-herdsman-converters#7210]
Since we have a new major version number and Extend was deprecated. I propose the removal of legacy clicks as well. It seems that not a lot of users make use of them on a modern versions. And the list of legacy enabled devices is proportionally getting smaller each day. Moreover, legacy converters are hindering their full conversion to Modern Extend.

**Comment by Koenkk** [comment]
This will not only force for a breaking change update of zhc, but more importantly z2m. And I'm still struggling with the fact if we want this or not.

**Comment by mrskycriper** [comment]
At some point it will be necessary. I’m currently working on a new batch modern extend conversions and legacy clicks are really out place there. Certainly they have no place in modern extends.

But it’s definitely a hard change for those who use those old devices.
