### ISSUE TITLE
Additional Device for Tuya Cover_3

### ISSUE THREAD

**Issue by keithskillicorn** [Koenkk/zigbee-herdsman-converters#7264]
Zemismart ZM25R3 (25mm cover motor, battery powered, zigbee) https://www.zemismart.com/products/zm25r3

Fingerprint: _TZE200_eevqq1uv

I created a definition.js file for the device using the cover_3 definition from tuya.ts, replacing one of the products with _TZE200_eevqq1uv.

Basic functions work.  Will test boundary limit settings and all other functions when I have it installed.

Apologies for not updating files myself (I don not have a sufficient depth of understanding yet), let me know if you require further info.

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
