### ISSUE TITLE
Bosch Twinguard exposes only CO2 instead of VOC levels

### ISSUE THREAD

**Issue by burmistrzak** [Koenkk/zigbee-herdsman-converters#7274]
Hi folks,
I've been preparing to finally migrate a handful of Bosch Twinguards to Z2M and saw that the current implementation exposes the VOC sensor readings as CO2 (ppm) instead of VOC (µg/m³).

While @safakaltun did absolutely stellar work, reverse engineering Bosch's ZCL extension, their choice to expose the VOC readings as CO2-equivalent (?) doesn't seem quite right to me.

- First, the [mentioned](https://github.com/Koenkk/zigbee2mqtt/issues/14355#issuecomment-1339677829) [data sheet](https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bme680-ds001.pdf) for the [BME680 sensor](https://www.bosch-sensortec.com/products/environmental-sensors/gas-sensors/bme680) explicitly states that the sensor _cannot_ directly measure CO2 levels (p. 25), instead having to estimate them.
- Second, it's a bit unclear, to me at least, how @safakaltun came up with that [ppm conversion](https://github.com/Koenkk/zigbee-herdsman-converters/blob/8a3f6442f4dcd88ff7ff26bf5c1669125c43a27c/src/devices/bosch.ts#L786) formula. I guess they tried matching the value from the Bosch Smart Home app? 🤔
- And third, exposing only a CO2 (and no VOC) sensor in Z2M, has some unintended consequences for downstream systems like homebridge-z2m. Namely e.g. a missing VOC sensor in HomeKit, something the native integration from Bosch (via their Smart Home Controller) already supports.

Now, what to do about this situation?
Well, simply exposing the raw AQI value isn't super useful because, among other things, there are **many different, national AQI scales** out there. AFAICT, the Twinguard uses the German AQI internally.

@Koenkk What do you think about exposing an additional VOC level, so to not break backwards compatibility while adding to the overall usefulness of the device? 👀

**Comment by Koenkk** [comment]
Im fine with that!

**Comment by safakaltun** [comment]
Hi, “alarm” is an action. Doesn’t have a state until you trigger it. Once you do that, you will see “siren state” changing accordingly.

**Comment by safakaltun** [comment]
Current “voc” sensor in z2m has a different unit that ppm. Twinguard uses ppm as voc unit in the bosch app. It also directly reports the voc ppm value. Using co2 sensor was just a workaround to get it implemented into z2m without a lot of hassle. Not 100% correct, but didn’t really matter back then whether it was called co2 or voc or a banana. Happy that you are fixing it :)

**Comment by safakaltun** [comment]
> > Current “voc” sensor in z2m has a different unit that ppm. Twinguard uses ppm as voc unit in the bosch app. It also directly reports the voc ppm value.
> 
> Yup, Bosch is certainly doing some funny business here. Their own data sheet explicitly states, that the BME680 sensor is incapable of directly measuring CO2 levels. They absolutely have to do some calculations on their end, to produce a ppm value from just AQI.
> 
> `result.co2 = msg.data['airpurity'] * 10.0 + 500.0;` On that note, how'd you come up with [this](https://github.com/Koenkk/zigbee-herdsman-converters/blob/a5170089dde9e054683377c75fdbb9df1e693616/src/devices/bosch.ts#L786C61-L787C14) specific conversion formula?

Yes, but it is based on the sniffs and what is shown in the bosch app. The minimum value the bosch app reports is 500.

**Comment by safakaltun** [comment]
> > Yes, but it is based on the sniffs and what is shown in the bosch app. The minimum value the bosch app reports is 500.
> 
> Ok, so what I thought. 😊 Lastly, would you mind sharing your reasoning behind gathering all sensor readings only from the `manuSpecificBosch3` cluster, when [respective default clusters are available](https://github.com/Koenkk/zigbee-herdsman-converters/issues/7274#issuecomment-2027545775)? 👀

That was a technical requirement as far as I remember. The device reports those values to that cluster and did not use the respective clusters. You should be able to look at the sniffs if you want to dig deeper in the original issue. :)

**Comment by sarangnemo** [comment]
> I have a hunch that [unknown5](https://github.com/Koenkk/zigbee-herdsman/blob/c36cd6a214acd12f51e680773cd863e52efcaaa7/src/zcl/definition/cluster.ts#L5403) from the `manuSpecificBosch3` cluster is (air) pressure in hPa. 💨
> 
> Can someone please check on their Twinguard? A weather station or similar should show a comparable value.

Just a note here – I just implemented a corresponding ZHA quirk for the Twinguard. For me, the values for cluster 0x4009 seem to max out at 1000, where it stays most of the time. It occasionally dips as low as about 750, but I can't figure out what it corresponds with.
![Cluster 0x4009 history](https://github.com/user-attachments/assets/fbc1d82b-d523-4555-8a35-f0d231846f6c)
