### ISSUE TITLE
Using groups for Tuya devices?

### ISSUE THREAD

**Issue by mnaser** [Koenkk/zigbee-herdsman-converters#7284]
https://github.com/Koenkk/zigbee-herdsman-converters/blob/b405404c2d8db02d94feb3a114c9baf2bd2fcf4e/src/lib/tuya.ts#L1140

I'm running into this exception when using a Zigbee group that's based on Tuya, but I don't really find any reference as to why this is not working.

Is there a reason why it can't be done?  I'm happy to help with fixing the code for this.

Thanks!

**Comment by sjorge** [comment]
TuYa implements their data layer and are essentially using zigbee as a transport layer.

That's why it's not supported.

**Comment by avbdr** [comment]
@sjorge is there is a way to implement the 'tuya way' grouping?

**Comment by sjorge** [comment]
Their IoT Core docs do mention device groups, but I have no access to their wire level docs/sdk nor do I have any devices to look into this.

I assume it would technically be possible.

**Comment by avbdr** [comment]
I still would keep this issue opened, maybe one day somebody will find a solution?
