### ISSUE TITLE
Local External converter for covers _TZE200_g5xqosu7

### ISSUE THREAD

**Issue by Killi77** [Koenkk/zigbee-herdsman-converters#7308]
Dear @Koenkk , I set up an external converter for my curtains since natively are not supported in Z2M. I got it up and working yesterday. This morning I install a the new update for Zigbe2mqtt and the curtain motor came "unsupported" again. It seems that the update caused the issue. I can't confirm that but I didn't do any changes to my setup only the Z2M update that popped up in HA. Here is my converter. Can you please check where may be the problem, please?

'const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require('zigbee-herdsman-converters/lib/tuya');

const definition = {
    // Since a lot of TuYa devices use the same modelID, but use different datapoints
    // it's necessary to provide a fingerprint instead of a zigbeeModel
    fingerprint: [
        {
        // The model ID from: Device with modelID 'TS0601' is not supported
        // You may need to add \u0000 at the end of the name in some cases
        modelID: 'TS0601',
        // The manufacturer name from: Device with modelID 'TS0601' is not supported.
        manufacturerName: '_TZE200_g5xqosu7',
        },
    ],
    model: 'TS0601_new',
    vendor: 'TuYa',
    description: 'Cover motors',
    fromZigbee: [tuya.fz.datapoints],
    toZigbee: [tuya.tz.datapoints],
    configure: tuya.configureMagicPacket,
    options: [exposes.options.invert_cover()],
    exposes: [
        e.cover_position().setAccess('position', ea.STATE_SET),
        e.enum('reverse_direction', ea.STATE_SET, ['true', 'false'])
            .withDescription('Reverse the motor direction'),
    ],
    meta: {
        tuyaDatapoints: [
            [1, 'state', tuya.valueConverterBasic.lookup({'OPEN': tuya.enum(0), 'STOP': tuya.enum(1), 'CLOSE': tuya.enum(2)})],
            [2, 'position', tuya.valueConverter.coverPositionInverted],
            [3, 'position', tuya.valueConverter.coverPositionInverted],
            [5, 'reverse_direction', tuya.valueConverterBasic.lookup({'true': tuya.enum(0), 'false': tuya.enum(1)})],
        ],
    },
};
module.exports = definition;`

![Zigbee motor 01](https://github.com/Koenkk/zigbee-herdsman-converters/assets/117964111/f5339240-e7ef-441b-94a4-a4e2e7678bfb)

Thank you.

**Comment by true9741** [comment]
Hi Sorry @Koenkk, Problem solved removing the line

const extend = require('zigbee-herdsman-converters/lib/extend');

I imagine is not longer needed.

Sorry for disturb you.

**Comment by Killi77** [comment]
@true9741 :) You are treasure! You came to this discussion as a gift for me :) I'm not that skilled IT and don't know how you figured it out but it works for me as well! 
Thank you so much.
Issue closed. 
@Koenkk I'm still adjusting the converter for  _TZE200_g5xqosu7. Want to make sure it'll adapt all features. Once I'm done and convinced all is OK I'll let you post you the file so you can release it.
Thank you.

**Comment by Koenkk** [comment]
Good that you found the issue, please make a PR to add out-of-the-box support for these devices 😄

**Comment by Killi77** [comment]
@true9741 :) You are treasure! You came to this discussion as a gift for me :) I'm not that skilled IT and don't know how you figured it out but it works for me as well! 
Thank you so much.
Issue closed. 
@Koenkk I'm still adjusting the converter for  _TZE200_g5xqosu7. Want to make sure it'll adapt all features. Once I'm done and convinced all is OK I'll let you post you the file so you can release it.
Thank you.

**Comment by Killi77** [comment]
@Koenkk this is the final converter that woks with  _TZE200_g5xqosu7 curtain motor

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require('zigbee-herdsman-converters/lib/tuya');

const definition = {
    // Since a lot of TuYa devices use the same modelID, but use different datapoints
    // it's necessary to provide a fingerprint instead of a zigbeeModel
    fingerprint: [
        {
        // The model ID from: Device with modelID 'TS0601' is not supported
        // You may need to add \u0000 at the end of the name in some cases
        modelID: 'TS0601',
        // The manufacturer name from: Device with modelID 'TS0601' is not supported.
        manufacturerName: '_TZE200_g5xqosu7',
        },
    ],
    model: 'TS0601_new',
    vendor: 'TuYa',
    description: 'Cover motors',
    fromZigbee: [tuya.fz.datapoints],
    toZigbee: [tuya.tz.datapoints],
    configure: tuya.configureMagicPacket,
    options: [exposes.options.invert_cover()],
    exposes: [
        e.cover_position().setAccess('position', ea.STATE_SET),
        e.enum('reverse_direction', ea.STATE_SET, ['true', 'false'])
            .withDescription('Reverse the motor direction'),
        e.binary('motor_fault', ea.STATE, true, false),
    ],
    meta: {
        tuyaDatapoints: [
            [1, 'state', tuya.valueConverterBasic.lookup({'OPEN': tuya.enum(0), 'STOP': tuya.enum(1), 'CLOSE': tuya.enum(2)})],
            [2, 'position', tuya.valueConverter.coverPositionInverted],
            [3, 'position', tuya.valueConverter.coverPositionInverted],
            [5, 'reverse_direction', tuya.valueConverterBasic.lookup({'true': tuya.enum(0), 'false': tuya.enum(1)})],
            [12, 'motor_fault', tuya.valueConverter.trueFalse1],
        ],
    },
};
module.exports = definition;

**Comment by Koenkk** [comment]
Added, thanks!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
