### ISSUE TITLE
Add Support Sonoff Basic Zigbee

### ISSUE THREAD

**Issue by BrunoSRibeiro** [Koenkk/zigbee-herdsman-converters#732]
I added the support to Sonoff Basic Zigbee, but I can't subimit the code..

Follow the code to add.

In devices.js

    // ITEAD
    {
        zigbeeModel: ['BASICZBR3'],
        model: 'IM190611001',
        vendor: 'ITEAD',
        description: 'SONOFF ZigBee DIY Smart Switch',
        supports: 'on/off',
        fromZigbee: [fz.IM190611001_switch],
        toZigbee: [tz.on_off],
    },

In fromZigbee.js

    IM190611001_switch: {
        cid: 'genOnOff',
        type: ['devChange', 'attReport'],
        convert: (model, msg, publish, options) => {
            const status = msg.data.data.onOff;
            const payload = {};
            payload['state'] = status & 1 ? 'ON' : 'OFF';
            if (msg.endpoints[0].hasOwnProperty('linkquality')) {
                payload['linkquality'] = msg.endpoints[0].linkquality;
            }
            return payload;
        },
    },

In homeassistant.js

`'IM190611001': [configurations.switch, configurations.sensor_linkquality],`

**Comment by Koenkk** [comment]
Thanks but this device is already supported in the latest dev branch.

**Comment by BrunoSRibeiro** [comment]
Ok, but the current support don't get linkquality, in this code submitted for me, I add this information.
Thx

**Comment by Koenkk** [comment]
Link quality sensor is discovered for all devices, no need to add it explicitly in `homeassistant.js`.
