### ISSUE TITLE
Twinguard 8750001213 stopped working with 1.36.1 (after ~36h - at least i noticed it than)

### ISSUE THREAD

**Issue by daloki83** [Koenkk/zigbee-herdsman-converters#7326]
Refering to: https://github.com/Koenkk/zigbee-herdsman-converters/pull/7286

Maybe thats the wrong place, but with Z2M 1.36.1 and the Twinguard 8750001213 the Device stopped working and only shows old values for Temperature, Humidity, Illuminance (and maybe some others). Factory reset, deleted in Z2M, repairing etc didn't solve it. Tried multiple times. Than i rolled back to 1.36.0-1 and everything was fine again after a few minutes. I would say something is wrong with that code change. If i can support in any way, please let me know.

EDIT: Heartbeat and Self test also didnt work with the new version

**Comment by daloki83** [comment]
Thanks @burmistrzak for that fast reply. Unfortunately I have to wait bc the pull request failed so far and I'm on HomeAssistant. Will try it asap after release.

**Comment by TheMagnetar** [comment]
This can be closed. The Twin Guard values get regular updates in 1.37.1
