### ISSUE TITLE
"local_temperature_calibration" new value change not updated SPZB0001 thermostat

### ISSUE THREAD

**Issue by vansoest** [Koenkk/zigbee-herdsman-converters#734]
The **local_temperature_calibration** attribute output is not updated to the new value, is always 0.

I set the **local_temperature_calibration** by
```zigbee2mqtt/thermostat/living_room/set {"local_temperature_calibration":1.4}``` and yes it changes the local temperature from 19.77°C to 21.17°C, but the update topic will not set my new offset value in the attributes json. 

Received topic:
```
zigbee2mqtt/thermostat/living_room 
{
  "local_temperature": 21.17,
  "linkquality": 94,
  "current_heating_setpoint": 21.5,
  "eurotronic_system_mode": 1,
  "system_mode": "heat",
  "occupied_heating_setpoint": 21,
  "unoccupied_heating_setpoint": 16,
  "eurotronic_error_status": 0,
  "pi_heating_demand": 32,
  "battery": 100,
  "local_temperature_calibration": 0
}
```

Eurotronic Spirit SPZB0001 thermostat

**Comment by Koenkk** [comment]
@mhelff @allofmex does this work for you?

**Comment by sti0** [comment]
You receive the actual calibration by publishing this payload
```
{
  "local_temperature_calibration": ""
}
```
to topic
`zigbee2mqtt/[DEVICE_ID]/get`

**Comment by allofmex** [comment]
> @allofmex does this work for you?
Using ioBroker, not applicable there. Can't help here, sorry.

**Comment by sti0** [comment]
This is still an issue. Even mentioned in https://github.com/Koenkk/zigbee-herdsman-converters/issues/788

**Comment by sjorge** [comment]
No, I played with it a bit but it didn't seem to do anything (setting local_temperature_calibration)

**Comment by sti0** [comment]
After some minutes the local_temperature should be increased / decreased by the value. Could you try to get the local_temperature?

**Comment by sjorge** [comment]
I'm not seeing any change in local_temperatur or local_temperature_calibration afterwards, the later always returning 0

**Comment by sti0** [comment]
did you publish 

`{"local_temperature_calibration":""}`

to

`zigbee2mqtt/DEVICE/get`

?

**Comment by sti0** [comment]
did you publish 

`{"local_temperature_calibration":""}`

to

`zigbee2mqtt/DEVICE/get`

?

**Comment by sjorge** [comment]
- publish a `{"local_temperature_calibration":"1"}` to `zigbee2mqtt/DEVICE/set`
- waited a minute or so
- publish `{"local_temperature_calibration":""}` to `zigbee2mqtt/DEVICE/get`
- publish `{"local_temperature":""}` to `zigbee2mqtt/DEVICE/get`

**Comment by sti0** [comment]
That's strange. Could you try to set it without quotes?

`{"local_temperature_calibration":1}` 

I did this within a node red flow and I think the value is number type. Maybe you like to set a negative value for testing, too.

`{"local_temperature_calibration":-1.5}` 

Did you check the z2m log files for an error?

**Comment by sjorge** [comment]
```
mosquitto_pub -h localhost -p 1883 -t zigbee2mqtt/bedroom/radiator/set -m '{"local_temperature_calibration":-2}'
sleep 1
mosquitto_pub -h localhost -p 1883 -t zigbee2mqtt/bedroom/radiator/get -m '{"local_temperature_calibration": "", "local_temperature": ""}'
```

results:

```
zigbee2mqtt:info  2020-01-10 18:07:47: MQTT publish: topic 'zigbee2mqtt/bedroom/radiator', payload '{"local_temperature_calibration":-2,"linkquality":60,"occupied_heating_setpoint":24,"local_temperature":25,"unoccupied_heating_setpoint":16,"pi_heating_demand":0,"eurotronic_error_status":0,"current_heating_setpoint":24,"eurotronic_host_flags":{"mirror_display":false,"boost":false,"window_open":false,"child_protection":true},"system_mode":"auto","eurotronic_system_mode":129,"battery":90}'
zigbee2mqtt:info  2020-01-10 18:08:14: MQTT publish: topic 'zigbee2mqtt/bedroom/radiator', payload '{"local_temperature_calibration":-2,"linkquality":60,"occupied_heating_setpoint":24,"local_temperature":23,"unoccupied_heating_setpoint":16,"pi_heating_demand":0,"eurotronic_error_status":0,"current_heating_setpoint":24,"eurotronic_host_flags":{"mirror_display":false,"boost":false,"window_open":false,"child_protection":true},"system_mode":"auto","eurotronic_system_mode":129,"battery":90}'
zigbee2mqtt:info  2020-01-10 18:08:17: MQTT publish: topic 'zigbee2mqtt/bedroom/radiator', payload '{"local_temperature_calibration":-2,"linkquality":60,"occupied_heating_setpoint":24,"local_temperature":23,"unoccupied_heating_setpoint":16,"pi_heating_demand":0,"eurotronic_error_status":0,"current_heating_setpoint":24,"eurotronic_host_flags":{"mirror_display":false,"boost":false,"window_open":false,"child_protection":true},"system_mode":"auto","eurotronic_system_mode":129,"battery":90}'
zigbee2mqtt:info  2020-01-10 18:08:23: MQTT publish: topic 'zigbee2mqtt/bedroom/radiator', payload '{"local_temperature_calibration":-2,"linkquality":60,"occupied_heating_setpoint":24,"local_temperature":23,"unoccupied_heating_setpoint":16,"pi_heating_demand":31,"eurotronic_error_status":0,"current_heating_setpoint":24,"eurotronic_host_flags":{"mirror_display":false,"boost":false,"window_open":false,"child_protection":true},"system_mode":"auto","eurotronic_system_mode":129,"battery":90}'
```

So when using a number it does look like it got applied, I don't think the get was needed.

**Comment by sjorge** [comment]
```zigbee2mqtt:debug 2020-01-10 18:10:53: Received MQTT message on 'zigbee2mqtt/bedroom/radiator/get' with data '{"local_temperature_calibration": ""}'
zigbee2mqtt:debug 2020-01-10 18:10:53: Publishing get 'get' 'local_temperature_calibration' to 'bedroom/radiator'
zigbee2mqtt:debug 2020-01-10 18:10:58: Received Zigbee message from 'bedroom/radiator', type 'readResponse', cluster 'hvacThermostat', data '{"localTemperatureCalibration":-20}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-01-10 18:11:01: MQTT publish: topic 'zigbee2mqtt/bedroom/radiator', payload '{"local_temperature_calibration":-2,"linkquality":60,"occupied_heating_setpoint":24,"local_temperature":23,"unoccupied_heating_setpoint":16,"pi_heating_demand":31,"eurotronic_error_status":0,"current_heating_setpoint":24,"eurotronic_host_flags":{"mirror_display":false,"boost":false,"window_open":false,"child_protection":true},"system_mode":"auto","eurotronic_system_mode":129,"battery":90}'```

Was the response to a seperate get request and it looks like the value is also properly read as -2 (-20)

**Comment by sjorge** [comment]
I just double checked the PDF document, it is not listed in the reporting table as a reportable attribute :(

@koenkk based on some debugging, setting a new calibration calls the convertSet method but  convertGet is not automatically called afterwards.

Is this the expected behavior? If so, would it be appropriate to add a read immediately after the write to update the info? Or maybe just update the cached state if the write was successful?

**Comment by Koenkk** [comment]
This is expected behaviour.

>  Or maybe just update the cached state if the write was successful?

This can be done quite easily, just return a state after the `convertSet`, example: https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/converters/toZigbee.js#L740

**Comment by sjorge** [comment]
That works, will open a PR in a few minutes.

```
zigbee2mqtt:debug 2020-01-11 15:58:06: Received MQTT message on 'zigbee2mqtt/bedroom/radiator/set' with data '{"local_temperature_calibration": 2}'
zigbee2mqtt:debug 2020-01-11 15:58:06: Publishing 'set' 'local_temperature_calibration' to 'bedroom/radiator'
zigbee2mqtt:info  2020-01-11 15:58:11: MQTT publish: topic 'zigbee2mqtt/bedroom/radiator', payload '{"local_temperature_calibration":2,"linkquality":65,"occupied_heating_setpoint":20,"local_temperature":21.5,"unoccupied_heating_setpoint":16,"pi_heating_demand":0,"eurotronic_error_status":0,"current_heating_setpoint":20,"eurotronic_host_flags":{"mirror_display":false,"boost":false,"window_open":false,"child_protection":true},"system_mode":"auto","eurotronic_system_mode":129,"battery":90}'
zigbee2mqtt:debug 2020-01-11 15:58:19: Received MQTT message on 'zigbee2mqtt/bedroom/radiator/set' with data '{"local_temperature_calibration": 0}'
zigbee2mqtt:debug 2020-01-11 15:58:19: Publishing 'set' 'local_temperature_calibration' to 'bedroom/radiator'
zigbee2mqtt:info  2020-01-11 15:58:24: MQTT publish: topic 'zigbee2mqtt/bedroom/radiator', payload '{"local_temperature_calibration":0,"linkquality":65,"occupied_heating_setpoint":20,"local_temperature":21.5,"unoccupied_heating_setpoint":16,"pi_heating_demand":0,"eurotronic_error_status":0,"current_heating_setpoint":20,"eurotronic_host_flags":{"mirror_display":false,"boost":false,"window_open":false,"child_protection":true},"system_mode":"auto","eurotronic_system_mode":129,"battery":90}'
```

**Comment by sti0** [comment]
Great! Thank you @sjorge

**Comment by kisseler** [comment]
I have issues in setting the value for **local_temperature_calibration** on some SPZB0001 devices. I publish Number values via OpenHab. That works for some devices. Other process values with factor 10 and report error message (either "out of range" or "INVALID_VALUE" as seen in the logs below).

There is no firmware update available, anyway that models are the same (working and not working ones). Did anyone face the same problem? Maybe the devices are not working properly?

Thanks for your support!!! 

`Publish 'set' 'local_temperature_calibration' to 'DG_Giebelzimmer_Heizkoerperthermostat_L' failed: 'Error: Write 0x00158d00032f7ced/1 hvacThermostat({"localTemperatureCalibration":-36}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'INVALID_VALUE')'
Publish 'set' 'local_temperature_calibration' to 'DG_Giebelzimmer_Heizkoerperthermostat_R' failed: 'Error: Write 0x00158d00030c8695/1 hvacThermostat({"localTemperatureCalibration":28}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'INVALID_VALUE')'
Publish 'set' 'local_temperature_calibration' to 'DG_Giebelzimmer_Heizkoerperthermostat_L' failed: 'Error: Write 0x00158d00032f7ced/1 hvacThermostat({"localTemperatureCalibration":-38}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'INVALID_VALUE')'
Publish 'set' 'local_temperature_calibration' to 'DG_Giebelzimmer_Heizkoerperthermostat_R' failed: 'Error: Write 0x00158d00030c8695/1 hvacThermostat({"localTemperatureCalibration":28}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'INVALID_VALUE')'
Publish 'set' 'local_temperature_calibration' to 'DG_Giebelzimmer_Heizkoerperthermostat_R' failed: 'Error: Write 0x00158d00030c8695/1 hvacThermostat({"localTemperatureCalibration":28}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'INVALID_VALUE')'
Publish 'set' 'local_temperature_calibration' to 'DG_Giebelzimmer_Heizkoerperthermostat_L' failed: 'Error: Write 0x00158d00032f7ced/1 hvacThermostat({"localTemperatureCalibration":-39}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'INVALID_VALUE')'`
