### ISSUE TITLE
How to update the zigbee-herdsman-converters version in HAOS?

### ISSUE THREAD

**Issue by mkammes** [Koenkk/zigbee-herdsman-converters#7348]
...as there is no npm ability in HAOS.

Is there any way to update zigbee-herdsman within the zigbee2mqtt HAOS GUI?

Thanks!

**Comment by mrskycriper** [comment]
It's updates are linked to Zigbee2MQTT updates, there is no need to do anything extra.

**Comment by mkammes** [comment]
Thanks for the response, @mrskycriper .

Yes, I'm aware of that - I was just curious if the latest hotfix could be installed without waiting for the next Zigbee2MQTT update.

Thanks again!

**Comment by mrskycriper** [comment]
> Thanks for the response, @mrskycriper .
> 
> 
> 
> Yes, I'm aware of that - I was just curious if the latest hotfix could be installed without waiting for the next Zigbee2MQTT update.
> 
> 
> 
> Thanks again!

Unfortunately this is not possible within HAOS. But it's also not a good idea since it has its onw dependencies that are also regularly updated. I'd suggest using the Edge version of Zigbee2MQTT instead.
