### ISSUE TITLE
"No converter available for" when running in docker environment

### ISSUE THREAD

**Issue by kovaga** [Koenkk/zigbee-herdsman-converters#737]
"zigbee2mqtt version 1.6.0" running in Docker-compose.
all running normally, but after i # git clonezigbee-shepherd-converters and add the mapping 
+++
 volumes:
      - /home/zigbee2mqtt/data:/app/data
      - /home/zigbee2mqtt/data/zigbee-shepherd-converters:/app/node_modules/zigbee-shepherd-converters
+++
of the volume to docker-compose.yaml 
zigbee2mqtt is no longr recognises the devices that were previously recogniseable.

i.e. the following logs are geenrated "No converter available for 'MCCGQ11LM' with cid 'genBasic', type 'devChange' and data..."

I can see that the content of the shared zigbee-shepherd-converters directorsy is accessible within the container.
~ # docker container  exec 31a14beaf2a0 ls -a /app/node_modules/zigbee-shepherd-converters/                                                                             
.
..
.eslintignore
.eslintrc.json
.git
.github
.gitignore
LICENSE
README.md
azure-pipelines.yaml
converters
devices.js
index.js
npm-shrinkwrap.json
package.json
test

And I can check that this device is present in the device.js
~ # docker container  exec 31a14beaf2a0 cat /app/node_modules/zigbee-shepherd-converters/devices.js  | grep -i MCCGQ11LM                                      
        model: 'MCCGQ11LM',

But zigbee2mqtt does not seem to identify it. Any ideas?

**Comment by Koenkk** [comment]
Shoud already be fixed in latest dev branch. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
