### ISSUE TITLE
failed interview when using TI-Ztool script emulating  ZStack 3.x Switch-Example

### ISSUE THREAD

**Issue by am2600** [Koenkk/zigbee-herdsman-converters#738]
Hi,
i'm following my own post in the TI e2e forum (http://e2e.ti.com/support/wireless-connectivity/zigbee-and-thread/f/158/p/850882/3153813#pi320995=2), hoping to get help here. 
I've written a TI ZTool script for use with a ZStack ZNP (in my case a CC1352R1 Launchpad, but that doesnt matter i think) that should emulate the same behaviour like the ZStack Switch-Example from the latest cc13x2_26x2_sdk. 
The problem is: the ZNP controlled by my script is not interviewed successful, but the "real" switch (running completely in firmware on the CC1352) is interviewed correct.   
What i can see in the sniffer logs is that the coord is only sending out the first "Read Attribute" command (which is correctly responded by my node), but then stops interviewing my node, resulting in a timeout-failure. The real swich in contrast is interviewed by 3 Read-Attribute-Request/Response cycles.

Inside interviewInternal() within  /opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/device.js i see that following line is not executed successfully (i do not get beyond this line): 
const result = yield endpoint.read('genBasic', chunk);

Finally this results in a failed interview:
 zigbee-herdsman:controller:error Interview failed for '0x00124b001ca19401 with error 'Error: Timeout - 38738 - 8 - 10 - 1 after 10000ms'

What i would expect is that the coord is  issuing two more "Read Attribute" requests, which i can respond to in my ZTool-script (this is not implemented yet... but at least I should see the receipt of the incoming second request in my script). 

Can you help me fix this issue?  
Attached you find my ZTool script, the slightly expanded devices.js ( new zigbeeModel: ['TI_Switch']) and both LogFiles from the Sniffer as well as Console output from  DEBUG=zigbee-herdsman* npm start. Maybe someone could reproduce my problem by executing the attached ZTool script? 
Thanks a lot, regards Albert

[zigbee2mqtt_log_switchWithZNP-interview_failed.txt](https://github.com/Koenkk/zigbee-herdsman-converters/files/3820484/zigbee2mqtt_log_switchWithZNP-interview_failed.txt)

[ZNP-zed-Switch not interviewed successful.zip](https://github.com/Koenkk/zigbee-herdsman-converters/files/3820475/ZNP-zed-Switch.not.interviewed.successful.zip)

**Comment by Koenkk** [comment]
Please provide a sniff log of the interview procedure: https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html

**Comment by am2600** [comment]
right now i don't have a wireshark sniffer log, but a can provide a screenshot of the Ubiqua-Logs attached in the last post... i hope this helps a bit
![Ubiqua Protocol Analyzer_interview_TIswitch_OK](https://user-images.githubusercontent.com/57493405/68411716-418c0a00-018b-11ea-842a-121d747cfbb0.png)
![Ubiqua Protocol Analyzer_interview_ZNPswitch_NOT_OK](https://user-images.githubusercontent.com/57493405/68411721-451f9100-018b-11ea-8d2e-cb4ff743b2b7.png)

**Comment by am2600** [comment]
first screenshot is of the successful intervie, second from the failed ZNP interview...

**Comment by Koenkk** [comment]
The problem is that the transaction number of the response doesn't match the one of the request, as you can see in the log the read response has `"transactionSequenceNumber":0`. This number needs to match the one of the request.

**Comment by am2600** [comment]
Thanks for the advice, I really overlooked that! 
Can you tell me in which function the comparison of the transaction sequence number is performed? is there also the possibility for a debug output here? it probably would have saved me a lot of time ...    Thank you for the quick help!

**Comment by Koenkk** [comment]
Here: https://github.com/Koenkk/zigbee-herdsman/blob/master/src/adapter/z-stack/adapter/zStackAdapter.ts#L640

**Comment by am2600** [comment]
Thank you, that helped a lot!
