### ISSUE TITLE
Physical Button Does not Update State of Iluminize 511.201 Dimmer

### ISSUE THREAD

**Issue by packagedeliverer** [Koenkk/zigbee-herdsman-converters#743]
Hi,

The **Iluminize 511.201 dimmer** and **iCasa ICZB-IW11D dimmer** have two ways of turning off/on: one with is with zigbee, the other through a physical button. When controlled through zigbee, the state of the light is always up-to-date. When the physical button is used, the state is not updated.

When using the Alexa Echo Plus zigbee hub as controller, the state of the light gets updated when the physical button is used.

How could I help identifying the root cause of this?

Zigbee2MQTT version: 1.7.1
Original ticket as a reference: #688 

Kind regards,
Olivier

**Comment by Koenkk** [comment]
The reason is a missing configure. Can you update the device definition like this (https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L4835):

```js
{
    zigbeeModel: ['511.201'],
    model: '511.201',
    vendor: 'Iluminize',
    description: 'HV LED dimmer',
    extend: generic.light_onoff_brightness,
    configure: async (device, coordinatorEndpoint) => {
        const endpoint = device.getEndpoint(1);
        await bind(endpoint, coordinatorEndpoint, ['genOnOff']);
        await configureReporting.onOff(endpoint);
    },
},
```

How to get to `devices.js` in your installation: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

If this works, feel free to make a PR.

**Comment by packagedeliverer** [comment]
Hi @Koenkk ,

This works! 
I also tried adding config for the brightness level, but what I tried had some weird effects up to the point that I couldn't control the light anymore. Do you have a recommended configuration for brightness?

**Comment by Koenkk** [comment]
Should work with

```js
{
    zigbeeModel: ['511.201'],
    model: '511.201',
    vendor: 'Iluminize',
    description: 'HV LED dimmer',
    extend: generic.light_onoff_brightness,
    configure: async (device, coordinatorEndpoint) => {
        const endpoint = device.getEndpoint(1);
        await bind(endpoint, coordinatorEndpoint, ['genOnOff', 'genLevelCtrl']);
        await configureReporting.onOff(endpoint);
        await configureReporting.brightness(endpoint);
    },
},
```

**Comment by packagedeliverer** [comment]
Hi @Koenkk ,
With this configure, it shows quirky behavior where the brightness is constantly changing in the app. The bulb also seems less responsive through the physical button.
Not sure if this is a hardware issue of Iluminize.
So, only on/off seems to work fine.

**Comment by packagedeliverer** [comment]
Also, testing the brightness reporting twice required me to reflash my CC2531 twice. The reset button on the chip did not help.

**Comment by Koenkk** [comment]
Can you try

Should work with

```js

{
    zigbeeModel: ['511.201'],
    model: '511.201',
    vendor: 'Iluminize',
    description: 'HV LED dimmer',
    extend: generic.light_onoff_brightness,
    configure: async (device, coordinatorEndpoint) => {
        const endpoint = device.getEndpoint(1);
        await bind(endpoint, coordinatorEndpoint, ['genOnOff', 'genLevelCtrl']);
        await configureReporting.onOff(endpoint);
        const payload = [{
            attribute: 'currentLevel',
            minimumReportInterval: 1,
            maximumReportInterval: repInterval.HOUR,
            reportableChange: 1,
        }];
        await endpoint.configureReporting('genLevelCtrl', payload);
    },
},
```

**Comment by packagedeliverer** [comment]
Hi Koen,

Thanks for the reply, I had to put my tinkering on hold for a bit up till now.
With the last snippet, the physical button doesn't update the status anymore in the app, as it did for the one without config.
Do you have another alternative or a log I can view? I'll have a look at similar dimmer configs whether I can find anything that works

**Comment by Koenkk** [comment]
@packagedeliverer this is currently being fixed in https://github.com/Koenkk/zigbee-herdsman-converters/pull/951 (so please wait until that has been merged).

**Comment by packagedeliverer** [comment]
Hi Koen, 
Ok, thanks!
Though it seems I was wrong and the above did work. I didn't restart the container the right way. Thanks!

**Comment by rfkortekaas** [comment]
@Koenkk what is the function of `await configureReporting.brightness(endpoint);`. Without this line in [#951](https://github.com/Koenkk/zigbee-herdsman-converters/pull/951) the brightness is updated when it's adjusted with the hardware switch.

**Comment by packagedeliverer** [comment]
Further testing: the standard dimmer script no longer works with the last snippet.
https://www.home-assistant.io/cookbook/dim_and_brighten_lights/

**Comment by Koenkk** [comment]
Does it still work without after factory reset of the device?
