### ISSUE TITLE
WORKING CODE for SZ-DWS04 (Telstra Smart Home Window/Door Sensor)

### ISSUE THREAD

**Issue by stripeyhorse** [Koenkk/zigbee-herdsman-converters#744]
I have been successful in getting the Telstra Smart Home - Door and Window sensor working (SZ-DWS04)

` {
        zigbeeModel: ['SZ-DWS04'],
        model: 'SZ-DWS04',
        vendor: 'Sercomm',
        description: 'Magnetic door & window contact sensor',
        supports: 'contact, temperature',
        fromZigbee: [fz.iaszone_contact, fz.temperature, fz.battery_3V_2100],
        toZigbee: [],
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            await bind(endpoint, coordinatorEndpoint, ['msTemperatureMeasurement', 'genPowerCfg']);
            await configureReporting.temperature(endpoint);
            await configureReporting.batteryPercentageRemaining(endpoint);
        },
    }`

From the logs
`zigbee2mqtt:debug 2019-11-13T06:55:35: Received Zigbee message from 'Back Door', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"zonestatus":33,"extendedstatus":0}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2019-11-13T06:55:35: MQTT publish: topic 'zigbee2mqtt/Back Door', payload '{"contact":false,"tamper":false,"battery_low":false,"linkquality":7,"last_seen":1573628135674}'
zigbee2mqtt:debug 2019-11-13T06:55:36: Received Zigbee message from 'Back Door', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"zonestatus":32,"extendedstatus":0}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2019-11-13T06:55:36: MQTT publish: topic 'zigbee2mqtt/Back Door', payload '{"contact":true,"tamper":false,"battery_low":false,"linkquality":2,"last_seen":1573628136288}'`

Working at the moment
* Contact
* Tamper
* Battery_Low
* Link Quality

Not Working
* Temp
* Battery Voltage

I had these working under the home assistant ZHA out of the box but recently switched to Zigbee2Mqtt due to better support for smart things sensors.

**Comment by Koenkk** [comment]
I've added the code, the temperature and battery can take some time to report, if after a day it's not reported yet, let me know and share your `database.db`.

**Comment by stripeyhorse** [comment]
Temp and Battery are now reporting. Thank you.

**Comment by Koenkk** [comment]
great, thanks!
