### ISSUE TITLE
Bitron AV2010/32 functionality documented > actual

### ISSUE THREAD

**Issue by tt1pjm** [Koenkk/zigbee-herdsman-converters#748]
Base functionality all seems to be working correctly:

- local_temperature
- linkquality
- local_temperature_calibration
- occupied_heating_setpoint
- running_state
- battery
- voltage
- last_seen
- battery_alarm_state

The documented functionality (https://www.zigbee2mqtt.io/devices/AV2010_32.html) seems to show a lot more functions available but they are not all implemented.
I found a technical document (https://images-eu.ssl-images-amazon.com/images/I/91ZbuTU-duS.pdf) that documents those functions and others that should be possible.

**Comment by Chrischi-** [comment]
@tt1pjm 
i had focused on the implementation of the basics and functions i needed myself. 

feel free to add the other features.
