### ISSUE TITLE
Issue with 2018 SmartThings Water Leak Sensor (IM6001-WLP01) treated like 2015 version (F-WTR-UK-V2)

### ISSUE THREAD

**Issue by airdrummingfool** [Koenkk/zigbee-herdsman-converters#749]
I have found a weird circumstance when pairing my `IM6001-WLP01` [SmartThings water leak sensor](https://www.samsung.com/us/smart-home/smartthings/sensors/samsung-smartthings-water-leak-sensor-gp-u999sjvlcaa/). I have verified that the device's firmware is fully up-to-date (version `0x11` / `17`).

During pairing, it identifies itself as follows:
* Manufacturer: `Samjin`
* ModelID: `water`

When pairing is complete, Zigbee2MQTT treats it as a SmartThings `F-WTR-UK-V2`, _which is a [completely different device](https://www.samsung.com/uk/smartthings/sensors-plug-f-wtr-uk-v2/F-WTR-UK-V2/)_. When I short the sensors (to simulate a water leak event), zigbee2mqtt cannot interpret the resulting zigbee message, so the leak is not reported.

Interestingly, the `F-WTR-UK-V2` is referred to as the "2018 model" by z2m, but it is actually a 2014 or 2015 model according to this [SmartThings support article](https://support.smartthings.com/hc/en-us/articles/213497623-Which-SmartThings-Water-Leak-Sensor-do-I-have-). I believe the device I have (the `IM6001-WLP01`) is the 2018 model. The zigbee2mqtt documentation website has the correct pictures for both the [`IM6001-WLP01`](https://www.zigbee2mqtt.io/devices/IM6001-WLP01) and the [`F-WTR-UK-V2`](https://www.zigbee2mqtt.io/devices/F-WTR-UK-V2.html).

I believe that one of two things has happened:
1. There are multiple different devices with the modelId `water`. This would be bad!
2. zigbee-herdsman-converter's `devices.js` has an error in it.

I do not know what to do if 1 has happened, and I'm hoping that Samsung wouldn't allow that kind of oversight. Thus, going forward, I will assume 2.

Here's what I've been able to gather:
* The code that associates modelId `water` with `F-WTR-UK-V2` was added here: https://github.com/Koenkk/zigbee-herdsman-converters/pull/554. @Fabiancrg , if you still have this device, could you confirm both the model number printed on the device and the `modelId` as reported by the device (available in `database.db`)?
* I found a separate PR (https://github.com/Koenkk/zigbee-herdsman-converters/pull/556) that adds code to handle the `IM6001-WLP01`, but with the (ostensibly incorrect) modelId `IM6001-WLP01` instead of `water`. The issue that PR references shows that the modelId is `water`, but there is a commit in the PR that changed the modelId before it was merged. @johntdyer can you check your device's model number, and the modelId it reported to zigbee2mqtt? Do you remember why you changed the modelId before submitting the PR?
* The related issue, https://github.com/Koenkk/zigbee2mqtt/issues/663, was filed by @pfischbach. @pfischbach, is your SmartThings water leak sensor `IM6001-WLP01` working properly with the newest version of zigbee2mqtt?
* @skandragon, you have 3 of the same devices I do (according to https://github.com/Koenkk/zigbee-herdsman-converters/issues/713), can you verify that they paired as `F-WTR-UK-V2` and check and see whether or not the water leak reporting works?
* Other versions:
    * `STS-WTR-250` [identifies itself](https://community.hubitat.com/t/smartthings-water-leak-sensor/880/15) as modelId `moisturev4`. 
    * [`F-WTR-US-2`](https://www.samsung.com/us/smart-home/smartthings/sensors/samsung-smartthings-water-leak-sensor-f-wtr-us-2/): I can't find any references to its self-reported modelId, but this might be the US analogue for the `F-WTR-UK-V2`.

In order to make my device work, I would have to change the modelId of `water` for the existing devices.js entry for the `F-WTR-UK-V2` (and replace the modelId of `IM6001-WLP01` for the existing `IM6001-WLP01` entry). I don't know what the correct modelId for the `F-WTR-UK-V2` is, and I certainly don't want to break any existing device configurations.

**Comment by Koenkk** [comment]
Thanks for this throughout investigation, hopefully the people will respond so it can be solved.

**Comment by johntdyer** [comment]
@airdrummingfool ... Yea, I dont recall why I picked that modelID, I kinda pieced this together from other PR's and other models... It would not surprise me if I messed something up, Node is far from my strongest language

**Comment by johntdyer** [comment]
@airdrummingfool  - Its possible I Cargo cult'ed it from [here](https://github.com/Koenkk/zigbee2mqtt/issues/663#issuecomment-445303274)

**Comment by johntdyer** [comment]
@airdrummingfool  IMHO you should go ahead w/ your suggestion since you seem to have a firmer grasp of the situation then I do at this moment

**Comment by airdrummingfool** [comment]
@johntdyer thanks for your responses. I've been testing some modifications to support the sensor I have on hand correctly, and I'll be submitting a PR soon.

Would it be possible for you to check `database.db`  for the actual `modelId` reported by the sensor you have (or upload your entire `database.db`)? This will help me feel more confident that I won't be breaking compatibility for any existing sensors.

**Comment by achurak** [comment]
Hello,

I have exactly the same problem. I have several newer leak sensors (bought in US), but they are treated as F-WTR-UK-V2 for some reason (though it does say 2018 model). It also doesn't recognize the "contact" events:

zigbee2mqtt          | zigbee2mqtt:debug 2019-12-18 12:56:09: Received Zigbee message from '0x286d970001016dcd', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"zonestatus":33,"extendedstatus":0}' from endpoint 1 with groupID 0

zigbee2mqtt          | zigbee2mqtt:debug 2019-12-18 12:56:09: No converter available for 'F-WTR-UK-V2' with cluster 'ssIasZone' and type 'commandStatusChangeNotification' and data '{"zonestatus":33,"extendedstatus":0}'

Here's the database entry for one of these sensors:

{"id":2,"type":"EndDevice","ieeeAddr":"0x286d970001016dcd","nwkAddr":36939,"manufId":4673,"manufName":"Samjin","powerSource":"Battery","modelId":"water","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,32,1026,1280,2821],"outClusterList":[3,25],"clusters":{"genBasic":{"attributes":{"modelId":"water","manufacturerName":"Samjin","powerSource":3,"zclVersion":2,"appVersion":17,"hwVersion":0,"swBuildId":""}}},"binds":[{"cluster":1026,"type":"endpoint","deviceIeeeAddress":"0x00124b00194a20da","endpointID":1},{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b00194a20da","endpointID":1}]}},"appVersion":17,"hwVersion":0,"swBuildId":"","zclVersion":2,"interviewCompleted":false,"meta":{"configured":1},"lastSeen":1576691619459}

Let me know if you need any additional information.

**Comment by airdrummingfool** [comment]
@achurak thanks for the information. I had the same issue with contact events on my sensor, and have fixed it in my local branch. I'll be submitting a PR in the next couple days that includes the fix for both the contact sensor and the identification of the device.

**Comment by Koenkk** [comment]
Closing this as #833 has been merged, thank you very much @airdrummingfool for figuring this out.
