### ISSUE TITLE
NodOn SIN-4-RS-20 - Add value `8` to `windowCoveringMode`

### ISSUE THREAD

**Issue by AlbanDurrheimer** [Koenkk/zigbee-herdsman-converters#7545]
### Linked to Koenkk/zigbee2mqtt#22728  
  
Hello,  
Since I updated my NodOn SIN-4-RS-20 modules, `{"windowCoveringMode":8}` has appeared. However, this mode does not exist in the integration.  
According to the conversation in Koenkk/zigbee2mqtt#22728, this seems to be related to the control of the status LED.

**Comment by Koenkk** [comment]
Added in https://github.com/Koenkk/zigbee2mqtt/issues/22728
