### ISSUE TITLE
Incorrect attribute "occupancy" for iHORN LH03121 door contact sensor

### ISSUE THREAD

**Issue by EVExwc** [Koenkk/zigbee-herdsman-converters#7556]
Hi ,

I have identified an issue with the device definition for the iHORN LH03121 door contact sensor. The current attribute is incorrectly listed as "occupancy," but it should be "contact."

Here is the relevant section of the device definition:

```
zigbeeModel: ['LH03121'],
model: 'LH03121',
vendor: 'iHORN',
description: 'Door contact DNAKE SH-DM-S01',
extend: [iasZoneAlarm({zoneType: 'occupancy', zoneAttributes: ['alarm_1', 'battery_low', 'tamper']}), battery()],

``` 

Please update the zoneType from 'occupancy' to 'contact'.

Thank you for your attention to this matter!

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
