### ISSUE TITLE
Sonoff TRVZB attributes are not marked with device_category as configuration entities

### ISSUE THREAD

**Issue by blacknell** [Koenkk/zigbee-herdsman-converters#7564]
In the recent enhancements to support custom cluster and new attributes for the TRV ([closing and opening degree](https://github.com/Koenkk/zigbee-herdsman-converters/pull/7130)) these are not marked as `device_category` = `config`

I've searched everywhere (I think!) particularly in [sonoff.ts](https://github.com/Koenkk/zigbee-herdsman-converters/pull/7130/files) but I can't see where this is defined. If I knew how to change this I would submit a PR.  For example, `local_temperature_calibration` does come through as config but I can't see how.

`valveOpeningDegree` & `valveClosingDegree` should be config and not therefore displayed in dashboards.

**Comment by Koenkk** [comment]
This should do it:

```
numeric({
                entityCategory: 'config', // <-- add this line
                name: 'valve_opening_degree',
                cluster: 'customSonoffTrvzb',
                attribute: 'valveOpeningDegree',
                description: 'Valve open position (percentage) control. ' +
                    'If the opening degree is set to 100%, the valve is fully open when it is opened. ' +
                    'If the opening degree is set to 0%, the valve is fully closed when it is opened, ' +
                    'and the default value is 100%. ' +
                    'Note: only version v1.1.4 or higher is supported.',
                valueMin: 0.0,
                valueMax: 100.0,
                valueStep: 1.0,
                unit: '%',
            }),
```

**Comment by blacknell** [comment]
I'm happy to create a PR but:

1. I don't see this new line in any of the entities that do appear as config items (so that's unclear)
2. I don't have the set up to properly test this
-- the docs for adding a new device seem fairly involved but adding to an existing seems tricky
-- I don't have a debug/test instance only my prod instance

Is there a way I can create the PR and then test later the development stream, or someone else test it (shocking I know) or someone else take this on.

**Comment by blacknell** [comment]
I can see the new config payload in HA (devices -> mqtt info) but it doesn't seem to be reloading. I've tried restarting z2m (which already did due to addon upload) and restarting mosquitto.

Usually a new payload gets read by HA and the device refreshes?

**Comment by Koenkk** [comment]
I think HA doesn't update, try to force remove the device and re-pair it, this will re-init the entity at the HA side.
