### ISSUE TITLE
New device template for SODA Circle S8 window handle `_TZE200_j7sgd8po`

### ISSUE THREAD

**Issue by clumsy-stefan** [Koenkk/zigbee-herdsman-converters#7565]
Below a new template for the [SODA Circle S8 Professional](https://soda-gmbh.de/) window handle, probably this is of use for someone.

I have the agreement from the supplier/manufacturer (SODA GmbH) to publish it here and have it included in the z2m project!

Just save it as `TZE200_j7sgd8po.js` in your data directory and include it in your `configuration.yaml`.

If someone want's to include it in the standard distribution, feel free, unfortunately I don't succeed in making a successful PR (as I don't understand how to include the special functions in the standard library).

Regards

```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;
//const extend = require('zigbee-herdsman-converters/lib/extend');
const legacy = require('zigbee-herdsman-converters/lib/legacy');
const utils = require('zigbee-herdsman-converters/lib/utils');
const { Buffer } = require('node:buffer');
/*
const fzLocal = {
        TZE200_j7sgd8po: {
        cluster: 'manuSpecificTuya',
        type: ['commandDataResponse', 'commandDataReport'],
        convert: (model, msg, publish, options, meta) => {
                const splitToAttributes = (limit) => {
                const result = {};
                const len = limit.length;
                let i = 0;
                while (i < len) {
                        const key = limit.readUInt8(i);
                        result[key] = [limit.readUInt8(i + 1), limit.readUInt16BE(i + 2)];
                        i += 4;
                }
                return result;
                };
                const lookup = { 0: 'OFF', 1: 'ON' };

                for (const dpValue of msg.data.dpValues) {
                        const value = legacy.getDataValue(dpValue);
                        const dp = dpValue.dp;
//                      meta.logger.info(`DP: ${dp} -- VALUE = ${value}`);
                        switch (dp) {
                                case 16: return {
                                        state: value ? 'ON' : 'OFF',
                                        trip: 'clear',
                                }
                                case 11: return {
                                        prepay: value ? 'ON' : 'OFF',
                                }
                                case 12: {
//                                      meta.logger.info(`DP: ${dp} -- VALUE = ${value}`);
                                        return {
//                                              clear_energy: value ? 'reset' : 'clear',
                                                clear_energy: 'clear',
                                        }
                                }
                                case 102: {
                                        meta.logger.info(`DP: ${dp} -- VALUE = ${value}`);
                                }
                        }
                }
          },
    },
};
*/

const tzLocal = {
    TZE200_j7sgd8po: {
        key: ['vacation', 'keysound', 'handlesound', 'calibrate'],
        convertSet: async (entity, key, value, meta) => {
                const onOffLookup = { 'ON': 1, 'OFF': 0 };
//              meta.logger.info(`Key: ${key} -- VALUE = ${value}`);
                switch (key) {
                case 'vacation': {
                        var state = [];
                        state[0] = utils.getFromLookup(value, onOffLookup);
                        await tuya.sendDataPointRaw(entity, 107, state);
                        return { state: { vacation: value } };
                }
                case 'keysound': {
                        var state = [];
                        state[0] = utils.getFromLookup(value, onOffLookup);
                        await tuya.sendDataPointRaw(entity, 111, state);
                        return { state: { keysound: value } };
                }
                case 'handlesound': {
                        var state = [];
                        state[0] = utils.getFromLookup(value, onOffLookup);
                        await tuya.sendDataPointRaw(entity, 114, state);
                        return { state: { handlesound: value } };
                }
                case 'calibrate': {
                        var state = [];
//                      state[0] = utils.getFromLookup(value, onOffLookup);
//                      state[0] = value;
                        await tuya.sendDataPointRaw(entity, 120, state);
                        return;
                }
                default: // Unknown key
                        meta.logger.warn(`Unhandled key ${key}`);
                }
        },
    },
};

const definition = {
        fingerprint: tuya.fingerprint('TS0601', ['_TZE200_j7sgd8po']),
        model: 'TS0601',
        vendor: 'TuYa',
        description: 'SODA S8 premium window handle',
        extend: [],
        // fromZigbee: [tuya.fz.datapoints, fzLocal.TZE200_j7sgd8po],
        toZigbee: [tuya.tz.datapoints, tzLocal.TZE200_j7sgd8po],
        fromZigbee: [tuya.fz.datapoints],
        configure: tuya.configureMagicPacket,
        exposes: [
                  e.battery(), e.battery_low(),
                  e.binary('vacation', ea.STATE_SET, 'ON', 'OFF').withDescription('Vacation mode'),
                  e.enum('alarm', ea.STATE, ['ALARM', 'idle']).withDescription('Alarm'),
                  e.binary('alarm_switch', ea.STATE_SET, 'ON', 'OFF').withDescription('Alarm enable'),
                  e.binary('handlesound', ea.STATE_SET, 'ON', 'OFF').withDescription('Handle closed sound'),
                  e.enum('opening_mode', ea.STATE, ['closed', 'tilted']).withDescription('Window tilt'),
                  e.temperature(), e.humidity(),
                  e.binary('keysound', ea.STATE_SET, 'ON', 'OFF')
                                .withDescription('Key beep sound'),
                  e.enum('sensitivity', ea.STATE_SET, ['off', 'low', 'medium', 'high', 'max'])
                                .withDescription('Sensitivity of the alarm sensor'),
                  e.enum('position', ea.STATE, ['up', 'right', 'down', 'left']),
                  e.enum('button_left', ea.STATE, ['released', 'pressed']),
                  e.enum('button_right', ea.STATE, ['released', 'pressed']),
                  e.numeric('duration', ea.STATE_SET).withValueMin(0).withValueMax(300).withValueStep(1)
                                .withUnit('sec').withDescription('Duration of the alarm')
                                .withPreset('default', 180, 'Default value'),
                  e.numeric('update_frequency', ea.STATE_SET).withUnit('min').withDescription('Update frequency')
                                .withValueMin(0)
                                .withValueMax(700)
                                .withPreset('default', 20, 'Default value'),
                  e.enum('calibrate', ea.STATE_SET, ['calibrate']),
//                e.enum('calibrate', ea.STATE_SET, [0,1,2]),
                ],
        meta: {
                tuyaDatapoints: [
                [3, 'battery', tuya.valueConverter.raw],
                [8, 'temperature', tuya.valueConverter.divideBy10],
                [101, 'humidity', tuya.valueConverter.raw],
                [102, 'alarm', tuya.valueConverterBasic.lookup({ 'idle': tuya.enum(0), 'ALARM': tuya.enum(1) })],
                [103, 'opening_mode', tuya.valueConverterBasic.lookup({ 'closed': tuya.enum(0), 'tilted': tuya.enum(1) })],
                [104, 'position', tuya.valueConverterBasic.lookup({ 'left': tuya.enum(4), 'up': tuya.enum(1), 'down': tuya.enum(2), 'right': tuya.enum(3), })],
                [105, 'button_left', tuya.valueConverterBasic.lookup({ 'released': tuya.enum(0), 'pressed': tuya.enum(1)})],
                [106, 'button_right', tuya.valueConverterBasic.lookup({ 'released': tuya.enum(0), 'pressed': tuya.enum(1)})],
                [107, 'vacation', tuya.valueConverterBasic.lookup({ 'OFF': tuya.enum(0), 'ON': tuya.enum(1)})],
                [108, 'sensitivity', tuya.valueConverterBasic.lookup({ 'off': tuya.enum(0), 'low': tuya.enum(1), 'medium': tuya.enum(2), 'high': tuya.enum(3), 'max': tuya.enum(4), })],
                [109, 'alarm_switch', tuya.valueConverterBasic.lookup({ 'OFF': tuya.enum(0), 'ON': tuya.enum(1)})],
                [110, 'update_frequency', tuya.valueConverter.raw],
                [111, 'keysound', tuya.valueConverterBasic.lookup({ 'OFF': tuya.enum(0), 'ON': tuya.enum(1)})],
                [112, 'battery_low', tuya.valueConverterBasic.lookup({ 'ON': tuya.enum(0), 'OFF': tuya.enum(1)})],
                [113, 'duration', tuya.valueConverter.raw],
                [114, 'handlesound', tuya.valueConverterBasic.lookup({ 'OFF': tuya.enum(0), 'ON': tuya.enum(1)})],
//                [120, 'calibrate', tuya.valueConverterBasic.lookup({ '0': tuya.enum(0), '1': tuya.enum(1), '2': tuya.enum(2)})],
                [120, null, tuya.valueConverter.raw],

                ],
        },
};

module.exports = definition;
/*

{
  "3": "Battery Level",
  "8": "Temperature",
  "101": "Humidity",
  "102": "Alarm",
  "103": "Tilt Position",
  "104": "Handle Position",
  "105": "Button Left",
  "106": "Button Right",
  "107": "Vacation Mode",
  "108": "Alarm Sensitivity",
  "109": "Alarm Sound",
  "110": "Update Interval",
  "111": "Button Beep Sound",
  "112": "Low Battery Click",
  "113": "Alarm Duration",
  "114": "Handle Closed Click",
  "120": "Calibration"
}

*/
```

**Comment by clumsy-stefan** [comment]
I'm happy to help, what how/what should I check? How do I integrate this "ext.js"? It looks the same as my .js just without the tz/fz part... 
Should I jsut include this one instead of my TZE200_j7sgd8po.js?

I'm really sorry but I still don't understand how the whoel ts/nodejs stuff works...

**Comment by clumsy-stefan** [comment]
> In order to get this integrated, we have to get rid of `tzLocal.TZE200_j7sgd8po`. Could you check what works with the following [external definition](https://gist.github.com/Koenkk/1004c5d876488aea3345a41a8bef7ce6)?

Ok, just tested your definition. Basically everything seems to work except "calibration" where it throws a "no datapoint defined for calibrate".

And two minor syntax errors (some wrong "}" or so)...

does that help?

**Comment by Koenkk** [comment]
Great, yes it's a replacement for your own converter. Just to confirm, everything works now and I can integrate it? (with the code from: https://github.com/Koenkk/zigbee-herdsman-converters/issues/7565#issuecomment-2143878239)?

**Comment by clumsy-stefan** [comment]
As far as I could test, yes!

I removed the two commented lines as it was for testing, so from my point of view you could integrate it!

Thanks a lot for your help!!

**Comment by Koenkk** [comment]
Thanks, added!

Could you also submit a picture for the docs? This can be done by clicking [here](https://github.com/Koenkk/zigbee2mqtt.io/upload/master/public/images/devices). 

Make sure that:
- The filename is `MODEL.png` (update `model` accordingly) 
- The size is 512x512
- The background is transparent (use e.g. [Adobe remove background](https://new.express.adobe.com/tools/remove-background))

**Comment by clumsy-stefan** [comment]
I asked the manufacturer if he can provide an original image of the handle, if not I'll make one as requested. But it seems I won't be able to upload it here:
<img width="967" alt="image" src="https://github.com/Koenkk/zigbee-herdsman-converters/assets/32835100/325b962a-89b3-493b-95e5-adfa782e9dd1">

No write access...

thanks again for your help!

**Comment by clumsy-stefan** [comment]
I'll attach it here... Prob. you can use it...

![soda_doppel](https://github.com/Koenkk/zigbee-herdsman-converters/assets/32835100/51c67beb-3de0-4740-b9e8-18c923e4e194)

**Comment by Koenkk** [comment]
Does it work when clicking Add file -> Create new file [here](https://github.com/Koenkk/zigbee2mqtt.io/tree/master/public/images/devices)?

**Comment by clumsy-stefan** [comment]
Yeah it seems to work. But the model reportet is just "TS0601" which I think already exists, that's quite generic... SO I think the code need to be amended to show something more uniqe?

**Comment by Koenkk** [comment]
I see, will add the picture with the next release!

**Comment by clumsy-stefan** [comment]
Thanks, I saw it's integrated since yesterday.

Would it be possible to change the Vendor reference from TuYa to SODA GmBh.? Also, can I somehow extend the Description to make a reference to the homepage of the product, as it's a quite rare one and hard to find...

regards
STefan

**Comment by Koenkk** [comment]
- Changed the vendor to `SODA`
- You can add a link to the [docs](https://www.zigbee2mqtt.io/devices/SODA_S8.html) (scroll down click on "help to make...")

**Comment by clumsy-stefan** [comment]
Thx a lot!!

PR for Notes done...

**Comment by clumsy-stefan** [comment]
PS: not sure, but after changing vendor/model you probably need to rename the device image/png?

**Comment by Koenkk** [comment]
That will be done with the next z2m release

**Comment by theimo1221** [comment]
Hello team,
Im not sure if this device is working as intended with zigbee2mqtt or if the device I received is broken.
After pairing the device no values do update and the device is in like an interview loop:
1. Device get's interviewed
2. Device get's configured
3. Device leaves network
4. Step 1-3 are repeatetd

Personally I doubt it being an issue with my zigbee network as it is fairly big with devices from plenty of manufacturer:
<img width="228" alt="image" src="https://github.com/user-attachments/assets/bf628729-e4da-4311-a0f6-dd8144a2a0a2">


Thanks and best regards

Thiemo

**Comment by theimo1221** [comment]
Today a second device arrived having the same issue.
I talked to SODA directly and they said all devices are tested before being shipped thus highly reducing the propability of 2 broken devices.

@clumsy-stefan They asked me to contact you as well, as it seems you've got it working fine with zigbee2mqtt. Which coordinator are you using?
Mine is a sonoff running this version:
![image](https://github.com/user-attachments/assets/08a7493b-8779-4676-9654-666be33d5158)

After interview is done, rotating the handle doesn't result in any message to zigbee2mqtt

Thanks and best regards 

Thiemo

**Comment by clumsy-stefan** [comment]
Hi
I have 5 of these handles installed since a few months. All of them are working without issues. I had a issue in the beginning, that the device could not connect at all to the network after the first time, but they changed that in the firmware and since then they are working rock solid.

I run version:
<img width="662" alt="image" src="https://github.com/user-attachments/assets/fdb92365-b0d7-44c6-929e-acc29eb6ee44">

Does resetting and rebinding work?

Can you try what happens if you trigger the alarm (i.e. shaking the handle while it's closed) and see if it starts to send events?

Do you have the chance to test it with another coordinator?

I also have a fairly big network
<img width="700" alt="image" src="https://github.com/user-attachments/assets/18e0dfaa-1e2e-47cc-a521-dae9e1a0bbbf">

**Comment by theimo1221** [comment]
Thanks for the fast response, I did reset the devices but that didn't work either.
I'm not sure with which FW-Version these devices are flashed:
![image](https://github.com/user-attachments/assets/fb58189f-190e-4f37-b620-9aecfe608c31)

Do I have to get a Tuya Gateway to update them in order to connect them to zigbee2mqtt?

**Comment by clumsy-stefan** [comment]
You can't update them yourself. it was the tuya firmware that had a flaw which they captured in their firmware. I assume they ship all handles with the correct FW now. I have handles from three different (production) batches.

<img width="1004" alt="image" src="https://github.com/user-attachments/assets/928ecd07-ddbe-41c6-a3ca-78a943555613">

As writen, you could also try to force an alarm, this somehow triggered in the very first versions I had the start of sending messages, however, in the newer versions, this was not needed anymore..

**Comment by theimo1221** [comment]
Thanks for the hints, I got one working now:
![image](https://github.com/user-attachments/assets/966560a0-1198-4457-aad1-7495cc18ece4)

The other one still resists my charm...

**Comment by theimo1221** [comment]
@clumsy-stefan I did receive another one, but that one doesn't update values as well.... But as I talked to Soda directly this device definetly has the latest FW so that shouldn't be the issue...

As I have the same issue with another Tuya device that might be the problem: https://github.com/Koenkk/zigbee2mqtt/issues/24314

**Comment by clumsy-stefan** [comment]
That issue sounds like it could be related to your problem. However I've never faced that...

**Comment by stefanhintermayr** [comment]
Does anyone of you have the same problem that when you turn the door handle, it feels like both buttons are triggered? The manufacturer claims that this is a software problem, that the entities are being evaluated incorrectly. In the current case, when I turn the window handle, my shutters go up and down because they are placed on the buttons.

**Comment by clumsy-stefan** [comment]
Never had this issue until now on any of the 5 handles...

**Comment by stefanhintermayr** [comment]
That's really strange, I have the feeling that something isn't right. Every time I operate the door handle, it seems like all the values ​​change. Even the humidity sometimes jumps into double figures. Can someone please help me? How can I tell if the device is defective?https://github.com/user-attachments/assets/5c4462c3-be54-47d3-8068-7ad90029299a

**Comment by 57234rs59** [comment]
Hi this is SODA as we understand checking 2 different videos of this device Based on the videos, you can see that everything works exactly as it should and as we understood.

When the handle is turned, the current value of the sensors is determined at that moment. You can see that the button state "released," meaning not pressed, is sent. Later in the video, you can observe that only the buttons are pressed. At that point, "pressed" is sent when the button is pressed. Shortly after that, "released" is sent, meaning the button is released. Therefore, if you want to respond only to a button press, you must set the event to "pressed."

Why the button states are temporarily set to "NULL" in Home Assistant is a peculiarity of Zigbee2MQTT. The handle only sends "pressed" and "released." Zigbee2MQTT apparently sets the button state to "NULL" automatically after a short time. This implementation is fundamentally questionable because every time the handle is turned, there is a change in the button state, which can lead to the described issues for the customer. It always switches from "NULL" to "released" and back again.

As mentioned, these "NULL" values do not come from the handle; Zigbee2MQTT sets them automatically. This should be improved, and the automatic "NULL" should be removed.

The "jumping" of humidity values is also completely within the range of 1% to 5%. These values are also re-measured when the handle is turned, and due to the sensitivity of the sensors, corresponding fluctuations occur. If the handle is held in hand, the fluctuations can be even greater.

**Comment by 57234rs59** [comment]
I hope this helps

**Comment by clumsy-stefan** [comment]
As I don't use Home Assistant I can't really help here. It seems (to me) that Z2M handles it correctly, but probably HA timeouts the Values when there is no update in a certain time and changes it tu NULL... Which would indeed be a questionable behaviour, as especially for battery powered devices only "needed" changes should be sent, even if there is a longer time inbetween.

**Comment by stefanhintermayr** [comment]
So to me it looks like the door handle always sends all values ​​or overwrites Z2M with NULL, because just turning the door handle, which definitely doesn't change the value of the button, sometimes results in NULL.

**Comment by marazmarci** [comment]
FYI I have plans for ordering one and if nobody else fixes the Z2M code in the meantime, I can work on it a bit during my christmas free time 🙂

**Comment by adischerrer** [comment]
Hi all,
even though this thread is already closed, I'd like to contribute my findings in a Home Assistant w. Zigbee2MQTT setup.
Just bought one device for testing and integration worked well. But similar to @stefanhintermayr  I have some strange behavior:
There is a lot of (unnecessary) traffic while the door handle is "idle". I set the "update_frequency" to 1 (minute). Indeed, every 1 minute I see a message containing the button states "released" but there are a lot of messages in between containing "null" values for the buttons.
![mqtt-traffic-while-idle](https://github.com/user-attachments/assets/691637aa-9a83-44e5-8160-9ee9fa865bb0)

**Comment by marazmarci** [comment]
> FYI I have plans for ordering one and if nobody else fixes the Z2M code in the meantime, I can work on it a bit during my christmas free time 🙂

Oh no, I just wanted to order the window handle now, but it seems to be out of stock on [Amazon](https://www.amazon.de/s?me=AS4J66PXH3SHW&marketplaceID=A1PA6795UKMFR9) 😢 In this case I'm not sure I will be able to test and fix it this year.

@57234rs59, do you know when it will be available again?

**Comment by 57234rs59** [comment]
Good morning, we did not expect to have sold such a large quantity in such a short time. Many people ordered 1 or 2 pieces and then reordered up to 25 pieces by email. We are in re-production and this will take about 10-12 weeks - sorry about this.[ ](@marazmarci I have a reserved sample for you - please contact us at info@soda-gmbh.de. Best wishes, Samuel

**Comment by JoachimGru** [comment]
Good morning,

I've create the TZE200_j7sgd8po.js. But how  include it in the configuration.yaml. Already aks Google but find no solution. 

Joachim

**Comment by clumsy-stefan** [comment]
Why would you want to replace the existing integration? It works flawless with a pure z2m environment, just HA seems to have issues...

What did you change in your version?

As I wrote the original (currently in z2m integrated) template I'm happy to test your version in my environment.

**Comment by marazmarci** [comment]
FYI I created a separate issue about the problem when turning the handle is causing phantom button released events. I also proposed a few possible solutions. Please continue the discussion there.

https://github.com/Koenkk/zigbee-herdsman-converters/issues/9171
