### ISSUE TITLE
The compiled zcl folder is missing.

### ISSUE THREAD

**Issue by liubotongs** [Koenkk/zigbee-herdsman-converters#7578]
> zigbee-herdsman-converters@19.45.0 build
src/devices/sonoff.ts:2:32 - error TS2307:  Cannot find module 'zigbee-herdsman/dist/zcl/definition/buffaloZclDataType' or its corresponding type declarations.
I observed that... The /zigbee-herdsman-converters/node_modules/zigbee-herdsman/dist path is missing the zcl folder, resulting in the above compilation error.

**Comment by LaurentChardin** [comment]
`import {BuffaloZclDataType} from 'zigbee-herdsman/dist/zspec/zcl/definition/enums';` 
It should be fixed in the latest version: 19.49.0 as there was some refactoring some time ago from the ZCL folder.
