### ISSUE TITLE
Eurotronic Spirit local_temperature / pi_heating_demand

### ISSUE THREAD

**Issue by sti0** [Koenkk/zigbee-herdsman-converters#758]
I noticed on the weekend that the local_temperature of the Eurotronic Spirit is in many cases only published once an hour. This ends up in discussions with my wife of the real temperature in our kid's room. 

On the manual the local_temperature should reported every 1200s (20 min). It's recommended to report these value every 600s (look at page 17, described in English):
https://eurotronic.org/wp-content/uploads/2019/01/Spirit_ZigBee_BAL_web_DE_view_V9.pdf

How to set this to update every 10 minutes (this would be enough for me)?

Same goes for the pi_heating_demand. In some cases it updates the demand right after open or close but sometimes the thermostat closes fully and still had a pi_heating_demand for some minutes (or more).

I tried already to add reporting for temperature calibration (which is not reported automatically yet) and pi heating demand in `devices.js` but this don't work
```
await configureReporting.thermostatTemperatureCalibration(endpoint);
await configureReporting.thermostatPIHeatingDemand(endpoint);
```

@allofmex could you confirm this behaviour?

**Comment by allofmex** [comment]
@sti0: It works for me. Value is updated on change and more frequent than only hourly.

![grafik](https://user-images.githubusercontent.com/22577004/69027521-7db33c00-09cf-11ea-88bb-6a5e3f43453f.png)
blue: heating demand, red: local_temperature
(I am still on sherpherd/iobroker, not herdsman)

Sounds like your device did not receive configuration at all. What do your logs say about `Succesfully configured [device_id]....?`

When exactly does re-configure of a device happen in new herdsman implementation?
I remembered https://github.com/Koenkk/zigbee-herdsman-converters/pull/682#issuecomment-542646293 , does a device gets configured after it rejoined the network (e.g. battery changed)?

(calibration reporting is not needed, since this is only changed by coordinator, never by device itself)

**Comment by sti0** [comment]
I added a new template temperature sensor to track the local temperature and the pi heating demand today. Will come back here tonight to verify my conclusions.

If I remove the batteries, wait, and place them back there is no `Succesfully configured [device_id].... `message in the logs.  Maybe this only happen by first join?

**Comment by sjorge** [comment]
AFAIK configuration happens once after join, however herdman will retry if it hasn't succeeded yet.
If the TRV loses it's settings after the batteries are replaced that would probably be an issue.

**Comment by sti0** [comment]
This is what it looks like today:

Blue line is the temperature of a Xiaomi Aqara temperature sensor, red line is reported the Eurotronic Spirit temperature. 

As you could see the Xiaomi reports much more in detail and for example the last hours Eurotronic reports only once an hour (+-).
![image](https://user-images.githubusercontent.com/18382402/69087239-ef7a9c80-0a46-11ea-8962-6d56dba52edd.png)
![image](https://user-images.githubusercontent.com/18382402/69087418-ff927c00-0a46-11ea-9d80-f83372c091ca.png)
![image](https://user-images.githubusercontent.com/18382402/69087611-120cb580-0a47-11ea-9845-31d1309d0d11.png)

Another example is that there is no reporting between 10:45 and 14:47:
![image](https://user-images.githubusercontent.com/18382402/69088607-b989e800-0a47-11ea-90bd-3936397394d4.png)
![image](https://user-images.githubusercontent.com/18382402/69088698-cad2f480-0a47-11ea-9494-de097b4bfe32.png)

**Comment by allofmex** [comment]
Your thermostat reports in device default interval, it does not has the after-pairing-configuration-info anymore.

As @sjorge pointed out, the device is not configured anymore after initial pairing. 
@Koenkk: Is this correct? If yes, are you sure this is a good behavior?
In my opinion, a device should always be reconfigured when it rejoins (interview..) the network as it happens after cc25xx reset for example.
And there are for sure multiple devices that keep there pairing, but not the configuration on battery change.

**Comment by Koenkk** [comment]
@allofmex yes you are right, zigbee2mqtt will now always reconfigure on rejoin.

**Comment by sti0** [comment]
Thank you. I will test this in the next days and come back to you.

Would it make sense to print it out in the logs if a device is re-configured? Actually there is no log entry or should there be one?

**Comment by Koenkk** [comment]
There are log entries once finished you will see either `Succesfully/Failed to configure ..`

**Comment by sti0** [comment]
Than it doesn't work for me with latest dev. I removed the batteries of the Eurotronic and waited some minutes and placed them back in. No configure messages.

Even a Hue bulb and an Osram switch which are both disconnected from power send only a availibility message with payload "online" but no re-configure messages at all.

**Comment by Koenkk** [comment]
I guess the device doesn't rejoin on the battery repower, one thing you can do to make sure it is reconfigured you can force remove it and repair. https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttbridgeconfigremove

**Comment by sti0** [comment]
Ok did this. Climate entity is now sucessfully configured. 

I digged in the code of devices.js. On device configuration there is a min and max reporting time. Would it make sense to set the max time to 10 minutes instead of an hour? So the device should be forced to report after 10 min, am I right?

https://github.com/Koenkk/zigbee-herdsman-converters/blob/983ecac26fa896bf9f3462a5d902ded18b84efd4/devices.js#L161

**Comment by Koenkk** [comment]
Yes please try

**Comment by sti0** [comment]
OK I will try this.

But I have 2 questions:
1. After the change I have to remove and re-pair the device, so it can be re-configured with the new setting, right?

2. What means the attribute reportableChange?

**Comment by Koenkk** [comment]
1. Remove or increase the `configureKey` by 1.
2. It means that the device will not report unless the reportable change threshold is exceeded

**Comment by sti0** [comment]
This seems to be fixed with https://github.com/Koenkk/zigbee-herdsman-converters/pull/817 and https://github.com/Koenkk/zigbee-herdsman-converters/pull/850. Great! Thanks.
