### ISSUE TITLE
Sonoff TRVZB exposes battery_low but never updates it 

### ISSUE THREAD

**Issue by blacknell** [Koenkk/zigbee-herdsman-converters#7582]
The `battery` entity does display correctly as a percentage. But the `battery_low` binary warning entity is never updated and is thus sent on mqtt as `null`

I haven't been able to sniff the zigbee packets but it seems that either a) the value is not published by the device itself b) something is awry with the converter (I couldn't see anything obvious in the code).

a) seems unlikely as there is a battery warning indicator on the device itself so I'd be very surprised if they decided not to expose it.

I would say that the binary indicator (rather than reacting to the battery percentage level) is an important distinction since one would hope and expect that Sonoff are setting this at an optimal level.

I've noticed that when a device goes offline due to battery usage, it happens very quickly after 20%. So there is a steady battery level decline over time and then a much more sudden drop once it gets to 20%.

**Comment by blacknell** [comment]
@Koenkk do you agree this is worth pursuing? and that the binary_low indicator is important. i'm happy to try and do some more work on it but i've never yet tried a debug instance and/or capturing/logging data at the level

**Comment by Koenkk** [comment]
Doesn't seem to be supported (also checked with mine), removed it.

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
