### ISSUE TITLE
Lutron Connected Remote (LZL4BWHL01) On / Off Buttons

### ISSUE THREAD

**Issue by j4c3** [Koenkk/zigbee-herdsman-converters#766]
The remote has four buttons, and the up and down converters make sense, but the On and Off both report the same thing, "action":"toggle_hold".  The message from the device has a Level value, though.  254 for On, and 0 for Off. 

The fromZigbee definition it uses is fz.E1524_hold, which it also used by an Ikea remote.  The other (up / down) fromZigbee definitions are from the Gira 2430-100 remote. 

Would the preference be to create a new fromZigbee definition for this, and include the level values, do some calculation and send an On or Off?  fz.LZL4B_onoff?

Thanks!

**Comment by Koenkk** [comment]
Yes, please add new converters for this
