### ISSUE TITLE
support for lumi.remote.b686opcn01

### ISSUE THREAD

**Issue by arteck** [Koenkk/zigbee-herdsman-converters#771]
its a new dev Xiaomi Aqara Opple  button

debug info follows

**Comment by kirovilya** [comment]
PR is coming :)

**Comment by kirovilya** [comment]
need sniff traffic between switch and aqara-hub...

**Comment by kirovilya** [comment]
[opple_failed_pairing_z3_and_success.zip](https://github.com/Koenkk/zigbee-herdsman-converters/files/3902857/opple_failed_pairing_z3_and_success.zip)

**Comment by arteck** [comment]
nice works.. thx
