### ISSUE TITLE
Add support to Yale YMC420

### ISSUE THREAD

**Issue by lgp1985** [Koenkk/zigbee-herdsman-converters#7718]
Yale YMC420-W is a device that has same API as YRD420 TS and can be referred by the same code, tested locally with a device and worked as expected. please follow Pull Request associated

**Comment by patricktd** [comment]
There are 4 variations of the lock

Models:
YMC420
YMC 420
YMC 420 A
YMC 420 D

Locks 420, 420W and Papaiz SL200

All can use the same code
