### ISSUE TITLE
Support for Kwikset SMARTCODE_DEADBOLT_10

### ISSUE THREAD

**Issue by ShaunNeutron** [Koenkk/zigbee-herdsman-converters#7729]
Purchased a Kwikset 914 based on it being listed as supported on https://zigbee.blakadder.com/Kwikset_914.html. That page calls out Device IDs SMARTCODE_DEADBOLT_10_L | SMARTCODE_DEADBOLT_10_W3, but my device is showing up as SMARTCODE_DEADBOLT_10. I can get it to pair and expose the components, but as soon as pairing it complete, the device goes offline. Basically the same concern as https://github.com/Koenkk/zigbee2mqtt/issues/13298, but just a slightly different model.

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
