### ISSUE TITLE
need some configure ReportInterval explanation

### ISSUE THREAD

**Issue by Chrischi-** [Koenkk/zigbee-herdsman-converters#779]
@Koenkk 
i missed the herdsman-converter train and need some explanation to set the following values:
```
minimumReportInterval
maximumReportInterval
```
after your conversation from shepard to herdsman my Bitron Thermostat implementation reports now the temperature every 30 seconds instead of every 15 minutes.

is it like this? (await endpoint.configureReporting('thermostatTemperature'))

```
        supports: 'temperature, heating/cooling system control',
        fromZigbee: [
            fz.bitron_thermostat_att_report,
            fz.bitron_battery_att_report,
        ],
        toZigbee: [
            tz.thermostat_occupied_heating_setpoint, tz.thermostat_local_temperature_calibration,
            tz.thermostat_local_temperature, tz.thermostat_running_state,
            tz.thermostat_temperature_display_mode,
        ],
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            const binds = [
                'genBasic', 'genPowerCfg', 'genIdentify', 'genPollCtrl', 'hvacThermostat', 'hvacUserInterfaceCfg',
            ];
            await bind(endpoint, coordinatorEndpoint, binds);
            await endpoint.configureReporting('thermostatTemperature', [{
                minimumReportInterval: 900,
                maximumReportInterval: repInterval.HOUR,
            }], endpoint);
            // await configureReporting.thermostatTemperature(endpoint);
            await configureReporting.thermostatTemperatureCalibration(endpoint);
            await configureReporting.thermostatOccupiedHeatingSetpoint(endpoint);
            await configureReporting.thermostatRunningState(endpoint);
            await configureReporting.batteryAlarmState(endpoint);
            await configureReporting.batteryVoltage(endpoint);
        },
    },
```

**Comment by Chrischi-** [comment]
and i need a short explanation what `reportableChange` exactly does. 

Could you also point me to the herdsman documentation?

thanks

**Comment by Koenkk** [comment]
Hi @Chrischi- 

These configure options come from the Zigbee spec (it's not something from herdsman). It's documented well in chapter 2.5.7.1 of the zigbee spec: https://github.com/Koenkk/zigbee-herdsman/blob/master/docs/07-5123-06-zigbee-cluster-library-specification.pdf

![image](https://user-images.githubusercontent.com/2892853/69828986-71747d80-121e-11ea-91b4-b974a1af97d6.png)

**Comment by Chrischi-** [comment]
@Koenkk thanks 

Thanks for the clarification.

Is this right?
```
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            const binds = [
                'genBasic', 'genPowerCfg', 'genIdentify', 'genPollCtrl', 'hvacThermostat', 'hvacUserInterfaceCfg',
            ];
            await bind(endpoint, coordinatorEndpoint, binds);
            const payload = [{
                attribute: 'localTemp',
                minimumReportInterval: 900,
                maximumReportInterval: repInterval.HOUR,
                reportableChange: 1,
            }];
            await endpoint.configureReporting('hvacThermostat', payload);
            await configureReporting.thermostatTemperatureCalibration(endpoint);
            await configureReporting.thermostatOccupiedHeatingSetpoint(endpoint);
            await configureReporting.thermostatRunningState(endpoint);
            await configureReporting.batteryAlarmState(endpoint);
            await configureReporting.batteryVoltage(endpoint);
        },
    },
```

and is there a way to force a reconfiguration of a device?

**Comment by Koenkk** [comment]
Looks good, you can force a reconfigure by bumping the `configureKey` (set it to `2` in the above example).

**Comment by Chrischi-** [comment]
Thank you. This helps a lot.

Will do a PR soon...

What if i set the `configureKey` back to 1? Will it reconfigure and is there no way to do a reconfigure via mqtt?

**Comment by Koenkk** [comment]
This is possible now in the latest dev: https://github.com/Koenkk/zigbee2mqtt.io/blob/develop/docs/information/mqtt_topics_and_message_structure.md#zigbee2mqttbridgeconfigure

**Comment by Chrischi-** [comment]
I'am closing this now, thanks for clarification-

**Comment by Chrischi-** [comment]
@Koenkk 
could you take a moment to explain me how to interpret the/this error message(s)?

> Publish 'set' 'occupied_heating_setpoint' to 'bitron_living_room' failed: 'Error: Timeout - 5273 - 1 - 9 - 513 - 4 after 10000ms'

I get these every now and then without changing anything about Z2M. After that error I have to reset the device and pair it again.

**Comment by Koenkk** [comment]
It means that the device is not reachable, trying improving connection: https://www.zigbee2mqtt.io/how_tos/how_to_improve_network_range.html
