### ISSUE TITLE
Incorrect cluster in Ubisys dimmer specs

### ISSUE THREAD

**Issue by mberglun** [Koenkk/zigbee-herdsman-converters#7807]
Should this cluster not be 0xFC01?
https://github.com/Koenkk/zigbee-herdsman-converters/blob/bbe18586cd13b500a7d97a5d177744f4e236b50c/src/lib/ubisys.ts#L149
based on the documentation of D1: https://www.ubisys.de/wp-content/uploads/ubisys-d1-technical-reference.pdf, page 16, section 7.2.

I have these devices, not quite sure how to test whether it works, but happy to do it if someone can provide instructions.

**Comment by sjorge** [comment]
I might have messed this up with a refactor recently, let me double check.

**Comment by sjorge** [comment]
Yep looks like I did, https://github.com/Koenkk/zigbee-herdsman/pull/1034/files#diff-ec1a2d43181075d54fd33395e767a90a8d5e66cc2778f3944130d6aa537992b7L4313

I'll do a PR to fix.

**Comment by mberglun** [comment]
Thanks a lot for the quick fix!
