### ISSUE TITLE
Tuya EAYCB-Z-2P / _TZ3000_zrm3oxsh

### ISSUE THREAD

**Issue by rfcdejong** [Koenkk/zigbee-herdsman-converters#7838]
No matter what threshold I try to set in my Zigbee2MQTT. Running homeassistant and I don't have much knowledge yet. Cannot find any devices.yaml where others are talking about.

I added an EAYCB-Z-2P today and whatever i try to set using the interface i get the following errors.

z2m: Publish 'set' 'over_voltage_threshold' to 'MySwitch' failed: 'Error: Expected string or number, got undefined'
z2m: Publish 'set' 'over_current_threshold' to 'MySwitch' failed: 'Error: Expected string or number, got undefined'
z2m: Publish 'set' 'power_threshold' to 'MySwitch' failed: 'Error: Expected string or number, got undefined'
z2m: Publish 'set' 'temerature_threshold' to 'MySwitch' failed: 'Error: Expected string or number, got undefined'

**Comment by rodrigogbs** [comment]
Same here

**Comment by rodrigogbs** [comment]
@Perfect-Web do you mind helping us here?
