### ISSUE TITLE
Adding Support to OSRAM Classic E27

### ISSUE THREAD

**Issue by dims31** [Koenkk/zigbee-herdsman-converters#789]
OSRAM SMART + Classic E27 show up as LEDVANCE light. This lamp has the same property as AC03642. This work perfectly:
{
        zigbeeModel: ['A60 TW Z3'],
        model: 'AC10787',
        vendor: 'OSRAM',
        description: 'SMART+ CLASSIC E27 TW',
        extend: generic.light_onoff_brightness_colortemp,
    }

**Comment by Koenkk** [comment]
added, thanks!
