### ISSUE TITLE
TS0601_soil_2 (_TZE284_sgabhwa6) soil sensor's remaining battery % is equal to irs temperature in Fahrenheit

### ISSUE THREAD

**Issue by shift-del1** [Koenkk/zigbee-herdsman-converters#7933]
The remaining battery % is wrong, matching the temperature in Fahrenheit. In the official Tuya app it is displayed fine.

![image](https://github.com/user-attachments/assets/e2773bb0-1b63-43d2-9048-e7f71d5b341a)

In Z2M 1.39.1 (same after upgrading to 1.40.0, but the screenshots are earlier):

![image](https://github.com/user-attachments/assets/46492d84-421b-4518-9418-2acdda0cbf9e)

In official Tuya app:

![image](https://github.com/user-attachments/assets/604f06dc-00fb-4cd7-8433-3b299f56668c)

Adapter firmware version
0x26780700

Adapter
ConBee2/RaspBee2

Setup
Add-on on Home Assistant OS on virtualized x86-64 PC (Proxmox 8.2.4))

**Comment by gkyprios** [comment]
I am having issues with the battery datapoints for these devices as well. I have several units so it seems to be an issue with Z2M and not a pairing issue. I'm using 1.40.0 I dont get any battery readings now:

![image](https://github.com/user-attachments/assets/fa9a1b17-ea33-470c-9bbb-e87ed4afa3de)

Also, when sending configuration changes to the device (such as Schedule Periodic change), i see this error in the log:

![image](https://github.com/user-attachments/assets/636008c6-d075-4f1f-b071-c8b4e1096103)

**Comment by nprez83** [comment]
@shift-del1, see [#23729](https://github.com/Koenkk/zigbee2mqtt/issues/23729) for a troubleshooting idea related to this issue.
