### ISSUE TITLE
New device model name

### ISSUE THREAD

**Issue by iStitch07** [Koenkk/zigbee-herdsman-converters#797]
Hello, Aqara start sell new smart plug with code lumi.plug.maeu01
I think its similar to any other smart plug lumi.plug.mxxxx
![product-photo-_0000s_0000_rozet](https://user-images.githubusercontent.com/56363568/70092682-e2a59d80-162f-11ea-9710-e4c2155a7cd7.jpg)

can you add support for it?

**Comment by Koenkk** [comment]
Can you try with the following config (https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html)

```js
{
    zigbeeModel: ['lumi.plug.maeu01'],
    model: 'ZNCZ04LM',
    description: 'Mi power plug ZigBee EU',
    supports: 'on/off, power measurement',
    vendor: 'Xiaomi',
    fromZigbee: [
        fz.on_off, fz.xiaomi_power, fz.xiaomi_plug_state,
    ],
    toZigbee: [tz.on_off],
},
```

Also what is the model number of the device? (should be written on it).

**Comment by iStitch07** [comment]
Model, from the box: SP-EUC01

**Comment by iStitch07** [comment]
Yes, its worked


zigbee2mqtt:info  2019-12-05T18:09:39: Starting interview of '0x04cf8cdf3c765cf1',
zigbee2mqtt:info  2019-12-05T18:09:40: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0x04cf8cdf3c765cf1","model":"ZNCZ04LM","vendor":"Xiaomi","description":"Mi power plug ZigBee EU","supported":true}}',
zigbee2mqtt:info  2019-12-05T18:09:40: Successfully interviewed '0x04cf8cdf3c765cf1', device has successfully been paired,
zigbee2mqtt:info  2019-12-05T18:09:40: Device '0x04cf8cdf3c765cf1' is supported, identified as: Xiaomi Mi power plug ZigBee EU (ZNCZ04LM),
zigbee2mqtt:info  2019-12-05T18:09:39: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"0x04cf8cdf3c765cf1"}}',
zigbee2mqtt:info  2019-12-05T18:09:39: Device '0x04cf8cdf3c765cf1' joined,
zigbee2mqtt:info  2019-12-05T18:09:39: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":{"friendly_name":"0x04cf8cdf3c765cf1"}}'

**Comment by iStitch07** [comment]
But after adding to homeassistant.js 
'ZNCZ04LM': [cfg.switch, cfg.sensor_power],
I can switching it from HA, but have no data for power consummate and link quality

**Comment by Koenkk** [comment]
Are you sure it supports power measurements? When running zigbee2mqtt with debug log enabled and attaching a load to the plug, do you see any messages incoming?

To enable debug logging set in `configuration.yaml`:
```yaml
advanced:
  log_level: debug
```

**Comment by iStitch07** [comment]
hmm, now im not sure
`
zigbee2mqtt:debug 2019-12-07T20:38:29: Received MQTT message on 'zigbee2mqtt/Aqara Plug01/set' with data 'ON',
zigbee2mqtt:debug 2019-12-07T20:38:29: Publishing 'set' 'state' to 'Aqara Plug01',
zigbee2mqtt:info  2019-12-07T20:38:29: MQTT publish: topic 'zigbee2mqtt/Aqara Plug01', payload '{"state":"ON"}'
`
I thought about it based on what they wrote on the site

**Comment by iStitch07** [comment]
Yes. I connect it to aqara hub, attach load and none. this plug at least on this firmware not measure power consuming 
![IMG_0597](https://user-images.githubusercontent.com/56363568/70380818-17786400-1952-11ea-9f6d-927f791375d6.png)

I think this issue can be closed

**Comment by Koenkk** [comment]
Added, thanks!
