### ISSUE TITLE
Add support for SmartThings Outlet (UK)

### ISSUE THREAD

**Issue by jonnyrider** [Koenkk/zigbee-herdsman-converters#798]
Sorry, I don't know how to submit a pull request, but I have added the below to devices.js:

```
{
    zigbeeModel: ['3200-Sgb'],
    model: '3200-Sgb',
    vendor: 'SmartThings',
    description: 'Outlet - UK ',
    supports: 'on/off',
    fromZigbee: [fz.on_off, fz.ignore_onoff_report],
        toZigbee: [tz.on_off],
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            await bind(endpoint, coordinatorEndpoint, ['genOnOff']);
            await configureReporting.onOff(endpoint);
},
},
```

and:

 `  '3200-Sgb': [cfg.switch],    `  

to homeassistant.js to support for the SmartThing Outlet (UK).

All appears to be wokring correctly, reporting state (on/off) and link quality.

**Comment by Koenkk** [comment]
Is this the device? https://www.amazon.com/Centralite-3-ZigBee-Appliance-Module/dp/B01CKKVX30

**Comment by jonnyrider** [comment]
No, it is this:

https://www.amazon.co.uk/dp/B01LXXNGGD/ref=cm_sw_r_sms_apa_i_T5.5DbFEN7BYR

**Comment by Koenkk** [comment]
Thanks, added!
