### ISSUE TITLE
`_TZE204_pcdmj88b` is already supported.

### ISSUE THREAD

**Issue by lowerprofile** [Koenkk/zigbee-herdsman-converters#7990]
`_TZE204_pcdmj88b` is already supported.

_Originally posted by @Koenkk in https://github.com/Koenkk/zigbee-herdsman-converters/issues/6688#issuecomment-1852615707_

I have a couple of these and they are recognized, but as TS0601_thermostat_4 rather than BAB-1413_Pro, which they actually are

![Screenshot 2024-09-15 063218](https://user-images.githubusercontent.com/40688583/367561491-ce879ad4-fdac-401d-a11e-3f886d3c9dc4.png)

**Comment by lowerprofile** [comment]
It's not just cosmetic. As with most of these zigbee rad valves the major functions like setpoint, local temperature, calibration are the same but there are numerous differences in things like running state, preset selection, frost protection etc.
I thought I could fix it locally but after upgrading the SBC to debian 12 and reinstalling z2m I can't seem to find devices.js.

**Comment by Koenkk** [comment]
@tnako do these features work for you?

**Comment by lowerprofile** [comment]
I've got 2 of each of _TZE204_g2ki0ejr and _TZE204_pcdmj88b, the displays are in a different place but under the hood they're the same device. The first is correctly identified and uses the BAB-1413_Pro converter, which works fine.

**Comment by tnako** [comment]
Hi @Koenkk , datapoints of both looks similar. For first iteration of converter for _TZE204_pcdmj88b tried everything and somehow missed that BAB-1413_Pro. By picture they are different. But this is just picture and this is common for all tuya family :D

Regarding datapoints:
- _TZE204_g2ki0ejr have more alias names for 49
- my _TZE204_pcdmj88b works with "state, preset selection, frost protection" and this points 1:1 with _TZE204_g2ki0ejr. Not sure why this not working for @lowerprofile 
- mine have additional "eco" preset, googled "_TZE204_g2ki0ejr" and looks like it also have it. Somebody please confirm "eco" preset for BAB-1413_Pro
- point 47, mine only allow to calibrate [-3, 3] and 1 degree precision, with [-9, 9] and 0.1° from _TZE204_g2ki0ejr it stop responding for some time
- points 14,16,17 for open window feature not working for me. Need winter time to investigate (0.1° vs 0.5° precision issue?)

No objections to merge both into one but I don't have _TZE204_g2ki0ejr to investigate calibration steps (1° vs 0.1°). With `withLocalTemperatureCalibration(-9, 9, 1, ea.STATE_SET)` _TZE204_pcdmj88b works between [-3, 3] which is compromise but need confirmation that BAB-1413_Pro also support it...

**Comment by lowerprofile** [comment]
They do look different, but less so when you take the cover off.
You can see the alternative display position on _TZE204_g2ki0ejr

[image: valves.png]

**Comment by lowerprofile** [comment]
BAB-1413_Pro has the eco preset. Temp calibration only seems to work in multiples of 0.5°. You can send other values and it'll respond but doesn't seem to apply it. Unlike most Tuya rad valves it doesn't send local_temperature when you send calibration.

**Comment by lowerprofile** [comment]
Both of these valves seem to multiply the temperature calibration by 10. So I can send steps of 0.1 and get a 1 degree offset.
