### ISSUE TITLE
Signify vs. Philips in `vendor` field

### ISSUE THREAD

**Issue by mundschenk-at** [Koenkk/zigbee-herdsman-converters#8039]
Since `Philips` has really long been `Signify` now, shouldn't we update the vendor designation? (Feel free to close and point me to a better forum for this discussion, it just came up while working on the new converter for `LGT001`/`LGT002`).

**Comment by Koenkk** [comment]
Signify still uses the Philips brand, so I think it shouldn't be updated.

**Comment by mundschenk-at** [comment]
Thanks, now I understand the reasoning.
