### ISSUE TITLE
Update required for NOUS D4Z

### ISSUE THREAD

**Issue by DEFAYArnaud** [Koenkk/zigbee-herdsman-converters#8064]
Hello,

I have just bought the NOUS D4Z module (https://www.zigbee2mqtt.io/devices/D4Z.html).
But the problem is that it is not recognized and so it is “Not supported”.

<img width="1356" alt="Capture d’écran 2024-10-02 à 16 55 06" src="https://github.com/user-attachments/assets/181edee3-1255-49ce-a2b4-46e0026e745a">

How can I solve the problem please.

Thank you in advance

### Zigbee2MQTT version

1.40.2

**Comment by Koenkk** [comment]
@DEFAYArnaud could you make a PR by clicking [here](https://github.com/Koenkk/zigbee-herdsman-converters/edit/master/src/devices/tuya.ts)?
