### ISSUE TITLE
GLEDOPTO GL-SD-001P ZigBee2Mqtt  the field "manufacterer" is  valued unsupported

### ISSUE THREAD

**Issue by xdmore70** [Koenkk/zigbee-herdsman-converters#8097]
I integrated the gledopto Zigbee Triac AC Dimmer; All works fine but the frontend report Unsupported Manufactered

![light](https://github.com/user-attachments/assets/0a02f3fa-726d-43c0-b886-5e53e5e196f4)

I use last coordinator/frontend releases
![Screenshot 2024-10-08 150559](https://github.com/user-attachments/assets/67c9d04a-23e2-4dc7-b9db-cfe9de7d77ad)

const {light} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['GL-SD-001P'],
    model: 'GL-SD-001P',
    vendor: 'GLEDOPTO',
    description: 'Automatically generated definition',
    extend: [light()],
    meta: {},
};

module.exports = definition;

**Comment by Koenkk** [comment]
Could you make a PR by clicking [here](https://github.com/Koenkk/zigbee-herdsman-converters/edit/master/src/devices/gledopto.ts)?

**Comment by xdmore70** [comment]
Thanks Koenkk, i'm not very familiar with this worl; in any case I tried to make the change. I hope that Pull Request procedure is correct

**Comment by Koenkk** [comment]
I added it.

Could you also submit a picture for the docs? This can be done by:
1. Create a fork by clicking [here](https://github.com/Koenkk/zigbee2mqtt.io/fork)
2. Go to the `public/images/devices` directory, *Add file* -> *Upload files*
3. Upload the files and press *Commit changes*
4. Press *Contribute* -> *Open pull request* -> update title/description -> *Create pull request*

Make sure that:
- The filename is `GL-SD-001P.png`
- The size is 512x512
- The background is transparent (use e.g. [Adobe remove background](https://new.express.adobe.com/tools/remove-background))

**Comment by xdmore70** [comment]
i just done it; It would be all ok

Thank so much Koenkk
