### ISSUE TITLE
Please add support for TOB9Z-M with Manufacturer id _TZ3000_6l1pjfqe

### ISSUE THREAD

**Issue by ros-kamach** [Koenkk/zigbee-herdsman-converters#8126]
I bought a few `TOB9Z-M` devices, and almost all switches were connected and worked fine as expected (id:  `_TZ3000_303avxxt`). However, I received two devices that had a different identifier: `_TZ3000_6l1pjfqe`. These were initially detected by Zigbee2MQTT as `TS011F_plug_3`.
As a workaround to resolve this issue, I searched the Zigbee2MQTT code base for `_TZ3000_303avxxt` and adjusted the container start command to append `_TZ3000_6l1pjfqe`. Here's the container start command:
```
    command:
      - /bin/sh
      - -c
      - >
        sed -i "s/tuya\.whitelabel('Tomzn', 'TOB9Z-M', 'Smart circuit breaker', \['_TZ3000_303avxxt'\])/tuya.whitelabel('Tomzn', 'TOB9Z-M', 'Smart circuit breaker', ['_TZ3000_303avxxt', '_TZ3000_6l1pjfqe'])/" ./node_modules/zigbee-herdsman-converters/devices/tuya.js &&
        sed -i "s/if (device?\.manufacturerName !== '_TZ3000_303avxxt' && device?\.manufacturerName !== '_TZ3000_zjchz7pd') {/if (device?\.manufacturerName !== '_TZ3000_303avxxt' \&\& device?\.manufacturerName !== '_TZ3000_6l1pjfqe' \&\& device?\.manufacturerName !== '_TZ3000_zjchz7pd') {/" ./node_modules/zigbee-herdsman-converters/devices/tuya.js &&
        sed -i "s/ '_TZ3000_303avxxt',/ '_TZ3000_303avxxt', '_TZ3000_6l1pjfqe',/" ./node_modules/zigbee-herdsman-converters/devices/tuya.js &&
        /sbin/tini -- node index.js
```
After applying these changes to the Zigbee2MQTT configuration, the devices with the id `_TZ3000_6l1pjfqe` are now correctly recognized and operate as expected (see screenshots below).
<img width="994" alt="Screenshot 2024-10-13 at 21 28 18" src="https://github.com/user-attachments/assets/a198d1aa-b8f3-4ded-9ff8-310c46305211">
<img width="1293" alt="Screenshot 2024-10-13 at 21 30 13" src="https://github.com/user-attachments/assets/b0213378-d882-4518-836a-0b4020919f6e">
<img width="996" alt="Screenshot 2024-10-13 at 21 31 09" src="https://github.com/user-attachments/assets/fe3aea11-35d3-49e9-b262-ba8f5d875ccc">
<img width="1338" alt="Screenshot 2024-10-13 at 21 32 01" src="https://github.com/user-attachments/assets/66483e77-a9bf-4ba3-b79f-fe65ebe0c031">

Could you please add these changes into your code in the next release? It only requires adding `_TZ3000_6l1pjfqe` in three places:
- https://github.com/Koenkk/zigbee-herdsman-converters/blob/b53aef5c1d93f33f68835ea96d2902c5a93e8979/src/devices/tuya.ts#L8595
- https://github.com/Koenkk/zigbee-herdsman-converters/blob/b53aef5c1d93f33f68835ea96d2902c5a93e8979/src/devices/tuya.ts#L8614
- https://github.com/Koenkk/zigbee-herdsman-converters/blob/b53aef5c1d93f33f68835ea96d2902c5a93e8979/src/devices/tuya.ts#L8682

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by ros-kamach** [comment]
Thanks!!!
