### ISSUE TITLE
Add support for GLEDOPTO GL-S-008Z

### ISSUE THREAD

**Issue by rikthefrog** [Koenkk/zigbee-herdsman-converters#813]
Light has RGB color and dual white
{
        zigbeeModel: ['GL-S-008Z'],
        model: 'GL-S-008Z',
        vendor: 'Gledopto',
        description: 'Soposh Dual White And Color ',
        extend: gledopto.light,
        supports: 'on/off, brightness, color temperature, color',
    },

**Comment by Koenkk** [comment]
Added, thanks!
