### ISSUE TITLE
Refactoring suggestion: break devices.js into one file per manufacturer

### ISSUE THREAD

**Issue by carldebilly** [Koenkk/zigbee-herdsman-converters#816]
I would be nice to separate `devices.js` into multiple files, one per manufacturer.

The file is starting to be very big and the order of the converters in it is not obvious.

**Comment by Koenkk** [comment]
This has already been discussed a few times, and I'm still not convinced that this makes adding support for new devices easier. E.g. for hassio `devices.js` is overwritten by a manual one, when it is split up this cannot be done so easy.
