### ISSUE TITLE
In the new version, spotmau Not supported，Hope to join, thank you

### ISSUE THREAD

**Issue by wangling75** [Koenkk/zigbee-herdsman-converters#8186]
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

module.exports = [
{
    zigbeeModel: ['1719SP-PS1-02'],
    model: 'bdmswitch',
    vendor: 'spotmau',
    description: 'Spotmau switch',
    extend: extend.switch(),
    fromZigbee: [fz.on_off],
    toZigbee: [tz.on_off],
    meta: {multiEndpoint: true},
    endpoint: (device) => {
        return {'left': 16};
    },
    exposes: [e.switch().withEndpoint('left')],
    configure: async (device, coordinatorEndpoint, logger) => {
        await reporting.bind(device.getEndpoint(16), coordinatorEndpoint, ['genOnOff']);
        await reporting.onOff(device.getEndpoint(16));
    },
},
{
    zigbeeModel: ['1719SP-PS2-02'],
    model: 'bdmswitch',
    vendor: 'spotmau',
    description: 'Spotmau switch',
    extend: extend.switch(),
    fromZigbee: [fz.on_off],
    toZigbee: [tz.on_off],
    meta: {multiEndpoint: true},
    endpoint: (device) => {
        return {'left': 16, 'center': 17};
    },
    exposes: [e.switch().withEndpoint('left'), e.switch().withEndpoint('center')],
    configure: async (device, coordinatorEndpoint, logger) => {
        await reporting.bind(device.getEndpoint(16), coordinatorEndpoint, ['genOnOff']);
        await reporting.bind(device.getEndpoint(17), coordinatorEndpoint, ['genOnOff']);
        await reporting.onOff(device.getEndpoint(16));
        await reporting.onOff(device.getEndpoint(17));
    },
},
{
    zigbeeModel: ['1719SP-PS3-02'],
    model: 'bdmswitch',
    vendor: 'spotmau',
    description: 'Spotmau switch',
    extend: extend.switch(),
    fromZigbee: [fz.on_off],
    toZigbee: [tz.on_off],
    meta: {multiEndpoint: true},
    endpoint: (device) => {
        return {'left': 16, 'center': 17, 'right': 18};
    },
    exposes: [e.switch().withEndpoint('left'), e.switch().withEndpoint('center'), e.switch().withEndpoint('right')],
    configure: async (device, coordinatorEndpoint, logger) => {
        await reporting.bind(device.getEndpoint(16), coordinatorEndpoint, ['genOnOff']);
        await reporting.bind(device.getEndpoint(17), coordinatorEndpoint, ['genOnOff']);
        await reporting.bind(device.getEndpoint(18), coordinatorEndpoint, ['genOnOff']);
        await reporting.onOff(device.getEndpoint(16));
        await reporting.onOff(device.getEndpoint(17));
        await reporting.onOff(device.getEndpoint(18));
    },
},

{
    zigbeeModel: ['1719SP-WS-02'],
    model: 'bdmsocket',
    vendor: 'spotmau',
    description: 'Spotmau Socket',
    extend: extend.switch(),
    fromZigbee: [fz.on_off],
    toZigbee: [tz.on_off],
    meta: {multiEndpoint: true},
    endpoint: (device) => {
        return {'left': 16};
    },
    exposes: [e.switch().withEndpoint('left')],
    configure: async (device, coordinatorEndpoint, logger) => {
        await reporting.bind(device.getEndpoint(16), coordinatorEndpoint, ['genOnOff']);
        await reporting.onOff(device.getEndpoint(16));
    },
},
];

**Comment by Koenkk** [comment]
could you make a PR by clicking here: https://github.com/Koenkk/zigbee-herdsman-converters/edit/master/src/devices/spotmau.ts?

**Comment by wangling75** [comment]
>你能点击这里做PR吗：https://github.com/Koenkk/zigbee-herdsman-converters/edit/master/src/devices/spotmau.ts？


> could you make a PR by clicking here: https://github.com/Koenkk/zigbee-herdsman-converters/edit/master/src/devices/spotmau.ts?

Can you help me submit it? I failed the verification after submitting. thank you


const {deviceEndpoints, onOff} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = [
    {
        zigbeeModel: ['1719SP-PS1-02'],
        model: 'SP-PS1-02',
        vendor: 'Spotmau',
        description: 'Smart wall switch - 1 gang',
        extend: [deviceEndpoints({endpoints: {left: 16}}), onOff({endpointNames: ['left']})],
    },
    {
        zigbeeModel: ['1719SP-PS2-02'],
        model: 'SP-PS2-02',
        vendor: 'Spotmau',
        description: 'Smart wall switch - 2 gang',
        extend: [deviceEndpoints({endpoints: {left: 16, center: 17}}), onOff({endpointNames: ['left', 'center']})],
    },
    {
    zigbeeModel: ['1719SP-PS3-02'],
    model: 'SP-PS3-02',
    vendor: 'Spotmau',
    description: 'Smart wall switch - 3 gang',
    extend: [deviceEndpoints({endpoints: {left: 16, center: 17, right: 18}}), onOff({endpointNames: ['left', 'center', 'right']})],
    },
    {
        zigbeeModel: ['1719SP-WS-02'],
        model: 'SP-WS-02',
        vendor: 'Spotmau',
        description: 'Smart wall switch - Socket',
        extend: [deviceEndpoints({endpoints: {left: 16}}), onOff({endpointNames: ['left']})],
    },
];

module.exports = definition;

**Comment by Koenkk** [comment]
feat(add): SP-PS1-02, SP-PS2-02, SP-PS3-02, SP-WS-02
