### ISSUE TITLE
Support M-Elec Stitchy devices

### ISSUE THREAD

**Issue by willu** [Koenkk/zigbee-herdsman-converters#819]
I've been looking for either light switches or in-wall relays for controlling 240v power in Australia.  I recently came across M-Elec's stitchy product (https://melec.com.au/stitchy/).  They sent me a sample dimmer.  It seems to work well.  This is to track the pull request to add its configuration.

**Comment by willu** [comment]
I guess I don't really need this separate from the pull request.  (I don't use github much...)

**Comment by ryanbeaton** [comment]
Thanks for finding these

**Comment by ryanbeaton** [comment]
@willu where did you get and how much? No info online!

**Comment by willu** [comment]
I used the 'contact' link on the web site.  They were very responsive.

**Comment by willu** [comment]
What do I need to do to get the device listed here: https://www.zigbee2mqtt.io/information/supported_devices.html ?

That page has things like pictures, which aren't discussed here: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html .

**Comment by Koenkk** [comment]
@willu that is done automatically in the next zigbee2mqtt release.
