### ISSUE TITLE
Help with adding device parameter

### ISSUE THREAD

**Issue by tomaae** [Koenkk/zigbee-herdsman-converters#827]
Hey,
Could someone help with adding a device parameter?
I have tried based on documentation and what I seen in code:

/app/node_modules/zigbee-herdsman/dist/zcl/definition/cluster.js
>    manuSpecificXiaomi: {
        ID: 64704,
        attributes: {},
        commands: {},
        commandsResponse: {},
    },

/app/node_modules/zigbee-herdsman-converters/converters/toZigbee.js
>    ZNCZ04LM_poweroff_memory: {
        key: ['poweroff_memory'],
        convertSet: async (entity, key, value, meta) => {
            await entity.write('manuSpecificXiaomi', {0x0201: {value: value ? 0x01 : 0x00, type: 0x10}}, options.xiaomi);
        },
    },

/app/node_modules/zigbee-herdsman-converters/devices.js
>    {
        zigbeeModel: ['lumi.plug.mmeu01'],
        model: 'ZNCZ04LM',
        description: 'Mi power plug ZigBee EU',
        supports: 'on/off, power measurement',
        vendor: 'Xiaomi',
        fromZigbee: [
            fz.on_off, fz.xiaomi_power, fz.xiaomi_plug_state,
        ],
        toZigbee: [tz.on_off, tz.ZNCZ04LM_poweroff_memory],
    },

zigbee2mqtt/devices.js
>poweroff_memory: true

![image](https://user-images.githubusercontent.com/23486452/71147528-5d260e00-2229-11ea-8c5a-48354b37ef6d.png)

**Comment by Koenkk** [comment]
You can find an example here: https://github.com/Koenkk/zigbee-herdsman-converters/commit/c2b4b167e6951b573423e366d62c4193b5b98b5a

Instead of `await entity.write('genBasic', {0x0401: {value: payload, type: 0x42}}, options.xiaomi);` use

```js
await entity.write('manuSpecificXiaomi', {0x0201: {value: true, type: 0x10}}, options.xiaomi);
```

**Comment by tomaae** [comment]
Looks the same as what I used, except hardcoded true. I tried that as well just now, but no change. Sniffers wont even detect any traffic with that cluster other than reports originating from device itself.

**Comment by tomaae** [comment]
I spent whole day with it, but cant figure out what I'm doing wrong or find any alternative.

Also I know its also possible to poll this parameter so it could be included in UI, but could not get polling to work. Thats not an important part tho.

**Comment by Koenkk** [comment]
Are you sure that your code is executed? Can you add `console.log('helloworld')` for example?

**Comment by tomaae** [comment]
No, nothing in z2m log while z2m log level was set to debug. 
But it does not log anything with ones which work (I think, cant be 100% sure), like DJT11LM_vibration_sensitivity.
I also tried meta.logger.info, but got nothing from DJT11LM_vibration_sensitivity as well.

**Comment by Koenkk** [comment]
It will not be logged to the log but to stdout, did you check that? If not it means that your code is not executed so something is not setup correctly.

**Comment by tomaae** [comment]
I have z2m as hassio container, so not sure if I can access stdout. it is bit inconvenient for development.
is there anything else to setup? I have been researching it some more, but cant figure out anything new. I'm not even sure if it reads those custom parameters from devices.yaml and triggers toZigbee based on that. It would make sense if something is missing, but other devices dont have anything extra.

**Comment by Koenkk** [comment]
Setting up a dev environment would be much easier indeed (hassio is a pain to develop on). I recommend the bare metal installation https://www.zigbee2mqtt.io/getting_started/running_zigbee2mqtt.html

**Comment by tomaae** [comment]
You are right, I will do that.
