### ISSUE TITLE
Calculation of factor is null in energy converter, leading to way off energy consumption

### ISSUE THREAD

**Issue by tbowmo** [Koenkk/zigbee-herdsman-converters#8293]
After the latest update, the energy reported by my frient device is way off (factor 1000 too large). Debugging things, I found that the division/multiplication factor in the metering function in fromZigbee converter cannot be calculated as both divisor and multiplier is undefined, https://github.com/Koenkk/zigbee-herdsman-converters/blob/15835f6fa2e9658e6dbb1f1599c5ab88b7051622/src/converters/fromZigbee.ts#L745
which leads to a multiplication/division factor of 1 to be used on line 758 in the above file.

The multiplier / divisor is set in the frient device setup
https://github.com/Koenkk/zigbee-herdsman-converters/blob/15835f6fa2e9658e6dbb1f1599c5ab88b7051622/src/devices/frient.ts#L15

I remember that I suggested to make a fallback for divisor/multiplier to sensible values instead of undefined. It seems that it could be necessary after all, or is there something else wrong somewhere, that I fail to see?

**Comment by Koenkk** [comment]
Is it fixed after reconfiguring your device via the z2m frontend? (yellow refresh button)

**Comment by tbowmo** [comment]
Ok, that fixed it.. Had tried everything, that I could think of.
