### ISSUE TITLE
ZBBridge device (in zigbee router mode) needs external converter

### ISSUE THREAD

**Issue by alichaudry** [Koenkk/zigbee-herdsman-converters#8306]
I used [this](https://digiblur.com/2022/02/20/how-to-convert-the-sonoff-zigbee-bridge-into-a-router-repeater/) guide to flash my ZBBridge as a router. Pairing this device has Z2M picking it up but with an "unsupported device" flag. For that very reason, they also recommend a custom external converter:

> Zigbee2MQTT Users will need to download this [silabs.js](https://github.com/digiblur/Tasmota/blob/development/zigbee_router/silabs.js) file from Github, add it to their Z2M config folder, and add the custom converter to the configuration either via the GUI or YAML file.  This will not be necessary after the device is added into Z2M builds.

Give the insinuation in a 2022 blog post that this will eventually make it into Z2M builds, I was surprised to find out that I still (in late 2024) needed to manually include the `silabs.js` custom external converter, especially when I had been using it in ZHA for a few years now, and only very recently - when I decided to migrate to Z2M - ran into this issue.

1. What's the best way for me to get caught up to speed on making a PR to include this logic?
2. The [file](https://github.com/digiblur/Tasmota/blob/development/zigbee_router/silabs.js) from the blog post contains two devices: `UT-01` and `UT-02`. I was a bit surprised to see the latter [already included in this repo](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/devices/custom_devices_diy.ts#L706-L714). Not totally sure why someone would choose to include one but not the other, when presumably they took the logic from [the file in the repo](https://github.com/digiblur/Tasmota/blob/development/zigbee_router/silabs.js) referenced in the blog post.
3. There are minute differences in the model and description of `UT-02` in this repo and the other. I guess it matches on `zigbeeModel` so these other fields are modifiable?
4. Given that I'm new to this, I'm not totally sure I follow the logic [here](https://github.com/digiblur/Tasmota/blob/development/zigbee_router/silabs.js#L1-L6) re: `exposes`, `fz`, `tz`, `reporting`, and `e`. Also not sure why `extend` is commented out.
5. Using this manual external converter shows the device power icon as a question mark. Any way to update that via this config to flag it as a powered device?

<img width="1494" alt="image" src="https://github.com/user-attachments/assets/a0144615-5188-48fa-bcb9-d53c77af9fb2">

I appreciate any advice or direction on this!

**Comment by Koenkk** [comment]
1. You can do that by clicking here: https://github.com/Koenkk/zigbee-herdsman-converters/edit/master/src/devices/custom_devices_diy.ts#L706-L714
3. Yes, everything else can be modified
5. Use:

```
{
        zigbeeModel: ['UT-01'],
        model: 'UT-01',
        vendor: 'Custom devices (DiY)',
        description: 'EFR32MG21 Zigbee bridge router',
        extend: [forcePowerSource({powerSource: 'Mains (single phase)'})],
    }
```

**Comment by alichaudry** [comment]
Thank you @Koenkk; added my PR [here](https://github.com/Koenkk/zigbee-herdsman-converters/pull/8334). Let me know if I can assist in any other way (or if I need to make further updates in here).
