### ISSUE TITLE
Support for: TS0112

### ISSUE THREAD

**Issue by matlab22** [Koenkk/zigbee-herdsman-converters#840]
I don't have any permission to push to your branch. Could you add the following:

```
{
        zigbeeModel: ['TS0112'],
        model: 'TS0112',
        vendor: 'CR Smart Home',
        description: 'Power plug',
        supports: 'on/off',
        fromZigbee: [fz.on_off],
        toZigbee: [tz.on_off],
},
```

The socket looks like this:
https://www.moeshouse.com/collections/zigbee-3-0-socket
But I guess this is just an OEM supplier.
I bought it here:
https://www.aliexpress.com/item/4000181115109.html?spm=a2g0s.9042311.0.0.27424c4dwPgKlH

I set the vendor to CR Smart Home because you already have the TS0111 and I guess they are coming from the same supplier.

**Comment by matlab22** [comment]
hmm the switch is working fine but I get this warning
```
No converter available for 'TS0112' with cluster 'genBasic' and type 'attributeReport' and data '{"appVersion":67}'
```

**Comment by sjorge** [comment]
You can add `fz.ignore_basic_report` to fromZigbee

**Comment by Koenkk** [comment]
Added, thanks!
