### ISSUE TITLE
HuePowerOnBehavior converter not available.

### ISSUE THREAD

**Issue by Chrischi-** [Koenkk/zigbee-herdsman-converters#842]
the tzHuePowerOnBehavior converters are not available

929001953101 - Philips Hue White and Color Ambiance GU10 (Router)
```
zigbee2mqtt:error 2019-12-24T15:27:09: No converter available for 'hue_power_on_behavior' (recover)
zigbee2mqtt:error 2019-12-24T15:33:27: No converter available for 'hue_power_on_color_temperature' (0)
zigbee2mqtt:error 2019-12-24T15:37:30: No converter available for 'hue_power_on_brightness' (255)
```

**Comment by Koenkk** [comment]
Are you sure you don't use a custom zigbee-herdsman-converters? It seems to be there: https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L1238

**Comment by Chrischi-** [comment]
in the example above, i unfortunately specified the group as the target.

When I try to set the device one by one I get the following message:
```
zigbee2mqtt:debug 2019-12-27 15:23:12: Received MQTT message on 'zigbee2mqtt/k_r/set' with data '{"hue_power_on_behavior":"off","hue_power_on_brightness":255,"hue_power_on_color_temperature":1}'
zigbee2mqtt:debug 2019-12-27 15:23:12: Publishing 'set' 'hue_power_on_color_temperature' to 'k_r'
zigbee2mqtt:debug 2019-12-27 15:23:13: Publishing 'set' 'hue_power_on_brightness' to 'k_r'
zigbee2mqtt:debug 2019-12-27 15:23:13: Publishing 'set' 'hue_power_on_behavior' to 'k_r'
```

unfortunately the lamp does not accept the settings.

**Comment by Koenkk** [comment]
I believe you need to be on a recent firmware to use this feature, if not you have to update the bulbs via the hue hub

**Comment by Chrischi-** [comment]
i tried it also with the old GU10 that i used to develop the converter in the past

**Comment by Koenkk** [comment]
Strange, will check in my own setup after holidays.

**Comment by Koenkk** [comment]
Closing this in favour of https://github.com/Koenkk/zigbee2mqtt/issues/2439.
