### ISSUE TITLE
Iluminize 511.202 missing

### ISSUE THREAD

**Issue by sallazda** [Koenkk/zigbee-herdsman-converters#846]
Hello,

I add this (base on OSRAM plug) to control my Iluminize 511.202:
  {
        zigbeeModel: ['511.202'],
        model: '511.202',
        vendor: 'Iluminize',
        description: 'switch',
        supports: 'on/off',
        fromZigbee: [fz.on_off],
        toZigbee: [tz.on_off],
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(3);
            await bind(endpoint, coordinatorEndpoint, ['genOnOff']);
            await configureReporting.onOff(endpoint);
        },
    },

**Comment by Koenkk** [comment]
Added, thanks!
