### ISSUE TITLE
_TZE200_p3dbf6qs is AVATTO ME167 not AVATTO ME168

### ISSUE THREAD

**Issue by lecocqe** [Koenkk/zigbee-herdsman-converters#8474]
Hello,

searching for months for a solution, i found that _TZE200_p3dbf6qs is AVATTO ME 167 not 168.
I own 3x _TZE200_p3dbf6qs and i have problems since the very beginning of using it.

can you adapt tuya.ts with 2 times (1 comment) where _TZE200_p3dbf6qs refers to ME168, put ME167

Thank you in advance

Lecocqe

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now. Note that the dev branch currently contains **breaking changes**, see https://github.com/Koenkk/zigbee2mqtt/discussions/24198
