### ISSUE TITLE
Idea: support for generic devices

### ISSUE THREAD

**Issue by carldebilly** [Koenkk/zigbee-herdsman-converters#870]
I think it would be a good idea to implement generic support for common devices. When some well-known clusters are found, it could be use to very quickly support unknown devices instead of having to add a key for each of them.

Once done, you can add a "report this new device" feature to automatically create an issue here for supporting it with required information.

**Comment by allofmex** [comment]
Thought about something similar too.
I submitted a first change for zigbee-herdsman (https://github.com/Koenkk/zigbee-herdsman/pull/114#issuecomment-570059647). These changes may provide us with the needed feedback to write some routines to semi-automatically test for supported attributes.
