### ISSUE TITLE
Aqara ZNCZ12LM Support

### ISSUE THREAD

**Issue by faceoff34** [Koenkk/zigbee-herdsman-converters#875]
Would it be possible to support the US Version of the Aqara Plug (ZNCZ12LM)?  The device looks identical to ZNCZ03LM (which is already supported), I would think the commands would be the same.  The model of the device in the logs is 'lumi.plug.maus01'.  Thanks!

**Comment by faceoff34** [comment]
Below is the code I added to devices.js to make the outlet work.  Could you add this to your code if haven't already?  Thanks.

      { 
       zigbeeModel: ['lumi.plug.maus01'],
        model: 'ZNCZ12LM',
        description: 'Mi power plug ZigBee US',
        supports: 'on/off, power measurement',
        vendor: 'Xiaomi',
        fromZigbee: [
            fz.on_off, fz.xiaomi_power, fz.xiaomi_plug_state,
            fz.ignore_occupancy_report,
            fz.ignore_illuminance_report,
        ],
        toZigbee: [tz.on_off],
  },

**Comment by Koenkk** [comment]
added, thanks!
