### ISSUE TITLE
Add support for Tuya 3-gang switch (Zigbee model TS0003)

### ISSUE THREAD

**Issue by DarkMagic** [Koenkk/zigbee-herdsman-converters#887]
Real image of the switch:
![Real image of the switch](https://i.ibb.co/St6Cb5M/01b57d10220795a55220805e1398bfc8.jpg)

After set it in pairing mode (and set zigbee2mqtt's permit join to true), here is the log of zigbee2mqtt:
```
zigbee2mqtt:warn  2020-01-09 00:35:44: Received message from unsupported device with Zigbee model 'TS0003'
zigbee2mqtt:warn  2020-01-09 00:35:44: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
```
I found that zigbee model **TS0003** has already implemented by Zemismart's model.

After remove/comment-out Zemismart's code and add following code to the devices.js file, it works for my Tuya 3-gang switch.
```
    {
        zigbeeModel: ['TS0003'],
        model: 'GDKES-03TZXD',
        vendor: 'TUYATEC',
        description: 'Smart light switch - 3 gang with neutral wire',
        supports: 'on/off',
        fromZigbee: [fz.generic_state_multi_ep],
        toZigbee: [tz.on_off],
        endpoint: (device) => {
            return {'left': 1, 'center': 2, 'right': 3};
        },
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            await bind(device.getEndpoint(1), coordinatorEndpoint, ['genOnOff']);
            await bind(device.getEndpoint(2), coordinatorEndpoint, ['genOnOff']);
            await bind(device.getEndpoint(3), coordinatorEndpoint, ['genOnOff']);
        },
    },
```
Does zigbeeModel need to be unique in this devices.js file, everyone?

**Comment by Koenkk** [comment]
`zigbeeModel` indeed has to be unique, but as this is probably the same device and the definition is the same (just a different brand), it will already work.

**Comment by DarkMagic** [comment]
@Koenkk right, it have worked with Zemismart switch's definition, I checked again.
Only remain small warning / error that doesn't impact working state of the switch
```
zigbee2mqtt:warn  2020-01-09 22:43:23: No converter available for 'ZM-L03E-Z' with cluster 'genTime' and type 'read' and data '["localTime"]'
zigbee2mqtt:error 2020-01-10 05:30:10: Failed to execute LQI for 'tuya_switch_living_room_1'
```

**Comment by Koenkk** [comment]
- No converter available can be ignored for that message, (not interesting to expose to MQTT) it's also already handled in zigbee-herdsman.
- It could be that this device does not support a link quality (LQI) scan, not fixable from the zigbee2mqtt side.

**Comment by DarkMagic** [comment]
After all, the Zemismart switch's definition not work with with this Tuya's device (TS0003).
I ended-up with work-around as in my question.

Close this issue.
