### ISSUE TITLE
Add support for Paulmann Pendulum light Aptare (500.45 Controller)

### ISSUE THREAD

**Issue by bifi2090** [Koenkk/zigbee-herdsman-converters#890]
Hey guys,

please add the following Converter for "Paulmann Pendulum light Aptare" to "devices.js".
It has an inbuild Led-Stripe Driver (model 500.45) which seems allmost to be configured with the name 'Dimmable light' (vendor: Paulmann). But after pairing with the coordinator it shows up as zigbee model: '500.45 '. It can be used with the regular converter from the 'Dimmable light ' configuration, but needs to be declared separtely as written below:

![79815mi10_600x600](https://user-images.githubusercontent.com/58722598/72100702-60da1b80-3323-11ea-94ab-3eb094e4ae55.jpg)
{
        zigbeeModel: ['500.45'],
        model: '50045',
        vendor: 'Paulmann',
        description: 'SmartHome Zigbee Pendulum Light Aptare',
        extend: generic.light_onoff_brightness,
},

Thx.

**Comment by Koenkk** [comment]
added, thanks!

**Comment by sjorge** [comment]
@bifi2090 I assume you own this (and maybe other) Paulmann devices?
Could you perhaps update the table https://www.zigbee2mqtt.io/information/report.html#support to add Paulmann
