### ISSUE TITLE
Action attribute generates 2 mqtt messages

### ISSUE THREAD

**Issue by cemonneau** [Koenkk/zigbee-herdsman-converters#899]
When a converter returns an "action" attribute (see Legrand devices and others) like 
```
return {action:"identify"};
```
it generates 2 mqtt messages, the first looking like 
```
{"state":"OFF","power":0,"linkquality":132,"action":"identify"}
```
and the second contains an empty action like
```
{"state":"OFF","power":0,"linkquality":132,"action":""}
```

No other attributes is modified.
Latest version of everything (zigbee2mqtt, herdsman).
I'm not at ease with all the source code yet, if I find the source I will patch it if someone didn't do it before

**Comment by Koenkk** [comment]
This is expected, see https://github.com/Koenkk/zigbee2mqtt/issues/1155#issuecomment-467094619

Tldr; required for home assistant integration
