### ISSUE TITLE
Devices assets database

### ISSUE THREAD

**Issue by kirovilya** [Koenkk/zigbee-herdsman-converters#914]
I propose making a devices database based on this repository, not just a set of converters and code.
For example, add images and comments about device features (pairing channels, binding options, links to resources).
The source can be from zigbee2mqtt.io. Part of the data from this resource can be transferred to the database.
Or come up with a separate repository where, by the model code of the device, you could get information for display (picture, description, links).

Currentrly I am collect pictures for displaying devices in my project (iobroker.zigbee), although I could do it centrally.

**Comment by allofmex** [comment]
Do you mean something like https://www.zigbee2mqtt.io/information/supported_devices.html but with programmatically readable content? To have for example device pictures that can be used by all projects?

**Comment by kirovilya** [comment]
@allofmex yes!

**Comment by Koenkk** [comment]
The zigbee2mqtt supported devices page and device specific pages are already programmatically accessible (everything is generated), also the pictures.

Source: https://github.com/Koenkk/zigbee2mqtt.io/tree/master/docgen

Note that some docs are zigbee2mqtt specific, therefore this cannot be put in zigbee-herdsman-converters.
