### ISSUE TITLE
Double Click and Long-Press on WXCJKG11LM

### ISSUE THREAD

**Issue by benny000004** [Koenkk/zigbee-herdsman-converters#918]
Double Click and Long-Press Events are not yet implemented for WXCJKG11LM. According to Aqara, it should also work with the two button Opple Switch. Can someone doublecheck, if this is correct?

Also the Double-Click and Long-Press events are only implemented for on the 4 and 6 button switches on buttons 3+, not for buttons one and two.

EDIT: Here are the bindings when directly connected to a lamp, https://www.zigbee2mqtt.io/devices/WXCJKG11LM.html

**Comment by uncle-fed** [comment]
I can confirm that unfortunately, the double-click and the long-press events are not recognized for the two button Opple switch (the 4 button Opple now works pefectly with zigbee2mqtt 1.11.0 thanks to @kirovilya ). 

Also, current implementation generates 4 messages (exactly the same 4 messages) for a single button click, instead of a single message which does not occur for 4 button switch.  :-(

**Comment by benny000004** [comment]
With newest converters and a reconnect of the switches, everything works for me now. Double and Triple Click as well as Long Press. On 3 band as well as 1 band switches.

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by uncle-fed** [comment]
Are you using development branch?
I installed latest released zigbee2mqtt 1.11.0 and tried it with brand new Opple 2 button switch that was never used before. I get the behaviour as described in my previous message :-(

**Comment by benny000004** [comment]
I'm using the the herdsman version 12.0.33 and converters 0.12.56 which came with the ZigBee 1.0.3 Adapter version for ioBroker Home Automation System. There i have no problems since the Opple Cluster got refreshed. I don't use zigbee2mqtt but according to the changelog it should also work with the newest version.
________________________________

**Comment by uncle-fed** [comment]
I followed your earlier advice and paired same switch once more and now it works fine!
Thanks!
Still weird that the very first time it was misbehaving so strangely, even though from the logs it looked like it paired well.
