### ISSUE TITLE
Eurotronic Spirit always full power

### ISSUE THREAD

**Issue by joshwapohlmann** [Koenkk/zigbee-herdsman-converters#947]
Hello,
I recently updated Zigbee2mqtt on my HomeAssistant installation and saw, that you made "improvements" to the Eurotronic implementation in #817. While I **really** appreciate all the time and work spend on this awesome open source project (thanks for that!) the recent update broke my setup and I'm not sure if it's a bug or a feature.

Whenever I send "heat" to the device
```
zigbee2mqtt/0x00158d0003c4731b/set/system_mode :
heat
```

It will first respond as intended:
```
zigbee2mqtt/0x00158d0003c4731b:
{
    "local_temperature": 23.5,
    "occupied_heating_setpoint": 22, <--
    "unoccupied_heating_setpoint": 16,
    "pi_heating_demand": 2,
    "linkquality": 52,
    "current_heating_setpoint": 22,
    "eurotronic_error_status": 0,
    "eurotronic_system_mode": 5,
    "system_mode": "heat",
    "battery": 100,
    "eurotronic_host_flags": {
        "mirror_display": false,
        "boost": true,
        "window_open": false,
        "child_protection": false
    }
}
```

But then immediatly dials up the maximum temperatur to 30 degrees celcius.
```
zigbee2mqtt/0x00158d0003c4731b um 9:53 :
{
    "local_temperature": 24,
    **"occupied_heating_setpoint": 30,  <---
    "unoccupied_heating_setpoint": 16,
    "pi_heating_demand": 2,
    "linkquality": 52,
    "current_heating_setpoint": 22,
    "eurotronic_error_status": 0,
    "eurotronic_system_mode": 5,
    "system_mode": "heat",
    "battery": 100,
    "eurotronic_host_flags": {
        "mirror_display": false,
        "boost": true,
        "window_open": false,
        "child_protection": false
    }
}
```

Before that update, it just returned to heat the room to the previous set temperature and I just had to control on/off state. Now, I can't. Any ideas? Did the changes @sjorge made cause this?

**Comment by sjorge** [comment]
Yes, as per https://github.com/Koenkk/zigbee-herdsman-converters/issues/788

auto and heat were swapped, old behavior:
heat -> auto regulate temperature to set point
auto -> boost (max open)

new behavior:
auto -> auto regulate temperature to set point
heat -> boost (max open)

**Comment by joshwapohlmann** [comment]
thanks @sjorge for pointing that out. Didn't understood this before. I will test this later and close the issue then.

**Comment by sjorge** [comment]
The docs were also update, but perhaps the behavior is not super clear. Suggestions welcome:
https://www.zigbee2mqtt.io/devices/SPZB0001.html

**Comment by joshwapohlmann** [comment]
The docs are clear, I just didn't look there first. Great work. Thank you!
