### ISSUE TITLE
toZigbee - light_brightness_move line 248

### ISSUE THREAD

**Issue by fnfid** [Koenkk/zigbee-herdsman-converters#948]
Hi, as brightness_move seem to use always 'moveWithOnOff' it would be great to optify this to 'move' by any option set, as this easyfies to mimick the original IKEA remote sending 'move' natively. 
As  I only need 'move' for now i included 'sed -i s/moveWithOnOff/move/ toZigbee.js ' in my updade script as a workaround, works fine so far.
Maybe  something like {"moveWithOnOff": true} with default true for compatibility reasons can add this functionality.

**Comment by Koenkk** [comment]
It should be `move` from the start, fixed it thanks!
