### ISSUE TITLE
Model: ICZB-KPD18S provides "battery_percentage_remaining"

### ISSUE THREAD

**Issue by reinhard089** [Koenkk/zigbee-herdsman-converters#952]
hai,
my: iCasa ICZB-KPD18S
provides: battery_percentage_remaining
so i get errors in node-red.

please add: fz.battery_percentage_remaining
to: fromZigbee: [fz.scenes_recall_click, fz.genOnOff_cmdOn, fz.genOnOff_cmdOff],
within the devices.js "zigbeeModel: ['ICZB-KPD18S']"

regards
reinhard

**Comment by Koenkk** [comment]
Added, will update zigbee2mqtt later today.

**Comment by reinhard089** [comment]
thank you :-D 👍 
nice regards
reinhard
