### ISSUE TITLE
Stuck with adding new device, unable to edit devices.js

### ISSUE THREAD

**Issue by JHurk** [Koenkk/zigbee-herdsman-converters#958]
I am really in the dark here :).
I installed zigbee2MQTT and it is up and running, just want to add my first device.
This device is unsupported (Robb Zigbee Dimmer Rob_200-014-0) so now I want to add the device to the devices.js. 

I followed the guide but get stuck on this step:
----------
Now add the volumes to the Docker container by adding the following to your docker run command.:

-v /opt/zigbee-herdsman-converters:/app/node_modules/zigbee-herdsman-converters -v /opt/homeassistant.js:/app/lib/extension/homeassistant.js

Now you can start modifying e.g. /opt/zigbee-herdsman-converters/devices.js. Note that after each modification you need to restart the container for the changes to take effect.
-----------

No matter how I try, I can not get this step to work so the volume (and devices.js) does not show in File Station (Synology DSM 6). So now I am unable to edit the devices.js and stuck.
I am to noob to edit the file through ssh, but I am able to look in opt/ to see the file is there.

Could you please help me out, either by pointing out how to get the devices.js visible in File Station. Or by adding support for the device Rob_200-014-0 (https://www.robbshop.nl/zigbee-draaidimmer-robb-smarrt). Another dimmer device from Robbshop is supported so I guess adding this one is quite similar.

**Setup:**
DSM 6
zigbee-herdsman-converters is in the opt/ folder
Zigbee2MQTT in Docker on DSM (in log I can see it is working and 1 device is joined, unsupported)
Zigbee2MQTTAssistant in Docker on DSM
Zigbee2MQTT Domoticz plugin
Domoticz installed on Synology

Device which is similar to my device:
 {
        zigbeeModel: ['ROB_200-004-0'],
        model: 'ROB_200-004-0',
        vendor: 'ROBB',
        description: 'ZigBee AC phase-cut dimmer',
        extend: generic.light_onoff_brightness,
        meta: {configureKey: 2},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            await bind(endpoint, coordinatorEndpoint, ['genOnOff', 'genLevelCtrl']);
            await configureReporting.onOff(endpoint);
        },
    },

So I guess my device should be something like this:
 {
        zigbeeModel: ['ROB_200-014-0'],
        model: 'ROB_200-014-0',
        vendor: 'ROBB',
        description: 'ZigBee AC phase-cut  rotary dimmer',
        extend: generic.light_onoff_brightness,
        meta: {configureKey: 2},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            await bind(endpoint, coordinatorEndpoint, ['genOnOff', 'genLevelCtrl']);
            await configureReporting.onOff(endpoint);
        },
    },

**Comment by Koenkk** [comment]
Added, supported in the latest zigbee2qmtt dev branch now.

**Comment by JHurk** [comment]
Wow, thanks for the quick help. Unfortunately I am not really there yet.
I got the latest-dev version up and running, but I have trouble resetting the device, so I tried adding the devices.js from the dev-branche to my setup where I use the devices.js from opt/zigbee-herdsman-converters

I copied the devices.js but the device still comes up as unsupported.
Here are the logs;

debug 2020-01-31 22:43:52: Received MQTT message on 'zigbee2mqtt/bridge/config/devices' with data ''
info  2020-01-31 22:43:52: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"devices","message":[{"ieeeAddr":"0x00124b001cd47114","type":"Coordinator","networkAddress":0,"friendly_name":"Coordinator","softwareBuildID":"zStack12","dateCode":"20190608","lastSeen":1580507032018}]}'
info  2020-01-31 22:43:57: Device 'Dimmer Woonkamer voor' joined
info  2020-01-31 22:43:57: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":{"friendly_name":"Dimmer Woonkamer voor"}}'
info  2020-01-31 22:43:57: Starting interview of 'Dimmer Woonkamer voor'
info  2020-01-31 22:43:57: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"Dimmer Woonkamer voor"}}'
debug 2020-01-31 22:43:57: Received MQTT message on 'zigbee2mqtt/bridge/config/devices' with data ''
info  2020-01-31 22:43:57: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"devices","message":[{"ieeeAddr":"0x00124b001cd47114","type":"Coordinator","networkAddress":0,"friendly_name":"Coordinator","softwareBuildID":"zStack12","dateCode":"20190608","lastSeen":1580507037529},{"ieeeAddr":"0xec1bbdfffe7f3e4f","networkAddress":57116,"friendly_name":"Dimmer Woonkamer voor","lastSeen":1580507037512}]}'
debug 2020-01-31 22:43:58: Device 'Dimmer Woonkamer voor' announced itself
debug 2020-01-31 22:43:58: Received Zigbee message from 'Dimmer Woonkamer voor', type 'readResponse', cluster 'genBasic', data '{"modelId":"ROB_200-014-0","manufacturerName":"ROBB smarrt","powerSource":1}' from endpoint 1 with groupID 0
warn  2020-01-31 22:43:58: Received message from unsupported device with Zigbee model 'ROB_200-014-0'
warn  2020-01-31 22:43:58: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
debug 2020-01-31 22:43:58: Received Zigbee message from 'Dimmer Woonkamer voor', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3,"appVersion":0,"stackVersion":0}' from endpoint 1 with groupID 0
warn  2020-01-31 22:43:58: Received message from unsupported device with Zigbee model 'ROB_200-014-0'
warn  2020-01-31 22:43:58: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
debug 2020-01-31 22:43:58: Received Zigbee message from 'Dimmer Woonkamer voor', type 'readResponse', cluster 'genBasic', data '{"hwVersion":0,"dateCode":"NULL","swBuildId":"2.5.3_r47"}' from endpoint 1 with groupID 0
warn  2020-01-31 22:43:58: Received message from unsupported device with Zigbee model 'ROB_200-014-0'
warn  2020-01-31 22:43:58: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
info  2020-01-31 22:43:58: Successfully interviewed 'Dimmer Woonkamer voor', device has successfully been paired
warn  2020-01-31 22:43:58: Device 'Dimmer Woonkamer voor' with Zigbee model 'ROB_200-014-0' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
info  2020-01-31 22:43:58: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"Dimmer Woonkamer voor","supported":false}}'

**Comment by Koenkk** [comment]
Doesn't look like correctly copied `devices.js`, note that you don't need to repair devices when going to the dev branch (or switching back to master). For the sake of simplicity just  stay on the dev branch for now. Instructions how to correctly switch to the dev branch: https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html

**Comment by JHurk** [comment]
Dev-branche doesn't work either. I just tried re-pairing it with the dev-branch container and got this log:

info  2020-01-31 21:57:32: Device '0xec1bbdfffe7f3e4f' joined
info  2020-01-31 21:57:32: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":{"friendly_name":"0xec1bbdfffe7f3e4f"}}'
info  2020-01-31 21:57:32: Starting interview of '0xec1bbdfffe7f3e4f'
info  2020-01-31 21:57:32: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"0xec1bbdfffe7f3e4f"}}'
info  2020-01-31 21:57:32: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"devices","message":[{"ieeeAddr":"0x00124b001cd47114","type":"Coordinator","networkAddress":0,"friendly_name":"Coordinator","softwareBuildID":"zStack12","dateCode":"20190608","lastSeen":1580507852658},{"ieeeAddr":"0xec1bbdfffe7f3e4f","networkAddress":21550,"friendly_name":"0xec1bbdfffe7f3e4f","lastSeen":1580507852611}]}'
warn  2020-01-31 21:57:43: Received message from unsupported device with Zigbee model 'ROB_200-014-0'
warn  2020-01-31 21:57:43: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
warn  2020-01-31 21:57:43: Received message from unsupported device with Zigbee model 'ROB_200-014-0'
warn  2020-01-31 21:57:43: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
warn  2020-01-31 21:57:43: Received message from unsupported device with Zigbee model 'ROB_200-014-0'
warn  2020-01-31 21:57:43: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
warn  2020-01-31 21:57:43: Received message from unsupported device with Zigbee model 'ROB_200-014-0'
warn  2020-01-31 21:57:43: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
warn  2020-01-31 21:57:43: Received message from unsupported device with Zigbee model 'ROB_200-014-0'
warn  2020-01-31 21:57:43: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
info  2020-01-31 21:57:43: Successfully interviewed '0xec1bbdfffe7f3e4f', device has successfully been paired
warn  2020-01-31 21:57:43: Device '0xec1bbdfffe7f3e4f' with Zigbee model 'ROB_200-014-0' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
info  2020-01-31 21:57:43: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0xec1bbdfffe7f3e4f","supported":false}}'

**Comment by Koenkk** [comment]
What is in devices.js now? (`/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/devices.js`) Post it on pastebin.com and link it here.

**Comment by JHurk** [comment]
Sorry, in my /opt/ folder I only have /zigbee-herdsman-converters/ and /containerd/, both folders will not bring me to zigbee2mqtt folder.
It is Docker on a Synology NAS, have no idea where the files are stored of each container.

**Comment by Koenkk** [comment]
As you are using docker, switch to the `latest-dev` tag but make sure that you have no `zigbee-herdsman-converters` volumes mapped.

**Comment by JHurk** [comment]
The last log-file was from the latest-dev and with that container I have not mapped the volumes (only the data folders are 'mapped').
<img width="1522" alt="Schermafbeelding 2019-05-28 om 15 28 50" src="https://user-images.githubusercontent.com/7835370/73579909-1eb87b80-4484-11ea-8b2d-d7887ada2825.png">

**Comment by JHurk** [comment]
I am on the latest-dev and the volumes are not mapped, I am sure about that:
<img width="1545" alt="Schermafbeelding 2020-01-31 om 23 49 56" src="https://user-images.githubusercontent.com/7835370/73580024-722ac980-4484-11ea-8852-92d1fff69c97.png">

**Comment by JHurk** [comment]
I deleted all containers related to Zigbee2MQTT and did a fresh install of the dev-branch. And now I have a dimmer which is being supported. 

Tomorrow I will try to make it work with Domoticz and Homebridge.
But the dimmer is supported now, so I think I will get there. Thanks for your help!

**Comment by Koenkk** [comment]
Great, as that is not directly part of zigbee2mqtt I will close this.
