### ISSUE TITLE
Philips Hue Smartplug - power_on_behaviour

### ISSUE THREAD

**Issue by fnfid** [Koenkk/zigbee-herdsman-converters#968]
The Philips Hue Smart Plug from 'devices.js' line 1826 (and i guess the other one at line 1841 as well) do also support the 'hue_power_on_behaviour', as defined in 'devices.js' line 411, but as statet in line 1832 currently its not supported.

Guess its only a small change, unfortunally failed to suggest a more proper solution, if anyone can, I'll be happy and thankful!

**Comment by Koenkk** [comment]
Added, thanks!

**Comment by RedNo7** [comment]
Hi - is this going to be implemented?
