### ISSUE TITLE
How to configure reporting for device?

### ISSUE THREAD

**Issue by Kryzek** [Koenkk/zigbee-herdsman-converters#970]
I have this Airam remote (https://www.zigbee2mqtt.io/devices/AIRAM-CTR.U.html) which does not report anything and with availability it will get marked as offline. What kind of configuration I would need to in devices.js? Currently it has this  https://github.com/Koenkk/zigbee-herdsman-converters/blob/e92fefb3d164852c33f4ccf2ef63669b09b9c613/devices.js#L5038-L5050 - it does not have configure: -rows, and I do not figure out what to even try out (I've gotten only configure failed-messages so far) :)

Database entry for this device:
```{"id":15,"type":"EndDevice","ieeeAddr":"0x00158d0001b70237","nwkAddr":34015,"manufId":4456,"manufName":"C046","powerSource":"Battery","modelId":"ZBT-Remote-EU-DIMV1A2","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":2096,"inClusterList":[0,4096,3],"outClusterList":[3,4,5,6,8,4096,25],"clusters":{"genBasic":{"attributes":{"modelId":"ZBT-Remote-EU-DIMV1A2","manufacturerName":"C046","powerSource":3,"zclVersion":2,"appVersion":1,"stackVersion":1,"hwVersion":1,"dateCode":"20171211-367","swBuildId":"2.1"}}},"binds":[]}},"appVersion":1,"stackVersion":1,"hwVersion":1,"dateCode":"20171211-367","swBuildId":"2.1","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1580481776945}```

**Comment by Koenkk** [comment]
It makes sense to setup battery reporting for this device, example: https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L1241

**Comment by sjorge** [comment]
@Koenkk a lot of the devices have fz.ignore_basic_report, but would those still trigger a update of the last seen? If not, maybe they should.

**Comment by Koenkk** [comment]
This will trigger an update of last seen.

**Comment by Kryzek** [comment]
With https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L1241-1245 added to device configure-section I get error:
```
 Failed to configure '0x00158d0001b6beee', attempt 1 (Error: ConfigureReporting 0x00158d0001b6beee/1 genPowerCfg([{"attribute":"batteryPercentageRemaining","minimumReportInterval":3600,"maximumReportInterval":62000,"reportableChange":0}], {"timeout":10000,"defaultResponseTimeout":15000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Timeout - 56099 - 1 - 7 - 1 - 7 after 10000ms)
    at Endpoint.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:316:23)
    at Generator.throw (<anonymous>)
    at rejected (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65))
```

I tried same thing with `await configureReporting.batteryVoltage(endpoint);`

And this results into:
```
Failed to configure '0x00158d0001b6beee', attempt 2 (Error: ConfigureReporting 0x00158d0001b6beee/1 genPowerCfg([{"attribute":"batteryVoltage","minimumReportInterval":3600,"maximumReportInterval":62000,"reportableChange":0}], {"timeout":10000,"defaultResponseTimeout":15000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Timeout - 28437 - 1 - 2 - 1 - 7 after 10000ms)
    at Endpoint.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:316:23)
    at Generator.throw (<anonymous>)
    at rejected (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65))
```

Is there something else I could try out?

**Comment by Koenkk** [comment]
Make sure to wakeup the device while the configure is happening (by pressing some buttons on it).

**Comment by Kryzek** [comment]
I kept pressing buttons and device was awake. Maybe this device just cannot be configured. It also has static groupid which I cannot change with binding/unbinding and I got two of these devices and both are with same groupid.

**Comment by Koenkk** [comment]
Probably yes, in that case blacklist it from being checked in device availability

**Comment by Kryzek** [comment]
I think I'll just ditch those remotes since they are not co-operating with me at all :)

But in short: to get battery information reported periodically, for battery powered devices we should use something like:

```
    meta: {configureKey: 1},
    configure: async (device, coordinatorEndpoint) => {
        const endpoint = device.getEndpoint(1);
        await bind(endpoint, coordinatorEndpoint, ['genPowerCfg']);
        await configureReporting.batteryPercentageRemaining(endpoint);
        and/or:
        await configureReporting.batteryVoltage(endpoint);
    },
```
This part is not covered in https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
And if device does not respond to either of these it will not probably provide such information?

**Comment by Koenkk** [comment]
Yes exactly, if they don't respond they probably don't provide. Exception is e.g. Xiaomi battery powered devices which do this via a Xiaomi specific message on an interval basis.

**Comment by Kryzek** [comment]
All right, thanks for the information once again!
