### ISSUE TITLE
Changing minimumReportInterval 

### ISSUE THREAD

**Issue by dersparkiie** [Koenkk/zigbee-herdsman-converters#971]
I've tried to change the minimumReportInterval to 10 seconds without any result. 
Isn'n it possible to set a higher interval?

https://github.com/Koenkk/zigbee-herdsman-converters/commit/e20a3c77b14e8455a456c67e6fcd8b6783b3bbf3

**Comment by coolguymatt** [comment]
Having this be something we can customize easily would be great - I have a few plugs that I do not actually care what the energy reading is, so being able to set it to 60 seconds or higher would be awesome.

**Comment by dersparkiie** [comment]
No ideas?
Changing the minimumReportInterval from 1 to 5 did really change the number of messages.
Changing to 10, 20, 60 didn't make any visible effect? https://github.com/Koenkk/zigbee-herdsman-converters/commit/e20a3c77b14e8455a456c67e6fcd8b6783b3bbf3
