### ISSUE TITLE
OTA updates over HTTPS (Ikea Tradfri)

### ISSUE THREAD

**Issue by dfsx1** [Koenkk/zigbee-herdsman-converters#977]
After testing the new OTA feature (nice work btw!) I noticed that the Ikea Tradfri firmware is downloaded over insecure http protocol:
http://fw.ota.homesmart.ikea.net/feed/version_info.json

Can you fetch the secure https version instead?
https://fw.ota.homesmart.ikea.net/feed/version_info.json

Unfortunately the binaries inside Ikea's json file always point to http, even if requested over https. 
I'll submit a vulnerability report directly to them.
Until they fix this, I think we can do some string.replace() magic in /ota/tradfri.js?

Yes I know the binaries are signed by the vendor, but still, non-HTTPS anno 2020? 🥺
Ikea's SSL certificate works perfectly fine, so I think we should just use it 🤷

**Comment by Koenkk** [comment]
Merged, thanks!

**Comment by JimboJ** [comment]
I think OTA no longer functions for IKEA devices, I've done a little investigation. The secure URL appears not to work correctly, the non-secure version does function correctly. 

http://fw.ota.homesmart.ikea.net/feed/version_info.json - Works
https://fw.ota.homesmart.ikea.net/feed/version_info.json - Fails

Firmwares however can be downloaded from either HTTP or HTTPS e.g
http://fw.ota.homesmart.ikea.net/global/GW1.0/01.19.032/bin/10054470-TRADFRI-shortcut-button-2.3.080.ota.ota.signed 
https://fw.ota.homesmart.ikea.net/global/GW1.0/01.19.032/bin/10054470-TRADFRI-shortcut-button-2.3.080.ota.ota.signed

**Comment by JimboJ** [comment]
Thankyou, my mistake
