### ISSUE TITLE
ZEN Device has wrong endpoint(3)

### ISSUE THREAD

**Issue by peter1960** [Koenkk/zigbee-herdsman-converters#984]
When using the ZEN thermostat it will fail after pairing with 'Cannot read property 'bind' of undefined :"

In devices.js if I change the getEndpoint to 1 it works. From what I can see from looking at others in the file it can only be 1 and 3 is a mistake?

meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = **device.getEndpoint(3);**
            const binds = [
                'genBasic', 'genIdentify', 'genPowerCfg', 'genTime', 'hvacThermostat', 'hvacUserInterfaceCfg',
            ];
            await bind(endpoint, coordinatorEndpoint, binds);
            await configureReporting.thermostatTemperature(endpoint);
        },

**Comment by Koenkk** [comment]
Probably not a mistake, it can differ between different software version of this device.

Fixed: we will now pick endpoint 1 if 3 doesn't exist.
